# module: gshare.common_util

import MConfig
import base64
import consts
import formula
import game_const_data
import mail_multi_data
import re
import six2
import struct
import sys
import visible_limit_data

COMPONENT: str = 'Client'
OFFICIAL_HEAD_URLS: tuple = ()
THIRD_PARTY_PREFIX: str = 'http...'

def CheckDistance(pos1, pos2, dis): ...
def CheckHeadUrl(url): ...
def CheckMayShowId(value_str): ...
def CheckNameLengthValid(name, max_len=6): ...
def CheckNameValid(name): ...
def DecodeTopic(topic): ...
def DoBitMark(int_mask, index): ...
def EncodeTopic(topic_key, guid): ...
def GetCharCount(text, cn_word_len=2): ...
def GetHostnumByAvatarId(avatar_id): ...
def GetNGPMailId(avatar): ...
def GetNameLength(name): ...
def GetNameRichText(name, anchor): ...
def GetNameRichTextNew(name, player_identity_dict): ...
def HasBitMark(int_mask, index): ...
def HasEmoji(name): ...
def IsBaseLatern(uchar): ...
def IsCHJPEN(content): ...
def IsCharAlpha(uchar): ...
def IsCharCH(uchar): ...
def IsCharJP(uchar): ...
def IsCharNum(uchar): ...
def IsEnableDataVisible(avatar, visible_limit_id): ...
def IsGuid(g): ...
def IsNameChinese(name): ...
def IsNameHasChinese(name): ...
def IsSymbols(uchar): ...
def RaiseCatchError(msg=''): ...

