# module: gshare.decorators

import Timer
import consts
import datetime
import functools
import time

call_until_player_ready: partial = functools.partial(<class 'gshare.decorators.call_until'>, <function <lambda> at 0x7040f72ac0>)

class FrameLimit(object):
class IntervalCall(object):
class LimitCall(object):
class LimitCallTimes(object):
class MergeCall(object):
class MergeCallPrevious(object):
class cached_property(object):
class call_until(object):
class partial(object):
    args: member_descriptor = <member 'args' of 'functools.partial' objects>
    func: member_descriptor = <member 'func' of 'functools.partial' objects>
    keywords: member_descriptor = <member 'keywords' of 'functools.partial' objects>


def DelayCall(delay=0): ...
def DelayCallWithKeyFunc(delay=0, delay_key_func=None): ...
def HallDelayCall(delay=0): ...
def ProfileFunc(func): ...
def SpaceCachingSkip(func): ...
def TimerCb(interval=-1, timer_name=None, is_repeat=False, stop_cond_func=None): ...
def TimerCbUINode(interval=-1, timer_name=None, is_repeat=False, stop_cond_func=None): ...
def VisibleCall(is_visible=True): ...
def _cb_once(self, func, timer_name, args, kwargs): ...
def _cb_repeat(self, func, timer_name, stop_cond_func, args, kwargs): ...
def _inner_ret(func, timer_name, is_repeat, interval, _cb): ...
def _start_timer(self, interval, _timer_name, is_repeat, cb, args, kwargs): ...
def _stop_timer(self, timer_name): ...
def cache_then_run_after(delay=0): ...
def destroyed_protect(func): ...
def interval_call(interval): ...
def log_invoke(func): ...
def rpc_frequency_limit(cd, prompt=0, limit=1): ...
def run_once_in_a_frame(func): ...
def space_needed(func): ...
def with_tag(*args): ...

