# module: gshare.utils

import base64
import functools
import inspect
import json
import operator
import six2
import sys
import time
import weakref
import zlib

COMPONENT: str = 'Client'
get_ident: builtin_function_or_method = <built-in function get_ident>

class BitList(CustomIntListType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: type = <class 'int'>
    append: method_descriptor = <method 'append' of 'area_list' objects>
    assign: method_descriptor = <method 'assign' of 'area_list' objects>
    clear: method_descriptor = <method 'clear' of 'area_list' objects>
    copy: method_descriptor = <method 'copy' of 'area_list' objects>
    delete: method_descriptor = <method 'delete' of 'area_list' objects>
    extend: method_descriptor = <method 'extend' of 'area_list' objects>
    get: method_descriptor = <method 'get' of 'area_list' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_list' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_list' objects>
    insert: method_descriptor = <method 'insert' of 'area_list' objects>
    list: method_descriptor = <method 'list' of 'area_list' objects>
    pop: method_descriptor = <method 'pop' of 'area_list' objects>
    size: method_descriptor = <method 'size' of 'area_list' objects>
    slice: method_descriptor = <method 'slice' of 'area_list' objects>
    sorted: method_descriptor = <method 'sorted' of 'area_list' objects>
    update: method_descriptor = <method 'update' of 'area_list' objects>

    def CheckBit(self, n): ...
    def CleanBits(self): ...
    def ClearBit(self, n): ...
    def GetBits(self): ...
    def SetBit(self, n): ...
    def on_update(self, index, old): ...

class BitListMap(CustomMapType):
    INTERVAL: int = 1000
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomListTypeMetaClass = <class 'gshare.utils.BitList'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def CheckBit(self, n): ...
    def ClearBit(self, n): ...
    def GetBits(self): ...
    def SetBit(self, n): ...
    def _initProperty(self, data): ...
    def _on_update_bit(self, i, bit): ...
    def items(self): ...
    def keys(self): ...
    def on_init(self, parent): ...
    def on_setattr(self, key, old, new): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class BitListOp(object):
    INT_BIT_LEN: int = 63

    def CheckBit(value, n): ...
    def CleanBits(value): ...
    def ClearBit(value, n): ...
    def GetBits(value): ...
    def GetIdx(n): ...
    def SetBit(value, n): ...

class Cache(OrderedDict):
    _OrderedDict__marker: object = <object object at 0x702c5c4b30>
    get: method_descriptor = <method 'get' of 'dict' objects>

    def _OrderedDict__update(self, other=(), /, **kwds): ...
    def clean(self): ...
    def cleantimeout(self, now, count=1000): ...
    def clear(self): ...
    def copy(self): ...
    def fromkeys(iterable, value=None): ...
    def front_item(self): ...
    def front_key(self): ...
    def front_value(self): ...
    def getdatas(self): ...
    def invalid(self, key): ...
    def items(self): ...
    def iteritems(self): yield ...
    def iterkeys(self): ...
    def itervalues(self): yield ...
    def keys(self): ...
    def move_to_end(self, key, last=True): ...
    def pop(self, key, default=<object object at 0x702c5c4b30>): ...
    def popitem(self, last=True): ...
    def select(self, key, timeout=None): ...
    def setdefault(self, key, default=None): ...
    def update(self, key, value, timeout=0): ...
    def values(self): ...

class CustomIntListType(CustomListType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: type = <class 'int'>
    append: method_descriptor = <method 'append' of 'area_list' objects>
    assign: method_descriptor = <method 'assign' of 'area_list' objects>
    clear: method_descriptor = <method 'clear' of 'area_list' objects>
    copy: method_descriptor = <method 'copy' of 'area_list' objects>
    delete: method_descriptor = <method 'delete' of 'area_list' objects>
    extend: method_descriptor = <method 'extend' of 'area_list' objects>
    get: method_descriptor = <method 'get' of 'area_list' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_list' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_list' objects>
    insert: method_descriptor = <method 'insert' of 'area_list' objects>
    list: method_descriptor = <method 'list' of 'area_list' objects>
    pop: method_descriptor = <method 'pop' of 'area_list' objects>
    size: method_descriptor = <method 'size' of 'area_list' objects>
    slice: method_descriptor = <method 'slice' of 'area_list' objects>
    sorted: method_descriptor = <method 'sorted' of 'area_list' objects>
    update: method_descriptor = <method 'update' of 'area_list' objects>

class CustomMapType(area_map):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class Dispatcher(object):
    record: member_descriptor = <member 'record' of 'Dispatcher' objects>

    def dispatch(self, tag, *args, **kwargs): ...
    def register(self, tag, callback): ...
    def release(self): ...
    def unregister(self, tag, callback): ...
    def unregister_tag(self, tag): ...

class EnumMetaclass(type):
    mro: method_descriptor = <method 'mro' of 'type' objects>

class Functor(object):
class List2D(list):
    clear: method_descriptor = <method 'clear' of 'list' objects>
    copy: method_descriptor = <method 'copy' of 'list' objects>
    count: method_descriptor = <method 'count' of 'list' objects>
    index: method_descriptor = <method 'index' of 'list' objects>
    insert: method_descriptor = <method 'insert' of 'list' objects>
    pop: method_descriptor = <method 'pop' of 'list' objects>
    remove: method_descriptor = <method 'remove' of 'list' objects>
    reverse: method_descriptor = <method 'reverse' of 'list' objects>
    sort: method_descriptor = <method 'sort' of 'list' objects>

    def Create(iterable, line_size): ...
    def CreateByList(list_or_tuple, line_size): ...
    def append(self, p_object): ...
    def extend(self, iterable): ...

class LogInvoke(object):
class LruCache(OrderedDict):
    _OrderedDict__marker: object = <object object at 0x702c5c4b30>
    get: method_descriptor = <method 'get' of 'dict' objects>

    def _OrderedDict__update(self, other=(), /, **kwds): ...
    def clean(self): ...
    def clear(self): ...
    def copy(self): ...
    def fromkeys(iterable, value=None): ...
    def front_item(self): ...
    def front_key(self): ...
    def front_value(self): ...
    def invalid(self, key): ...
    def items(self): ...
    def iteritems(self): yield ...
    def iterkeys(self): ...
    def itervalues(self): yield ...
    def keys(self): ...
    def move_to_end(self, key, last=True): ...
    def pop(self, key, default=<object object at 0x702c5c4b30>): ...
    def popitem(self, last=True): ...
    def select(self, key): ...
    def setdefault(self, key, default=None): ...
    def update(self, key, value): ...
    def values(self): ...

class MutableMapping(Mapping):
    _MutableMapping__marker: object = <object object at 0x702c5c41c0>
    _abc_impl: _abc_data = <_abc._abc_data object at 0x7011e88c00>

    def clear(self): ...
    def get(self, key, default=None): ...
    def items(self): ...
    def keys(self): ...
    def pop(self, key, default=<object object at 0x702c5c41c0>): ...
    def popitem(self): ...
    def setdefault(self, key, default=None): ...
    def update(self, other=(), /, **kwds): ...
    def values(self): ...

class NonexistentSwallower(Swallower):
class OrderedDict(dict):
    _OrderedDict__marker: object = <object object at 0x702c5c4b30>
    get: method_descriptor = <method 'get' of 'dict' objects>

    def _OrderedDict__update(self, other=(), /, **kwds): ...
    def clear(self): ...
    def copy(self): ...
    def fromkeys(iterable, value=None): ...
    def front_item(self): ...
    def front_key(self): ...
    def front_value(self): ...
    def items(self): ...
    def iteritems(self): yield ...
    def iterkeys(self): ...
    def itervalues(self): yield ...
    def keys(self): ...
    def move_to_end(self, key, last=True): ...
    def pop(self, key, default=<object object at 0x702c5c4b30>): ...
    def popitem(self, last=True): ...
    def setdefault(self, key, default=None): ...
    def update(self, other=(), /, **kwds): ...
    def values(self): ...

class Singleton(object):
    def Destroy(): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class SingletonMeta(type):
    mro: method_descriptor = <method 'mro' of 'type' objects>

class SlotsEnum(object):
class SlotsEnumMetaClass(_SlotsEnumMetaClassBase):
    mro: method_descriptor = <method 'mro' of 'type' objects>

    def from_string(cls, name): ...
    def to_string(cls, idx): ...

class SlotsEnumStr(object):
class SlotsEnumStrMetaClass(_SlotsEnumMetaClassBase):
    mro: method_descriptor = <method 'mro' of 'type' objects>

    def to_idx(cls, name): ...

class Swallower(object):
class _Link(object):
    key: member_descriptor = <member 'key' of '_Link' objects>
    next: member_descriptor = <member 'next' of '_Link' objects>
    prev: member_descriptor = <member 'prev' of '_Link' objects>

class _SlotsEnumMetaClassBase(type):
    mro: method_descriptor = <method 'mro' of 'type' objects>

class defaultdict(dict):
    clear: method_descriptor = <method 'clear' of 'dict' objects>
    copy: method_descriptor = <method 'copy' of 'collections.defaultdict' objects>
    default_factory: member_descriptor = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys: builtin_function_or_method = <built-in method fromkeys of type object at 0x702850e7d8>
    get: method_descriptor = <method 'get' of 'dict' objects>
    items: method_descriptor = <method 'items' of 'dict' objects>
    keys: method_descriptor = <method 'keys' of 'dict' objects>
    pop: method_descriptor = <method 'pop' of 'dict' objects>
    popitem: method_descriptor = <method 'popitem' of 'dict' objects>
    setdefault: method_descriptor = <method 'setdefault' of 'dict' objects>
    update: method_descriptor = <method 'update' of 'dict' objects>
    values: method_descriptor = <method 'values' of 'dict' objects>

class enum(object):
    name_to_values: dict = {}
    value_to_names: dict = {}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...


def Account2Sdkuid(account): ...
def CompressedProperty(name, default): ...
def EnsureSafeStr(s): ...
def GSharePrompt(proto_id, extra_data=None, extra_info=None): ...
def JsonUTF8Loads(d): ...
def NormalDecrypt(key, cur_input): ...
def NormalEncrypt(key, cur_input): ...
def UTF8(string): ...
def UnicodeToUTF8(d): ...
def clamp(val, low, high): ...
def decryptString(data): ...
def encryptString(data): ...
def recursive_repr(fillvalue='...'): ...

