# module: gclient.gamesystem.uiwarehouse.warehouse_hero_model_ctrl

import MType
import MUI
import cconst
import consts
import lobby_item_data
import six2
import unit_model_data

WATCH_MODE_HAND_WATCH: int = 2
WATCH_MODE_MODEL: int = 0
WATCH_MODE_WATCH: int = 1

class HallModelComponent(object):
    def AddHiddenReason(self, reason): ...
    def AddSkeletonIKSlot(self): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def AddWeaponByEquipId(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, principle_role=False, extra=None): ...
    def AddWeaponByEquipIdForHeroSkin(self, show_item_id): ...
    def AddWeaponByItemProto(self, item_proto): ...
    def AddWeaponForDoll(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, extra=None): ...
    def AddWeaponForMainNpc(self): ...
    def CacheModel(self): ...
    def ChangeArmClothes(self, arm_clothes): ...
    def ChangeGender(self, gender): ...
    def ChangeWeaponSkinId(self, skin_id): ...
    def CheckClearHeroSkinAnimDlc(self): ...
    def CheckEmoteModelAttach(self): ...
    def CheckHeroAttachModel(self): ...
    def CheckHeroSkinEffect(self): ...
    def CheckNeedDownload(self): ...
    def CheckPlayHeroSkinAnim(self, is_reload=True): ...
    def CheckRefreshNpcPose(self): ...
    def ClearHeroSkinPose(self): ...
    def ClearPose(self): ...
    def ClearPoseOnEmoteEnd(self): ...
    def ClearPoseOnExecuteEnd(self): ...
    def CreateWeaponCaseByItemProto(self, item_proto): ...
    def DelHeroAttachModel(self): ...
    def DelWeapon(self): ...
    def DelaySetDlcNodePosition(self): ...
    def DetachWeapon(self): ...
    def GetBasicGraph(self): ...
    def GetDlcNodePosition(self): ...
    def GetDlcUINode(self): ...
    def GetHeroId(self): ...
    def GetLobbyPoseId(self): ...
    def GetModelCls(self): ...
    def GetModelComponentList(self): ...
    def GetModelOwner(self): ...
    def GetModelSkeleton(self): ...
    def GetModelUnitID(self): ...
    def InitModelDlcStatusNode(self): ...
    def IsClothesNeedDownload(self): ...
    @property
    def IsVisible(self): ...    def OnAttachWeaponCaseDone(self, _): ...
    def OnHallShowModelLoaded(self, is_reload=False): ...
    def OnPlayEmoteEnd(self, callback): ...
    def OnRefreshDownloadState(self, dlc_id, status): ...
    def PlayEmoteAnim(self, interrupt=True): ...
    def PlayExecuteAnim(self): ...
    def RefreshCurAttachWeaponCaseForDlc(self): ...
    def RefreshWeaponDlcids(self): ...
    def RefreshWeaponModelAttach(self, is_mvp=False): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def ResetAttensionDlcIds(self): ...
    def ResetDlcId(self): ...
    def SetArmClothes(self, arm_clothes, refresh_dlc=True): ...
    def SetIsShowHeroSkin(self, value): ...
    def SetLobbyPoseId(self, pose_id): ...
    def SetMipBias(self, bias): ...
    def SetupCastDynamicShadow(self): ...
    def ShowEmoteAttachModel(self, value): ...
    def ShowEmoteModel(self, item_proto, emote_loop=True, callback=None): ...
    def ShowExecuteModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowExecutedModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowHeroSkinModel(self, item_proto, is_idle=False, is_executed=False, without_anim=False): ...
    def ShowModel(self, use_ready_to_appear=False): ...
    def ShowTailEffect(self, item_proto): ...
    def StopTailEffect(self): ...
    def _ChangeShaderGraphParamForHallDollGun(self): ...
    def _DoAddWeapon(self, equip_id, skin_id, guise_id, part_slots, extra=None, is_reload=False): ...
    def _GetDefaultSuitItemId(self): ...
    def _GetPoseInfoByWeaponId(self, weapon_id): ...
    def _RefreshDlcInfoForPlayEmote(self, emote_item_id): ...
    def _RefreshDlcInfoForPlayExecute(self, execution_item_id): ...
    def _RefreshInfoOnArmClothesChange(self): ...
    @property
    def entity_area(self): ...
class HallShowModel(SimpleModel):
    DISSOLVE_CUTOFF_HEIGHT_RANGE: tuple = (26, 36)
    DISSOLVE_SPEED: float = 0.5
    logger: Logger = <Logger Model (DEBUG)>

    def AddHiddenReason(self, reason): ...
    def AddLoadTask(self, name): ...
    def AddTargetSlot(self, slot_name, actor): ...
    def AddTechState(self, id, custom_param=None): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def ApplyCustomStencil(self, custom_stencil, is_check=False): ...
    def AttachHeadModelImp(self): ...
    def AttachShowWeaponCase(self, model_ctrl): ...
    def AttachToParent(self, entity, basepoint, hardpoint): ...
    def BatchResetShaderGraphParameter(self, params, layer=-1): ...
    def BatchSetShaderGraphParameter(self, params, values, layer=-1): ...
    def BindBoneColliderCallFunc(self, result): ...
    def BindEventSignalNotify(self): ...
    def CallOwner(self, method, *args, **kwargs): ...
    def CancelEmoteAnim(self, smooth=False): ...
    def CancelExecuteAnim(self, smooth=False): ...
    def CancelHeroSkinAnim(self, smooth=False): ...
    def ChangeCustomMaterial(self, material_path, **kwargs): ...
    def ChangeShaderGraphMaterial(self, shader_graph_path, layer=-1, inherit=False): ...
    def CheckCreateAttachModel(self, model_id, is_attach, hardpoint, basepoint, is_execute=False): ...
    def CheckHeadModel(self): ...
    def CheckHelmetHeroClicked(self): ...
    def CheckHelmetModels(self): ...
    def CheckPreloadExecuteThirdModel(self): ...
    def CheckRecreateSkeletonOnReloaded(self, data): ...
    def ClearALLCueCameraEffect(self): ...
    def ClearAllCueEffectCache(self): ...
    def ClearAllCueSoundCache(self): ...
    def ClearAllSkeletonEffect(self): ...
    def ClearCueEffectCache(self, graph_id, path): ...
    def ClearCueEffectCacheByGraphID(self, graph_id): ...
    def ClearEmoteInfo(self, smooth=False): ...
    def ClearExecuteInfo(self, smooth=False): ...
    def ClearHeroSkinInfo(self, smooth=False): ...
    def ClearHiddenReason(self): ...
    def ClearMotionBlur(self, elapsedTime, centerU, centerV): ...
    def ClearRigidBodies(self): ...
    def ClearRotateRecover(self): ...
    def ClearSkeletonEffect(self, effect_id): ...
    def ClearSkeletonEffectByEffectId(self, effect_id): ...
    def ClearSkeletonEffectByEffectIdImmediately(self, effect_id): ...
    def ClearSkeletonEffectImmediately(self, effect_id): ...
    def ClearTailEffect(self): ...
    def ClearTechParam(self): ...
    def ClearTechState(self): ...
    def ClearWarmingUpHiddenReason(self): ...
    def ClearZoomRecover(self): ...
    def CreateSpecifyBone(self, bone_name): ...
    def CueEmoteEnd(self): ...
    def CueExecuteHideModel(self): ...
    def CueExecuteShowModel(self): ...
    def CueExecuteThirdModel(self): ...
    def CueExecutionEnd(self): ...
    def CueStartShowEmoteModel(self): ...
    def CueStopShowEmoteModel(self): ...
    def CustomStencilCheck(self, target_stencil, *args): ...
    def DebugChangeSkinWithRepositoryName(self, repository_name, stage='lobby'): ...
    def Destroy(self): ...
    def DestroyCppModel(self): ...
    def DisableMixMapAsFarAsPossible(self): ...
    def DisableNormalMap(self): ...
    def DisableOutlined(self): ...
    def DisablePrincipleRole(self): ...
    def EnableModelRotate(self, is_enable): ...
    def EnableOutlined(self, color, thickness): ...
    def EndRotateRecover(self): ...
    def ExecuteCreateThirdPersonModel(self, is_create, model_id=0): ...
    def FireEvent(self, event, gid=-1): ...
    def GetAllPrim(self, need_sorted=False): ...
    def GetBoneLocalPosition(self, bone): ...
    def GetBoneLocalTransform(self, bone): ...
    def GetBoneModelPosition(self, bone): ...
    def GetBoneTransform(self, bone): ...
    def GetBoneWorldPosition(self, bone): ...
    def GetBoneWorldTransform(self, bone): ...
    def GetCurArmExecutionItemId(self): ...
    def GetEmoteProto(self): ...
    def GetExecuteProto(self): ...
    def GetExecuteThirdModel(self): ...
    def GetGraphHandleInGraphStack(self, graph_name): ...
    def GetHeadModelID(self): ...
    def GetModelResource(self, data): ...
    def GetMotionSkeletonFile(skeleton): ...
    def GetPrimWorldBound(self): ...
    def GetPrimWorldBoundCentre(self): ...
    def GetPrimWorldBoundCentreWithAttachments(self): ...
    def GetPrimWorldBoundLength(self): ...
    def GetPrimWorldBoundWithAttachments(self): ...
    def GetShaderGraphOriginParameter(self, param, layer=-1): ...
    def GetShaderGraphParameter(self, param, layer): ...
    def GetShaderParameter(self, param): ...
    def GetSkeleton(self): ...
    def GetSkeletonDynamicWorldBound(self): ...
    def GetSkeletonDynamicWorldBoundCentre(self): ...
    def GetSkeletonEffectEntities(self, eff_id): ...
    def GetSkeletonEffectEntitiesByEffectId(self, effect_id): ...
    def GetVariableF(self, varname, gid=-1): ...
    def GetVariableI(self, varname, gid=-1): ...
    def GetVariableS(self, varname, gid=-1): ...
    def GetVariableV3(self, varname, gid=-1): ...
    def GetVariableZ(self, varname, gid=-1): ...
    def HasActorComponent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HaveWarmingUpHiddenReason(self, reason): ...
    def HideAllAttachedNormalModes(self): ...
    def InitControlTrans(self, origin_pos=None): ...
    def InitRotateAxis(self, x_axis=None, y_axis=None): ...
    def IsEnableOutlined(self): ...
    def IsPrincipleRole(self): ...
    def IsRotateModelY(self): ...
    @property
    def IsVisible(self): ...    def JumpToState(self, state, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def Load(self, data, done=None, **create_kwargs): ...
    def MakeSureBones(self): ...
    def MarkPrincipleRole(self): ...
    def ModelExpireCallback(self, ientity): ...
    def OnAttachModelDone(self): ...
    def OnBodyOrHeadModelDone(self): ...
    def OnChangeModelId(self, old_model_id): ...
    def OnCineDisplayPerformer(self, trigger, cueinput): ...
    def OnCineHidePerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformers(self, trigger, cueinput): ...
    def OnCineRenamePerformer(self, trigger, cueinput): ...
    def OnHallShowModelLoaded(self, is_reload=False): ...
    def OnHeadModelDone(self): ...
    def OnMouseEnd(self): ...
    def OnMouseMove(self, x, y): ...
    def OnRefreshDownloadStateForStageModel(self, dlc_id, status): ...
    def OnVisibleChanged(self, visible): ...
    def PauseGraph(self, pause, gid=-1): ...
    def PlayAnimation(self, anim_name, single_play=True, remove_motion=True, play_speed=1.0): ...
    def PlayEffectById(self, effect_id, max_life=-1, scale=1, bone='root', offset=(0, 0, 0), insure_play=False): ...
    def PlayEmoteAnim(self, interrupt=True): ...
    def PlayExecuteAnim(self): ...
    def PlayHeroSkinAnim(self, model_ctrl, is_idle): ...
    def PlaySkeletonEffect(self, effect_str, max_life=-1, insure_play=False, effect_id=None): ...
    def PlayTailEffect(self, item_proto): ...
    def PopEffectDictByEngineEid(self, engine_eid): ...
    def PopGraph(self, graph_id, blendTime=0): ...
    def PushGraph(self, graph, transtime=0, ratio=0): ...
    def ReceiveDynamicShadow(self): ...
    def RecoverOriginTransform(self): ...
    def Refresh(self): ...
    def RefreshHairCustomRenderSet(self): ...
    def RefreshRotateOrigin(self, origin_pos): ...
    def RefreshTeammateTechState(self): ...
    def Reload(self, data, done=None, use_ready_to_appear=True): ...
    def ReloadPrimitives(self, data, use_ready_to_appear=True): ...
    def ReloadSkeleton(self, data): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveLoadTask(self, name): ...
    def RemoveTechState(self, proto_id): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def RemoveXRayBlock(self): ...
    def ReplaceGraph(self, graph_id, graph): ...
    def ResetCustomMaterial(self): ...
    def ResetShaderGraphMaterial(self, layer=-1): ...
    def ResetShaderGraphParameter(self, param, layer=-1): ...
    def ResetShaderGraphParameters(self, layer=-1): ...
    def ResetShaderParameter(self, param): ...
    def RotateModel(self, x, y): ...
    def RotateRecover(self, dt): ...
    def RotateRecoverImmediately(self): ...
    def SetAsCSMRole(self, is_role): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetEmoteAnimInfo(self, item_id, graph_file, emote_id, loop=True, break_callback=None): ...
    def SetEnableVisibilityOptimize(self, enable): ...
    def SetExecuteAnimInfo(self, item_id, graph_file, execute_id, is_executed=True, loop=True, break_callback=None, is_stop=False): ...
    def SetHeroSkinAnimInfo(self, graph_file, hero_skin_id, hero_id, need_download, is_executed): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetLodDistance(self, layer, distance): ...
    def SetLodDistanceAllLayers(self, distances): ...
    def SetNoNearPlaneClip(self, enable): ...
    def SetOutlinedParam(self, color, thickness): ...
    def SetRotateModelY(self, value): ...
    def SetShaderGraphParameter(self, param, value, layer=-1): ...
    def SetShaderGraphParameterRecursively(self, param, value, layer=-1): ...
    def SetShaderParameter(self, param, value, **kwargs): ...
    def SetShaderParameterRecursively(self, param, value): ...
    def SetSkeletonEffectVisible(self, visible): ...
    def SetSkeletonEffectVisibleForEffectId(self, effect_id, visible): ...
    def SetTechState(self): ...
    def SetTechStateParam(self, tech_id, custom_param): ...
    def SetTitlesToplogoVisible(self, visible): ...
    def SetTransformWithAttachmentsImmediately(self, transform): ...
    def SetVariableF(self, varname, varvalue, gid=-1): ...
    def SetVariableI(self, varname, varvalue, gid=-1): ...
    def SetVariableS(self, varname, varvalue, gid=-1): ...
    def SetVariableV3(self, varname, varvalue, gid=-1): ...
    def SetVariableZ(self, varname, varvalue, gid=-1): ...
    def SetWarmingUp(self, value): ...
    def SetWarmingUpAppearImmediately(self, value): ...
    def ShiftGraph(self, gid, offset): ...
    def ShowStageModel(self, is_idle): ...
    def ShowTitles(self, cur_titles): ...
    def SignalNotifyCallback(self, trigger, stype, signalStr): ...
    def SkeletonExpireCallback(self, skeleton): ...
    def StartPutOnWithDissolve(self, is_puton): ...
    def StartRotateRecover(self): ...
    def StartRotateRecoverTimer(self): ...
    def StartZoomRecover(self): ...
    def StartZoomRecoverTimer(self): ...
    def StopAnimation(self, anim_name): ...
    def StopTailEffect(self): ...
    def UseDistancedEnemyTechState(self, param, param2): ...
    def UseTechEdgeLine(self, color, thickness): ...
    def UseTechFrozen(self): ...
    def UseTechHighLightXray(self, param, param2, color2): ...
    def UseTechHighlight(self, color, frequency=0.0): ...
    def UseTechXray(self, color2=None, param2=None): ...
    def ZoomRecoverImmediately(self): ...
    def _CancelDissolveTimer(self): ...
    def _CheckSameTachStatus(self, parent, basepoint, hardpoint): ...
    def _DiscardHelmetModels(self): ...
    def _GetAvailableModelInfo(self, model_data): ...
    def _ProcessCueEnd(self, prev, trigger): ...
    def _SetCutOffHeight(self, value): ...
    def _SetEnableDissolve(self, enable): ...
    def _SetHeadNotReceiveDynamicShadow(self): ...
    def _SetHelmetIsWarmingUp(self, is_warmingup): ...
    def _SetVisible(self, visible): ...
    def _TickDissolveValue(self): ...
    def _TryPutHelmetModels(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, interval, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def cue_signal_attach_execute_freeze_model(self, trigger, signal_str): ...
    def cue_signal_attach_normal_model(self, trigger, signal_str): ...
    def cue_signal_effect_attach_detach(self, trigger, signal_str): ...
    def cue_signal_event(self, trigger, signal_str): ...
    def cue_signal_execute_third_model(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate_enable(self, trigger, signal_str): ...
    def cue_signal_motion_blur_to_percent(self, trigger, signal_str): ...
    def cue_signal_player_event(self, trigger, signal_str): ...
    def cue_signal_sound_event(self, trigger, signal_str): ...
    def cue_signal_sound_far_event(self, trigger, signal_str): ...
    def cue_signal_variable_event_sync_stack(self, trigger, signal_str): ...
    def cue_type_node_transition_excute(self, trigger, curinput): ...
    def isModelOnlyValid(self): ...
    def isValid(self): ...
    @property
    def is_destroyed(self): ...    @property
    def is_loaded(self): ...    def onCineDismissPerformer(self, trigger, cueinput): ...
    def onCineDismissPerformers(self, trigger, cueinput): ...
    def onCineDisplayCaption(self, trigger, cueinput): ...
    def onLoaded(self): ...
    @property
    def position(self): ...    @property
    def scale(self): ...    @property
    def skeleton(self): ...    @property
    def space(self): ...    @property
    def yaw(self): ...
class HeroSelectModelCtrl(Singleton):
    MODEL_YAW: float = 2.0

    def AddHiddenReason(self, reason): ...
    def AddSkeletonIKSlot(self): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def AddWeaponByEquipId(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, principle_role=False, extra=None): ...
    def AddWeaponByEquipIdForHeroSkin(self, show_item_id): ...
    def AddWeaponByItemProto(self, item_proto): ...
    def AddWeaponForDoll(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, extra=None): ...
    def AddWeaponForMainNpc(self): ...
    def CacheModel(self): ...
    def ChangeArmClothes(self, arm_clothes): ...
    def ChangeGender(self, gender): ...
    def ChangeWeaponSkinId(self, skin_id): ...
    def CheckClearHeroSkinAnimDlc(self): ...
    def CheckEmoteModelAttach(self): ...
    def CheckHeroAttachModel(self): ...
    def CheckHeroSkinEffect(self): ...
    def CheckNeedDownload(self): ...
    def CheckPlayHeroSkinAnim(self, is_reload=True): ...
    def CheckRefreshNpcPose(self): ...
    def ClearHeroSkinPose(self): ...
    def ClearPose(self): ...
    def ClearPoseOnEmoteEnd(self): ...
    def ClearPoseOnExecuteEnd(self): ...
    def CreateWeaponCaseByItemProto(self, item_proto): ...
    def DelHeroAttachModel(self): ...
    def DelWeapon(self): ...
    def DelaySetDlcNodePosition(self): ...
    def Destroy(): ...
    def DetachWeapon(self): ...
    def EndRotateRecover(self): ...
    def GetBasicGraph(self): ...
    def GetDlcNodePosition(self): ...
    def GetDlcUINode(self): ...
    def GetHeroId(self): ...
    def GetLobbyPoseId(self): ...
    def GetModelCls(self): ...
    def GetModelComponentList(self): ...
    def GetModelOwner(self): ...
    def GetModelSkeleton(self): ...
    def GetModelUnitID(self): ...
    def InitModelDlcStatusNode(self): ...
    def IsClothesNeedDownload(self): ...
    @property
    def IsVisible(self): ...    def OnAttachWeaponCaseDone(self, _): ...
    def OnDestroy(self): ...
    def OnHallShowModelLoaded(self, is_reload=False): ...
    def OnMouseEnd(self): ...
    def OnMouseMove(self, x, y, rotate_x=True, rotate_y=True): ...
    def OnMouseRDown(self, x, y): ...
    def OnMouseRUp(self, x, y): ...
    def OnPlayEmoteEnd(self, callback): ...
    def OnRefreshDownloadState(self, dlc_id, status): ...
    def PlayEmoteAnim(self, interrupt=True): ...
    def PlayExecuteAnim(self): ...
    def RefreshCurAttachWeaponCaseForDlc(self): ...
    def RefreshWeaponDlcids(self): ...
    def RefreshWeaponModelAttach(self, is_mvp=False): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def ResetAttensionDlcIds(self): ...
    def ResetDlcId(self): ...
    def SetArmClothes(self, arm_clothes, refresh_dlc=True): ...
    def SetIsShowHeroSkin(self, value): ...
    def SetLobbyPoseId(self, pose_id): ...
    def SetMipBias(self, bias): ...
    def SetupCastDynamicShadow(self): ...
    def ShowEmoteAttachModel(self, value): ...
    def ShowEmoteModel(self, item_proto, emote_loop=True, callback=None): ...
    def ShowExecuteModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowExecutedModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowHeroSkinModel(self, item_proto, is_idle=False, is_executed=False, without_anim=False): ...
    def ShowModel(self, use_ready_to_appear=False): ...
    def ShowTailEffect(self, item_proto): ...
    def StopTailEffect(self): ...
    def _ChangeShaderGraphParamForHallDollGun(self): ...
    def _DoAddWeapon(self, equip_id, skin_id, guise_id, part_slots, extra=None, is_reload=False): ...
    def _GetDefaultSuitItemId(self): ...
    def _GetPoseInfoByWeaponId(self, weapon_id): ...
    def _RefreshDlcInfoForPlayEmote(self, emote_item_id): ...
    def _RefreshDlcInfoForPlayExecute(self, execution_item_id): ...
    def _RefreshInfoOnArmClothesChange(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def entity_area(self): ...    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class WarehouseHeroModelComponent(HallModelComponent):
    def AddHiddenReason(self, reason): ...
    def AddSkeletonIKSlot(self): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def AddWeaponByEquipId(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, principle_role=False, extra=None): ...
    def AddWeaponByEquipIdForHeroSkin(self, show_item_id): ...
    def AddWeaponByItemProto(self, item_proto): ...
    def AddWeaponForDoll(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, extra=None): ...
    def AddWeaponForMainNpc(self): ...
    def AttachWatchToHandModel(self): ...
    def CacheModel(self): ...
    def ChangeArmClothes(self, arm_clothes): ...
    def ChangeGender(self, gender): ...
    def ChangeWatchMode(self, watch_mode): ...
    def ChangeWeaponSkinId(self, skin_id): ...
    def CheckClearHeroSkinAnimDlc(self): ...
    def CheckEmoteModelAttach(self): ...
    def CheckHeroAttachModel(self): ...
    def CheckHeroSkinEffect(self): ...
    def CheckNeedDownload(self): ...
    def CheckPlayHeroSkinAnim(self, is_reload=True): ...
    def CheckRefreshNpcPose(self): ...
    def CheckWatchModel(self): ...
    def ClearHeroSkinPose(self): ...
    def ClearPose(self): ...
    def ClearPoseOnEmoteEnd(self): ...
    def ClearPoseOnExecuteEnd(self): ...
    def CreateWeaponCaseByItemProto(self, item_proto): ...
    def DelHeroAttachModel(self): ...
    def DelWeapon(self): ...
    def DelaySetDlcNodePosition(self): ...
    def DetachWeapon(self): ...
    def GetBasicGraph(self): ...
    def GetDlcNodePosition(self): ...
    def GetDlcUINode(self): ...
    def GetHeroId(self): ...
    def GetLobbyPoseId(self): ...
    def GetModelCls(self): ...
    def GetModelComponentList(self): ...
    def GetModelOwner(self): ...
    def GetModelSkeleton(self): ...
    def GetModelUnitID(self): ...
    def InitModelDlcStatusNode(self): ...
    def IsClothesNeedDownload(self): ...
    @property
    def IsVisible(self): ...    def LoadHandModel(self, callback=None): ...
    def OnAttachWeaponCaseDone(self, _): ...
    def OnHallShowModelLoaded(self, is_reload=False): ...
    def OnHandModelLoaded(self, callback=None): ...
    def OnPlayEmoteEnd(self, callback): ...
    def OnRefreshDownloadState(self, dlc_id, status): ...
    def OnWatchModelDone(self): ...
    def PlayEmoteAnim(self, interrupt=True): ...
    def PlayExecuteAnim(self): ...
    def RefreshCurAttachWeaponCaseForDlc(self): ...
    def RefreshWeaponDlcids(self): ...
    def RefreshWeaponModelAttach(self, is_mvp=False): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def ResetAttensionDlcIds(self): ...
    def ResetDlcId(self): ...
    def SetArmClothes(self, arm_clothes, refresh_dlc=True): ...
    def SetIsShowHeroSkin(self, value): ...
    def SetLobbyPoseId(self, pose_id): ...
    def SetMipBias(self, bias): ...
    def SetWatchItemId(self, watch_item_id): ...
    def SetupCastDynamicShadow(self): ...
    def ShowEmoteAttachModel(self, value): ...
    def ShowEmoteModel(self, item_proto, emote_loop=True, callback=None): ...
    def ShowExecuteModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowExecutedModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowHeroSkinModel(self, item_proto, is_idle=False, is_executed=False, without_anim=False): ...
    def ShowModel(self, use_ready_to_appear=False): ...
    def ShowTailEffect(self, item_proto): ...
    def StopTailEffect(self): ...
    def SwitchToHandModel(self, is_switch): ...
    def _ChangeShaderGraphParamForHallDollGun(self): ...
    def _DoAddWeapon(self, equip_id, skin_id, guise_id, part_slots, extra=None, is_reload=False): ...
    def _GetDefaultSuitItemId(self): ...
    def _GetPoseInfoByWeaponId(self, weapon_id): ...
    def _RefreshDlcInfoForPlayEmote(self, emote_item_id): ...
    def _RefreshDlcInfoForPlayExecute(self, execution_item_id): ...
    def _RefreshInfoOnArmClothesChange(self): ...
    @property
    def entity_area(self): ...
class WarehouseHeroModelCtrl(HeroSelectModelCtrl):
    MODEL_POS: tuple = (0.6, 0.08, 0.15)
    MODEL_YAW: float = 2.269

    def AddHiddenReason(self, reason): ...
    def AddSkeletonIKSlot(self): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def AddWeaponByEquipId(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, principle_role=False, extra=None): ...
    def AddWeaponByEquipIdForHeroSkin(self, show_item_id): ...
    def AddWeaponByItemProto(self, item_proto): ...
    def AddWeaponForDoll(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, extra=None): ...
    def AddWeaponForMainNpc(self): ...
    def AttachWatchToHandModel(self): ...
    def CacheModel(self): ...
    def ChangeArmClothes(self, arm_clothes): ...
    def ChangeGender(self, gender): ...
    def ChangeWatchMode(self, watch_mode): ...
    def ChangeWeaponSkinId(self, skin_id): ...
    def CheckClearHeroSkinAnimDlc(self): ...
    def CheckEmoteModelAttach(self): ...
    def CheckHeroAttachModel(self): ...
    def CheckHeroSkinEffect(self): ...
    def CheckNeedDownload(self): ...
    def CheckPlayHeroSkinAnim(self, is_reload=True): ...
    def CheckRefreshNpcPose(self): ...
    def CheckWatchModel(self): ...
    def ClearHeroSkinPose(self): ...
    def ClearPose(self): ...
    def ClearPoseOnEmoteEnd(self): ...
    def ClearPoseOnExecuteEnd(self): ...
    def CreateWeaponCaseByItemProto(self, item_proto): ...
    def DelHeroAttachModel(self): ...
    def DelWeapon(self): ...
    def DelaySetDlcNodePosition(self): ...
    def Destroy(): ...
    def DetachWeapon(self): ...
    def EndRotateRecover(self): ...
    def GetBasicGraph(self): ...
    def GetDlcNodePosition(self): ...
    def GetDlcUINode(self): ...
    def GetHeroId(self): ...
    def GetLobbyPoseId(self): ...
    def GetModelCls(self): ...
    def GetModelComponentList(self): ...
    def GetModelOwner(self): ...
    def GetModelSkeleton(self): ...
    def GetModelUnitID(self): ...
    def InitModelDlcStatusNode(self): ...
    def IsClothesNeedDownload(self): ...
    @property
    def IsVisible(self): ...    def LoadHandModel(self, callback=None): ...
    def OnAttachWeaponCaseDone(self, _): ...
    def OnDestroy(self): ...
    def OnHallShowModelLoaded(self, is_reload=False): ...
    def OnHandModelLoaded(self, callback=None): ...
    def OnMouseEnd(self): ...
    def OnMouseMove(self, x, y, rotate_x=True, rotate_y=True): ...
    def OnMouseRDown(self, x, y): ...
    def OnMouseRUp(self, x, y): ...
    def OnPlayEmoteEnd(self, callback): ...
    def OnRefreshDownloadState(self, dlc_id, status): ...
    def OnWatchModelDone(self): ...
    def PlayEmoteAnim(self, interrupt=True): ...
    def PlayExecuteAnim(self): ...
    def RefreshCurAttachWeaponCaseForDlc(self): ...
    def RefreshWeaponDlcids(self): ...
    def RefreshWeaponModelAttach(self, is_mvp=False): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def ResetAttensionDlcIds(self): ...
    def ResetDlcId(self): ...
    def SetArmClothes(self, arm_clothes, refresh_dlc=True): ...
    def SetIsShowHeroSkin(self, value): ...
    def SetLobbyPoseId(self, pose_id): ...
    def SetMipBias(self, bias): ...
    def SetWatchItemId(self, watch_item_id): ...
    def SetupCastDynamicShadow(self): ...
    def ShowEmoteAttachModel(self, value): ...
    def ShowEmoteModel(self, item_proto, emote_loop=True, callback=None): ...
    def ShowExecuteModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowExecutedModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowHeroSkinModel(self, item_proto, is_idle=False, is_executed=False, without_anim=False): ...
    def ShowModel(self, use_ready_to_appear=False): ...
    def ShowTailEffect(self, item_proto): ...
    def StopTailEffect(self): ...
    def SwitchToHandModel(self, is_switch): ...
    def _ChangeShaderGraphParamForHallDollGun(self): ...
    def _DoAddWeapon(self, equip_id, skin_id, guise_id, part_slots, extra=None, is_reload=False): ...
    def _GetDefaultSuitItemId(self): ...
    def _GetPoseInfoByWeaponId(self, weapon_id): ...
    def _RefreshDlcInfoForPlayEmote(self, emote_item_id): ...
    def _RefreshDlcInfoForPlayExecute(self, execution_item_id): ...
    def _RefreshInfoOnArmClothesChange(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def entity_area(self): ...    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...


def Components(*components, **kwargs): ...

