# module: gclient.gameplay.logic_moba_zombie.ui.map.map_base_zombie_battle

import MEngine
import MType
import MUI
import cc
import cconst
import replay_util
import six2
import switches

TAGTYPE_2_DATA: dict = {18: {'tag_id': 10002, 'pos_name': 'crack_entity_pos'}, 21: {'tag_id': 10003, 'pos_name': 'recover_item_pos'}}
_reload_all: bool = True

class MapBaseMoba(MapBase):
    MAX_NUM: int = 10
    MAX_Z_ORDER: int = 10
    MIN_Z_ORDER: int = 7
    TEAM_TAG: type = <class 'gclient.gameplay.logic_moba.ui.moba_map_base.MobaTeamTag'>

    def AddAirlineTick(self): ...
    def AddBorderProcessForTag(self, mark_id, tag, origin_pix=None): ...
    def AddChaosAreaTag(self, guid, target_area): ...
    def AddChaosUavArea(self, guid, target_area): ...
    def AddDotLineTick(self): ...
    def AddHiddenReasonForSafeRegion(self, hidden_reason): ...
    def AddHiddenReasonFullUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def AddHiddenReasonUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def AddRotateWithImageNode(self, widget): ...
    def AddTagHiddenReasonByTagType(self, tag_type, hidden_reason=1): ...
    def AddTagHiddenReasonByTagTypeInRegion(self, tag_type, region, hidden_reason=1): ...
    def AdjustMapPositionWithDiffPos(self, diff_pos): ...
    def BlockCurSafeRegion(self, region): ...
    def BorderTagTick(self, dtime): ...
    def CalTeamMemberPosInPanelMask(self, pix): ...
    def CalTeamMemberPosInPanelMaskAny(self, pix): ...
    def CenterStoryTick(self, dtime): ...
    def CenterStoryTickBigMap(self, dtime): ...
    def ChangeIconInBigMap(self, to_small): ...
    def CheckAndDelForseeRegion(self): ...
    def ClearDotLine(self): ...
    def ClearMarkLine(self): ...
    def ClearSrLine(self): ...
    def CommonTagStoryTick(self, dtime): ...
    def CommonTagStoryTickBigMap(self, dtime): ...
    def ConvertPaprachuteSateToFsmAirlineState(self, parachute_stage): ...
    def ConvertToImageSpace(self, pix): ...
    def ConvertToPanelCutSpace(self, pix): ...
    def CreateAndShowWindow(self): ...
    def CreateCommonMarkToplogo(self, mark_id, mark_info): ...
    def CreateHunterTag(self): ...
    def CreateMarkToplogo(self, pos, slot, mark_type, guid, extra_info=None, member_id=''): ...
    def CreateOrRefreshRobotTag(self, robot_info): ...
    def CreateTag(self, src_img, zorder=2, anchor=(0.5, 0.5), anchor_scale=(0.0, 0.0), parent=None, scale=1, name=''): ...
    def CreateTagById(self, map_tag_id, wrapper=<class 'gclient.gameplay.uicomponents.map_tags.MapTagBase'>, wrapper_info=None, parent=None, scale=None, name='', extra=None): ...
    def CreateText(self, zorder=2, anchor=(0.5, 0.5), anchor_scale=(0.0, 0.0), parent=None, scale=1, fnt_size=15, name='', font_name='', outline_size=0, outline_color=(0, 0, 0, 255)): ...
    def DestroyCommonMarkToplogo(self, mark_id): ...
    def DestroyMarkToplogo(self, slot, mark_type, guid): ...
    def DotLineTick(self, dtime): ...
    def DrawAirLine(self, start, end, line_size, unit_len, color1, color2): ...
    def DrawAirLineWhite(self): ...
    def DrawCurAndNextSafeRegion(self, game_logic): ...
    def DrawDebugString(self, pos_dict, is_show=True): ...
    def DrawSafeRegion(self, draw_sr, region, color, clear=True): ...
    def DrawSafeRegionTips(self): ...
    def EnterFsmAirlineState(self, state): ...
    def EnterFsmAirlineStateByPaprachuteGamingState(self, parachute_stage): ...
    def EnterFsmSafeRegionStateBySrState(self, sr_state): ...
    def FixedAirLine(self, game_logic): ...
    def FixedDotLine(self, org, des, aircraftPos, lineStart): ...
    def GMShowSupplyTag(self, transforms): ...
    def GenAirline(self): ...
    def GenJumpTag(self): ...
    def GetAirDropShopBigMapInitScale(self, radius): ...
    def GetAvatarClientPositionAndYaw(self, avatar=None): ...
    def GetCenterTickEntity(self): ...
    def GetCenterUINode(self): ...
    def GetCommonMarkTag(self, guid): ...
    def GetDotLineState(self, sr_state): ...
    def GetFactionByVehicleFactionInfo(vehicle_faction_info): ...
    def GetFsmAirlineState(self): ...
    def GetFsmSafeRegionState(self, sr_state): ...
    def GetMiniMapParamKey(self): ...
    def GetSelfMarkPos(self): ...
    def GetTagScaleByRadius(self, radius, ui_image_radius): ...
    def GetVehicleTag(self, vehicle_id): ...
    def HaveTagHiddenReasonByTagType(self, tag_type, hidden_reason=1): ...
    def HideAllEnemyMarkTags(self): ...
    def HideAllUavTag(self): ...
    def HideCommonMarkToplogo(self, mark_id, hidden_reason): ...
    def HideEnemyMarkTagsByAvatarId(self, avatar_id): ...
    def HideMarkLine(self): ...
    def HideUavEnemyTagFull(self): ...
    def InitAirline(self): ...
    def InitData(self): ...
    def InitEnemyMarkShow(self): ...
    def InitMatrixNum(self): ...
    def InitRatio(self): ...
    def InitSafeRegion(self): ...
    def InitSelfTag(self): ...
    def InitTeamTag(self): ...
    def InitUavShow(self, force=False): ...
    def InitUavShowFull(self, force=False): ...
    def IsAircraftArrived(self): ...
    def IsCenterInPanelCut(self): ...
    def IsHasMarkLine(self): ...
    def IsTeamMemberInsideAny(self, pix): ...
    def IsTeamMemberInsideWithoutRotate(self, pix, cur_center_pix=None): ...
    def MapTransfer(self, screen_pos): ...
    def MarkLineTick(self, dtime): ...
    def MoveTagToImage(self, tag): ...
    def MoveTagToPanelMask(self, tag): ...
    def OnAirCraftArrived(self): ...
    def OnAvatarModelDestroy(self, avatar_id): ...
    def OnChaosUavRegionEnter(self, is_enter): ...
    def OnGetOnAircraft(self): ...
    def OnInfoChaos(self, is_chaos): ...
    def OnMapMissionMarkScaleDown(self, mark_id): ...
    def OnMapMissionMarkScaleUp(self, mark_id): ...
    def OnMiniMapRotateModeChanged(self, mode): ...
    def OnSafeRegionForeseeChange(self, info): ...
    def OnSafeRegionStateEnd(self): ...
    def OnSafeRegionStateShrink(self): ...
    def OnSafeRegionStateStable(self): ...
    def OnSafeRegionStateStart(self): ...
    def OnShowShutterEnergyMapGuide(self): ...
    def OnSpellShowingRange(self, spell_id, is_show): ...
    def OnVehicleIdInfoChanged(self, vehicle_id, vehicle_info, vehicle_faction_info): ...
    def OnWaitAircraft(self): ...
    def PercentToScale(self, percent): ...
    def PixToPos(self, pixx, pixy): ...
    def PosToPix(self, posx, posz): ...
    def PostCreateTagById(self, map_tag_id, tag_type, tag): ...
    def PreVisible(self, value): ...
    def RealYawToTagAngle(self, yaw): ...
    def ReconnectAirLine(self): ...
    def RecoverForeseeSafeRegion(self): ...
    def RefreshChaosUavArea(self): ...
    def RefreshDotLineFSM(self): ...
    def RefreshEnergyPlayerPos(self): ...
    def RefreshSafeRegion(self): ...
    def RefreshVehicleTags(self, vehicle_info_dict, vehicle_faction_info): ...
    def RemoveAirlineTick(self): ...
    def RemoveBorderProcessForTag(self, mark_id, tag): ...
    def RemoveChaosAreaTag(self, guid): ...
    def RemoveChaosUavArea(self, guid): ...
    def RemoveDotLineTick(self): ...
    def RemoveHiddenReasonForSafeRegion(self, hidden_reason): ...
    def RemoveHiddenReasonFullUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def RemoveHiddenReasonUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def RemoveSafeRegionShrinkTick(self): ...
    def RemoveTag(self, tag, remove_from_parent=True): ...
    def RemoveTagHiddenReasonByTagType(self, tag_type, hidden_reason=1): ...
    def RemoveTagHiddenReasonByTagTypeInRegion(self, tag_type, region, hidden_reason=1): ...
    def ResetCenterTagPos(self, center_tag=None): ...
    def ResetTeammateTickParam(self, teammate_id): ...
    def SafeRegionShrinkTick(self, dtime): ...
    def ScaleToPercent(self, scale): ...
    def SetAirLineInfo(self): ...
    def SetAirLineVisible(self, val): ...
    def SetBgText(self): ...
    def SetBgTexture(self): ...
    def SetBgTextureSplendor(self): ...
    def SetCenterNodeImgDir(self): ...
    def SetChaosUavArea(self, guid, target_area, has_chaos_effect): ...
    def SetImageCenter(self, pix): ...
    def SetImagePositionWithClamp(self, x, y): ...
    def SetImageRotation(self, angle): ...
    def SetScaleWithBase(self, scale, base=None): ...
    def SetSliderPercent(self, percent): ...
    def SetSpecifyPosToCenterBigMap(self, x, z): ...
    def SetTargetArea(self, target_area): ...
    def SetupBigMapScaleAndPos(self, scale, pos): ...
    def SetupMiniMapScale(self, scale): ...
    def SetupMiniMapScaleG(self, to_scale, duration): ...
    def ShowAirline(self, val): ...
    def ShowAirlineByValue(self, show_airline): ...
    def ShowCommonMarkToplogo(self, mark_id, hidden_reason): ...
    def ShowEnemyMark(self, avatar_infos, extra=None): ...
    def ShowMarkLine(self): ...
    def ShowPosRemindAnim(self): ...
    def ShowRadarEnermyPosition(self, pos): ...
    def ShowUav(self, caster_info, avatar_infos, level, spell_id, fix_pos, uav_range, start_time=None): ...
    def ShowUavFull(self, caster_info, avatar_infos, level, spell_id, fix_pos, refresh_circle, start_time=None): ...
    def ShowVehicleInfo(self, is_show): ...
    def SortZorderByStamp(self): ...
    def StartSimpleAOI(self, interval=3.0): ...
    def StartTick(self): ...
    def StopSimpleAOI(self): ...
    def StopTick(self): ...
    def TeamMemberStoryTick(self, dtime): ...
    def TeamMemberStoryTickBigMap(self, dtime): ...
    def TeamMemberStoryTickNew(self, dtime): ...
    def TickSimpleAOI(self): ...
    def TickVehicleTagInAoi(self): ...
    def UpdateAirlineTick(self, dtime): ...
    def UpdateCenterNode(self, tick_target=None): ...
    def UpdateCocosMiniMapTickParam(self): ...
    def VecToImageAngle(self, z_axis): ...
    def VehicleEnterAoiForMapTag(self, vehicle_id, is_enter): ...
    def YawToImageAngle(self, yaw): ...
    def YawToTagAngle(self, z_axis): ...
    def YawToTagAngleTuple(self, vec): ...
    def _CacheTagVehicle(self, vehicle_id): ...
    def _CheckDisturbEnable(self): ...
    def _CreateRadarEnermyTag(self): ...
    def _DrawCurAndNextSafeRegion(self, game_logic): ...
    def _GetCenterBigMapEntityYaw(self, entity): ...
    def _GetCurDisturbCenterInfo(self, key): ...
    def _GetDisturbCenterName(self, idx): ...
    def _GetDisturbFreeIdx(self): ...
    def _GetRadarTag(self): ...
    def _PostTagHiddenReason(self, tag_type, tag): ...
    def _RemoveRadarTag(self, tag): ...
    def _SetTagIconTexture(self, tag, icon): ...
    def _SetVehicleTagInfo(self, tag, vehicle_id, vehicle_info): ...
    def _SetupMiniMapScaleG(self, start_scale, to_scale, start_time, end_time, dtime): ...
    def _ShowPosRemindAnim(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def airline_color1(self): ...    @property
    def airline_color2(self): ...    @property
    def airline_color_passed(self): ...    @property
    def color_foresee_sr(self): ...    @property
    def color_next_sr(self): ...    @property
    def color_sr_block(self): ...    @property
    def color_sr_line(self): ...    @property
    def cur_center_pix(self): ...    @property
    def game_logic(self): ...    @property
    def markline_color_4b(self): ...    @property
    def scale(self): ...
class MapBaseZombieBattle(MapBaseMoba):
    MAX_NUM: int = 10
    MAX_Z_ORDER: int = 10
    MIN_Z_ORDER: int = 7
    TEAM_TAG: type = <class 'gclient.gameplay.logic_moba.ui.moba_map_base.MobaTeamTag'>

    def AddAirlineTick(self): ...
    def AddBorderProcessForTag(self, mark_id, tag, origin_pix=None): ...
    def AddChaosAreaTag(self, guid, target_area): ...
    def AddChaosUavArea(self, guid, target_area): ...
    def AddDotLineTick(self): ...
    def AddHiddenReasonForSafeRegion(self, hidden_reason): ...
    def AddHiddenReasonFullUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def AddHiddenReasonUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def AddRotateWithImageNode(self, widget): ...
    def AddTagHiddenReasonByTagType(self, tag_type, hidden_reason=1): ...
    def AddTagHiddenReasonByTagTypeInRegion(self, tag_type, region, hidden_reason=1): ...
    def AdjustMapPositionWithDiffPos(self, diff_pos): ...
    def BlockCurSafeRegion(self, region): ...
    def BorderTagTick(self, dtime): ...
    def CalTeamMemberPosInPanelMask(self, pix): ...
    def CalTeamMemberPosInPanelMaskAny(self, pix): ...
    def CenterStoryTick(self, dtime): ...
    def CenterStoryTickBigMap(self, dtime): ...
    def ChangeIconInBigMap(self, to_small): ...
    def CheckAndDelForseeRegion(self): ...
    def ClearDotLine(self): ...
    def ClearMarkLine(self): ...
    def ClearSrLine(self): ...
    def CommonTagStoryTick(self, dtime): ...
    def CommonTagStoryTickBigMap(self, dtime): ...
    def ConvertPaprachuteSateToFsmAirlineState(self, parachute_stage): ...
    def ConvertToImageSpace(self, pix): ...
    def ConvertToPanelCutSpace(self, pix): ...
    def CreateAndShowWindow(self): ...
    def CreateCommonMarkToplogo(self, mark_id, mark_info): ...
    def CreateHunterTag(self): ...
    def CreateMarkToplogo(self, pos, slot, mark_type, guid, extra_info=None, member_id=''): ...
    def CreateOrRefreshRobotTag(self, robot_info): ...
    def CreateTag(self, src_img, zorder=2, anchor=(0.5, 0.5), anchor_scale=(0.0, 0.0), parent=None, scale=1, name=''): ...
    def CreateTagById(self, map_tag_id, wrapper=<class 'gclient.gameplay.uicomponents.map_tags.MapTagBase'>, wrapper_info=None, parent=None, scale=None, name='', extra=None): ...
    def CreateText(self, zorder=2, anchor=(0.5, 0.5), anchor_scale=(0.0, 0.0), parent=None, scale=1, fnt_size=15, name='', font_name='', outline_size=0, outline_color=(0, 0, 0, 255)): ...
    def DestroyCommonMarkToplogo(self, mark_id): ...
    def DestroyMarkToplogo(self, slot, mark_type, guid): ...
    def DotLineTick(self, dtime): ...
    def DrawAirLine(self, start, end, line_size, unit_len, color1, color2): ...
    def DrawAirLineWhite(self): ...
    def DrawCurAndNextSafeRegion(self, game_logic): ...
    def DrawDebugString(self, pos_dict, is_show=True): ...
    def DrawSafeRegion(self, draw_sr, region, color, clear=True): ...
    def DrawSafeRegionTips(self): ...
    def EnterFsmAirlineState(self, state): ...
    def EnterFsmAirlineStateByPaprachuteGamingState(self, parachute_stage): ...
    def EnterFsmSafeRegionStateBySrState(self, sr_state): ...
    def FixedAirLine(self, game_logic): ...
    def FixedDotLine(self, org, des, aircraftPos, lineStart): ...
    def GMShowSupplyTag(self, transforms): ...
    def GenAirline(self): ...
    def GenJumpTag(self): ...
    def GetAirDropShopBigMapInitScale(self, radius): ...
    def GetAvatarClientPositionAndYaw(self, avatar=None): ...
    def GetCenterTickEntity(self): ...
    def GetCenterUINode(self): ...
    def GetCommonMarkTag(self, guid): ...
    def GetDotLineState(self, sr_state): ...
    def GetFactionByVehicleFactionInfo(vehicle_faction_info): ...
    def GetFsmAirlineState(self): ...
    def GetFsmSafeRegionState(self, sr_state): ...
    def GetMiniMapParamKey(self): ...
    def GetSelfMarkPos(self): ...
    def GetTagScaleByRadius(self, radius, ui_image_radius): ...
    def GetVehicleTag(self, vehicle_id): ...
    def HaveTagHiddenReasonByTagType(self, tag_type, hidden_reason=1): ...
    def HideAllEnemyMarkTags(self): ...
    def HideAllUavTag(self): ...
    def HideCommonMarkToplogo(self, mark_id, hidden_reason): ...
    def HideEnemyMarkTagsByAvatarId(self, avatar_id): ...
    def HideMarkLine(self): ...
    def HideUavEnemyTagFull(self): ...
    def InitAirline(self): ...
    def InitData(self): ...
    def InitEnemyMarkShow(self): ...
    def InitMatrixNum(self): ...
    def InitRatio(self): ...
    def InitSafeRegion(self): ...
    def InitSelfTag(self): ...
    def InitTeamTag(self): ...
    def InitUavShow(self, force=False): ...
    def InitUavShowFull(self, force=False): ...
    def IsAircraftArrived(self): ...
    def IsCenterInPanelCut(self): ...
    def IsHasMarkLine(self): ...
    def IsTeamMemberInsideAny(self, pix): ...
    def IsTeamMemberInsideWithoutRotate(self, pix, cur_center_pix=None): ...
    def MapTransfer(self, screen_pos): ...
    def MarkLineTick(self, dtime): ...
    def MoveTagToImage(self, tag): ...
    def MoveTagToPanelMask(self, tag): ...
    def OnAirCraftArrived(self): ...
    def OnAvatarModelDestroy(self, avatar_id): ...
    def OnChaosUavRegionEnter(self, is_enter): ...
    def OnGetOnAircraft(self): ...
    def OnInfoChaos(self, is_chaos): ...
    def OnMapMissionMarkScaleDown(self, mark_id): ...
    def OnMapMissionMarkScaleUp(self, mark_id): ...
    def OnMiniMapRotateModeChanged(self, mode): ...
    def OnSafeRegionForeseeChange(self, info): ...
    def OnSafeRegionStateEnd(self): ...
    def OnSafeRegionStateShrink(self): ...
    def OnSafeRegionStateStable(self): ...
    def OnSafeRegionStateStart(self): ...
    def OnShowShutterEnergyMapGuide(self): ...
    def OnSpellShowingRange(self, spell_id, is_show): ...
    def OnVehicleIdInfoChanged(self, vehicle_id, vehicle_info, vehicle_faction_info): ...
    def OnWaitAircraft(self): ...
    def PercentToScale(self, percent): ...
    def PixToPos(self, pixx, pixy): ...
    def PosToPix(self, posx, posz): ...
    def PostCreateTagById(self, map_tag_id, tag_type, tag): ...
    def PreVisible(self, value): ...
    def RealYawToTagAngle(self, yaw): ...
    def ReconnectAirLine(self): ...
    def RecoverForeseeSafeRegion(self): ...
    def RefreshChaosUavArea(self): ...
    def RefreshDotLineFSM(self): ...
    def RefreshEnergyPlayerPos(self): ...
    def RefreshSafeRegion(self): ...
    def RefreshVehicleTags(self, vehicle_info_dict, vehicle_faction_info): ...
    def RemoveAirlineTick(self): ...
    def RemoveBorderProcessForTag(self, mark_id, tag): ...
    def RemoveChaosAreaTag(self, guid): ...
    def RemoveChaosUavArea(self, guid): ...
    def RemoveDotLineTick(self): ...
    def RemoveHiddenReasonForSafeRegion(self, hidden_reason): ...
    def RemoveHiddenReasonFullUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def RemoveHiddenReasonUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def RemoveSafeRegionShrinkTick(self): ...
    def RemoveTag(self, tag, remove_from_parent=True): ...
    def RemoveTagHiddenReasonByTagType(self, tag_type, hidden_reason=1): ...
    def RemoveTagHiddenReasonByTagTypeInRegion(self, tag_type, region, hidden_reason=1): ...
    def ResetCenterTagPos(self, center_tag=None): ...
    def ResetTeammateTickParam(self, teammate_id): ...
    def SafeRegionShrinkTick(self, dtime): ...
    def ScaleToPercent(self, scale): ...
    def SetAirLineInfo(self): ...
    def SetAirLineVisible(self, val): ...
    def SetBgText(self): ...
    def SetBgTexture(self): ...
    def SetBgTextureSplendor(self): ...
    def SetCenterNodeImgDir(self): ...
    def SetChaosUavArea(self, guid, target_area, has_chaos_effect): ...
    def SetImageCenter(self, pix): ...
    def SetImagePositionWithClamp(self, x, y): ...
    def SetImageRotation(self, angle): ...
    def SetScaleWithBase(self, scale, base=None): ...
    def SetSliderPercent(self, percent): ...
    def SetSpecifyPosToCenterBigMap(self, x, z): ...
    def SetTargetArea(self, target_area): ...
    def SetupBigMapScaleAndPos(self, scale, pos): ...
    def SetupMiniMapScale(self, scale): ...
    def SetupMiniMapScaleG(self, to_scale, duration): ...
    def ShowAirline(self, val): ...
    def ShowAirlineByValue(self, show_airline): ...
    def ShowCommonMarkToplogo(self, mark_id, hidden_reason): ...
    def ShowEnemyMark(self, avatar_infos, extra=None): ...
    def ShowMarkLine(self): ...
    def ShowPosRemindAnim(self): ...
    def ShowRadarEnermyPosition(self, pos): ...
    def ShowUav(self, caster_info, avatar_infos, level, spell_id, fix_pos, uav_range, start_time=None): ...
    def ShowUavFull(self, caster_info, avatar_infos, level, spell_id, fix_pos, refresh_circle, start_time=None): ...
    def ShowVehicleInfo(self, is_show): ...
    def SortZorderByStamp(self): ...
    def StartSimpleAOI(self, interval=3.0): ...
    def StartTick(self): ...
    def StopSimpleAOI(self): ...
    def StopTick(self): ...
    def TeamMemberStoryTick(self, dtime): ...
    def TeamMemberStoryTickBigMap(self, dtime): ...
    def TeamMemberStoryTickNew(self, dtime): ...
    def TickSimpleAOI(self): ...
    def TickVehicleTagInAoi(self): ...
    def UpdateAirlineTick(self, dtime): ...
    def UpdateCenterNode(self, tick_target=None): ...
    def UpdateCocosMiniMapTickParam(self): ...
    def VecToImageAngle(self, z_axis): ...
    def VehicleEnterAoiForMapTag(self, vehicle_id, is_enter): ...
    def YawToImageAngle(self, yaw): ...
    def YawToTagAngle(self, z_axis): ...
    def YawToTagAngleTuple(self, vec): ...
    def _CacheTagVehicle(self, vehicle_id): ...
    def _CheckDisturbEnable(self): ...
    def _CreateRadarEnermyTag(self): ...
    def _DrawCurAndNextSafeRegion(self, game_logic): ...
    def _GetCenterBigMapEntityYaw(self, entity): ...
    def _GetCurDisturbCenterInfo(self, key): ...
    def _GetDisturbCenterName(self, idx): ...
    def _GetDisturbFreeIdx(self): ...
    def _GetRadarTag(self): ...
    def _PostTagHiddenReason(self, tag_type, tag): ...
    def _RemoveRadarTag(self, tag): ...
    def _SetTagIconTexture(self, tag, icon): ...
    def _SetVehicleTagInfo(self, tag, vehicle_id, vehicle_info): ...
    def _SetupMiniMapScaleG(self, start_scale, to_scale, start_time, end_time, dtime): ...
    def _ShowPosRemindAnim(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_crack_by_guid(self, tag_type, guid, pos): ...
    @property
    def airline_color1(self): ...    @property
    def airline_color2(self): ...    @property
    def airline_color_passed(self): ...    def clear_all_crack(self, tag_type): ...
    def clear_border_process(self): ...
    def clear_crack_not_exist(self): ...
    @property
    def color_foresee_sr(self): ...    @property
    def color_next_sr(self): ...    @property
    def color_sr_block(self): ...    @property
    def color_sr_line(self): ...    @property
    def cur_center_pix(self): ...    def delay_refresh_crack(self, tag_type, check_cur_type=False): ...
    def frame_create_crack_tag(self, *args): ...
    @property
    def game_logic(self): ...    def get_player_tag_type(self): ...
    def get_show_game_logic_pos(self, game_logic): ...
    def get_show_tag_id(self): ...
    def get_show_tag_nodes(self): ...
    @property
    def markline_color_4b(self): ...    def refresh_zombie_crack_tag(self, show_tag_type=18): ...
    def remove_crack_by_guid(self, tag_type, guid): ...
    @property
    def scale(self): ...    def show_mini_border(self, tag_type): ...
    def show_tag_by_player_zombie(self): ...
    def stop_crack_delay_refresh_timer(self): ...
    def update_zombie_mark_aoi(self, *args): ...
    def zombie_create_one_tag(self, guid, tag_id, tag_type, pos, crack_tags): ...
    def zombie_remove_one_tag(self, guid, tag_type, tag): ...

class MapTagType(enum):
    AirDrop: int = 14
    AirDropShop: int = 7
    AirlineArrow: int = 2
    CenterTag: int = 5
    ChaosUav: int = 20
    Crack: int = 18
    EnergyStronghold: int = 19
    Hunt: int = 8
    LightAttackMark: int = 17
    MapText: int = 1
    Mission: int = 13
    Radar: int = 9
    Remind: int = 11
    RobotDebug: int = 3
    Shop: int = 16
    TalentMark: int = 15
    TeammateMark: int = 12
    TeammateTag: int = 6
    Uav: int = 4
    ValDrone: int = 23
    Vehicle: int = 10
    ZombieNeedle: int = 21
    name_to_values: dict = {'MapText': 1, 'AirlineArrow': 2, 'RobotDebug': 3, 'Uav': 4, 'CenterTag': 5, 'TeammateTag': 6, 'AirDropShop': 7, 'Hunt': 8, 'Radar': 9, 'Vehicle': 10, 'Remind': 11, 'TeammateMark': 12, 'Mission': 13, 'AirDrop': 14, 'TalentMark': 15, 'Shop': 16, 'LightAttackMark': 17, 'Crack': 18, 'EnergyStronghold': 19, 'ChaosUav': 20, 'ZombieNeedle': 21, 'ValDrone': 23}
    value_to_names: dict = {1: 'MapText', 2: 'AirlineArrow', 3: 'RobotDebug', 4: 'Uav', 5: 'CenterTag', 6: 'TeammateTag', 7: 'AirDropShop', 8: 'Hunt', 9: 'Radar', 10: 'Vehicle', 11: 'Remind', 12: 'TeammateMark', 13: 'Mission', 14: 'AirDrop', 15: 'TalentMark', 16: 'Shop', 17: 'LightAttackMark', 18: 'Crack', 19: 'EnergyStronghold', 20: 'ChaosUav', 21: 'ZombieNeedle', 23: 'ValDrone'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class ReplayRoomMapBaseMoba(MapBaseMoba):
    MAX_NUM: int = 10
    MAX_Z_ORDER: int = 10
    MIN_Z_ORDER: int = 7
    TEAM_TAG: type = <class 'gclient.gameplay.uicomponents.hud_room_spectator_comp.ReplayRoomMobaTeamTag'>

    def AddAirlineTick(self): ...
    def AddBorderProcessForTag(self, mark_id, tag, origin_pix=None): ...
    def AddChaosAreaTag(self, guid, target_area): ...
    def AddChaosUavArea(self, guid, target_area): ...
    def AddDotLineTick(self): ...
    def AddHiddenReasonForSafeRegion(self, hidden_reason): ...
    def AddHiddenReasonFullUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def AddHiddenReasonUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def AddRotateWithImageNode(self, widget): ...
    def AddTagHiddenReasonByTagType(self, tag_type, hidden_reason=1): ...
    def AddTagHiddenReasonByTagTypeInRegion(self, tag_type, region, hidden_reason=1): ...
    def AdjustMapPositionWithDiffPos(self, diff_pos): ...
    def BlockCurSafeRegion(self, region): ...
    def BorderTagTick(self, dtime): ...
    def CalTeamMemberPosInPanelMask(self, pix): ...
    def CalTeamMemberPosInPanelMaskAny(self, pix): ...
    def CenterStoryTick(self, dtime): ...
    def CenterStoryTickBigMap(self, dtime): ...
    def ChangeIconInBigMap(self, to_small): ...
    def CheckAndDelForseeRegion(self): ...
    def ClearDotLine(self): ...
    def ClearMarkLine(self): ...
    def ClearSrLine(self): ...
    def CommonTagStoryTick(self, dtime): ...
    def CommonTagStoryTickBigMap(self, dtime): ...
    def ConvertPaprachuteSateToFsmAirlineState(self, parachute_stage): ...
    def ConvertToImageSpace(self, pix): ...
    def ConvertToPanelCutSpace(self, pix): ...
    def CreateAndShowWindow(self): ...
    def CreateCommonMarkToplogo(self, mark_id, mark_info): ...
    def CreateHunterTag(self): ...
    def CreateMarkToplogo(self, pos, slot, mark_type, guid, extra_info=None, member_id=''): ...
    def CreateOrRefreshRobotTag(self, robot_info): ...
    def CreateTag(self, src_img, zorder=2, anchor=(0.5, 0.5), anchor_scale=(0.0, 0.0), parent=None, scale=1, name=''): ...
    def CreateTagById(self, map_tag_id, wrapper=<class 'gclient.gameplay.uicomponents.map_tags.MapTagBase'>, wrapper_info=None, parent=None, scale=None, name='', extra=None): ...
    def CreateText(self, zorder=2, anchor=(0.5, 0.5), anchor_scale=(0.0, 0.0), parent=None, scale=1, fnt_size=15, name='', font_name='', outline_size=0, outline_color=(0, 0, 0, 255)): ...
    def DestroyCommonMarkToplogo(self, mark_id): ...
    def DestroyMarkToplogo(self, slot, mark_type, guid): ...
    def DotLineTick(self, dtime): ...
    def DrawAirLine(self, start, end, line_size, unit_len, color1, color2): ...
    def DrawAirLineWhite(self): ...
    def DrawCurAndNextSafeRegion(self, game_logic): ...
    def DrawDebugString(self, pos_dict, is_show=True): ...
    def DrawSafeRegion(self, draw_sr, region, color, clear=True): ...
    def DrawSafeRegionTips(self): ...
    def EnterFsmAirlineState(self, state): ...
    def EnterFsmAirlineStateByPaprachuteGamingState(self, parachute_stage): ...
    def EnterFsmSafeRegionStateBySrState(self, sr_state): ...
    def FixedAirLine(self, game_logic): ...
    def FixedDotLine(self, org, des, aircraftPos, lineStart): ...
    def GMShowSupplyTag(self, transforms): ...
    def GenAirline(self): ...
    def GenJumpTag(self): ...
    def GetAirDropShopBigMapInitScale(self, radius): ...
    def GetAvatarClientPositionAndYaw(self, avatar=None): ...
    def GetCenterTickEntity(self): ...
    def GetCenterUINode(self): ...
    def GetCommonMarkTag(self, guid): ...
    def GetDotLineState(self, sr_state): ...
    def GetFactionByVehicleFactionInfo(vehicle_faction_info): ...
    def GetFsmAirlineState(self): ...
    def GetFsmSafeRegionState(self, sr_state): ...
    def GetMiniMapParamKey(self): ...
    def GetSelfMarkPos(self): ...
    def GetTagScaleByRadius(self, radius, ui_image_radius): ...
    def GetVehicleTag(self, vehicle_id): ...
    def HaveTagHiddenReasonByTagType(self, tag_type, hidden_reason=1): ...
    def HideAllEnemyMarkTags(self): ...
    def HideAllUavTag(self): ...
    def HideCommonMarkToplogo(self, mark_id, hidden_reason): ...
    def HideEnemyMarkTagsByAvatarId(self, avatar_id): ...
    def HideMarkLine(self): ...
    def HideUavEnemyTagFull(self): ...
    def InitAirline(self): ...
    def InitData(self): ...
    def InitEnemyMarkShow(self): ...
    def InitMatrixNum(self): ...
    def InitRatio(self): ...
    def InitSafeRegion(self): ...
    def InitSelfTag(self): ...
    def InitTeamTag(self): ...
    def InitUavShow(self, force=False): ...
    def InitUavShowFull(self, force=False): ...
    def IsAircraftArrived(self): ...
    def IsCenterInPanelCut(self): ...
    def IsHasMarkLine(self): ...
    def IsTeamMemberInsideAny(self, pix): ...
    def IsTeamMemberInsideWithoutRotate(self, pix, cur_center_pix=None): ...
    def MapTransfer(self, screen_pos): ...
    def MarkLineTick(self, dtime): ...
    def MoveTagToImage(self, tag): ...
    def MoveTagToPanelMask(self, tag): ...
    def OnAirCraftArrived(self): ...
    def OnAvatarModelDestroy(self, avatar_id): ...
    def OnChaosUavRegionEnter(self, is_enter): ...
    def OnGetOnAircraft(self): ...
    def OnInfoChaos(self, is_chaos): ...
    def OnMapMissionMarkScaleDown(self, mark_id): ...
    def OnMapMissionMarkScaleUp(self, mark_id): ...
    def OnMiniMapRotateModeChanged(self, mode): ...
    def OnSafeRegionForeseeChange(self, info): ...
    def OnSafeRegionStateEnd(self): ...
    def OnSafeRegionStateShrink(self): ...
    def OnSafeRegionStateStable(self): ...
    def OnSafeRegionStateStart(self): ...
    def OnShowShutterEnergyMapGuide(self): ...
    def OnSpellShowingRange(self, spell_id, is_show): ...
    def OnVehicleIdInfoChanged(self, vehicle_id, vehicle_info, vehicle_faction_info): ...
    def OnWaitAircraft(self): ...
    def PercentToScale(self, percent): ...
    def PixToPos(self, pixx, pixy): ...
    def PosToPix(self, posx, posz): ...
    def PostCreateTagById(self, map_tag_id, tag_type, tag): ...
    def PreVisible(self, value): ...
    def RealYawToTagAngle(self, yaw): ...
    def ReconnectAirLine(self): ...
    def RecoverForeseeSafeRegion(self): ...
    def RefreshChaosUavArea(self): ...
    def RefreshDotLineFSM(self): ...
    def RefreshEnergyPlayerPos(self): ...
    def RefreshSafeRegion(self): ...
    def RefreshVehicleTags(self, vehicle_info_dict, vehicle_faction_info): ...
    def RemoveAirlineTick(self): ...
    def RemoveBorderProcessForTag(self, mark_id, tag): ...
    def RemoveChaosAreaTag(self, guid): ...
    def RemoveChaosUavArea(self, guid): ...
    def RemoveDotLineTick(self): ...
    def RemoveHiddenReasonForSafeRegion(self, hidden_reason): ...
    def RemoveHiddenReasonFullUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def RemoveHiddenReasonUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def RemoveSafeRegionShrinkTick(self): ...
    def RemoveTag(self, tag, remove_from_parent=True): ...
    def RemoveTagHiddenReasonByTagType(self, tag_type, hidden_reason=1): ...
    def RemoveTagHiddenReasonByTagTypeInRegion(self, tag_type, region, hidden_reason=1): ...
    def ResetCenterTagPos(self, center_tag=None): ...
    def ResetTeammateTickParam(self, teammate_id): ...
    def SafeRegionShrinkTick(self, dtime): ...
    def ScaleToPercent(self, scale): ...
    def SetAirLineInfo(self): ...
    def SetAirLineVisible(self, val): ...
    def SetBgText(self): ...
    def SetBgTexture(self): ...
    def SetBgTextureSplendor(self): ...
    def SetCenterNodeImgDir(self): ...
    def SetChaosUavArea(self, guid, target_area, has_chaos_effect): ...
    def SetImageCenter(self, pix): ...
    def SetImagePositionWithClamp(self, x, y): ...
    def SetImageRotation(self, angle): ...
    def SetScaleWithBase(self, scale, base=None): ...
    def SetSliderPercent(self, percent): ...
    def SetSpecifyPosToCenterBigMap(self, x, z): ...
    def SetTargetArea(self, target_area): ...
    def SetupBigMapScaleAndPos(self, scale, pos): ...
    def SetupMiniMapScale(self, scale): ...
    def SetupMiniMapScaleG(self, to_scale, duration): ...
    def ShowAirline(self, val): ...
    def ShowAirlineByValue(self, show_airline): ...
    def ShowCommonMarkToplogo(self, mark_id, hidden_reason): ...
    def ShowEnemyMark(self, avatar_infos, extra=None): ...
    def ShowMarkLine(self): ...
    def ShowPosRemindAnim(self): ...
    def ShowRadarEnermyPosition(self, pos): ...
    def ShowUav(self, caster_info, avatar_infos, level, spell_id, fix_pos, uav_range, start_time=None): ...
    def ShowUavFull(self, caster_info, avatar_infos, level, spell_id, fix_pos, refresh_circle, start_time=None): ...
    def ShowVehicleInfo(self, is_show): ...
    def SortZorderByStamp(self): ...
    def StartSimpleAOI(self, interval=3.0): ...
    def StartTick(self): ...
    def StopSimpleAOI(self): ...
    def StopTick(self): ...
    def TeamMemberStoryTick(self, dtime): ...
    def TeamMemberStoryTickBigMap(self, dtime): ...
    def TeamMemberStoryTickNew(self, dtime): ...
    def TickSimpleAOI(self): ...
    def TickVehicleTagInAoi(self): ...
    def UpdateAirlineTick(self, dtime): ...
    def UpdateCenterNode(self, tick_target=None): ...
    def UpdateCocosMiniMapTickParam(self): ...
    def VecToImageAngle(self, z_axis): ...
    def VehicleEnterAoiForMapTag(self, vehicle_id, is_enter): ...
    def YawToImageAngle(self, yaw): ...
    def YawToTagAngle(self, z_axis): ...
    def YawToTagAngleTuple(self, vec): ...
    def _CacheTagVehicle(self, vehicle_id): ...
    def _CheckDisturbEnable(self): ...
    def _CreateRadarEnermyTag(self): ...
    def _DrawCurAndNextSafeRegion(self, game_logic): ...
    def _GetCenterBigMapEntityYaw(self, entity): ...
    def _GetCurDisturbCenterInfo(self, key): ...
    def _GetDisturbCenterName(self, idx): ...
    def _GetDisturbFreeIdx(self): ...
    def _GetRadarTag(self): ...
    def _PostTagHiddenReason(self, tag_type, tag): ...
    def _RemoveRadarTag(self, tag): ...
    def _SetTagIconTexture(self, tag, icon): ...
    def _SetVehicleTagInfo(self, tag, vehicle_id, vehicle_info): ...
    def _SetupMiniMapScaleG(self, start_scale, to_scale, start_time, end_time, dtime): ...
    def _ShowPosRemindAnim(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def airline_color1(self): ...    @property
    def airline_color2(self): ...    @property
    def airline_color_passed(self): ...    @property
    def color_foresee_sr(self): ...    @property
    def color_next_sr(self): ...    @property
    def color_sr_block(self): ...    @property
    def color_sr_line(self): ...    @property
    def cur_center_pix(self): ...    @property
    def game_logic(self): ...    @property
    def markline_color_4b(self): ...    @property
    def scale(self): ...
class ReplayRoomMapBaseZombie(ReplayRoomMapBaseMoba):
    MAX_NUM: int = 10
    MAX_Z_ORDER: int = 10
    MIN_Z_ORDER: int = 7
    TEAM_TAG: type = <class 'gclient.gameplay.uicomponents.hud_room_spectator_comp.ReplayRoomMobaTeamTag'>

    def AddAirlineTick(self): ...
    def AddBorderProcessForTag(self, mark_id, tag, origin_pix=None): ...
    def AddChaosAreaTag(self, guid, target_area): ...
    def AddChaosUavArea(self, guid, target_area): ...
    def AddDotLineTick(self): ...
    def AddHiddenReasonForSafeRegion(self, hidden_reason): ...
    def AddHiddenReasonFullUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def AddHiddenReasonUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def AddRotateWithImageNode(self, widget): ...
    def AddTagHiddenReasonByTagType(self, tag_type, hidden_reason=1): ...
    def AddTagHiddenReasonByTagTypeInRegion(self, tag_type, region, hidden_reason=1): ...
    def AdjustMapPositionWithDiffPos(self, diff_pos): ...
    def BlockCurSafeRegion(self, region): ...
    def BorderTagTick(self, dtime): ...
    def CalTeamMemberPosInPanelMask(self, pix): ...
    def CalTeamMemberPosInPanelMaskAny(self, pix): ...
    def CenterStoryTick(self, dtime): ...
    def CenterStoryTickBigMap(self, dtime): ...
    def ChangeIconInBigMap(self, to_small): ...
    def CheckAndDelForseeRegion(self): ...
    def ClearDotLine(self): ...
    def ClearMarkLine(self): ...
    def ClearSrLine(self): ...
    def CommonTagStoryTick(self, dtime): ...
    def CommonTagStoryTickBigMap(self, dtime): ...
    def ConvertPaprachuteSateToFsmAirlineState(self, parachute_stage): ...
    def ConvertToImageSpace(self, pix): ...
    def ConvertToPanelCutSpace(self, pix): ...
    def CreateAndShowWindow(self): ...
    def CreateCommonMarkToplogo(self, mark_id, mark_info): ...
    def CreateHunterTag(self): ...
    def CreateMarkToplogo(self, pos, slot, mark_type, guid, extra_info=None, member_id=''): ...
    def CreateOrRefreshRobotTag(self, robot_info): ...
    def CreateTag(self, src_img, zorder=2, anchor=(0.5, 0.5), anchor_scale=(0.0, 0.0), parent=None, scale=1, name=''): ...
    def CreateTagById(self, map_tag_id, wrapper=<class 'gclient.gameplay.uicomponents.map_tags.MapTagBase'>, wrapper_info=None, parent=None, scale=None, name='', extra=None): ...
    def CreateText(self, zorder=2, anchor=(0.5, 0.5), anchor_scale=(0.0, 0.0), parent=None, scale=1, fnt_size=15, name='', font_name='', outline_size=0, outline_color=(0, 0, 0, 255)): ...
    def DestroyCommonMarkToplogo(self, mark_id): ...
    def DestroyMarkToplogo(self, slot, mark_type, guid): ...
    def DotLineTick(self, dtime): ...
    def DrawAirLine(self, start, end, line_size, unit_len, color1, color2): ...
    def DrawAirLineWhite(self): ...
    def DrawCurAndNextSafeRegion(self, game_logic): ...
    def DrawDebugString(self, pos_dict, is_show=True): ...
    def DrawSafeRegion(self, draw_sr, region, color, clear=True): ...
    def DrawSafeRegionTips(self): ...
    def EnterFsmAirlineState(self, state): ...
    def EnterFsmAirlineStateByPaprachuteGamingState(self, parachute_stage): ...
    def EnterFsmSafeRegionStateBySrState(self, sr_state): ...
    def FixedAirLine(self, game_logic): ...
    def FixedDotLine(self, org, des, aircraftPos, lineStart): ...
    def GMShowSupplyTag(self, transforms): ...
    def GenAirline(self): ...
    def GenJumpTag(self): ...
    def GetAirDropShopBigMapInitScale(self, radius): ...
    def GetAvatarClientPositionAndYaw(self, avatar=None): ...
    def GetCenterTickEntity(self): ...
    def GetCenterUINode(self): ...
    def GetCommonMarkTag(self, guid): ...
    def GetDotLineState(self, sr_state): ...
    def GetFactionByVehicleFactionInfo(vehicle_faction_info): ...
    def GetFsmAirlineState(self): ...
    def GetFsmSafeRegionState(self, sr_state): ...
    def GetMiniMapParamKey(self): ...
    def GetSelfMarkPos(self): ...
    def GetTagScaleByRadius(self, radius, ui_image_radius): ...
    def GetVehicleTag(self, vehicle_id): ...
    def HaveTagHiddenReasonByTagType(self, tag_type, hidden_reason=1): ...
    def HideAllEnemyMarkTags(self): ...
    def HideAllUavTag(self): ...
    def HideCommonMarkToplogo(self, mark_id, hidden_reason): ...
    def HideEnemyMarkTagsByAvatarId(self, avatar_id): ...
    def HideMarkLine(self): ...
    def HideUavEnemyTagFull(self): ...
    def InitAirline(self): ...
    def InitData(self): ...
    def InitEnemyMarkShow(self): ...
    def InitMatrixNum(self): ...
    def InitRatio(self): ...
    def InitSafeRegion(self): ...
    def InitSelfTag(self): ...
    def InitTeamTag(self): ...
    def InitUavShow(self, force=False): ...
    def InitUavShowFull(self, force=False): ...
    def IsAircraftArrived(self): ...
    def IsCenterInPanelCut(self): ...
    def IsHasMarkLine(self): ...
    def IsTeamMemberInsideAny(self, pix): ...
    def IsTeamMemberInsideWithoutRotate(self, pix, cur_center_pix=None): ...
    def MapTransfer(self, screen_pos): ...
    def MarkLineTick(self, dtime): ...
    def MoveTagToImage(self, tag): ...
    def MoveTagToPanelMask(self, tag): ...
    def OnAirCraftArrived(self): ...
    def OnAvatarModelDestroy(self, avatar_id): ...
    def OnChaosUavRegionEnter(self, is_enter): ...
    def OnGetOnAircraft(self): ...
    def OnInfoChaos(self, is_chaos): ...
    def OnMapMissionMarkScaleDown(self, mark_id): ...
    def OnMapMissionMarkScaleUp(self, mark_id): ...
    def OnMiniMapRotateModeChanged(self, mode): ...
    def OnSafeRegionForeseeChange(self, info): ...
    def OnSafeRegionStateEnd(self): ...
    def OnSafeRegionStateShrink(self): ...
    def OnSafeRegionStateStable(self): ...
    def OnSafeRegionStateStart(self): ...
    def OnShowShutterEnergyMapGuide(self): ...
    def OnSpellShowingRange(self, spell_id, is_show): ...
    def OnVehicleIdInfoChanged(self, vehicle_id, vehicle_info, vehicle_faction_info): ...
    def OnWaitAircraft(self): ...
    def PercentToScale(self, percent): ...
    def PixToPos(self, pixx, pixy): ...
    def PosToPix(self, posx, posz): ...
    def PostCreateTagById(self, map_tag_id, tag_type, tag): ...
    def PreVisible(self, value): ...
    def RealYawToTagAngle(self, yaw): ...
    def ReconnectAirLine(self): ...
    def RecoverForeseeSafeRegion(self): ...
    def RefreshChaosUavArea(self): ...
    def RefreshDotLineFSM(self): ...
    def RefreshEnergyPlayerPos(self): ...
    def RefreshSafeRegion(self): ...
    def RefreshVehicleTags(self, vehicle_info_dict, vehicle_faction_info): ...
    def RemoveAirlineTick(self): ...
    def RemoveBorderProcessForTag(self, mark_id, tag): ...
    def RemoveChaosAreaTag(self, guid): ...
    def RemoveChaosUavArea(self, guid): ...
    def RemoveDotLineTick(self): ...
    def RemoveHiddenReasonForSafeRegion(self, hidden_reason): ...
    def RemoveHiddenReasonFullUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def RemoveHiddenReasonUavTagByAvatarId(self, avatar_id, hidden_reason): ...
    def RemoveSafeRegionShrinkTick(self): ...
    def RemoveTag(self, tag, remove_from_parent=True): ...
    def RemoveTagHiddenReasonByTagType(self, tag_type, hidden_reason=1): ...
    def RemoveTagHiddenReasonByTagTypeInRegion(self, tag_type, region, hidden_reason=1): ...
    def ResetCenterTagPos(self, center_tag=None): ...
    def ResetTeammateTickParam(self, teammate_id): ...
    def SafeRegionShrinkTick(self, dtime): ...
    def ScaleToPercent(self, scale): ...
    def SetAirLineInfo(self): ...
    def SetAirLineVisible(self, val): ...
    def SetBgText(self): ...
    def SetBgTexture(self): ...
    def SetBgTextureSplendor(self): ...
    def SetCenterNodeImgDir(self): ...
    def SetChaosUavArea(self, guid, target_area, has_chaos_effect): ...
    def SetImageCenter(self, pix): ...
    def SetImagePositionWithClamp(self, x, y): ...
    def SetImageRotation(self, angle): ...
    def SetScaleWithBase(self, scale, base=None): ...
    def SetSliderPercent(self, percent): ...
    def SetSpecifyPosToCenterBigMap(self, x, z): ...
    def SetTargetArea(self, target_area): ...
    def SetupBigMapScaleAndPos(self, scale, pos): ...
    def SetupMiniMapScale(self, scale): ...
    def SetupMiniMapScaleG(self, to_scale, duration): ...
    def ShowAirline(self, val): ...
    def ShowAirlineByValue(self, show_airline): ...
    def ShowCommonMarkToplogo(self, mark_id, hidden_reason): ...
    def ShowEnemyMark(self, avatar_infos, extra=None): ...
    def ShowMarkLine(self): ...
    def ShowPosRemindAnim(self): ...
    def ShowRadarEnermyPosition(self, pos): ...
    def ShowUav(self, caster_info, avatar_infos, level, spell_id, fix_pos, uav_range, start_time=None): ...
    def ShowUavFull(self, caster_info, avatar_infos, level, spell_id, fix_pos, refresh_circle, start_time=None): ...
    def ShowVehicleInfo(self, is_show): ...
    def SortZorderByStamp(self): ...
    def StartSimpleAOI(self, interval=3.0): ...
    def StartTick(self): ...
    def StopSimpleAOI(self): ...
    def StopTick(self): ...
    def TeamMemberStoryTick(self, dtime): ...
    def TeamMemberStoryTickBigMap(self, dtime): ...
    def TeamMemberStoryTickNew(self, dtime): ...
    def TickSimpleAOI(self): ...
    def TickVehicleTagInAoi(self): ...
    def UpdateAirlineTick(self, dtime): ...
    def UpdateCenterNode(self, tick_target=None): ...
    def UpdateCocosMiniMapTickParam(self): ...
    def VecToImageAngle(self, z_axis): ...
    def VehicleEnterAoiForMapTag(self, vehicle_id, is_enter): ...
    def YawToImageAngle(self, yaw): ...
    def YawToTagAngle(self, z_axis): ...
    def YawToTagAngleTuple(self, vec): ...
    def _CacheTagVehicle(self, vehicle_id): ...
    def _CheckDisturbEnable(self): ...
    def _CreateRadarEnermyTag(self): ...
    def _DrawCurAndNextSafeRegion(self, game_logic): ...
    def _GetCenterBigMapEntityYaw(self, entity): ...
    def _GetCurDisturbCenterInfo(self, key): ...
    def _GetDisturbCenterName(self, idx): ...
    def _GetDisturbFreeIdx(self): ...
    def _GetRadarTag(self): ...
    def _PostTagHiddenReason(self, tag_type, tag): ...
    def _RemoveRadarTag(self, tag): ...
    def _SetTagIconTexture(self, tag, icon): ...
    def _SetVehicleTagInfo(self, tag, vehicle_id, vehicle_info): ...
    def _SetupMiniMapScaleG(self, start_scale, to_scale, start_time, end_time, dtime): ...
    def _ShowPosRemindAnim(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_crack_by_guid(self, tag_type, guid, pos): ...
    @property
    def airline_color1(self): ...    @property
    def airline_color2(self): ...    @property
    def airline_color_passed(self): ...    def clear_all_crack(self, tag_type): ...
    def clear_border_process(self): ...
    def clear_crack_not_exist(self): ...
    @property
    def color_foresee_sr(self): ...    @property
    def color_next_sr(self): ...    @property
    def color_sr_block(self): ...    @property
    def color_sr_line(self): ...    @property
    def cur_center_pix(self): ...    def delay_refresh_crack(self, tag_type, check_cur_type=False): ...
    def frame_create_crack_tag(self, *args): ...
    @property
    def game_logic(self): ...    def get_player_tag_type(self): ...
    def get_show_game_logic_pos(self, game_logic): ...
    def get_show_tag_id(self): ...
    def get_show_tag_nodes(self): ...
    @property
    def markline_color_4b(self): ...    def refresh_zombie_crack_tag(self, show_tag_type=18): ...
    def remove_crack_by_guid(self, tag_type, guid): ...
    @property
    def scale(self): ...    def show_mini_border(self, tag_type): ...
    def show_tag_by_player_zombie(self): ...
    def stop_crack_delay_refresh_timer(self): ...
    def update_zombie_mark_aoi(self, *args): ...
    def zombie_create_one_tag(self, guid, tag_id, tag_type, pos, crack_tags): ...
    def zombie_remove_one_tag(self, guid, tag_type, tag): ...

class SimpleAOI(object):
    def AddEntry(self, entry, x, y): ...
    def QueryEntries(self, x, y, radius): ...
    def RemoveEntry(self, entry): ...
    def UpdateEntry(self, entry, x, y): ...
    def _Locate(self, x, y): ...

class ZombieCrackTagComp(object):
    def add_crack_by_guid(self, tag_type, guid, pos): ...
    def clear_all_crack(self, tag_type): ...
    def clear_border_process(self): ...
    def clear_crack_not_exist(self): ...
    def delay_refresh_crack(self, tag_type, check_cur_type=False): ...
    def frame_create_crack_tag(self, *args): ...
    def get_player_tag_type(self): ...
    def get_show_game_logic_pos(self, game_logic): ...
    def get_show_tag_id(self): ...
    def get_show_tag_nodes(self): ...
    def refresh_zombie_crack_tag(self, show_tag_type=18): ...
    def remove_crack_by_guid(self, tag_type, guid): ...
    def show_mini_border(self, tag_type): ...
    def show_tag_by_player_zombie(self): ...
    def stop_crack_delay_refresh_timer(self): ...
    def update_zombie_mark_aoi(self, *args): ...
    def zombie_create_one_tag(self, guid, tag_id, tag_type, pos, crack_tags): ...
    def zombie_remove_one_tag(self, guid, tag_type, tag): ...

class ZombieSimpleMarkComp(SimpleMarkComp):
    def ChangeIconInBigMap(self, to_small): ...
    def CreateCommonMarkToplogo(self, mark_id, mark_info): ...
    def DestroyCommonMarkToplogo(self, mark_id): ...
    def GetCommonMarkTag(self, guid): ...
    def HideCommonMarkToplogo(self, mark_id, hidden_reason): ...
    def OnMapMissionMarkScaleDown(self, mark_id): ...
    def OnMapMissionMarkScaleUp(self, mark_id): ...
    def ShowCommonMarkToplogo(self, mark_id, hidden_reason): ...
    def StartSimpleAOI(self, interval=3.0): ...
    def StopSimpleAOI(self): ...
    def TickSimpleAOI(self): ...

class defaultdict(dict):
    clear: method_descriptor = <method 'clear' of 'dict' objects>
    copy: method_descriptor = <method 'copy' of 'collections.defaultdict' objects>
    default_factory: member_descriptor = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys: builtin_function_or_method = <built-in method fromkeys of type object at 0x702850e7d8>
    get: method_descriptor = <method 'get' of 'dict' objects>
    items: method_descriptor = <method 'items' of 'dict' objects>
    keys: method_descriptor = <method 'keys' of 'dict' objects>
    pop: method_descriptor = <method 'pop' of 'dict' objects>
    popitem: method_descriptor = <method 'popitem' of 'dict' objects>
    setdefault: method_descriptor = <method 'setdefault' of 'dict' objects>
    update: method_descriptor = <method 'update' of 'dict' objects>
    values: method_descriptor = <method 'values' of 'dict' objects>

class partial(object):
    args: member_descriptor = <member 'args' of 'functools.partial' objects>
    func: member_descriptor = <member 'func' of 'functools.partial' objects>
    keywords: member_descriptor = <member 'keywords' of 'functools.partial' objects>


def Components(*components, **kwargs): ...

