# module: gclient.util.cc_client

import MChat
import MConfig
import MEngine
import MPlatform
import cc_util
import cconst
import events
import icc_voice
import json
import os
import six2
import sys

class CCClient(object):
    OnLeaveInactive: AsyncDescriptor = <gshare.async_util.AsyncDescriptor object at 0x70b06bf2d0>
    _instance: CCClient = <gclient.util.cc_client.CCClient object at 0x7005e1d090>

    def CloseAllMike(self): ...
    def CloseCCMini(self): ...
    def EidRecordClose(self, eid): ...
    def EidRecordOpen(self, eid): ...
    def Enable3DReceiver(self, enable): ...
    def EnableFadingForSpace(self, enable): ...
    def EnableMike(self, enable, channel=None): ...
    def EnableOutputWwisePlugin(self, session_id, enable): ...
    def EnablePlayback(self, enable, channel): ...
    def EnableWwiseCompatible(self, enable): ...
    def EnsureStart(self): ...
    def IgnoreUidVoice(self, uid, ignore=True, sid=0): ...
    def IgnoreVoice(self, eid, ignore=True, sid=0): ...
    def ListenStream(self, streamid, listen=True): ...
    def LoginSession(self, channel, info, cb=None): ...
    def LogoutSession(self, channel): ...
    def MutePlay(self, mute=True): ...
    def OnEnterInactive(self): ...
    def OnlyListenEids(self, channel, enable, eids): ...
    def QuerySpeakingList(self, sid, cb): ...
    def Recordlastaudio(self): ...
    def ResetWhenHeadsetChange(self, enable): ...
    def SessionRouteChanged(self, status): ...
    def Set3DSourceRadius(self, radius): ...
    def Set3DVoice(self, status): ...
    def Set3DVoiceBySessionRoute(self): ...
    def SetAsWWiseSource(self, session_id, val): ...
    def SetBlueToothMic(self): ...
    def SetEidVolumeForTargetChannel(self, eid, channel, percent=100): ...
    def SetMickVol(self, ratio=1): ...
    def SetVolume(self, percent): ...
    def StartCCMini(self): ...
    def UpdatePlayerPos(self, pos): ...
    def _ControlMini(self, ctrl_info, context=0, cb=None): ...
    def _ControlMiniString(self, controlString, context=0, cb=None): ...
    def _CreateSession(self): ...
    def _DealResultDefaultContext(self, json_dict): ...
    def _DealResultSystemContext(self, jsonDict): ...
    def _DispatchResult(self, json_str, context): ...
    def _OnCreateSession(self, jsonDict): ...
    def _ResetData(self): ...
    def _ResetDevice(self): ...
    def _ResetEngine(self): ...
    def _SetEidVolume(self, eid, sid, percent=100): ...
    def _StopEngine(self): ...

class ControlMiniContext(enum):
    CONTEXT_CREATE_SESSION: int = 1
    CONTEXT_DEFAULT: int = 0
    CONTEXT_GET_SPEAKING_LIST: int = 400
    CONTEXT_LOGIN: int = 100
    CONTEXT_LOGOUT_SESSION: int = 3
    CONTEXT_VOL: int = 300
    name_to_values: dict = {'CONTEXT_DEFAULT': 0, 'CONTEXT_CREATE_SESSION': 1, 'CONTEXT_LOGOUT_SESSION': 3, 'CONTEXT_LOGIN': 100, 'CONTEXT_VOL': 300, 'CONTEXT_GET_SPEAKING_LIST': 400}
    value_to_names: dict = {0: 'CONTEXT_DEFAULT', 1: 'CONTEXT_CREATE_SESSION', 3: 'CONTEXT_LOGOUT_SESSION', 100: 'CONTEXT_LOGIN', 300: 'CONTEXT_VOL', 400: 'CONTEXT_GET_SPEAKING_LIST'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class SingletonMeta(type):
    mro: method_descriptor = <method 'mro' of 'type' objects>

class enum(object):
    name_to_values: dict = {}
    value_to_names: dict = {}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...


def Async(tag=0): ...

