# module: gclient.util.cclan_util

import events
import iclan
import six2

clan_components: tuple = (<class 'gclient.util.cclan_util.BasicComponent'>, <class 'gclient.util.cclan_util.MemberComponent'>)

class BasicComponent(object):
    ach_logs: member_descriptor = <member 'ach_logs' of 'BasicComponent' objects>
    board: member_descriptor = <member 'board' of 'BasicComponent' objects>
    change_name_time: member_descriptor = <member 'change_name_time' of 'BasicComponent' objects>
    country_icon: member_descriptor = <member 'country_icon' of 'BasicComponent' objects>
    creator: member_descriptor = <member 'creator' of 'BasicComponent' objects>
    icon: member_descriptor = <member 'icon' of 'BasicComponent' objects>
    id: member_descriptor = <member 'id' of 'BasicComponent' objects>
    mail_sent: member_descriptor = <member 'mail_sent' of 'BasicComponent' objects>
    name: member_descriptor = <member 'name' of 'BasicComponent' objects>
    no: member_descriptor = <member 'no' of 'BasicComponent' objects>
    region_pids: member_descriptor = <member 'region_pids' of 'BasicComponent' objects>
    styles: member_descriptor = <member 'styles' of 'BasicComponent' objects>

class CClan(object):
    ach_logs: member_descriptor = <member 'ach_logs' of 'CClan' objects>
    appliers: member_descriptor = <member 'appliers' of 'CClan' objects>
    apply_accept: member_descriptor = <member 'apply_accept' of 'CClan' objects>
    apply_level: member_descriptor = <member 'apply_level' of 'CClan' objects>
    apply_score: member_descriptor = <member 'apply_score' of 'CClan' objects>
    apply_verify: member_descriptor = <member 'apply_verify' of 'CClan' objects>
    board: member_descriptor = <member 'board' of 'CClan' objects>
    ceo: member_descriptor = <member 'ceo' of 'CClan' objects>
    change_name_time: member_descriptor = <member 'change_name_time' of 'CClan' objects>
    country_icon: member_descriptor = <member 'country_icon' of 'CClan' objects>
    creator: member_descriptor = <member 'creator' of 'CClan' objects>
    current_members: member_descriptor = <member 'current_members' of 'CClan' objects>
    icon: member_descriptor = <member 'icon' of 'CClan' objects>
    id: member_descriptor = <member 'id' of 'CClan' objects>
    is_ready: member_descriptor = <member 'is_ready' of 'CClan' objects>
    mail_sent: member_descriptor = <member 'mail_sent' of 'CClan' objects>
    managers: member_descriptor = <member 'managers' of 'CClan' objects>
    max_members: member_descriptor = <member 'max_members' of 'CClan' objects>
    member_info: member_descriptor = <member 'member_info' of 'CClan' objects>
    members: member_descriptor = <member 'members' of 'CClan' objects>
    name: member_descriptor = <member 'name' of 'CClan' objects>
    no: member_descriptor = <member 'no' of 'CClan' objects>
    online: member_descriptor = <member 'online' of 'CClan' objects>
    player_info: member_descriptor = <member 'player_info' of 'CClan' objects>
    player_info_team_info: member_descriptor = <member 'player_info_team_info' of 'CClan' objects>
    region_pids: member_descriptor = <member 'region_pids' of 'CClan' objects>
    shield_appliers: member_descriptor = <member 'shield_appliers' of 'CClan' objects>
    styles: member_descriptor = <member 'styles' of 'CClan' objects>

    def CountRole(self, role): ...
    def GetApplierList(self): ...
    def GetManagersDict(self): ...
    def GetMemberList(self, sort_key=None): ...
    def GetMemberPlayerInfo(self, member_id): ...
    def GetPlayerInfo(self, player_id, default=None): ...
    def GetRole(self, guid): ...
    def IsManager(self, player_id): ...
    def IsRole(self, *target_role, **kwargs): ...
    def IsRoleMemberMax(self, role): ...
    def RemoveMember(self, target_id): ...
    def UpdateMemberRole(self, target_id, role): ...
    def UpdatePlayerInfo(self, player_id, info): ...
    def UpdatePlayerInfo_TeamInfo(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_set_appliers(self, old): ...
    def _on_set_members(self, old): ...
    def _postComponents(self, bdict): ...
    def _pre_set_player_info(self, v): ...
    def _tickComponents(self, dtime): ...
    def _updateOne(self, k, v): ...
    def get(self, key, default=None): ...
    def update(self, data): ...

class MemberComponent(object):
    appliers: member_descriptor = <member 'appliers' of 'MemberComponent' objects>
    apply_accept: member_descriptor = <member 'apply_accept' of 'MemberComponent' objects>
    apply_level: member_descriptor = <member 'apply_level' of 'MemberComponent' objects>
    apply_score: member_descriptor = <member 'apply_score' of 'MemberComponent' objects>
    apply_verify: member_descriptor = <member 'apply_verify' of 'MemberComponent' objects>
    ceo: member_descriptor = <member 'ceo' of 'MemberComponent' objects>
    current_members: member_descriptor = <member 'current_members' of 'MemberComponent' objects>
    managers: member_descriptor = <member 'managers' of 'MemberComponent' objects>
    max_members: member_descriptor = <member 'max_members' of 'MemberComponent' objects>
    member_info: member_descriptor = <member 'member_info' of 'MemberComponent' objects>
    members: member_descriptor = <member 'members' of 'MemberComponent' objects>
    online: member_descriptor = <member 'online' of 'MemberComponent' objects>
    player_info: member_descriptor = <member 'player_info' of 'MemberComponent' objects>
    player_info_team_info: member_descriptor = <member 'player_info_team_info' of 'MemberComponent' objects>
    shield_appliers: member_descriptor = <member 'shield_appliers' of 'MemberComponent' objects>

    def CountRole(self, role): ...
    def GetApplierList(self): ...
    def GetManagersDict(self): ...
    def GetMemberList(self, sort_key=None): ...
    def GetMemberPlayerInfo(self, member_id): ...
    def GetPlayerInfo(self, player_id, default=None): ...
    def GetRole(self, guid): ...
    def IsManager(self, player_id): ...
    def IsRole(self, *target_role, **kwargs): ...
    def IsRoleMemberMax(self, role): ...
    def RemoveMember(self, target_id): ...
    def UpdateMemberRole(self, target_id, role): ...
    def UpdatePlayerInfo(self, player_id, info): ...
    def UpdatePlayerInfo_TeamInfo(self): ...


def Components(*components, **kwargs): ...
def Property(name, default, flag=2): ...

