# module: gclient.util.CinematicsImp

import CinematicsUSImp
import GlobalData
import MCharacter
import MEngine
import MObject
import MRender
import MType
import json
import math
import six2

CUE_CINEMATICS_DISMISS_PERFORMER: int = 62105
CUE_CINEMATICS_DISMISS_PERFORMERS: int = 62101
CUE_CINEMATICS_DISPLAY_CAPTION: int = 62107
CUE_CINEMATICS_DISPLAY_PERFORMER: int = 62103
CUE_CINEMATICS_HIDE_PERFORMER: int = 62102
CUE_CINEMATICS_RECRUIT_PERFORMER: int = 62104
CUE_CINEMATICS_RECRUIT_PERFORMERS: int = 62100
CUE_CINEMATICS_RENAME_PERFORMER: int = 62106
CastManagerInstance: NoneType = None
CustomTrackClass: dict = {'Sun': <class 'gclient.util.CinematicsBase.CustomSunTrack'>, 'Matrix': <class 'gclient.util.CinematicsBase.CustomMatrixTrack'>, 'Fade': <class 'gclient.util.CinematicsBase.CustomFadeTrack'>, 'Letterbox': <class 'gclient.util.CinematicsBase.CustomLetterboxTrack'>, 'PrintPosition': <class 'gclient.util.CinematicsBase.CustomPrintPositionTrack'>, 'EnvParams': <class 'gclient.util.CinematicsBase.CustomEnvParamsTrack'>}
CustomTrackDefinition: dict = {'Letterbox': (2, [], {'minV': 0.0, 'maxV': 0.5}, {'Renamable': True}), 'Fade': (2, [], {'minV': 0.0, 'maxV': 1.0}, {}), 'Sun': (0, [], {'Time': (2, [], {}, {}), 'Longitude': (2, [], {}, {}), 'SunColorIntensity': (2, [], {}, {})}, {}), 'Matrix': (5, [], {}, {}), 'PrintPosition': (1, [], {}, {'Location': 'EntityBase'}), 'EnvParams': (0, [], {'Time': (2, [], {}, {}), 'Longitude': (2, [], {}, {}), 'SunColor': (3, [], {}, {}), 'SunColorIntensity': (2, [], {}, {}), 'Temperature': (2, [], {}, {}), 'SunAmbient': (3, [], {}, {}), 'SunAmbientIntensity': (2, [], {}, {}), 'DiyParam1_xyz': (3, [], {}, {}), 'DiyParam3_w': (2, [], {}, {})}, {'Location': 'EntityBase'})}
GlobalCustomTrack: dict = {}
Version: float = 1.02
_CustomTrackDefinition: dict = {}

class CastManagerBase(object):
    PerformerCls: type = <class 'gclient.util.CinematicsBase.PerformerBase'>

    def cancelFocus(self): ...
    def dismissPerformer(self, groupName, position): ...
    def dismissPerformers(self, groupName): ...
    def displayPerformer(self, cueInfo): ...
    def focusEntity(self, entity): ...
    def focusSceneEntity(self, *args): ...
    def getDesc(self, groupName, position): ...
    def getEntity(self, groupName, position): ...
    def getPerformer(self, groupName, position): ...
    def hidePerformer(self, cueInfo): ...
    def isCinePerformer(self, groupName, entity): ...
    def onCineGroupReady(self, groupName): ...
    def queryCustomTracks(self): ...
    def queryEntityInfo(self, mode, *args): ...
    def queryExistEntity(self): ...
    def querySceneEntity(self, level): ...
    def recruitPerformer(self, recruitInfo): ...
    def recruitPerformers(self, recruitInfo, director=None): ...
    def renamePerformer(self, groupInfo, oldName, newName): ...

class CastManagerImp(CastManagerBase):
    PerformerCls: type = <class 'gclient.util.CinematicsImp.PerformerImp'>

    def cancelFocus(self): ...
    def dismissPerformer(self, groupName, position): ...
    def dismissPerformers(self, groupName): ...
    def displayPerformer(self, cueInfo): ...
    def focusEntity(self, entity): ...
    def focusSceneEntity(self, *args): ...
    def getDesc(self, groupName, position): ...
    def getEntity(self, groupName, position): ...
    def getPerformer(self, groupName, position): ...
    def hidePerformer(self, cueInfo): ...
    def isCinePerformer(self, groupName, entity): ...
    def onCineGroupReady(self, groupName): ...
    def queryCustomTracks(self): ...
    def queryEntityInfo(self, mode, *args): ...
    def queryExistEntity(self): ...
    def querySceneEntity(self, level): ...
    def recruitPerformer(self, recruitInfo): ...
    def recruitPerformers(self, recruitInfo, director=None): ...
    def renamePerformer(self, groupInfo, oldName, newName): ...

class CustomEnvParamsTrack(CustomTrack):
    IsGlobal: bool = True

    def Active(self): ...
    def Deactive(self): ...

class CustomFadeTrack(CustomTrack):
    IsGlobal: bool = True

    def Active(self): ...
    def Deactive(self): ...

class CustomLetterboxTrack(CustomTrack):
    IsGlobal: bool = True

    def Active(self): ...
    def Deactive(self): ...

class CustomMatrixTrack(CustomTrack):
    IsGlobal: bool = True

    def Active(self): ...
    def Deactive(self): ...

class CustomPrintPositionTrack(CustomTrack):
    IsGlobal: bool = False

    def Active(self): ...
    def Deactive(self): ...

class CustomSunTrack(CustomTrack):
    IsGlobal: bool = True

    def Active(self): ...
    def Deactive(self): ...

class CustomTrack(object):
    IsGlobal: bool = True

    def Active(self): ...
    def Deactive(self): ...

class CustomTrackLocation(object):
    Both: int = 2
    Episode: int = 0
    Performer: int = 1

class CustomTrackType(object):
    Color3: int = 4
    Float: int = 2
    Matrix: int = 5
    Timer: int = 1
    Union: int = 0
    Vector3: int = 3

class GroupInfo(object):
    def active(self): ...
    def addPerformer(self, position, performer): ...
    def cinematicsTickedCallback(self, cineCustomOutput): ...
    def deactive(self): ...

class HideFlag(object):
    HideAll: int = 3
    HideByGroup: int = 2
    HideByPosition: int = 1
    HideNone: int = 0

class PerformerBase(object):
    GRAPH_DIR: str = 'Graph/'

    def ConvertKeyToData(key): ...
    def CreateEntityByData(data): ...
    def CreateEntityByKey(key): ...
    def GetModelCreateInfo(key, identifier): ...
    def bindEvent(self): ...
    def cinematicsTickedCallback(self, cineCustomOutput): ...
    @property
    def createInfo(self): ...    @property
    def createMode(self): ...    def dismissEntity(self): ...
    def displayEntity(self, groupName, hideFlag): ...
    def finiActor(self): ...
    def getActor(self): ...
    def getDesc(self): ...
    def getEntity(self): ...
    def hideEntity(self, groupName, hideFlag): ...
    @property
    def hideInfo(self): ...    def initActor(self): ...
    def recruitEntity(self): ...
    def signalNotifyCallback(self, trigger, stype, signalStr): ...
    def unbindEvent(self): ...
    @property
    def userData(self): ...
class PerformerImp(PerformerBase):
    GRAPH_DIR: str = 'Graph/'

    def ConvertKeyToData(key): ...
    def CreateEntityByData(data): ...
    def CreateEntityByKey(key): ...
    def CreatePerformer(key, identifier): ...
    def GetModelCreateInfo(key, identifier): ...
    def bindEvent(self): ...
    def cinematicsTickedCallback(self, cineCustomOutput): ...
    @property
    def createInfo(self): ...    @property
    def createMode(self): ...    def dismissEntity(self): ...
    def displayEntity(self, groupName, hideFlag): ...
    def finiActor(self): ...
    def getActor(self): ...
    def getDesc(self): ...
    def getEntity(self): ...
    def hideEntity(self, groupName, hideFlag): ...
    @property
    def hideInfo(self): ...    def initActor(self): ...
    @property
    def position(self): ...    def recruitEntity(self): ...
    def signalNotifyCallback(self, trigger, stype, signalStr): ...
    def unbindEvent(self): ...
    @property
    def userData(self): ...

def CreateCamera(withModel=False): ...
def CreateDummy(): ...
def CreateLight(lightCompName, withModel=False): ...
def DataToStr(data, ignoreDicts=False): ...
def GetCastManager(): ...
def GetLightModel(lightCompName): ...
def GetTransformDict(entity): ...
def JsonLoadsStr(text): ...

