# module: gclient.util.gun_upgrade_util

import cdata_util
import item_feature_data
import lobby_item_data
import lobby_item_upgrade_data
import six2

FEATURE_LIST: list = ['inspect_anim', 'show_3p_weapon', 'weapon_special_skill', 'first_raise_anim', 'trail_effect', 'raise_anim', 'kill_hud_id', 'kill_hud_csb_path', 'tip_fire', 'bullet_trace', 'hit_effect', 'kill_effect', 'reload_anim', 'reload_transform', 'kill_num', 'new_appear', 'unlock_part', 'iron_sight', 'high_iron_sight', 'new_sound_effect', 'fire_light', 'recevier_show_ammo', 'linkage_raise_anim']
NOT_SHOW_FEATURE_LIST: list = ['weapon_special_skill']

class GunUpgradeDataMgr(Singleton):
    def CanShowFeature(self, item_id): ...
    def CanUpgrade(self, item_id): ...
    def Destroy(): ...
    def GetBaseItemLevel(self, base_item_id): ...
    def GetFeatureByItemID(self, item_id): ...
    def GetImportantFeatures(self, item_id): ...
    def GetItemFeature(self, base_item_id, level): ...
    def GetItemFeatureList(self, base_item_id): ...
    def GetItemNewFeatureList(self, base_item_id, exclude_not_show_feature=False): ...
    def GetUpgradeFeature(self, new_item_id, old_item_id): ...
    def GetUpgradeFeatureList(self, new_item_id, old_item_id): ...
    def HasFeatureByItemId(self, item_id, feature): ...
    def IsUnlockAllFeatureDirectly(self, item_id): ...
    def ItemId2BaseLevelItem(self, item_id): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class GunUpgradeFeature(enum):
    UPGRADE_FEATURE_BASE: str = 'base'
    UPGRADE_FEATURE_BULLET_TRACE: str = 'bullet_trace'
    UPGRADE_FEATURE_DYNAMIC_KULL_UI: str = 'kill_hud_csb_path'
    UPGRADE_FEATURE_FIRE_LIGHT: str = 'fire_light'
    UPGRADE_FEATURE_FIRE_TIPS: str = 'tip_fire'
    UPGRADE_FEATURE_FIRST_RAISE_ANIM: str = 'first_raise_anim'
    UPGRADE_FEATURE_HIGH_IRON_SIGHT: str = 'high_iron_sight'
    UPGRADE_FEATURE_HIT_EFFECT: str = 'hit_effect'
    UPGRADE_FEATURE_INSPECT_ANIM: str = 'inspect_anim'
    UPGRADE_FEATURE_IRON_SIGHT: str = 'iron_sight'
    UPGRADE_FEATURE_KILL_EFFECT: str = 'kill_effect'
    UPGRADE_FEATURE_KILL_NUMBER: str = 'kill_num'
    UPGRADE_FEATURE_KILL_UI: str = 'kill_hud_id'
    UPGRADE_FEATURE_LINKAGE_RAISE_ANIM: str = 'linkage_raise_anim'
    UPGRADE_FEATURE_NEW_APPEAR: str = 'new_appear'
    UPGRADE_FEATURE_NEW_SOUND: str = 'new_sound_effect'
    UPGRADE_FEATURE_RAISE_ANIM: str = 'raise_anim'
    UPGRADE_FEATURE_RECEVIER_SHOW_AMMO: str = 'recevier_show_ammo'
    UPGRADE_FEATURE_RELOAD_ANIM: str = 'reload_anim'
    UPGRADE_FEATURE_RELOAD_TRANSFORM: str = 'reload_transform'
    UPGRADE_FEATURE_SHOW_3P_WEAPON: str = 'show_3p_weapon'
    UPGRADE_FEATURE_SPECIAL_SKILL: str = 'weapon_special_skill'
    UPGRADE_FEATURE_TRAIL_EFFECT: str = 'trail_effect'
    UPGRADE_FEATURE_UNLOCK_ITEM: str = 'bind_items'
    UPGRADE_FEATURE_UNLOCK_ITEM_1: str = 'bind_items_1'
    UPGRADE_FEATURE_UNLOCK_ITEM_2: str = 'bind_items_2'
    UPGRADE_FEATURE_UNLOCK_ITEM_3: str = 'bind_items_3'
    UPGRADE_FEATURE_UNLOCK_PARTS: str = 'unlock_part'
    name_to_values: dict = {'UPGRADE_FEATURE_BASE': 'base', 'UPGRADE_FEATURE_KILL_UI': 'kill_hud_id', 'UPGRADE_FEATURE_DYNAMIC_KULL_UI': 'kill_hud_csb_path', 'UPGRADE_FEATURE_FIRE_TIPS': 'tip_fire', 'UPGRADE_FEATURE_BULLET_TRACE': 'bullet_trace', 'UPGRADE_FEATURE_HIT_EFFECT': 'hit_effect', 'UPGRADE_FEATURE_TRAIL_EFFECT': 'trail_effect', 'UPGRADE_FEATURE_INSPECT_ANIM': 'inspect_anim', 'UPGRADE_FEATURE_RAISE_ANIM': 'raise_anim', 'UPGRADE_FEATURE_RELOAD_ANIM': 'reload_anim', 'UPGRADE_FEATURE_KILL_EFFECT': 'kill_effect', 'UPGRADE_FEATURE_UNLOCK_PARTS': 'unlock_part', 'UPGRADE_FEATURE_NEW_APPEAR': 'new_appear', 'UPGRADE_FEATURE_KILL_NUMBER': 'kill_num', 'UPGRADE_FEATURE_UNLOCK_ITEM': 'bind_items', 'UPGRADE_FEATURE_UNLOCK_ITEM_1': 'bind_items_1', 'UPGRADE_FEATURE_UNLOCK_ITEM_2': 'bind_items_2', 'UPGRADE_FEATURE_UNLOCK_ITEM_3': 'bind_items_3', 'UPGRADE_FEATURE_IRON_SIGHT': 'iron_sight', 'UPGRADE_FEATURE_HIGH_IRON_SIGHT': 'high_iron_sight', 'UPGRADE_FEATURE_NEW_SOUND': 'new_sound_effect', 'UPGRADE_FEATURE_FIRE_LIGHT': 'fire_light', 'UPGRADE_FEATURE_RECEVIER_SHOW_AMMO': 'recevier_show_ammo', 'UPGRADE_FEATURE_RELOAD_TRANSFORM': 'reload_transform', 'UPGRADE_FEATURE_LINKAGE_RAISE_ANIM': 'linkage_raise_anim', 'UPGRADE_FEATURE_FIRST_RAISE_ANIM': 'first_raise_anim', 'UPGRADE_FEATURE_SPECIAL_SKILL': 'weapon_special_skill', 'UPGRADE_FEATURE_SHOW_3P_WEAPON': 'show_3p_weapon'}
    value_to_names: dict = {'base': 'UPGRADE_FEATURE_BASE', 'kill_hud_id': 'UPGRADE_FEATURE_KILL_UI', 'kill_hud_csb_path': 'UPGRADE_FEATURE_DYNAMIC_KULL_UI', 'tip_fire': 'UPGRADE_FEATURE_FIRE_TIPS', 'bullet_trace': 'UPGRADE_FEATURE_BULLET_TRACE', 'hit_effect': 'UPGRADE_FEATURE_HIT_EFFECT', 'trail_effect': 'UPGRADE_FEATURE_TRAIL_EFFECT', 'inspect_anim': 'UPGRADE_FEATURE_INSPECT_ANIM', 'raise_anim': 'UPGRADE_FEATURE_RAISE_ANIM', 'reload_anim': 'UPGRADE_FEATURE_RELOAD_ANIM', 'kill_effect': 'UPGRADE_FEATURE_KILL_EFFECT', 'unlock_part': 'UPGRADE_FEATURE_UNLOCK_PARTS', 'new_appear': 'UPGRADE_FEATURE_NEW_APPEAR', 'kill_num': 'UPGRADE_FEATURE_KILL_NUMBER', 'bind_items': 'UPGRADE_FEATURE_UNLOCK_ITEM', 'bind_items_1': 'UPGRADE_FEATURE_UNLOCK_ITEM_1', 'bind_items_2': 'UPGRADE_FEATURE_UNLOCK_ITEM_2', 'bind_items_3': 'UPGRADE_FEATURE_UNLOCK_ITEM_3', 'iron_sight': 'UPGRADE_FEATURE_IRON_SIGHT', 'high_iron_sight': 'UPGRADE_FEATURE_HIGH_IRON_SIGHT', 'new_sound_effect': 'UPGRADE_FEATURE_NEW_SOUND', 'fire_light': 'UPGRADE_FEATURE_FIRE_LIGHT', 'recevier_show_ammo': 'UPGRADE_FEATURE_RECEVIER_SHOW_AMMO', 'reload_transform': 'UPGRADE_FEATURE_RELOAD_TRANSFORM', 'linkage_raise_anim': 'UPGRADE_FEATURE_LINKAGE_RAISE_ANIM', 'first_raise_anim': 'UPGRADE_FEATURE_FIRST_RAISE_ANIM', 'weapon_special_skill': 'UPGRADE_FEATURE_SPECIAL_SKILL', 'show_3p_weapon': 'UPGRADE_FEATURE_SHOW_3P_WEAPON'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class Singleton(object):
    def Destroy(): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...


