# module: gclient.util.parameter_change_util

class ParameterChangeUtil(object):
    def ChangeToValue(self, target_value, interval=0.1, init_value=None): ...
    def Clear(self): ...
    def EndStoryTick(self): ...
    def SetCallbackFunc(self, func): ...
    def StartStoryTick(self): ...
    def StoryTickFunc(self, frame): ...
    @property
    def value(self): ...
class StoryTick(object):
    _instance: StoryTick = <gclient.framework.util.story_tick.StoryTick object at 0x7005e37fd0>

    def Add(self, func, frames=0): ...
    def Remove(self, func): ...
    def doAdd(self, func, frames): ...
    def doRemove(self, func): ...
    def onTick(self, _, dtime): ...


