# module: gclient.util.pharos_client

import Timer
import json
import random
import switches
import sys

class GeneralLog(GeneralLog):
    def SALog(self, operation, **kwargs): ...
    def log(self, operation, **kwargs): ...
    def reloadAppVersion(self): ...

class PharosClient(Singleton):
    _instance: PharosClient = <PharosClient(0x0x6f54170750)>

    def ConnectFail(self): ...
    def ConnectOriginIp(self, reason): ...
    def Destroy(): ...
    def DoGateConnect(self, ip, port, ipv6='', port_v6=0, reason=''): ...
    def OnDestroy(self): ...
    def Start(self, ip, port, login_entry=None, region='cn'): ...
    def StartIpV6(self, ip, port, login_entry=None, region='cn'): ...
    def _OnPharosProbe(self, probe_data): ...
    def _OnPharosProbeIpv6(self, probe_data): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...
    def is_ipv4(self, ip): ...

class Singleton(object):
    def Destroy(): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class UnisdkPharos(Singleton):
    TIME_OUT: int = 2

    def ClearTimer(self): ...
    def Destroy(): ...
    def OnDestroy(self): ...
    def OnPharosProbe(self, content): ...
    def OnPharosProbeIpv6(self, content): ...
    def Probe(self, server_host, server_port, region, callback): ...
    def QueryIpv6Address(self, server_host, server_port, region, callback): ...
    def _ProbeCallback(self, probe_data): ...
    def _ProbeIp6Callback(self, probe_data): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...


def UnicodeToUTF8(d): ...

