# module: gclient.util.rank_util

import cdata_util
import qualifying_reward_data
import qualifying_season_data
import rank_level_data
import six2

LocalConfig: _LocalConfig = <gclient.config._LocalConfig object at 0x7040bf6d50>
RANK_LEVEL_SOUND_MAP: dict = {1: 554, 2: 555, 3: 556, 4: 557, 5: 558, 6: 559, 7: 560}

class GetState(enum):
    CanGet: int = 2
    Got: int = 3
    Normal: int = 1
    name_to_values: dict = {'Normal': 1, 'CanGet': 2, 'Got': 3}
    value_to_names: dict = {1: 'Normal', 2: 'CanGet', 3: 'Got'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class enum(object):
    name_to_values: dict = {}
    value_to_names: dict = {}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...


def CalGetState(reward_id, avatar_reward_id, qualifying_level_reward): ...
def CalStarAndTotalStarNumber(match_type, qualifying_score): ...
def CalcQualifyingLevel(qualifying_score, match_type=1004, cache=False): ...
def GetDefineRankLevelProtoByScoreDict(qualifying_score_dict, match_type=0): ...
def GetQualifyingRewardProto(match_type): ...
def GetQualifyingRewardProtoByDefine(): ...
def GetQualifyingSeasonProtoByDefine(): ...
def GetRankLevelProto(match_type): ...
def GetRankLevelProtoByDefine(): ...
def QualifyingLevelByScoreDictAndMatchType(qualifying_score_dict, match_type): ...

