# module: gclient.util.weather_util

import MCharacter
import MRender
import MType
import cconst
import consts
import effect_util
import events
import replay_util
import time

NEED_RAIN_STATE_CHANGE: bool = True
RAIN_STATE_NAME_RAINING: str = 'rainning'
RAIN_STATE_NAME_RAIN_OVER: str = 'rain_over'

class FiniteStateMachine(object):
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...

class StateCloudy(object):
    NAME: str = 'Cloudy'

    def OnCloudyEnter(self): ...
    def OnCloudyExit(self): ...

class StateRain(object):
    NAME: str = 'Rain'

    def OnRainEnter(self): ...
    def OnRainExit(self): ...
    def RefreshRainEntityVisible(self, entities, entity_visible): ...
    def TickRainEntity(self, entities): ...
    def _CancelTickTimer(self): ...

class StateSunny(object):
    NAME: str = 'Sunny'

    def OnSunnyEnter(self): ...
    def OnSunnyExit(self): ...
    def _StartSunnySound(self): ...

class WeatherFsm(FiniteStateMachine):
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...

class WeatherManager(object):
    NAME: str = 'Cloudy'

    def CacheSpaceForSound(self): ...
    def CancelEnvSound(self): ...
    def Clear(self): ...
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...
    def OnChangePlayerInHouse(self): ...
    def OnCloudyEnter(self): ...
    def OnCloudyExit(self): ...
    def OnPlayerModelCreated(self): ...
    def OnRainEnter(self): ...
    def OnRainExit(self): ...
    def OnSunnyEnter(self): ...
    def OnSunnyExit(self): ...
    def RefreshRainEntityVisible(self, entities, entity_visible): ...
    def RestoreStateOnLoaded(self): ...
    def ReuseSpaceForSound(self): ...
    def SetWeather(self, weather_type): ...
    def TickRainEntity(self, entities): ...
    def _CancelTickTimer(self): ...
    def _StartSunnySound(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...


def Components(*components, **kwargs): ...
def StateWrapper(cls): ...

