# module: Timer

import asiocore
import wheeltimer

_logger: Logger = <Logger asynctimer (DEBUG)>
set_enable: builtin_function_or_method = <built-in method set_enabled of wheeltimer.wheeltimer object at 0x702c553d90>
timer_mgr: wheeltimer = wheeltimer.wheeltimer

class CallbackProxy(TimerProxy):
    timerid: member_descriptor = <member 'timerid' of 'TimerProxy' objects>

    def cancel(self): ...
    @property
    def repeat(self): ...
class LogManager(object):
    asyncwrite: bool = False
    created_modules: set = {'CombatAvatarSquadFight', 'GameLogicRookieGuide', 'ReplayGameLogicSniperMode', 'RobotCombatAvatarNowhere', 'BaitBombField', 'ClientAreaEntity', 'ReplayCombatAvatarSniperMode', 'CombatTeamEntity_SquadFight', 'AttachScoutArrowEntity', 'bhttp_client.BHttpClient', 'AdsShield', 'BaseSupply', 'CombatAvatarMobaZombie', 'IceWallField', 'ClientSpace', 'CombatTeamEntity_BigHead', 'PlayerCombatAvatarPlacement', 'ControlTargetBase', 'RepelBomb', 'Formula', 'GameLogicNowhere', 'ReplayRoomGameLogicSquadFight', 'VehicleCannon', 'HumanoidMonsterMonsterAI', 'ReconDrone', 'CombatAvatar', 'RobotCombatAvatarMoba', 'PlayerCombatAvatarSniperMode', 'CombatAvatarMobaFirst', 'PlayerCombatAvatarHotSpotBase', 'EnergyStronghold', 'Bomb', 'Preload', 'GameLogicBigHead', 'GrenadeLauncherBomb', 'LeadWayEntity', 'ReplayCombatAvatarShootingRange', 'GameLogicGrandTheft', 'ReplayGameLogicMobaZombie', 'PlayerCombatAvatarSquadFightBase', 'Shop', 'MovingPlatformTelpher', 'ClientEntity', 'HelenRobotCombatAvatarMoba', 'SuicideDrone', 'ThermiteBomb', 'PhyBall', 'ReplayCombatAvatarMoba', 'FireWallField', 'RobotCombatAvatarRookieGuideNew', 'PlayerCombatAvatarRookieGuideNew', 'ReplayCombatAvatarSquadFight', 'ReplayDummy', 'TrackBomb', 'AmmoBox', 'CombatAvatarPlacement', 'Supply', 'asynctimer', 'PlayerAvatar', 'ServerUtil', 'PlayerCombatAvatar', 'RobotCombatAvatarShootingRange', 'StropEntity', 'CombatAvatarBigHead', 'CureUav', 'HelenRobotCombatAvatarNoWhere', 'SearchContractBox', 'RobotCombatAvatarMobaZombieAi', 'InteractionEntity', 'NewCrystalMonster', 'CombatTeamEntity_Moba', 'SaveMachine', 'ReplayCombatAvatarMobaZombie', 'NavigateCannon', 'ATM', 'RobotCombatAvatarBigHead', 'SatellitePlaceItem', 'Arrow', 'RestrictWall', 'WaterSnare', 'CDrone', 'Vehicle', 'MonsterCommon', 'OccupyContractTarget', 'ScoutField', 'Helicopter', 'HolographicRobotMoba', 'ReplayGameLogicPlacement', 'TrackTrapBomb', 'HolographicRobot', 'CombatAvatarShootingRange', 'ReplayGameLogicGrandTheft', 'Pubsub', 'Space', 'ReplayGameLogicNowhere', 'CombatAvatarMobaFirstNew', 'GameLogicRookieGuideNew', 'CombatAvatarGrandTheft', 'PlayerCombatAvatarMobaZombie', 'Account', 'PlayerCombatAvatarNowhere', 'ValDrone', 'CombatAvatarHotSpot', 'DeathBoxDummyEntity', 'CombatAvatarGunFight', 'CrystalMonster', 'Airdrop', 'ReplayRoomGameLogicMoba', 'RobotCombatAvatarMobaFirstNew', 'GateClient', 'MoveFireWall', 'Oilbox', 'ScoutTotemField', 'NewMonsterCommon', 'RPGMissile', 'SafeBox', 'RobotCombatAvatarATMGuard', 'RobotCombatAvatarMobaZombie', 'PlayerCombatAvatarClientOffline', 'ReplayCombatAvatar', 'PlayerEntity', 'ChaosUAV', 'SyncTransEntity', 'ReplayCombatAvatarGunFight', 'BigHeadCalculationDoll', 'DestructibleCollections', 'ScoutArrow', 'GameLogicSquadFight', 'MovingShield', 'CombatAvatarHotSpotBase', 'FreeviewDummyEntity', 'RobotCombatAvatarSniperMode', 'GameLogicPlacement', 'RobotCombatAvatarGrandTheft', 'CombatAvatarSquadFightBase', 'ActivityItem', 'ReplayRoomGameLogicBase', 'Missile', 'MonsterAI', 'CalculationDoll', 'MonitorMissile', 'AsioServerProxy', 'PlayerCombatAvatarHotSpot', 'Stronghold', 'GameLogicShootingRange', 'PlayerCombatAvatarGrandTheft', 'CombatAvatarGunFightBase', 'KcpClient', 'RobotCombatAvatarSquadFight', 'ReplayRoomGameLogicBigHead', 'ClientEnv', 'CombatTeamEntity_GunFight', 'ReplayCombatAvatarMobaFirstNew', 'ThroughBomb', 'ReplayCombatAvatarHotSpot', 'GameLogicMobaZombie', 'GameLogicGunFight', 'Building', 'mobilerpc.SimpleAsyncBHTTPClient', 'DummyCombatAvatar', 'ReplayGameLogicGunFight', 'ReplayCombatAvatarNowhere', 'ExplodingArrowEntity', 'RobotCombatAvatarHotSpot', 'NinjaBeacon', 'ReplayCombatAvatarGrandTheft', 'BarrieCannon', 'ReplayRoomGameLogicMobaZombie', 'CombatTeamEntity_ShootingRange', 'ReplayGameLogicMobaFirst', 'TrackBomb2025', 'PlayerCombatAvatarGunFightBase', 'CombatItemEntity', 'GameLogicMoba', 'CombatAvatarMoba', 'PlayerCombatAvatarShootingRange', 'RobotCombatAvatarRookieGuide', 'GameLogicClientOffline', 'PlayerCombatAvatarRookieGuide', 'CombatAvatarRookieGuideNew', 'Crow', 'Entity', 'MagicField', 'PlayerCombatAvatarSquadFight', 'AircraftPlane', 'Model', 'RpcIndexer', 'SpaceSnare', 'PlayerCombatAvatarMoba', 'PlaceEntity', 'SaveDrone', 'ReplayGameLogicHotSpot', 'PlayerCombatAvatarBigHeadBase', 'AvatarEntity', 'PortableShop', 'ReplayGameLogicShootingRange', 'CommonMoveItem', 'ShockField', 'ClueBox', 'VehicleAirplane', 'CombatTeamEntity_GrandTheft', 'AsioGateClient', 'FollowShieldMagicField', 'BigHeadMostKillDummyEntity', 'ReplayGameLogicBase', 'SamuraiBlockField', 'ReplayGameLogicMoba', 'CombatTeamEntity_Nowhere', 'ModelCache', 'CombatAvatarBigHeadBase', 'CombatTeamEntity_SniperMode', 'ReplayCombatAvatarMobaFirst', 'PlayerCombatAvatarMobaFirst', 'CombatTeamEntity', 'GameLogicMobaFirstNew', 'ATMGuardMonster', 'RobotCombatAvatarMobaFirst', 'SaveDroneDummyEntity', 'CombatTeamEntity_HotSpot', 'Telnet', 'GameLogicSniperMode', 'OccupyContractTargetNew', 'CombatTeamEntity_MobaZombie', 'ItemSpaceSnare', 'GameLogicBase', 'EmoteTree', 'ReplayCombatAvatarBigHead', 'CombatAvatarRookieGuide', 'ReplayRoomGameLogicSniperMode', 'CombatAvatarSniperMode', 'AttackDrone', 'StickyObjectEntity', 'ReplayGameLogicBigHead', 'SwordSpirit', 'ReplayGameLogicSquadFight', 'PlayerCombatAvatarMobaFirstNew', 'TotemField', 'PlayerCombatAvatarGunFight', 'CureUavFix', 'Doll', 'Crack', 'BlastBomb', 'ClusterBomb', 'HolographicRobotNowhere', 'GameLogicHotSpot', 'RobotCombatAvatarGunFight', 'DollLike', 'CombatAvatarNowhere', 'ReplayRoomGameLogicGunFight', 'HolographicHitTargetDummyEntity', 'server.EntityManager', 'StropUAV', 'CombatAvatarClientOffline', 'PlayerCombatAvatarBigHead', 'FollowerInteractionEntity', 'CommonItem', 'server.EntityFactory', 'ReplayGameLogicMobaFirstNew', 'GameLogicMobaFirst', 'Avatar'}
    custom_handler: NoneType = None
    log_handle: str = 'stream'
    log_level: int = 10
    log_tag: str = ''
    run_tag: str = ''
    sa_log_tag: str = ''
    sys_logger: NoneType = None

    def _create_handler(logger): ...
    def get_logger(moduleName): ...
    def get_sa_logger(): ...
    def run_message(message): ...
    def set_asyncwrite(asyncwrite): ...
    def set_custom_handler(handler): ...
    def set_log_handle(handle): ...
    def set_log_level(lv): ...
    def set_log_tag(log_tag): ...
    def set_run_tag(run_tag): ...
    def set_sa_log_tag(tag): ...

class TimerManager(object):
    WheelCallbackProxy: type = <class 'Timer.WheelTimerManager.WheelCallbackProxy'>
    WheelTimerProxy: type = <class 'Timer.WheelTimerManager.WheelTimerProxy'>

    def addRepeatTimer(self, delay, func, *args, **kwargs): ...
    def addRepeatTimerWithDt(self, delay, func, *args, **kwargs): ...
    def addTimer(self, delay, func, *args, **kwargs): ...
    def add_callback(self, delay, repeat, func, gtick=0, with_dt=False): ...
    def cancel_all(self): ...
    def cancel_all_run_once_timers(self): ...
    def cancel_timer(self, timerid): ...
    def ensure_cancel_timer(self, timerid): ...
    def set_enabled(self, enabled): ...
    def set_slot_step(self, slot_num, time_step): ...
    def update(self): ...

class TimerProxy(object):
    timerid: member_descriptor = <member 'timerid' of 'TimerProxy' objects>

    def cancel(self): ...
    @property
    def repeat(self): ...
class WheelTimerManager(object):
    WheelCallbackProxy: type = <class 'Timer.WheelTimerManager.WheelCallbackProxy'>
    WheelTimerProxy: type = <class 'Timer.WheelTimerManager.WheelTimerProxy'>

    def addRepeatTimer(self, delay, func, *args, **kwargs): ...
    def addRepeatTimerWithDt(self, delay, func, *args, **kwargs): ...
    def addTimer(self, delay, func, *args, **kwargs): ...
    def add_callback(self, delay, repeat, func, gtick=0, with_dt=False): ...
    def cancel_all(self): ...
    def cancel_all_run_once_timers(self): ...
    def cancel_timer(self, timerid): ...
    def ensure_cancel_timer(self, timerid): ...
    def set_enabled(self, enabled): ...
    def set_slot_step(self, slot_num, time_step): ...
    def update(self): ...


def addRepeatTimer(delay, func, *args, **kwargs): ...
def addRepeatTimerWithDt(delay, func, *args, **kwargs): ...
def addTimer(delay, func, *args, **kwargs): ...
def add_callback(delay, repeat, func, gtick=0, with_dt=False): ...
def cancel_all(): ...
def cancel_timer(timerid): ...
def ensure_cancel_timer(timerid): ...
def is_repeat_timer(timerid): ...

