# module: gclient.gamesystem.uihall.uihero.hero_window_model_comp

import cconst
import consts
import events
import formula
import hall_item_util
import hero_data_util
import lobby_item_data
import mall_model_pos_data
import mall_util
import math

class CommonDescribeNodeCur(CommonDescribeNode):
    FIRST_PANEL_NAME: str = 'panel_name'
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTextShadow(self): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetDescribeTextNode(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def RefreshItemByItemId(self, item_id): ...
    def RefreshItemByProto(self, item_proto): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class HeroSkinWindowModelComp(HeroWindowModelComp):
    HIDDEN_REASON: int = 13

    def ClearALLCueCameraEffect(self): ...
    def HideAllModel(self): ...
    def InitPanelBtn(self, panel_content): ...
    def InitPanelDescribe(self, panel_content): ...
    def InitPanelTouchModel(self, panel_content): ...
    def InitPanelVideo(self, panel_content): ...
    def OnBtnExecuteVideoClick(self, data, proto): ...
    def OnBtnHandSkillVideoClick(self, data, proto): ...
    def OnBtnHandVideoClick(self, data, proto): ...
    def OnBtnSkillVideoClick(self, data, proto): ...
    def OnClosePanelVideo(self): ...
    def OnRefreshDownloadState(self, dlc_id, status): ...
    def RePlayVideo(self): ...
    def RefreshItemDesc(self, item_proto): ...
    def RefreshModel(self, item_proto, extra=None): ...
    def SetModelSettingProto(self, model_pos_key): ...
    def ShowAppearanceAni(self, item_proto): ...
    def ShowExecute(self, item_proto): ...
    def ShowExecuteVideo(self, item_id): ...
    def _HeroWindowModelComp__post_visible_component(self, value, hidden_reason): ...
    def _HeroWindowModelComp__pre_visible_component(self, value, hidden_reason): ...
    def _OnClosePanelVideo(self): ...
    def _RefreshModel(self, item_proto): ...
    @property
    def hero_skin_can_move(self): ...
class HeroWindowHeroExecutedModelCtrl(HeroWindowHeroModelCtrl):
    MODEL_POS: tuple = (0, 0, 0)
    MODEL_YAW: float = 2.9181159619

    def AddHiddenReason(self, reason): ...
    def AddSkeletonIKSlot(self): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def AddWeaponByEquipId(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, principle_role=False, extra=None): ...
    def AddWeaponByEquipIdForHeroSkin(self, show_item_id): ...
    def AddWeaponByItemProto(self, item_proto): ...
    def AddWeaponForDoll(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, extra=None): ...
    def AddWeaponForMainNpc(self): ...
    def AttachWatchToHandModel(self): ...
    def CacheModel(self): ...
    def ChangeArmClothes(self, arm_clothes): ...
    def ChangeGender(self, gender): ...
    def ChangeWatchMode(self, watch_mode): ...
    def ChangeWeaponSkinId(self, skin_id): ...
    def CheckClearHeroSkinAnimDlc(self): ...
    def CheckEmoteModelAttach(self): ...
    def CheckHeroAttachModel(self): ...
    def CheckHeroSkinEffect(self): ...
    def CheckNeedDownload(self): ...
    def CheckPlayHeroSkinAnim(self, is_reload=True): ...
    def CheckRefreshNpcPose(self): ...
    def CheckWatchModel(self): ...
    def ClearHeroSkinPose(self): ...
    def ClearPose(self): ...
    def ClearPoseOnEmoteEnd(self): ...
    def ClearPoseOnExecuteEnd(self): ...
    def CreateWeaponCaseByItemProto(self, item_proto): ...
    def DelHeroAttachModel(self): ...
    def DelWeapon(self): ...
    def DelaySetDlcNodePosition(self): ...
    def Destroy(): ...
    def DetachWeapon(self): ...
    def EndRotateRecover(self): ...
    def GetBasicGraph(self): ...
    def GetDlcNodePosition(self): ...
    def GetDlcUINode(self): ...
    def GetHeroId(self): ...
    def GetLobbyPoseId(self): ...
    def GetModelCls(self): ...
    def GetModelComponentList(self): ...
    def GetModelOwner(self): ...
    def GetModelSkeleton(self): ...
    def GetModelUnitID(self): ...
    def InitModelDlcStatusNode(self): ...
    def IsClothesNeedDownload(self): ...
    @property
    def IsVisible(self): ...    def LoadHandModel(self, callback=None): ...
    def OnAttachWeaponCaseDone(self, _): ...
    def OnDestroy(self): ...
    def OnHallShowModelLoaded(self, is_reload=False): ...
    def OnHandModelLoaded(self, callback=None): ...
    def OnMouseEnd(self): ...
    def OnMouseMove(self, x, y, rotate_x=True, rotate_y=True): ...
    def OnMouseRDown(self, x, y): ...
    def OnMouseRUp(self, x, y): ...
    def OnPlayEmoteEnd(self, callback): ...
    def OnRefreshDownloadState(self, dlc_id, status): ...
    def OnWatchModelDone(self): ...
    def PlayEmoteAnim(self, interrupt=True): ...
    def PlayExecuteAnim(self): ...
    def RefreshCurAttachWeaponCaseForDlc(self): ...
    def RefreshWeaponDlcids(self): ...
    def RefreshWeaponModelAttach(self, is_mvp=False): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def ResetAttensionDlcIds(self): ...
    def ResetDlcId(self): ...
    def ResetModelPos(self): ...
    def SetArmClothes(self, arm_clothes, refresh_dlc=True): ...
    def SetIsShowHeroSkin(self, value): ...
    def SetLobbyPoseId(self, pose_id): ...
    def SetMipBias(self, bias): ...
    def SetModelPos(self, pos, yaw): ...
    def SetWatchItemId(self, watch_item_id): ...
    def SetupCastDynamicShadow(self): ...
    def ShowEmoteAttachModel(self, value): ...
    def ShowEmoteModel(self, item_proto, emote_loop=True, callback=None): ...
    def ShowExecuteModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowExecutedModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowHeroSkinModel(self, item_proto, is_idle=False, is_executed=False, without_anim=False): ...
    def ShowModel(self, use_ready_to_appear=False): ...
    def ShowTailEffect(self, item_proto): ...
    def StopTailEffect(self): ...
    def SwitchToHandModel(self, is_switch): ...
    def _ChangeShaderGraphParamForHallDollGun(self): ...
    def _DoAddWeapon(self, equip_id, skin_id, guise_id, part_slots, extra=None, is_reload=False): ...
    def _GetDefaultSuitItemId(self): ...
    def _GetPoseInfoByWeaponId(self, weapon_id): ...
    def _RefreshDlcInfoForPlayEmote(self, emote_item_id): ...
    def _RefreshDlcInfoForPlayExecute(self, execution_item_id): ...
    def _RefreshInfoOnArmClothesChange(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def entity_area(self): ...    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class HeroWindowHeroModelCtrl(MallHeroModelCtrlBase):
    MODEL_POS: tuple = (0, 0, 0)
    MODEL_YAW: float = 2.9181159619

    def AddHiddenReason(self, reason): ...
    def AddSkeletonIKSlot(self): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def AddWeaponByEquipId(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, principle_role=False, extra=None): ...
    def AddWeaponByEquipIdForHeroSkin(self, show_item_id): ...
    def AddWeaponByItemProto(self, item_proto): ...
    def AddWeaponForDoll(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, extra=None): ...
    def AddWeaponForMainNpc(self): ...
    def AttachWatchToHandModel(self): ...
    def CacheModel(self): ...
    def ChangeArmClothes(self, arm_clothes): ...
    def ChangeGender(self, gender): ...
    def ChangeWatchMode(self, watch_mode): ...
    def ChangeWeaponSkinId(self, skin_id): ...
    def CheckClearHeroSkinAnimDlc(self): ...
    def CheckEmoteModelAttach(self): ...
    def CheckHeroAttachModel(self): ...
    def CheckHeroSkinEffect(self): ...
    def CheckNeedDownload(self): ...
    def CheckPlayHeroSkinAnim(self, is_reload=True): ...
    def CheckRefreshNpcPose(self): ...
    def CheckWatchModel(self): ...
    def ClearHeroSkinPose(self): ...
    def ClearPose(self): ...
    def ClearPoseOnEmoteEnd(self): ...
    def ClearPoseOnExecuteEnd(self): ...
    def CreateWeaponCaseByItemProto(self, item_proto): ...
    def DelHeroAttachModel(self): ...
    def DelWeapon(self): ...
    def DelaySetDlcNodePosition(self): ...
    def Destroy(): ...
    def DetachWeapon(self): ...
    def EndRotateRecover(self): ...
    def GetBasicGraph(self): ...
    def GetDlcNodePosition(self): ...
    def GetDlcUINode(self): ...
    def GetHeroId(self): ...
    def GetLobbyPoseId(self): ...
    def GetModelCls(self): ...
    def GetModelComponentList(self): ...
    def GetModelOwner(self): ...
    def GetModelSkeleton(self): ...
    def GetModelUnitID(self): ...
    def InitModelDlcStatusNode(self): ...
    def IsClothesNeedDownload(self): ...
    @property
    def IsVisible(self): ...    def LoadHandModel(self, callback=None): ...
    def OnAttachWeaponCaseDone(self, _): ...
    def OnDestroy(self): ...
    def OnHallShowModelLoaded(self, is_reload=False): ...
    def OnHandModelLoaded(self, callback=None): ...
    def OnMouseEnd(self): ...
    def OnMouseMove(self, x, y, rotate_x=True, rotate_y=True): ...
    def OnMouseRDown(self, x, y): ...
    def OnMouseRUp(self, x, y): ...
    def OnPlayEmoteEnd(self, callback): ...
    def OnRefreshDownloadState(self, dlc_id, status): ...
    def OnWatchModelDone(self): ...
    def PlayEmoteAnim(self, interrupt=True): ...
    def PlayExecuteAnim(self): ...
    def RefreshCurAttachWeaponCaseForDlc(self): ...
    def RefreshWeaponDlcids(self): ...
    def RefreshWeaponModelAttach(self, is_mvp=False): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def ResetAttensionDlcIds(self): ...
    def ResetDlcId(self): ...
    def ResetModelPos(self): ...
    def SetArmClothes(self, arm_clothes, refresh_dlc=True): ...
    def SetIsShowHeroSkin(self, value): ...
    def SetLobbyPoseId(self, pose_id): ...
    def SetMipBias(self, bias): ...
    def SetModelPos(self, pos, yaw): ...
    def SetWatchItemId(self, watch_item_id): ...
    def SetupCastDynamicShadow(self): ...
    def ShowEmoteAttachModel(self, value): ...
    def ShowEmoteModel(self, item_proto, emote_loop=True, callback=None): ...
    def ShowExecuteModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowExecutedModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowHeroSkinModel(self, item_proto, is_idle=False, is_executed=False, without_anim=False): ...
    def ShowModel(self, use_ready_to_appear=False): ...
    def ShowTailEffect(self, item_proto): ...
    def StopTailEffect(self): ...
    def SwitchToHandModel(self, is_switch): ...
    def _ChangeShaderGraphParamForHallDollGun(self): ...
    def _DoAddWeapon(self, equip_id, skin_id, guise_id, part_slots, extra=None, is_reload=False): ...
    def _GetDefaultSuitItemId(self): ...
    def _GetPoseInfoByWeaponId(self, weapon_id): ...
    def _RefreshDlcInfoForPlayEmote(self, emote_item_id): ...
    def _RefreshDlcInfoForPlayExecute(self, execution_item_id): ...
    def _RefreshInfoOnArmClothesChange(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def entity_area(self): ...    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class HeroWindowModelComp(object):
    HIDDEN_REASON: int = 13

    def ClearALLCueCameraEffect(self): ...
    def HideAllModel(self): ...
    def InitPanelBtn(self, panel_content): ...
    def InitPanelDescribe(self, panel_content): ...
    def InitPanelTouchModel(self, panel_content): ...
    def InitPanelVideo(self, panel_content): ...
    def OnBtnExecuteVideoClick(self, data, proto): ...
    def OnBtnHandSkillVideoClick(self, data, proto): ...
    def OnBtnHandVideoClick(self, data, proto): ...
    def OnBtnSkillVideoClick(self, data, proto): ...
    def OnClosePanelVideo(self): ...
    def OnRefreshDownloadState(self, dlc_id, status): ...
    def RePlayVideo(self): ...
    def RefreshItemDesc(self, item_proto): ...
    def RefreshModel(self, item_proto, extra=None): ...
    def SetModelSettingProto(self, model_pos_key): ...
    def ShowAppearanceAni(self, item_proto): ...
    def ShowExecute(self, item_proto): ...
    def ShowExecuteVideo(self, item_id): ...
    def _HeroWindowModelComp__post_visible_component(self, value, hidden_reason): ...
    def _HeroWindowModelComp__pre_visible_component(self, value, hidden_reason): ...
    def _OnClosePanelVideo(self): ...
    def _RefreshModel(self, item_proto): ...
    @property
    def hero_skin_can_move(self): ...
class HeroWindowModelFloorComp(MallModelFloorComp):
    def AddFloorLevel(self): ...
    def BackgroundFadeInOutTick(self, prim, param, start_time, duration, start_value, end_value, dt): ...
    def EnterSkinV6Intro(self): ...
    def FadeInBackground(self, gacha_setting_proto): ...
    def FadeoutBackground(self, gacha_setting_proto): ...
    def GetFloorProto(self): ...
    def LeftSkinV6Intro(self, btn=None): ...
    def RemoveFloorLevel(self): ...
    def _MallModelFloorComp__pre_visible_component(self, value, hidden_reason): ...

class MallHeroModelCtrlBase(WarehouseHeroModelCtrl):
    MODEL_POS: tuple = (0, 0, 0)
    MODEL_YAW: float = 2.269

    def AddHiddenReason(self, reason): ...
    def AddSkeletonIKSlot(self): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def AddWeaponByEquipId(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, principle_role=False, extra=None): ...
    def AddWeaponByEquipIdForHeroSkin(self, show_item_id): ...
    def AddWeaponByItemProto(self, item_proto): ...
    def AddWeaponForDoll(self, equip_id=None, skin_id=None, guise_id=None, part_slots=None, extra=None): ...
    def AddWeaponForMainNpc(self): ...
    def AttachWatchToHandModel(self): ...
    def CacheModel(self): ...
    def ChangeArmClothes(self, arm_clothes): ...
    def ChangeGender(self, gender): ...
    def ChangeWatchMode(self, watch_mode): ...
    def ChangeWeaponSkinId(self, skin_id): ...
    def CheckClearHeroSkinAnimDlc(self): ...
    def CheckEmoteModelAttach(self): ...
    def CheckHeroAttachModel(self): ...
    def CheckHeroSkinEffect(self): ...
    def CheckNeedDownload(self): ...
    def CheckPlayHeroSkinAnim(self, is_reload=True): ...
    def CheckRefreshNpcPose(self): ...
    def CheckWatchModel(self): ...
    def ClearHeroSkinPose(self): ...
    def ClearPose(self): ...
    def ClearPoseOnEmoteEnd(self): ...
    def ClearPoseOnExecuteEnd(self): ...
    def CreateWeaponCaseByItemProto(self, item_proto): ...
    def DelHeroAttachModel(self): ...
    def DelWeapon(self): ...
    def DelaySetDlcNodePosition(self): ...
    def Destroy(): ...
    def DetachWeapon(self): ...
    def EndRotateRecover(self): ...
    def GetBasicGraph(self): ...
    def GetDlcNodePosition(self): ...
    def GetDlcUINode(self): ...
    def GetHeroId(self): ...
    def GetLobbyPoseId(self): ...
    def GetModelCls(self): ...
    def GetModelComponentList(self): ...
    def GetModelOwner(self): ...
    def GetModelSkeleton(self): ...
    def GetModelUnitID(self): ...
    def InitModelDlcStatusNode(self): ...
    def IsClothesNeedDownload(self): ...
    @property
    def IsVisible(self): ...    def LoadHandModel(self, callback=None): ...
    def OnAttachWeaponCaseDone(self, _): ...
    def OnDestroy(self): ...
    def OnHallShowModelLoaded(self, is_reload=False): ...
    def OnHandModelLoaded(self, callback=None): ...
    def OnMouseEnd(self): ...
    def OnMouseMove(self, x, y, rotate_x=True, rotate_y=True): ...
    def OnMouseRDown(self, x, y): ...
    def OnMouseRUp(self, x, y): ...
    def OnPlayEmoteEnd(self, callback): ...
    def OnRefreshDownloadState(self, dlc_id, status): ...
    def OnWatchModelDone(self): ...
    def PlayEmoteAnim(self, interrupt=True): ...
    def PlayExecuteAnim(self): ...
    def RefreshCurAttachWeaponCaseForDlc(self): ...
    def RefreshWeaponDlcids(self): ...
    def RefreshWeaponModelAttach(self, is_mvp=False): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def ResetAttensionDlcIds(self): ...
    def ResetDlcId(self): ...
    def ResetModelPos(self): ...
    def SetArmClothes(self, arm_clothes, refresh_dlc=True): ...
    def SetIsShowHeroSkin(self, value): ...
    def SetLobbyPoseId(self, pose_id): ...
    def SetMipBias(self, bias): ...
    def SetModelPos(self, pos, yaw): ...
    def SetWatchItemId(self, watch_item_id): ...
    def SetupCastDynamicShadow(self): ...
    def ShowEmoteAttachModel(self, value): ...
    def ShowEmoteModel(self, item_proto, emote_loop=True, callback=None): ...
    def ShowExecuteModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowExecutedModel(self, item_proto, execute_loop=True, is_stop=False): ...
    def ShowHeroSkinModel(self, item_proto, is_idle=False, is_executed=False, without_anim=False): ...
    def ShowModel(self, use_ready_to_appear=False): ...
    def ShowTailEffect(self, item_proto): ...
    def StopTailEffect(self): ...
    def SwitchToHandModel(self, is_switch): ...
    def _ChangeShaderGraphParamForHallDollGun(self): ...
    def _DoAddWeapon(self, equip_id, skin_id, guise_id, part_slots, extra=None, is_reload=False): ...
    def _GetDefaultSuitItemId(self): ...
    def _GetPoseInfoByWeaponId(self, weapon_id): ...
    def _RefreshDlcInfoForPlayEmote(self, emote_item_id): ...
    def _RefreshDlcInfoForPlayExecute(self, execution_item_id): ...
    def _RefreshInfoOnArmClothesChange(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def entity_area(self): ...    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class MallModelDescribeNode(UINode):
    LIST_BLOW_NAME: str = 'list_below'
    NODE_TAG_CLS: type = <class 'gclient.ui.common.quality_tag_node.QualityTagNewNode'>
    TIMER_COUNTER: int = 1
    TXT_PEIJIAN_CLS: type = <class 'gclient.framework.ui.widgets.ui_text.UIText'>
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetListviewSize(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def LoadData(self, item_proto, reset_content_size=True, show_part_text=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnClickJumpMallPartView(self, btn): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def ResetContentSize(self): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class MallModelFloorComp(object):
    def AddFloorLevel(self): ...
    def BackgroundFadeInOutTick(self, prim, param, start_time, duration, start_value, end_value, dt): ...
    def EnterSkinV6Intro(self): ...
    def FadeInBackground(self, gacha_setting_proto): ...
    def FadeoutBackground(self, gacha_setting_proto): ...
    def GetFloorProto(self): ...
    def LeftSkinV6Intro(self, btn=None): ...
    def RemoveFloorLevel(self): ...
    def _MallModelFloorComp__pre_visible_component(self, value, hidden_reason): ...

class MallModelTouchPanel(WarehouseModelTouchPanel):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableDoubleTouchZoom(self, is_enable): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnModelTouchBegin(self, touch, event): ...
    def OnModelTouchEnd(self, touch, event): ...
    def OnModelTouchMove(self, touch, event): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class PanelActionNode(UINode):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def BuildData(item_info, skill_func, execute_func, hand_func, hand_skill_func): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def LoadData(self, data): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnExecuteClick(self, btn): ...
    def OnHandClick(self, btn): ...
    def OnHandSkillClick(self, btn): ...
    def OnSkillClick(self, btn): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class Swallower(object):
class UINode(object):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class UITexture(UINode):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddExternalImage(self, key, path): ...
    def AddHiddenReason(self, reason): ...
    def AutoStopVideoOnRelease(self): ...
    def CheckExternalImageExist(self, path): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def DisableLoadingExternalImageNode(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLoadingExternalImageNode(self): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLoading(self): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSameTexture(self, value): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def LoadDefaultTexture(self, value_int): ...
    def LoadTextureAndCheckScale9Enabled(self, value, texture_type): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnDownloadRefreshTexture(self, value): ...
    def OnRequestNetTexture(self, host, image_url, request, reply): ...
    def OnRequestNetVideo(self, host, video_url, request, reply): ...
    def OnWidgetRelease(self, callback_type): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayVideo(self, value): ...
    def PlayVideoCallback(self, event, msg): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RequestNetTexture(self, image_url): ...
    def RequestNetVideo(self, video_url): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetExternalImage(self, key, isok): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetReverse(self): ...
    def SetTextColorByList(self, color_list): ...
    def SetVertexColor(self, enable, bottom_left=None, bottom_right=None, top_left=None, top_right=None): ...
    def SetVideoEndCallback(self, callback): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def StopVideo(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    @property
    def external_image_key(self): ...    def getContentSize(self): ...
    @property
    def gray(self): ...    @property
    def hidden_reason(self): ...    def initCircle(self, angle, cx, cy): ...
    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setCicrlePercent(self, percent): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def texture(self): ...    @property
    def video(self): ...    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class VideoNode(UINode):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def ClickClose(self, btn): ...
    def ClickExecution(self, btn): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ExitExecution(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def JumpUrl(self, btn): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayExecution(self, item_id): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def ShowPanelClose(self, visible): ...
    def StopAnim(self): ...
    def StopVideo(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def video(self): ...    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...


