# module: gclient.gameplay.uicomponents.hud_calculation_teammate_display_comp

import cc
import cconst
import consts
import controller_util
import copy
import events
import lang
import match_client_data
import six2
import space_data
import text_message_data
import ui_define

class CalOneMoreGameComp(object):
    def CheckShowOneMoreGameWindow(self): ...

class CalculationModelManager(Singleton, HallDollManagerBase):
    def AddHiddenReason(self, reason): ...
    def AddMemberUINode(self, slot, index, total_num, play_anim=True): ...
    def AddTeammate(self, player_id, gender, face_dict, arm_clothes, slot, index, total_num, extra): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def ClearHiddenReason(self): ...
    def ClearWarmingUpHiddenReason(self): ...
    def Destroy(): ...
    def DestroyDoll(self, doll): ...
    def EnsureGetCameraControl(self): ...
    def GetCameraParam(self): ...
    def HideAllCalculationModel(self): ...
    def InitCamera(self): ...
    def MemberUINodeAddHiddenReason(self, npc_id, hidden_reason): ...
    def MemberUINodeRemoveHiddenReason(self, npc_id, hidden_reason): ...
    def OnDestroy(self): ...
    def OnDollModelLoaded(self, doll_id): ...
    def OnEnter(self, info): ...
    def OnLeave(self): ...
    def OnMoveToMvpPlayerModel(self): ...
    def RefreshMemberUiPos(self): ...
    def RefreshTeammateModels(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def RestoreCamera(self): ...
    def SetControl(self, control): ...
    def _CreateDoll(self, player_id, target_index, arm_clothes, pos_and_yaw, gender=1, is_main_npc=False, extra=None): ...
    def _GetTeammatePosYawByIndex(self, index, total_num): ...
    def _GetTeammateUIPosByIndex(self, index, total_num): ...
    def _GetTransformedUIPos(self, pos): ...
    def _TransformPosConsiderCutout(self, pos): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class CalculationPanelTopComp(object):
    def OnHidePanelByCapture(self, is_capture): ...
    def OnReport(self, _): ...

class CalculationSoundComp(object):
class CalculationTeamPanelBtnComp(CommonCalculationPanelBtnBaseComp):
    def CheckCanPlayOutstandingShow(self): ...
    def CountdownTimer(self): ...
    def GetParentPanelBtn(self): ...
    def HandleButtonRB(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HandleButtonRT(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HandleButtonX(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def OnClickAgain(self, _): ...
    def OnClickDetail(self, _): ...
    def OnOutstandingShow(self, _): ...
    def OnPlayBack(self, btn=None): ...
    def OnPlayerAvatarJoinAgainUpdate(self): ...
    def OnWatchKiller(self, btn=None): ...
    def RefreshBtnState(self): ...
    def ReturnToHall(self, btn=None): ...
    def StartCountdownTimer(self): ...
    def _CancelCountDownTimer(self): ...

class CalculationTeammateDisplayWindow(UIWindow):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def CheckDLcExist(): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCalculationModelData(self, combat_data_sorted): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetMatchAndSpace(self): ...
    def GetPersonalCardPopLocation(self, location_idx=0): ...
    def GetRecoveryFunc(): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsGrandTheftMatchType(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnDestroy(self): ...
    def OnFocus(self, value): ...
    def OnKeyDownEsc(self): ...
    def OnScreenSizeChanged(self): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayCloseAnim(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PlayLoopAnim(self): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def RefreshMemberNodePos(self): ...
    def RefreshPanelResult(self): ...
    def RefreshPcKey(self): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RestartPosUpdateTimer(self): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetFriendNodePos(self, slot, pos, play_anim=True): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetTopLeftVisible(self): ...
    def SetTopVictoryText(self): ...
    def SetUINodeTranslation(self, slot, pos, play_anim=True): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def StopPosUpdate(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _SetHallLevel(self, visible): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _cancelLongTouch(self): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _postComponents(self, bdict): ...
    def _show_node_hover(self, node, visible): ...
    def _tickComponents(self, dtime): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class CalculationTeammateDisplayWindowV2(UIWindow):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddGamepadKeyPanel(self, func_id, panel, with_txt=False, force_long=False): ...
    def AddHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def CheckCanPlayOutstandingShow(self): ...
    def CheckDLcExist(): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def CheckShowOneMoreGameWindow(self): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def CountdownTimer(self): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetParentPanelBtn(self): ...
    def GetPersonalCardPopLocation(self, location_idx=0): ...
    def GetRecoveryFunc(): ...
    def GetSettleTagData(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTopPanel(self): ...
    def GetTotalFrame(self, anim_name): ...
    def GetUINodePosition(self, idx): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HandleButtonRB(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HandleButtonRT(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HandleButtonX(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnBeLikedListChanged(self, be_liked_id, liked_id): ...
    def OnClickAgain(self, _): ...
    def OnClickDetail(self, _): ...
    def OnDestroy(self): ...
    def OnFocus(self, value): ...
    def OnGameStateEnumChange(self, old_state, new_state): ...
    def OnGamepadChange(self, has_gamepad): ...
    def OnGamepadKeySettingChange(self): ...
    def OnHidePanelByCapture(self, is_capture): ...
    def OnKeyDownEsc(self): ...
    def OnOutstandingShow(self, _): ...
    def OnPlayBack(self, btn=None): ...
    def OnPlayerAvatarJoinAgainUpdate(self): ...
    def OnReport(self, _): ...
    def OnScreenSizeChanged(self): ...
    def OnWatchKiller(self, btn=None): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayCloseAnim(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PlayLoopAnim(self): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def PromptLikeTips(self): ...
    def RefreshBtnState(self): ...
    def RefreshLikeCount(self, be_liked_id): ...
    def RefreshPcKey(self): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def ReturnToHall(self, btn=None): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetFriendNodePos(self, slot, pos): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetUINodeTranslation(self, slot, pos): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def StartCountdownTimer(self): ...
    def StopAnim(self): ...
    def _CancelCountDownTimer(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoSetPromptFalse(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _SetHallLevel(self, visible): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _cancelLongTouch(self): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _postComponents(self, bdict): ...
    def _show_node_hover(self, node, visible): ...
    def _tickComponents(self, dtime): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class CommonCalculationPlayerNodeV2(CommonCalculationPlayerNodeV3):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HelperChildex(self, name, wrapper=None): ...
    def HelperSeek(self, name, wrapper=None): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def LoadData(self, data): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def Refresh(self): ...
    def RefreshAll(self): ...
    def RefreshData(self): ...
    def RefreshNode(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def ResetPanelState(self): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _GetWrapper(self, wrapper): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    @property
    def window(self): ...    def zoomChildren(self, bzoom): ...

class CommonCalculationPlayerXDNode(HelperNode):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HelperChildex(self, name, wrapper=None): ...
    def HelperSeek(self, name, wrapper=None): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def LoadData(self, data): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnClickLike(self, btn): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def Refresh(self): ...
    def RefreshAll(self): ...
    def RefreshBtnLike(self): ...
    def RefreshData(self): ...
    def RefreshNode(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def ResetPanelState(self): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _GetWrapper(self, wrapper): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    @property
    def window(self): ...    def zoomChildren(self, bzoom): ...

class CommonCursorDisplayComp(object):
class CommonLikeComp(object):
    def OnBeLikedListChanged(self, be_liked_id, liked_id): ...
    def PromptLikeTips(self): ...
    def _DoSetPromptFalse(self): ...

class CommonPersonalCardLocationComp(object):
    def GetPersonalCardPopLocation(self, location_idx=0): ...

class GameResult(enum):
    DEFEAT: int = 200
    DRAW: int = 100
    QUIT: int = 300
    VICTORY: int = 1
    name_to_values: dict = {'VICTORY': 1, 'DRAW': 100, 'DEFEAT': 200, 'QUIT': 300}
    value_to_names: dict = {1: 'VICTORY', 100: 'DRAW', 200: 'DEFEAT', 300: 'QUIT'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class GamepadKeyNodesManagerComp(object):
    def AddGamepadKeyPanel(self, func_id, panel, with_txt=False, force_long=False): ...
    def OnGamepadChange(self, has_gamepad): ...
    def OnGamepadKeySettingChange(self): ...

class HotSpotCalculationTeammateDisplayWindow(CalculationTeammateDisplayWindow):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def CheckDLcExist(): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCalculationModelData(self, combat_data_sorted): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetMatchAndSpace(self): ...
    def GetPersonalCardPopLocation(self, location_idx=0): ...
    def GetRecoveryFunc(): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsGrandTheftMatchType(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnDestroy(self): ...
    def OnFocus(self, value): ...
    def OnKeyDownEsc(self): ...
    def OnScreenSizeChanged(self): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayCloseAnim(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PlayLoopAnim(self): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def RefreshMemberNodePos(self): ...
    def RefreshPanelResult(self): ...
    def RefreshPcKey(self): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RestartPosUpdateTimer(self): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetFriendNodePos(self, slot, pos, play_anim=True): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetTopLeftVisible(self): ...
    def SetTopVictoryText(self): ...
    def SetUINodeTranslation(self, slot, pos, play_anim=True): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def StopPosUpdate(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _SetHallLevel(self, visible): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _cancelLongTouch(self): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _postComponents(self, bdict): ...
    def _show_node_hover(self, node, visible): ...
    def _tickComponents(self, dtime): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class UINode(object):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class UIText(UiTextBase):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CancelBounceTimer(self): ...
    def CancelTypewriterTimer(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMergeDraw(self, is_enable): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableShadow(self, rgba, offset=(2, -2)): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnTypewriterTimer(self, *args): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def ResetTypewriter(self): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFontSize(self, size): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetTextColorByList(self, color_list): ...
    def SetTypewriterText(self, text, interval=0.1): ...
    def SetVertexColor(self, enable, bottom_left=None, bottom_right=None, top_left=None, top_right=None): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StartTextNumBounce(self, target_num, txt_template='{}', bounce_time=1, bounce_interval=0.03, init_num=0): ...
    def StartTypewriterTimer(self, interval=0.5): ...
    def StopAnim(self): ...
    def StopTypewriter(self, finish_write=True): ...
    def UpdateBounceText(self, init_num, target_num, txt_template, bounce_time, *args): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setFntFile(self, fnt_index): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def string_message_id(self): ...    @property
    def text(self): ...    @property
    def text_color(self): ...    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class UIWindow(UINode):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def CheckDLcExist(): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetRecoveryFunc(): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnDestroy(self): ...
    def OnFocus(self, value): ...
    def OnKeyDownEsc(self): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def RefreshPcKey(self): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _SetHallLevel(self, visible): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _cancelLongTouch(self): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class partial(object):
    args: member_descriptor = <member 'args' of 'functools.partial' objects>
    func: member_descriptor = <member 'func' of 'functools.partial' objects>
    keywords: member_descriptor = <member 'keywords' of 'functools.partial' objects>


def Components(*components, **kwargs): ...

