# module: gclient.gameplay.util.replay_util

import MDebug
import MType
import six2
import time

class AntiPlugDebugDrawer(Singleton):
    def ClearAll(self): ...
    def Destroy(): ...
    def DrawLine(self, start, end, color=(0, 1, 0), kind=''): ...
    def DrawSphere(self, pos, color=(0, 1, 0), radius=0.1, kind=''): ...
    def OnDestroy(self): ...
    def ToMType(self, point): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class ReplayLogManager(Singleton):
    AUTOCLEAR: float = 2.0
    TIMEOUT: float = 600.0

    def Destroy(): ...
    def Enqueue(self, timestamp, line): ...
    def Fetch(self, start, end): ...
    def FetchAll(self): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class Singleton(object):
    def Destroy(): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class defaultdict(dict):
    clear: method_descriptor = <method 'clear' of 'dict' objects>
    copy: method_descriptor = <method 'copy' of 'collections.defaultdict' objects>
    default_factory: member_descriptor = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys: builtin_function_or_method = <built-in method fromkeys of type object at 0x702850e7d8>
    get: method_descriptor = <method 'get' of 'dict' objects>
    items: method_descriptor = <method 'items' of 'dict' objects>
    keys: method_descriptor = <method 'keys' of 'dict' objects>
    pop: method_descriptor = <method 'pop' of 'dict' objects>
    popitem: method_descriptor = <method 'popitem' of 'dict' objects>
    setdefault: method_descriptor = <method 'setdefault' of 'dict' objects>
    update: method_descriptor = <method 'update' of 'dict' objects>
    values: method_descriptor = <method 'values' of 'dict' objects>

class deque(object):
    append: method_descriptor = <method 'append' of 'collections.deque' objects>
    appendleft: method_descriptor = <method 'appendleft' of 'collections.deque' objects>
    clear: method_descriptor = <method 'clear' of 'collections.deque' objects>
    copy: method_descriptor = <method 'copy' of 'collections.deque' objects>
    count: method_descriptor = <method 'count' of 'collections.deque' objects>
    extend: method_descriptor = <method 'extend' of 'collections.deque' objects>
    extendleft: method_descriptor = <method 'extendleft' of 'collections.deque' objects>
    index: method_descriptor = <method 'index' of 'collections.deque' objects>
    insert: method_descriptor = <method 'insert' of 'collections.deque' objects>
    maxlen: getset_descriptor = <attribute 'maxlen' of 'collections.deque' objects>
    pop: method_descriptor = <method 'pop' of 'collections.deque' objects>
    popleft: method_descriptor = <method 'popleft' of 'collections.deque' objects>
    remove: method_descriptor = <method 'remove' of 'collections.deque' objects>
    reverse: method_descriptor = <method 'reverse' of 'collections.deque' objects>
    rotate: method_descriptor = <method 'rotate' of 'collections.deque' objects>


def GetPlayer(): ...
def GetRealPlayerId(): ...
def GetRoomReplayAllTeam(): ...
def GetRoomReplayAnotherAliveMember(cur_player, step): ...
def GetRoomReplayAnotherAliveTeam(cur_team, step): ...
def GetRoomReplayAnotherAliveTeamMember(team, cur_member, step): ...
def GetRoomReplayNextStep(step): ...
def GetRoomReplayTeamMember(team_guid, member_guid): ...
def GetTeammateInfo(): ...
def IsCalculationNow(): ...
def IsEnemyReplay(): ...
def IsPlayback(): ...
def IsPlayerTeammate(avatar_id): ...
def IsRoomReplayPlayerWatchable(team_guid, member_guid): ...
def ReplayLog(fmt, *args): ...
def ReplayServerNow(): ...
def ReplayStartTime(): ...
def RoomReplayWatchAnotherPlayer(cur_player, step): ...
def TimeFromReplayStartTime(): ...

