# module: gclient.gameplay.logic_base.models.common_hand_model_cue

import MEngine
import MHelper
import cconst
import consts
import six2
import time
import unit_model_data

ResourceLoader: _ResourceLoader = <gclient.framework.util.resource_loader._ResourceLoader object at 0x7040c51950>

class CommonHandModelCue(object):
    def AddHandPrimitives(self, hand_model_id): ...
    def ClearAllAnimEffect(self, _): ...
    def ClearAllCurItemCaseAnimEffect(self, _): ...
    def ClearAllMeleeAnimEffect(self, _): ...
    def CueAddInspectExtraModel(self): ...
    def CueForceScaleTransform(self): ...
    def CueInspectAnimEnd(self): ...
    def CueInspectAnimStart(self): ...
    def CueInspectHideDoubleWeapon(self): ...
    def CueInspectShowDoubleWeapon(self): ...
    def CueLoadReloadTwinWeaponCase(self): ...
    def CueReloadAnimEnd(self): ...
    def CueReloadAnimStart(self): ...
    def CueReloadSwitchTwinWeapon(self): ...
    def CueRemoveInspectModel(self): ...
    def CueSkinAttachArmour(self): ...
    def CueSkinDetachArmour(self): ...
    def CueSkinReplaceHandModel(self): ...
    def CueSkinRevertHandModel(self): ...
    def CueStartScaleTransform(self): ...
    def CueSwitchReloadTwinWeaponCase(self): ...
    def CueWeaponEmiPowerClose(self): ...
    def CueWeaponEmiPowerOpen(self): ...
    def HideTwinWeaponCase(self): ...
    def OnDoubleWeaponCaseLoadDone(self, _): ...
    def OnReloadWeaponCaseLoadDone(self, weapon_case): ...
    def OnReplaceHandLoaded(self): ...
    def OnRevertHandLoaded(self): ...
    def PlayCurItemCaseAnimEffect(self, signal_str): ...
    def PlayGunAnimEffect(self, signal_str): ...
    def PlayHandAnimEffect(self, signal_str): ...
    def PlayMeleeAnimEffect(self, signal_str): ...
    def _InspectAnimTick(self): ...
    def _ReloadAnimTick(self): ...

class EquipCaseFactory(object):
    def Create(weapon_id, *args, **kwargs): ...

class IdManager(object):
    def bytes2id(bytes): ...
    def genid(): ...
    def id2bytes(uid): ...
    def id2str(uid): ...
    def is_valid_id(entityid): ...
    def str2id(string): ...

class ItemCase(WeaponCaseBase):
    EnableLazyLoadModel: bool = True
    IsCommonSkillCase: bool = False
    IsDualMelee: bool = False
    IsMelee: bool = False
    IsWeapon: bool = False
    ammunition_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f810>
    body_equip_proto: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520c310>
    equip_proto: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520ca10>
    guise_template_data: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f610>
    is_dual_weapon: bool = False
    is_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e310>
    is_melee: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f590>
    is_own_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520eb90>
    show_guise_bullet_trace: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231a50>
    show_guise_hit_effect: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231b10>
    skin_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f5d0>
    spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e250>
    vice_spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520d250>

    def ActiveBindBomb(self, extra=None): ...
    def AddHiddenReason(self, reason): ...
    def AddWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def AttachWeaponToAvatarBack(self): ...
    def AttachWeaponToAvatarHand(self): ...
    def AttachWeaponToHandAnimWeapon(self): ...
    def AttachWeaponToHandBack(self): ...
    def AttachWeaponToHandEquip(self): ...
    def AttachWeaponToLeftHand(self): ...
    def AttachWeaponToRightHand(self): ...
    def BanSamuraiSmoothSwitchOnce(self): ...
    def ChangeWeaponGuise(self, guise_id): ...
    def ChangeWeaponSkin(self, skin_id): ...
    def CheckIfQuickRaise(self, old_weapon_guid): ...
    def ClearGuiseItemCache(self): ...
    def ClearTrailEffectList(self, effect_list, fadeout=0, is_lefthand=False): ...
    def DeActiveBindBomb(self): ...
    def Destroy(self): ...
    def DisablePrincipleRole(self): ...
    def DropWeapon(self): ...
    def DropWeaponForAvatar(self): ...
    def ForceAttachWeaponToHandAnimWeapon(self): ...
    def ForceAttachWeaponToLeftHand(self): ...
    def ForceAttachWeaponToRightHand(self): ...
    def ForceDropCurWeapon(self): ...
    def ForceDropWeaponForAvatar(self): ...
    def GetDefaultMeleeEquipId(self): ...
    def GetFallDirSpeed(self): ...
    def GetGunSkinPartModelList(self, default_value=None): ...
    def GetGunType(self): ...
    def GetMeleeAttackEffectId(self, hit_pose_id): ...
    def GetMeleeCaseDlcId(self): ...
    def GetMeleeCaseDlcids(self): ...
    def GetMeleeWeaponModelId(self): ...
    def GetWeaponAttrValue(self, name, default=None): ...
    def GetWorldBound(self): ...
    def GetWorldBoundCentre(self): ...
    def HideAttachModel(self): ...
    def InitWeapon(self, part_slots=None, part_loaded_callback=None, all_loaded_callback=None, need_refresh_prop=True, is_reload=False, extra=None): ...
    def IsAllPartsModelLoaded(self): ...
    def IsOwnerValid(self): ...
    def IsSamuraiWithSamuraiSword(self): ...
    def MarkPrincipleRole(self): ...
    def ModelAnimArmWeapon(self, model): ...
    def OnAttachModelLoad(self): ...
    def OnCastSpell(self): ...
    def OnCastSpellStart(self): ...
    def OnCastSpellStop(self): ...
    def OnSpellImmune(self): ...
    def OnWeaponModelLoad(self): ...
    def PlayAttachModelEffect(self, effect_id): ...
    def PlayTrailEffectList(self, effect_list, is_lefthand=False): ...
    def RaiseWeapon(self): ...
    def RaiseWeaponForAvatar(self): ...
    def RefreshGuise3PEffectInCombat(self): ...
    def RefreshGuiseEffect(self): ...
    def RefreshGuiseOverlayIdlePose(self): ...
    def RefreshGuiseSkinAnimPose(self, model, graph_id): ...
    def RefreshGuiseSkinAnimPoseForHand(self): ...
    def RefreshGuiseSkinAnimPoseForWeapon(self): ...
    def RefreshHasGuiseDlcId(self): ...
    def RefreshTpsEffectEntityVisible(self): ...
    def RefreshWeaponAttrFromCombatAttr(self, attr_name): ...
    def RefreshWeaponDecorate(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetIsAds(self, is_ads): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsInShowRoom(self, in_showroom): ...
    def SetIsLoadForWarmingUp(self, is_warmingup): ...
    def SetIsMeleeFirstRaise(self, value): ...
    def SetIsRealAds(self, is_real_ads): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetNoNearPlaneClip(self, enable): ...
    def ShowAttachModel(self): ...
    def ShowModel(self): ...
    def UseAllPartWarmingUp(self, is_warmingup): ...
    def _GetGuiseModelId(self, origin_model_id): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def attach_model_effecet_id(self): ...    @property
    def attach_model_id(self): ...    @property
    def is_cur_taking(self): ...    @property
    def is_destroyed(self): ...    @property
    def is_match_server(self): ...    @property
    def state_relationship(self): ...    @property
    def weapon_model(self): ...
class SkinCoreType(enum):
    SkinCoreGem: int = 1
    SkinCoreMP5: int = 4
    SkinCoreScales: int = 2
    SkinCoreTwin: int = 3
    name_to_values: dict = {'SkinCoreGem': 1, 'SkinCoreScales': 2, 'SkinCoreTwin': 3, 'SkinCoreMP5': 4}
    value_to_names: dict = {1: 'SkinCoreGem', 2: 'SkinCoreScales', 3: 'SkinCoreTwin', 4: 'SkinCoreMP5'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class defaultdict(dict):
    clear: method_descriptor = <method 'clear' of 'dict' objects>
    copy: method_descriptor = <method 'copy' of 'collections.defaultdict' objects>
    default_factory: member_descriptor = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys: builtin_function_or_method = <built-in method fromkeys of type object at 0x702850e7d8>
    get: method_descriptor = <method 'get' of 'dict' objects>
    items: method_descriptor = <method 'items' of 'dict' objects>
    keys: method_descriptor = <method 'keys' of 'dict' objects>
    pop: method_descriptor = <method 'pop' of 'dict' objects>
    popitem: method_descriptor = <method 'popitem' of 'dict' objects>
    setdefault: method_descriptor = <method 'setdefault' of 'dict' objects>
    update: method_descriptor = <method 'update' of 'dict' objects>
    values: method_descriptor = <method 'values' of 'dict' objects>


