# module: gclient.gameplay.logic_base.models.para_model_comp

import MHelper
import MType
import cconst
import consts
import copy
import events
import formula
import ireplay
import math
import unit_model_data

PARA_ON_SKY_STAGE: tuple = (3, 4, 7, 5, 6, 8)
TAG_SPACE: int = 2
TAG_UNIQUE: int = 4

class ParaAvatarReason(enum):
    Airplane: int = 1
    Born: int = 0
    HighSky: int = 3
    Reborn: int = 2
    Transfer: int = 4
    name_to_values: dict = {'Born': 0, 'Airplane': 1, 'Reborn': 2, 'HighSky': 3, 'Transfer': 4}
    value_to_names: dict = {0: 'Born', 1: 'Airplane', 2: 'Reborn', 3: 'HighSky', 4: 'Transfer'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class ParaAvatarStage(enum):
    Cinematics: int = 1
    CloseParachute: int = 6
    Default: int = 0
    Finish: int = 9
    FreeFall: int = 3
    FreeFallWithWeapon: int = 4
    LandGround: int = 8
    OnAircraft: int = 2
    OpenParachute: int = 5
    Parachute: int = 7
    name_to_values: dict = {'Default': 0, 'Cinematics': 1, 'OnAircraft': 2, 'FreeFall': 3, 'FreeFallWithWeapon': 4, 'OpenParachute': 5, 'CloseParachute': 6, 'Parachute': 7, 'LandGround': 8, 'Finish': 9}
    value_to_names: dict = {0: 'Default', 1: 'Cinematics', 2: 'OnAircraft', 3: 'FreeFall', 4: 'FreeFallWithWeapon', 5: 'OpenParachute', 6: 'CloseParachute', 7: 'Parachute', 8: 'LandGround', 9: 'Finish'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class ParachuteControllerComp(object):
    def ClearShakeOnSky(self): ...
    def EventOnFreeFall(self, joy_off=None, pitch=None): ...
    def JoyShakeOnParachute(self, x, y, force=False): ...
    def JoyShakeOnSky(self, x, y): ...
    def SetGraphJoyStickYaw(self, x, y): ...
    def SetParachuteFallAction(self, fall_action): ...
    def SetParachutePitchRad(self, pitch): ...
    def SetParachuteRollRad(self, roll_rad): ...
    def UpdateFreeFallPose(self, x, y, pitch): ...

class ParachuteGraphModel(object):
    def CheckTrainerForPassive(self, force_check=False): ...
    def ForceLockSpeedForLeaveTrainer(self): ...
    def JumpToStateCloseParachute(self): ...
    def JumpToStateFreeFall(self): ...
    def JumpToStateLandGround(self): ...
    def JumpToStateOnAircraft(self): ...
    def JumpToStateOpenParachute(self): ...
    def JumpToStateParaFinish(self): ...
    def JumpToStateParachute(self): ...
    def PopToIdleGraph(self): ...
    def PushParaGraph(self): ...
    def ReadjustParaGraphId(self): ...
    def RefreshTraineeUseFollower(self): ...
    def SetIsOpenFire(self, is_open): ...
    def SetOnAircraftPose(self, pose): ...
    def SetOpenFireAction(self, open_fire_action): ...
    def UnlockSpeedForTrainerPara(self): ...
    def _CancelUnlockTrainerSpeedTimer(self): ...
    def _GetTpsParaGraphFile(self): ...

class ParachuteModelComp(object):
    CheckFreefallMaxSpeed: AsyncDescriptor = <gshare.async_util.AsyncDescriptor object at 0x6f9c303ad0>
    CheckLocalVelocityZ: AsyncDescriptor = <gshare.async_util.AsyncDescriptor object at 0x6f9c303b10>

    def ChangeParachuteCameraMode(self): ...
    def CheckEnableHandIKToWeapon(self): ...
    def EnableSpeedZOpenPara(self, value): ...
    def FinishParachuteGraph(self): ...
    def SetForceParachuteAction(self, force): ...
    def SetParaModelParaState(self, para_stage): ...
    def _InitParachuteSpeedZ(self, local_z=True): ...
    def _OnJumpTo_CloseParachute(self, info): ...
    def _OnJumpTo_FreeFall(self, info): ...
    def _OnJumpTo_FreeFallOpenFire(self, info): ...
    def _OnJumpTo_LandGround(self, info): ...
    def _OnJumpTo_OnAircraft(self, info): ...
    def _OnJumpTo_OpenParachute(self, info): ...
    def _OnJumpTo_Parachute(self, info): ...
    def _OnJumpTo_PassiveFly(self, info): ...

class ParachuteUnitModelComp(object):
    def AddFollower(self, avatar_model): ...
    def AddParachuteModel(self): ...
    def CreateFollowerEntity(self): ...
    def DestroyFollowerEntity(self): ...
    def DestroyParachuteModel(self): ...
    def OpenParachuteEndForParaModel(self): ...
    def RemoveFollower(self): ...
    def ResetYawForFolloweeModel(self): ...
    def SetParachuteModelRenderSet(self, render_set): ...
    def SetParachuteModelVisible(self, visible): ...
    def _TickFollowerYawToSelf(self, dt=None): ...

class StoryTick(object):
    _instance: StoryTick = <gclient.framework.util.story_tick.StoryTick object at 0x7005e37fd0>

    def Add(self, func, frames=0): ...
    def Remove(self, func): ...
    def doAdd(self, func, frames): ...
    def doRemove(self, func): ...
    def onTick(self, _, dtime): ...


def Async(tag=0): ...

