# module: gclient.gameplay.logic_base.models.robot_avatar_model

import MHelper
import MPhysics
import MType
import cconst
import consts
import events
import formula
import graph_index_map
import math
import moving_speed_data
import six2
import spell_util
import time
import weapon_util

GRAPH_DIR: str = 'Graph/'

class AvatarModel(PoseSenderModel):
    logger: Logger = <Logger Model (DEBUG)>
    material_change_funcs: cached_property = <gshare.decorators.cached_property object at 0x6f9c4dfdd0>
    material_reset_funcs: cached_property = <gshare.decorators.cached_property object at 0x6f9c300510>
    material_set_param_funcs: cached_property = <gshare.decorators.cached_property object at 0x6f9c300590>

    def AddAttachEntityForMaterialChange(self, entity, is_add): ...
    def AddBeardModel(self): ...
    def AddFollower(self, avatar_model): ...
    def AddHiddenReason(self, reason): ...
    def AddLoadTask(self, name): ...
    def AddParachuteModel(self): ...
    def AddStealthAttachEffectEntity(self, effect_entity): ...
    def AddStealthAttachEntity(self, entity): ...
    def AddTargetSlot(self, slot_name, actor): ...
    def AddTechState(self, id, custom_param=None): ...
    def AddTechStateWholeBody(self, proto_id, custom_param=None): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def AddWeapon(self, guid): ...
    def AddWeaponPart(self, weapon_guid, part_id): ...
    def AdjustBeardTachPosition(self): ...
    def AnimArmWeapon(self, gun_type=None, left_hand_case_gun_type=False): ...
    def ApplyCustomStencil(self, custom_stencil, is_check=False): ...
    def ApplyFilterMotion(self, apply): ...
    def ApplyGravity(self, enable=True): ...
    def ApplyMotion(self, flag=True): ...
    def AttachToParent(self, entity, basepoint, hardpoint): ...
    def BatchResetShaderGraphParameter(self, params, layer=-1): ...
    def BatchSetShaderGraphParameter(self, params, values, layer=-1): ...
    def BindBoneColliderCallFunc(self, result): ...
    def BindEventSignalNotify(self): ...
    def CalcDeathDir(self, hit_dir): ...
    def CallOwner(self, method, *args, **kwargs): ...
    def CancelBeardModelTimer(self): ...
    def CancelStealthSound(self): ...
    def ChangeCastDynamicShadowOnStealth(self): ...
    def ChangeCustomMaterial(self, material_path, **kwargs): ...
    def ChangeCustomMaterialWholeBody(self, material_path, **kwargs): ...
    def ChangeLeftHandWeapon(self): ...
    def ChangeMaterialByRank(self, proto_id, duration, change_enum): ...
    def ChangeMotionState(self, motion_state): ...
    def ChangeShaderGraphMaterial(self, shader_graph_path, layer=-1, inherit=False): ...
    def ChangeShaderGraphMaterialWholeBody(self, material_path, layer=-1, inherit=False): ...
    def ChangeStealthState(self, to_stealth): ...
    def ChangeUpperMotionState(self, upper_motion_state): ...
    def ChangeWeapon(self): ...
    def CheckBodyAttachModel(self): ...
    def CheckCreateAttachModel(self, model_id, is_attach, hardpoint, basepoint, is_execute=False): ...
    def CheckExecuteOnDead(self): ...
    def CheckHeroAttachModel(self): ...
    def CheckHideOnWeaponCaseCreated(self, weapon_case): ...
    def CheckRecreateSkeletonOnReloaded(self, data): ...
    def CheckTrainerForPassive(self, force_check=False): ...
    def CheckVehicleGraph(self): ...
    def CheckWeaponModelValidForFunc(self, weapon_model): ...
    def ClearALLCueCameraEffect(self): ...
    def ClearAllCueEffectCache(self): ...
    def ClearAllCueSoundCache(self): ...
    def ClearAllGraphSyncSlaveReason(self): ...
    def ClearAllSkeletonEffect(self): ...
    def ClearCharctrlHeightReason(self): ...
    def ClearCueEffectCache(self, graph_id, path): ...
    def ClearCueEffectCacheByGraphID(self, graph_id): ...
    def ClearHiddenReason(self): ...
    def ClearMotionBlur(self, elapsedTime, centerU, centerV): ...
    def ClearMoveDirection(self): ...
    def ClearRigidBodies(self): ...
    def ClearSkeletonEffect(self, effect_id): ...
    def ClearSkeletonEffectByEffectId(self, effect_id): ...
    def ClearSkeletonEffectByEffectIdImmediately(self, effect_id): ...
    def ClearSkeletonEffectImmediately(self, effect_id): ...
    def ClearTechParam(self): ...
    def ClearTechState(self): ...
    def ClearWarmingUpHiddenReason(self): ...
    def CreateCharCtrl(self, width, height, physics_info, **kwargs): ...
    def CreateEmoteShowModel(self): ...
    def CreateFilter(self, debug=False): ...
    def CreateFollowerEntity(self): ...
    def CreatePoseSender(self): ...
    def CreateSpecifyBone(self, bone_name): ...
    def CueAddParachute(self): ...
    def CueExecuteHideModel(self): ...
    def CueExecuteShowModel(self): ...
    def CuePauseSlidingSound(self): ...
    def CuePulseArrowHide(self): ...
    def CuePulseArrowShow(self): ...
    def CueRecoverSlidingSound(self): ...
    def CueSamuraiBlockEnd(self): ...
    def CueSaveEnd(self): ...
    def CueStartShowEmoteModel(self): ...
    def CueStopShowEmoteModel(self): ...
    def CueTpsFireBomb(self): ...
    def CustomStencilCheck(self, target_stencil, *args): ...
    def DebugChangeSkinWithRepositoryName(self, repository_name, stage='3p'): ...
    def DeleteFilter(self): ...
    def DeletePoseSender(self): ...
    def Destroy(self): ...
    def DestroyBeardModel(self): ...
    def DestroyCppModel(self): ...
    def DestroyFollowerEntity(self): ...
    def DestroyParachuteModel(self): ...
    def DestroyWeapon(self, guid): ...
    def DisableAutoFrameLimit(self): ...
    def DisableClipMaterials(self): ...
    def DisableGraphSyncSlaveWithReason(self, reason): ...
    def DisableInvisibleFrameLimit(self): ...
    def DisableMixMapAsFarAsPossible(self): ...
    def DisableNormalMap(self): ...
    def DisableOutlined(self): ...
    def DisablePrincipleRole(self): ...
    def DisableSignalTypes(self, signal_types): ...
    def DoWeaponOpticShaderRefresh(self): ...
    def DoWeaponPartsAction(self, func_name, *func_args, **kwargs): ...
    def DropCurLeftHandWeapon(self): ...
    def DropCurSpecWeapon(self): ...
    def DropCurWeapon(self, guid=None): ...
    def EnableAutoFrameLimit(self): ...
    def EnableCharCtrlWithReason(self, reason): ...
    def EnableDockingDetector(self, enable=True): ...
    def EnableFilterWithReason(self, reason): ...
    def EnableGraphSyncMaster(self, enable=True): ...
    def EnableGraphSyncSlave(self, enable=True): ...
    def EnableGraphSyncSlaveWithReason(self, reason): ...
    def EnableInvisibleFrameLimit(self, frames): ...
    def EnableIsLookAt(self, isLookAt): ...
    def EnableOutlined(self, color, thickness): ...
    def EnablePoseSender(self, is_enable): ...
    def EnablePoseSenderWithReason(self, reason): ...
    def EnableSignalTypes(self, signal_types): ...
    def ExitState(self, state): ...
    def FilterMotionNotifyCallback(self, motion): ...
    def FireEvent(self, event, gid=-1): ...
    def FireJumpEventForJump(self): ...
    def FireLocomotionEvent(self, event): ...
    def ForceDropLeftHandWeapon(self, old): ...
    def ForceDropWeapon(self, guid): ...
    def ForceLockSpeedForLeaveTrainer(self): ...
    def GetAllPrim(self, need_sorted=False): ...
    def GetBoneLocalPosition(self, bone): ...
    def GetBoneLocalTransform(self, bone): ...
    def GetBoneModelPosition(self, bone): ...
    def GetBoneTransform(self, bone): ...
    def GetBoneWorldPosition(self, bone): ...
    def GetBoneWorldTransform(self, bone): ...
    def GetCurClientLeftHandWeaponCase(self): ...
    def GetCurClientWeaponCase(self): ...
    def GetCurClientWeaponGunType(self): ...
    def GetGraphHandleInGraphStack(self, graph_name): ...
    def GetGraphSyncMode(self): ...
    def GetMotionSkeletonFile(skeleton): ...
    def GetMoveYawDiff(self, x, z): ...
    def GetOwnerSpeed(self): ...
    def GetPrimWorldBound(self): ...
    def GetPrimWorldBoundCentre(self): ...
    def GetPrimWorldBoundCentreWithAttachments(self): ...
    def GetPrimWorldBoundLength(self): ...
    def GetPrimWorldBoundWithAttachments(self): ...
    def GetShaderGraphOriginParameter(self, param, layer=-1): ...
    def GetShaderGraphParameter(self, param, layer): ...
    def GetShaderParameter(self, param): ...
    def GetSkeleton(self): ...
    def GetSkeletonDynamicWorldBound(self): ...
    def GetSkeletonDynamicWorldBoundCentre(self): ...
    def GetSkeletonEffectEntities(self, eff_id): ...
    def GetSkeletonEffectEntitiesByEffectId(self, effect_id): ...
    def GetSlideExtraJumpSpeed(self, yaw_diff, is_fall=False): ...
    def GetSlideSpeed(self, normal_speed=None): ...
    def GetStopYawOffset(self): ...
    def GetVariableF(self, varname, gid=-1): ...
    def GetVariableI(self, varname, gid=-1): ...
    def GetVariableS(self, varname, gid=-1): ...
    def GetVariableV3(self, varname, gid=-1): ...
    def GetVariableZ(self, varname, gid=-1): ...
    def GetWeaponCase(self, guid): ...
    def HandIkToWeapon(self, enable=True, hand_type=0): ...
    def HasActorComponent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HaveWarmingUpHiddenReason(self, reason): ...
    def HideAllAttachedNormalModes(self): ...
    def HideHeroAttachModel(self, hide, hide_scabbard, hidden_reason): ...
    def HideTeammateDyingEffect(self): ...
    def IsEnableOutlined(self): ...
    def IsGraphSyncSlave(self): ...
    def IsMoving(self): ...
    def IsPrincipleRole(self): ...
    @property
    def IsVisible(self): ...    def JumpBreak(self): ...
    def JumpLand(self): ...
    def JumpToDualFire(self, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def JumpToDualFireEnd(self): ...
    def JumpToFire(self, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def JumpToFireEnd(self): ...
    def JumpToIdle(self): ...
    def JumpToMeleeEnd(self): ...
    def JumpToMeleeStart(self, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def JumpToState(self, state, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def JumpToStateCloseParachute(self): ...
    def JumpToStateFreeFall(self): ...
    def JumpToStateLandGround(self): ...
    def JumpToStateOnAircraft(self): ...
    def JumpToStateOpenParachute(self): ...
    def JumpToStateParaFinish(self): ...
    def JumpToStateParachute(self): ...
    def Load(self, data, done=None, **create_kwargs): ...
    def MakeSureBones(self): ...
    def MarkPrincipleRole(self): ...
    def ModelExpireCallback(self, ientity): ...
    def OnBodyAttachModelDone(self): ...
    def OnCineDisplayPerformer(self, trigger, cueinput): ...
    def OnCineHidePerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformers(self, trigger, cueinput): ...
    def OnCineRenamePerformer(self, trigger, cueinput): ...
    def OnConnectOnVehicle(self): ...
    def OnCrouch(self, crouch): ...
    def OnDead(self, info): ...
    def OnEmoteWeaponModelLoaded(self, weapon_case): ...
    def OnGhost(self): ...
    def OnHit(self, info): ...
    def OnHitSamurai(self, info): ...
    def OnKnockDown(self, is_knock_down): ...
    def OnLoseConnectOnVehicle(self): ...
    def OnPoseTypeChange(self, pose_type): ...
    def OnProne(self, prone, to_stand=True): ...
    def OnPull(self, info): ...
    def OnReborn(self, info): ...
    def OnSaveEnd(self): ...
    def OnSlide(self, slide, to_stand=False): ...
    def OnSpeedLevelChange(self): ...
    def OnVisibleChanged(self, visible): ...
    def OnWeaponPartModelFinishLoad(self, weapon_model): ...
    def OpenParachuteEndForParaModel(self): ...
    def PauseGraph(self, pause, gid=-1): ...
    def PlayAnimation(self, anim_name, single_play=True, remove_motion=True, play_speed=1.0): ...
    def PlayDeadCoinEffect(self, info): ...
    def PlayEffectById(self, effect_id, max_life=-1, scale=1, bone='root', offset=(0, 0, 0), insure_play=False): ...
    def PlayMeleeSkill(self, skill_type=0, info={}): ...
    def PlaySkeletonEffect(self, effect_str, max_life=-1, insure_play=False, effect_id=None): ...
    def PlaySkinDeadAnimAndEffect(self, info): ...
    def PlaySkinDeadEffect(self, sfx_info, material, time_offset, info): ...
    def PopAllSpellGraph(self): ...
    def PopEffectDictByEngineEid(self, engine_eid): ...
    def PopExecuteGraph(self): ...
    def PopGraph(self, graph_id, blendTime=0): ...
    def PopHitGraph(self): ...
    def PopPullGraph(self): ...
    def PopSamuraiHitGraph(self): ...
    def PopToIdleGraph(self): ...
    def PopToLocomotionGraph(self): ...
    def PopUpperGraph(self): ...
    def ProcessMaterialRank(self): ...
    def PushGraph(self, graph, transtime=0, ratio=0): ...
    def PushMaterialRankNode(self, rank_id, proto, duration, change_enum): ...
    def PushParaGraph(self): ...
    def PushUpperGraph(self, graph, transtime=0.0): ...
    def RaiseCurLeftHandWeapon(self): ...
    def RaiseCurSpecWeapon(self): ...
    def RaiseCurWeapon(self): ...
    def ReadjustParaGraphId(self): ...
    def ReceiveDynamicShadow(self): ...
    def Refresh(self): ...
    def RefreshAutoFrameLimit(self): ...
    def RefreshForStealthState(self): ...
    def RefreshHandIK(self, hand_left_ik_tps): ...
    def RefreshMaterialForExtraAttachEntity(self): ...
    def RefreshMoveSpeed(self): ...
    def RefreshStealthAttachEffectEntities(self): ...
    def RefreshStealthAttachEntities(self): ...
    def RefreshTeammateTechState(self): ...
    def RefreshTraineeUseFollower(self): ...
    def RefreshWeaponList(self): ...
    def Reload(self, data, done=None, use_ready_to_appear=True): ...
    def ReloadPrimitives(self, data, use_ready_to_appear=True): ...
    def ReloadSkeleton(self, data): ...
    def ReloadWeaponStop(self): ...
    def RemoveCharctrlHeightReason(self, reason): ...
    def RemoveFollower(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveLoadTask(self, name): ...
    def RemoveStealthAttachEffectEntity(self, effect_entity): ...
    def RemoveStealthAttachEntity(self, entity): ...
    def RemoveTechState(self, proto_id): ...
    def RemoveTechStateWholeBody(self, proto_id): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def RemoveXRayBlock(self): ...
    def ReplaceGraph(self, graph_id, graph): ...
    def RescueOtherFinish(self): ...
    def ResetCustomMaterial(self): ...
    def ResetCustomMaterialWholeBody(self): ...
    def ResetHairPrim(self): ...
    def ResetLocomotionGraphID(self): ...
    def ResetLocomotionGraphParam(self): ...
    def ResetMaterialByRank(self, proto_id): ...
    def ResetPosResult(self): ...
    def ResetShaderGraphMaterial(self, layer=-1): ...
    def ResetShaderGraphMaterialWholeBody(self): ...
    def ResetShaderGraphParameter(self, param, layer=-1): ...
    def ResetShaderGraphParameters(self, layer=-1): ...
    def ResetShaderParameter(self, param): ...
    def ResetYawForFolloweeModel(self): ...
    def ResizeCharCtrlFpsModeRadius(self, is_fps_mode): ...
    def ResizeCharCtrlPoseHeight(self, pose_type): ...
    def ResizeCharctrHeightForReason(self, reason): ...
    def RestoreTechStateParamWholeBody(self): ...
    def SetAsCSMRole(self, is_role): ...
    def SetCharCtrlProne(self, enable): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetEnableRideVelocity(self, enable): ...
    def SetEnableSlope(self, enable): ...
    def SetEnableVisibilityOptimize(self, enable): ...
    def SetFilterInputInterval(self, value): ...
    def SetFresnelShowPercent(self, percent): ...
    def SetGraphDynamicAnim(self): ...
    def SetGraphYawHalfLife(self, halflife): ...
    def SetHipDirection(self, x, z): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsDualWeapon(self, is_dual): ...
    def SetIsOpenFire(self, is_open): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetLodDistance(self, layer, distance): ...
    def SetLodDistanceAllLayers(self, distances): ...
    def SetNoNearPlaneClip(self, enable): ...
    def SetOnAircraftPose(self, pose): ...
    def SetOpenFireAction(self, open_fire_action): ...
    def SetOutlinedParam(self, color, thickness): ...
    def SetParachuteModelRenderSet(self, render_set): ...
    def SetParachuteModelVisible(self, visible): ...
    def SetPitchAndYaw(self, pitch, yaw): ...
    def SetPoseSenderInterval(self, value): ...
    def SetShaderGraphParameter(self, param, value, layer=-1): ...
    def SetShaderGraphParameterRecursively(self, param, value, layer=-1): ...
    def SetShaderGraphParameterWholeBody(self, param, value, layer=-1): ...
    def SetShaderParameter(self, param, value, **kwargs): ...
    def SetShaderParameterRecursively(self, param, value): ...
    def SetShaderParameterWholeBody(self, param, value, **kwargs): ...
    def SetSkeletonEffectVisible(self, visible): ...
    def SetSkeletonEffectVisibleForEffectId(self, effect_id, visible): ...
    def SetStealthPercent(self, percent, interval=0.02): ...
    def SetTechState(self): ...
    def SetTechStateCustomParam(self, proto_id, custom_param): ...
    def SetTechStateParam(self, tech_id, custom_param): ...
    def SetTransformWithAttachmentsImmediately(self, transform): ...
    def SetUpperGraphCommonParam(self): ...
    def SetVariableF(self, varname, varvalue, gid=-1): ...
    def SetVariableI(self, varname, varvalue, gid=-1): ...
    def SetVariableS(self, varname, varvalue, gid=-1): ...
    def SetVariableV3(self, varname, varvalue, gid=-1): ...
    def SetVariableZ(self, varname, varvalue, gid=-1): ...
    def SetWarmingUp(self, value): ...
    def SetWarmingUpAppearImmediately(self, value): ...
    def ShiftGraph(self, gid, offset): ...
    def ShowBodyAttachModel(self, show, hidden_reason): ...
    def ShowTeammateDyingEffect(self): ...
    def SignalNotifyCallback(self, trigger, stype, signalStr): ...
    def SkeletonExpireCallback(self, skeleton): ...
    def StartRescueOther(self, rescue): ...
    def StopAnimation(self, anim_name): ...
    def Towards(self, x, z, speed=None): ...
    def UnableCharCtrlWithReason(self, reason): ...
    def UnableFilterWithReason(self, reason): ...
    def UnablePoseSenderWithReason(self, reason): ...
    def UnlockSpeedForTrainerPara(self): ...
    def UpdateSlideMoveVec(self): ...
    def UseDistancedEnemyTechState(self, param, param2): ...
    def UseTechEdgeLine(self, color, thickness): ...
    def UseTechFrozen(self): ...
    def UseTechHighLightXray(self, param, param2, color2): ...
    def UseTechHighlight(self, color, frequency=0.0): ...
    def UseTechXray(self, color2=None, param2=None): ...
    def _CancelUnlockTrainerSpeedTimer(self): ...
    def _CheckCharctrlSizeForReason(self): ...
    def _CheckDropClientWeapon(self): ...
    def _CheckPopNeedYawGraphId(self): ...
    def _CheckSameTachStatus(self, parent, basepoint, hardpoint): ...
    def _CreateParaChangeUtil(self): ...
    def _DoChangeMaterialForTargetEntity(self, entity): ...
    def _DoCheckWeaponFuncAndExec(self, model, func_name, *args): ...
    def _DoSetFresnelParam(self, percent): ...
    def _DoSetTransparencyParam(self, value): ...
    def _EnablePopToLocomotionGraph(self): ...
    def _ExecuteAndCheckHideAction(self, model, func_name, *func_args): ...
    def _GetAvailableModelInfo(self, model_data): ...
    def _GetOwnerHeroId(self): ...
    def _GetOwnerSpeed(self, owner, speed_level, move_dir): ...
    def _GetTpsParaGraphFile(self): ...
    def _OnExit_Emote(self): ...
    def _OnJumpTo_BeExecuted(self, info): ...
    def _OnJumpTo_ClimbLadder(self, info): ...
    def _OnJumpTo_Crouch(self, info): ...
    def _OnJumpTo_Dead(self, info): ...
    def _OnJumpTo_Emote(self, info): ...
    def _OnJumpTo_EnterProne(self, info): ...
    def _OnJumpTo_Execution(self, info): ...
    def _OnJumpTo_ExitProne(self, info): ...
    def _OnJumpTo_Idle(self, info): ...
    def _OnJumpTo_Jump(self, info): ...
    def _OnJumpTo_KnockDown(self, info): ...
    def _OnJumpTo_PickUp(self, info): ...
    def _OnJumpTo_Prone(self, info): ...
    def _OnJumpTo_Reload(self, info): ...
    def _OnJumpTo_RescueOther(self, info): ...
    def _OnJumpTo_Stand(self, info): ...
    def _ProcessCueEnd(self, prev, trigger): ...
    def _SetGraphYaw(self, yaw): ...
    def _SetModelPoseType(self, pose_type): ...
    def _SetVisible(self, visible): ...
    def _TickBeardVisibility(self): ...
    def _TickFollowerYawToSelf(self, dt=None): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, interval, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    @property
    def client_weapon_case(self): ...    def cue_signal_attach_normal_model(self, trigger, signal_str): ...
    def cue_signal_auto_pop_graph(self, trigger, signal_str): ...
    def cue_signal_auto_push_graph(self, trigger, signal_str): ...
    def cue_signal_effect_attach_detach(self, trigger, signal_str): ...
    def cue_signal_event(self, trigger, signal_str): ...
    def cue_signal_execute_third_model(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate_enable(self, trigger, signal_str): ...
    def cue_signal_gun_sfx(self, trigger, signal_str): ...
    def cue_signal_gunfire_sound_event(self, trigger, signal_str): ...
    def cue_signal_motion_blur_to_percent(self, trigger, signal_str): ...
    def cue_signal_player_event(self, trigger, signal_str): ...
    def cue_signal_sound_break(self, trigger, signal_str): ...
    def cue_signal_sound_event(self, trigger, signal_str): ...
    def cue_signal_sound_far_event(self, trigger, signal_str): ...
    def cue_signal_variable_event_sync_stack(self, trigger, signal_str): ...
    def cue_type_node_transition_excute(self, trigger, curinput): ...
    @property
    def gun_type(self): ...    def isModelOnlyValid(self): ...
    def isValid(self): ...
    @property
    def is_destroyed(self): ...    @property
    def is_loaded(self): ...    def onCineDismissPerformer(self, trigger, cueinput): ...
    def onCineDismissPerformers(self, trigger, cueinput): ...
    def onCineDisplayCaption(self, trigger, cueinput): ...
    def onLoaded(self): ...
    @property
    def poseSender(self): ...    @property
    def pose_type(self): ...    @property
    def position(self): ...    @property
    def scale(self): ...    @property
    def skeleton(self): ...    @property
    def space(self): ...    @property
    def tps_idle_graph(self): ...    @property
    def weapon_case(self): ...    @property
    def yaw(self): ...
class AvatarModelCue(ModelCueBase):
    def BindBoneColliderCallFunc(self, result): ...
    def BindEventSignalNotify(self): ...
    def ClearALLCueCameraEffect(self): ...
    def ClearAllCueEffectCache(self): ...
    def ClearAllCueSoundCache(self): ...
    def ClearCueEffectCache(self, graph_id, path): ...
    def ClearCueEffectCacheByGraphID(self, graph_id): ...
    def ClearMotionBlur(self, elapsedTime, centerU, centerV): ...
    def CueAddParachute(self): ...
    def CueExecuteHideModel(self): ...
    def CueExecuteShowModel(self): ...
    def CuePauseSlidingSound(self): ...
    def CuePulseArrowHide(self): ...
    def CuePulseArrowShow(self): ...
    def CueRecoverSlidingSound(self): ...
    def CueSaveEnd(self): ...
    def CueTpsFireBomb(self): ...
    def OnCineDisplayPerformer(self, trigger, cueinput): ...
    def OnCineHidePerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformers(self, trigger, cueinput): ...
    def OnCineRenamePerformer(self, trigger, cueinput): ...
    def SignalNotifyCallback(self, trigger, stype, signalStr): ...
    def _ProcessCueEnd(self, prev, trigger): ...
    def cue_signal_attach_normal_model(self, trigger, signal_str): ...
    def cue_signal_auto_pop_graph(self, trigger, signal_str): ...
    def cue_signal_auto_push_graph(self, trigger, signal_str): ...
    def cue_signal_effect_attach_detach(self, trigger, signal_str): ...
    def cue_signal_event(self, trigger, signal_str): ...
    def cue_signal_execute_third_model(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate_enable(self, trigger, signal_str): ...
    def cue_signal_gun_sfx(self, trigger, signal_str): ...
    def cue_signal_gunfire_sound_event(self, trigger, signal_str): ...
    def cue_signal_motion_blur_to_percent(self, trigger, signal_str): ...
    def cue_signal_player_event(self, trigger, signal_str): ...
    def cue_signal_sound_break(self, trigger, signal_str): ...
    def cue_signal_sound_event(self, trigger, signal_str): ...
    def cue_signal_sound_far_event(self, trigger, signal_str): ...
    def cue_signal_variable_event_sync_stack(self, trigger, signal_str): ...
    def cue_type_node_transition_excute(self, trigger, curinput): ...
    def onCineDismissPerformer(self, trigger, cueinput): ...
    def onCineDismissPerformers(self, trigger, cueinput): ...
    def onCineDisplayCaption(self, trigger, cueinput): ...

class HelenRobotAvatarModelComp(object):
    def FilterMotionNotifyCallback(self, motion): ...

class ModelCharCtrlReason(enum):
    DEAD: int = 1
    DYING: int = 0
    EXECUTION: int = 5
    HOLOGRAPHICROBOT: int = 3
    KICK_UP: int = 6
    ON_AIRCRAFT: int = 2
    VEHICLE: int = 4
    name_to_values: dict = {'DYING': 0, 'DEAD': 1, 'ON_AIRCRAFT': 2, 'HOLOGRAPHICROBOT': 3, 'VEHICLE': 4, 'EXECUTION': 5, 'KICK_UP': 6}
    value_to_names: dict = {0: 'DYING', 1: 'DEAD', 2: 'ON_AIRCRAFT', 3: 'HOLOGRAPHICROBOT', 4: 'VEHICLE', 5: 'EXECUTION', 6: 'KICK_UP'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class ModelFilterReason(enum):
    DEAD: int = 1
    DYING: int = 0
    MONSTER: int = 3
    ROBOT_MASTER: int = 2
    name_to_values: dict = {'DYING': 0, 'DEAD': 1, 'ROBOT_MASTER': 2, 'MONSTER': 3}
    value_to_names: dict = {0: 'DYING', 1: 'DEAD', 2: 'ROBOT_MASTER', 3: 'MONSTER'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class ModelPoseType(enum):
    Crouch: int = 1
    Jump: int = 2
    Ladder: int = 6
    Prone: int = 4
    Slide: int = 3
    Stand: int = 0
    Swim: int = 5
    name_to_values: dict = {'Stand': 0, 'Crouch': 1, 'Jump': 2, 'Slide': 3, 'Prone': 4, 'Swim': 5, 'Ladder': 6}
    value_to_names: dict = {0: 'Stand', 1: 'Crouch', 2: 'Jump', 3: 'Slide', 4: 'Prone', 5: 'Swim', 6: 'Ladder'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class RobotAvatarModel(AvatarModel):
    logger: Logger = <Logger Model (DEBUG)>
    material_change_funcs: cached_property = <gshare.decorators.cached_property object at 0x6f9c4dfdd0>
    material_reset_funcs: cached_property = <gshare.decorators.cached_property object at 0x6f9c300510>
    material_set_param_funcs: cached_property = <gshare.decorators.cached_property object at 0x6f9c300590>

    def AddAttachEntityForMaterialChange(self, entity, is_add): ...
    def AddBeardModel(self): ...
    def AddFollower(self, avatar_model): ...
    def AddHiddenReason(self, reason): ...
    def AddLoadTask(self, name): ...
    def AddParachuteModel(self): ...
    def AddStealthAttachEffectEntity(self, effect_entity): ...
    def AddStealthAttachEntity(self, entity): ...
    def AddTargetSlot(self, slot_name, actor): ...
    def AddTechState(self, id, custom_param=None): ...
    def AddTechStateWholeBody(self, proto_id, custom_param=None): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def AddWeapon(self, guid): ...
    def AddWeaponPart(self, weapon_guid, part_id): ...
    def AdjustBeardTachPosition(self): ...
    def AnimArmWeapon(self, gun_type=None, left_hand_case_gun_type=False): ...
    def ApplyCustomStencil(self, custom_stencil, is_check=False): ...
    def ApplyFilterMotion(self, apply): ...
    def ApplyGravity(self, enable=True): ...
    def ApplyMotion(self, flag=True): ...
    def AttachToParent(self, entity, basepoint, hardpoint): ...
    def BatchResetShaderGraphParameter(self, params, layer=-1): ...
    def BatchSetShaderGraphParameter(self, params, values, layer=-1): ...
    def BindBoneColliderCallFunc(self, result): ...
    def BindEventSignalNotify(self): ...
    def CalcDeathDir(self, hit_dir): ...
    def CalculateLeanAmount(self, dtime): ...
    def CalculateVelocityYawOffset(self, dtime): ...
    def CallOwner(self, method, *args, **kwargs): ...
    def CancelBeardModelTimer(self): ...
    def CancelStealthSound(self): ...
    def ChangeCastDynamicShadowOnStealth(self): ...
    def ChangeCustomMaterial(self, material_path, **kwargs): ...
    def ChangeCustomMaterialWholeBody(self, material_path, **kwargs): ...
    def ChangeLeftHandWeapon(self): ...
    def ChangeMaterialByRank(self, proto_id, duration, change_enum): ...
    def ChangeMotionState(self, motion_state): ...
    def ChangeShaderGraphMaterial(self, shader_graph_path, layer=-1, inherit=False): ...
    def ChangeShaderGraphMaterialWholeBody(self, material_path, layer=-1, inherit=False): ...
    def ChangeStealthState(self, to_stealth): ...
    def ChangeUpperMotionState(self, upper_motion_state): ...
    def ChangeWeapon(self): ...
    def CheckBodyAttachModel(self): ...
    def CheckCreateAttachModel(self, model_id, is_attach, hardpoint, basepoint, is_execute=False): ...
    def CheckExecuteOnDead(self): ...
    def CheckHeroAttachModel(self): ...
    def CheckHideOnWeaponCaseCreated(self, weapon_case): ...
    def CheckRecreateSkeletonOnReloaded(self, data): ...
    def CheckTrainerForPassive(self, force_check=False): ...
    def CheckVehicleGraph(self): ...
    def CheckWeaponModelValidForFunc(self, weapon_model): ...
    def ClearALLCueCameraEffect(self): ...
    def ClearAllCueEffectCache(self): ...
    def ClearAllCueSoundCache(self): ...
    def ClearAllGraphSyncSlaveReason(self): ...
    def ClearAllSkeletonEffect(self): ...
    def ClearCharctrlHeightReason(self): ...
    def ClearCueEffectCache(self, graph_id, path): ...
    def ClearCueEffectCacheByGraphID(self, graph_id): ...
    def ClearHiddenReason(self): ...
    def ClearMotionBlur(self, elapsedTime, centerU, centerV): ...
    def ClearMoveDirection(self): ...
    def ClearRigidBodies(self): ...
    def ClearSkeletonEffect(self, effect_id): ...
    def ClearSkeletonEffectByEffectId(self, effect_id): ...
    def ClearSkeletonEffectByEffectIdImmediately(self, effect_id): ...
    def ClearSkeletonEffectImmediately(self, effect_id): ...
    def ClearTechParam(self): ...
    def ClearTechState(self): ...
    def ClearWarmingUpHiddenReason(self): ...
    def CreateCharCtrl(self, width, height, physics_info, **kwargs): ...
    def CreateEmoteShowModel(self): ...
    def CreateFilter(self, debug=False): ...
    def CreateFollowerEntity(self): ...
    def CreatePoseSender(self): ...
    def CreateSpecifyBone(self, bone_name): ...
    def CueAddParachute(self): ...
    def CueCanChangeProne(self): ...
    def CueCheckForceOpenParachuteForRobot(self): ...
    def CueExecuteHideModel(self): ...
    def CueExecuteShowModel(self): ...
    def CueHideParachute(self): ...
    def CueLandEnd(self): ...
    def CueOnParachuteActionTo5(self): ...
    def CueOnParachuteReadyLand(self): ...
    def CueOpenParachuteEnd(self): ...
    def CueParachuteEnd(self): ...
    def CuePauseSlidingSound(self): ...
    def CuePulseArrowHide(self): ...
    def CuePulseArrowShow(self): ...
    def CueRecoverSlidingSound(self): ...
    def CueSamuraiBlockEnd(self): ...
    def CueSaveEnd(self): ...
    def CueStartShowEmoteModel(self): ...
    def CueStopShowEmoteModel(self): ...
    def CueTpsFireBomb(self): ...
    def CustomStencilCheck(self, target_stencil, *args): ...
    def DebugChangeSkinWithRepositoryName(self, repository_name, stage='3p'): ...
    def DeleteFilter(self): ...
    def DeletePoseSender(self): ...
    def Destroy(self): ...
    def DestroyBeardModel(self): ...
    def DestroyCppModel(self): ...
    def DestroyFollowerEntity(self): ...
    def DestroyParachuteModel(self): ...
    def DestroyWeapon(self, guid): ...
    def DisableAutoFrameLimit(self): ...
    def DisableClipMaterials(self): ...
    def DisableGraphSyncSlaveWithReason(self, reason): ...
    def DisableInvisibleFrameLimit(self): ...
    def DisableMixMapAsFarAsPossible(self): ...
    def DisableNormalMap(self): ...
    def DisableOutlined(self): ...
    def DisablePrincipleRole(self): ...
    def DisableSignalTypes(self, signal_types): ...
    def DoWeaponOpticShaderRefresh(self): ...
    def DoWeaponPartsAction(self, func_name, *func_args, **kwargs): ...
    def DropCurLeftHandWeapon(self): ...
    def DropCurSpecWeapon(self): ...
    def DropCurWeapon(self, guid=None): ...
    def EnableAutoFrameLimit(self): ...
    def EnableCharCtrlWithReason(self, reason): ...
    def EnableDockingDetector(self, enable=True): ...
    def EnableFilterWithReason(self, reason): ...
    def EnableGraphSyncMaster(self, enable=True): ...
    def EnableGraphSyncSlave(self, enable=True): ...
    def EnableGraphSyncSlaveWithReason(self, reason): ...
    def EnableInvisibleFrameLimit(self, frames): ...
    def EnableIsLookAt(self, isLookAt): ...
    def EnableOutlined(self, color, thickness): ...
    def EnablePoseSender(self, is_enable): ...
    def EnablePoseSenderWithReason(self, reason): ...
    def EnableSelfTrigger(self, enable): ...
    def EnableSignalTypes(self, signal_types): ...
    def ExitState(self, state): ...
    def FilterMotionNotifyCallback(self, motion): ...
    def FireEvent(self, event, gid=-1): ...
    def FireJumpEventForJump(self): ...
    def FireLocomotionEvent(self, event): ...
    def ForceDropLeftHandWeapon(self, old): ...
    def ForceDropWeapon(self, guid): ...
    def ForceLockSpeedForLeaveTrainer(self): ...
    def GetAllPrim(self, need_sorted=False): ...
    def GetBoneLocalPosition(self, bone): ...
    def GetBoneLocalTransform(self, bone): ...
    def GetBoneModelPosition(self, bone): ...
    def GetBoneTransform(self, bone): ...
    def GetBoneWorldPosition(self, bone): ...
    def GetBoneWorldTransform(self, bone): ...
    def GetCurClientLeftHandWeaponCase(self): ...
    def GetCurClientWeaponCase(self): ...
    def GetCurClientWeaponGunType(self): ...
    def GetGraphHandleInGraphStack(self, graph_name): ...
    def GetGraphSyncMode(self): ...
    def GetMotionSkeletonFile(skeleton): ...
    def GetMoveYawDiff(self, x, z): ...
    def GetOwnerSpeed(self): ...
    def GetPrimWorldBound(self): ...
    def GetPrimWorldBoundCentre(self): ...
    def GetPrimWorldBoundCentreWithAttachments(self): ...
    def GetPrimWorldBoundLength(self): ...
    def GetPrimWorldBoundWithAttachments(self): ...
    def GetRunStartDirection(self): ...
    def GetShaderGraphOriginParameter(self, param, layer=-1): ...
    def GetShaderGraphParameter(self, param, layer): ...
    def GetShaderParameter(self, param): ...
    def GetSkeleton(self): ...
    def GetSkeletonDynamicWorldBound(self): ...
    def GetSkeletonDynamicWorldBoundCentre(self): ...
    def GetSkeletonEffectEntities(self, eff_id): ...
    def GetSkeletonEffectEntitiesByEffectId(self, effect_id): ...
    def GetSlideExtraJumpSpeed(self, yaw_diff, is_fall=False): ...
    def GetSlideSpeed(self, normal_speed=None): ...
    def GetStopYawOffset(self): ...
    def GetVariableF(self, varname, gid=-1): ...
    def GetVariableI(self, varname, gid=-1): ...
    def GetVariableS(self, varname, gid=-1): ...
    def GetVariableV3(self, varname, gid=-1): ...
    def GetVariableZ(self, varname, gid=-1): ...
    def GetWeaponCase(self, guid): ...
    def HandIkToWeapon(self, enable=True, hand_type=0): ...
    def HasActorComponent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HaveWarmingUpHiddenReason(self, reason): ...
    def HideAllAttachedNormalModes(self): ...
    def HideHeroAttachModel(self, hide, hide_scabbard, hidden_reason): ...
    def HideTeammateDyingEffect(self): ...
    def IsEnableOutlined(self): ...
    def IsGraphSyncSlave(self): ...
    def IsMoving(self): ...
    def IsPrincipleRole(self): ...
    @property
    def IsVisible(self): ...    def JumpBreak(self): ...
    def JumpEnd(self): ...
    def JumpLand(self): ...
    def JumpToClimb(self): ...
    def JumpToCross(self): ...
    def JumpToDualFire(self, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def JumpToDualFireEnd(self): ...
    def JumpToFire(self, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def JumpToFireEnd(self): ...
    def JumpToIdle(self): ...
    def JumpToMeleeEnd(self): ...
    def JumpToMeleeStart(self, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def JumpToState(self, state, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def JumpToStateCloseParachute(self): ...
    def JumpToStateFreeFall(self): ...
    def JumpToStateLandGround(self): ...
    def JumpToStateOnAircraft(self): ...
    def JumpToStateOpenParachute(self): ...
    def JumpToStateParaFinish(self): ...
    def JumpToStateParachute(self): ...
    def Load(self, data, done=None): ...
    def MakeSureBones(self): ...
    def MarkPrincipleRole(self): ...
    def ModelExpireCallback(self, ientity): ...
    def OnBodyAttachModelDone(self): ...
    def OnCineDisplayPerformer(self, trigger, cueinput): ...
    def OnCineHidePerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformers(self, trigger, cueinput): ...
    def OnCineRenamePerformer(self, trigger, cueinput): ...
    def OnConnectOnVehicle(self): ...
    def OnCrouch(self, crouch): ...
    def OnDead(self, info): ...
    def OnEmoteWeaponModelLoaded(self, weapon_case): ...
    def OnGhost(self): ...
    def OnHit(self, info): ...
    def OnHitSamurai(self, info): ...
    def OnKnockDown(self, is_knock_down): ...
    def OnLoseConnectOnVehicle(self): ...
    def OnModelTick(self, dtime): ...
    def OnPoseTypeChange(self, pose_type): ...
    def OnProne(self, prone, to_stand=True): ...
    def OnPull(self, info): ...
    def OnReborn(self, info): ...
    def OnSaveEnd(self): ...
    def OnSlide(self, slide, to_stand=False): ...
    def OnSpeedLevelChange(self): ...
    def OnVisibleChanged(self, visible): ...
    def OnWeaponPartModelFinishLoad(self, weapon_model): ...
    def OpenParachuteEndForParaModel(self): ...
    def PauseGraph(self, pause, gid=-1): ...
    def PlayAnimation(self, anim_name, single_play=True, remove_motion=True, play_speed=1.0): ...
    def PlayDeadCoinEffect(self, info): ...
    def PlayEffectById(self, effect_id, max_life=-1, scale=1, bone='root', offset=(0, 0, 0), insure_play=False): ...
    def PlayMeleeSkill(self, skill_type=0, info={}): ...
    def PlaySkeletonEffect(self, effect_str, max_life=-1, insure_play=False, effect_id=None): ...
    def PlaySkinDeadAnimAndEffect(self, info): ...
    def PlaySkinDeadEffect(self, sfx_info, material, time_offset, info): ...
    def PopAllSpellGraph(self): ...
    def PopEffectDictByEngineEid(self, engine_eid): ...
    def PopExecuteGraph(self): ...
    def PopGraph(self, graph_id, blendTime=0): ...
    def PopHitGraph(self): ...
    def PopPullGraph(self): ...
    def PopSamuraiHitGraph(self): ...
    def PopSlaveResidualGraph(self): ...
    def PopToIdleGraph(self): ...
    def PopToLocomotionGraph(self): ...
    def PopUpperGraph(self): ...
    def ProcessMaterialRank(self): ...
    def PushGraph(self, graph, transtime=0, ratio=0): ...
    def PushMaterialRankNode(self, rank_id, proto, duration, change_enum): ...
    def PushParaGraph(self): ...
    def PushUpperGraph(self, graph, transtime=0.0): ...
    def RaiseCurLeftHandWeapon(self): ...
    def RaiseCurSpecWeapon(self): ...
    def RaiseCurWeapon(self): ...
    def ReadjustParaGraphId(self): ...
    def ReceiveDynamicShadow(self): ...
    def Refresh(self): ...
    def RefreshAutoFrameLimit(self): ...
    def RefreshForStealthState(self): ...
    def RefreshHandIK(self, hand_left_ik_tps): ...
    def RefreshLocomotionGraphId(self): ...
    def RefreshMaterialForExtraAttachEntity(self): ...
    def RefreshMoveSpeed(self): ...
    def RefreshStealthAttachEffectEntities(self): ...
    def RefreshStealthAttachEntities(self): ...
    def RefreshTeammateTechState(self): ...
    def RefreshTraineeUseFollower(self): ...
    def RefreshWeaponList(self): ...
    def Reload(self, data, done=None, use_ready_to_appear=True): ...
    def ReloadPrimitives(self, data, use_ready_to_appear=True): ...
    def ReloadSkeleton(self, data): ...
    def ReloadWeaponStop(self): ...
    def RemoveCharctrlHeightReason(self, reason): ...
    def RemoveFollower(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveLoadTask(self, name): ...
    def RemoveStealthAttachEffectEntity(self, effect_entity): ...
    def RemoveStealthAttachEntity(self, entity): ...
    def RemoveTechState(self, proto_id): ...
    def RemoveTechStateWholeBody(self, proto_id): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def RemoveXRayBlock(self): ...
    def ReplaceGraph(self, graph_id, graph): ...
    def RescueOtherFinish(self): ...
    def ResetCustomMaterial(self): ...
    def ResetCustomMaterialWholeBody(self): ...
    def ResetHairPrim(self): ...
    def ResetLocomotionGraphID(self): ...
    def ResetLocomotionGraphParam(self): ...
    def ResetMaterialByRank(self, proto_id): ...
    def ResetPosResult(self): ...
    def ResetShaderGraphMaterial(self, layer=-1): ...
    def ResetShaderGraphMaterialWholeBody(self): ...
    def ResetShaderGraphParameter(self, param, layer=-1): ...
    def ResetShaderGraphParameters(self, layer=-1): ...
    def ResetShaderParameter(self, param): ...
    def ResetYawForFolloweeModel(self): ...
    def ResizeCharCtrlFpsModeRadius(self, is_fps_mode): ...
    def ResizeCharCtrlPoseHeight(self, pose_type): ...
    def ResizeCharctrHeightForReason(self, reason): ...
    def RestoreTechStateParamWholeBody(self): ...
    def SelectIdleGraph(self, value): ...
    def SetAsCSMRole(self, is_role): ...
    def SetCanDocking(self, is_can): ...
    def SetCharCtrlProne(self, enable): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetEnableRideVelocity(self, enable): ...
    def SetEnableSlope(self, enable): ...
    def SetEnableVisibilityOptimize(self, enable): ...
    def SetFilterInputInterval(self, value): ...
    def SetFresnelShowPercent(self, percent): ...
    def SetGraphDynamicAnim(self): ...
    def SetGraphPitch(self, value): ...
    def SetGraphYawHalfLife(self, halflife): ...
    def SetHipDirection(self, x, z): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsDualWeapon(self, is_dual): ...
    def SetIsOpenFire(self, is_open): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetLocomotionCycleDir(self): ...
    def SetLodDistance(self, layer, distance): ...
    def SetLodDistanceAllLayers(self, distances): ...
    def SetMoveSpeed(self, speed): ...
    def SetNoNearPlaneClip(self, enable): ...
    def SetOnAircraftPose(self, pose): ...
    def SetOpenFireAction(self, open_fire_action): ...
    def SetOutlinedParam(self, color, thickness): ...
    def SetParachuteModelRenderSet(self, render_set): ...
    def SetParachuteModelVisible(self, visible): ...
    def SetPitchAndYaw(self, pitch, yaw): ...
    def SetPoseSenderInterval(self, value): ...
    def SetShaderGraphParameter(self, param, value, layer=-1): ...
    def SetShaderGraphParameterRecursively(self, param, value, layer=-1): ...
    def SetShaderGraphParameterWholeBody(self, param, value, layer=-1): ...
    def SetShaderParameter(self, param, value, **kwargs): ...
    def SetShaderParameterRecursively(self, param, value): ...
    def SetShaderParameterWholeBody(self, param, value, **kwargs): ...
    def SetSkeletonEffectVisible(self, visible): ...
    def SetSkeletonEffectVisibleForEffectId(self, effect_id, visible): ...
    def SetStealthPercent(self, percent, interval=0.02): ...
    def SetTechState(self): ...
    def SetTechStateCustomParam(self, proto_id, custom_param): ...
    def SetTechStateParam(self, tech_id, custom_param): ...
    def SetTransformWithAttachmentsImmediately(self, transform): ...
    def SetUpperGraphCommonParam(self): ...
    def SetVariableF(self, varname, varvalue, gid=-1): ...
    def SetVariableI(self, varname, varvalue, gid=-1): ...
    def SetVariableS(self, varname, varvalue, gid=-1): ...
    def SetVariableV3(self, varname, varvalue, gid=-1): ...
    def SetVariableZ(self, varname, varvalue, gid=-1): ...
    def SetWarmingUp(self, value): ...
    def SetWarmingUpAppearImmediately(self, value): ...
    def ShiftGraph(self, gid, offset): ...
    def ShowBodyAttachModel(self, show, hidden_reason): ...
    def ShowTeammateDyingEffect(self): ...
    def SignalNotifyCallback(self, trigger, stype, signalStr): ...
    def SkeletonExpireCallback(self, skeleton): ...
    def SlidingEnd(self): ...
    def SlidingToLocomotion(self): ...
    def StartRescueOther(self, rescue): ...
    def StopAnimation(self, anim_name): ...
    def StropEnd(self): ...
    def Towards(self, x, z, speed=None): ...
    def UnableCharCtrlWithReason(self, reason): ...
    def UnableFilterWithReason(self, reason): ...
    def UnablePoseSenderWithReason(self, reason): ...
    def UnlockSpeedForTrainerPara(self): ...
    def UpdateSlideMoveVec(self): ...
    def UseDistancedEnemyTechState(self, param, param2): ...
    def UseTechEdgeLine(self, color, thickness): ...
    def UseTechFrozen(self): ...
    def UseTechHighLightXray(self, param, param2, color2): ...
    def UseTechHighlight(self, color, frequency=0.0): ...
    def UseTechXray(self, color2=None, param2=None): ...
    def _CancelUnlockTrainerSpeedTimer(self): ...
    def _CheckCanDocking(self): ...
    def _CheckCharctrlSizeForReason(self): ...
    def _CheckDropClientWeapon(self): ...
    def _CheckPopNeedYawGraphId(self): ...
    def _CheckSameTachStatus(self, parent, basepoint, hardpoint): ...
    def _CreateParaChangeUtil(self): ...
    def _DoChangeMaterialForTargetEntity(self, entity): ...
    def _DoCheckWeaponFuncAndExec(self, model, func_name, *args): ...
    def _DoSetFresnelParam(self, percent): ...
    def _DoSetTransparencyParam(self, value): ...
    def _EnablePopToLocomotionGraph(self): ...
    def _EnableSelfTriggerImp(self, p, enable): ...
    def _ExecuteAndCheckHideAction(self, model, func_name, *func_args): ...
    def _GetAvailableModelInfo(self, model_data): ...
    def _GetOwnerHeroId(self): ...
    def _GetOwnerSpeed(self, owner, speed_level, move_dir): ...
    def _GetTpsParaGraphFile(self): ...
    def _OnExit_Emote(self): ...
    def _OnJumpTo_BeExecuted(self, info): ...
    def _OnJumpTo_ClimbLadder(self, info): ...
    def _OnJumpTo_Crouch(self, info): ...
    def _OnJumpTo_Dead(self, info): ...
    def _OnJumpTo_Emote(self, info): ...
    def _OnJumpTo_EnterProne(self, info): ...
    def _OnJumpTo_Execution(self, info): ...
    def _OnJumpTo_ExitProne(self, info): ...
    def _OnJumpTo_Idle(self, info): ...
    def _OnJumpTo_Jump(self, info): ...
    def _OnJumpTo_KnockDown(self, info): ...
    def _OnJumpTo_PickUp(self, info): ...
    def _OnJumpTo_Prone(self, info): ...
    def _OnJumpTo_RaiseWeapon(self, info): ...
    def _OnJumpTo_Reload(self, info): ...
    def _OnJumpTo_RescueOther(self, info): ...
    def _OnJumpTo_Spell(self, info): ...
    def _OnJumpTo_Stand(self, info): ...
    def _ProcessCueEnd(self, prev, trigger): ...
    def _SetGraphYaw(self, yaw): ...
    def _SetModelPoseType(self, pose_type): ...
    def _SetVisible(self, visible): ...
    def _TickBeardVisibility(self): ...
    def _TickFollowerYawToSelf(self, dt=None): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, interval, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    @property
    def client_weapon_case(self): ...    def cue_signal_attach_normal_model(self, trigger, signal_str): ...
    def cue_signal_auto_pop_graph(self, trigger, signal_str): ...
    def cue_signal_auto_push_graph(self, trigger, signal_str): ...
    def cue_signal_creep_stand_ok(self, trigger, signal_str): ...
    def cue_signal_effect_attach_detach(self, trigger, signal_str): ...
    def cue_signal_event(self, trigger, signal_str): ...
    def cue_signal_execute_third_model(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate_enable(self, trigger, signal_str): ...
    def cue_signal_gun_sfx(self, trigger, signal_str): ...
    def cue_signal_gunfire_sound_event(self, trigger, signal_str): ...
    def cue_signal_motion_blur_to_percent(self, trigger, signal_str): ...
    def cue_signal_player_event(self, trigger, signal_str): ...
    def cue_signal_reload_ammo(self, trigger, signal_str): ...
    def cue_signal_replay_robot_event(self, trigger, signal_str): ...
    def cue_signal_sound_break(self, trigger, signal_str): ...
    def cue_signal_sound_event(self, trigger, signal_str): ...
    def cue_signal_sound_far_event(self, trigger, signal_str): ...
    def cue_signal_spell_event(self, trigger, signal_str): ...
    def cue_signal_variable_event_sync_stack(self, trigger, signal_str): ...
    def cue_type_node_transition_excute(self, trigger, curinput): ...
    @property
    def gun_type(self): ...    def isModelOnlyValid(self): ...
    def isValid(self): ...
    @property
    def is_destroyed(self): ...    @property
    def is_loaded(self): ...    def onCineDismissPerformer(self, trigger, cueinput): ...
    def onCineDismissPerformers(self, trigger, cueinput): ...
    def onCineDisplayCaption(self, trigger, cueinput): ...
    def onLoaded(self): ...
    @property
    def poseSender(self): ...    @property
    def pose_type(self): ...    @property
    def position(self): ...    @property
    def scale(self): ...    @property
    def skeleton(self): ...    @property
    def space(self): ...    @property
    def tps_idle_graph(self): ...    @property
    def tps_idle_slave_graph(self): ...    @property
    def weapon_case(self): ...    @property
    def yaw(self): ...
class RobotAvatarModelCue(AvatarModelCue):
    def BindBoneColliderCallFunc(self, result): ...
    def BindEventSignalNotify(self): ...
    def ClearALLCueCameraEffect(self): ...
    def ClearAllCueEffectCache(self): ...
    def ClearAllCueSoundCache(self): ...
    def ClearCueEffectCache(self, graph_id, path): ...
    def ClearCueEffectCacheByGraphID(self, graph_id): ...
    def ClearMotionBlur(self, elapsedTime, centerU, centerV): ...
    def CueAddParachute(self): ...
    def CueCanChangeProne(self): ...
    def CueCheckForceOpenParachuteForRobot(self): ...
    def CueExecuteHideModel(self): ...
    def CueExecuteShowModel(self): ...
    def CueHideParachute(self): ...
    def CueLandEnd(self): ...
    def CueOnParachuteActionTo5(self): ...
    def CueOnParachuteReadyLand(self): ...
    def CueOpenParachuteEnd(self): ...
    def CueParachuteEnd(self): ...
    def CuePauseSlidingSound(self): ...
    def CuePulseArrowHide(self): ...
    def CuePulseArrowShow(self): ...
    def CueRecoverSlidingSound(self): ...
    def CueSaveEnd(self): ...
    def CueTpsFireBomb(self): ...
    def JumpEnd(self): ...
    def JumpToClimb(self): ...
    def JumpToCross(self): ...
    def OnCineDisplayPerformer(self, trigger, cueinput): ...
    def OnCineHidePerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformers(self, trigger, cueinput): ...
    def OnCineRenamePerformer(self, trigger, cueinput): ...
    def SignalNotifyCallback(self, trigger, stype, signalStr): ...
    def SlidingEnd(self): ...
    def SlidingToLocomotion(self): ...
    def StropEnd(self): ...
    def _ProcessCueEnd(self, prev, trigger): ...
    def cue_signal_attach_normal_model(self, trigger, signal_str): ...
    def cue_signal_auto_pop_graph(self, trigger, signal_str): ...
    def cue_signal_auto_push_graph(self, trigger, signal_str): ...
    def cue_signal_creep_stand_ok(self, trigger, signal_str): ...
    def cue_signal_effect_attach_detach(self, trigger, signal_str): ...
    def cue_signal_event(self, trigger, signal_str): ...
    def cue_signal_execute_third_model(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate_enable(self, trigger, signal_str): ...
    def cue_signal_gun_sfx(self, trigger, signal_str): ...
    def cue_signal_gunfire_sound_event(self, trigger, signal_str): ...
    def cue_signal_motion_blur_to_percent(self, trigger, signal_str): ...
    def cue_signal_player_event(self, trigger, signal_str): ...
    def cue_signal_reload_ammo(self, trigger, signal_str): ...
    def cue_signal_replay_robot_event(self, trigger, signal_str): ...
    def cue_signal_sound_break(self, trigger, signal_str): ...
    def cue_signal_sound_event(self, trigger, signal_str): ...
    def cue_signal_sound_far_event(self, trigger, signal_str): ...
    def cue_signal_spell_event(self, trigger, signal_str): ...
    def cue_signal_variable_event_sync_stack(self, trigger, signal_str): ...
    def cue_type_node_transition_excute(self, trigger, curinput): ...
    def onCineDismissPerformer(self, trigger, cueinput): ...
    def onCineDismissPerformers(self, trigger, cueinput): ...
    def onCineDisplayCaption(self, trigger, cueinput): ...

class StoryTick(object):
    _instance: StoryTick = <gclient.framework.util.story_tick.StoryTick object at 0x7005e37fd0>

    def Add(self, func, frames=0): ...
    def Remove(self, func): ...
    def doAdd(self, func, frames): ...
    def doRemove(self, func): ...
    def onTick(self, _, dtime): ...


def Components(*components, **kwargs): ...
def CueCallbackDef(cls_name, cue_type, is_charedit=False): ...
def CueEndCallbackDef(cls_name, cue_type): ...
def RegisterModelClass(cls): ...

