# module: gclient.gameplay.logic_base.models.robot_hand_model

import cconst
import consts
import functools

class ReplayHandModel(SimpleModel):
    NAME: str = 'ReadyToLand'
    logger: Logger = <Logger Model (DEBUG)>

    def ActionEndToIdle(self): ...
    def ActionEndToRechamber(self): ...
    def AddAttachEntityForMaterialChange(self, entity, is_add): ...
    def AddHandPrimitives(self, hand_model_id): ...
    def AddHiddenReason(self, reason): ...
    def AddLoadTask(self, name): ...
    def AddParachuteModel(self): ...
    def AddStealthAttachEffectEntity(self, effect_entity): ...
    def AddStealthAttachEntity(self, entity): ...
    def AddTargetSlot(self, slot_name, actor): ...
    def AddTechState(self, id, custom_param=None): ...
    def AddTechStateWholeBody(self, proto_id, custom_param=None): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def AddWeapon(self, guid): ...
    def AddWeaponPart(self, weapon_guid, part_id): ...
    def ApplyCustomStencil(self, custom_stencil, is_check=False): ...
    def AttachToAvatar(self): ...
    def AttachToParent(self, entity, basepoint, hardpoint): ...
    def BanHandIKToWeapon(self, is_ban, ban_type): ...
    def BatchResetShaderGraphParameter(self, params, layer=-1): ...
    def BatchSetShaderGraphParameter(self, params, values, layer=-1): ...
    def BindBoneColliderCallFunc(self, result): ...
    def BindEventSignalNotify(self): ...
    def CallOwner(self, method, *args, **kwargs): ...
    def CancelDelayFireTimer(self): ...
    def CancelExitProne(self): ...
    def CancelStealthSound(self): ...
    def ChangeActionState(self, state): ...
    def ChangeCastDynamicShadowOnStealth(self): ...
    def ChangeCustomMaterial(self, material_path, **kwargs): ...
    def ChangeCustomMaterialWholeBody(self, material_path, **kwargs): ...
    def ChangeLeftHandWeapon(self): ...
    def ChangeMoveState(self, state): ...
    def ChangeParaState(self, state, is_force_change=False): ...
    def ChangeShaderGraphMaterial(self, shader_graph_path, layer=-1, inherit=False): ...
    def ChangeShaderGraphMaterialWholeBody(self, material_path, layer=-1, inherit=False): ...
    def ChangeStealthState(self, to_stealth): ...
    def ChangeWeapon(self): ...
    def CheckCreateAttachModel(self, model_id, is_attach, hardpoint, basepoint): ...
    def CheckExtraAttachModel(self): ...
    def CheckLadderGraphOnActionGraph(self): ...
    def CheckNeedWarmUpAnimations(self, res_tag): ...
    def CheckRecreateSkeletonOnReloaded(self, data): ...
    def CheckWeaponModelValidForFunc(self, weapon_model): ...
    def ClearALLCueCameraEffect(self): ...
    def ClearAllAnimEffect(self, _): ...
    def ClearAllCueEffectCache(self): ...
    def ClearAllCueSoundCache(self): ...
    def ClearAllCurItemCaseAnimEffect(self, _): ...
    def ClearAllMeleeAnimEffect(self, _): ...
    def ClearAllSkeletonEffect(self): ...
    def ClearCueEffectCache(self, graph_id, path): ...
    def ClearCueEffectCacheByGraphID(self, graph_id): ...
    def ClearHiddenReason(self): ...
    def ClearMotionBlur(self, elapsedTime, centerU, centerV): ...
    def ClearRigidBodies(self): ...
    def ClearSkeletonEffect(self, effect_id): ...
    def ClearSkeletonEffectByEffectId(self, effect_id): ...
    def ClearSkeletonEffectByEffectIdImmediately(self, effect_id): ...
    def ClearSkeletonEffectImmediately(self, effect_id): ...
    def ClearTechParam(self): ...
    def ClearTechState(self): ...
    def ClearWarmingUpHiddenReason(self): ...
    def ClimbLadderUpEnd(self): ...
    def ClimbLadderUpStart(self): ...
    def CommonOverlayActionEnd(self, pop_time=0.2): ...
    def CreateSpecifyBone(self, bone_name): ...
    def CueAddInspectExtraModel(self): ...
    def CueAttachWeaponToHandBack(self): ...
    def CueChangeTPSIsStub(self): ...
    def CueForceScaleTransform(self): ...
    def CueFpsSlidingEnd(self): ...
    def CueFpsSlidingOver(self): ...
    def CueFpsSlidingStart(self): ...
    def CueHideWeapon(self): ...
    def CueInspectAnimEnd(self): ...
    def CueInspectAnimStart(self): ...
    def CueInspectHideDoubleWeapon(self): ...
    def CueInspectShowDoubleWeapon(self): ...
    def CueInspectionOver(self): ...
    def CueLoadReloadTwinWeaponCase(self): ...
    def CueMinigunFireIntervalChanged(self): ...
    def CuePlayMeleeAttackEffect(self): ...
    def CuePulseArrowHide(self): ...
    def CuePulseArrowShow(self): ...
    def CueRaiseOver(self): ...
    def CueReloadAnimEnd(self): ...
    def CueReloadAnimStart(self): ...
    def CueReloadSwitchTwinWeapon(self): ...
    def CueRemoveInspectModel(self): ...
    def CueShowWeapon(self): ...
    def CueSkinAttachArmour(self): ...
    def CueSkinDetachArmour(self): ...
    def CueSkinReplaceHandModel(self): ...
    def CueSkinRevertHandModel(self): ...
    def CueSlidingDone(self): ...
    def CueStartScaleTransform(self): ...
    def CueSwitchReloadTwinWeaponCase(self): ...
    def CueWeaponEmiPowerClose(self): ...
    def CueWeaponEmiPowerOpen(self): ...
    def CustomStencilCheck(self, target_stencil, *args): ...
    def DelayBanUseWeapon(self): ...
    def Destroy(self): ...
    def DestroyCppModel(self): ...
    def DestroyParachuteModel(self): ...
    def DestroyWeapon(self, guid, force_destroy=False): ...
    def DisableMixMapAsFarAsPossible(self): ...
    def DisableNormalMap(self): ...
    def DisableOutlined(self): ...
    def DisablePrincipleRole(self): ...
    def DoWeaponOpticShaderRefresh(self): ...
    def DoWeaponPartsAction(self, func_name, *func_args, **kwargs): ...
    def DropCurLeftHandWeapon(self): ...
    def DropCurSpecWeapon(self): ...
    def DropCurWeapon(self): ...
    def DropCurWeaponWithOutAnim(self): ...
    def DualActionEndToIdle(self): ...
    def EnableHandIKToWeapon(self, enable=True, hand_bone='WL', gun_bone='HP_Hand_Left_IK'): ...
    def EnableOutlined(self, color, thickness): ...
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...
    def FinishParachuteGraph(self): ...
    def FireEvent(self, event, gid=-1): ...
    def ForceDropWeapon(self, guid): ...
    def GetAllPrim(self, need_sorted=False): ...
    def GetBackItem(self): ...
    def GetBoneLocalPosition(self, bone): ...
    def GetBoneLocalTransform(self, bone): ...
    def GetBoneModelPosition(self, bone): ...
    def GetBoneTransform(self, bone): ...
    def GetBoneWorldPosition(self, bone): ...
    def GetBoneWorldTransform(self, bone): ...
    def GetCanForceOpenParachute(self): ...
    def GetCurClientLeftHandWeaponCase(self): ...
    def GetCurClientWeaponCase(self): ...
    def GetGraphHandleInGraphStack(self, graph_name): ...
    def GetMotionSkeletonFile(skeleton): ...
    def GetPrimWorldBound(self): ...
    def GetPrimWorldBoundCentre(self): ...
    def GetPrimWorldBoundCentreWithAttachments(self): ...
    def GetPrimWorldBoundLength(self): ...
    def GetPrimWorldBoundWithAttachments(self): ...
    def GetShaderGraphOriginParameter(self, param, layer=-1): ...
    def GetShaderGraphParameter(self, param, layer): ...
    def GetShaderParameter(self, param): ...
    def GetSkeleton(self): ...
    def GetSkeletonDynamicWorldBound(self): ...
    def GetSkeletonDynamicWorldBoundCentre(self): ...
    def GetSkeletonEffectEntities(self, eff_id): ...
    def GetSkeletonEffectEntitiesByEffectId(self, effect_id): ...
    def GetVariableF(self, varname, gid=-1): ...
    def GetVariableI(self, varname, gid=-1): ...
    def GetVariableS(self, varname, gid=-1): ...
    def GetVariableV3(self, varname, gid=-1): ...
    def GetVariableZ(self, varname, gid=-1): ...
    def GetWeaponCase(self, guid): ...
    def GetWeaponCaseByWeaponId(self, weapon_id): ...
    def HandIkToWeapon(self, enable=True, hand_bone='WL', gun_bone='HP_Hand_Left_IK'): ...
    def HasActorComponent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HaveWarmingUpHiddenReason(self, reason): ...
    def HideAllAttachedNormalModes(self): ...
    def HideTeammateDyingEffect(self): ...
    def HideTwinWeaponCase(self): ...
    def HitShakeDone(self): ...
    def InjectEnd(self): ...
    def InspectionWeaponEnd(self): ...
    def InspectionWeaponStart(self): ...
    def IsEnableOutlined(self): ...
    def IsForceUnableLeftHandIK(self): ...
    def IsPrincipleRole(self): ...
    @property
    def IsVisible(self): ...    def JumpFall(self): ...
    def JumpLand(self): ...
    def JumpToAds(self, is_ads): ...
    def JumpToDualFireEnd(self): ...
    def JumpToDualFireStart(self, is_auto_fire=True): ...
    def JumpToFireEnd(self): ...
    def JumpToFireStart(self, is_auto_fire=True): ...
    def JumpToMeleeEnd(self): ...
    def JumpToMeleeStart(self, *args, **kwargs): ...
    def JumpToSkillEnd(self): ...
    def JumpToSkillHold(self): ...
    def JumpToSkillToss(self): ...
    def JumpToSkillToss2(self): ...
    def JumpToSkillTossSecondary(self): ...
    def JumpToState(self, state, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def JumpToSwitchToss(self): ...
    def JumpToThrowBomb(self, spell_id): ...
    def Load(self, data, done=None, **create_kwargs): ...
    def MakeSureBones(self): ...
    def MakeSureHandModelWeaponAdsStateRight(self): ...
    def MakeSureParaEndParachute(self): ...
    def MarkPrincipleRole(self): ...
    def ModelExpireCallback(self, ientity): ...
    def OnCineDisplayPerformer(self, trigger, cueinput): ...
    def OnCineHidePerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformers(self, trigger, cueinput): ...
    def OnCineRenamePerformer(self, trigger, cueinput): ...
    def OnCloseParachuteEnter(self): ...
    def OnDead(self): ...
    def OnDoubleWeaponCaseLoadDone(self, _): ...
    def OnExitSwim(self): ...
    def OnExtraAttachModelDone(self): ...
    def OnExtraAttachToss(self, event_name=None): ...
    def OnFinishEnter(self): ...
    def OnFreeFallEnter(self): ...
    def OnFreeFallOpenFireEnter(self): ...
    def OnFreeFallOpenFireExit(self): ...
    def OnGhost(self): ...
    def OnHandModelLoad(self): ...
    def OnHandModelLoadedForCamera(self): ...
    def OnHandModelReload(self): ...
    def OnHit(self, info): ...
    def OnLandGroundEnter(self): ...
    def OnLeftHandAdditive(self, is_add): ...
    def OnOnAircraftEnter(self): ...
    def OnOpenParachuteEnter(self): ...
    def OnParachuteEnter(self): ...
    def OnPulseEndForNextSpell(self, use_next): ...
    def OnReadyForNextPulseSpell(self): ...
    def OnReadyToLandEnter(self): ...
    def OnReborn(self): ...
    def OnReloadWeaponCaseLoadDone(self, weapon_case): ...
    def OnReplaceHandLoaded(self): ...
    def OnRevertHandLoaded(self): ...
    def OnScoutArrowSkillReadyForWeaponCase(self, is_pulse): ...
    def OnSlideEnd(self, break_slide): ...
    def OnSpeedLevelChange(self): ...
    def OnStopHoldCurSpecWeapon(self): ...
    def OnUseSkill(self): ...
    def OnVisibleChanged(self, visible): ...
    def OnWeaponPartModelFinishLoad(self, weapon_model): ...
    def PauseGraph(self, pause, gid=-1): ...
    def PinAnimations(self, res_tag, resources): ...
    def PinGraphs(self, res_tag, resources): ...
    def PinResource(self, res_tag, res_name): ...
    def PinWeaponGraph(self, graph): ...
    def PlayAnimation(self, anim_name, single_play=True, remove_motion=True, play_speed=1.0): ...
    def PlayCurItemCaseAnimEffect(self, signal_str): ...
    def PlayEffectById(self, effect_id, max_life=-1, scale=1, bone='root', offset=(0, 0, 0), insure_play=False): ...
    def PlayGunAnimEffect(self, signal_str): ...
    def PlayGunFireEffect(self, signal_str, effect_key): ...
    def PlayHandAnimEffect(self, signal_str): ...
    def PlayHeroSkinHandEffect(self): ...
    def PlayMeleeAnimEffect(self, signal_str): ...
    def PlayMeleeSkill(self, skill_type=0, info={}): ...
    def PlaySkeletonEffect(self, effect_str, max_life=5.0, insure_play=False, effect_id=None): ...
    def PopActionGraph(self): ...
    def PopEffectDictByEngineEid(self, engine_eid): ...
    def PopGraph(self, graph_id, blendTime=0): ...
    def PopOverlayActionGraph(self, blendtime=0.0): ...
    def PopParaGraph(self): ...
    def PopSpellGraph(self): ...
    def PrintAnimations(self): ...
    def PrintGraphs(self): ...
    def PrintSkeletonData(self): ...
    def PushActionGraph(self, graph, blendTime=0): ...
    def PushGraph(self, graph, transtime=0, ratio=0): ...
    def PushOverlayActionGraph(self, graph, blendTime=0): ...
    def PushParaGraph(self): ...
    def PushPlates(self, is_end): ...
    def PushPoseGraph(self): ...
    def PushSpellGraph(self, graph, blendTime=0): ...
    def RaiseCurLeftHandWeapon(self): ...
    def RaiseCurSpecWeapon(self): ...
    def RaiseCurUseWeapon(self): ...
    def RaiseCurWeapon(self): ...
    def ReceiveDynamicShadow(self): ...
    def Refresh(self): ...
    def RefreshAfterPushActionGraph(self): ...
    def RefreshAllWeaponDecorates(self): ...
    def RefreshAnimationDetail(self): ...
    def RefreshBarrelPose(self): ...
    def RefreshCurStatus(self): ...
    def RefreshDrumPose(self): ...
    def RefreshExtraAttachModelState(self): ...
    def RefreshForStealthState(self): ...
    def RefreshGuiseSkinAnimPoseForHandPoseGraph(self, guise_template_data): ...
    def RefreshHandGunType(self, gun_type): ...
    def RefreshIsNeedRechamber(self, is_need): ...
    def RefreshIsReloadAllBullet(self): ...
    def RefreshMaterialForExtraAttachEntity(self): ...
    def RefreshMoveActionSpeed(self, speed): ...
    def RefreshMoveInAnim(self): ...
    def RefreshOpticPose(self): ...
    def RefreshReloadMode(self): ...
    def RefreshStatusByKey(self, key): ...
    def RefreshStealthAttachEffectEntities(self): ...
    def RefreshStealthAttachEntities(self): ...
    def RefreshStockPose(self): ...
    def RefreshTeammateTechState(self): ...
    def RefreshUnderbarrelPose(self): ...
    def RefreshWeaponCaseOptic(self): ...
    def RefreshWeaponList(self): ...
    def RefreshWeaponState(self): ...
    def Reload(self, data, done=None, use_ready_to_appear=True): ...
    def ReloadDualWeaponStart(self): ...
    def ReloadDualWeaponStop(self): ...
    def ReloadPrimitives(self, data, use_ready_to_appear=True): ...
    def ReloadSkeleton(self, data): ...
    def ReloadWeaponStop(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveLoadTask(self, name): ...
    def RemoveStealthAttachEffectEntity(self, effect_entity): ...
    def RemoveStealthAttachEntity(self, entity): ...
    def RemoveTechState(self, proto_id): ...
    def RemoveTechStateWholeBody(self, proto_id): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def RemoveXRayBlock(self): ...
    def ReplaceGraph(self, graph_id, graph): ...
    def ResetCustomMaterial(self): ...
    def ResetCustomMaterialWholeBody(self): ...
    def ResetHairPrim(self): ...
    def ResetShaderGraphMaterial(self, layer=-1): ...
    def ResetShaderGraphMaterialWholeBody(self): ...
    def ResetShaderGraphParameter(self, param, layer=-1): ...
    def ResetShaderGraphParameters(self, layer=-1): ...
    def ResetShaderParameter(self, param): ...
    def ResetStatus(self): ...
    def RestoreStateByParaStage(self): ...
    def RestoreTechStateParamWholeBody(self): ...
    def SetAsCSMRole(self, is_role): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetDualIsEmptyReload(self, is_empty): ...
    def SetDualMpFpsAction(self, action, blendTime): ...
    def SetEnableVisibilityOptimize(self, enable): ...
    def SetFreefallFallAction(self, skydive_action): ...
    def SetFresnelShowPercent(self, percent): ...
    def SetGraphAnimIn(self, state, is_need_transition): ...
    def SetGraphDynamicAnim(self, equip_id): ...
    def SetGraphModelSkin(self): ...
    def SetGraphMoveStartTime(self): ...
    def SetGraphMoveType(self, move_type): ...
    def SetIsAds(self, is_ads): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsDualEmptyAmmo(self, is_empty): ...
    def SetIsDualWeapon(self, is_dual): ...
    def SetIsEmptyAmmo(self, is_empty): ...
    def SetIsEmptyReload(self, is_empty): ...
    def SetIsFastRaise(self, is_fast_raise): ...
    def SetIsFirstRaiseWeapon(self, is_first_raise): ...
    def SetIsHighFallAir(self, is_high_fall): ...
    def SetIsLinkageRaise(self, is_linkage): ...
    def SetIsMeleeFirstRaiseWeapon(self, is_melee_first_raise): ...
    def SetIsOpenFire(self, is_open): ...
    def SetIsRealAds(self, is_real_ads): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetJumpAirHeight(self, height): ...
    def SetLadderGraphDirection(self, direction): ...
    def SetLodDistance(self, layer, distance): ...
    def SetLodDistanceAllLayers(self, distances): ...
    def SetMoveDirection(self, move_direction): ...
    def SetMoveStartTime(self, move_action_time): ...
    def SetMpFpsAction(self, action, blendTime): ...
    def SetNoNearPlaneClip(self, enable): ...
    def SetOutlinedParam(self, color, thickness): ...
    def SetParachuteFallActionByJoystick(self, x, y): ...
    def SetParachuteNearGroundAction(self, is_near_ground): ...
    def SetPitchAndYaw(self, pitch, yaw): ...
    def SetPoseAnimDynamicSpeed(self, equip_id): ...
    def SetPoseType(self, pose_type): ...
    def SetRunShootDelayTime(self, delay_time): ...
    def SetShaderGraphParameter(self, param, value, layer=-1): ...
    def SetShaderGraphParameterRecursively(self, param, value, layer=-1): ...
    def SetShaderGraphParameterWholeBody(self, param, value, layer=-1): ...
    def SetShaderParameter(self, param, value, **kwargs): ...
    def SetShaderParameterRecursively(self, param, value): ...
    def SetShaderParameterWholeBody(self, param, value, **kwargs): ...
    def SetSkeletonEffectVisible(self, visible): ...
    def SetSkeletonEffectVisibleForEffectId(self, effect_id, visible): ...
    def SetSkinActionAnim(self, anim_key, anim_name): ...
    def SetSkinPoseAnim(self, anim_key, anim_name): ...
    def SetStealthPercent(self, percent, interval=0.02): ...
    def SetSwitchWeaponDuration(self, raise_speed, drop_speed): ...
    def SetTechState(self): ...
    def SetTechStateCustomParam(self, proto_id, custom_param): ...
    def SetTechStateParam(self, tech_id, custom_param): ...
    def SetTransformWithAttachmentsImmediately(self, transform): ...
    def SetVariableF(self, varname, varvalue, gid=-1): ...
    def SetVariableI(self, varname, varvalue, gid=-1): ...
    def SetVariableS(self, varname, varvalue, gid=-1): ...
    def SetVariableV3(self, varname, varvalue, gid=-1): ...
    def SetVariableZ(self, varname, varvalue, gid=-1): ...
    def SetWarmingUp(self, value): ...
    def SetWarmingUpAppearImmediately(self, value): ...
    def ShiftGraph(self, gid, offset): ...
    def ShowParachuteModel(self, is_show): ...
    def ShowTeammateDyingEffect(self): ...
    def SignalNotifyCallback(self, trigger, stype, signalStr): ...
    def SkeletonExpireCallback(self, skeleton): ...
    def SlideToDone(self): ...
    def SlideToEnd(self): ...
    def StartToFinishParachuteGraph(self): ...
    def StopAnimation(self, anim_name): ...
    def UnpinAllAnimations(self): ...
    def UnpinAllGraphs(self): ...
    def UnpinAllSkeletons(self): ...
    def UnpinResource(self, res_tag, res_name): ...
    def UnpinResourcesByTag(self, res_tag): ...
    def UnpinResourcesByType(self, res_type): ...
    def UnpinWeaponAnimations(self, weapon_id): ...
    def UnpinWeaponGraph(self): ...
    def UseDistancedEnemyTechState(self, param, param2): ...
    def UseTechEdgeLine(self, color, thickness): ...
    def UseTechFrozen(self): ...
    def UseTechHighLightXray(self, param, param2, color2): ...
    def UseTechHighlight(self, color, frequency=0.0): ...
    def UseTechXray(self, color2=None, param2=None): ...
    def WarmUpAndPinResources(self, resources, callback=None): ...
    def WarmUpAnimations(self, resources, callback=None): ...
    def WarmUpGraphs(self, resources, callback=None): ...
    def WarmUpResources(self, resources, callback=None): ...
    def WarmUpWeaponAnimations(self, weapon_id, callback=None): ...
    def _ChangeParaGraphStack(self, change): ...
    def _CheckDropClientLeftHandWeapon(self): ...
    def _CheckDropClientWeapon(self): ...
    def _CheckSameTachStatus(self, parent, basepoint, hardpoint): ...
    def _CheckUnpinResources(self): ...
    def _CreateParaChangeUtil(self): ...
    def _DoChangeMaterialForTargetEntity(self, entity): ...
    def _DoCheckWeaponFuncAndExec(self, model, func_name, *args): ...
    def _DoSetFresnelParam(self, percent): ...
    def _DoSetTransparencyParam(self, value): ...
    def _ExecuteAndCheckHideAction(self, model, func_name, *func_args): ...
    def _GetAnimPathPrefix(self): ...
    def _GetAvailableModelInfo(self, model_data): ...
    def _GetFpsParaGraphFile(self): ...
    def _GetResType(self, res_name): ...
    def _InspectAnimTick(self): ...
    def _OnJumpTo_Climb(self, info): ...
    def _OnJumpTo_ClimbLadder(self, info): ...
    def _OnJumpTo_Cross(self, info): ...
    def _OnJumpTo_Crouch(self, info): ...
    def _OnJumpTo_Idle(self, info): ...
    def _OnJumpTo_Jog(self, info): ...
    def _OnJumpTo_Jump(self, info): ...
    def _OnJumpTo_PickUp(self, info): ...
    def _OnJumpTo_Prone(self, info): ...
    def _OnJumpTo_Reload(self, info): ...
    def _OnJumpTo_Slide(self, info): ...
    def _OnJumpTo_Sprint(self, info): ...
    def _OnJumpTo_Stand(self, info): ...
    def _OnJumpTo_SuperSprint(self, info): ...
    def _OnJumpTo_Swim(self, info): ...
    def _OnJumpTo_Walk(self, info): ...
    def _ProcessCueEnd(self, prev, trigger): ...
    def _ReloadAnimTick(self): ...
    def _SetActorToParachute(self): ...
    def _SetActorToSkyDiveState(self): ...
    def _SetActorToSkyOpenFireState(self): ...
    def _SetVisible(self, visible): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_refresh_status_is_ads(self, status, args, kwargs): ...
    def _on_refresh_status_is_dual_fire_start(self, status, args, kwargs): ...
    def _on_refresh_status_is_fire_start(self, status, args, kwargs): ...
    def _on_refresh_status_is_melee_start(self, status, args, kwargs): ...
    def _on_refresh_status_move_state(self, status, args, kwargs): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def _unpinResourcesByTag(self, res_tag): ...
    def _warmUpAndPinResources(self, count): ...
    def _warmUpCallback(self, count): ...
    def add_repeat_timer(self, interval, func): ...
    def add_timer(self, delay, func): ...
    @property
    def can_use_weapon_for_sky(self): ...    def cancel_timer(self, timerid): ...
    def cue_signal_ads_state(self, trigger, signal_str): ...
    def cue_signal_attach_lefthand_weapon(self, trigger, signal_str): ...
    def cue_signal_attach_normal_model(self, trigger, signal_str): ...
    def cue_signal_ban_handik(self, trigger, signal_str): ...
    def cue_signal_camera_sfx(self, trigger, signal_str): ...
    def cue_signal_clear_gun_sfx(self, trigger, signal_str): ...
    def cue_signal_effect_attach_detach(self, trigger, signal_str): ...
    def cue_signal_effect_camera_detach(self, trigger, signal_str): ...
    def cue_signal_enable_handik(self, trigger, signal_str): ...
    def cue_signal_event(self, trigger, signal_str): ...
    def cue_signal_execute_third_model(self, trigger, signal_str): ...
    def cue_signal_fire_end(self, trigger, signal_str): ...
    def cue_signal_fps_camera_hand_offset_enable(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate_enable(self, trigger, signal_str): ...
    def cue_signal_gun_anim_effect(self, trigger, signal_str): ...
    def cue_signal_gun_fire_bullet_effect(self, trigger, signal_str): ...
    def cue_signal_gun_fire_muzzle_effect(self, trigger, signal_str): ...
    def cue_signal_gun_sfx(self, trigger, signal_str): ...
    def cue_signal_gunfire_sound_event(self, trigger, signal_str): ...
    def cue_signal_itemcase_anim_clear_effect(self, trigger, signal_str): ...
    def cue_signal_itemcase_anim_effect(self, trigger, signal_str): ...
    def cue_signal_left_weapon_sfx(self, trigger, signal_str): ...
    def cue_signal_melee_anim_clear_effect(self, trigger, signal_str): ...
    def cue_signal_melee_anim_effect(self, trigger, signal_str): ...
    def cue_signal_motion_blur_to_percent(self, trigger, signal_str): ...
    def cue_signal_optic_model_change(self, trigger, signal_str): ...
    def cue_signal_player_event(self, trigger, signal_str): ...
    def cue_signal_reload_charger_control(self, trigger, signal_str): ...
    def cue_signal_sound_break(self, trigger, signal_str): ...
    def cue_signal_sound_event(self, trigger, signal_str): ...
    def cue_signal_sound_far_event(self, trigger, signal_str): ...
    def cue_signal_spell_event(self, trigger, signal_str): ...
    def cue_signal_switch_weapon(self, trigger, signal_str): ...
    def cue_signal_variable_event_sync_stack(self, trigger, signal_str): ...
    def cue_signal_variable_hand_to_weapon(self, trigger, signal_str): ...
    def cue_signal_weapon_attach(self, trigger, signal_str): ...
    def cue_signal_weapon_show_effect(self, trigger, signal_str): ...
    def cue_type_node_transition_excute(self, trigger, curinput): ...
    def cur_signal_reload_end(self, trigger, signal_str): ...
    @property
    def dual_weapon_model(self): ...    @property
    def fps_move_graph(self): ...    def isModelOnlyValid(self): ...
    def isValid(self): ...
    @property
    def is_destroyed(self): ...    @property
    def is_loaded(self): ...    @property
    def lefthand_weapon_case(self): ...    def onCineDismissPerformer(self, trigger, cueinput): ...
    def onCineDismissPerformers(self, trigger, cueinput): ...
    def onCineDisplayCaption(self, trigger, cueinput): ...
    def onLoaded(self): ...
    @property
    def pose_type(self): ...    @property
    def position(self): ...    @property
    def scale(self): ...    @property
    def skeleton(self): ...    @property
    def space(self): ...    @property
    def weapon_case(self): ...    @property
    def weapon_model(self): ...    @property
    def yaw(self): ...
class RobotHandModel(object):
    def ChangeMoveState(self, state): ...
    def JumpLand(self): ...
    def JumpToFire(self, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def JumpToFireEnd(self): ...
    def JumpToFireStart(self, is_auto_fire=True): ...
    def JumpToMoveState(self, state, info=None, transtime=0.1, reset=False, switch_pos_type=False): ...
    def JumpToState(self, state, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def JumpToThrowBomb(self, spell_id): ...
    def OnCrouch(self, crouch): ...
    def OnSlide(self, slide): ...
    def OnSlideEnd(self, break_slide): ...
    def PushPlates(self, is_end): ...
    def RaiseCurSpecWeapon(self): ...
    def RaiseCurWeapon(self): ...
    def RefreshMoveState(self, state=None): ...
    def SetGraphAnimIn(self, state, is_need_transition): ...
    def SetIsEmptyAmmo(self, is_empty): ...
    def SetMoveDirection(self, move_direction): ...
    def SetMoveStartTime(self, move_action_time): ...
    def SetMpFpsAction(self, action, blendTime): ...
    def Towards(self, x, y): ...
    def _OnJumpTo_Climb(self, info): ...
    def _OnJumpTo_Cross(self, info): ...
    def _OnJumpTo_Crouch(self, info): ...
    def _OnJumpTo_Idle(self, info): ...
    def _OnJumpTo_Jog(self, info): ...
    def _OnJumpTo_Jump(self, info): ...
    def _OnJumpTo_Reload(self, info): ...
    def _OnJumpTo_Slide(self, info): ...
    def _OnJumpTo_Sprint(self, info): ...
    def _OnJumpTo_Stand(self, info): ...
    def _OnJumpTo_SuperSprint(self, info): ...
    def _OnJumpTo_Walk(self, info): ...

class RobotHudFrontsightComp(object):
    def AimPointFadeIn(self, duration=0.5): ...
    def AimPointFadeOut(self, duration=0.5): ...
    def AimPointScatter(self, robot, shoot_idx=0): ...
    def OnMotionStateChange(self, robot, pose_change=False): ...
    def PlayHitAnim(self, hit_part): ...
    def PlayKillAnim(self, hit_part): ...
    def PointerMoveToDist(self, move_dist, pose_dist, speed, min_dist=0): ...
    def PointerSetPosAndMoveToOrigin(self, delay_time, dist, recover_speed): ...
    def RefreshPointerBasePos(self, base_dist): ...
    def SetAimVisible(self, visible): ...

class SimpleModel(BaseModel):
    logger: Logger = <Logger Model (DEBUG)>

    def AddHiddenReason(self, reason): ...
    def AddLoadTask(self, name): ...
    def AddTargetSlot(self, slot_name, actor): ...
    def AddTechState(self, id, custom_param=None): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def ApplyCustomStencil(self, custom_stencil, is_check=False): ...
    def AttachToParent(self, entity, basepoint, hardpoint): ...
    def BatchResetShaderGraphParameter(self, params, layer=-1): ...
    def BatchSetShaderGraphParameter(self, params, values, layer=-1): ...
    def BindBoneColliderCallFunc(self, result): ...
    def BindEventSignalNotify(self): ...
    def CallOwner(self, method, *args, **kwargs): ...
    def ChangeCustomMaterial(self, material_path, **kwargs): ...
    def ChangeShaderGraphMaterial(self, shader_graph_path, layer=-1, inherit=False): ...
    def CheckRecreateSkeletonOnReloaded(self, data): ...
    def ClearALLCueCameraEffect(self): ...
    def ClearAllCueEffectCache(self): ...
    def ClearAllCueSoundCache(self): ...
    def ClearAllSkeletonEffect(self): ...
    def ClearCueEffectCache(self, graph_id, path): ...
    def ClearCueEffectCacheByGraphID(self, graph_id): ...
    def ClearHiddenReason(self): ...
    def ClearMotionBlur(self, elapsedTime, centerU, centerV): ...
    def ClearRigidBodies(self): ...
    def ClearSkeletonEffect(self, effect_id): ...
    def ClearSkeletonEffectByEffectId(self, effect_id): ...
    def ClearSkeletonEffectByEffectIdImmediately(self, effect_id): ...
    def ClearSkeletonEffectImmediately(self, effect_id): ...
    def ClearTechParam(self): ...
    def ClearTechState(self): ...
    def ClearWarmingUpHiddenReason(self): ...
    def CreateSpecifyBone(self, bone_name): ...
    def CustomStencilCheck(self, target_stencil, *args): ...
    def Destroy(self): ...
    def DestroyCppModel(self): ...
    def DisableMixMapAsFarAsPossible(self): ...
    def DisableNormalMap(self): ...
    def DisableOutlined(self): ...
    def DisablePrincipleRole(self): ...
    def EnableOutlined(self, color, thickness): ...
    def FireEvent(self, event, gid=-1): ...
    def GetAllPrim(self, need_sorted=False): ...
    def GetBoneLocalPosition(self, bone): ...
    def GetBoneLocalTransform(self, bone): ...
    def GetBoneModelPosition(self, bone): ...
    def GetBoneTransform(self, bone): ...
    def GetBoneWorldPosition(self, bone): ...
    def GetBoneWorldTransform(self, bone): ...
    def GetGraphHandleInGraphStack(self, graph_name): ...
    def GetMotionSkeletonFile(skeleton): ...
    def GetPrimWorldBound(self): ...
    def GetPrimWorldBoundCentre(self): ...
    def GetPrimWorldBoundCentreWithAttachments(self): ...
    def GetPrimWorldBoundLength(self): ...
    def GetPrimWorldBoundWithAttachments(self): ...
    def GetShaderGraphOriginParameter(self, param, layer=-1): ...
    def GetShaderGraphParameter(self, param, layer): ...
    def GetShaderParameter(self, param): ...
    def GetSkeleton(self): ...
    def GetSkeletonDynamicWorldBound(self): ...
    def GetSkeletonDynamicWorldBoundCentre(self): ...
    def GetSkeletonEffectEntities(self, eff_id): ...
    def GetSkeletonEffectEntitiesByEffectId(self, effect_id): ...
    def GetVariableF(self, varname, gid=-1): ...
    def GetVariableI(self, varname, gid=-1): ...
    def GetVariableS(self, varname, gid=-1): ...
    def GetVariableV3(self, varname, gid=-1): ...
    def GetVariableZ(self, varname, gid=-1): ...
    def HasActorComponent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HaveWarmingUpHiddenReason(self, reason): ...
    def IsEnableOutlined(self): ...
    def IsPrincipleRole(self): ...
    @property
    def IsVisible(self): ...    def JumpToState(self, state, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def Load(self, data, done=None, **create_kwargs): ...
    def MakeSureBones(self): ...
    def MarkPrincipleRole(self): ...
    def ModelExpireCallback(self, ientity): ...
    def OnCineDisplayPerformer(self, trigger, cueinput): ...
    def OnCineHidePerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformers(self, trigger, cueinput): ...
    def OnCineRenamePerformer(self, trigger, cueinput): ...
    def OnVisibleChanged(self, visible): ...
    def PauseGraph(self, pause, gid=-1): ...
    def PlayAnimation(self, anim_name, single_play=True, remove_motion=True, play_speed=1.0): ...
    def PlayEffectById(self, effect_id, max_life=-1, scale=1, bone='root', offset=(0, 0, 0), insure_play=False): ...
    def PlaySkeletonEffect(self, effect_str, max_life=-1, insure_play=False, effect_id=None): ...
    def PopEffectDictByEngineEid(self, engine_eid): ...
    def PopGraph(self, graph_id, blendTime=0): ...
    def PushGraph(self, graph, transtime=0, ratio=0): ...
    def ReceiveDynamicShadow(self): ...
    def Refresh(self): ...
    def RefreshTeammateTechState(self): ...
    def Reload(self, data, done=None, use_ready_to_appear=True): ...
    def ReloadPrimitives(self, data, use_ready_to_appear=True): ...
    def ReloadSkeleton(self, data): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveLoadTask(self, name): ...
    def RemoveTechState(self, proto_id): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def RemoveXRayBlock(self): ...
    def ReplaceGraph(self, graph_id, graph): ...
    def ResetCustomMaterial(self): ...
    def ResetShaderGraphMaterial(self, layer=-1): ...
    def ResetShaderGraphParameter(self, param, layer=-1): ...
    def ResetShaderGraphParameters(self, layer=-1): ...
    def ResetShaderParameter(self, param): ...
    def SetAsCSMRole(self, is_role): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetEnableVisibilityOptimize(self, enable): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetLodDistance(self, layer, distance): ...
    def SetLodDistanceAllLayers(self, distances): ...
    def SetNoNearPlaneClip(self, enable): ...
    def SetOutlinedParam(self, color, thickness): ...
    def SetShaderGraphParameter(self, param, value, layer=-1): ...
    def SetShaderGraphParameterRecursively(self, param, value, layer=-1): ...
    def SetShaderParameter(self, param, value, **kwargs): ...
    def SetShaderParameterRecursively(self, param, value): ...
    def SetSkeletonEffectVisible(self, visible): ...
    def SetSkeletonEffectVisibleForEffectId(self, effect_id, visible): ...
    def SetTechState(self): ...
    def SetTechStateParam(self, tech_id, custom_param): ...
    def SetTransformWithAttachmentsImmediately(self, transform): ...
    def SetVariableF(self, varname, varvalue, gid=-1): ...
    def SetVariableI(self, varname, varvalue, gid=-1): ...
    def SetVariableS(self, varname, varvalue, gid=-1): ...
    def SetVariableV3(self, varname, varvalue, gid=-1): ...
    def SetVariableZ(self, varname, varvalue, gid=-1): ...
    def SetWarmingUp(self, value): ...
    def SetWarmingUpAppearImmediately(self, value): ...
    def ShiftGraph(self, gid, offset): ...
    def SignalNotifyCallback(self, trigger, stype, signalStr): ...
    def SkeletonExpireCallback(self, skeleton): ...
    def StopAnimation(self, anim_name): ...
    def UseDistancedEnemyTechState(self, param, param2): ...
    def UseTechEdgeLine(self, color, thickness): ...
    def UseTechFrozen(self): ...
    def UseTechHighLightXray(self, param, param2, color2): ...
    def UseTechHighlight(self, color, frequency=0.0): ...
    def UseTechXray(self, color2=None, param2=None): ...
    def _CheckSameTachStatus(self, parent, basepoint, hardpoint): ...
    def _GetAvailableModelInfo(self, model_data): ...
    def _ProcessCueEnd(self, prev, trigger): ...
    def _SetVisible(self, visible): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, interval, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def cue_signal_effect_attach_detach(self, trigger, signal_str): ...
    def cue_signal_event(self, trigger, signal_str): ...
    def cue_signal_execute_third_model(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate_enable(self, trigger, signal_str): ...
    def cue_signal_motion_blur_to_percent(self, trigger, signal_str): ...
    def cue_signal_player_event(self, trigger, signal_str): ...
    def cue_signal_sound_event(self, trigger, signal_str): ...
    def cue_signal_sound_far_event(self, trigger, signal_str): ...
    def cue_signal_variable_event_sync_stack(self, trigger, signal_str): ...
    def cue_type_node_transition_excute(self, trigger, curinput): ...
    def isModelOnlyValid(self): ...
    def isValid(self): ...
    @property
    def is_destroyed(self): ...    @property
    def is_loaded(self): ...    def onCineDismissPerformer(self, trigger, cueinput): ...
    def onCineDismissPerformers(self, trigger, cueinput): ...
    def onCineDisplayCaption(self, trigger, cueinput): ...
    def onLoaded(self): ...
    @property
    def position(self): ...    @property
    def scale(self): ...    @property
    def skeleton(self): ...    @property
    def space(self): ...    @property
    def yaw(self): ...

def RobotHandCommand(replay_op, need_pack=True): ...
def get_hip_shoot_scatter_ratio(attr_getter_func, speed_level, pose_type): ...

