# module: gclient.gameplay.logic_base.models.weapon_part_model

import MHelper
import MType
import cconst
import consts
import effect_data
import events
import formula
import gun_skin_optic_data
import gun_skin_template_data
import lobby_item_data
import random_effect_data
import unit_model_data
import weapon_util

RandomSkeletonEffectCache: dict = {}

class SimpleModel(BaseModel):
    logger: Logger = <Logger Model (DEBUG)>

    def AddHiddenReason(self, reason): ...
    def AddLoadTask(self, name): ...
    def AddTargetSlot(self, slot_name, actor): ...
    def AddTechState(self, id, custom_param=None): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def ApplyCustomStencil(self, custom_stencil, is_check=False): ...
    def AttachToParent(self, entity, basepoint, hardpoint): ...
    def BatchResetShaderGraphParameter(self, params, layer=-1): ...
    def BatchSetShaderGraphParameter(self, params, values, layer=-1): ...
    def BindBoneColliderCallFunc(self, result): ...
    def BindEventSignalNotify(self): ...
    def CallOwner(self, method, *args, **kwargs): ...
    def ChangeCustomMaterial(self, material_path, **kwargs): ...
    def ChangeShaderGraphMaterial(self, shader_graph_path, layer=-1, inherit=False): ...
    def CheckRecreateSkeletonOnReloaded(self, data): ...
    def ClearALLCueCameraEffect(self): ...
    def ClearAllCueEffectCache(self): ...
    def ClearAllCueSoundCache(self): ...
    def ClearAllSkeletonEffect(self): ...
    def ClearCueEffectCache(self, graph_id, path): ...
    def ClearCueEffectCacheByGraphID(self, graph_id): ...
    def ClearHiddenReason(self): ...
    def ClearMotionBlur(self, elapsedTime, centerU, centerV): ...
    def ClearRigidBodies(self): ...
    def ClearSkeletonEffect(self, effect_id): ...
    def ClearSkeletonEffectByEffectId(self, effect_id): ...
    def ClearSkeletonEffectByEffectIdImmediately(self, effect_id): ...
    def ClearSkeletonEffectImmediately(self, effect_id): ...
    def ClearTechParam(self): ...
    def ClearTechState(self): ...
    def ClearWarmingUpHiddenReason(self): ...
    def CreateSpecifyBone(self, bone_name): ...
    def CustomStencilCheck(self, target_stencil, *args): ...
    def Destroy(self): ...
    def DestroyCppModel(self): ...
    def DisableMixMapAsFarAsPossible(self): ...
    def DisableNormalMap(self): ...
    def DisableOutlined(self): ...
    def DisablePrincipleRole(self): ...
    def EnableOutlined(self, color, thickness): ...
    def FireEvent(self, event, gid=-1): ...
    def GetAllPrim(self, need_sorted=False): ...
    def GetBoneLocalPosition(self, bone): ...
    def GetBoneLocalTransform(self, bone): ...
    def GetBoneModelPosition(self, bone): ...
    def GetBoneTransform(self, bone): ...
    def GetBoneWorldPosition(self, bone): ...
    def GetBoneWorldTransform(self, bone): ...
    def GetGraphHandleInGraphStack(self, graph_name): ...
    def GetMotionSkeletonFile(skeleton): ...
    def GetPrimWorldBound(self): ...
    def GetPrimWorldBoundCentre(self): ...
    def GetPrimWorldBoundCentreWithAttachments(self): ...
    def GetPrimWorldBoundLength(self): ...
    def GetPrimWorldBoundWithAttachments(self): ...
    def GetShaderGraphOriginParameter(self, param, layer=-1): ...
    def GetShaderGraphParameter(self, param, layer): ...
    def GetShaderParameter(self, param): ...
    def GetSkeleton(self): ...
    def GetSkeletonDynamicWorldBound(self): ...
    def GetSkeletonDynamicWorldBoundCentre(self): ...
    def GetSkeletonEffectEntities(self, eff_id): ...
    def GetSkeletonEffectEntitiesByEffectId(self, effect_id): ...
    def GetVariableF(self, varname, gid=-1): ...
    def GetVariableI(self, varname, gid=-1): ...
    def GetVariableS(self, varname, gid=-1): ...
    def GetVariableV3(self, varname, gid=-1): ...
    def GetVariableZ(self, varname, gid=-1): ...
    def HasActorComponent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HaveWarmingUpHiddenReason(self, reason): ...
    def IsEnableOutlined(self): ...
    def IsPrincipleRole(self): ...
    @property
    def IsVisible(self): ...    def JumpToState(self, state, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def Load(self, data, done=None, **create_kwargs): ...
    def MakeSureBones(self): ...
    def MarkPrincipleRole(self): ...
    def ModelExpireCallback(self, ientity): ...
    def OnCineDisplayPerformer(self, trigger, cueinput): ...
    def OnCineHidePerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformers(self, trigger, cueinput): ...
    def OnCineRenamePerformer(self, trigger, cueinput): ...
    def OnVisibleChanged(self, visible): ...
    def PauseGraph(self, pause, gid=-1): ...
    def PlayAnimation(self, anim_name, single_play=True, remove_motion=True, play_speed=1.0): ...
    def PlayEffectById(self, effect_id, max_life=-1, scale=1, bone='root', offset=(0, 0, 0), insure_play=False): ...
    def PlaySkeletonEffect(self, effect_str, max_life=-1, insure_play=False, effect_id=None): ...
    def PopEffectDictByEngineEid(self, engine_eid): ...
    def PopGraph(self, graph_id, blendTime=0): ...
    def PushGraph(self, graph, transtime=0, ratio=0): ...
    def ReceiveDynamicShadow(self): ...
    def Refresh(self): ...
    def RefreshTeammateTechState(self): ...
    def Reload(self, data, done=None, use_ready_to_appear=True): ...
    def ReloadPrimitives(self, data, use_ready_to_appear=True): ...
    def ReloadSkeleton(self, data): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveLoadTask(self, name): ...
    def RemoveTechState(self, proto_id): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def RemoveXRayBlock(self): ...
    def ReplaceGraph(self, graph_id, graph): ...
    def ResetCustomMaterial(self): ...
    def ResetShaderGraphMaterial(self, layer=-1): ...
    def ResetShaderGraphParameter(self, param, layer=-1): ...
    def ResetShaderGraphParameters(self, layer=-1): ...
    def ResetShaderParameter(self, param): ...
    def SetAsCSMRole(self, is_role): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetEnableVisibilityOptimize(self, enable): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetLodDistance(self, layer, distance): ...
    def SetLodDistanceAllLayers(self, distances): ...
    def SetNoNearPlaneClip(self, enable): ...
    def SetOutlinedParam(self, color, thickness): ...
    def SetShaderGraphParameter(self, param, value, layer=-1): ...
    def SetShaderGraphParameterRecursively(self, param, value, layer=-1): ...
    def SetShaderParameter(self, param, value, **kwargs): ...
    def SetShaderParameterRecursively(self, param, value): ...
    def SetSkeletonEffectVisible(self, visible): ...
    def SetSkeletonEffectVisibleForEffectId(self, effect_id, visible): ...
    def SetTechState(self): ...
    def SetTechStateParam(self, tech_id, custom_param): ...
    def SetTransformWithAttachmentsImmediately(self, transform): ...
    def SetVariableF(self, varname, varvalue, gid=-1): ...
    def SetVariableI(self, varname, varvalue, gid=-1): ...
    def SetVariableS(self, varname, varvalue, gid=-1): ...
    def SetVariableV3(self, varname, varvalue, gid=-1): ...
    def SetVariableZ(self, varname, varvalue, gid=-1): ...
    def SetWarmingUp(self, value): ...
    def SetWarmingUpAppearImmediately(self, value): ...
    def ShiftGraph(self, gid, offset): ...
    def SignalNotifyCallback(self, trigger, stype, signalStr): ...
    def SkeletonExpireCallback(self, skeleton): ...
    def StopAnimation(self, anim_name): ...
    def UseDistancedEnemyTechState(self, param, param2): ...
    def UseTechEdgeLine(self, color, thickness): ...
    def UseTechFrozen(self): ...
    def UseTechHighLightXray(self, param, param2, color2): ...
    def UseTechHighlight(self, color, frequency=0.0): ...
    def UseTechXray(self, color2=None, param2=None): ...
    def _CheckSameTachStatus(self, parent, basepoint, hardpoint): ...
    def _GetAvailableModelInfo(self, model_data): ...
    def _ProcessCueEnd(self, prev, trigger): ...
    def _SetVisible(self, visible): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, interval, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def cue_signal_effect_attach_detach(self, trigger, signal_str): ...
    def cue_signal_event(self, trigger, signal_str): ...
    def cue_signal_execute_third_model(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate_enable(self, trigger, signal_str): ...
    def cue_signal_motion_blur_to_percent(self, trigger, signal_str): ...
    def cue_signal_player_event(self, trigger, signal_str): ...
    def cue_signal_sound_event(self, trigger, signal_str): ...
    def cue_signal_sound_far_event(self, trigger, signal_str): ...
    def cue_signal_variable_event_sync_stack(self, trigger, signal_str): ...
    def cue_type_node_transition_excute(self, trigger, curinput): ...
    def isModelOnlyValid(self): ...
    def isValid(self): ...
    @property
    def is_destroyed(self): ...    @property
    def is_loaded(self): ...    def onCineDismissPerformer(self, trigger, cueinput): ...
    def onCineDismissPerformers(self, trigger, cueinput): ...
    def onCineDisplayCaption(self, trigger, cueinput): ...
    def onLoaded(self): ...
    @property
    def position(self): ...    @property
    def scale(self): ...    @property
    def skeleton(self): ...    @property
    def space(self): ...    @property
    def yaw(self): ...
class WeaponPartModel(SimpleModel):
    logger: Logger = <Logger Model (DEBUG)>

    def AddHiddenReason(self, reason): ...
    def AddLoadTask(self, name): ...
    def AddTargetSlot(self, slot_name, actor): ...
    def AddTechState(self, id, custom_param=None): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def ApplyCustomStencil(self, custom_stencil, is_check=False): ...
    def AttachToParent(self, entity, basepoint, hardpoint): ...
    def AttachToParentPart(self, parent, base_point=None, hard_point=None): ...
    def BatchResetShaderGraphParameter(self, params, layer=-1): ...
    def BatchSetShaderGraphParameter(self, params, values, layer=-1): ...
    def BindBoneColliderCallFunc(self, result): ...
    def BindEventSignalNotify(self): ...
    def CallOwner(self, method, *args, **kwargs): ...
    def ChangeCustomMaterial(self, material_path, **kwargs): ...
    def ChangePartModel(self, model_id, done=None): ...
    def ChangeShaderGraphMaterial(self, shader_graph_path, layer=-1, inherit=False): ...
    def CheckRecreateSkeletonOnReloaded(self, data): ...
    def ClearALLCueCameraEffect(self): ...
    def ClearAllCueEffectCache(self): ...
    def ClearAllCueSoundCache(self): ...
    def ClearAllSkeletonEffect(self): ...
    def ClearCueEffectCache(self, graph_id, path): ...
    def ClearCueEffectCacheByGraphID(self, graph_id): ...
    def ClearHiddenReason(self): ...
    def ClearMotionBlur(self, elapsedTime, centerU, centerV): ...
    def ClearRigidBodies(self): ...
    def ClearSkeletonEffect(self, eid): ...
    def ClearSkeletonEffectByEffectId(self, effect_id): ...
    def ClearSkeletonEffectByEffectIdImmediately(self, effect_id): ...
    def ClearSkeletonEffectImmediately(self, effect_id): ...
    def ClearTechParam(self): ...
    def ClearTechState(self): ...
    def ClearWarmingUpHiddenReason(self): ...
    def CreateSpecifyBone(self, bone_name): ...
    def CustomStencilCheck(self, target_stencil, *args): ...
    def Destroy(self): ...
    def DestroyCppModel(self): ...
    def DetachFromParentPart(self): ...
    def DisableMixMapAsFarAsPossible(self): ...
    def DisableNormalMap(self): ...
    def DisableOutlined(self): ...
    def DisablePrincipleRole(self): ...
    def EnableOutlined(self, color, thickness): ...
    def FireEvent(self, event, gid=-1): ...
    def GetAllPrim(self, need_sorted=False): ...
    def GetBoneLocalPosition(self, bone): ...
    def GetBoneLocalTransform(self, bone): ...
    def GetBoneModelPosition(self, bone): ...
    def GetBoneTransform(self, bone): ...
    def GetBoneWorldPosition(self, bone): ...
    def GetBoneWorldTransform(self, bone): ...
    def GetGraphHandleInGraphStack(self, graph_name): ...
    def GetMotionSkeletonFile(skeleton): ...
    def GetPrimWorldBound(self): ...
    def GetPrimWorldBoundCentre(self): ...
    def GetPrimWorldBoundCentreWithAttachments(self): ...
    def GetPrimWorldBoundLength(self): ...
    def GetPrimWorldBoundWithAttachments(self): ...
    def GetShaderGraphOriginParameter(self, param, layer=-1): ...
    def GetShaderGraphParameter(self, param, layer): ...
    def GetShaderParameter(self, param): ...
    def GetSkeleton(self): ...
    def GetSkeletonDynamicWorldBound(self): ...
    def GetSkeletonDynamicWorldBoundCentre(self): ...
    def GetSkeletonEffectEntities(self, eff_id): ...
    def GetSkeletonEffectEntitiesByEffectId(self, effect_id): ...
    def GetVariableF(self, varname, gid=-1): ...
    def GetVariableI(self, varname, gid=-1): ...
    def GetVariableS(self, varname, gid=-1): ...
    def GetVariableV3(self, varname, gid=-1): ...
    def GetVariableZ(self, varname, gid=-1): ...
    def HasActorComponent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HaveWarmingUpHiddenReason(self, reason): ...
    def InitPrimAlphaValue(self): ...
    def InspectionWeaponEnd(self): ...
    def InspectionWeaponStart(self): ...
    def IsEnableOutlined(self): ...
    def IsPrincipleRole(self): ...
    @property
    def IsVisible(self): ...    def JumpToAds(self, is_ads): ...
    def JumpToFireEnd(self): ...
    def JumpToFireStart(self): ...
    def JumpToState(self, state, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def Load(self, data, done=None, **create_kwargs): ...
    def LoadModelBaseSkin(self): ...
    def LoadModelSkin(self, skin_id, is_init=False, start_load=False): ...
    def LoadSkinTextureCallback(self, param, guid, is_init=False, start_load=False): ...
    def MakeSureBones(self): ...
    def MarkPrincipleRole(self): ...
    def ModelExpireCallback(self, ientity): ...
    def OnCineDisplayPerformer(self, trigger, cueinput): ...
    def OnCineHidePerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformers(self, trigger, cueinput): ...
    def OnCineRenamePerformer(self, trigger, cueinput): ...
    def OnModelLoadedFinally(self, is_init=False): ...
    def OnSkinLoaded(self, is_init=False): ...
    def OnVisibleChanged(self, visible): ...
    def OnWeaponModelLoad(self): ...
    def PauseGraph(self, pause, gid=-1): ...
    def PlayAnimation(self, anim_name, single_play=True, remove_motion=True, play_speed=1.0): ...
    def PlayEffectById(self, effect_id, max_life=-1, scale=1, bone='root', offset=(0, 0, 0), insure_play=False): ...
    def PlayModelCombineAnim(self, anim_name): ...
    def PlayModelSplitAnim(self, anim_name, is_splited=False): ...
    def PlayRandomSkeletonEffect(self, group_id, max_life=5.0, insure_play=False): ...
    def PlaySkeletonEffect(self, effect_str, max_life=5.0, insure_play=False, effect_id=None): ...
    def PopEffectDictByEngineEid(self, engine_eid): ...
    def PopGraph(self, graph_id, blendTime=0): ...
    def PostprocessPerformance(self): ...
    def ProcessExtraOffsetForOptic(self): ...
    def PushGraph(self, graph, transtime=0, ratio=0): ...
    def ReceiveDynamicShadow(self): ...
    def Refresh(self): ...
    def RefreshAmmoNumberEffect(self, ammo, max_ammo): ...
    def RefreshAmmoShaderEffect(self, ammo, max_ammo): ...
    def RefreshHandGraphValue(self, val_name, value): ...
    def RefreshTeammateTechState(self): ...
    def Reload(self, data, done=None, use_ready_to_appear=True): ...
    def ReloadPrimitives(self, data, use_ready_to_appear=True): ...
    def ReloadSkeleton(self, data): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveLoadTask(self, name): ...
    def RemoveTechState(self, proto_id): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def RemoveXRayBlock(self): ...
    def ReplaceGraph(self, graph_id, graph): ...
    def ResetAlphaOnResetShaderGraphParam(self): ...
    def ResetCustomMaterial(self): ...
    def ResetShaderGraphMaterial(self, layer=-1): ...
    def ResetShaderGraphParameter(self, param, layer=-1): ...
    def ResetShaderGraphParameters(self, layer=-1): ...
    def ResetShaderParameter(self, param): ...
    def SetAsCSMRole(self, is_role): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetEnableVisibilityOptimize(self, enable): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsEmptyReload(self, is_empty): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetLeftAmmoCount(self, value): ...
    def SetLodDistance(self, layer, distance): ...
    def SetLodDistanceAllLayers(self, distances): ...
    def SetMpFpsAction(self, action, blendTime): ...
    def SetNoNearPlaneClip(self, enable): ...
    def SetOutlinedParam(self, color, thickness): ...
    def SetShaderGraphParameter(self, param, value, layer=-1): ...
    def SetShaderGraphParameterRecursively(self, param, value, layer=-1): ...
    def SetShaderParameter(self, param, value, **kwargs): ...
    def SetShaderParameterRecursively(self, param, value): ...
    def SetSkeletonEffectVisible(self, visible): ...
    def SetSkeletonEffectVisibleForEffectId(self, effect_id, visible): ...
    def SetTechState(self): ...
    def SetTechStateParam(self, tech_id, custom_param): ...
    def SetTransformWithAttachmentsImmediately(self, transform): ...
    def SetVariableF(self, varname, varvalue, gid=-1): ...
    def SetVariableI(self, varname, varvalue, gid=-1): ...
    def SetVariableS(self, varname, varvalue, gid=-1): ...
    def SetVariableV3(self, varname, varvalue, gid=-1): ...
    def SetVariableZ(self, varname, varvalue, gid=-1): ...
    def SetWarmingUp(self, value): ...
    def SetWarmingUpAppearImmediately(self, value): ...
    def SetWeaponModelShadingParam(self): ...
    def ShiftGraph(self, gid, offset): ...
    def SignalNotifyCallback(self, trigger, stype, signalStr): ...
    def SkeletonExpireCallback(self, skeleton): ...
    def StopAnimation(self, anim_name): ...
    def UseDistancedEnemyTechState(self, param, param2): ...
    def UseTechEdgeLine(self, color, thickness): ...
    def UseTechFrozen(self): ...
    def UseTechHighLightXray(self, param, param2, color2): ...
    def UseTechHighlight(self, color, frequency=0.0): ...
    def UseTechXray(self, color2=None, param2=None): ...
    def _CheckNeedRefreshGraphValue(self, name): ...
    def _CheckSameTachStatus(self, parent, basepoint, hardpoint): ...
    def _GetAvailableModelInfo(self, model_data): ...
    def _ProcessCueEnd(self, prev, trigger): ...
    def _SetVisible(self, visible): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, interval, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def cue_signal_effect_attach_detach(self, trigger, signal_str): ...
    def cue_signal_event(self, trigger, signal_str): ...
    def cue_signal_execute_third_model(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate_enable(self, trigger, signal_str): ...
    def cue_signal_motion_blur_to_percent(self, trigger, signal_str): ...
    def cue_signal_player_event(self, trigger, signal_str): ...
    def cue_signal_sound_event(self, trigger, signal_str): ...
    def cue_signal_sound_far_event(self, trigger, signal_str): ...
    def cue_signal_variable_event_sync_stack(self, trigger, signal_str): ...
    def cue_type_node_transition_excute(self, trigger, curinput): ...
    def isModelOnlyValid(self): ...
    def isValid(self): ...
    @property
    def is_destroyed(self): ...    @property
    def is_loaded(self): ...    def onCineDismissPerformer(self, trigger, cueinput): ...
    def onCineDismissPerformers(self, trigger, cueinput): ...
    def onCineDisplayCaption(self, trigger, cueinput): ...
    def onLoaded(self): ...
    @property
    def position(self): ...    @property
    def scale(self): ...    @property
    def skeleton(self): ...    @property
    def space(self): ...    @property
    def yaw(self): ...
class WeaponSkinComponent(object):
    def LoadModelBaseSkin(self): ...
    def LoadModelSkin(self, skin_id, is_init=False, start_load=False): ...
    def LoadSkinTextureCallback(self, param, guid, is_init=False, start_load=False): ...
    def OnModelLoadedFinally(self, is_init=False): ...
    def OnSkinLoaded(self, is_init=False): ...
    def PostprocessPerformance(self): ...


def Components(*components, **kwargs): ...
def RegisterModelClass(cls): ...

