# module: gclient.gamesystem.models.warehouse_model_manager

import MEngine
import MType
import MUI
import Timer
import cconst
import consts
import equip_data
import events
import formula
import gun_attachments_data
import gun_decal_slot_template_data
import gun_smith_camera
import math

BOW_HANGING_CAMERA_FOCUS_OFFSET: Vector3 = <0.0300, 0.0000, -0.1104>
CAM_DIR_BASE: tuple = (-0.7964, 0.0799, 0.5994)
CAM_FOCUS_POS_BASE: tuple = (2.5376, 0.7749, -0.8246)
CAM_FOCUS_POS_OFFSET_BASE: tuple = (-0.1, -0.005, 0.2313)
CAM_TO_WEAPON_BASE_VEC: tuple = (-0.84, 0.071, 0.3681)
CAM_TRANS_BASE: Matrix4x3 = <<-0.6014, 0.0000, -0.7990> <0.0639, 0.9968, -0.0481> <0.7964, -0.0799, -0.5994> <2.9340, 0.6950, -1.4240>>
DECAL_CAMERA_FOCUS_OFFSET: float = 0.1
HANGING_CAMERA_FOCUS_OFFSET: Vector3 = <0.0171, 0.0000, -0.0362>
WEAPON_BOX_BASE_CENTER: tuple = (2.094, 0.766, -1.0559)
WEAPON_BOX_BASE_LENGTH: float = 1.046
WEAPON_BOX_BASE_LENGTH_V: float = 0.8
WEAPON_INIT_POS: Vector3 = <-100.0000, -100.0000, -100.0000>
WEAPON_MODEL_POS: tuple = (2.0, 0.85, -1.15)
WEAPON_MODEL_YAW: float = 0.785

class EquipCaseFactory(object):
    def Create(weapon_id, *args, **kwargs): ...

class IdManager(object):
    def bytes2id(bytes): ...
    def genid(): ...
    def id2bytes(uid): ...
    def id2str(uid): ...
    def is_valid_id(entityid): ...
    def str2id(string): ...

class ModelRotateComponent(object):
    def ClearRotateRecover(self): ...
    def ClearZoomRecover(self): ...
    def EnableModelRotate(self, is_enable): ...
    def EndRotateRecover(self): ...
    def InitControlTrans(self, origin_pos=None): ...
    def InitRotateAxis(self, x_axis=None, y_axis=None): ...
    def IsRotateModelY(self): ...
    def OnMouseEnd(self): ...
    def OnMouseMove(self, x, y): ...
    def RecoverOriginTransform(self): ...
    def RefreshRotateOrigin(self, origin_pos): ...
    def RotateModel(self, x, y): ...
    def RotateRecover(self, dt): ...
    def RotateRecoverImmediately(self): ...
    def SetRotateModelY(self, value): ...
    def StartRotateRecover(self): ...
    def StartRotateRecoverTimer(self): ...
    def StartZoomRecover(self): ...
    def StartZoomRecoverTimer(self): ...
    def ZoomRecoverImmediately(self): ...

class Singleton(object):
    def Destroy(): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class WarehouseModelManager(Singleton):
    def AddHiddenReason(self, reason): ...
    def CheckBoundBoxValid(self, min, max): ...
    def ClearRefreshTimer(self): ...
    def ClearRotateRecover(self): ...
    def ClearWeaponModel(self): ...
    def ClearZoomRecover(self): ...
    def Destroy(): ...
    def EnableModelRotate(self, is_enable): ...
    def EndRotateRecover(self): ...
    def FocusCamera(self, show_weapon): ...
    def GetShowPositionByEquipProto(self, equip_proto): ...
    def GetShowRotationByEquipProto(self, equip_proto): ...
    def GetShowScaleByEquipProto(self, equip_proto): ...
    def InitControlTrans(self, origin_pos=None): ...
    def InitRotateAxis(self, x_axis=None, y_axis=None): ...
    def InitWeaponModel(self, equip_id, skin_id=None, guise_id=None, part_slots=None, hangings_id=None, sticker_dict=None, part_guise_info=None, focus_camera=False, bomb_skin_id=None): ...
    def IsRotateModelY(self): ...
    def OnDestroy(self): ...
    def OnMouseEnd(self): ...
    def OnMouseMove(self, x, y): ...
    def OnWeaponLoaded(self, focus_camera, weapon_model): ...
    def RecoverModelRotateImmediately(self): ...
    def RecoverOriginTransform(self): ...
    def RefreshModelDisplay(self, focus_camera): ...
    def RefreshRotateOrigin(self, origin_pos): ...
    def RemoveHiddenReason(self, reason): ...
    def RotateModel(self, x, y): ...
    def RotateRecover(self, dt): ...
    def RotateRecoverImmediately(self): ...
    def SelectCameraType(self, camera_type, show_weapon): ...
    def SetRotateModelY(self, value): ...
    def StartRotateRecover(self): ...
    def StartRotateRecoverTimer(self): ...
    def StartZoomRecover(self): ...
    def StartZoomRecoverTimer(self): ...
    def UpdateModelYaw(self): ...
    def ZoomRecoverImmediately(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def default_weapon_pos(self): ...    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...
    @property
    def model(self): ...    @property
    def position(self): ...    @property
    def scale(self): ...    @property
    def weapon_model(self): ...
class partial(object):
    args: member_descriptor = <member 'args' of 'functools.partial' objects>
    func: member_descriptor = <member 'func' of 'functools.partial' objects>
    keywords: member_descriptor = <member 'keywords' of 'functools.partial' objects>


def Components(*components, **kwargs): ...

