# module: gclient.gamesystem.models.warehouse_item_model_ctrl

import MEngine
import MType
import Timer
import cc
import consts
import events
import lobby_item_data
import math

class DlcStatusComponent(object):
    def OnRefreshDownloadState(self, dlc_id, status): ...
    def ShowDlcStatusNode(self, dlc_id, pos): ...

class HallCommonModelShowCtrl(Singleton):
    HallWeaponType: int = 0
    MODEL_BOUND_LENGTH_BASE: float = 1.33069443806
    MODEL_PITCH_BASE: int = 0
    MODEL_POS_BASE: tuple = (0.009, 1.005, -1.914)
    MODEL_ROLL_BASE: int = 0
    MODEL_YAW_BASE: float = 1.571

    def AddHiddenReason(self, reason): ...
    def CancelDelayRefreshOriginTimer(self): ...
    def CancelDelayRefreshPosTimer(self): ...
    def ClearRotateRecover(self): ...
    def ClearZoomRecover(self): ...
    def DelayRefreshRotateOrigin(self): ...
    def DelayRefreshWeaponPos(self): ...
    def Destroy(): ...
    def EnableModelRotate(self, is_enable): ...
    def EndRotateRecover(self): ...
    def GetItemModelPosition(self, item_proto=None): ...
    def GetItemModelYaw(self, item_proto): ...
    def GetModelPos(self): ...
    def GetModelRotation(self, equip_proto): ...
    def HasHiddenReason(self, reason): ...
    def InitControlTrans(self, origin_pos=None): ...
    def InitModel(self, item_id, check_dlc=True): ...
    def InitModel_BombSkin(self, item_id): ...
    def InitModel_Clothes(self, item_id): ...
    def InitModel_Collection(self, item_id): ...
    def InitModel_GunGuise(self, item_id): ...
    def InitModel_GunSkin(self, item_id): ...
    def InitModel_Item(self, item_id): ...
    def InitModel_MeleeWeapon(self, item_id): ...
    def InitModel_NoShow(self, item_id): ...
    def InitRotateAxis(self, x_axis=None, y_axis=None): ...
    def InitWeaponModel(self, equip_id, skin_id=None, guise_id=None, part_slots=None, extra=None, gun_id=None): ...
    def IsRotateModelY(self): ...
    def OnDestroy(self): ...
    def OnMouseEnd(self): ...
    def OnMouseMove(self, x, y): ...
    def OnRefreshDownloadState(self, dlc_id, status): ...
    def OnShowDlcStatusNode(self): ...
    def OnShowModelLoaded(self, weapon_model=None): ...
    def RecoverOriginTransform(self): ...
    def RefreshRotateOrigin(self, origin_pos): ...
    def RemoveHiddenReason(self, reason): ...
    def RotateModel(self, x, y): ...
    def RotateRecover(self, dt): ...
    def RotateRecoverImmediately(self): ...
    def SetRotateModelY(self, value): ...
    def SetShowModelScale(self, scale): ...
    def ShowDlcStatusNode(self, dlc_id, pos): ...
    def StartRotateRecover(self): ...
    def StartRotateRecoverTimer(self): ...
    def StartZoomRecover(self): ...
    def StartZoomRecoverTimer(self): ...
    def UpdateModelTrans(self): ...
    def ZoomRecoverImmediately(self): ...
    def _GetModelWorldBound(self): ...
    def _GetModelWorldBoundCentre(self): ...
    def _InitWeaponCaseByPartSlots(self, part_slots, extra=None): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...
    @property
    def is_loaded(self): ...    @property
    def model(self): ...
class WarehouseItemModelCtrl(HallCommonModelShowCtrl):
    HallWeaponType: int = 0
    MODEL_BOUND_LENGTH_BASE: float = 0.6363636363636362
    MODEL_PITCH_BASE: int = 0
    MODEL_POS_BASE: tuple = (1.8666, 0.7583, -1.0493)
    MODEL_ROLL_BASE: int = 0
    MODEL_YAW_BASE: float = 0.7
    SCREEN_POS_DIRECTION: tuple = (0, 0, 1)

    def AddHiddenReason(self, reason): ...
    def CancelDelayRefreshOriginTimer(self): ...
    def CancelDelayRefreshPosTimer(self): ...
    def ClearRotateRecover(self): ...
    def ClearZoomRecover(self): ...
    def DelayRefreshRotateOrigin(self): ...
    def DelayRefreshWeaponPos(self): ...
    def Destroy(): ...
    def EnableModelRotate(self, is_enable): ...
    def EndRotateRecover(self): ...
    def GetItemModelPosition(self, item_proto=None): ...
    def GetItemModelYaw(self, item_proto): ...
    def GetModelPos(self): ...
    def GetModelRotation(self, equip_proto): ...
    def HasHiddenReason(self, reason): ...
    def InitControlTrans(self, origin_pos=None): ...
    def InitModel(self, item_id, check_dlc=True): ...
    def InitModel_BombSkin(self, item_id): ...
    def InitModel_Clothes(self, item_id): ...
    def InitModel_Collection(self, item_id): ...
    def InitModel_GunGuise(self, item_id): ...
    def InitModel_GunSkin(self, item_id): ...
    def InitModel_Item(self, item_id): ...
    def InitModel_MeleeWeapon(self, item_id): ...
    def InitModel_NoShow(self, item_id): ...
    def InitRotateAxis(self, x_axis=None, y_axis=None): ...
    def InitWeaponModel(self, equip_id, skin_id=None, guise_id=None, part_slots=None, extra=None, gun_id=None): ...
    def IsRotateModelY(self): ...
    def OnDestroy(self): ...
    def OnMouseEnd(self): ...
    def OnMouseMove(self, x, y): ...
    def OnRefreshDownloadState(self, dlc_id, status): ...
    def OnShowDlcStatusNode(self): ...
    def OnShowModelLoaded(self, weapon_model=None): ...
    def RecoverOriginTransform(self): ...
    def RefreshRotateOrigin(self, origin_pos): ...
    def RemoveHiddenReason(self, reason): ...
    def RotateModel(self, x, y): ...
    def RotateRecover(self, dt): ...
    def RotateRecoverImmediately(self): ...
    def SetRotateModelY(self, value): ...
    def SetShowModelScale(self, scale): ...
    def ShowDlcStatusNode(self, dlc_id, pos): ...
    def ShowItem(self, item_id, visible): ...
    def StartRotateRecover(self): ...
    def StartRotateRecoverTimer(self): ...
    def StartZoomRecover(self): ...
    def StartZoomRecoverTimer(self): ...
    def UpdateModelTrans(self): ...
    def ZoomRecoverImmediately(self): ...
    def _GetModelWorldBound(self): ...
    def _GetModelWorldBoundCentre(self): ...
    def _InitWeaponCaseByPartSlots(self, part_slots, extra=None): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...
    @property
    def is_loaded(self): ...    @property
    def model(self): ...

def Components(*components, **kwargs): ...

