# module: gclient.gameplay.logic_hotspot.avatarmembers.cimp_hotspot

import cconst
import events
import replay_util

DeadTopologFlag: str = 'dead'

class CombatAvatarMember(object):
    def GetTeammateColorIndex(self, teammate_id): ...
    def _on_set_faction(self, old): ...

class GameState(enum):
    FINISHED: int = 2
    GAMING: int = 1
    WAITING: int = 0
    name_to_values: dict = {'WAITING': 0, 'GAMING': 1, 'FINISHED': 2}
    value_to_names: dict = {0: 'WAITING', 1: 'GAMING', 2: 'FINISHED'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class PlayerCombatAvatarMember(CombatAvatarMember):
    def ClearControlPlayerOnDead(self): ...
    def GetTeammateColorIndex(self, teammate_id): ...
    def OnGameStateEnumChange(self, old_state, new_state): ...
    def _on_set_faction(self, old): ...


