# module: gclient.gameplay.logic_client_offline.game_logic_client_offline

class GameLogicBase(ClientAreaEntity):
    ALLOW_SELECT_SAME_HERO: bool = False
    CAN_HIGH_SKY_PARA: bool = False
    FORBIDDEN_USE_COMBAT_ITEM_GAME_STATE: tuple = ()
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = True
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = False
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    MAIN_UI_TYPE: int = 1
    NEED_MARK_ITEM: bool = True
    NinjaBeacon: bool = False
    RECORD_QUALITY_EFFECT_ITEM: bool = False
    SHOW_ITEM_QUALITY_EFFECT: bool = True
    SHOW_KNOCKDOWN: bool = True
    SHOW_PICKUP_DETAIL: bool = True
    SUPPLY_ITEM_BLOW_OUT: bool = False
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    logger: Logger = <Logger GameLogicBase (DEBUG)>

    def AddStoryTick(self, func, frames=0): ...
    def CacheGameLogicUI(self): ...
    def CalDamageForMonster(self, caster, target, skill_idx): ...
    def CalFallHurtDamage(self, fall_diff_height): ...
    def CalFinalWeaponDamge(self, spell_id, spell_result, caster, target, weapon_id, damage_data, check_precondition): ...
    def CalWeaponDamageForRobotAttackPlayer(self, caster, target, hit_part): ...
    def CalWeaponDamageNormal(self, caster, target, weapon_id, hit_part, spell_result, damage_data): ...
    def CalWeaponDamageNormalForRobot(self, caster, target, hit_part): ...
    def CanDamage(self, a, b): ...
    def CanDealDamageResult(self, caster, target): ...
    def CheckBlockSkill(self, caster_or_pos, target, hit_part, damage_data): ...
    def CheckCasterCanShootShield(self, caster, target): ...
    def CheckCasterCanShootTarget(self, caster, target): ...
    def CheckRobotCanAttack(self): ...
    def ClearAllStoryTick(self): ...
    def DealDamageWithCombatAttr(self, caster, target, weapon_id, base_damage=None): ...
    def DealDamageWithTalent(self, caster, target, damage_data): ...
    def DealHitPartChange(self, cur_weapon, hit_part): ...
    def DealMeleeWeaponDamageResult(self, spell_id, spell_result, caster, target, weapon_id, **kwargs): ...
    def DealPenetrateFalloff(self, caster, cur_weapon, damage, penetrate_power, penetrate_materials): ...
    def DealRangeFalloff(self, caster, weapon_id, cur_weapon, damage, dist): ...
    def DealWeaponDamageResult(self, spell_id, spell_result, caster, target, weapon_id, calc_damage, **kwargs): ...
    def DestroyGameLogicUI(self): ...
    def GetBaseWeaponDamage_bow_spell(self, spell_result, caster, target, weapon_id, cur_weapon, real_hit_part, damage_data): ...
    def GetBaseWeaponDamage_dual_gun_spell(self, spell_result, caster, target, weapon_id, cur_weapon, real_hit_part, damage_data): ...
    def GetBaseWeaponDamage_gun_spell(self, spell_result, caster, target, weapon_id, cur_weapon, real_hit_part, damage_data): ...
    def GetBaseWeaponDamage_melee_spell(self, spell_result, caster, target, weapon_id, cur_weapon, hit_part, damage_data): ...
    def GetBaseWeaponDamage_samurai_sprint_kick_up_spell(self, spell_result, caster, target, weapon_id, cur_weapon, hit_part, damage_data): ...
    def GetBaseWeaponDamage_samurai_sprint_spell(self, spell_result, caster, target, weapon_id, cur_weapon, hit_part, damage_data): ...
    def GetBaseWeaponDamage_shotgun_spell(self, spell_result, caster, target, weapon_id, cur_weapon, real_hit_part, damage_data): ...
    def GetBaseWeaponDamage_spirit_spell(self, spell_result, caster, target, weapon_id, cur_weapon, hit_part, damage_data): ...
    def GetBaseWeaponDamage_sword_laser_spell(self, spell_result, caster, target, weapon_id, cur_weapon, hit_part, damage_data): ...
    def GetBaseWeaponDamage_sword_spirit_spell(self, spell_result, caster, target, weapon_id, cur_weapon, hit_part, damage_data): ...
    def GetHitEffectMaxLifeTime(self, weapon_id=None): ...
    def GetHudTeamInfoClass(): ...
    def GetOption(self, name, default=None): ...
    def InBirthIsland(self): ...
    def InForbiddenUseCombatItemGameState(self): ...
    def InitBattleUI(self): ...
    def InitGameLogic(self): ...
    def InitGameLogicUI(self): ...
    def IsCrystalMode(self): ...
    def IsEnableRobotStrop(self): ...
    def IsEnemy(self, a, b): ...
    def IsFinishLoading(self): ...
    def IsFriend(self, a, b): ...
    def IsOpenGameplayMode(self, mode): ...
    def IsTeammate(self, a, b): ...
    def IsValidActivity(self, act_id): ...
    def LoadRelativeMedias(self): ...
    def MissileBlast(self, hit_pos, shoot_dir, hit_normal, arms_class): ...
    def OnAvatarDie(self, target, caster, critical_spell): ...
    def OnAvatarDying(self, target, caster, critical_spell): ...
    def OnGameFinished(self): ...
    def OnGameGaming(self): ...
    def OnGameWaiting(self): ...
    def OnHitCombatAvatarByNonBoneParts(self, spell_id, spell_result, caster, target, weapon, hit_result, hit_dir, penetrate_materials): ...
    def OnInteractionWithAirdrop(self, entity, is_enter): ...
    def OnMonsterDie(self, monster, caster, critical_spell): ...
    def OnPlayerClothes(self, key, old, new): ...
    def OnSpellResult(self, cur_result): ...
    def OnSpellResultFull(self, cur_result): ...
    def OnWorldLoaded(self): ...
    def PostDealDamage(self, caster, target, damage, base_damage, damage_data): ...
    def PushKillPrompt(self, target, caster, critical_spell): ...
    def RefreshBattleUI(self): ...
    def RemoveStoryTick(self, func): ...
    def RestoreBattleUI(self): ...
    def SetOpenGameplayMode(self, mode): ...
    def ShowCalculationUI(self, settle_data, delay_time=0, from_replay=False): ...
    def StartCountdown(self): ...
    def StopBattleUI(self): ...
    def UnloadRelativeMedias(self): ...
    def _CalDamageForRobot(caster, target, hit_part): ...
    def _GetRelativeMediaFiles(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_set_countdown(self, old): ...
    def _on_set_game_state(self, old): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    @property
    def combat_avatars(self): ...    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    def destroy_for_replay(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    @property
    def game_logic_code(self): ...    @property
    def game_logic_data(self): ...    def get_gtick(self): ...
    @property
    def hall_match_data(self): ...    def init_from_dict(self, *args, **kwargs): ...
    @property
    def is_consider_hit_non_bone_parts(self): ...    def is_deactived(self): ...
    def is_destroyed(self): ...
    @property
    def is_gaming(self): ...    @property
    def is_highlight(self): ...    @property
    def is_playback(self): ...    @property
    def is_room(self): ...    @property
    def is_shutter_clue_open(self): ...    @property
    def is_shutter_energy_open(self): ...    @property
    def is_watching(self): ...    @property
    def is_zombie_mode(self): ...    @property
    def match_data(self): ...    @property
    def match_proto(self): ...    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def player(self): ...    @property
    def pos(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def show_match_data(self): ...    @property
    def show_match_type(self): ...    @property
    def space(self): ...    @property
    def speed(self): ...    @property
    def suffix(self): ...    def tick(self, dtime): ...
    @property
    def yaw(self): ...
class GameLogicClientOffline(GameLogicBase):
    ALLOW_SELECT_SAME_HERO: bool = False
    CAN_HIGH_SKY_PARA: bool = False
    FORBIDDEN_USE_COMBAT_ITEM_GAME_STATE: tuple = ()
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = True
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = False
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    MAIN_UI_TYPE: int = 1
    NEED_MARK_ITEM: bool = True
    NinjaBeacon: bool = False
    RECORD_QUALITY_EFFECT_ITEM: bool = False
    SHOW_ITEM_QUALITY_EFFECT: bool = True
    SHOW_KNOCKDOWN: bool = True
    SHOW_PICKUP_DETAIL: bool = True
    SUPPLY_ITEM_BLOW_OUT: bool = False
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    logger: Logger = <Logger GameLogicClientOffline (DEBUG)>

    def AddStoryTick(self, func, frames=0): ...
    def CacheGameLogicUI(self): ...
    def CalDamageForMonster(self, caster, target, skill_idx): ...
    def CalFallHurtDamage(self, fall_diff_height): ...
    def CalFinalWeaponDamge(self, spell_id, spell_result, caster, target, weapon_id, damage_data, check_precondition): ...
    def CalWeaponDamageForRobotAttackPlayer(self, caster, target, hit_part): ...
    def CalWeaponDamageNormal(self, caster, target, weapon_id, hit_part, spell_result, damage_data): ...
    def CalWeaponDamageNormalForRobot(self, caster, target, hit_part): ...
    def CanDamage(self, a, b): ...
    def CanDealDamageResult(self, caster, target): ...
    def CheckBlockSkill(self, caster_or_pos, target, hit_part, damage_data): ...
    def CheckCasterCanShootShield(self, caster, target): ...
    def CheckCasterCanShootTarget(self, caster, target): ...
    def CheckRobotCanAttack(self): ...
    def ClearAllStoryTick(self): ...
    def DealDamageWithCombatAttr(self, caster, target, weapon_id, base_damage=None): ...
    def DealDamageWithTalent(self, caster, target, damage_data): ...
    def DealHitPartChange(self, cur_weapon, hit_part): ...
    def DealMeleeWeaponDamageResult(self, spell_id, spell_result, caster, target, weapon_id, **kwargs): ...
    def DealPenetrateFalloff(self, caster, cur_weapon, damage, penetrate_power, penetrate_materials): ...
    def DealRangeFalloff(self, caster, weapon_id, cur_weapon, damage, dist): ...
    def DealSpellResult(self, avatar, cur_result): ...
    def DealWeaponDamageResult(self, spell_id, spell_result, caster, target, weapon_id, calc_damage, **kwargs): ...
    def DestroyGameLogicUI(self): ...
    def GetBaseWeaponDamage_bow_spell(self, spell_result, caster, target, weapon_id, cur_weapon, real_hit_part, damage_data): ...
    def GetBaseWeaponDamage_dual_gun_spell(self, spell_result, caster, target, weapon_id, cur_weapon, real_hit_part, damage_data): ...
    def GetBaseWeaponDamage_gun_spell(self, spell_result, caster, target, weapon_id, cur_weapon, real_hit_part, damage_data): ...
    def GetBaseWeaponDamage_melee_spell(self, spell_result, caster, target, weapon_id, cur_weapon, hit_part, damage_data): ...
    def GetBaseWeaponDamage_samurai_sprint_kick_up_spell(self, spell_result, caster, target, weapon_id, cur_weapon, hit_part, damage_data): ...
    def GetBaseWeaponDamage_samurai_sprint_spell(self, spell_result, caster, target, weapon_id, cur_weapon, hit_part, damage_data): ...
    def GetBaseWeaponDamage_shotgun_spell(self, spell_result, caster, target, weapon_id, cur_weapon, real_hit_part, damage_data): ...
    def GetBaseWeaponDamage_spirit_spell(self, spell_result, caster, target, weapon_id, cur_weapon, hit_part, damage_data): ...
    def GetBaseWeaponDamage_sword_laser_spell(self, spell_result, caster, target, weapon_id, cur_weapon, hit_part, damage_data): ...
    def GetBaseWeaponDamage_sword_spirit_spell(self, spell_result, caster, target, weapon_id, cur_weapon, hit_part, damage_data): ...
    def GetHitEffectMaxLifeTime(self, weapon_id=None): ...
    def GetHudTeamInfoClass(): ...
    def GetOption(self, name, default=None): ...
    def InBirthIsland(self): ...
    def InForbiddenUseCombatItemGameState(self): ...
    def InitBattleUI(self): ...
    def InitGameLogic(self): ...
    def InitGameLogicUI(self): ...
    def IsCrystalMode(self): ...
    def IsEnableRobotStrop(self): ...
    def IsEnemy(self, a, b): ...
    def IsFinishLoading(self): ...
    def IsFriend(self, a, b): ...
    def IsOpenGameplayMode(self, mode): ...
    def IsTeammate(self, a, b): ...
    def IsValidActivity(self, act_id): ...
    def LoadRelativeMedias(self): ...
    def MissileBlast(self, hit_pos, shoot_dir, hit_normal, arms_class): ...
    def OnAvatarDie(self, target, caster, critical_spell): ...
    def OnAvatarDying(self, target, caster, critical_spell): ...
    def OnGameFinished(self): ...
    def OnGameGaming(self): ...
    def OnGameWaiting(self): ...
    def OnHitCombatAvatarByNonBoneParts(self, spell_id, spell_result, caster, target, weapon, hit_result, hit_dir, penetrate_materials): ...
    def OnInteractionWithAirdrop(self, entity, is_enter): ...
    def OnMonsterDie(self, monster, caster, critical_spell): ...
    def OnPlayerClothes(self, key, old, new): ...
    def OnSpellResult(self, cur_result): ...
    def OnSpellResultFull(self, cur_result): ...
    def OnWorldLoaded(self): ...
    def PostDealDamage(self, caster, target, damage, base_damage, damage_data): ...
    def PushKillPrompt(self, target, caster, critical_spell): ...
    def RefreshBattleUI(self): ...
    def RemoveStoryTick(self, func): ...
    def RestoreBattleUI(self): ...
    def SetOpenGameplayMode(self, mode): ...
    def ShowCalculationUI(self, settle_data, delay_time=0, from_replay=False): ...
    def StartCountdown(self): ...
    def StopBattleUI(self): ...
    def UnloadRelativeMedias(self): ...
    def _CalDamageForRobot(caster, target, hit_part): ...
    def _GetRelativeMediaFiles(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_set_countdown(self, old): ...
    def _on_set_game_state(self, old): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    @property
    def combat_avatars(self): ...    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    def destroy_for_replay(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    @property
    def game_logic_code(self): ...    @property
    def game_logic_data(self): ...    def get_gtick(self): ...
    @property
    def hall_match_data(self): ...    def init_from_dict(self, *args, **kwargs): ...
    @property
    def is_consider_hit_non_bone_parts(self): ...    def is_deactived(self): ...
    def is_destroyed(self): ...
    @property
    def is_gaming(self): ...    @property
    def is_highlight(self): ...    @property
    def is_playback(self): ...    @property
    def is_room(self): ...    @property
    def is_shutter_clue_open(self): ...    @property
    def is_shutter_energy_open(self): ...    @property
    def is_watching(self): ...    @property
    def is_zombie_mode(self): ...    @property
    def match_data(self): ...    @property
    def match_proto(self): ...    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def player(self): ...    @property
    def pos(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def show_match_data(self): ...    @property
    def show_match_type(self): ...    @property
    def space(self): ...    @property
    def speed(self): ...    @property
    def suffix(self): ...    def tick(self, dtime): ...
    @property
    def yaw(self): ...
class SpellResult(object):
    def CreateSimple(caster, spell_id, spell_level=1, direct_caster=None): ...
    def FillSimpleDamage(self, targetid, damage, weapon_id=None, **kwargs): ...
    def Pack(self): ...
    def SimpPack(self): ...
    def SimpUnpack(self, result_list): ...
    def Unpack(self, result): ...
    def _Dict2List(self, dict_data, keys): ...
    def _List2Dict(self, list_data, keys): ...
    @property
    def proto(self): ...

