# module: gclient.framework.util.android_util

import BaseGeneralLog
import GeneralLog
import MConfig
import MEngine
import MLauncher
import MPlatform
import Timer
import cconst
import os
import six2
import switches
import sys
import traceback

def CheckIsEmulator(): ...
def CheckShutdownEmulator(): ...
def FindAndroidNetInfo(): ...
def FindMumuLiar(): ...
def GenerateCpuInfo(): ...
def GetOpenGlEsVersion(): ...
def IsChromeOS(): ...
def NormalInit(): ...
def SetAndroidCpuCores(): ...
def _GetHardwareInfo(): ...
def _InitAndroidPkgName(): ...
def _InitTouchHighSensitive(): ...

