# module: gclient.framework.util.desktop_input

import MConfig
import MEngine
import MUI
import functools
import six2
import time

class DesktopInput(object):
    ALL_MOUSE_KEYS: tuple = (258, 257, 262, 261, 259, 260, 263, 264)
    KEY_0: int = 11
    KEY_1: int = 2
    KEY_2: int = 3
    KEY_3: int = 4
    KEY_4: int = 5
    KEY_5: int = 6
    KEY_6: int = 7
    KEY_7: int = 8
    KEY_8: int = 9
    KEY_9: int = 10
    KEY_A: int = 30
    KEY_APOSTROPHE: int = 40
    KEY_APPS: int = 221
    KEY_B: int = 48
    KEY_BACKSLASH: int = 43
    KEY_BACKSPACE: int = 14
    KEY_C: int = 46
    KEY_CAPSLOCK: int = 58
    KEY_COMMA: int = 51
    KEY_D: int = 32
    KEY_DELETE: int = 211
    KEY_DOWNARROW: int = 208
    KEY_E: int = 18
    KEY_END: int = 207
    KEY_EQUAL: int = 13
    KEY_ESCAPE: int = 1
    KEY_F: int = 33
    KEY_F1: int = 59
    KEY_F10: int = 68
    KEY_F11: int = 87
    KEY_F12: int = 88
    KEY_F2: int = 60
    KEY_F3: int = 61
    KEY_F4: int = 62
    KEY_F5: int = 63
    KEY_F6: int = 64
    KEY_F7: int = 65
    KEY_F8: int = 66
    KEY_F9: int = 67
    KEY_G: int = 34
    KEY_GRAVE: int = 41
    KEY_H: int = 35
    KEY_HOME: int = 199
    KEY_I: int = 23
    KEY_INSERT: int = 210
    KEY_J: int = 36
    KEY_K: int = 37
    KEY_L: int = 38
    KEY_LALT: int = 56
    KEY_LBRACKET: int = 26
    KEY_LCTRL: int = 29
    KEY_LEFTARROW: int = 203
    KEY_LSHIFT: int = 42
    KEY_LWIN: int = 219
    KEY_M: int = 50
    KEY_MINIMUMKEY: int = 1
    KEY_MINUS: int = 12
    KEY_N: int = 49
    KEY_NONE: int = 0
    KEY_NUMLOCK: int = 197
    KEY_NUMPAD0: int = 82
    KEY_NUMPAD1: int = 79
    KEY_NUMPAD2: int = 80
    KEY_NUMPAD3: int = 81
    KEY_NUMPAD4: int = 75
    KEY_NUMPAD5: int = 76
    KEY_NUMPAD6: int = 77
    KEY_NUMPAD7: int = 71
    KEY_NUMPAD8: int = 72
    KEY_NUMPAD9: int = 73
    KEY_NUMPADADD: int = 78
    KEY_NUMPADCOMMA: int = 179
    KEY_NUMPADENTER: int = 156
    KEY_NUMPADMINUS: int = 74
    KEY_NUMPADPERIOD: int = 83
    KEY_NUMPADSLASH: int = 181
    KEY_NUMPADSTAR: int = 55
    KEY_O: int = 24
    KEY_P: int = 25
    KEY_PAGEDOWN: int = 209
    KEY_PAGEUP: int = 201
    KEY_PAUSE: int = 69
    KEY_PERIOD: int = 52
    KEY_Q: int = 16
    KEY_R: int = 19
    KEY_RALT: int = 184
    KEY_RBRACKET: int = 27
    KEY_RCTRL: int = 157
    KEY_RETURN: int = 28
    KEY_RIGHTARROW: int = 205
    KEY_RSHIFT: int = 54
    KEY_RWIN: int = 220
    KEY_S: int = 31
    KEY_SCRLOCK: int = 70
    KEY_SEMICOLON: int = 39
    KEY_SLASH: int = 53
    KEY_SPACE: int = 57
    KEY_SYSRQ: int = 183
    KEY_T: int = 20
    KEY_TAB: int = 15
    KEY_U: int = 22
    KEY_UPARROW: int = 200
    KEY_V: int = 47
    KEY_W: int = 17
    KEY_X: int = 45
    KEY_Y: int = 21
    KEY_Z: int = 44
    MOUSE_L: int = 257
    MOUSE_L_DOUBLE: int = 261
    MOUSE_M: int = 263
    MOUSE_M_D_CLICK: int = 264
    MOUSE_R: int = 258
    MOUSE_R_DOUBLE: int = 262
    MOUSE_WHEEL_DOWN: int = 260
    MOUSE_WHEEL_UP: int = 259
    MOUSE_X1: int = 265
    MOUSE_X2: int = 266
    UNBIND_REASON_TEXT_INPUT: int = 1
    _instance: NoneType = None

    def AddUnbindReason(self, reason): ...
    def EnableInput(self, enable): ...
    def ListenCharInput(self, callback, ch): ...
    def QueryHistoryFromNow(self, start_stamp): ...
    def RemoveCharInput(self, callback, ch): ...
    def RemoveUnbindReason(self, reason): ...
    def bind(self): ...
    def cleanup(self): ...
    def listenKeyDown(self, callback, *triggers): ...
    def listenKeyUp(self, callback, *triggers): ...
    def listenMouseLDown(self, callback): ...
    def listenMouseLUp(self, callback): ...
    def listenMouseMDClick(self, callback): ...
    def listenMouseMDown(self, callback): ...
    def listenMouseMUp(self, callback): ...
    def listenMouseMove(self, callback): ...
    def listenMouseRDown(self, callback): ...
    def listenMouseRUp(self, callback): ...
    def listenMouseWheelDown(self, callback): ...
    def listenMouseWheelUp(self, callback): ...
    def listenMouseX1Down(self, callback): ...
    def listenMouseX1Up(self, callback): ...
    def listenMouseX2Down(self, callback): ...
    def listenMouseX2Up(self, callback): ...
    def listenTouchDragBegin(self, callback, bottomleft, topright): ...
    def listenTouchDragEnd(self, callback, bottomleft, topright): ...
    def listenTouchDragMove(self, callback, bottomleft, topright, force): ...
    def listenTouchTip(self, callback, bottomleft, topright): ...
    def onChar(self, ch): ...
    def onKeyDown(self, state, key): ...
    def onKeyUp(self, state, key): ...
    def onMouseLDown(self, state, x, y): ...
    def onMouseLUp(self, state, x, y): ...
    def onMouseMDClick(self, state, x, y): ...
    def onMouseMDown(self, state, x, y): ...
    def onMouseMUp(self, state, x, y): ...
    def onMouseMove(self, state, x, y): ...
    def onMouseRDown(self, state, x, y): ...
    def onMouseRUp(self, state, x, y): ...
    def onMouseWheelDown(self, state): ...
    def onMouseWheelUp(self, state): ...
    def onMouseX1Down(self, state, x, y): ...
    def onMouseX1Up(self, state, x, y): ...
    def onMouseX2Down(self, state, x, y): ...
    def onMouseX2Up(self, state, x, y): ...
    def onTouchDragBegin(self, state, x, y, index, total, force): ...
    def onTouchDragEnd(self, state, x, y, index, total, force): ...
    def onTouchDragMove(self, state, x, y, index, total, force): ...
    def onTouchTip(self, state, x, y): ...
    def removeKeyDown(self, callback, *triggers): ...
    def removeMouseLDown(self, callback): ...
    def removeMouseLUp(self, callback): ...
    def removeMouseMDClick(self, callback): ...
    def removeMouseMDown(self, callback): ...
    def removeMouseMUp(self, callback): ...
    def removeMouseMove(self, callback): ...
    def removeMouseRDown(self, callback): ...
    def removeMouseRUp(self, callback): ...
    def removeMouseWheelDown(self, callback): ...
    def removeMouseWheelUp(self, callback): ...
    def removeMouseX1Down(self, callback): ...
    def removeMouseX1Up(self, callback): ...
    def removeMouseX2Down(self, callback): ...
    def removeMouseX2Up(self, callback): ...
    def unbind(self): ...
    def unbind_key(self): ...

class SingletonMeta(type):
    mro: method_descriptor = <method 'mro' of 'type' objects>

class deque(object):
    append: method_descriptor = <method 'append' of 'collections.deque' objects>
    appendleft: method_descriptor = <method 'appendleft' of 'collections.deque' objects>
    clear: method_descriptor = <method 'clear' of 'collections.deque' objects>
    copy: method_descriptor = <method 'copy' of 'collections.deque' objects>
    count: method_descriptor = <method 'count' of 'collections.deque' objects>
    extend: method_descriptor = <method 'extend' of 'collections.deque' objects>
    extendleft: method_descriptor = <method 'extendleft' of 'collections.deque' objects>
    index: method_descriptor = <method 'index' of 'collections.deque' objects>
    insert: method_descriptor = <method 'insert' of 'collections.deque' objects>
    maxlen: getset_descriptor = <attribute 'maxlen' of 'collections.deque' objects>
    pop: method_descriptor = <method 'pop' of 'collections.deque' objects>
    popleft: method_descriptor = <method 'popleft' of 'collections.deque' objects>
    remove: method_descriptor = <method 'remove' of 'collections.deque' objects>
    reverse: method_descriptor = <method 'reverse' of 'collections.deque' objects>
    rotate: method_descriptor = <method 'rotate' of 'collections.deque' objects>


def history_record(func): ...

