# module: gclient.framework.util.gameinput_controller

import GlobalData
import MConfig
import MEngine
import MUI
import Timer
import cconst
import controller_key_data
import controller_key_group_data
import events
import functools
import game_const_data
import hashlib
import joystick_smoother
import lang
import os
import pc_key_data
import pc_key_group_data
import replay_util
import six2
import switches
import sys
import time
import ui_define

CONTROLLER_DOWN_TYPE: tuple = (0, 2)
DO_NOT_CLEAR_INACTIVE: bool = False
LocalConfig: _LocalConfig = <gclient.config._LocalConfig object at 0x7040bf6d50>
RESPONSE_WAY_KEY_DOUBLE: int = 2
RESPONSE_WAY_KEY_DOWN: int = 0
RESPONSE_WAY_KEY_UP: int = 1
_reload_all: int = 1

class ControllerInput(object):
    CONTROLLER_KEY_IGNORE: int = 0
    CONTROLLER_KEY_MAX: int = 126
    CONTROLLER_KEY_MIN: int = 89
    EKey_ButtonA: int = 89
    EKey_ButtonB: int = 90
    EKey_ButtonBACK: int = 104
    EKey_ButtonC: int = 91
    EKey_ButtonCIRCLE: int = 114
    EKey_ButtonCROSS: int = 115
    EKey_ButtonDOWN: int = 109
    EKey_ButtonDPADDOWN: int = 123
    EKey_ButtonDPADLEFT: int = 124
    EKey_ButtonDPADRIGHT: int = 125
    EKey_ButtonDPADUP: int = 122
    EKey_ButtonDirLR: int = 215
    EKey_ButtonDirUpDown: int = 214
    EKey_ButtonL: int = 118
    EKey_ButtonL1: int = 95
    EKey_ButtonL2: int = 97
    EKey_ButtonL3: int = 105
    EKey_ButtonLEFT: int = 110
    EKey_ButtonLJoystick: int = 200
    EKey_ButtonLJoystickLR: int = 210
    EKey_ButtonLJoystickUpDown: int = 211
    EKey_ButtonMode: int = 103
    EKey_ButtonOPTIONS: int = 107
    EKey_ButtonR: int = 119
    EKey_ButtonR1: int = 96
    EKey_ButtonR2: int = 98
    EKey_ButtonR3: int = 106
    EKey_ButtonRIGHT: int = 112
    EKey_ButtonRJoystick: int = 201
    EKey_ButtonRJoystickLR: int = 212
    EKey_ButtonRJoystickUpDown: int = 213
    EKey_ButtonSELECT: int = 102
    EKey_ButtonSQUARE: int = 116
    EKey_ButtonSTART: int = 101
    EKey_ButtonTOUCHPAD: int = 117
    EKey_ButtonTRIANGLE: int = 113
    EKey_ButtonThumbL: int = 99
    EKey_ButtonThumbR: int = 100
    EKey_ButtonUP: int = 108
    EKey_ButtonX: int = 92
    EKey_ButtonY: int = 93
    EKey_ButtonZ: int = 94
    EKey_ButtonZL: int = 120
    EKey_ButtonZR: int = 121
    EKey_Cursor: int = 202
    KEYMAPPING: dict = {108: 122, 109: 123, 110: 124, 112: 125, 115: 89, 114: 90, 116: 92, 113: 93, 102: 104}
    ROCKER_TO_MOVE_LIST: tuple = (125, 124, 122, 123)
    _instance: ControllerInput = <gclient.framework.util.controller_input.ControllerInput object at 0x7005e34850>

    def AddUnbindReason(self, reason): ...
    def EnableInput(self, enable): ...
    def RemoveUnbindReason(self, reason): ...
    def bind(self): ...
    def cleanUp(self): ...
    def initCheck(self): ...
    def listenJoystickCursor(self, callback): ...
    def listenJoystickInfo(self, callback): ...
    def listenJoystickMove(self, callback): ...
    def listenKeyDown(self, callback, *triggers): ...
    def listenKeyUp(self, callback, *triggers): ...
    def onJoystickCursor(self, arg1, arg2, arg3): ...
    def onJoystickInfo(self, info, result, index=0, show_tips=True): ...
    def onJoystickMove(self, state, input_list): ...
    def onKeyDown(self, state, key): ...
    def onKeyUp(self, state, key): ...
    def unBind(self): ...
    def unbind_key(self): ...

class ControllerInputEvents(Singleton):
    _instance: ControllerInputEvents = <ControllerInputEvents(0x0x7005e342d0)>

    def Destroy(): ...
    def OnDestroy(self): ...
    def RegisterInputResponse(self, game_input_instance): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class ControllerInputResponse(enum):
    COMBINED_DOWN: int = 4
    DOWN: int = 0
    DOWN_AND_UP: int = 2
    LONG_DOWN_AND_UP: int = 3
    UP: int = 1
    name_to_values: dict = {'DOWN': 0, 'UP': 1, 'DOWN_AND_UP': 2, 'LONG_DOWN_AND_UP': 3, 'COMBINED_DOWN': 4}
    value_to_names: dict = {0: 'DOWN', 1: 'UP', 2: 'DOWN_AND_UP', 3: 'LONG_DOWN_AND_UP', 4: 'COMBINED_DOWN'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class ControllerKeyState(enum):
    NONE: int = 0
    WAIT_RESPONSE: int = 1
    WAIT_UP: int = 2
    name_to_values: dict = {'NONE': 0, 'WAIT_RESPONSE': 1, 'WAIT_UP': 2}
    value_to_names: dict = {0: 'NONE', 1: 'WAIT_RESPONSE', 2: 'WAIT_UP'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class DesktopInput(object):
    ALL_MOUSE_KEYS: tuple = (258, 257, 262, 261, 259, 260, 263, 264)
    KEY_0: int = 11
    KEY_1: int = 2
    KEY_2: int = 3
    KEY_3: int = 4
    KEY_4: int = 5
    KEY_5: int = 6
    KEY_6: int = 7
    KEY_7: int = 8
    KEY_8: int = 9
    KEY_9: int = 10
    KEY_A: int = 30
    KEY_APOSTROPHE: int = 40
    KEY_APPS: int = 221
    KEY_B: int = 48
    KEY_BACKSLASH: int = 43
    KEY_BACKSPACE: int = 14
    KEY_C: int = 46
    KEY_CAPSLOCK: int = 58
    KEY_COMMA: int = 51
    KEY_D: int = 32
    KEY_DELETE: int = 211
    KEY_DOWNARROW: int = 208
    KEY_E: int = 18
    KEY_END: int = 207
    KEY_EQUAL: int = 13
    KEY_ESCAPE: int = 1
    KEY_F: int = 33
    KEY_F1: int = 59
    KEY_F10: int = 68
    KEY_F11: int = 87
    KEY_F12: int = 88
    KEY_F2: int = 60
    KEY_F3: int = 61
    KEY_F4: int = 62
    KEY_F5: int = 63
    KEY_F6: int = 64
    KEY_F7: int = 65
    KEY_F8: int = 66
    KEY_F9: int = 67
    KEY_G: int = 34
    KEY_GRAVE: int = 41
    KEY_H: int = 35
    KEY_HOME: int = 199
    KEY_I: int = 23
    KEY_INSERT: int = 210
    KEY_J: int = 36
    KEY_K: int = 37
    KEY_L: int = 38
    KEY_LALT: int = 56
    KEY_LBRACKET: int = 26
    KEY_LCTRL: int = 29
    KEY_LEFTARROW: int = 203
    KEY_LSHIFT: int = 42
    KEY_LWIN: int = 219
    KEY_M: int = 50
    KEY_MINIMUMKEY: int = 1
    KEY_MINUS: int = 12
    KEY_N: int = 49
    KEY_NONE: int = 0
    KEY_NUMLOCK: int = 197
    KEY_NUMPAD0: int = 82
    KEY_NUMPAD1: int = 79
    KEY_NUMPAD2: int = 80
    KEY_NUMPAD3: int = 81
    KEY_NUMPAD4: int = 75
    KEY_NUMPAD5: int = 76
    KEY_NUMPAD6: int = 77
    KEY_NUMPAD7: int = 71
    KEY_NUMPAD8: int = 72
    KEY_NUMPAD9: int = 73
    KEY_NUMPADADD: int = 78
    KEY_NUMPADCOMMA: int = 179
    KEY_NUMPADENTER: int = 156
    KEY_NUMPADMINUS: int = 74
    KEY_NUMPADPERIOD: int = 83
    KEY_NUMPADSLASH: int = 181
    KEY_NUMPADSTAR: int = 55
    KEY_O: int = 24
    KEY_P: int = 25
    KEY_PAGEDOWN: int = 209
    KEY_PAGEUP: int = 201
    KEY_PAUSE: int = 69
    KEY_PERIOD: int = 52
    KEY_Q: int = 16
    KEY_R: int = 19
    KEY_RALT: int = 184
    KEY_RBRACKET: int = 27
    KEY_RCTRL: int = 157
    KEY_RETURN: int = 28
    KEY_RIGHTARROW: int = 205
    KEY_RSHIFT: int = 54
    KEY_RWIN: int = 220
    KEY_S: int = 31
    KEY_SCRLOCK: int = 70
    KEY_SEMICOLON: int = 39
    KEY_SLASH: int = 53
    KEY_SPACE: int = 57
    KEY_SYSRQ: int = 183
    KEY_T: int = 20
    KEY_TAB: int = 15
    KEY_U: int = 22
    KEY_UPARROW: int = 200
    KEY_V: int = 47
    KEY_W: int = 17
    KEY_X: int = 45
    KEY_Y: int = 21
    KEY_Z: int = 44
    MOUSE_L: int = 257
    MOUSE_L_DOUBLE: int = 261
    MOUSE_M: int = 263
    MOUSE_M_D_CLICK: int = 264
    MOUSE_R: int = 258
    MOUSE_R_DOUBLE: int = 262
    MOUSE_WHEEL_DOWN: int = 260
    MOUSE_WHEEL_UP: int = 259
    MOUSE_X1: int = 265
    MOUSE_X2: int = 266
    UNBIND_REASON_TEXT_INPUT: int = 1
    _instance: NoneType = None

    def AddUnbindReason(self, reason): ...
    def EnableInput(self, enable): ...
    def ListenCharInput(self, callback, ch): ...
    def QueryHistoryFromNow(self, start_stamp): ...
    def RemoveCharInput(self, callback, ch): ...
    def RemoveUnbindReason(self, reason): ...
    def bind(self): ...
    def cleanup(self): ...
    def listenKeyDown(self, callback, *triggers): ...
    def listenKeyUp(self, callback, *triggers): ...
    def listenMouseLDown(self, callback): ...
    def listenMouseLUp(self, callback): ...
    def listenMouseMDClick(self, callback): ...
    def listenMouseMDown(self, callback): ...
    def listenMouseMUp(self, callback): ...
    def listenMouseMove(self, callback): ...
    def listenMouseRDown(self, callback): ...
    def listenMouseRUp(self, callback): ...
    def listenMouseWheelDown(self, callback): ...
    def listenMouseWheelUp(self, callback): ...
    def listenMouseX1Down(self, callback): ...
    def listenMouseX1Up(self, callback): ...
    def listenMouseX2Down(self, callback): ...
    def listenMouseX2Up(self, callback): ...
    def listenTouchDragBegin(self, callback, bottomleft, topright): ...
    def listenTouchDragEnd(self, callback, bottomleft, topright): ...
    def listenTouchDragMove(self, callback, bottomleft, topright, force): ...
    def listenTouchTip(self, callback, bottomleft, topright): ...
    def onChar(self, ch): ...
    def onKeyDown(self, state, key): ...
    def onKeyUp(self, state, key): ...
    def onMouseLDown(self, state, x, y): ...
    def onMouseLUp(self, state, x, y): ...
    def onMouseMDClick(self, state, x, y): ...
    def onMouseMDown(self, state, x, y): ...
    def onMouseMUp(self, state, x, y): ...
    def onMouseMove(self, state, x, y): ...
    def onMouseRDown(self, state, x, y): ...
    def onMouseRUp(self, state, x, y): ...
    def onMouseWheelDown(self, state): ...
    def onMouseWheelUp(self, state): ...
    def onMouseX1Down(self, state, x, y): ...
    def onMouseX1Up(self, state, x, y): ...
    def onMouseX2Down(self, state, x, y): ...
    def onMouseX2Up(self, state, x, y): ...
    def onTouchDragBegin(self, state, x, y, index, total, force): ...
    def onTouchDragEnd(self, state, x, y, index, total, force): ...
    def onTouchDragMove(self, state, x, y, index, total, force): ...
    def onTouchTip(self, state, x, y): ...
    def removeKeyDown(self, callback, *triggers): ...
    def removeMouseLDown(self, callback): ...
    def removeMouseLUp(self, callback): ...
    def removeMouseMDClick(self, callback): ...
    def removeMouseMDown(self, callback): ...
    def removeMouseMUp(self, callback): ...
    def removeMouseMove(self, callback): ...
    def removeMouseRDown(self, callback): ...
    def removeMouseRUp(self, callback): ...
    def removeMouseWheelDown(self, callback): ...
    def removeMouseWheelUp(self, callback): ...
    def removeMouseX1Down(self, callback): ...
    def removeMouseX1Up(self, callback): ...
    def removeMouseX2Down(self, callback): ...
    def removeMouseX2Up(self, callback): ...
    def unbind(self): ...
    def unbind_key(self): ...

class DesktopInputEvents(Singleton):
    AllKeys: set = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 41, 42, 44, 45, 46, 47, 48, 49, 50, 54, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 71, 72, 73, 75, 76, 77, 79, 80, 81, 82, 87, 88, 156, 157, 199, 200, 201, 203, 205, 207, 208, 209, 211}

    def Destroy(): ...
    def OnDestroy(self): ...
    def RegisterInputResponse(self, game_input_instance): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class GameInputController(Singleton):
    _instance: GameInputController = <GameInputController(0x0x7005e1ff90)>

    def AddBanInputReason(self, input_type, reason): ...
    def AddCursorDisplayedReason(self, reason): ...
    def AddShowReasonGamepadCursor(self, reason): ...
    def AskHelp(self): ...
    def CheckActivateGamepad(self): ...
    def CheckAndTriggerFunc(self, func_name, args=None): ...
    def CheckConflictedKeyGuide(self, calculate=False): ...
    def CheckNewKeyGuide(self): ...
    def CheckRealGamepadKeyByFuncId(self, func_id): ...
    def CheckRealKeyByFuncId(self, func_id): ...
    def ClearAllInactive(self): ...
    def ClearBanInputReason(self, input_type): ...
    def ClearCursorDisplayedReason(self): ...
    def ClearDroneMoveKeys(self): ...
    def ClearMouseKeys(self): ...
    def ClearMoveKeys(self): ...
    def ClearSettingHook(self): ...
    def ClearVehicleMoveKeys(self): ...
    def ControlPlayer(self, player, handle_cursor=True): ...
    def ConvertDroneKeysState(self): ...
    def ConvertMoveKeysState(self): ...
    def ConvertVehicleKeysState(self): ...
    def Destroy(): ...
    def DoKeyResponseFunc(self, response_func, is_down, key): ...
    def DoKeyUpDownFunc(self, key, is_down=True): ...
    def ForceClearBanInputReason(self): ...
    def GamepadInputInit(self): ...
    def GetComplexKeyResponseFuncs(self, key, is_down): ...
    def GetFuncKeyByFuncId(self, func_id): ...
    def GetKeyCombineDownFuncList(self, key): ...
    def GetKeyDownFuncList(self, key): ...
    def GetKeyFuncsByCashed(self, key, cache, check_set): ...
    def GetKeyLongFuncList(self, key): ...
    def GetKeyResponseFuncs(self, key, is_down): ...
    def GetKeyResponseFuncsCache(self, key, is_down): ...
    def GetKeyUpFuncList(self, key): ...
    def GetMoveKeysState(self): ...
    def GetPlayerMoveDir(self): ...
    def HandleAllKeyFunc(self): ...
    def HandleCallbackUp(self, key): ...
    def HandleKeyCombineDown(self, key): ...
    def HandleKeyDown(self, key): ...
    def HandleKeyLong(self, key): ...
    def HandleKeyUp(self, key): ...
    def HandleRegisteredFunc(self, key, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HaveBanInputReason(self, input_type, reason): ...
    def HaveCursorDisplayedReason(self, reason): ...
    def InheritedDronePressedKeys(self): ...
    def InheritedVehiclePressedKeys(self): ...
    def InitDefaultKeyMap(self): ...
    def InitSettingKeyMap(self): ...
    def JoystickCursor(self, handle_no, x, y): ...
    def JoystickInfo(self, info, result, index, show_tips=True): ...
    def JoystickKeyDown(self, state, key): ...
    def JoystickKeyDownImp(self, key): ...
    def JoystickKeyUp(self, state, key): ...
    def JoystickKeyUpImp(self, key): ...
    def JoystickMove(self, state, input_list): ...
    def LeftJoystick(self, offset_x, offset_y): ...
    def OnActionDown(self): ...
    def OnActionUp(self): ...
    def OnCaptureScreen(self): ...
    def OnCloseCommonUI(self): ...
    def OnControllerTurnHudView(self, diffx, diffy): ...
    def OnDestroy(self): ...
    def OnEnterChat(self): ...
    def OnEnterInactive(self): ...
    def OnKeyDown(self, state, key): ...
    def OnKeyUp(self, state, key): ...
    def OnL2Battle(self, degree): ...
    def OnLongKeyTrigger(self, key): ...
    def OnMikeSetting(self): ...
    def OnMouseLDown(self, x, y): ...
    def OnMouseLOpWhenMouseBan(self): ...
    def OnMouseLUp(self, x, y): ...
    def OnMouseMDClick(self, x, y): ...
    def OnMouseMDown(self, x, y): ...
    def OnMouseMUp(self, x, y): ...
    def OnMouseMove(self, state, x, y): ...
    def OnMouseRDown(self, x, y): ...
    def OnMouseRUp(self, x, y): ...
    def OnMouseWheelDown(self): ...
    def OnMouseWheelUp(self): ...
    def OnMouseX1Down(self, x, y): ...
    def OnMouseX1Up(self, x, y): ...
    def OnMouseX2Down(self, x, y): ...
    def OnMouseX2Up(self, x, y): ...
    def OnPressPlaceSystemHotKey(self, args): ...
    def OnR2Battle(self, degree): ...
    def OnRequestNetTexture(self, use_immediately, host, image_url, request, reply): ...
    def OnToggleImguiCmd(self): ...
    def OnToggleMiniMap(self): ...
    def OnTouchControl(self, x, y): ...
    def OnTurnHudView(self, diffx, diffy): ...
    def OnTurnHudViewBegin(self): ...
    def OnTurnHudViewEnd(self): ...
    def OnWatchNext(self): ...
    def OpenSetting(self): ...
    def PreDownloadGamepadCursor(self): ...
    def ProcessRocker(self, dt): ...
    def RefreshControllerGroup(self): ...
    def RefreshCursorDisplayedReason(self): ...
    def RefreshCursorDisplayedReasonByHall(self, is_in_hall): ...
    def RefreshShowReasonGamepadCursor(self): ...
    def RegisterControllerFunc(self, key_funcs, all_keys=False, to_bottom=False): ...
    def RegisterGamepadCursor(self, rid, key=89, k_x=0, k_y=1): ...
    def RemoveBanInputReason(self, input_type, reason): ...
    def RemoveCursorDisplayedReason(self, reason): ...
    def RemoveShowReasonGamepadCursor(self, reason): ...
    def RightJoystick(self, rotate_x, rotate_y): ...
    def SetDronePressedKey(self, direction, value): ...
    def SetGameLogicInput(self, logic_input): ...
    def SetGamepadCursorIcon(self, icon_id=12111): ...
    def SetMovePressedKey(self, direction, value): ...
    def SetSettingHook(self, setting_hook): ...
    def SetVehiclePressedKey(self, direction, value): ...
    def UnregisterControllerFunc(self, rid): ...
    def _BanMouseInput(self, is_ban): ...
    def _BanMouseMove(self, is_ban): ...
    def _BanMoveInput(self, is_ban): ...
    def _CheckDPad(self, hat_x, hat_y): ...
    def _ImpOnJoyStickInfo(self, info, result, index): ...
    def _SetCursorVisible(self, visible): ...
    def _SetCursorVisibleByReason(self, visible): ...
    def _SetGamepadCursorVisible(self, visible): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class GamepadCursorShowReason(enum):
    COMMON: int = 0
    HALL: int = 1
    SWALLOW: int = 2
    name_to_values: dict = {'COMMON': 0, 'HALL': 1, 'SWALLOW': 2}
    value_to_names: dict = {0: 'COMMON', 1: 'HALL', 2: 'SWALLOW'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class Singleton(object):
    def Destroy(): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class StoryTick(object):
    _instance: StoryTick = <gclient.framework.util.story_tick.StoryTick object at 0x7005e37fd0>

    def Add(self, func, frames=0): ...
    def Remove(self, func): ...
    def doAdd(self, func, frames): ...
    def doRemove(self, func): ...
    def onTick(self, _, dtime): ...

class defaultdict(dict):
    clear: method_descriptor = <method 'clear' of 'dict' objects>
    copy: method_descriptor = <method 'copy' of 'collections.defaultdict' objects>
    default_factory: member_descriptor = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys: builtin_function_or_method = <built-in method fromkeys of type object at 0x702850e7d8>
    get: method_descriptor = <method 'get' of 'dict' objects>
    items: method_descriptor = <method 'items' of 'dict' objects>
    keys: method_descriptor = <method 'keys' of 'dict' objects>
    pop: method_descriptor = <method 'pop' of 'dict' objects>
    popitem: method_descriptor = <method 'popitem' of 'dict' objects>
    setdefault: method_descriptor = <method 'setdefault' of 'dict' objects>
    update: method_descriptor = <method 'update' of 'dict' objects>
    values: method_descriptor = <method 'values' of 'dict' objects>

class enum(object):
    name_to_values: dict = {}
    value_to_names: dict = {}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...


def EnsureSafeStr(s): ...
def FixPos(x): ...
def urlparse(url, scheme='', allow_fragments=True): ...

