# module: gclient.framework.util.memory_util

import MObject
import Timer

class MemoryManager(Singleton):
    def Destroy(): ...
    def OnDestroy(self): ...
    def SuggestEngineGC(self): ...
    def cancelTemporaryEngineGCTimer(self): ...
    @property
    def engine_gc_enabled(self): ...    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class Singleton(object):
    def Destroy(): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...


