# module: gclient.framework.util.shader_util

import GlobalData
import MConfig
import MEngine
import MLauncher
import MPlatform
import MRender
import Timer
import cPickle
import cconst
import collections
import consts
import copy
import functools
import hashlib
import os
import shader_const
import shutil
import six2
import sys
import time
import time_util
import traceback
import zlib

ExportPlatforms: list = [1, 6, 5, 3]
PROFILE_SIGNATURE: dict = {}
SHADER_CACHE_PROFILES: dict = {}

class EPlatform(enum):
    agc: int = 8
    dx11: int = 1
    dx12: int = 2
    es3: int = 5
    gl45: int = 4
    libgnm: int = 7
    metal: int = 6
    name_to_values: dict = {'offline': 0, 'dx11': 1, 'dx12': 2, 'vlk': 3, 'gl45': 4, 'es3': 5, 'metal': 6, 'libgnm': 7, 'agc': 8}
    offline: int = 0
    value_to_names: dict = {0: 'offline', 1: 'dx11', 2: 'dx12', 3: 'vlk', 4: 'gl45', 5: 'es3', 6: 'metal', 7: 'libgnm', 8: 'agc'}
    vlk: int = 3

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class PrecompileShaderManager(Singleton):
    _instance: PrecompileShaderManager = <PrecompileShaderManager(0x0x6f5396a250)>

    def ActiveCollect(self): ...
    def ActiveOnlineNotify(self): ...
    def ActivePrecompile(self): ...
    def CaptureScreen(self, ticket, delay): ...
    def CompileOlineAutoSaveTick(self): ...
    def Destroy(): ...
    def DoActivePrecompileHallCollection(self): ...
    def ExpandSGScopeShaderProfile(self): ...
    def ExpandShaderProfileFoliage(self): ...
    def ExpandShaderProfileWhenCollectEnd(self): ...
    def ExpandShaderProfileWhenHallCollectEnd(self): ...
    def GetGunSkinShaderProfileExpand(self, unexpanded, param_group): ...
    def GetSGScopeShaderProfileExpand(self, unexpanded): ...
    def GetShaderExpandProfiles(self, shader, tech, profile): ...
    def GetShaderProfileFoliageExpand(self, unexpanded): ...
    def LoadOnlineMissShaderCacheData(self): ...
    def OnCollectNotification(self, shader, tech, profile): ...
    def OnCompileOnlineNotification(self, shader, tech, profile): ...
    def OnDestroy(self): ...
    def OnPrecompileNext(self): ...
    def OnPrecompileNotification(self, shader, tech, profile): ...
    def OnPrecompileProgressNotification(self, progress): ...
    def OnSaveShaderCollection(self, expand_profiles): ...
    def PrecompileCategory(self, category, is_high_world): ...
    def PrecompileDeviceShaderNotification(self, progress): ...
    def PrecompileHallCollectionNext(self): ...
    def PrecompilePause(self): ...
    def SaveHallShaderCollection(self): ...
    def SaveOnlineMissShaderCacheRecord(self, data): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class ShaderMacros(enum):
    Billboard: int = 32
    CSMDynamic: int = 21
    Candela: int = 19
    CastSunShadow: int = 9
    Clipping: int = 26
    Debug0: int = 41
    Debug1: int = 42
    Debug2: int = 43
    Debug3: int = 44
    DeferredShading: int = 6
    Dissolving: int = 31
    ENCODEHDR: int = 8
    EShaderProfile_Skinning0: int = 24
    EShaderProfile_Skinning1: int = 25
    Emissive: int = 30
    EnvMapEnable: int = 16
    Feature0: int = 4
    Fog: int = 5
    HDR: int = 7
    Instanced: int = 40
    LightMap: int = 38
    LitCount0: int = 34
    LitCount1: int = 35
    LodLevel0: int = 22
    LodLevel1: int = 23
    NoFarPlaneClip: int = 28
    NoNearPlaneClip: int = 29
    Platform0: int = 0
    Platform1: int = 1
    Platform2: int = 2
    Platform3: int = 3
    ReceiveDynamicShadow: int = 33
    ReflectionMapEnable: int = 18
    Ripple: int = 14
    SSR: int = 17
    ShelterMapEnable: int = 15
    Tangent: int = 36
    Transparent: int = 27
    UV3UV4: int = 39
    VTEnable: int = 20
    VertexColor: int = 37
    VolumetricFog: int = 10
    Weather0: int = 12
    Weather1: int = 13
    _7MRT: int = 11
    name_to_values: dict = {'Platform0': 0, 'Platform1': 1, 'Platform2': 2, 'Platform3': 3, 'Feature0': 4, 'Fog': 5, 'DeferredShading': 6, 'HDR': 7, 'ENCODEHDR': 8, 'CastSunShadow': 9, 'VolumetricFog': 10, '_7MRT': 11, 'Weather0': 12, 'Weather1': 13, 'Ripple': 14, 'ShelterMapEnable': 15, 'EnvMapEnable': 16, 'SSR': 17, 'ReflectionMapEnable': 18, 'Candela': 19, 'VTEnable': 20, 'CSMDynamic': 21, 'LodLevel0': 22, 'LodLevel1': 23, 'EShaderProfile_Skinning0': 24, 'EShaderProfile_Skinning1': 25, 'Clipping': 26, 'Transparent': 27, 'NoFarPlaneClip': 28, 'NoNearPlaneClip': 29, 'Emissive': 30, 'Dissolving': 31, 'Billboard': 32, 'ReceiveDynamicShadow': 33, 'LitCount0': 34, 'LitCount1': 35, 'Tangent': 36, 'VertexColor': 37, 'LightMap': 38, 'UV3UV4': 39, 'Instanced': 40, 'Debug0': 41, 'Debug1': 42, 'Debug2': 43, 'Debug3': 44}
    value_to_names: dict = {0: 'Platform0', 1: 'Platform1', 2: 'Platform2', 3: 'Platform3', 4: 'Feature0', 5: 'Fog', 6: 'DeferredShading', 7: 'HDR', 8: 'ENCODEHDR', 9: 'CastSunShadow', 10: 'VolumetricFog', 11: '_7MRT', 12: 'Weather0', 13: 'Weather1', 14: 'Ripple', 15: 'ShelterMapEnable', 16: 'EnvMapEnable', 17: 'SSR', 18: 'ReflectionMapEnable', 19: 'Candela', 20: 'VTEnable', 21: 'CSMDynamic', 22: 'LodLevel0', 23: 'LodLevel1', 24: 'EShaderProfile_Skinning0', 25: 'EShaderProfile_Skinning1', 26: 'Clipping', 27: 'Transparent', 28: 'NoFarPlaneClip', 29: 'NoNearPlaneClip', 30: 'Emissive', 31: 'Dissolving', 32: 'Billboard', 33: 'ReceiveDynamicShadow', 34: 'LitCount0', 35: 'LitCount1', 36: 'Tangent', 37: 'VertexColor', 38: 'LightMap', 39: 'UV3UV4', 40: 'Instanced', 41: 'Debug0', 42: 'Debug1', 43: 'Debug2', 44: 'Debug3'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class Singleton(object):
    def Destroy(): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class defaultdict(dict):
    clear: method_descriptor = <method 'clear' of 'dict' objects>
    copy: method_descriptor = <method 'copy' of 'collections.defaultdict' objects>
    default_factory: member_descriptor = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys: builtin_function_or_method = <built-in method fromkeys of type object at 0x702850e7d8>
    get: method_descriptor = <method 'get' of 'dict' objects>
    items: method_descriptor = <method 'items' of 'dict' objects>
    keys: method_descriptor = <method 'keys' of 'dict' objects>
    pop: method_descriptor = <method 'pop' of 'dict' objects>
    popitem: method_descriptor = <method 'popitem' of 'dict' objects>
    setdefault: method_descriptor = <method 'setdefault' of 'dict' objects>
    update: method_descriptor = <method 'update' of 'dict' objects>
    values: method_descriptor = <method 'values' of 'dict' objects>

class enum(object):
    name_to_values: dict = {}
    value_to_names: dict = {}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...


def AnalyseShaderCacheMissRecords(records, write_path): ...
def BuildPrecompileShaderCollectionMessage(): ...
def CalMacroPercentInShader(shader_name, macro): ...
def CalMacroPercentInShaderCacheProfiles(query_cache_name, macro): ...
def CalculatePrecompileShaderHitPercent(): ...
def CompareFtpShaderCollectionWithPreCompileList(sort_key=5): ...
def CompareMacro(profile_miss, profile_precompile, miss_macro_dict, pre_compile_macro_dict): ...
def CompileAllPrecompileList(): ...
def DeleteRecordBaseOnPreCompileList(): ...
def DeleteShaderCacheMissRecords(send_file_paths): ...
def FindMostSimilarityShaderInPrecompileCollection(param_list, platform='es3', return_min_count=True): ...
def FindMostSimilarityShaderInPrecompileCollectionNew(profile_miss, shader_cache_query_key, return_min_count=True): ...
def FormatPrint(result): ...
def GenerateAllShaderProfilesCount(): ...
def GenerateShaderNameInShaderCache(): ...
def GetAllDevShaderInfoInPrecompileList(): ...
def GetAllSrcShaderInfoInPrecompileList(): ...
def GetFptFileFolder(): ...
def GetShaderMacroDict(shader, tech, profile): ...
def GetShaderStatistics(): ...
def IntegerToShaderProfileStr(integer): ...
def LoadAndFormatPrint(): ...
def LoadShaderCompareRecord(file_folder): ...
def PreCompileShaderWrapper(shader, tech, profile): ...
def ReadShaderCacheMissRecords(read_path): ...
def SaveShaderCacheMissRecords(shader_miss_records, category, spaceno, write_path): ...
def SendShaderCacheMissRecords(delete_file): ...
def ShaderProfileStrToBits(profile): ...
def ShaderProfileStrToInteger(profile): ...
def ViewShaderMacroInShaderCache(query_name, macro): ...
def ViewSrcShaderMacroInPrecompileList(macro): ...

