# module: gclient.gameplay.logic_base.entities.vehiclecomponents.vehicle_off_position_comp

import MObject
import MType
import cconst
import formula
import math
import time

EPS: float = 0.0001
_reload_all: bool = True

class VehicleOffPositionComp(object):
    def CheckResetPositionForUnderGroundWheels(self): ...
    def CheckWheelsUnderGround(self): ...
    def ClearDebugOffPosition(self): ...
    def GetOffPosition(self, seat, guarantee=False): ...
    def MakeOffPosFarther(self, pos): ...
    def _CancelWheelUnderGroundTimer(self): ...
    def _CheckPosValid(self, pos): ...
    def _GetOffPositionImp(self, pos): ...
    def _on_set_is_landed(self, old): ...


