# module: gclient.gameplay.logic_base.entities.vehiclecomponents.vehicle_graph_comp

import consts
import math
import time

EPS: float = 0.0001
Gravity: int = 10
WheelRotationPerTick: float = 0.011677282377919321
print_function: _Feature = _Feature((2, 6, 0, 'alpha', 2), (3, 0, 0, 'alpha', 0), 1048576)

class VehicleGraphComp(object):
    def EnableMotorHandIK(*args, **kwargs): ...
    def IsMotor(self): ...
    def TickLocalVehicleGraph(self, dt=0): ...
    def UpdateDriverGraphInfo(self): ...
    def UpdateMotorGraphInfoFromCCT(self, dt): ...


def AsyncTick(func): ...
def Lerp(a, b, t, clamp_t=False): ...

