# module: gclient.gameplay.logic_base.entities.vehiclecomponents.vehicle_helicopter_comp

import MType
import cconst
import consts
import effect_data
import events
import formula
import math
import random
import replay_util
import time

Gravity: int = 10
HELICOPTER_PICH: float = 0.08726646259971647
HELICOPTER_ROLL: float = 0.08726646259971647

class VehicleHelicopterComp(object):
    def CancelHelicopterFlyingTimer(self): ...
    def CheckHelicopterTimer(self): ...
    def CheckLanded(self, old_is_start): ...
    def CheckShowHelicopterPropellerModels(self): ...
    def ClearDriveVal(self): ...
    def DoRise(self, v): ...
    def FixHelecopterTurnOver(self): ...
    def GetHelicopterHeightDiff(self): ...
    def GetHelicopterRPM(self): ...
    def HelicopterUpdateCode(self): ...
    def IsBroomUpCollision(self): ...
    def RefreshHelicopterForwardSpeed(self): ...
    def RefreshHelicopterRotation(self): ...
    def RefreshHelicopterSideSpeed(self): ...
    def RefreshHelicopterUpSpeed(self): ...
    def SetHelicopterScrew(self): ...
    def SetVehicleForce(self, force): ...
    def SetVehicleTorque(self, torque): ...
    def _CheckFlyingAction(self): ...
    def _GetHelicopterProto(self): ...
    def _HelicopterForwardType(self, v): ...
    def _HelicopterTurningType(self, v): ...
    def _InitHelicopterData(self): ...
    def _SetHelicopterDownForce(self): ...
    def _SetHelicopterForceDown(self): ...
    def _SetHelicopterRemainHeightForce(self): ...
    def _SetHelicopterSyncInfo(self, steer_angle): ...
    def _SetHelicopterUpForce(self): ...


