# module: gclient.framework.entities.account

import GlobalData
import MConfig
import MPlatform
import channel_util
import consts
import events
import lang
import sdk_define
import socket
import ui_define

CLIENT_STUB: int = 8
LocalConfig: _LocalConfig = <gclient.config._LocalConfig object at 0x7040bf6d50>

class Account(AvatarEntity):
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = False
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    Space: EntityMetaClass = <class 'gclient.framework.entities.space.Space'>
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    logger: Logger = <Logger Account (DEBUG)>

    def CheckHotfix(self, md5s): ...
    def CheckHotfixGraphs(self, graph_md5): ...
    def ClientRelayPrompt(self, is_emulator): ...
    def CreateAvatar(self): ...
    def CreateNewAvatar(self, name, extra=None): ...
    def Hotfix(self, tag, md5, content): ...
    def HotfixData(self, hotfix): ...
    def HotfixGraphs(self, md5, content): ...
    def NotifyDuplicateName(self): ...
    def OnAuthLogin(self, unisdk_login_json): ...
    def OnLoginTimeout(self): ...
    def OnLogout(self, _type, extra): ...
    def OnRandomName(self, name): ...
    def OnServerTraceback(self, trace): ...
    def ReplaceWansterDataLang(self, val): ...
    def RequestBackpack(self): ...
    def RequestRandomName(self, gender): ...
    def SaveHotfixToConfig(self, tag, md5, encodestr): ...
    def UpdateLoginQueue(self, waiting_num, num_pertick, tick_interval, is_tick, is_update): ...
    def _UpdateOneActData(self, data_name, act_data): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _prepare_spectate(self, spaceno, spaceid, actorid): ...
    def _tickComponents(self, dtime): ...
    def _write_wanst_data_to_file(self, data_name, act_data): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def become_player(self): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def doHotfix(self, tag, md5, encodestr): ...
    def doHotfix_wanster(self, md5, hotfix): ...
    def enter_world(self, entity): ...
    def entity_method(self, md5, index, args): ...
    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    def is_deactived(self): ...
    def is_destroyed(self): ...
    def onEntityClassRegistered(): ...
    def on_be_relayed(self): ...
    def on_become_player(self): ...
    def on_clear_space_center(self): ...
    def on_del_space_data(self, key): ...
    def on_dist_aoi_enter(self, daois): ...
    def on_ent_out_sight(self, guid): ...
    def on_enter_space(self): ...
    def on_enter_world_level(self, spaceno, worldid, levelno, position, direction): ...
    def on_leave_space(self): ...
    def on_leave_world_level(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_relay_to(self, clientid, ip, port, entityid, reconnectkey, ipv6=''): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_spectator_leaved(self, actorid): ...
    def on_speed(self, speed): ...
    def on_teleport_in(self, spaceno, spaceid, position, direction): ...
    def on_teleport_out(self, dest): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def pos(self): ...    @property
    def position_uploader(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    def update_reconnectkey(self, reconnectkey): ...
    @property
    def yaw(self): ...
class AvatarEntity(PlayerEntity, ClientAreaEntity):
    Space: EntityMetaClass = <class 'gclient.framework.entities.space.Space'>
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    logger: Logger = <Logger AvatarEntity (DEBUG)>

    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _prepare_spectate(self, spaceno, spaceid, actorid): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def become_player(self): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def enter_world(self, entity): ...
    def entity_method(self, md5, index, args): ...
    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    def is_deactived(self): ...
    def is_destroyed(self): ...
    def onEntityClassRegistered(): ...
    def on_be_relayed(self): ...
    def on_become_player(self): ...
    def on_clear_space_center(self): ...
    def on_del_space_data(self, key): ...
    def on_dist_aoi_enter(self, daois): ...
    def on_ent_out_sight(self, guid): ...
    def on_enter_space(self): ...
    def on_enter_world_level(self, spaceno, worldid, levelno, position, direction): ...
    def on_leave_space(self): ...
    def on_leave_world_level(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_relay_to(self, clientid, ip, port, entityid, reconnectkey, ipv6='', vginfo=''): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_spectator_leaved(self, actorid): ...
    def on_speed(self, speed): ...
    def on_teleport_in(self, spaceno, spaceid, position, direction): ...
    def on_teleport_out(self, dest): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def pos(self): ...    @property
    def position_uploader(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    def update_reconnectkey(self, reconnectkey): ...
    @property
    def yaw(self): ...
class BinData(object):
    convert: method_descriptor = <method 'convert' of 'bin' objects>
    get_type: method_descriptor = <method 'get_type' of 'bin' objects>
    getname: method_descriptor = <method 'getname' of 'bin' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'bin' objects>
    name: getset_descriptor = <attribute 'name' of 'bin' objects>

class Bool(object):
    convert: method_descriptor = <method 'convert' of 'bool' objects>
    get_type: method_descriptor = <method 'get_type' of 'bool' objects>
    getname: method_descriptor = <method 'getname' of 'bool' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'bool' objects>
    name: getset_descriptor = <attribute 'name' of 'bool' objects>

class EntityID(object):
    convert: method_descriptor = <method 'convert' of 'entityid' objects>
    get_type: method_descriptor = <method 'get_type' of 'entityid' objects>
    getname: method_descriptor = <method 'getname' of 'entityid' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'entityid' objects>
    name: getset_descriptor = <attribute 'name' of 'entityid' objects>

class Float(object):
    convert: method_descriptor = <method 'convert' of 'float' objects>
    get_type: method_descriptor = <method 'get_type' of 'float' objects>
    getname: method_descriptor = <method 'getname' of 'float' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'float' objects>
    name: getset_descriptor = <attribute 'name' of 'float' objects>

class HotfixComponent(object):
    def CheckHotfix(self, md5s): ...
    def CheckHotfixGraphs(self, graph_md5): ...
    def Hotfix(self, tag, md5, content): ...
    def HotfixData(self, hotfix): ...
    def HotfixGraphs(self, md5, content): ...
    def ReplaceWansterDataLang(self, val): ...
    def RequestBackpack(self): ...
    def SaveHotfixToConfig(self, tag, md5, encodestr): ...
    def _UpdateOneActData(self, data_name, act_data): ...
    def _write_wanst_data_to_file(self, data_name, act_data): ...
    def doHotfix(self, tag, md5, encodestr): ...
    def doHotfix_wanster(self, md5, hotfix): ...

class Int(object):
    convert: method_descriptor = <method 'convert' of 'int' objects>
    get_type: method_descriptor = <method 'get_type' of 'int' objects>
    getname: method_descriptor = <method 'getname' of 'int' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'int' objects>
    name: getset_descriptor = <attribute 'name' of 'int' objects>

class Str(object):
    convert: method_descriptor = <method 'convert' of 'str' objects>
    get_type: method_descriptor = <method 'get_type' of 'str' objects>
    getname: method_descriptor = <method 'getname' of 'str' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'str' objects>
    name: getset_descriptor = <attribute 'name' of 'str' objects>


def Components(*components, **kwargs): ...
def Property(name, default, flag=2): ...
def rpc_method(rpctype, *types): ...
def with_tag(*args): ...

