# module: gclient.framework.entities.camera

import MEngine
import MHelper
import MObject
import MType
import camera_data
import cconst
import consts
import events
import formula
import replay_util
import six2
import sys

BLEND_TYPE: dict = {'easeInSine': 1, 'easeOutSine': 2, 'easeInCubic': 3, 'easeOutCubic': 4, 'easeInQuad': 5, 'easeOutQuad': 6, 'easeInQuint': 7, 'easeOutQuint': 8, 'easeInExpo': 9, 'easeOutExpo': 10, 'easeInCirc': 11, 'easeOutCirc': 12}

class ALSTpsPlacer(EnginePlacer):
    NAME: str = 'GraphRotate'
    Placers: dict = {}

    def ApplyCameraEasing(self): ...
    def ApplyMover(self, beginTargetPosOffset, endTargetPosOffset, beginDirection, endDirection, movetime=0.5, callback=None): ...
    def BlenderInFinished(self): ...
    def CheckCanJitter(self): ...
    def CreateBlender(self, blendTime=None, blend_type=0, direct_transit=True): ...
    def DelayRestoreUseBonePosition(self): ...
    def DisableStoryTick(self): ...
    def EnableBoneFollow(self, enable, bone_name='HP_Camera'): ...
    def EnableBreatheJitter(self, enable=True): ...
    def EnablePersistRecoilRecover(self, enable=True): ...
    def EnableStoryTick(self): ...
    def FSMAppend(self, state, replace, *args, **kwargs): ...
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMClear(self): ...
    def FSMEvent(self, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMRemove(self, state): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...
    def FetchPrePlacerInfo(self): ...
    def FinishExposeProperties(self): ...
    def FixTickTime(self, last_time, cur_time, target_time): ...
    def GetAllPlacerTypes(): ...
    def GetPlacerType(name): ...
    def GraphRotate(self): ...
    def IsValid(self): ...
    def LookAtTargetDirection(self, target_direction, target_pos_offset, use_time=0, callback=None): ...
    @property
    def MainFov(self): ...    @property
    def MainFovTarget(self): ...    def OnActive(self, info=None): ...
    def OnAffiliatedFovEasingFinished(self, easeTime, easeType): ...
    def OnAimEnter(self, is_aim=True, zoom_affiliated=True): ...
    def OnAimEvent(self, event): ...
    def OnBurstShakeEnter(self, initAmplitude_list=None, duration_list=None): ...
    def OnBurstShakeExit(self): ...
    def OnBurstShakePitchTick(self): ...
    def OnBurstShakeRollTick(self): ...
    def OnBurstShakeTick(self): ...
    def OnBurstShakeYawTick(self): ...
    def OnDeactive(self): ...
    def OnFovEasingFinished(self, easeTime, easeType): ...
    def OnGraphRotateCallback(self, easeTime, easeType): ...
    def OnGraphRotateEnter(self, target_pitch=None, target_yaw=None, graphRotateEasingType='linear', duration=0.0): ...
    def OnGraphRotateExit(self): ...
    def OnJitterEnter(self): ...
    def OnJitterExit(self): ...
    def OnJitterTick(self): ...
    def OnRecoilDownCallback(self, easeTime, easeType): ...
    def OnRecoilEnter(self, shoot_idx=0): ...
    def OnRecoilExit(self): ...
    def OnRecoilFallCallback(self, easeTime, easeType): ...
    def OnRecoilRecoverCallback(self, easeTime, easeType): ...
    def OnRecoilRecoverEnter(self, shoot_idx=0): ...
    def OnRecoilRecoverExit(self): ...
    def OnRecoilStaticCallback(self, easeTime, easeType): ...
    def OnRecoilUpCallback(self, easeTime, easeType): ...
    def OnRollShakeEnter(self, shoot_idx=0): ...
    def OnRollShakeExit(self): ...
    def OnRollShakeTick(self): ...
    def OnStaticEnter(self): ...
    def OnStaticExit(self): ...
    def OnStaticTick(self): ...
    def OnStoryTick(self, dtime): ...
    def OnZoomAffiliatedFov(self): ...
    def OnZoomFov(self): ...
    def RecoilDown(self): ...
    def RecoilFall(self): ...
    def RecoilStatic(self): ...
    def RecoilUp(self): ...
    def RefreshConfig(self, config=None): ...
    def RefreshFocusWeaponCase(self, weapon_case): ...
    def RefreshMainFovTarget(self): ...
    def RefreshRealRollShakeInfo(self, shoot_idx): ...
    def Rotate(self, yaw, pitch): ...
    def RotateTo(self, yaw, pitch): ...
    def SetAffiliatedFov(self, value): ...
    def SetBoneFollowTarget(self, animTarget): ...
    def SetFocusTarget(self, target): ...
    def SetFocusWeaponCase(self, weapon_case): ...
    def ShowRecoilDebug(self, cur_shoot_idx, cur_shoot_recoil_pitch, cur_shoot_recoil_yaw, cur_shoot_recoil_base_pitch, cur_shoot_recoil_base_yaw, cur_shoot_recoil_random_pitch, cur_shoot_recoil_random_yaw): ...
    def StartAssistAimShoot(self): ...
    def StartExposeProperties(self): ...
    def StorePrePlacerInfo(self): ...
    def TurnView(self, diffx, diffy, shoot_adsorb=False): ...
    def TurnViewBegin(self): ...
    def TurnViewEnd(self): ...
    def UseBonePosition(self, is_use, bone_name='Scene Root'): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_set_RecoilDownCycleIdx(self, value): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def debug_enabled(self): ...    @property
    def target(self): ...
class BasePlacer(object):
    Placers: dict = {}

    def DisableStoryTick(self): ...
    def EnableStoryTick(self): ...
    def GetAllPlacerTypes(): ...
    def GetPlacerType(name): ...
    def IsValid(self): ...
    def OnActive(self, info=None): ...
    def OnDeactive(self): ...
    def OnStoryTick(self, dtime): ...
    def RefreshConfig(self, config=None): ...
    def SetFocusTarget(self, target): ...
    @property
    def debug_enabled(self): ...    @property
    def target(self): ...
class Camera(object):
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = False
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False

    def ApplyCamera(self, camera_id, info=None): ...
    def Attach(self): ...
    def ConfigALSTpsPlacer(self, info=None): ...
    def ConfigAimPlacer(self): ...
    def ConfigDeadFollowPlacer(self): ...
    def ConfigEmoteTpsPlacer(self): ...
    def ConfigFollowPlacer(self): ...
    def ConfigFpsPlacer(self, info=None): ...
    def ConfigFreeviewPlacer(self): ...
    def ConfigGunSmithAimPlacer(self): ...
    def ConfigHildaAimPlacer(self): ...
    def ConfigHildaFollowPlacer(self): ...
    def ConfigReplayAimPlacer(self): ...
    def ConfigReplayPlacer(self): ...
    def ConfigTpsPlacer(self, info=None): ...
    def CreateCollider(self): ...
    def CreateController(self): ...
    def CreateShaker(self): ...
    def Detach(self, delay_leave_world=0): ...
    def DetachController(self, delay_leave_world): ...
    def EnsureEnterArea(self): ...
    def EnterCameraIdForLookAround(self, camera_id): ...
    def EnterLookAround(self): ...
    def ExitLookAround(self): ...
    def FetchPrePlacerInfo(self): ...
    def GetReplayCameraMode(self): ...
    def InitController(self): ...
    def LoadFromData(self, data): ...
    def NotifyPlacer(self, event, *args): ...
    def ReadyBy(self, info=None): ...
    def RefreshConfig(self, config=None): ...
    def RefreshNearAndFar(self, near=None, far=None): ...
    def RefreshPoseType(self, pose_type): ...
    def ResetTransform(self, pitch, yaw, roll, translation): ...
    def ResetTransformWithFocus(self, target_pos, direction): ...
    def RestoreCamera(self, need_blender=False): ...
    def SetAimCamera(self, is_aim): ...
    def SetColliderOffset(self, target_pos_offset): ...
    def SetFocusTarget(self, target): ...
    def SetFpsCameraForHall(self): ...
    def SetFreeviewCameraForHall(self): ...
    def SetPlacer(self, placer, info=None): ...
    def SetReplayMode(self, mode): ...
    def SetSpecialPlacerTarget(self): ...
    def SetTpsModelVisible(self, flag): ...
    def StandBy(self): ...
    def StorePrePlacerInfo(self): ...
    def UpdateSpecialPlacerTarget(self, target): ...
    def _UseSpecialPlacer(self, placer_name, info=None): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def destroy(self): ...
    @property
    def enableCollider(self): ...    @property
    def engine_camera(self): ...    @property
    def is_fps_placer(self): ...    @property
    def is_free_placer(self): ...    @property
    def is_gunsmith_placer(self): ...    @property
    def is_look_around(self): ...    @property
    def is_parachute_placer(self): ...    @property
    def is_tfps_placer(self): ...    @property
    def is_tps_placer(self): ...    @property
    def position(self): ...    @property
    def position_tuple(self): ...    @property
    def pre_direction(self): ...    def shake(self, type, amplitude, duration, decaycoeff, loopcount, force=False): ...
    def shakeLoop(self, amplitude, duration, loopcount): ...
    def shakePulse(self, amplitude, duration, decaycoeff): ...
    def stopShake(self): ...

class CameraMeta(ClassMeta):
    CLASS_NAME: str = 'Camera'
    COMPONENTIZED: bool = False
    COMPONENT_META_TYPE: NoneType = None
    CREATE_FROM_SPACE: bool = True
    EDITOR_ATTRIBUTES: dict = {}
    META_TYPE: str = 'Class'
    OBJECT_VISITOR: NoneType = None
    PROPERTIES: dict = {'ConfigAimPlacer': <SunshineSDK.Meta.TypeMeta.PButton object at 0x6fa5125550>, 'ConfigHildaAimPlacer': <SunshineSDK.Meta.TypeMeta.PButton object at 0x6fa5125410>, 'ConfigHildaFollowPlacer': <SunshineSDK.Meta.TypeMeta.PButton object at 0x6fa5125390>, 'ConfigFollowPlacer': <SunshineSDK.Meta.TypeMeta.PButton object at 0x6fa5125250>, 'ConfigFpsPlacer': <SunshineSDK.Meta.TypeMeta.PButton object at 0x6fa5125a50>, 'ConfigFromData': <SunshineSDK.Meta.TypeMeta.PButton object at 0x6fa5125090>, 'position': <SunshineSDK.Custom.Editor.EditorMeta.MessiahMeta.MVector3 object at 0x6fa5125050>, 'placer': <SunshineSDK.Meta.TypeMeta.PObject object at 0x6fa5124e90>}
    VALID_EDIT_TYPES: list = ['Object', 'Unknown']

    def CreateChildObject(self, obj, key, extValue=None, partialUpdate=False): ...
    def DelChildObject(self, obj, key): ...
    def DeserializeData(self, value): ...
    def FromDict(data): ...
    def GetAllProperties(self): ...
    def GetChildMeta(self, obj, key): ...
    def GetChildObject(self, obj, key): ...
    def GetChildrenCount(self, obj): ...
    def GetComponentMeta(self, obj): ...
    def GetDefault(self): ...
    def GetDynamicEditorMeta(self, obj, bindObject=None): ...
    def GetEditType(self): ...
    def GetEditorMeta(self): ...
    def GetKeys(self, obj): ...
    def InsertRawChildObject(self, obj, key, childObj): ...
    def SerializeData(self, obj): ...
    def SetChildObject(self, obj, key, value): ...
    def SetRawChildObject(self, obj, key, childObj): ...
    def SetValue(self, parent, parentMeta, key, value): ...
    def UpdateExtraMeta(self, extraMeta): ...
    def _CreateEditorMeta(self, **kwargs): ...
    def _GetValidChildObject(self, obj, key): ...
    def _IsValidObject(self, obj): ...
    def _WarnOnNoneCollectionData(obj, childMeta, key): ...

class CameraMode(enum):
    AIM: int = 3
    ALTPS: int = 2
    CAMCTRL: int = 6
    DEATH: int = 4
    EMOTE: int = 7
    FPS: int = 1
    FREE: int = 5
    REPLAY: int = 8
    TPS: int = 0
    name_to_values: dict = {'TPS': 0, 'FPS': 1, 'ALTPS': 2, 'AIM': 3, 'DEATH': 4, 'FREE': 5, 'CAMCTRL': 6, 'EMOTE': 7, 'REPLAY': 8}
    value_to_names: dict = {0: 'TPS', 1: 'FPS', 2: 'ALTPS', 3: 'AIM', 4: 'DEATH', 5: 'FREE', 6: 'CAMCTRL', 7: 'EMOTE', 8: 'REPLAY'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class CameraSunshineComponent(SunshineComponent):
    def OnCreateInSunshine(self, meta, data): ...
    def OnRefreshBySunshine(self): ...
    def OnRemoveInSunshine(self): ...
    def OnSelectedInSunshine(self): ...
    def OnSunshinePropertyAdded(self, name, value): ...
    def OnSunshinePropertyChanged(self, name, value): ...
    def OnSunshinePropertyDeleted(self, name): ...
    def OnUnselectedInSunshine(self): ...
    def TryRefreshBySunshine(self): ...
    @property
    def rainbowPlugin(self): ...    @property
    def sunshine(self): ...
class ClientAreaEntity(ClientEntity):
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    logger: Logger = <Logger ClientAreaEntity (DEBUG)>

    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    def is_deactived(self): ...
    def is_destroyed(self): ...
    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def pos(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    @property
    def yaw(self): ...
class FpsPlacer(EnginePlacer):
    NAME: str = 'GraphRotate'
    Placers: dict = {}

    def ApplyCameraEasing(self): ...
    def ApplyMover(self, beginTargetPosOffset, endTargetPosOffset, beginDirection, endDirection, movetime=0.5, callback=None): ...
    def BlenderInFinished(self): ...
    def CheckCanJitter(self): ...
    def ClearReloadFovOffset(self): ...
    def CreateBlender(self, blendTime=None, blend_type=0, direct_transit=True): ...
    def DelayRestoreUseBonePosition(self): ...
    def DisableStoryTick(self): ...
    def DisableStoryTickForReplay(self): ...
    def EnableAdditiveFovOffset(self, enable): ...
    def EnableAnimationBoneOffset(self, enable): ...
    def EnableBoneFollow(self, enable, bone_name='HP_Camera'): ...
    def EnableBreatheJitter(self, enable=True): ...
    def EnablePersistRecoilRecover(self, enable=True): ...
    def EnableStoryTick(self): ...
    def EnableStoryTickForReplay(self): ...
    def FSMAppend(self, state, replace, *args, **kwargs): ...
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMClear(self): ...
    def FSMEvent(self, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMRemove(self, state): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...
    def FetchPrePlacerInfo(self): ...
    def FinishExposeProperties(self): ...
    def FixTickTime(self, last_time, cur_time, target_time): ...
    def GetAllPlacerTypes(): ...
    def GetPlacerType(name): ...
    def GraphRotate(self): ...
    def InitDebugDraw(self): ...
    def InitParameter(self): ...
    def IsValid(self): ...
    def LookAtTargetDirection(self, target_direction, pos_offset, use_time=0, callback=None): ...
    @property
    def MainFov(self): ...    @property
    def MainFovTarget(self): ...    def OnActive(self, info=None): ...
    def OnAdditiveAffiliatedFovOffsetEasingFinished(self, easeTime, easeType): ...
    def OnAdditiveFovOffsetEasingFinished(self, easeTime, easeType): ...
    def OnAffiliatedFovEasingFinished(self, easeTime, easeType): ...
    def OnAimEnter(self, is_aim=True, zoom_affiliated=True): ...
    def OnAimEvent(self, event): ...
    def OnBurstShakeEnter(self, initAmplitude_list=None, duration_list=None): ...
    def OnBurstShakeExit(self): ...
    def OnBurstShakePitchTick(self): ...
    def OnBurstShakeRollTick(self): ...
    def OnBurstShakeTick(self): ...
    def OnBurstShakeYawTick(self): ...
    def OnDeactive(self): ...
    def OnFovEasingFinished(self, easeTime, easeType): ...
    def OnGraphRotateCallback(self, easeTime, easeType): ...
    def OnGraphRotateEnter(self, target_pitch=None, target_yaw=None, graphRotateEasingType='linear', duration=0.0): ...
    def OnGraphRotateExit(self): ...
    def OnJitterEnter(self): ...
    def OnJitterExit(self): ...
    def OnJitterTick(self): ...
    def OnPlacerExpired(self, ientity): ...
    def OnRecoilDownCallback(self, easeTime, easeType): ...
    def OnRecoilEnter(self, shoot_idx=0): ...
    def OnRecoilExit(self): ...
    def OnRecoilFallCallback(self, easeTime, easeType): ...
    def OnRecoilRecoverCallback(self, easeTime, easeType): ...
    def OnRecoilRecoverEnter(self, shoot_idx=0): ...
    def OnRecoilRecoverExit(self): ...
    def OnRecoilStaticCallback(self, easeTime, easeType): ...
    def OnRecoilUpCallback(self, easeTime, easeType): ...
    def OnRefreshPitchMaxMinCallback(self, easeTime, easeType): ...
    def OnReloadAimEnter(self, is_reload_aim=False): ...
    def OnRollShakeEnter(self, shoot_idx=0): ...
    def OnRollShakeExit(self): ...
    def OnRollShakeTick(self): ...
    def OnStaticEnter(self): ...
    def OnStaticExit(self): ...
    def OnStaticTick(self): ...
    def OnStoryTick(self, dtime): ...
    def OnStoryTickForReplay(self, dtime): ...
    def OnUpdateBoneOffset(self): ...
    def OnZoomAdditiveAffiliatedFov(self): ...
    def OnZoomAdditiveFov(self): ...
    def OnZoomAffiliatedFov(self): ...
    def OnZoomFov(self): ...
    def PlotFrameTick(self): ...
    def RecoilDown(self): ...
    def RecoilFall(self): ...
    def RecoilStatic(self): ...
    def RecoilUp(self): ...
    def RefreshConfig(self, config=None): ...
    def RefreshDirectionByMaster(self): ...
    def RefreshFocusWeaponCase(self, weapon_case): ...
    def RefreshMainFovTarget(self): ...
    def RefreshPitchMaxMin(self): ...
    def RefreshRealRollShakeInfo(self, shoot_idx): ...
    def Rotate(self, yaw, pitch): ...
    def RotateTo(self, yaw, pitch, rotate_target=True): ...
    def SetAffiliatedFov(self, value): ...
    def SetBoneFollowTarget(self, animTarget): ...
    def SetFocusTarget(self, target): ...
    def SetFocusWeaponCase(self, weapon_case): ...
    def ShowRecoilDebug(self, cur_shoot_idx, cur_shoot_recoil_pitch, cur_shoot_recoil_yaw, cur_shoot_recoil_base_pitch, cur_shoot_recoil_base_yaw, cur_shoot_recoil_random_pitch, cur_shoot_recoil_random_yaw): ...
    def StartAssistAimShoot(self): ...
    def StartExposeProperties(self): ...
    def StorePrePlacerInfo(self): ...
    def TurnView(self, diffx, diffy, shoot_adsorb=False): ...
    def TurnViewBegin(self): ...
    def TurnViewEnd(self): ...
    def UseBonePosition(self, is_use, bone_name='Scene Root'): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_set_RecoilDownCycleIdx(self, value): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def debug_enabled(self): ...    @property
    def target(self): ...
class FreeviewPlacer(EnginePlacer):
    Placers: dict = {}

    def BlenderInFinished(self): ...
    def CreateBlender(self, blendTime=None, blend_type=0, direct_transit=True): ...
    def DelayRestoreUseBonePosition(self): ...
    def DisableStoryTick(self): ...
    def EnableStoryTick(self): ...
    def FinishExposeProperties(self): ...
    def GetAllPlacerTypes(): ...
    def GetPlacerType(name): ...
    def IsValid(self): ...
    def MoveToPosAndRot(self, cam_pos, cam_rot, focus_len=1, half_life=0.05): ...
    def OnActive(self, info=None): ...
    def OnDeactive(self): ...
    def OnStoryTick(self, dtime): ...
    def RefreshConfig(self, config=None): ...
    def RefreshHalflife(self, focus_halflife, direction_halflife): ...
    def ResetTransform(self, focusPos, direction, zoom=1.0): ...
    def ResetTransformByCamPosAndRot(self, cam_pos, cam_rot, focus_len=1): ...
    def SetCameraFocusDistance(self, distance): ...
    def SetFocusTarget(self, target): ...
    def SetFov(self, fov): ...
    def StartExposeProperties(self): ...
    def TurnView(self, diffx, diffy, shoot_adsorb=False): ...
    def TurnViewBegin(self): ...
    def TurnViewEnd(self): ...
    def UseBonePosition(self, is_use, bone_name='Scene Root'): ...
    @property
    def debug_enabled(self): ...    @property
    def target(self): ...
class GunSmithAimPlacer(EnginePlacer):
    Placers: dict = {}

    def BlenderInFinished(self): ...
    def CreateBlender(self, blendTime=None, blend_type=0, direct_transit=True): ...
    def DelayRestoreUseBonePosition(self): ...
    def DisableStoryTick(self): ...
    def EnableStoryTick(self): ...
    def FinishExposeProperties(self): ...
    def FocusTo(self, focus_pos, direction, zoom=1.0): ...
    def GetAllPlacerTypes(): ...
    def GetPlacerType(name): ...
    def IsValid(self): ...
    def OnActive(self, info=None): ...
    def OnDeactive(self): ...
    def OnStoryTick(self, dtime): ...
    def RefreshConfig(self, config=None): ...
    def RefreshHalflife(self, focus_halflife, direction_halflife): ...
    def SetFocusTarget(self, target): ...
    def StartExposeProperties(self): ...
    def TurnView(self, diffx, diffy, shoot_adsorb=False): ...
    def TurnViewBegin(self): ...
    def TurnViewEnd(self): ...
    def UseBonePosition(self, is_use, bone_name='Scene Root'): ...
    @property
    def debug_enabled(self): ...    @property
    def target(self): ...
class LookAroundPlacer(EnginePlacer):
    Placers: dict = {}

    def BlenderInFinished(self): ...
    def CreateBlender(self, blendTime=None, blend_type=0, direct_transit=True): ...
    def DelayRestoreUseBonePosition(self): ...
    def DisableStoryTick(self): ...
    def EnableStoryTick(self): ...
    def FinishExposeProperties(self): ...
    def GetAllPlacerTypes(): ...
    def GetMoverTargetParams(self, to_fps): ...
    def GetPlacerType(name): ...
    def IsValid(self): ...
    def OnActive(self, info=None): ...
    def OnDeactive(self): ...
    def OnStoryTick(self, dtime): ...
    def RefreshConfig(self, config=None): ...
    def SetFocusTarget(self, target): ...
    def SetToDirection(self, direction): ...
    def StartExposeProperties(self): ...
    def SwitchToFpsPlacer(self): ...
    def TurnView(self, diffx, diffy, shoot_adsorb=False): ...
    def TurnViewBegin(self): ...
    def TurnViewEnd(self): ...
    def UseBonePosition(self, is_use, bone_name='Scene Root'): ...
    def _moverCallback(self): ...
    def _moverFpsCallback(self): ...
    @property
    def debug_enabled(self): ...    @property
    def target(self): ...
class ParachutePlacer(EnginePlacer):
    Placers: dict = {}

    def BlenderInFinished(self): ...
    def CreateBlender(self, blendTime=None, blend_type=0, direct_transit=True): ...
    def DelayRestoreUseBonePosition(self): ...
    def DisableStoryTick(self): ...
    def EnableStoryTick(self): ...
    def FinishExposeProperties(self): ...
    def GetAllPlacerTypes(): ...
    def GetCameraStoreInfo(self): ...
    def GetPlacerType(name): ...
    def IsValid(self): ...
    def OnActive(self, info=None): ...
    def OnDeactive(self): ...
    def OnShakeDirection(self): ...
    def OnStoryTick(self, dtime): ...
    def RefreshConfig(self, config=None): ...
    def SetFocusTarget(self, target): ...
    def StartExposeProperties(self): ...
    def TurnView(self, diffx, diffy, shoot_adsorb=False): ...
    def TurnViewBegin(self): ...
    def TurnViewEnd(self): ...
    def UseBonePosition(self, is_use, bone_name='Scene Root'): ...
    def _CancelDelayStoryTickTimer(self): ...
    @property
    def debug_enabled(self): ...    @property
    def target(self): ...
class ReplayDummy(ClientAreaEntity):
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = False
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    logger: Logger = <Logger ReplayDummy (DEBUG)>

    def ShowModel(self): ...
    def SyncCamera(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    def is_deactived(self): ...
    def is_destroyed(self): ...
    @property
    def is_replaying(self): ...    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def pos(self): ...    @property
    def position(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    @property
    def yaw(self): ...
class SunshineComponent(object):
    def OnCreateInSunshine(self, meta, data): ...
    def OnRemoveInSunshine(self): ...
    def OnSelectedInSunshine(self): ...
    def OnSunshinePropertyAdded(self, name, vals): ...
    def OnSunshinePropertyChanged(self, name, value): ...
    def OnSunshinePropertyDeleted(self, name): ...
    def OnUnselectedInSunshine(self): ...
    @property
    def rainbowPlugin(self): ...    @property
    def sunshine(self): ...

def Components(*components, **kwargs): ...
def UpdateObject(obj, meta, data, partialUpdate=False): ...
def with_tag(*args): ...

