# module: gclient.gamesystem.uisettingnew.setting_template_basic_window

import events
import six2

CLOUD_SETTING_CONFIG_DICT: dict = {1: ['is_show_lfire_simple', 'fire_mode_simple', 'trigger_ads_mode_simple', 'is_auto_fire', 'is_show_prone', 'fire_mode', 'trigger_ads_mode', 'is_show_lfire', 'lfire_mode', 'AR_fire_mode', 'AR_lfire_mode', 'SMG_fire_mode', 'SMG_lfire_mode', 'SR_fire_mode', 'SR_lfire_mode', 'SG_fire_mode', 'SG_lfire_mode', 'PT_fire_mode', 'PT_lfire_mode', 'RL_fire_mode', 'RL_lfire_mode', 'fire_mode_diy', 'assistaim_config_mode', 'is_turnview_by_lfire', 'is_turnview_by_rfire', 'is_turnview_by_ads', 'is_break_ads_by_reload', 'is_advance_basic_setting', 'is_quick_spell', 'gun_selected_record', 'use_quick_airdrop'], 2: ['can_auto_move', 'crouch_way', 'rush_break_crouch', 'supersprint_break_reload', 'auto_open_door', 'auto_mark_enemy', 'auto_mark_item', 'ammo_lack_alert', 'sound_notice_mode', 'need_medicine_recommended', 'need_airdrop_recommended', 'continuous_use_medicine', 'hit_notice_mode', 'continuous_throw', 'is_quick_throw', 'injured_close_picklist', 'airdrop_setting_publish', 'is_auto_pickup', 'auto_pickup_interval', 'is_auto_docking', 'mini_map_scale', 'is_jump_to_strop', 'auto_supersprint', 'is_turnview_by_jump', 'auto_pick_up_enemy', 'pc_old_pick_up', 'use_default_hit_effect', 'auto_pickup_3', 'auto_pickup_4', 'auto_pickup_9', 'auto_pickup_20', 'auto_pickup_218', 'auto_pickup_46', 'auto_pickup_47', 'auto_pickup_220'], 3: ['moba_main_ui_version', 'operation_move_turn_rfire_mode', 'operation_move_mode', 'operation_rfire_mode', 'moba_drive_mode', 'auto_restore_camera_for_passenger', 'auto_restore_camera_for_driver', 'hotspot_main_ui_version', 'hotspot_operation_move_turn_rfire_mode', 'hotspot_operation_move_mode', 'hotspot_operation_rfire_mode'], 5: ['moba_user_define_plan_names', 'show_btn_switchover_v1'], 6: ['moba_v2_user_define_plan_names', 'throw_expand_direction', 'med_expand_direction', 'show_btn_reload_version_2', 'show_btn_switchover_v2'], 7: ['moba_user_define0'], 8: ['moba_user_define1'], 9: ['moba_user_define2'], 10: ['moba_v2_user_define0'], 11: ['moba_v2_user_define1'], 12: ['moba_v2_user_define2'], 25: ['hotspot_user_define_plan_names'], 26: ['hotspot_v2_user_define_plan_names'], 27: ['hotspot_user_define0'], 28: ['hotspot_user_define1'], 29: ['hotspot_user_define2'], 30: ['hotspot_v2_user_define0'], 31: ['hotspot_v2_user_define1'], 32: ['hotspot_v2_user_define2'], 13: ['moba_user_vehicle_define_plan_names'], 15: ['moba_user_define_vehicle0'], 16: ['moba_user_define_vehicle1'], 17: ['moba_user_define_vehicle2'], 35: ['moba_user_vehicle_define_plan_names'], 37: ['moba_user_define_helicopter0'], 38: ['moba_user_define_helicopter1'], 39: ['moba_user_define_helicopter2'], 21: ['turn_mode', 'sensi_switch_mode', 'global_sensi_mode', 'is_sight_advance', 'is_fire_advance', 'gyroscope_mode', 'gyroscope_switch_mode', 'gyroscope_horizontal_reverse', 'gyroscope_vertical_reverse', 'gyroscope_calibration', 'gyroscope_input_cutoff', 'gyroscope_calibration_rate', 'controller_global_sensi_mode', 'is_controller_sight_advance', 'is_controller_fire_advance', 'controller_sensi_switch_mode', 'controller_sensitivity_curve', 'turn_mode_speed_a_show', 'turn_mode_dis_a_show', 'sight_sensitivity_diy', 'sight_sensitivity_x_diy', 'sight_sensitivity_y_diy', 'sight_sensitivity_reddot_diy', 'sight_sensitivity_reddot_x_diy', 'sight_sensitivity_reddot_y_diy', 'sight_sensitivity_2x_diy', 'sight_sensitivity_2x_x_diy', 'sight_sensitivity_2x_y_diy', 'sight_sensitivity_3x_diy', 'sight_sensitivity_3x_x_diy', 'sight_sensitivity_3x_y_diy', 'sight_sensitivity_4x_diy', 'sight_sensitivity_4x_x_diy', 'sight_sensitivity_4x_y_diy', 'sight_sensitivity_6x_diy', 'sight_sensitivity_6x_x_diy', 'sight_sensitivity_6x_y_diy', 'sight_sensitivity_8x_diy', 'sight_sensitivity_8x_x_diy', 'sight_sensitivity_8x_y_diy', 'sight_sensitivity', 'sight_sensitivity_x', 'sight_sensitivity_y', 'sight_sensitivity_reddot', 'sight_sensitivity_reddot_x', 'sight_sensitivity_reddot_y', 'sight_sensitivity_2x', 'sight_sensitivity_2x_x', 'sight_sensitivity_2x_y', 'sight_sensitivity_3x', 'sight_sensitivity_3x_x', 'sight_sensitivity_3x_y', 'sight_sensitivity_4x', 'sight_sensitivity_4x_x', 'sight_sensitivity_4x_y', 'sight_sensitivity_6x', 'sight_sensitivity_6x_x', 'sight_sensitivity_6x_y', 'sight_sensitivity_8x', 'sight_sensitivity_8x_x', 'sight_sensitivity_8x_y', 'fire_sensitivity_diy', 'fire_sensitivity_x_diy', 'fire_sensitivity_y_diy', 'fire_sensitivity_reddot_diy', 'fire_sensitivity_reddot_x_diy', 'fire_sensitivity_reddot_y_diy', 'fire_sensitivity_2x_diy', 'fire_sensitivity_2x_x_diy', 'fire_sensitivity_2x_y_diy', 'fire_sensitivity_3x_diy', 'fire_sensitivity_3x_x_diy', 'fire_sensitivity_3x_y_diy', 'fire_sensitivity_4x_diy', 'fire_sensitivity_4x_x_diy', 'fire_sensitivity_4x_y_diy', 'fire_sensitivity_6x_diy', 'fire_sensitivity_6x_x_diy', 'fire_sensitivity_6x_y_diy', 'fire_sensitivity_8x_diy', 'fire_sensitivity_8x_x_diy', 'fire_sensitivity_8x_y_diy', 'fire_sensitivity', 'fire_sensitivity_x', 'fire_sensitivity_y', 'fire_sensitivity_reddot', 'fire_sensitivity_reddot_x', 'fire_sensitivity_reddot_y', 'fire_sensitivity_2x', 'fire_sensitivity_2x_x', 'fire_sensitivity_2x_y', 'fire_sensitivity_3x', 'fire_sensitivity_3x_x', 'fire_sensitivity_3x_y', 'fire_sensitivity_4x', 'fire_sensitivity_4x_x', 'fire_sensitivity_4x_y', 'fire_sensitivity_6x', 'fire_sensitivity_6x_x', 'fire_sensitivity_6x_y', 'fire_sensitivity_8x', 'fire_sensitivity_8x_x', 'fire_sensitivity_8x_y', 'gyroscope_sensitivity', 'gyroscope_sensitivity_reddot', 'gyroscope_sensitivity_2x', 'gyroscope_sensitivity_3x', 'gyroscope_sensitivity_4x', 'gyroscope_sensitivity_6x', 'gyroscope_sensitivity_8x', 'gyroscope_shoot_sensitivity', 'gyroscope_shoot_sensitivity_reddot', 'gyroscope_shoot_sensitivity_2x', 'gyroscope_shoot_sensitivity_3x', 'gyroscope_shoot_sensitivity_4x', 'gyroscope_shoot_sensitivity_6x', 'gyroscope_shoot_sensitivity_8x', 'controller_sight_sensitivity_diy', 'controller_sight_sensitivity_x_diy', 'controller_sight_sensitivity_y_diy', 'controller_sight_sensitivity_reddot_diy', 'controller_sight_sensitivity_reddot_x_diy', 'controller_sight_sensitivity_reddot_y_diy', 'controller_sight_sensitivity_2x_diy', 'controller_sight_sensitivity_2x_x_diy', 'controller_sight_sensitivity_2x_y_diy', 'controller_sight_sensitivity_3x_diy', 'controller_sight_sensitivity_3x_x_diy', 'controller_sight_sensitivity_3x_y_diy', 'controller_sight_sensitivity_4x_diy', 'controller_sight_sensitivity_4x_x_diy', 'controller_sight_sensitivity_4x_y_diy', 'controller_sight_sensitivity_6x_diy', 'controller_sight_sensitivity_6x_x_diy', 'controller_sight_sensitivity_6x_y_diy', 'controller_sight_sensitivity_8x_diy', 'controller_sight_sensitivity_8x_x_diy', 'controller_sight_sensitivity_8x_y_diy', 'sight_sensitivity', 'sight_sensitivity_x', 'sight_sensitivity_y', 'sight_sensitivity_reddot', 'sight_sensitivity_reddot_x', 'sight_sensitivity_reddot_y', 'sight_sensitivity_2x', 'sight_sensitivity_2x_x', 'sight_sensitivity_2x_y', 'sight_sensitivity_3x', 'sight_sensitivity_3x_x', 'sight_sensitivity_3x_y', 'sight_sensitivity_4x', 'sight_sensitivity_4x_x', 'sight_sensitivity_4x_y', 'sight_sensitivity_6x', 'sight_sensitivity_6x_x', 'sight_sensitivity_6x_y', 'sight_sensitivity_8x', 'sight_sensitivity_8x_x', 'sight_sensitivity_8x_y', 'controller_fire_sensitivity_diy', 'controller_fire_sensitivity_x_diy', 'controller_fire_sensitivity_y_diy', 'controller_fire_sensitivity_reddot_diy', 'controller_fire_sensitivity_reddot_x_diy', 'controller_fire_sensitivity_reddot_y_diy', 'controller_fire_sensitivity_2x_diy', 'controller_fire_sensitivity_2x_x_diy', 'controller_fire_sensitivity_2x_y_diy', 'controller_fire_sensitivity_3x_diy', 'controller_fire_sensitivity_3x_x_diy', 'controller_fire_sensitivity_3x_y_diy', 'controller_fire_sensitivity_4x_diy', 'controller_fire_sensitivity_4x_x_diy', 'controller_fire_sensitivity_4x_y_diy', 'controller_fire_sensitivity_6x_diy', 'controller_fire_sensitivity_6x_x_diy', 'controller_fire_sensitivity_6x_y_diy', 'controller_fire_sensitivity_8x_diy', 'controller_fire_sensitivity_8x_x_diy', 'controller_fire_sensitivity_8x_y_diy', 'fire_sensitivity', 'fire_sensitivity_x', 'fire_sensitivity_y', 'fire_sensitivity_reddot', 'fire_sensitivity_reddot_x', 'fire_sensitivity_reddot_y', 'fire_sensitivity_2x', 'fire_sensitivity_2x_x', 'fire_sensitivity_2x_y', 'fire_sensitivity_3x', 'fire_sensitivity_3x_x', 'fire_sensitivity_3x_y', 'fire_sensitivity_4x', 'fire_sensitivity_4x_x', 'fire_sensitivity_4x_y', 'fire_sensitivity_6x', 'fire_sensitivity_6x_x', 'fire_sensitivity_6x_y', 'fire_sensitivity_8x', 'fire_sensitivity_8x_x', 'fire_sensitivity_8x_y'], 22: ['turn_mode', 'sensi_switch_mode', 'global_sensi_mode', 'is_sight_advance', 'is_fire_advance', 'gyroscope_mode', 'gyroscope_switch_mode', 'gyroscope_horizontal_reverse', 'gyroscope_vertical_reverse', 'gyroscope_calibration', 'gyroscope_input_cutoff', 'gyroscope_calibration_rate', 'controller_global_sensi_mode', 'is_controller_sight_advance', 'is_controller_fire_advance', 'controller_sensi_switch_mode', 'controller_sensitivity_curve', 'turn_mode_speed_a_show', 'turn_mode_dis_a_show', 'sight_sensitivity_diy', 'sight_sensitivity_x_diy', 'sight_sensitivity_y_diy', 'sight_sensitivity_reddot_diy', 'sight_sensitivity_reddot_x_diy', 'sight_sensitivity_reddot_y_diy', 'sight_sensitivity_2x_diy', 'sight_sensitivity_2x_x_diy', 'sight_sensitivity_2x_y_diy', 'sight_sensitivity_3x_diy', 'sight_sensitivity_3x_x_diy', 'sight_sensitivity_3x_y_diy', 'sight_sensitivity_4x_diy', 'sight_sensitivity_4x_x_diy', 'sight_sensitivity_4x_y_diy', 'sight_sensitivity_6x_diy', 'sight_sensitivity_6x_x_diy', 'sight_sensitivity_6x_y_diy', 'sight_sensitivity_8x_diy', 'sight_sensitivity_8x_x_diy', 'sight_sensitivity_8x_y_diy', 'sight_sensitivity', 'sight_sensitivity_x', 'sight_sensitivity_y', 'sight_sensitivity_reddot', 'sight_sensitivity_reddot_x', 'sight_sensitivity_reddot_y', 'sight_sensitivity_2x', 'sight_sensitivity_2x_x', 'sight_sensitivity_2x_y', 'sight_sensitivity_3x', 'sight_sensitivity_3x_x', 'sight_sensitivity_3x_y', 'sight_sensitivity_4x', 'sight_sensitivity_4x_x', 'sight_sensitivity_4x_y', 'sight_sensitivity_6x', 'sight_sensitivity_6x_x', 'sight_sensitivity_6x_y', 'sight_sensitivity_8x', 'sight_sensitivity_8x_x', 'sight_sensitivity_8x_y', 'fire_sensitivity_diy', 'fire_sensitivity_x_diy', 'fire_sensitivity_y_diy', 'fire_sensitivity_reddot_diy', 'fire_sensitivity_reddot_x_diy', 'fire_sensitivity_reddot_y_diy', 'fire_sensitivity_2x_diy', 'fire_sensitivity_2x_x_diy', 'fire_sensitivity_2x_y_diy', 'fire_sensitivity_3x_diy', 'fire_sensitivity_3x_x_diy', 'fire_sensitivity_3x_y_diy', 'fire_sensitivity_4x_diy', 'fire_sensitivity_4x_x_diy', 'fire_sensitivity_4x_y_diy', 'fire_sensitivity_6x_diy', 'fire_sensitivity_6x_x_diy', 'fire_sensitivity_6x_y_diy', 'fire_sensitivity_8x_diy', 'fire_sensitivity_8x_x_diy', 'fire_sensitivity_8x_y_diy', 'fire_sensitivity', 'fire_sensitivity_x', 'fire_sensitivity_y', 'fire_sensitivity_reddot', 'fire_sensitivity_reddot_x', 'fire_sensitivity_reddot_y', 'fire_sensitivity_2x', 'fire_sensitivity_2x_x', 'fire_sensitivity_2x_y', 'fire_sensitivity_3x', 'fire_sensitivity_3x_x', 'fire_sensitivity_3x_y', 'fire_sensitivity_4x', 'fire_sensitivity_4x_x', 'fire_sensitivity_4x_y', 'fire_sensitivity_6x', 'fire_sensitivity_6x_x', 'fire_sensitivity_6x_y', 'fire_sensitivity_8x', 'fire_sensitivity_8x_x', 'fire_sensitivity_8x_y', 'gyroscope_sensitivity', 'gyroscope_sensitivity_reddot', 'gyroscope_sensitivity_2x', 'gyroscope_sensitivity_3x', 'gyroscope_sensitivity_4x', 'gyroscope_sensitivity_6x', 'gyroscope_sensitivity_8x', 'gyroscope_shoot_sensitivity', 'gyroscope_shoot_sensitivity_reddot', 'gyroscope_shoot_sensitivity_2x', 'gyroscope_shoot_sensitivity_3x', 'gyroscope_shoot_sensitivity_4x', 'gyroscope_shoot_sensitivity_6x', 'gyroscope_shoot_sensitivity_8x', 'controller_sight_sensitivity_diy', 'controller_sight_sensitivity_x_diy', 'controller_sight_sensitivity_y_diy', 'controller_sight_sensitivity_reddot_diy', 'controller_sight_sensitivity_reddot_x_diy', 'controller_sight_sensitivity_reddot_y_diy', 'controller_sight_sensitivity_2x_diy', 'controller_sight_sensitivity_2x_x_diy', 'controller_sight_sensitivity_2x_y_diy', 'controller_sight_sensitivity_3x_diy', 'controller_sight_sensitivity_3x_x_diy', 'controller_sight_sensitivity_3x_y_diy', 'controller_sight_sensitivity_4x_diy', 'controller_sight_sensitivity_4x_x_diy', 'controller_sight_sensitivity_4x_y_diy', 'controller_sight_sensitivity_6x_diy', 'controller_sight_sensitivity_6x_x_diy', 'controller_sight_sensitivity_6x_y_diy', 'controller_sight_sensitivity_8x_diy', 'controller_sight_sensitivity_8x_x_diy', 'controller_sight_sensitivity_8x_y_diy', 'sight_sensitivity', 'sight_sensitivity_x', 'sight_sensitivity_y', 'sight_sensitivity_reddot', 'sight_sensitivity_reddot_x', 'sight_sensitivity_reddot_y', 'sight_sensitivity_2x', 'sight_sensitivity_2x_x', 'sight_sensitivity_2x_y', 'sight_sensitivity_3x', 'sight_sensitivity_3x_x', 'sight_sensitivity_3x_y', 'sight_sensitivity_4x', 'sight_sensitivity_4x_x', 'sight_sensitivity_4x_y', 'sight_sensitivity_6x', 'sight_sensitivity_6x_x', 'sight_sensitivity_6x_y', 'sight_sensitivity_8x', 'sight_sensitivity_8x_x', 'sight_sensitivity_8x_y', 'controller_fire_sensitivity_diy', 'controller_fire_sensitivity_x_diy', 'controller_fire_sensitivity_y_diy', 'controller_fire_sensitivity_reddot_diy', 'controller_fire_sensitivity_reddot_x_diy', 'controller_fire_sensitivity_reddot_y_diy', 'controller_fire_sensitivity_2x_diy', 'controller_fire_sensitivity_2x_x_diy', 'controller_fire_sensitivity_2x_y_diy', 'controller_fire_sensitivity_3x_diy', 'controller_fire_sensitivity_3x_x_diy', 'controller_fire_sensitivity_3x_y_diy', 'controller_fire_sensitivity_4x_diy', 'controller_fire_sensitivity_4x_x_diy', 'controller_fire_sensitivity_4x_y_diy', 'controller_fire_sensitivity_6x_diy', 'controller_fire_sensitivity_6x_x_diy', 'controller_fire_sensitivity_6x_y_diy', 'controller_fire_sensitivity_8x_diy', 'controller_fire_sensitivity_8x_x_diy', 'controller_fire_sensitivity_8x_y_diy', 'fire_sensitivity', 'fire_sensitivity_x', 'fire_sensitivity_y', 'fire_sensitivity_reddot', 'fire_sensitivity_reddot_x', 'fire_sensitivity_reddot_y', 'fire_sensitivity_2x', 'fire_sensitivity_2x_x', 'fire_sensitivity_2x_y', 'fire_sensitivity_3x', 'fire_sensitivity_3x_x', 'fire_sensitivity_3x_y', 'fire_sensitivity_4x', 'fire_sensitivity_4x_x', 'fire_sensitivity_4x_y', 'fire_sensitivity_6x', 'fire_sensitivity_6x_x', 'fire_sensitivity_6x_y', 'fire_sensitivity_8x', 'fire_sensitivity_8x_x', 'fire_sensitivity_8x_y'], 23: ['sensitivity_plan_names'], 24: ['is_friend_like_notify', 'recruit_invite_forbid'], 34: ['cloud_config_version'], 43: ['pc_key_group_map'], 44: ['controller_group_key_map', 'controller_hide_ui', 'controller_death_band_left_joystick_min', 'controller_death_band_left_joystick_max', 'controller_death_band_right_joystick_min', 'controller_death_band_right_joystick_max', 'controller_death_band_lt', 'controller_death_band_rt']}
LocalConfig: _LocalConfig = <gclient.config._LocalConfig object at 0x7040bf6d50>

class AssistAimModeConfig(enum):
    Expert: int = 3
    Newer: int = 2
    No: int = 1
    name_to_values: dict = {'No': 1, 'Newer': 2, 'Expert': 3}
    value_to_names: dict = {1: 'No', 2: 'Newer', 3: 'Expert'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class SettingTag(enum):
    AccountWindow: int = 24
    BasicWindow: int = 1
    CloudConfigVersion: int = 34
    ControlWindow: int = 3
    ControlWindowController: int = 44
    ControlWindowPC: int = 43
    CustomGraphics: int = 33
    CustomLayoutHelicopterV1Plan0: int = 37
    CustomLayoutHelicopterV1Plan1: int = 38
    CustomLayoutHelicopterV1Plan2: int = 39
    CustomLayoutHelicopterV1Window: int = 35
    CustomLayoutHelicopterV2Plan0: int = 40
    CustomLayoutHelicopterV2Plan1: int = 41
    CustomLayoutHelicopterV2Plan2: int = 42
    CustomLayoutHelicopterV2Window: int = 36
    CustomLayoutV1Plan0: int = 7
    CustomLayoutV1Plan1: int = 8
    CustomLayoutV1Plan2: int = 9
    CustomLayoutV1Window: int = 5
    CustomLayoutV2Plan0: int = 10
    CustomLayoutV2Plan1: int = 11
    CustomLayoutV2Plan2: int = 12
    CustomLayoutV2Window: int = 6
    CustomLayoutVehicleV1Plan0: int = 15
    CustomLayoutVehicleV1Plan1: int = 16
    CustomLayoutVehicleV1Plan2: int = 17
    CustomLayoutVehicleV1Window: int = 13
    CustomLayoutVehicleV2Plan0: int = 18
    CustomLayoutVehicleV2Plan1: int = 19
    CustomLayoutVehicleV2Plan2: int = 20
    CustomLayoutVehicleV2Window: int = 14
    GamePlayWindow: int = 2
    HotSpotCustomLayoutV1Plan0: int = 27
    HotSpotCustomLayoutV1Plan1: int = 28
    HotSpotCustomLayoutV1Plan2: int = 29
    HotSpotCustomLayoutV1Window: int = 25
    HotSpotCustomLayoutV2Plan0: int = 30
    HotSpotCustomLayoutV2Plan1: int = 31
    HotSpotCustomLayoutV2Plan2: int = 32
    HotSpotCustomLayoutV2Window: int = 26
    SensitivityPlan1: int = 21
    SensitivityPlan2: int = 22
    SensitivityWindow: int = 23
    name_to_values: dict = {'BasicWindow': 1, 'GamePlayWindow': 2, 'ControlWindow': 3, 'CustomLayoutV1Window': 5, 'CustomLayoutV2Window': 6, 'CustomLayoutV1Plan0': 7, 'CustomLayoutV1Plan1': 8, 'CustomLayoutV1Plan2': 9, 'CustomLayoutV2Plan0': 10, 'CustomLayoutV2Plan1': 11, 'CustomLayoutV2Plan2': 12, 'CustomLayoutVehicleV1Window': 13, 'CustomLayoutVehicleV2Window': 14, 'CustomLayoutVehicleV1Plan0': 15, 'CustomLayoutVehicleV1Plan1': 16, 'CustomLayoutVehicleV1Plan2': 17, 'CustomLayoutVehicleV2Plan0': 18, 'CustomLayoutVehicleV2Plan1': 19, 'CustomLayoutVehicleV2Plan2': 20, 'SensitivityPlan1': 21, 'SensitivityPlan2': 22, 'SensitivityWindow': 23, 'AccountWindow': 24, 'HotSpotCustomLayoutV1Window': 25, 'HotSpotCustomLayoutV2Window': 26, 'HotSpotCustomLayoutV1Plan0': 27, 'HotSpotCustomLayoutV1Plan1': 28, 'HotSpotCustomLayoutV1Plan2': 29, 'HotSpotCustomLayoutV2Plan0': 30, 'HotSpotCustomLayoutV2Plan1': 31, 'HotSpotCustomLayoutV2Plan2': 32, 'CustomGraphics': 33, 'CloudConfigVersion': 34, 'CustomLayoutHelicopterV1Window': 35, 'CustomLayoutHelicopterV2Window': 36, 'CustomLayoutHelicopterV1Plan0': 37, 'CustomLayoutHelicopterV1Plan1': 38, 'CustomLayoutHelicopterV1Plan2': 39, 'CustomLayoutHelicopterV2Plan0': 40, 'CustomLayoutHelicopterV2Plan1': 41, 'CustomLayoutHelicopterV2Plan2': 42, 'ControlWindowPC': 43, 'ControlWindowController': 44}
    value_to_names: dict = {1: 'BasicWindow', 2: 'GamePlayWindow', 3: 'ControlWindow', 5: 'CustomLayoutV1Window', 6: 'CustomLayoutV2Window', 7: 'CustomLayoutV1Plan0', 8: 'CustomLayoutV1Plan1', 9: 'CustomLayoutV1Plan2', 10: 'CustomLayoutV2Plan0', 11: 'CustomLayoutV2Plan1', 12: 'CustomLayoutV2Plan2', 13: 'CustomLayoutVehicleV1Window', 14: 'CustomLayoutVehicleV2Window', 15: 'CustomLayoutVehicleV1Plan0', 16: 'CustomLayoutVehicleV1Plan1', 17: 'CustomLayoutVehicleV1Plan2', 18: 'CustomLayoutVehicleV2Plan0', 19: 'CustomLayoutVehicleV2Plan1', 20: 'CustomLayoutVehicleV2Plan2', 21: 'SensitivityPlan1', 22: 'SensitivityPlan2', 23: 'SensitivityWindow', 24: 'AccountWindow', 25: 'HotSpotCustomLayoutV1Window', 26: 'HotSpotCustomLayoutV2Window', 27: 'HotSpotCustomLayoutV1Plan0', 28: 'HotSpotCustomLayoutV1Plan1', 29: 'HotSpotCustomLayoutV1Plan2', 30: 'HotSpotCustomLayoutV2Plan0', 31: 'HotSpotCustomLayoutV2Plan1', 32: 'HotSpotCustomLayoutV2Plan2', 33: 'CustomGraphics', 34: 'CloudConfigVersion', 35: 'CustomLayoutHelicopterV1Window', 36: 'CustomLayoutHelicopterV2Window', 37: 'CustomLayoutHelicopterV1Plan0', 38: 'CustomLayoutHelicopterV1Plan1', 39: 'CustomLayoutHelicopterV1Plan2', 40: 'CustomLayoutHelicopterV2Plan0', 41: 'CustomLayoutHelicopterV2Plan1', 42: 'CustomLayoutHelicopterV2Plan2', 43: 'ControlWindowPC', 44: 'ControlWindowController'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class SettingTemplateBasicWindow(SettingTemplateWindow):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    SETTING_CONFIG_ID: int = 1
    SETTING_TAGS: set = {1}
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def BanAssistAimMode(self): ...
    def CheckDLcExist(): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetRecoveryFunc(): ...
    def GetSettingNodeByIdx(self, page_idx, tab_idx, group_idx, setting_idx): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitListSettings(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnAssistAimConfigModeChange(self, assistaim_config_mode): ...
    def OnChangeAssistAimModeSettingClick(self, select_radio, val, name, setting_node, extra=None): ...
    def OnChangeSettingClick(self, select_radio, val, name, setting_node, extra=None): ...
    def OnClickAdvanceGun(self, select_radio, val, name, setting_node, extra=None): ...
    def OnDestroy(self): ...
    def OnFocus(self, value): ...
    def OnKeyDownEsc(self): ...
    def OnShowAdvanceGun(self, advance_gun_title): ...
    def OnSwitch(self, idx, from_show=False): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def RefreshCurSetting(self): ...
    def RefreshCurrentSettingListData(self): ...
    def RefreshFireMode(self, fire_mode_node): ...
    def RefreshLFireModeEnable(self, l_fire_mode_node): ...
    def RefreshPcKey(self): ...
    def RefreshSetting(self): ...
    def RefreshSettingList(self, setting_idx, irange): ...
    def RefreshSettingListDatas(self, from_show=False): ...
    def RefreshSwitchDatas(self, from_show=False): ...
    def RefreshSwitches(self, irange): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _SetHallLevel(self, visible): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _cancelLongTouch(self): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    def setting_names(): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class SettingTemplateWindow(UIWindow):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    SETTING_CONFIG_ID: int = 0
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def CheckDLcExist(): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetRecoveryFunc(): ...
    def GetSettingNodeByIdx(self, page_idx, tab_idx, group_idx, setting_idx): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitListSettings(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnDestroy(self): ...
    def OnFocus(self, value): ...
    def OnKeyDownEsc(self): ...
    def OnSwitch(self, idx, from_show=False): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def RefreshCurrentSettingListData(self): ...
    def RefreshPcKey(self): ...
    def RefreshSetting(self): ...
    def RefreshSettingList(self, setting_idx, irange): ...
    def RefreshSettingListDatas(self, from_show=False): ...
    def RefreshSwitchDatas(self, from_show=False): ...
    def RefreshSwitches(self, irange): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _SetHallLevel(self, visible): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _cancelLongTouch(self): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class SettingTitleShowType(enum):
    Hide: int = 2
    OnlyTitle: int = 1
    ShowAll: int = 0
    name_to_values: dict = {'ShowAll': 0, 'OnlyTitle': 1, 'Hide': 2}
    value_to_names: dict = {0: 'ShowAll', 1: 'OnlyTitle', 2: 'Hide'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...


