# module: gclient.gameplay.logic_moba.ui.moba_ghost_bottom_arms_comp

import events
import six2
import spell_data
import ui_define
import ui_util

class BackpackSlot(enum):
    ARMOR_PIECE: int = 5002
    CRACK_SCANNER: int = 5004
    EMERGENCY_NEEDLE: int = 5003
    FAKE_SLOT_1: int = 8001
    FAKE_SLOT_2: int = 8002
    LAUNCHER_WEAPON: int = 1005
    MEDICINE_1: int = 7001
    MEDICINE_2: int = 7002
    NONE: int = 0
    SKILL_WEAPON: int = 4001
    SKILL_WEAPON2: int = 4002
    SKILL_WEAPON3: int = 4003
    SUPPORT_WEAPON: int = 5001
    TACTICAL_WEAPON_1: int = 3001
    TACTICAL_WEAPON_2: int = 3002
    TALENT_1: int = 6001
    TALENT_2: int = 6002
    VICE_WEAPON: int = 1003
    WEAPON_1: int = 1001
    WEAPON_2: int = 1002
    WEAPON_3: int = 1004
    name_to_values: dict = {'NONE': 0, 'WEAPON_1': 1001, 'WEAPON_2': 1002, 'WEAPON_3': 1004, 'VICE_WEAPON': 1003, 'LAUNCHER_WEAPON': 1005, 'TACTICAL_WEAPON_1': 3001, 'TACTICAL_WEAPON_2': 3002, 'SKILL_WEAPON': 4001, 'SKILL_WEAPON2': 4002, 'SKILL_WEAPON3': 4003, 'SUPPORT_WEAPON': 5001, 'ARMOR_PIECE': 5002, 'EMERGENCY_NEEDLE': 5003, 'CRACK_SCANNER': 5004, 'MEDICINE_1': 7001, 'MEDICINE_2': 7002, 'TALENT_1': 6001, 'TALENT_2': 6002, 'FAKE_SLOT_1': 8001, 'FAKE_SLOT_2': 8002}
    value_to_names: dict = {0: 'NONE', 1001: 'WEAPON_1', 1002: 'WEAPON_2', 1004: 'WEAPON_3', 1003: 'VICE_WEAPON', 1005: 'LAUNCHER_WEAPON', 3001: 'TACTICAL_WEAPON_1', 3002: 'TACTICAL_WEAPON_2', 4001: 'SKILL_WEAPON', 4002: 'SKILL_WEAPON2', 4003: 'SKILL_WEAPON3', 5001: 'SUPPORT_WEAPON', 5002: 'ARMOR_PIECE', 5003: 'EMERGENCY_NEEDLE', 5004: 'CRACK_SCANNER', 7001: 'MEDICINE_1', 7002: 'MEDICINE_2', 6001: 'TALENT_1', 6002: 'TALENT_2', 8001: 'FAKE_SLOT_1', 8002: 'FAKE_SLOT_2'}

    def IsSkill(slot): ...
    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class CombatState(enum):
    ALIVE: int = 0
    DEAD: int = 2
    DYING: int = 1
    GHOST: int = 3
    NONE: int = 4
    name_to_values: dict = {'ALIVE': 0, 'DYING': 1, 'DEAD': 2, 'GHOST': 3, 'NONE': 4}
    value_to_names: dict = {0: 'ALIVE', 1: 'DYING', 2: 'DEAD', 3: 'GHOST', 4: 'NONE'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class GhostHudBottomArmComp(MobaHudBottomArmsComp):
    AUTO_OUT_ANIM: NoneType = None
    BACKPACK_CLS: type = <class 'gclient.gameplay.logic_moba.ui.moba_hud_backpack_comp.MobaHudBackpackComp'>
    BOTTOM_HEAD_BAR_NODE: type = <class 'gclient.gameplay.uicomponents.bottom_head_bar_node.BottomHeadAndBar'>
    CONTINUE_KILL_NODE: type = <class 'gclient.gameplay.logic_base.ui.hud_bottom_arms_base_comp.ContinueKillVxNode'>
    DEFAULT_BACKPACK_TAG: int = 1
    FOCUS_HIDDEN_REASON: tuple = (5, 16, 15)
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    SOUND_ID_CRYSTAL_SCANNER_TIPS_SHOW: int = 323
    TIMER_COUNTER: int = 1
    TXT_ID_CRYSTAL_GUIDE_TIPS: int = 591
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddGamepadKeyPanel(self, func_id, panel, with_txt=False, force_long=False): ...
    def AddHiddenReason(self, reason): ...
    def AddPcKeyNode(self, func_id, panel, have_text=False): ...
    def AddStoryTick(self, func, frames=0): ...
    def BuildMedicineListViewData(self): ...
    def BuildTacticalWeaponListViewData(self): ...
    def BuildTalentCDData(self, exclude_talent_id=None): ...
    def CacheSomeBtnOpacity(self): ...
    def ChangePanelPcKeyFuncId(self, old_func_id, new_func_id, target_panel=None): ...
    def CheckDLcExist(): ...
    def CheckDroneConnecting(self): ...
    def CheckHiddenAction(self): ...
    def CheckNeedShowCrystalStartGuide(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def CheckReddotForQuickAirDrop(self): ...
    def CheckThanksPanelVisibility(self): ...
    def CheckUseItemClick(self, btn): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseThanksPanel(self): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def CreateSkillDaojuItem(self, children): ...
    def CreateSkillMedicineItem(self, children): ...
    def CreateTalentCD(self, children): ...
    def CreateTalentTips(self, children): ...
    def DelPcKeyNode(self, func_id): ...
    def DelPcKeyNodeByPanel(self, panel): ...
    def DelayHidePanelSelectSkillTimer(self, delay_time): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FilterOneSupportWeapon(self): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetBackpackInstance(self, init=True): ...
    def GetCanOpenBackpack(self): ...
    def GetConfigList(self): ...
    def GetCrystalGuidePosition(self, target_node): ...
    def GetCsbPathFile(self): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetMedicineListviewItemCount(self): ...
    def GetRecoveryFunc(): ...
    def GetSlotColor(self): ...
    def GetSlotImgDict(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTacticalWeaponListviewItemCount(self): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWeaponAmmo(self, weapon, player): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def HideCrystalGuide(self, *args): ...
    def HideForReasonCombatBackpack(self, reason, is_hide): ...
    def HideForReasonEvent(self, reason, is_hide): ...
    def HidePanelTacticalForVehicle(self): ...
    def InitBtnBackpack(self): ...
    def InitClickSoundForUI(self): ...
    def InitCrystalGuideData(self): ...
    def InitCrystalGuideNode(self): ...
    def InitData(self): ...
    def InitDroneCureSelfBtn(self): ...
    def InitHidePanel(self): ...
    def InitMedDot(self): ...
    def InitMeleeAttackPanel(self): ...
    def InitNode(self): ...
    def InitOpacityWidgets(self, widgets_list, widget_info_list, widget_pc_list=[]): ...
    def InitPanelAirdrop(self): ...
    def InitPanelArms(self): ...
    def InitPanelExecute(self): ...
    def InitPanelProps(self): ...
    def InitPanelQuickBuy(self, panel_quickbuy_new): ...
    def InitPanelSelectSkill(self): ...
    def InitPanelTalent(self): ...
    def InitPanelThanks(self): ...
    def InitPanelWeapon(self): ...
    def InitQuickKongtouPanel(self): ...
    def InitSKillMedicine(self): ...
    def InitShopAndAirDropVisible(self): ...
    def InitSkillDaoju(self): ...
    def InitSkillXPanel(self): ...
    def InitSkillZhiyuan(self): ...
    def InitTactical(self): ...
    def InitTacticalDot(self): ...
    def InitTalentCDPanel(self): ...
    def InnerInitTacticalEnergy(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsMedicineListViewShow(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def LoadBtnBackpackImg(self): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnAddRecoverHpBuff(self, buff_info): ...
    def OnAttrSkillMaxCountChange(self): ...
    def OnAvatarLoginRelay(self, is_relay): ...
    def OnBackpackEntryClick(self, _=None): ...
    def OnBackpackShopEntryClick(self, _=None): ...
    def OnBeHuntLevelChange(self, alert_level): ...
    def OnBombModeChange(self, new_mode): ...
    def OnChangeLeftHandWeapon(self, guid, old=''): ...
    def OnChangeParkour(self): ...
    def OnChangeRepelBombExplodeTime(self): ...
    def OnChangeSpecWeapon(self, guid, old=''): ...
    def OnChangeWeapon(self, guid, old=''): ...
    def OnChangeWeaponClick(self, btn): ...
    def OnClickCrystalGuideNode(self, widget=None): ...
    def OnClickQuickAirDropGuide1(self, _=None): ...
    def OnCloseHeroChangeUI(self, inst, value): ...
    def OnCombatStateChanged_HideCrystalBattleGuide(self, *args, **kwargs): ...
    def OnCombatTeamShutterEnergyChanged(self, combat_team_id): ...
    def OnContractIDChange(self, old, contract_id): ...
    def OnCrystalGuideChanged_CheckShowGuide(self, *args, **kwargs): ...
    def OnDestroy(self): ...
    def OnDyeWeapon(self, weapon_guid): ...
    def OnFocus(self, value): ...
    def OnForbidSwitchWeapon(self): ...
    def OnGamepadChange(self, has_gamepad): ...
    def OnGamepadChangeArms(self, has_gamepad): ...
    def OnGamepadChangePcKeyNodes(self, has_gamepad): ...
    def OnGamepadKeySettingChange(self): ...
    def OnGrenadeLauncherBombChange(self): ...
    def OnHoldCombatItem(self, item): ...
    def OnHolographicRobotId(self): ...
    def OnInitReplayUI_CheckBackpackBtn(self): ...
    def OnKeyDownEsc(self): ...
    def OnMeleeAttackBegin(self, btn): ...
    def OnMeleeAttackEnd(self, btn): ...
    def OnMemberAskHelpTime(self, avatar_id): ...
    def OnParachuteStageChanged(self, stage): ...
    def OnPlayerBuffChanged(self, new_buff): ...
    def OnPlayerBuffPropChanged(self, key): ...
    def OnPlayerCannonIdChange(self): ...
    def OnPlayerCombatAvatarCreated(self): ...
    def OnPlayerCombatStateChange(self): ...
    def OnPlayerContinueKill(self, player_id, count): ...
    def OnPlayerControlTargetChange(self): ...
    def OnPlayerControlTelescope(self, is_use=False): ...
    def OnPlayerDroneConnectStateChanged(self, connected_or_disconnected): ...
    def OnPlayerDroneStateChanged(self, created_or_destroyed): ...
    def OnPlayerExecuteTarget(self, target_id): ...
    def OnPlayerGhostEnergyChange(self, avatar): ...
    def OnPlayerHeroIdChanged(self): ...
    def OnPlayerLandGroundEnd_ShowCrystalGuide(self, *args, **kwargs): ...
    def OnPlayerLeanOutChanged(self): ...
    def OnPlayerParaStageChanged(self, para_stage): ...
    def OnPlayerParaTraineeChange(self): ...
    def OnPlayerParaTrainerChange(self): ...
    def OnPlayerStateLinkAdd(self, state): ...
    def OnPlayerStateLinkRemove(self, state): ...
    def OnPlayerVehicleChanged(self): ...
    def OnPlayerVehicleSeatChanged(self): ...
    def OnRecommendBuySupport(self): ...
    def OnRecvThanksFlag(self, target_id, reason): ...
    def OnRefreshAll(self): ...
    def OnRefreshAllBackpackSlot(self): ...
    def OnRefreshBackpackSlot(self, slot_key, old=None, new=None): ...
    def OnRefreshBackpackSlotForClusterBomb(self, slot_key, old=None, new=None): ...
    def OnRefreshDroneCureSelf(self): ...
    def OnRefreshNeedleState(self, visible): ...
    def OnRefreshSpellStatus(self, spell, key=None, old=None, new=None): ...
    def OnRemoveRecoverHpBuff(self, buff_guid): ...
    def OnSelMed(self, guid, item_id=None): ...
    def OnSelThrowable(self, guid, item_id=None): ...
    def OnSelectOneMedicine(self, item_id): ...
    def OnSelectOneTacticalWeapon(self, item_id): ...
    def OnSelectSkillDaojuClick(self, btn=None): ...
    def OnSelectSkillMedicineClick(self, btn=None): ...
    def OnSetMoney(self, old=None, _=None): ...
    def OnSetQuickAirDrop(self): ...
    def OnSetQuickSwitchMed(self): ...
    def OnSettingQuickUseMode(self, quick_use_skill_mode): ...
    def OnShopGoodsBuyTimeChange(self, support_id, last_buy_time, cd): ...
    def OnShowCrystalScannerGuide(self): ...
    def OnShowDroneCureSelf(self, is_show): ...
    def OnShowOtherSkillDaojuClick(self, is_show, _=None): ...
    def OnShowOtherSkillMedicineClick(self, is_show, _=None, from_keyboard=False): ...
    def OnShowQuickKongtou(self, visible): ...
    def OnShutterEnergyTeamUpdate(self, energy_stronghold): ...
    def OnSkillNodeEnableUse(self, enable): ...
    def OnSwitchBackpackPanel(self, tag): ...
    def OnTacticalEnergyChange(self, old): ...
    def OnTacticalLevelChange(self, old): ...
    def OnTacticalLevelEffectDone(self): ...
    def OnTalentKaCountChange(self, new): ...
    def OnTeamMemberCoinsChange(self, member_id=None): ...
    def OnTeammateAskSupport(self, teammate_id, item_id): ...
    def OnTeammateBuySupport(self, player_id, item_list): ...
    def OnThanks(self, btn=None, ret={}): ...
    def OnUIOpacityChange(self, reason, is_hide): ...
    def OnUpdateArmorBar(self, player, old_armor=None): ...
    def OnUpdateBackpackClear(self): ...
    def OnUpdateBloodBar(self, player, old_hp=None): ...
    def OnUpdateCoinCount(self, old=None, _=None): ...
    def OnUpdateEmmaBuff(self, is_add): ...
    def OnUpdateItemCount(self, item, old, new): ...
    def OnUpdateMedicine(self): ...
    def OnUpdateMedicineListView(self): ...
    def OnUpdatePlayerSlot(self, player): ...
    def OnUpdateRecoverBloodBar(self, player, recover_hp): ...
    def OnUpdateSlotWeapon(self, slot_key): ...
    def OnUpdateSlot_CRACK_SCANNER(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_MEDICINE_1(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_MEDICINE_2(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_SKILL_WEAPON(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_SKILL_WEAPON2(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_SKILL_WEAPON3(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_TACTICAL_WEAPON_1(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_TACTICAL_WEAPON_2(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_WEAPON_1(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_WEAPON_2(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_WEAPON_3(self, slot_key, old=None, new=None): ...
    def OnUpdateSupportWeapon(self, key=None, is_add=None, item=None): ...
    def OnUpdateTactical(self, player, level=-1): ...
    def OnUpdateTacticalWeapon(self): ...
    def OnUpdateTacticalWeaponListView(self): ...
    def OnUpdateWeaponAmmo(self, guid, curr, total): ...
    def OnUpdateWeaponCurrAmmo(self, guid, curr): ...
    def OnUpdateWeaponRestAmmo(self, ammo_type, old, rest): ...
    def OnUseItemBeginClick(self, btn): ...
    def OnUseItemEndClick(self, btn): ...
    def OnUseNeedleClick(self, btn=None): ...
    def OnUsingCombatItem_CheckMedicineUse(self, item): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PlayHighLevelTalentEntranceAnim(self): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def ReShowPanelTacticalForVehicle(self): ...
    def RefreshArmorBarBottom(self, player, old_armor=None): ...
    def RefreshAvatarBanSkill(self, ban_skill): ...
    def RefreshBackpackBtn(self): ...
    def RefreshBtnMedImg(self): ...
    def RefreshBtnMeleeAttackForBombChange(self): ...
    def RefreshCrystalScannerStartGuide(self): ...
    def RefreshDebuffList(self): ...
    def RefreshImgParaVisible(self): ...
    def RefreshMeleeAttackBtn(self, weapon): ...
    def RefreshPanelSelectSkill(self, state=None): ...
    def RefreshPanelSkillX(self, player): ...
    def RefreshParaStageHide(self): ...
    def RefreshPcKey(self): ...
    def RefreshPcKeyNodes(self): ...
    def RefreshPlayerHpBar(self, player, old_hp=None): ...
    def RefreshQuickAirDrop(self): ...
    def RefreshShowSelectSkill(self): ...
    def RefreshSkillDaojuItem(self, irange): ...
    def RefreshSkillMedicineItem(self, irange): ...
    def RefreshTacticalWeaponSelected(self): ...
    def RefreshTalentCDListview(self, irange): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetCrystalScannerGuideVisible(self, show): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetHudVisibleOnPlayerDroneControlling(self, visible): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetSkillNodeVisibleOnPlayerDroneControlling(self, visible): ...
    def SetTacticalEnergy(self, energy_delta): ...
    def SetTacticalEnergyColor(self, color): ...
    def SetUserDefineWidgetPos(self): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def ShowQuickAirdropRecommended(self): ...
    def ShowQuickMedicineRecommended(self, item_id): ...
    def ShowSelectSkillWindow(self, btn): ...
    def StartCrystalBattleGuideShowCheckTimer(self, *args): ...
    def StopAnim(self): ...
    def StopCrystalBattleGuideShowCheckTimer(self): ...
    def StopHighLevelTalentEntranceAnim(self): ...
    def TryShowCrystalBattleGuide(self): ...
    def UpdatePanelGunWeapon(self, guid, old): ...
    def UpdatePanelSkill3(self): ...
    def UpdatePanelWeapon(self): ...
    def UpdateTalentEntrance(self): ...
    def _AddOpacityHideReason(self, reason): ...
    def _CheckExecuteTarget(self, delta=0): ...
    def _CheckNeedShowCrystalStartGuide_Item(self): ...
    def _CloseImpl(self, _=None): ...
    def _CloseQuickAirdropRecommended(self): ...
    def _CloseQuickMedicineRecommended(self): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _EnterParachute_FreeFall(self): ...
    def _EnterParachute_FreeFallWithGun(self): ...
    def _EnterParachute_OnAircraft(self): ...
    def _EnterParachute_Parachute(self): ...
    def _EnterParachute_ParachuteEnd(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _GetMedicineItemForHp(self): ...
    def _GetOpacityWidgets(self): ...
    def _GetOpactityWidgetsInfo(self): ...
    def _GetOpactityWidgetsPC(self): ...
    def _GetTacticalWeaponItem(self): ...
    def _HaveOpacityHideReason(self, reason): ...
    def _HideCrystalGuide(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _NodeVisibleConsideringVehicle(self): ...
    def _OnDirectlyBuyAirdrop(self): ...
    def _OnDirectlyUseMedicine(self, item_id): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _RemoveOpacityHideReason(self, reason): ...
    def _SetHallLevel(self, visible): ...
    def _SetOpacityForCacheWidgets(self, is_hide, opacity_factor, is_info=False, need_fade=False): ...
    def _SetOpacityForCacheWidgetsPC(self, is_hide, opacity_factor): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _ShowCrystalGuide(self): ...
    def _UpdateMedicineListViewHeight(self): ...
    def _UpdateTacticalWeaponListViewHeight(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _cancelLongTouch(self): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _postComponents(self, bdict): ...
    def _show_node_hover(self, node, visible): ...
    def _tickComponents(self, dtime): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    @property
    def crystal_guide_csb_name(self): ...    @property
    def cur_select_medicine_item_id(self): ...    @property
    def cur_select_tactical_item_id(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def skill_3_visible(self): ...    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class MedicineNode(CommonItemNode):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def LoadData(self, items): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetSelect(self, select): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowBottomBg(self, bottom): ...
    def ShowEmpty(self): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def UpdateCount(self, count=None): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def guid(self): ...    @property
    def hidden_reason(self): ...    @property
    def item_id(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class MobaHudBottomArmsComp(HudBottomArmsBaseComp):
    AUTO_OUT_ANIM: NoneType = None
    BACKPACK_CLS: type = <class 'gclient.gameplay.logic_moba.ui.moba_hud_backpack_comp.MobaHudBackpackComp'>
    BOTTOM_HEAD_BAR_NODE: type = <class 'gclient.gameplay.uicomponents.bottom_head_bar_node.BottomHeadAndBar'>
    CONTINUE_KILL_NODE: type = <class 'gclient.gameplay.logic_base.ui.hud_bottom_arms_base_comp.ContinueKillVxNode'>
    DEFAULT_BACKPACK_TAG: int = 1
    FOCUS_HIDDEN_REASON: tuple = (5, 16, 15)
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    SOUND_ID_CRYSTAL_SCANNER_TIPS_SHOW: int = 323
    TIMER_COUNTER: int = 1
    TXT_ID_CRYSTAL_GUIDE_TIPS: int = 591
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddGamepadKeyPanel(self, func_id, panel, with_txt=False, force_long=False): ...
    def AddHiddenReason(self, reason): ...
    def AddPcKeyNode(self, func_id, panel, have_text=False): ...
    def AddStoryTick(self, func, frames=0): ...
    def BuildMedicineListViewData(self): ...
    def BuildTacticalWeaponListViewData(self): ...
    def BuildTalentCDData(self, exclude_talent_id=None): ...
    def CacheSomeBtnOpacity(self): ...
    def ChangePanelPcKeyFuncId(self, old_func_id, new_func_id, target_panel=None): ...
    def CheckDLcExist(): ...
    def CheckDroneConnecting(self): ...
    def CheckHiddenAction(self): ...
    def CheckNeedShowCrystalStartGuide(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def CheckReddotForQuickAirDrop(self): ...
    def CheckThanksPanelVisibility(self): ...
    def CheckUseItemClick(self, btn): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseThanksPanel(self): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def CreateSkillDaojuItem(self, children): ...
    def CreateSkillMedicineItem(self, children): ...
    def CreateTalentCD(self, children): ...
    def CreateTalentTips(self, children): ...
    def DelPcKeyNode(self, func_id): ...
    def DelPcKeyNodeByPanel(self, panel): ...
    def DelayHidePanelSelectSkillTimer(self, delay_time): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FilterOneSupportWeapon(self): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetBackpackInstance(self, init=True): ...
    def GetCanOpenBackpack(self): ...
    def GetConfigList(self): ...
    def GetCrystalGuidePosition(self, target_node): ...
    def GetCsbPathFile(self): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetMedicineListviewItemCount(self): ...
    def GetRecoveryFunc(): ...
    def GetSlotColor(self): ...
    def GetSlotImgDict(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTacticalWeaponListviewItemCount(self): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWeaponAmmo(self, weapon, player): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def HideCrystalGuide(self, *args): ...
    def HideForReasonCombatBackpack(self, reason, is_hide): ...
    def HideForReasonEvent(self, reason, is_hide): ...
    def HidePanelTacticalForVehicle(self): ...
    def InitBtnBackpack(self): ...
    def InitClickSoundForUI(self): ...
    def InitCrystalGuideData(self): ...
    def InitCrystalGuideNode(self): ...
    def InitData(self): ...
    def InitDroneCureSelfBtn(self): ...
    def InitMedDot(self): ...
    def InitMeleeAttackPanel(self): ...
    def InitNode(self): ...
    def InitOpacityWidgets(self, widgets_list, widget_info_list, widget_pc_list=[]): ...
    def InitPanelAirdrop(self): ...
    def InitPanelArms(self): ...
    def InitPanelExecute(self): ...
    def InitPanelProps(self): ...
    def InitPanelQuickBuy(self, panel_quickbuy_new): ...
    def InitPanelSelectSkill(self): ...
    def InitPanelTalent(self): ...
    def InitPanelThanks(self): ...
    def InitPanelWeapon(self): ...
    def InitQuickKongtouPanel(self): ...
    def InitSKillMedicine(self): ...
    def InitShopAndAirDropVisible(self): ...
    def InitSkillXPanel(self): ...
    def InitSkillZhiyuan(self): ...
    def InitTactical(self): ...
    def InitTacticalDot(self): ...
    def InitTalentCDPanel(self): ...
    def InnerInitTacticalEnergy(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsMedicineListViewShow(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def LoadBtnBackpackImg(self): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnAddRecoverHpBuff(self, buff_info): ...
    def OnAttrSkillMaxCountChange(self): ...
    def OnAvatarLoginRelay(self, is_relay): ...
    def OnBackpackEntryClick(self, _=None): ...
    def OnBackpackShopEntryClick(self, _=None): ...
    def OnBeHuntLevelChange(self, alert_level): ...
    def OnBombModeChange(self, new_mode): ...
    def OnChangeLeftHandWeapon(self, guid, old=''): ...
    def OnChangeParkour(self): ...
    def OnChangeRepelBombExplodeTime(self): ...
    def OnChangeSpecWeapon(self, guid, old=''): ...
    def OnChangeWeapon(self, guid, old=''): ...
    def OnChangeWeaponClick(self, btn): ...
    def OnClickCrystalGuideNode(self, widget=None): ...
    def OnClickQuickAirDropGuide1(self, _=None): ...
    def OnCloseHeroChangeUI(self, inst, value): ...
    def OnCombatStateChanged_HideCrystalBattleGuide(self, *args, **kwargs): ...
    def OnCombatTeamShutterEnergyChanged(self, combat_team_id): ...
    def OnContractIDChange(self, old, contract_id): ...
    def OnCrystalGuideChanged_CheckShowGuide(self, *args, **kwargs): ...
    def OnDestroy(self): ...
    def OnDyeWeapon(self, weapon_guid): ...
    def OnFocus(self, value): ...
    def OnForbidSwitchWeapon(self): ...
    def OnGamepadChange(self, has_gamepad): ...
    def OnGamepadChangeArms(self, has_gamepad): ...
    def OnGamepadChangePcKeyNodes(self, has_gamepad): ...
    def OnGamepadKeySettingChange(self): ...
    def OnGrenadeLauncherBombChange(self): ...
    def OnHoldCombatItem(self, item): ...
    def OnHolographicRobotId(self): ...
    def OnInitReplayUI_CheckBackpackBtn(self): ...
    def OnKeyDownEsc(self): ...
    def OnMeleeAttackBegin(self, btn): ...
    def OnMeleeAttackEnd(self, btn): ...
    def OnMemberAskHelpTime(self, avatar_id): ...
    def OnParachuteStageChanged(self, stage): ...
    def OnPlayerBuffChanged(self, new_buff): ...
    def OnPlayerBuffPropChanged(self, key): ...
    def OnPlayerCannonIdChange(self): ...
    def OnPlayerCombatAvatarCreated(self): ...
    def OnPlayerCombatStateChange(self): ...
    def OnPlayerContinueKill(self, player_id, count): ...
    def OnPlayerControlTargetChange(self): ...
    def OnPlayerControlTelescope(self, is_use=False): ...
    def OnPlayerDroneConnectStateChanged(self, connected_or_disconnected): ...
    def OnPlayerDroneStateChanged(self, created_or_destroyed): ...
    def OnPlayerExecuteTarget(self, target_id): ...
    def OnPlayerHeroIdChanged(self): ...
    def OnPlayerLandGroundEnd_ShowCrystalGuide(self, *args, **kwargs): ...
    def OnPlayerLeanOutChanged(self): ...
    def OnPlayerParaStageChanged(self, para_stage): ...
    def OnPlayerParaTraineeChange(self): ...
    def OnPlayerParaTrainerChange(self): ...
    def OnPlayerStateLinkAdd(self, state): ...
    def OnPlayerStateLinkRemove(self, state): ...
    def OnPlayerVehicleChanged(self): ...
    def OnPlayerVehicleSeatChanged(self): ...
    def OnRecommendBuySupport(self): ...
    def OnRecvThanksFlag(self, target_id, reason): ...
    def OnRefreshAll(self): ...
    def OnRefreshAllBackpackSlot(self): ...
    def OnRefreshBackpackSlot(self, slot_key, old=None, new=None): ...
    def OnRefreshBackpackSlotForClusterBomb(self, slot_key, old=None, new=None): ...
    def OnRefreshDroneCureSelf(self): ...
    def OnRefreshNeedleState(self, visible): ...
    def OnRefreshSpellStatus(self, spell, key=None, old=None, new=None): ...
    def OnRemoveRecoverHpBuff(self, buff_guid): ...
    def OnSelMed(self, guid, item_id=None): ...
    def OnSelThrowable(self, guid, item_id=None): ...
    def OnSelectOneMedicine(self, item_id): ...
    def OnSelectOneTacticalWeapon(self, item_id): ...
    def OnSelectSkillDaojuClick(self, btn=None): ...
    def OnSelectSkillMedicineClick(self, btn=None): ...
    def OnSetMoney(self, old=None, _=None): ...
    def OnSetQuickAirDrop(self): ...
    def OnSetQuickSwitchMed(self): ...
    def OnSettingQuickUseMode(self, quick_use_skill_mode): ...
    def OnShopGoodsBuyTimeChange(self, support_id, last_buy_time, cd): ...
    def OnShowCrystalScannerGuide(self): ...
    def OnShowDroneCureSelf(self, is_show): ...
    def OnShowOtherSkillDaojuClick(self, is_show, _=None): ...
    def OnShowOtherSkillMedicineClick(self, is_show, _=None, from_keyboard=False): ...
    def OnShowQuickKongtou(self, visible): ...
    def OnShutterEnergyTeamUpdate(self, energy_stronghold): ...
    def OnSkillNodeEnableUse(self, enable): ...
    def OnSwitchBackpackPanel(self, tag): ...
    def OnTacticalEnergyChange(self, old): ...
    def OnTacticalLevelChange(self, old): ...
    def OnTacticalLevelEffectDone(self): ...
    def OnTalentKaCountChange(self, new): ...
    def OnTeamMemberCoinsChange(self, member_id=None): ...
    def OnTeammateAskSupport(self, teammate_id, item_id): ...
    def OnTeammateBuySupport(self, player_id, item_list): ...
    def OnThanks(self, btn=None, ret={}): ...
    def OnUIOpacityChange(self, reason, is_hide): ...
    def OnUpdateArmorBar(self, player, old_armor=None): ...
    def OnUpdateBackpackClear(self): ...
    def OnUpdateBloodBar(self, player, old_hp=None): ...
    def OnUpdateCoinCount(self, old=None, _=None): ...
    def OnUpdateEmmaBuff(self, is_add): ...
    def OnUpdateItemCount(self, item, old, new): ...
    def OnUpdateMedicine(self): ...
    def OnUpdateMedicineListView(self): ...
    def OnUpdatePlayerSlot(self, player): ...
    def OnUpdateRecoverBloodBar(self, player, recover_hp): ...
    def OnUpdateSlotWeapon(self, slot_key): ...
    def OnUpdateSlot_CRACK_SCANNER(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_MEDICINE_1(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_MEDICINE_2(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_SKILL_WEAPON(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_SKILL_WEAPON2(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_SKILL_WEAPON3(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_TACTICAL_WEAPON_1(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_TACTICAL_WEAPON_2(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_WEAPON_1(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_WEAPON_2(self, slot_key, old=None, new=None): ...
    def OnUpdateSlot_WEAPON_3(self, slot_key, old=None, new=None): ...
    def OnUpdateSupportWeapon(self, key=None, is_add=None, item=None): ...
    def OnUpdateTactical(self, player, level=-1): ...
    def OnUpdateTacticalWeapon(self): ...
    def OnUpdateTacticalWeaponListView(self): ...
    def OnUpdateWeaponAmmo(self, guid, curr, total): ...
    def OnUpdateWeaponCurrAmmo(self, guid, curr): ...
    def OnUpdateWeaponRestAmmo(self, ammo_type, old, rest): ...
    def OnUseItemBeginClick(self, btn): ...
    def OnUseItemEndClick(self, btn): ...
    def OnUseNeedleClick(self, btn=None): ...
    def OnUsingCombatItem_CheckMedicineUse(self, item): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PlayHighLevelTalentEntranceAnim(self): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def ReShowPanelTacticalForVehicle(self): ...
    def RefreshArmorBarBottom(self, player, old_armor=None): ...
    def RefreshAvatarBanSkill(self, ban_skill): ...
    def RefreshBackpackBtn(self): ...
    def RefreshBtnMedImg(self): ...
    def RefreshBtnMeleeAttackForBombChange(self): ...
    def RefreshCrystalScannerStartGuide(self): ...
    def RefreshDebuffList(self): ...
    def RefreshImgParaVisible(self): ...
    def RefreshMeleeAttackBtn(self, weapon): ...
    def RefreshPanelSelectSkill(self, state=None): ...
    def RefreshPanelSkillX(self, player): ...
    def RefreshParaStageHide(self): ...
    def RefreshPcKey(self): ...
    def RefreshPcKeyNodes(self): ...
    def RefreshPlayerHpBar(self, player, old_hp=None): ...
    def RefreshQuickAirDrop(self): ...
    def RefreshShowSelectSkill(self): ...
    def RefreshSkillDaojuItem(self, irange): ...
    def RefreshSkillMedicineItem(self, irange): ...
    def RefreshTacticalWeaponSelected(self): ...
    def RefreshTalentCDListview(self, irange): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetCrystalScannerGuideVisible(self, show): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetHudVisibleOnPlayerDroneControlling(self, visible): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetSkillNodeVisibleOnPlayerDroneControlling(self, visible): ...
    def SetTacticalEnergy(self, energy_delta): ...
    def SetTacticalEnergyColor(self, color): ...
    def SetUserDefineWidgetPos(self): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def ShowQuickAirdropRecommended(self): ...
    def ShowQuickMedicineRecommended(self, item_id): ...
    def ShowSelectSkillWindow(self, btn): ...
    def StartCrystalBattleGuideShowCheckTimer(self, *args): ...
    def StopAnim(self): ...
    def StopCrystalBattleGuideShowCheckTimer(self): ...
    def StopHighLevelTalentEntranceAnim(self): ...
    def TryShowCrystalBattleGuide(self): ...
    def UpdatePanelGunWeapon(self, guid, old): ...
    def UpdatePanelSkill3(self): ...
    def UpdatePanelWeapon(self): ...
    def UpdateTalentEntrance(self): ...
    def _AddOpacityHideReason(self, reason): ...
    def _CheckExecuteTarget(self, delta=0): ...
    def _CheckNeedShowCrystalStartGuide_Item(self): ...
    def _CloseImpl(self, _=None): ...
    def _CloseQuickAirdropRecommended(self): ...
    def _CloseQuickMedicineRecommended(self): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _EnterParachute_FreeFall(self): ...
    def _EnterParachute_FreeFallWithGun(self): ...
    def _EnterParachute_OnAircraft(self): ...
    def _EnterParachute_Parachute(self): ...
    def _EnterParachute_ParachuteEnd(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _GetMedicineItemForHp(self): ...
    def _GetOpacityWidgets(self): ...
    def _GetOpactityWidgetsInfo(self): ...
    def _GetOpactityWidgetsPC(self): ...
    def _GetTacticalWeaponItem(self): ...
    def _HaveOpacityHideReason(self, reason): ...
    def _HideCrystalGuide(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _NodeVisibleConsideringVehicle(self): ...
    def _OnDirectlyBuyAirdrop(self): ...
    def _OnDirectlyUseMedicine(self, item_id): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _RemoveOpacityHideReason(self, reason): ...
    def _SetHallLevel(self, visible): ...
    def _SetOpacityForCacheWidgets(self, is_hide, opacity_factor, is_info=False, need_fade=False): ...
    def _SetOpacityForCacheWidgetsPC(self, is_hide, opacity_factor): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _ShowCrystalGuide(self): ...
    def _UpdateMedicineListViewHeight(self): ...
    def _UpdateTacticalWeaponListViewHeight(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _cancelLongTouch(self): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _postComponents(self, bdict): ...
    def _show_node_hover(self, node, visible): ...
    def _tickComponents(self, dtime): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    @property
    def crystal_guide_csb_name(self): ...    @property
    def cur_select_medicine_item_id(self): ...    @property
    def cur_select_tactical_item_id(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def skill_3_visible(self): ...    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class SkillJinengNode(UINode):
    COLOR_CISHA_AMMO_COMMON_NOT_USING: tuple = (117, 116, 117, 255)
    COLOR_CISHA_AMMO_COMMON_USING: tuple = (190, 186, 180, 255)
    COLOR_CISHA_AMMO_TEXT_CUR_NOT_USING: tuple = (175, 175, 175)
    COLOR_CISHA_AMMO_TEXT_CUR_USING: tuple = (255, 255, 255, 255)
    COLOR_CISHA_AMMO_TEXT_REST_NOT_USING: tuple = (141, 141, 141, 255)
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def ChargeLoading(self, cur_pct, charge_speed, count, charge_limit): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def DisableTouch(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def EnergyChargeLoading(self, cur_pct, charge_speed, spell): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def LoadData(self, item, op_mode=0): ...
    def LoadingSpellCallback(self): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnClickBegin(self, _): ...
    def OnClickCancel(self, _): ...
    def OnClickEnd(self, _): ...
    def OnClickMove(self, _): ...
    def OnSelect(self, is_visible): ...
    def OnTakeAssassinateWeapon(self, _): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def ProcessSpellLoading(self, spell, key=None, old=None, new=None): ...
    def RefreshCishaColor(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def SetAvatarWeapon(self, weapon): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetOpMode(self, op_mode): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def TriggerAndRefreshListviewCount(self, ka_count): ...
    def UpdateAmmoNumber(self, curr, rest): ...
    def UpdateCurrAmmoNumber(self, curr): ...
    def UpdateRestAmmoNumber(self, rest=None): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _cancelLongTouch(self): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _show_node_hover(self, node, visible): ...
    def _tickComponents(self, dtime): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def guid(self): ...    @property
    def hidden_reason(self): ...    @property
    def item_id(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class Swallower(object):
class UIProgressBar(UINode):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CancelGradualTimer(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeadPoint(self, com, offx, offy, headpoint_reverse=False): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPercent(self, percent): ...
    def SetPercentCallback(self, callback): ...
    def SetPercentG(self, targetpercent, step, callback, dt): ...
    def SetPercentGradually(self, targetpercent, duration=3.0, callback=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def StopPercentGradually(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def texture(self): ...    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class UIText(UiTextBase):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CancelBounceTimer(self): ...
    def CancelTypewriterTimer(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMergeDraw(self, is_enable): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableShadow(self, rgba, offset=(2, -2)): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnTypewriterTimer(self, *args): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def ResetTypewriter(self): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFontSize(self, size): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetTextColorByList(self, color_list): ...
    def SetTypewriterText(self, text, interval=0.1): ...
    def SetVertexColor(self, enable, bottom_left=None, bottom_right=None, top_left=None, top_right=None): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StartTextNumBounce(self, target_num, txt_template='{}', bounce_time=1, bounce_interval=0.03, init_num=0): ...
    def StartTypewriterTimer(self, interval=0.5): ...
    def StopAnim(self): ...
    def StopTypewriter(self, finish_write=True): ...
    def UpdateBounceText(self, init_num, target_num, txt_template, bounce_time, *args): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setFntFile(self, fnt_index): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def string_message_id(self): ...    @property
    def text(self): ...    @property
    def text_color(self): ...    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class UIWindow(UINode):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def CheckDLcExist(): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetRecoveryFunc(): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnDestroy(self): ...
    def OnFocus(self, value): ...
    def OnKeyDownEsc(self): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def RefreshPcKey(self): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _SetHallLevel(self, visible): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _cancelLongTouch(self): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...


