# module: gclient.framework.sound.sound_manager

import MConfig
import MEngine
import MPlatform
import MType
import Timer
import cconst
import cdata_util
import consts
import equip_data
import events
import formula
import os
import random
import six2
import sound_event_data

LocalConfig: _LocalConfig = <gclient.config._LocalConfig object at 0x7040bf6d50>
PRELOAD_SOUND_LIST: set = {'esm_skills_drone_release', 'esm_skills_icewall_break', 'kag6', 'esm_ui_general_store', 'impact_bullet_threat', 'esm_ui_skill_fully_charged', 'esm_skills_vortex_takeout', 'esm_skills_icewall_generate', 'esm_airdrop_open', 'm700', 'm4a1_act_media', 'esm_ui_general_back', 'esm_ui_general_character_configure', 'm700_media', 'ak47', 'esm_impact_hit_armor_feedback', 'esm_nv_ui_general_fail', 'esm_ui_general_battle_countdown_three', 'esm_impact_1p', 'esm_nv_ui_team_fail_points', 'ar97_media', 'vo_char_ran_cn_media', 'vo_char_female_cn_media', 'esm_ui_mission_receive', 'esm_skills_rockets_explosion', 'fst_general', 'eagle', 'esm_ui_settings_select', 'esm_skills_vortex_release', 'katana', 'esm_skills_vortex_loop', 'esm_ui_mission_fail', 'esm_skills_rockets_release', 'eagle_media', 'esm_character_revive', 'mp155_media', 'vector', 'esm_gamemode_xujing_ui_navigation', 'vo_char_male_cn_media', 'esm_impact_hit_armor_broken_confirm', 'origin12', 'esm_game_process_resurrection_signal', 'm4a1', 'scarlet_dawn_media', 'esm_parachuting_open', 'vehicle_helicopter_media', 'esm_ui_general_teammate_achievement', 'esm_strop_catch', 'kag6_v6_unstable_act_media', 'vehicle_pickup_media', 'vss', 'm4a1_media', 'voice_message', 'esm_nv_ui_team_win', 'esm_character_death', 'glock_act_media', 'esm_wpn_grenade_smoke_burst', 'origin12_act_media', 'esm_impact_hit_vehicle_feedback', 'scar', 'esm_ui_fight_bag_open', 'esm_item_inhaler', 'glock', 'impact_bullet_threat_media', 'vss_media', 'origin12_media', 'esm_skills_shield_release', 'dagger_media', 'esm_ui_mark_common', 'esm_skills_turret_take_out', 'esm_skills_detection_take_out', 'inp9_media', 'vehicle_common', 'esm_freefall_landing_lp', 'esm_skills_zero_jifengzhan_sprint', 'esm_nv_ui_general_tip', 'esm_ui_general_confirm', 'kala_act_media', 'esm_nv_ui_general_victory', 'esm_enemy_killed_headshot_confirm', 'esm_cutscene_plane_plot', 'esm_skills_zero_bullet_block', 'urb_act_media', 'vector_act_media', 'esm_parachuting_fall', 'esm_enemy_killed_confirm', 'esm_item_talent_pickup', 'scar_act_media', 'esm_item_firstaidkit', 'esm_ui_fight_bag_close', 'esm_parachuting_landing_lp', 'esm_amb_rain', 'esm_act_throw_light', 'esm_action_rescue_needle', 'esm_ui_mark_enemy', 'esm_duquan_alarm', 'vector_media', 'esm_strop_slide_loop', 'rpg_media', 'esm_supply_package_open', 'p90_media', 'esm_rpg_explosion', 'dagger', 'esm_act_parachuting', 'esm_airdrop_fall', 'esm_ui_countdown_warning', 'esm_amb_thunder_01', 'urb_media', 'ak47_act_media', 'esm_skills_detection_running', 'esm_ui_general_map_select', 'esm_item_bag_pickup', 'esm_skills_penetrate_bomb_insert', 'esm_ui_general_buy_success', 'esm_ui_mission_accept', 'kag6_media', 'esm_skills_drone_healing', 'esm_skills_turret_deploy', 'esm_strop_loosen', 'esm_skills_penetrate_bomb_penetrate', 'rpg', 'esm_item_door_metal_open', 'esm_ui_general_banner', 'esm_ui_demo_general_click', 'esm_skills_turret_destroyed', 'esm_wpn_grenade_impact', 'esm_ui_general_character_configure_02', 'katana_media', 'esm_nv_ui_general_click', 'ar97', 'esm_rpg_flyby', 'esm_skills_paticle_matrix_disappear', 'esm_transport_plane_star', 'scar_media', 'esm_item_bandage', 'handaxe_media', 'ak47_media', 'esm_airdrop_disappear', 'esm_parachuting_ground', 'esm_nv_ui_general_tipesm_cutscene_plane_plot', 'p90', 'esm_skills_turret_attack', 'inp9', 'esm_nv_ui_general_zan_bobao', 'esm_skills_detection_destroyed', 'm9a3_media', 'kag6_v6_unstable_media', 'esm_skills_rockets_take_out', 'esm_skills_rockets_whoosh', 'esm_skills_shockwave_pull', 'esm_skills_penetrate_bomb_explosion', 'kala_media', 'urb', 'vehicle_pickup', 'vehicle_common_media', 'esm_skills_shockwave_explosion', 'kala', 'esm_item_box_open', 'esm_ui_general_map', 'kag6_act_media', 'vo_saa_en', 'esm_item_bullet_pickup', 'esm_skills_gas_grenade_explosion', 'esm_wpn_grenade_using_a', 'esm_act_throw_strong', 'glock_media', 'esm_item_coin_pickup', 'esm_wpn_grenade_explode', 'esm_character_resurrection', 'esm_ui_hotzone_enemyteam_occupied', 'esm_skills_zero_jifengzhan_attack', 'esm_ui_general_weapon_achievement', 'esm_wpn_napalm_grenade_burn', 'esm_gamemode_xujing_ui_hall_background_meteorite', 'esm_nv_ui_general_back', 'esm_ui_general_use_error', 'esm_item_door_metal_close', 'esm_skills_paticle_matrix_expand', 'esm_hit_feedback', 'esm_player_heartbeat', 'eagle_act_media', 'esm_act_swing', 'baseball_bat_media', 'esm_action_reviving', 'fst_slide', 'esm_item_firearms_part_pickup', 'esm_wpn_medic_drone_fly_loop'}
SOUND_FADEOUT_INVSCURE: int = 4
SOUND_FADEOUT_LINEAR: int = 0
SOUND_FADEOUT_SCURRE: int = 3
SOUND_FADEOUT_SINE: int = 1
SOUND_FADEOUT_SINERECIP: int = 2
SoundCache: dict = {(211, 'zh'): {'self_event': 'Play_music', 'other_event': 'Play_music', 'struct_bnk': 'music_basic_es'}}
_GUN_GENERAL_BNK: tuple = ('gun_general', 'gun_general_media', 'voice_message_media', 'ccmini_test', 'voice_sys', 'gun_fire_int_media', 'gun_bullet_drop_media')

class LogManager(object):
    asyncwrite: bool = False
    created_modules: set = {'CombatAvatarSquadFight', 'GameLogicRookieGuide', 'ReplayGameLogicSniperMode', 'RobotCombatAvatarNowhere', 'BaitBombField', 'ClientAreaEntity', 'ReplayCombatAvatarSniperMode', 'CombatTeamEntity_SquadFight', 'AttachScoutArrowEntity', 'bhttp_client.BHttpClient', 'AdsShield', 'BaseSupply', 'CombatAvatarMobaZombie', 'IceWallField', 'ClientSpace', 'CombatTeamEntity_BigHead', 'PlayerCombatAvatarPlacement', 'ControlTargetBase', 'RepelBomb', 'Formula', 'GameLogicNowhere', 'ReplayRoomGameLogicSquadFight', 'VehicleCannon', 'HumanoidMonsterMonsterAI', 'ReconDrone', 'CombatAvatar', 'RobotCombatAvatarMoba', 'PlayerCombatAvatarSniperMode', 'CombatAvatarMobaFirst', 'PlayerCombatAvatarHotSpotBase', 'EnergyStronghold', 'Bomb', 'Preload', 'GameLogicBigHead', 'GrenadeLauncherBomb', 'LeadWayEntity', 'ReplayCombatAvatarShootingRange', 'GameLogicGrandTheft', 'ReplayGameLogicMobaZombie', 'PlayerCombatAvatarSquadFightBase', 'Shop', 'MovingPlatformTelpher', 'ClientEntity', 'HelenRobotCombatAvatarMoba', 'SuicideDrone', 'ThermiteBomb', 'PhyBall', 'ReplayCombatAvatarMoba', 'FireWallField', 'RobotCombatAvatarRookieGuideNew', 'PlayerCombatAvatarRookieGuideNew', 'ReplayCombatAvatarSquadFight', 'ReplayDummy', 'TrackBomb', 'AmmoBox', 'CombatAvatarPlacement', 'Supply', 'asynctimer', 'PlayerAvatar', 'ServerUtil', 'PlayerCombatAvatar', 'RobotCombatAvatarShootingRange', 'StropEntity', 'CombatAvatarBigHead', 'CureUav', 'HelenRobotCombatAvatarNoWhere', 'SearchContractBox', 'RobotCombatAvatarMobaZombieAi', 'InteractionEntity', 'NewCrystalMonster', 'CombatTeamEntity_Moba', 'SaveMachine', 'ReplayCombatAvatarMobaZombie', 'NavigateCannon', 'ATM', 'RobotCombatAvatarBigHead', 'SatellitePlaceItem', 'Arrow', 'RestrictWall', 'WaterSnare', 'CDrone', 'Vehicle', 'MonsterCommon', 'OccupyContractTarget', 'ScoutField', 'Helicopter', 'HolographicRobotMoba', 'ReplayGameLogicPlacement', 'TrackTrapBomb', 'HolographicRobot', 'CombatAvatarShootingRange', 'ReplayGameLogicGrandTheft', 'Pubsub', 'Space', 'ReplayGameLogicNowhere', 'CombatAvatarMobaFirstNew', 'GameLogicRookieGuideNew', 'CombatAvatarGrandTheft', 'PlayerCombatAvatarMobaZombie', 'Account', 'PlayerCombatAvatarNowhere', 'ValDrone', 'CombatAvatarHotSpot', 'DeathBoxDummyEntity', 'CombatAvatarGunFight', 'CrystalMonster', 'Airdrop', 'ReplayRoomGameLogicMoba', 'RobotCombatAvatarMobaFirstNew', 'GateClient', 'MoveFireWall', 'Oilbox', 'ScoutTotemField', 'NewMonsterCommon', 'RPGMissile', 'SafeBox', 'RobotCombatAvatarATMGuard', 'RobotCombatAvatarMobaZombie', 'PlayerCombatAvatarClientOffline', 'ReplayCombatAvatar', 'PlayerEntity', 'ChaosUAV', 'SyncTransEntity', 'ReplayCombatAvatarGunFight', 'BigHeadCalculationDoll', 'DestructibleCollections', 'ScoutArrow', 'GameLogicSquadFight', 'MovingShield', 'CombatAvatarHotSpotBase', 'FreeviewDummyEntity', 'RobotCombatAvatarSniperMode', 'GameLogicPlacement', 'RobotCombatAvatarGrandTheft', 'CombatAvatarSquadFightBase', 'ActivityItem', 'ReplayRoomGameLogicBase', 'Missile', 'MonsterAI', 'CalculationDoll', 'MonitorMissile', 'AsioServerProxy', 'PlayerCombatAvatarHotSpot', 'Stronghold', 'GameLogicShootingRange', 'PlayerCombatAvatarGrandTheft', 'CombatAvatarGunFightBase', 'KcpClient', 'RobotCombatAvatarSquadFight', 'ReplayRoomGameLogicBigHead', 'ClientEnv', 'CombatTeamEntity_GunFight', 'ReplayCombatAvatarMobaFirstNew', 'ThroughBomb', 'ReplayCombatAvatarHotSpot', 'GameLogicMobaZombie', 'GameLogicGunFight', 'Building', 'mobilerpc.SimpleAsyncBHTTPClient', 'DummyCombatAvatar', 'ReplayGameLogicGunFight', 'ReplayCombatAvatarNowhere', 'ExplodingArrowEntity', 'RobotCombatAvatarHotSpot', 'NinjaBeacon', 'ReplayCombatAvatarGrandTheft', 'BarrieCannon', 'ReplayRoomGameLogicMobaZombie', 'CombatTeamEntity_ShootingRange', 'ReplayGameLogicMobaFirst', 'TrackBomb2025', 'PlayerCombatAvatarGunFightBase', 'CombatItemEntity', 'GameLogicMoba', 'CombatAvatarMoba', 'PlayerCombatAvatarShootingRange', 'RobotCombatAvatarRookieGuide', 'GameLogicClientOffline', 'PlayerCombatAvatarRookieGuide', 'CombatAvatarRookieGuideNew', 'Crow', 'Entity', 'MagicField', 'PlayerCombatAvatarSquadFight', 'AircraftPlane', 'Model', 'RpcIndexer', 'SpaceSnare', 'PlayerCombatAvatarMoba', 'PlaceEntity', 'SaveDrone', 'ReplayGameLogicHotSpot', 'PlayerCombatAvatarBigHeadBase', 'AvatarEntity', 'PortableShop', 'ReplayGameLogicShootingRange', 'CommonMoveItem', 'ShockField', 'ClueBox', 'VehicleAirplane', 'CombatTeamEntity_GrandTheft', 'AsioGateClient', 'FollowShieldMagicField', 'BigHeadMostKillDummyEntity', 'ReplayGameLogicBase', 'SamuraiBlockField', 'ReplayGameLogicMoba', 'CombatTeamEntity_Nowhere', 'ModelCache', 'CombatAvatarBigHeadBase', 'CombatTeamEntity_SniperMode', 'ReplayCombatAvatarMobaFirst', 'PlayerCombatAvatarMobaFirst', 'CombatTeamEntity', 'GameLogicMobaFirstNew', 'ATMGuardMonster', 'RobotCombatAvatarMobaFirst', 'SaveDroneDummyEntity', 'CombatTeamEntity_HotSpot', 'Telnet', 'GameLogicSniperMode', 'OccupyContractTargetNew', 'CombatTeamEntity_MobaZombie', 'ItemSpaceSnare', 'GameLogicBase', 'EmoteTree', 'ReplayCombatAvatarBigHead', 'CombatAvatarRookieGuide', 'ReplayRoomGameLogicSniperMode', 'CombatAvatarSniperMode', 'AttackDrone', 'StickyObjectEntity', 'ReplayGameLogicBigHead', 'SwordSpirit', 'ReplayGameLogicSquadFight', 'PlayerCombatAvatarMobaFirstNew', 'TotemField', 'PlayerCombatAvatarGunFight', 'CureUavFix', 'Doll', 'Crack', 'BlastBomb', 'ClusterBomb', 'HolographicRobotNowhere', 'GameLogicHotSpot', 'RobotCombatAvatarGunFight', 'DollLike', 'CombatAvatarNowhere', 'ReplayRoomGameLogicGunFight', 'HolographicHitTargetDummyEntity', 'server.EntityManager', 'StropUAV', 'CombatAvatarClientOffline', 'PlayerCombatAvatarBigHead', 'FollowerInteractionEntity', 'CommonItem', 'server.EntityFactory', 'ReplayGameLogicMobaFirstNew', 'GameLogicMobaFirst', 'Avatar'}
    custom_handler: NoneType = None
    log_handle: str = 'stream'
    log_level: int = 10
    log_tag: str = ''
    run_tag: str = ''
    sa_log_tag: str = ''
    sys_logger: NoneType = None

    def _create_handler(logger): ...
    def get_logger(moduleName): ...
    def get_sa_logger(): ...
    def run_message(message): ...
    def set_asyncwrite(asyncwrite): ...
    def set_custom_handler(handler): ...
    def set_log_handle(handle): ...
    def set_log_level(lv): ...
    def set_log_tag(log_tag): ...
    def set_run_tag(run_tag): ...
    def set_sa_log_tag(tag): ...

class PreloadSound(Singleton):
    _instance: PreloadSound = <PreloadSound(0x0x6f5396a950)>
    logger: Logger = <Logger Preload (DEBUG)>

    def Destroy(): ...
    def GetAllBnk(self): ...
    def LoadBattleBnk(self): ...
    def OnDestroy(self): ...
    def OnLoadMediaCallback(self, bnk): ...
    def OnStoryTick(self, dt): ...
    def UploadLoadBnkLog(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class Singleton(object):
    def Destroy(): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class SoundManager(Singleton):
    _instance: SoundManager = <SoundManager(0x0x7040b53790)>

    def DecGameObjectRefCount(self, gid): ...
    def Destroy(): ...
    def GetEventLength(self, sid): ...
    def GetEventVolume(self, event): ...
    def GetGameObjectID(self, event_id): ...
    def IncGameObjectRefCount(self, gid): ...
    def KeyOff(self, sid, name): ...
    def LoadBattleBnk(self): ...
    def LoadHallMusic(self): ...
    def LoadHallMusicDefault(self): ...
    def LoadHallMusicSpecific(self, sound_id, check_dlc=True): ...
    def LoadLoadingMusicDefault(self): ...
    def LoadMedia(self, filename): ...
    def LoadNeedfulBnk(self): ...
    def OnAudioSessionRouteChange(self, session_route): ...
    def OnDestroy(self): ...
    def OnRefreshSoundDlcStatus(self, dlc_id, status): ...
    def PauseEvent(self, sid, paused): ...
    def Play2DEventWithSwitches(self, filename, event, switch_dict, vol=1.0): ...
    def Play3DEvent(self, filename, event, position, vol, direction=None): ...
    def Play3DEventFollowTarget(self, filename, event, entity, off_pos, vol=1.0): ...
    def Play3DEventFollowTargetBySoundId(self, sound_id, entity, off_pos=<0.0000, 0.0000, 0.0000>, vol=1.0): ...
    def Play3DEventFollowTargetWitchSwitches(self, filename, event, entity, off_pos, switch_dict, vol=1.0): ...
    def Play3DEventWithSwitch(self, filename, event, position, switchGroup, switchValue, direction=None, vol=1.0): ...
    def Play3DEventWithSwitches(self, filename, event, position, switch_dict, direction=None, vol=1.0): ...
    def PlayBGM(self, type, event_id, vol=1.0): ...
    def PlayEffect(self, filename, sound, vol=1.0, pos=None): ...
    def PlayEvent(self, filename, event, volscale=1.0): ...
    def PlayEventById(self, event_id, position=None, lang='zh', switch_dict=None, param_dict=None, direction=None, is_3d=True, vol=1.0, follow_entity=None, gameobjectid=None): ...
    def PlayEventSound(self, event_id, file_name, position=None, switch_dict=None, param_dict=None, fromOther=False, gameObjectID=None, followEntity=None, lang='zh', is_3d=True, direction=None, vol=1.0): ...
    def ResetMediaPath(self): ...
    def SetEventParameter(self, sound_id, name, value): ...
    def SetEventVolume(self, event, vol): ...
    def SetGameObjectSwitch(self, sound_id, name, value): ...
    def SetGlobalParameter(self, name, value): ...
    def SetNextGameObjectIDByCurEvent(self, event_id): ...
    def SetScalingFactor(self, event_id, factor): ...
    def SetState(self, name, value, refresh=True): ...
    def SetSwitch(self, event_id, type, value): ...
    def SetupGlobalRtpc(self): ...
    def StopBGM(self, type): ...
    def StopEvent(self, sid): ...
    def UnLoadEventBySoundId(self, sound_id, fadeout_time=0, fade_type=0): ...
    def UnLoadMedia(self): ...
    def UnLoadMediaFile(self, file_name): ...
    def getSoul(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class StoryTick(object):
    _instance: StoryTick = <gclient.framework.util.story_tick.StoryTick object at 0x7005e37fd0>

    def Add(self, func, frames=0): ...
    def Remove(self, func): ...
    def doAdd(self, func, frames): ...
    def doRemove(self, func): ...
    def onTick(self, _, dtime): ...


