# module: gclient.gameplay.logic_moba_zombie.avatarmembers.cimp_zombie_talent

import comp_talent
import six2
import time_util

PARA_ON_GROUND_STAGE: tuple = (0, 9)

class PlayerCombatAvatarMember(PlayerCombatAvatarMember):
    def AddLowHpEffect(self, tech_state, material_rank_id, duration): ...
    def CancelExposeKilledEnemyTimer(self): ...
    def CancelFeelHpTimer(self): ...
    def CancelFeelSurmount1Timer(self): ...
    def CancelLowHpEffectTimer(self): ...
    def ChangeClientAmmo(self, guid, delta): ...
    def CheckCrisisAwarenessInSight(self, target_id, offset_x=0, offset_y=0): ...
    def CheckCrisisAwarenessTimer(self): ...
    def ClearLowHpEffect(self, tech_state, material_rank_id): ...
    def CrisisAwarenessTickTimer(self): ...
    def DealForAdsMarkPos(self, is_ads): ...
    def DealForFeelSurmount3(self, enter): ...
    def ExposeKilledTeamEnemyPos(self, info): ...
    def ExposeKilledTeamEnemyPosTick(self, info): ...
    def FeelLowHpEnemyTick(self, param): ...
    def FeelSurmount1Timer(self): ...
    def GetEmptyFragileTalentSlot(self): ...
    def GetEmptyTalentSlot(self): ...
    def GetProtoFromTalentCode(self, talent_code): ...
    def GetSpellKaCount(self): ...
    def GetTacticalArmorLevel(self): ...
    def GetTacticalColorLevel(self): ...
    def GetTacticalLevelColorOpacity(self, is_bg=False): ...
    def GiveUpRandomTalent(self): ...
    def HasTalent(self, talent_id): ...
    def HasTalentCode(self, talent_code): ...
    def HasTalentId(self, talent_id): ...
    def HideEnemyTopLogo(self): ...
    def IsFullTalentMozu(self): ...
    def IsSkillTalentFull(self): ...
    def OnAdsChangeForTalent(self, is_ads): ...
    def OnAvatarCastSpell(self, result): ...
    def OnGainTalentArmorEnergy(self): ...
    def OnGainTalentEnemyTrack(self): ...
    def OnGainTalentFeelLowHp(self): ...
    def OnGainTalentFeelSurmount1(self): ...
    def OnGainTalentLOCK(self): ...
    def OnHolographicMarkChange(self, key, old, new): ...
    def OnLoseTalentArmorEnergy(self): ...
    def OnLoseTalentEnemyTrack(self): ...
    def OnLoseTalentFeelLowHp(self): ...
    def OnLoseTalentLOCK(self): ...
    def OnLoseTalentSurmount1(self): ...
    def OnOpenAdsShield(self, is_open): ...
    def OnPlayerTalentSlotChangeForTips(self, key, old, new): ...
    def OnRealAdsChangeForTalent(self, is_ads): ...
    def RefreshHolographicMark(self): ...
    def RemoveKilledTeamEnemyPos(self): ...
    def ShowBeCuedForTeammate(self): ...
    def ShowEnemyTopLogoInRange(self, params): ...
    def ShowHighAlartInfo(self, caster): ...
    def _CancelCrisisAwarenessTimer(self): ...
    def _CheckNeedTickCrisisAwareness(self): ...
    def _on_set_tactical_energy(self, old): ...
    def _on_set_tactical_level(self, old): ...
    def _on_set_talent_codes(self, old): ...
    def _on_set_talent_exp(self, old): ...
    def _on_set_talent_sensing_info(self, old): ...
    @property
    def hero_skill_talent(self): ...    @property
    def talent_exp_proto(self): ...

