# module: gclient.gameplay.logic_shootingrange.challenge_rank_data_mgr

import consts
import copy
import events
import rank_data
import six2
import time

class ChallengeRankDataUtil(object):
    CLIENT_REQUEST_RANK_DATA_TIME_CACHE: int = 100
    _instance: NoneType = None

    def ClearChallengeCache(self): ...
    def GetChallengeRankDataByRankKey(self, rank_key): ...
    def GetMyChallengeRankData(self, rank_key): ...
    def GetRankPercent(self, rank_key, score): ...
    def GetRankingByScore(self, rank_key, score): ...
    def GetResultDataIsRecord(self, rank_info_id): ...
    def MergeChallengeRankData(self, gun_id): ...
    def OnGetChallengeRankData(self, rank_key, rank_list): ...
    def OnGetRankPercent(self, rank_key, score, percent): ...
    def OnSpaceLoaded(self, spaceno): ...
    def PushChallengeRankData(self, gun_id, rank_info): ...
    def ResetChallengeRankScoreList(self, rank_key, rank_list): ...
    def TryGetChallengeRankData(self, rank_key, callback=None, ignore_time=False): ...
    def TryGetRankPercent(self, rank_key, score, callback): ...
    def _FindBestRecordForAllGun(self, add_data, pre_my_rank_info): ...
    def _MergeAllChallengeRankData(self): ...
    def _MergeTargetGunChallengeRankData(self, gun_id): ...
    def _ReadjustRankList(self, rank_list): ...
    def _RefreshMyBestRankInfo(self, rank_key, rank_list): ...
    def _SetMergedChallengeRankData(self, rank_key, rank_list): ...

class RankKey(enum):
    GrandTheft: int = 13
    GrandTheftActivity: int = 10
    GrandTheftDaily: int = 14
    GrandTheftTopCoin: int = 15
    Kill: int = 3
    Qualifying: int = 1
    ShootingChallenge: int = 1000
    ShutterIslandEnergy: int = 8
    SquadFightKill: int = 6
    SquadFightQualifying: int = 5
    ZombieWin: int = 16
    name_to_values: dict = {'Qualifying': 1, 'Kill': 3, 'SquadFightQualifying': 5, 'SquadFightKill': 6, 'ShutterIslandEnergy': 8, 'GrandTheftActivity': 10, 'GrandTheft': 13, 'GrandTheftDaily': 14, 'GrandTheftTopCoin': 15, 'ZombieWin': 16, 'ShootingChallenge': 1000}
    value_to_names: dict = {1: 'Qualifying', 3: 'Kill', 5: 'SquadFightQualifying', 6: 'SquadFightKill', 8: 'ShutterIslandEnergy', 10: 'GrandTheftActivity', 13: 'GrandTheft', 14: 'GrandTheftDaily', 15: 'GrandTheftTopCoin', 16: 'ZombieWin', 1000: 'ShootingChallenge'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class SingletonMeta(type):
    mro: method_descriptor = <method 'mro' of 'type' objects>


