# module: gclient.gameplay.logic_base.entities.cbuilding

import MObject
import MType
import Timer
import cconst
import events
import formula
import math
import six2
import time

DOOR_LEFT_YAW: tuple = (1.57, -1.57)
DOOR_RIGHT_YAW: tuple = (-1.57, 1.57)

class Building(ClientAreaEntity):
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = True
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = True
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = False
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    logger: Logger = <Logger Building (DEBUG)>

    def AttachToMaster(self): ...
    def BindDoor(self, res_name): ...
    def DetachFromMaster(self, at_attach_id=None): ...
    def GetDoor(self, no): ...
    def GetDoorByName(self, res_name): ...
    def GetDoorNo(self, res_name): ...
    def GetHitIdx(self, hit_pos, target_name): ...
    def GetLevelName(self): ...
    def GetWidgetByNo(self, no): ...
    def IsAttachLoaded(self): ...
    def ProcessDoorType(self): ...
    def ShowModel(self): ...
    def TryBindDoors(self): ...
    def UnbindDoor(self, res_name): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_set_at_attach_id(self, old): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    def is_deactived(self): ...
    def is_destroyed(self): ...
    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def pos(self): ...    @property
    def position(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    @property
    def yaw(self): ...
class CBuilding(IBuilding):
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...

class CDoor(IDoor):
    IS_CUSTOM_TYPE: bool = True
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = True
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = False
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    SetAnimDestroyed: AsyncDescriptor = <gshare.async_util.AsyncDescriptor object at 0x6f780cbd90>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def AddHealth(self, delta): ...
    def Bind(self, entity): ...
    def ChangeDoorContactForSprint(self, is_change): ...
    def ChangeState(self, state): ...
    def ContractRb(self, trigger_info): ...
    def DealPlayersCollisionForPhysicInteraction(self): ...
    def DecHealth(self, delta): ...
    def DoInitRigidBody_Single(self): ...
    def EnableSingleDoorPhysic(self, enable=True): ...
    def GetHealth(self): ...
    def GetState(self): ...
    def InitRigidBody_Single(self): ...
    def Initialize(self, building, no): ...
    def IsAlive(self): ...
    def IsRecentStateChanged(self): ...
    def IsValid(self): ...
    def PlayDieEffect(self): ...
    def PlayKickDoorEffect(self): ...
    def RotateDoor(*args, **kwargs): ...
    def SetDoorDestroyed(self): ...
    def SetDoorMaterial(self): ...
    def SetDoorState(self, oldvalue): ...
    def SetHealth(self, old): ...
    def TryBind(self): ...
    def Unbind(self): ...
    def _SetDoorStateImpl_Animation(self, oldvalue): ...
    def _SetDoorStateImpl_Tick(self, oldvalue): ...
    def _initProperty(self, data): ...
    def destroy(self): ...
    @property
    def is_alive(self): ...    def is_destroyed(self): ...
    def is_inited(self): ...
    def items(self): ...
    def keys(self): ...
    def on_setattr(self, key, old, new): ...
    @property
    def owner(self): ...    @property
    def position(self): ...    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...
    @property
    def yaw(self): ...
class CDoors(IDoors):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gclient.gameplay.logic_base.entities.cbuilding.CDoor'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class ClientAreaEntity(ClientEntity):
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    logger: Logger = <Logger ClientAreaEntity (DEBUG)>

    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    def is_deactived(self): ...
    def is_destroyed(self): ...
    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def pos(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    @property
    def yaw(self): ...
class DoorInitState(enum):
    BIND_ENTITY: int = 2
    BIND_OWNER: int = 1
    DESTROYED: int = 3
    EMPTY: int = 0
    name_to_values: dict = {'EMPTY': 0, 'BIND_OWNER': 1, 'BIND_ENTITY': 2, 'DESTROYED': 3}
    value_to_names: dict = {0: 'EMPTY', 1: 'BIND_OWNER', 2: 'BIND_ENTITY', 3: 'DESTROYED'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class DoorState(enum):
    DOOR_STATE_CLOSED: int = 0
    DOOR_STATE_INSIDE: int = 2
    DOOR_STATE_OUTSIDE: int = 1
    name_to_values: dict = {'DOOR_STATE_CLOSED': 0, 'DOOR_STATE_OUTSIDE': 1, 'DOOR_STATE_INSIDE': 2}
    value_to_names: dict = {0: 'DOOR_STATE_CLOSED', 1: 'DOOR_STATE_OUTSIDE', 2: 'DOOR_STATE_INSIDE'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class DoorType(enum):
    LEFT: int = 1
    RIGHT: int = 2
    name_to_values: dict = {'LEFT': 1, 'RIGHT': 2}
    value_to_names: dict = {1: 'LEFT', 2: 'RIGHT'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class EntityMasterComponent(IEntityMasterComponent):
    def AttachToMaster(self): ...
    def DetachFromMaster(self, at_attach_id=None): ...
    def IsAttachLoaded(self): ...
    def _on_set_at_attach_id(self, old): ...

class IBuilding(object):
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...

class IDoor(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def AddHealth(self, delta): ...
    def ChangeState(self, state): ...
    def DecHealth(self, delta): ...
    def _initProperty(self, data): ...
    @property
    def is_alive(self): ...    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class IDoors(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gshare.ibuilding.IDoor'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class IdManager(object):
    def bytes2id(bytes): ...
    def genid(): ...
    def id2bytes(uid): ...
    def id2str(uid): ...
    def is_valid_id(entityid): ...
    def str2id(string): ...

class enum(object):
    name_to_values: dict = {}
    value_to_names: dict = {}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...


def Async(tag=0): ...
def AsyncTick(func): ...
def Components(*components, **kwargs): ...
def Property(name, default, flag=2): ...
def with_tag(*args): ...

