# module: gclient.gameplay.logic_base.entities.chelicopter

import MHelper
import MPhysics
import MType
import cconst
import effect_data
import formula
import math
import replay_util
import six2
import vehicle_helicopter_comp

EPS: float = 0.0001

class Helicopter(Vehicle):
    AllVehicles: list = []
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = True
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = True
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = True
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = True
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    logger: Logger = <Logger Helicopter (DEBUG)>

    def AddParachuteModel(self, is_add): ...
    def AddStoryTick(self, func, frames=0): ...
    def AdjustPitchRollInAir(self): ...
    def ApplyForceInWorldFrameAtStart(self, add=True): ...
    def AttachToMaster(self): ...
    def CacheModel(self): ...
    def CacheTires(self): ...
    def CalculateWheelRotationAngle(self, count): ...
    def CallServerDrive(self): ...
    def CanHearSoundByDist(self): ...
    def CanLeanOut(self, seat): ...
    def CanLeanOutForCollision(self, seat): ...
    def CanLeanOutForVehicleSeat(self, seat): ...
    def CanPlayEffectByDist(self): ...
    def CancelCheckWaterHeightTimer(self): ...
    def CancelHelicopterFlyingTimer(self): ...
    def ChangeBrokenMaterial(self): ...
    def CheckHelicopterTimer(self): ...
    def CheckLanded(self, old_is_start): ...
    def CheckPlayOilAlertSound(self): ...
    def CheckResetPositionForUnderGroundWheels(self): ...
    def CheckShowHelicopterPropellerModels(self): ...
    def CheckSoundPlay(self): ...
    def CheckStartTickWheelRotation(self): ...
    def CheckWarningEffect(self): ...
    def CheckWheelsUnderGround(self): ...
    def ClearAllStoryTick(self): ...
    def ClearDebugOffPosition(self): ...
    def ClearDriveVal(self): ...
    def ClearEffectByIdx(self, name, idx): ...
    def ContactedRb(self, contact_info): ...
    def CreatePhysicsFilter(self, local=True): ...
    def CreateStickyObject(self, guid): ...
    def CreateVehicleComponent(self, config_id=None): ...
    def DestroyParachuteModel(self): ...
    def DestroyStickyObject(self, guid): ...
    def DestroyTires(self): ...
    def DetachFromMaster(self, at_attach_id=None): ...
    def DoRise(self, v): ...
    def Drive(self, turning, forward, hand_brake=0): ...
    def DriveForward(self, val): ...
    def DriveTurning(self, val): ...
    def DriverOff(self, old): ...
    def DriverOn(self): ...
    def EnableMotorHandIK(*args, **kwargs): ...
    def EnableVehicleCCT(self, is_enable=True): ...
    def EnableVehicleSound(self, enable): ...
    def FixHelecopterTurnOver(self): ...
    def FixPositionOnSky(self): ...
    def FixVehicleRotation(self): ...
    def GearChangedResponse(self, to_gear, from_gear): ...
    def GetAllSeatIndex(self): ...
    def GetCCTParam(self, name): ...
    def GetCCTParamRange(self, name): ...
    def GetChassisShapesNumber(self): ...
    def GetDriveStatus(self, seat): ...
    def GetFaction(self): ...
    def GetHelicopterHeightDiff(self): ...
    def GetHelicopterRPM(self): ...
    def GetHitTireIndex(self, pos): ...
    def GetMapTagId(self, marker=None): ...
    def GetOffPosition(self, seat, guarantee=False): ...
    def GetRealCCTParam(self, name): ...
    def GetReplaceModelID(self, model_id): ...
    def GetRotationFromAToB(self, v1, v2): ...
    def GetSceneNodeId(self, marker=None): ...
    def GetSeatBoneNameBySeat(self, seat): ...
    def GetSeatById(self, avatar_id): ...
    def GetVacantPassengerSeat(self): ...
    def GetVacantSeatForBigger(self, cur_seat): ...
    def HasVacantSeat(self): ...
    def HelicopterUpdateCode(self): ...
    def HideAttachTargetRb(self, is_hide): ...
    def InitEffectInfo(self): ...
    def IsAllWheelsInAir(self): ...
    def IsAttachLoaded(self): ...
    def IsBackSeat(self, seat): ...
    def IsBroomUpCollision(self): ...
    def IsHelicopterWingDamaged(self): ...
    def IsInAir(self): ...
    def IsLeftSeat(self, seat): ...
    def IsMotor(self): ...
    def IsMoving(self): ...
    def IsMovingForward(self): ...
    def IsSeatOccupied(self, seat): ...
    def IsVehicleModelInStuck(self): ...
    @property
    def IsVisible(self): ...    def LoadConfigFromSunshine(self, meta, config_data, vertices_data): ...
    def LoadTireModels(self): ...
    def MakeOffPosFarther(self, pos): ...
    def OffPassenger(self, avatar_id): ...
    def OnCreateInSunshine(self, objMeta, data): ...
    def OnEnterWater(self, snare): ...
    def OnExitWater(self, snare): ...
    def OnLoadModel(self): ...
    def OnPassenger(self, avatar_id): ...
    def OnRemoveInSunshine(self): ...
    def OnSelectedInSunshine(self): ...
    def OnSunshinePropertyAdded(self, name, vals): ...
    def OnSunshinePropertyChanged(self, name, value): ...
    def OnSunshinePropertyDeleted(self, name): ...
    def OnUnselectedInSunshine(self): ...
    def OnUpdatePosition(self, pos): ...
    def OnVehicleHitSound(self, sound_id, pos, kph): ...
    def OnVehicleOilChanged(self): ...
    def OnVehiclePlaySoundWithKphEvent(self, sound_id, pos, kph): ...
    def PlayAccelSound(self): ...
    def PlayBackCarLightEffect(self, enable): ...
    def PlayDamagedSmokeEffect(self, play=True): ...
    def PlayEffectByDrivingState(self): ...
    def PlayEffectByDrivingStateForHelicopter(self): ...
    def PlayExplodeEffect(self): ...
    def PlayHelicopterEffect(self): ...
    def PlayHelicopterEngineSound(self, play): ...
    def PlayHelicopterStopSound(self, play): ...
    def PlayHitSound(self): ...
    def PlayHornSound(self): ...
    def PlayLightEffect(self, enable): ...
    def PlayStartSound(self): ...
    def PlayStopSound(self): ...
    def PlayTireSound(self): ...
    def PlayWheelEffectBySpeed(self, enable): ...
    def QueueRefreshConfigDataInSunshine(self): ...
    def ReduceVehiclePeakTorque(self): ...
    def RefreshCCTConfig(self): ...
    def RefreshConfigDataInSunshine(self): ...
    def RefreshHelicopterForwardSpeed(self): ...
    def RefreshHelicopterRotation(self): ...
    def RefreshHelicopterSideSpeed(self): ...
    def RefreshHelicopterUpSpeed(self): ...
    def RefreshLocalMode(self): ...
    def RefreshSoundByDist(self): ...
    def RemoveStoryTick(self, func): ...
    def ResetNanTransform(self, pos, rot): ...
    def ResetNormalMaterial(self): ...
    def SetCCTParam(self, name, value): ...
    def SetCCTParamRange(self, name, min_value, max_value): ...
    def SetDeadMaterial(self): ...
    def SetHandBrake(self, val): ...
    def SetHelicopterScrew(self): ...
    def SetLocalMode(self, local): ...
    def SetNormalMaterial(self): ...
    def SetTireMaterial(self): ...
    def SetVehicleForce(self, force): ...
    def SetVehicleTorque(self, torque): ...
    def SetupVehicleComponent(self): ...
    def ShowModel(self): ...
    def StopHornSound(self): ...
    def StopOilAlertSound(self): ...
    def StopTireSound(self): ...
    def SwitchSyncMode(self): ...
    def TickEffect(self): ...
    def TickHelicopterEngineSound(self): ...
    def TickLocalVehicleGraph(self, dt=0): ...
    def TickWheelRotation(self): ...
    def TryBindPassenger(self, avatar): ...
    def UpdateDriverGraphInfo(self): ...
    def UpdateMotorGraphInfoFromCCT(self, dt): ...
    def _CancelTickEffect(self): ...
    def _CancelTickWheelRotation(self): ...
    def _CancelWheelUnderGroundTimer(self): ...
    def _CheckCanChangeSwimState(self, snare, enter): ...
    def _CheckFlyingAction(self): ...
    def _CheckPosValid(self, pos): ...
    def _CheckSoundTimer(self): ...
    def _CheckTireSoundPlay(self): ...
    def _CheckWaterHeight(self): ...
    def _CheckWheelLongitudinalSlipForEffect(self): ...
    def _GetDustEffectLastPos(self): ...
    def _GetHelicopterProto(self): ...
    def _GetOffPositionImp(self, pos): ...
    def _GetSoundPath(self, sound_id): ...
    def _HelicopterForwardType(self, v): ...
    def _HelicopterTurningType(self, v): ...
    def _InitEffectImpl(self, name, suffix_bits=None): ...
    def _InitHelicopterData(self): ...
    def _PlayEffectImpl(self, name, enable, time=-1, ensure_play=False): ...
    def _PlayEffectImplInWorld(self, name, enable, pos, time=-1): ...
    def _PlayWheelEffectImpl(self, name, enable_list, time=-1): ...
    def _ProcessOneTireMaterail(self, part_list, material_list): ...
    def _SetForwardType(self, val): ...
    def _SetHelicopterDownForce(self): ...
    def _SetHelicopterForceDown(self): ...
    def _SetHelicopterRemainHeightForce(self): ...
    def _SetHelicopterSyncInfo(self, steer_angle): ...
    def _SetHelicopterUpForce(self): ...
    def _SetTurningType(self, val): ...
    def _StopPlayDrivingEffect(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_set_at_attach_id(self, old): ...
    def _on_set_driving_state(self, old): ...
    def _on_set_gear(self, old): ...
    def _on_set_horn(self, old): ...
    def _on_set_hp(self, old): ...
    def _on_set_is_airdrop_landed(self, old): ...
    def _on_set_is_landed(self, old): ...
    def _on_set_oil(self, old): ...
    def _on_set_physx_handbrake(self, old): ...
    def _on_set_proto_id(self, old): ...
    def _on_set_sync_mode(self, old_val): ...
    def _on_sunshine_set_proto_id(self, new): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    @property
    def capacity(self): ...    @property
    def cur_speed(self): ...    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    @property
    def driver(self): ...    @property
    def driver_id(self): ...    def entity_method(self, md5, index, args): ...
    @property
    def forward_speed(self): ...    def get_gtick(self): ...
    @property
    def height(self): ...    @property
    def helicopter_max_height(self): ...    @property
    def hit_kill_speed(self): ...    def init_from_dict(self, *args, **kwargs): ...
    @property
    def is_alive(self): ...    def is_deactived(self): ...
    def is_destroyed(self): ...
    @property
    def is_helicopter(self): ...    @property
    def is_invincible(self): ...    @property
    def max_health(self): ...    @property
    def max_oil(self): ...    @property
    def max_tire_health(self): ...    @property
    def normal_oil(self): ...    @property
    def oil_per_kilometer(self): ...    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    def on_update_vehicle_state(self, state_str): ...
    @property
    def passenger_entities(self): ...    @property
    def pos(self): ...    @property
    def position(self): ...    def pre_reload_script(self): ...
    @property
    def rainbowPlugin(self): ...    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    @property
    def sunshine(self): ...    def tick(self, dtime): ...
    @property
    def tire_count(self): ...    @property
    def vehicle_proto(self): ...    @property
    def vehicle_type(self): ...    @property
    def weightKG(self): ...    @property
    def yaw(self): ...
class HelicopterEffectComp(VehicleEffectComp):
    def CalculateWheelRotationAngle(self, count): ...
    def CanPlayEffectByDist(self): ...
    def CheckStartTickWheelRotation(self): ...
    def ClearEffectByIdx(self, name, idx): ...
    def InitEffectInfo(self): ...
    def PlayBackCarLightEffect(self, enable): ...
    def PlayDamagedSmokeEffect(self, play=True): ...
    def PlayEffectByDrivingState(self): ...
    def PlayExplodeEffect(self): ...
    def PlayLightEffect(self, enable): ...
    def PlayWheelEffectBySpeed(self, enable): ...
    def TickEffect(self): ...
    def TickWheelRotation(self): ...
    def _CancelTickEffect(self): ...
    def _CancelTickWheelRotation(self): ...
    def _CheckWheelLongitudinalSlipForEffect(self): ...
    def _GetDustEffectLastPos(self): ...
    def _InitEffectImpl(self, name, suffix_bits=None): ...
    def _PlayEffectImpl(self, name, enable, time=-1, ensure_play=False): ...
    def _PlayEffectImplInWorld(self, name, enable, pos, time=-1): ...
    def _PlayWheelEffectImpl(self, name, enable_list, time=-1): ...
    def _StopPlayDrivingEffect(self): ...

class HelicopterModelComp(VehicleModelComp):
    def AddParachuteModel(self, is_add): ...
    def CacheModel(self): ...
    def CacheTires(self): ...
    def ChangeBrokenMaterial(self): ...
    def CheckWarningEffect(self): ...
    def ContactedRb(self, contact_info): ...
    def CreatePhysicsFilter(self, local=True): ...
    def CreateVehicleComponent(self, config_id=None): ...
    def DestroyParachuteModel(self): ...
    def DestroyTires(self): ...
    def FixPositionOnSky(self): ...
    def FixVehicleRotation(self): ...
    def GearChangedResponse(self, to_gear, from_gear): ...
    def GetChassisShapesNumber(self): ...
    def GetReplaceModelID(self, model_id): ...
    def GetRotationFromAToB(self, v1, v2): ...
    def IsVehicleModelInStuck(self): ...
    @property
    def IsVisible(self): ...    def LoadConfigFromSunshine(self, meta, config_data, vertices_data): ...
    def LoadTireModels(self): ...
    def OnLoadModel(self): ...
    def ReduceVehiclePeakTorque(self): ...
    def RefreshLocalMode(self): ...
    def ResetNanTransform(self, pos, rot): ...
    def SetLocalMode(self, local): ...
    def ShowModel(self): ...
    def SwitchSyncMode(self): ...
    def TryBindPassenger(self, avatar): ...
    def _on_set_is_airdrop_landed(self, old): ...
    def _on_set_sync_mode(self, old_val): ...
    @property
    def position(self): ...    @property
    def yaw(self): ...
class HelicopterOffPositionComp(VehicleOffPositionComp):
    def CheckResetPositionForUnderGroundWheels(self): ...
    def CheckWheelsUnderGround(self): ...
    def ClearDebugOffPosition(self): ...
    def GetOffPosition(self, seat, guarantee=False): ...
    def MakeOffPosFarther(self, pos): ...
    def _CancelWheelUnderGroundTimer(self): ...
    def _CheckPosValid(self, pos): ...
    def _GetOffPositionImp(self, pos): ...
    def _on_set_is_landed(self, old): ...

class HelicopterSoundComp(VehicleSoundComp):
    def CanHearSoundByDist(self): ...
    def CheckSoundPlay(self): ...
    def EnableVehicleSound(self, enable): ...
    def PlayAccelSound(self): ...
    def PlayEffectByDrivingStateForHelicopter(self): ...
    def PlayHelicopterEngineSound(self, play): ...
    def PlayHelicopterStopSound(self, play): ...
    def PlayHitSound(self): ...
    def PlayHornSound(self): ...
    def PlayStartSound(self): ...
    def PlayStopSound(self): ...
    def PlayTireSound(self): ...
    def RefreshSoundByDist(self): ...
    def StopHornSound(self): ...
    def StopTireSound(self): ...
    def TickHelicopterEngineSound(self): ...
    def _CheckSoundTimer(self): ...
    def _CheckTireSoundPlay(self): ...
    def _GetSoundPath(self, sound_id): ...

class Vehicle(ClientAreaEntity):
    AllVehicles: list = []
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = True
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = True
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = True
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = True
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    logger: Logger = <Logger Vehicle (DEBUG)>

    def AddParachuteModel(self, is_add): ...
    def AddStoryTick(self, func, frames=0): ...
    def AdjustPitchRollInAir(self): ...
    def ApplyForceInWorldFrameAtStart(self, add=True): ...
    def AttachToMaster(self): ...
    def CacheModel(self): ...
    def CacheTires(self): ...
    def CalculateWheelRotationAngle(self, count): ...
    def CallServerDrive(self): ...
    def CanHearSoundByDist(self): ...
    def CanLeanOut(self, seat): ...
    def CanLeanOutForCollision(self, seat): ...
    def CanLeanOutForVehicleSeat(self, seat): ...
    def CanPlayEffectByDist(self): ...
    def CancelCheckWaterHeightTimer(self): ...
    def ChangeBrokenMaterial(self): ...
    def CheckResetPositionForUnderGroundWheels(self): ...
    def CheckSoundPlay(self): ...
    def CheckStartTickWheelRotation(self): ...
    def CheckWarningEffect(self): ...
    def CheckWheelsUnderGround(self): ...
    def ClearAllStoryTick(self): ...
    def ClearDebugOffPosition(self): ...
    def ClearEffectByIdx(self, name, idx): ...
    def ContactedRb(self, contact_info): ...
    def CreatePhysicsFilter(self, local=True): ...
    def CreateStickyObject(self, guid): ...
    def CreateVehicleComponent(self, config_id=None): ...
    def DestroyParachuteModel(self): ...
    def DestroyStickyObject(self, guid): ...
    def DestroyTires(self): ...
    def DetachFromMaster(self, at_attach_id=None): ...
    def Drive(self, turning, forward, handbrake=0): ...
    def DriveForward(self, val): ...
    def DriveTurning(self, val): ...
    def DriverOff(self, old): ...
    def DriverOn(self): ...
    def EnableMotorHandIK(*args, **kwargs): ...
    def EnableVehicleCCT(self, is_enable=True): ...
    def EnableVehicleSound(self, enable): ...
    def FixPositionOnSky(self): ...
    def FixVehicleRotation(self): ...
    def GearChangedResponse(self, to_gear, from_gear): ...
    def GetAllSeatIndex(self): ...
    def GetCCTParam(self, name): ...
    def GetCCTParamRange(self, name): ...
    def GetChassisShapesNumber(self): ...
    def GetDriveStatus(self, seat): ...
    def GetFaction(self): ...
    def GetHitTireIndex(self, pos): ...
    def GetMapTagId(self, marker=None): ...
    def GetOffPosition(self, seat, guarantee=False): ...
    def GetRealCCTParam(self, name): ...
    def GetReplaceModelID(self, model_id): ...
    def GetRotationFromAToB(self, v1, v2): ...
    def GetSceneNodeId(self, marker=None): ...
    def GetSeatBoneNameBySeat(self, seat): ...
    def GetSeatById(self, avatar_id): ...
    def GetVacantPassengerSeat(self): ...
    def GetVacantSeatForBigger(self, cur_seat): ...
    def HasVacantSeat(self): ...
    def HideAttachTargetRb(self, is_hide): ...
    def InitEffectInfo(self): ...
    def IsAllWheelsInAir(self): ...
    def IsAttachLoaded(self): ...
    def IsBackSeat(self, seat): ...
    def IsInAir(self): ...
    def IsLeftSeat(self, seat): ...
    def IsMotor(self): ...
    def IsMoving(self): ...
    def IsMovingForward(self): ...
    def IsSeatOccupied(self, seat): ...
    def IsVehicleModelInStuck(self): ...
    @property
    def IsVisible(self): ...    def LoadConfigFromSunshine(self, meta, config_data, vertices_data): ...
    def LoadTireModels(self): ...
    def MakeOffPosFarther(self, pos): ...
    def OffPassenger(self, avatar_id): ...
    def OnCreateInSunshine(self, objMeta, data): ...
    def OnEnterWater(self, snare): ...
    def OnExitWater(self, snare): ...
    def OnLoadModel(self): ...
    def OnPassenger(self, avatar_id): ...
    def OnRemoveInSunshine(self): ...
    def OnSelectedInSunshine(self): ...
    def OnSunshinePropertyAdded(self, name, vals): ...
    def OnSunshinePropertyChanged(self, name, value): ...
    def OnSunshinePropertyDeleted(self, name): ...
    def OnUnselectedInSunshine(self): ...
    def OnUpdatePosition(self, pos): ...
    def OnVehicleHitSound(self, sound_id, pos, kph): ...
    def OnVehicleOilChanged(self): ...
    def OnVehiclePlaySoundWithKphEvent(self, sound_id, pos, kph): ...
    def PlayAccelSound(self): ...
    def PlayBackCarLightEffect(self, enable): ...
    def PlayDamagedSmokeEffect(self, play=True): ...
    def PlayEffectByDrivingState(self): ...
    def PlayExplodeEffect(self): ...
    def PlayHitSound(self): ...
    def PlayHornSound(self): ...
    def PlayLightEffect(self, enable): ...
    def PlayStartSound(self): ...
    def PlayStopSound(self): ...
    def PlayTireSound(self): ...
    def PlayWheelEffectBySpeed(self, enable): ...
    def QueueRefreshConfigDataInSunshine(self): ...
    def ReduceVehiclePeakTorque(self): ...
    def RefreshCCTConfig(self): ...
    def RefreshConfigDataInSunshine(self): ...
    def RefreshLocalMode(self): ...
    def RefreshSoundByDist(self): ...
    def RemoveStoryTick(self, func): ...
    def ResetNanTransform(self, pos, rot): ...
    def ResetNormalMaterial(self): ...
    def SetCCTParam(self, name, value): ...
    def SetCCTParamRange(self, name, min_value, max_value): ...
    def SetDeadMaterial(self): ...
    def SetHandBrake(self, val): ...
    def SetLocalMode(self, local): ...
    def SetNormalMaterial(self): ...
    def SetTireMaterial(self): ...
    def SetupVehicleComponent(self): ...
    def ShowModel(self): ...
    def StopHornSound(self): ...
    def StopTireSound(self): ...
    def SwitchSyncMode(self): ...
    def TickEffect(self): ...
    def TickLocalVehicleGraph(self, dt=0): ...
    def TickWheelRotation(self): ...
    def TryBindPassenger(self, avatar): ...
    def UpdateDriverGraphInfo(self): ...
    def UpdateMotorGraphInfoFromCCT(self, dt): ...
    def _CancelTickEffect(self): ...
    def _CancelTickWheelRotation(self): ...
    def _CancelWheelUnderGroundTimer(self): ...
    def _CheckCanChangeSwimState(self, snare, enter): ...
    def _CheckPosValid(self, pos): ...
    def _CheckSoundTimer(self): ...
    def _CheckTireSoundPlay(self): ...
    def _CheckWaterHeight(self): ...
    def _CheckWheelLongitudinalSlipForEffect(self): ...
    def _GetDustEffectLastPos(self): ...
    def _GetOffPositionImp(self, pos): ...
    def _GetSoundPath(self, sound_id): ...
    def _InitEffectImpl(self, name, suffix_bits=None): ...
    def _PlayEffectImpl(self, name, enable, time=-1, ensure_play=False): ...
    def _PlayEffectImplInWorld(self, name, enable, pos, time=-1): ...
    def _PlayWheelEffectImpl(self, name, enable_list, time=-1): ...
    def _ProcessOneTireMaterail(self, part_list, material_list): ...
    def _SetForwardType(self, val): ...
    def _SetTurningType(self, val): ...
    def _StopPlayDrivingEffect(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_set_at_attach_id(self, old): ...
    def _on_set_driving_state(self, old): ...
    def _on_set_gear(self, old): ...
    def _on_set_horn(self, old): ...
    def _on_set_hp(self, old): ...
    def _on_set_is_airdrop_landed(self, old): ...
    def _on_set_is_landed(self, old): ...
    def _on_set_oil(self, old): ...
    def _on_set_physx_handbrake(self, old): ...
    def _on_set_proto_id(self, old): ...
    def _on_set_sync_mode(self, old_val): ...
    def _on_sunshine_set_proto_id(self, new): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    @property
    def capacity(self): ...    @property
    def cur_speed(self): ...    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    @property
    def driver(self): ...    @property
    def driver_id(self): ...    def entity_method(self, md5, index, args): ...
    @property
    def forward_speed(self): ...    def get_gtick(self): ...
    @property
    def height(self): ...    @property
    def helicopter_max_height(self): ...    @property
    def hit_kill_speed(self): ...    def init_from_dict(self, *args, **kwargs): ...
    @property
    def is_alive(self): ...    def is_deactived(self): ...
    def is_destroyed(self): ...
    @property
    def is_helicopter(self): ...    @property
    def is_invincible(self): ...    @property
    def max_health(self): ...    @property
    def max_oil(self): ...    @property
    def max_tire_health(self): ...    @property
    def normal_oil(self): ...    @property
    def oil_per_kilometer(self): ...    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    def on_update_vehicle_state(self, state_str): ...
    @property
    def passenger_entities(self): ...    @property
    def pos(self): ...    @property
    def position(self): ...    def pre_reload_script(self): ...
    @property
    def rainbowPlugin(self): ...    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    @property
    def sunshine(self): ...    def tick(self, dtime): ...
    @property
    def tire_count(self): ...    @property
    def vehicle_proto(self): ...    @property
    def vehicle_type(self): ...    @property
    def weightKG(self): ...    @property
    def yaw(self): ...
class VehicleEffectComp(object):
    def CalculateWheelRotationAngle(self, count): ...
    def CanPlayEffectByDist(self): ...
    def CheckStartTickWheelRotation(self): ...
    def ClearEffectByIdx(self, name, idx): ...
    def InitEffectInfo(self): ...
    def PlayBackCarLightEffect(self, enable): ...
    def PlayDamagedSmokeEffect(self, play=True): ...
    def PlayEffectByDrivingState(self): ...
    def PlayExplodeEffect(self): ...
    def PlayLightEffect(self, enable): ...
    def PlayWheelEffectBySpeed(self, enable): ...
    def TickEffect(self): ...
    def TickWheelRotation(self): ...
    def _CancelTickEffect(self): ...
    def _CancelTickWheelRotation(self): ...
    def _CheckWheelLongitudinalSlipForEffect(self): ...
    def _GetDustEffectLastPos(self): ...
    def _InitEffectImpl(self, name, suffix_bits=None): ...
    def _PlayEffectImpl(self, name, enable, time=-1, ensure_play=False): ...
    def _PlayEffectImplInWorld(self, name, enable, pos, time=-1): ...
    def _PlayWheelEffectImpl(self, name, enable_list, time=-1): ...
    def _StopPlayDrivingEffect(self): ...

class VehicleModelComp(ModelComponent):
    def AddParachuteModel(self, is_add): ...
    def CacheModel(self): ...
    def CacheTires(self): ...
    def ChangeBrokenMaterial(self): ...
    def CheckWarningEffect(self): ...
    def ContactedRb(self, contact_info): ...
    def CreatePhysicsFilter(self, local=True): ...
    def CreateVehicleComponent(self, config_id=None): ...
    def DestroyParachuteModel(self): ...
    def DestroyTires(self): ...
    def FixPositionOnSky(self): ...
    def FixVehicleRotation(self): ...
    def GearChangedResponse(self, to_gear, from_gear): ...
    def GetChassisShapesNumber(self): ...
    def GetReplaceModelID(self, model_id): ...
    def GetRotationFromAToB(self, v1, v2): ...
    def IsVehicleModelInStuck(self): ...
    @property
    def IsVisible(self): ...    def LoadConfigFromSunshine(self, meta, config_data, vertices_data): ...
    def LoadTireModels(self): ...
    def OnLoadModel(self): ...
    def ReduceVehiclePeakTorque(self): ...
    def RefreshLocalMode(self): ...
    def ResetNanTransform(self, pos, rot): ...
    def SetLocalMode(self, local): ...
    def ShowModel(self): ...
    def SwitchSyncMode(self): ...
    def TryBindPassenger(self, avatar): ...
    def _on_set_is_airdrop_landed(self, old): ...
    def _on_set_sync_mode(self, old_val): ...
    @property
    def position(self): ...    @property
    def yaw(self): ...
class VehicleOffPositionComp(object):
    def CheckResetPositionForUnderGroundWheels(self): ...
    def CheckWheelsUnderGround(self): ...
    def ClearDebugOffPosition(self): ...
    def GetOffPosition(self, seat, guarantee=False): ...
    def MakeOffPosFarther(self, pos): ...
    def _CancelWheelUnderGroundTimer(self): ...
    def _CheckPosValid(self, pos): ...
    def _GetOffPositionImp(self, pos): ...
    def _on_set_is_landed(self, old): ...

class VehicleSoundComp(object):
    def CanHearSoundByDist(self): ...
    def CheckSoundPlay(self): ...
    def EnableVehicleSound(self, enable): ...
    def PlayAccelSound(self): ...
    def PlayHitSound(self): ...
    def PlayHornSound(self): ...
    def PlayStartSound(self): ...
    def PlayStopSound(self): ...
    def PlayTireSound(self): ...
    def RefreshSoundByDist(self): ...
    def StopHornSound(self): ...
    def StopTireSound(self): ...
    def _CheckSoundTimer(self): ...
    def _CheckTireSoundPlay(self): ...
    def _GetSoundPath(self, sound_id): ...


def Components(*components, **kwargs): ...

