# module: gclient.gameplay.logic_base.entities.freeview_entity

import six2

CLIENT_STUB: int = 8

class ClientAreaEntity(ClientEntity):
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    logger: Logger = <Logger ClientAreaEntity (DEBUG)>

    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    def is_deactived(self): ...
    def is_destroyed(self): ...
    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def pos(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    @property
    def yaw(self): ...
class CombatAvatar(ClientAreaEntity):
    HAS_TOPLOGO: bool = False
    IS_SHOOTING_RANGE: bool = False
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = True
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = True
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = True
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    NEED_BESHOOT_FRESNEL: bool = False
    NinjaBeacon: bool = False
    TOPLOGO_SHOW_POSITION: bool = True
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    logger: Logger = <Logger CombatAvatar (DEBUG)>
    recon_drone_frame_top_logo: cached_property = <gshare.decorators.cached_property object at 0x6f9c2b6350>

    def AddAssassinateEffect(self): ...
    def AddBeShootTechEffect(self): ...
    def AddBuffSpell(self, spell_id, spell_level, item_guid): ...
    def AddCameraEffect(self, effect_id, keep_time=-1, color=None): ...
    def AddCameraEffectByBuff(self, buff_proto, buff): ...
    def AddClientBuff(self, buff): ...
    def AddHoldingTimer(self, duration, item_guid, key_mode): ...
    def AddSkeletonEffectByBuff(self, buff_proto, buff): ...
    def AddSnareToSnareDict(self, proto_id, guid): ...
    def AddStoryTick(self, func, frames=0): ...
    def AddTechStateXray(self, effect, proto_id=1): ...
    def AddTpsShowEntity(self, entity): ...
    def AddUavResidualBloodTip(self): ...
    def AddWorldField(self, world_field_id, magic_field_id): ...
    def AdsFlashTick(self, dtime): ...
    def ApplyFilterMotionForExecute(self, apply_motion): ...
    def AttachToVehicle(self, vehicle): ...
    def BatchForwardSpellResult(self, results): ...
    def BatchForwardSpellResultFull(self, results): ...
    def BatchOnSpellResult(self, results): ...
    def BatchOnSpellResultFull(self, results): ...
    def BlastBombExplode(self, spell_id): ...
    def BroadcastSoundEvent(self, sound_type, sound_pos, extra=None): ...
    def CacheModel(self): ...
    def CacheMovingPlatformInfoForShow(self, platform_guid): ...
    def CacheSoundID(self, event_id, sound_id, sound_tag): ...
    def CalAttrResult(self, attr_type, value, equip_id=''): ...
    def CanLimitFrameInvisible(self, combat_team_id): ...
    def CanRecycleCannon(self, spell_id): ...
    def CanShowEnemyToplogo(self): ...
    def CancelEmoteDetect(self): ...
    def CancelHeartbeatResetTimer(self): ...
    def CancelHoldTelescopeForFov(self): ...
    def CancelMissileAttackIndicateTick(self): ...
    def CancelRemoveCameraEffectTimer(self, effect_id): ...
    def CancelSamuraiSprintTick(self): ...
    def ChangeCustomMaterial(self, buff_proto): ...
    def ChangeFireWallSpellMode(self): ...
    def ChangeRelayStateInfo(self, key, value): ...
    def ChangeShaderGraphMaterial(self, buff_proto, buff_guid): ...
    def ChangeSpellMode226(self): ...
    def ChangeSpellMode227(self): ...
    def ChangeSpellMode231(self): ...
    def CheckAndGetSwitchDict(self, event_id, pos, is_3d, max_dist, notify_ai): ...
    def CheckEmitterObstructValue(self): ...
    def CheckHeroSkinEffect(self): ...
    def CheckInHouseWhenStateChange(self): ...
    def CheckIsOutDoor(self, door, position=None): ...
    def CheckPreloadExecuteThirdModel(self): ...
    def CheckProne(self): ...
    def CheckReset000ForMovingPlatform(self): ...
    def CheckResetFilterForMovingPlatform(self): ...
    def ClearAllStoryTick(self): ...
    def ClearAssassinateEffect(self): ...
    def ClearCureConnectingLine(self): ...
    def ClearDirectionExplode(self): ...
    def ClearElecticalFieldEffect(self): ...
    def ClearFireWallPlaceEntity(self): ...
    def ClearHeroSkinEffect(self): ...
    def ClearHoldingTimer(self): ...
    def ClearParanoiaEntity(self): ...
    def ClearPlaceExplodeEntity(self): ...
    def ClearPrePlaceEntity(self): ...
    def ClearUnit(self): ...
    def CreateElecticalFieldEffect(self, spell_id, level=1): ...
    def CreateFireWallPlaceEntity(self, spell_id, firewall_mode): ...
    def CreateModelFollow(self, buff_proto, buff_guid, max_time=-1): ...
    def CreateParanoiaEntity(self, spell_id): ...
    def CreatePrePlaceEntity(self, spell_id, level): ...
    def CreateStickyObject(self, guid): ...
    def CreateWorldFieldFollow(self, buff_proto, buff_guid): ...
    def DealScatterOffsetByTalent(self, scatter_offset): ...
    def DelayPlayRebornSound(self): ...
    def DelayStartHeartbeatScan(self): ...
    def DestroyReconDroneMarkFrame(self): ...
    def DestroyStickyObject(self, guid): ...
    def DetachFromVehicle(self, old): ...
    def DetectVisibleTargetInEmote(self): ...
    def DirectionExplode(self): ...
    def DisEnableSpecifyWorldField(self, world_field_id): ...
    def DisableInvisibleFrameLimit(self): ...
    def DisableUselessSignal(self): ...
    def DoAirplaneParachuteMusicBasic(self, value): ...
    def DoSkySound(self, sound_id): ...
    def DrawCureConnectingLine(self, target_ent, refresh=False): ...
    def DrawReconDroneMarkFrame(self): ...
    def DroneCureSelf(self, use_skill_whatever=False): ...
    def DroneCureSelfDown(self): ...
    def EnableSpecifyWorldField(self, world_field_id): ...
    def EnterKickUp(self, entity): ...
    def ExecuteCreateThirdPersonModel(self, is_create, model_id=0): ...
    def ForceDropAllWeaponForAvatar(self, is_drop=True): ...
    def ForwardSpellResult(self, cur_result): ...
    def ForwardSpellResultFull(self, cur_result): ...
    def GetBuffs(self): ...
    def GetCombatStatusLastInterval(self, combat_status): ...
    def GetCurArmExecutionItemId(self): ...
    def GetCurHighPriorityWeapon(self): ...
    def GetCurLeftHandWeapon(self): ...
    def GetCurLeftHandWeaponCase(self, is_fps_weapon=True): ...
    def GetCurSpecWeapon(self): ...
    def GetCurSpecWeaponCase(self, is_fps_weapon=True): ...
    def GetCurThrowableWeapon(self): ...
    def GetCurWeapon(self): ...
    def GetCurWeaponCase(self, is_fps_weapon=True): ...
    def GetCurWeaponGunType(self): ...
    def GetCurWeaponPartOpticType(self): ...
    def GetCurWeaponPartSlots(self): ...
    def GetCureUavDuration(self): ...
    def GetExecuteThirdModel(self): ...
    def GetFireWallPlacePosition(self, proto): ...
    def GetFireWallPlacePositionH(self, proto): ...
    def GetFireWallPlacePositionV(self, proto): ...
    def GetGrenadeLauncherBombItemIds(self): ...
    def GetGunSoundMedia(self): ...
    def GetInHouseName(self): ...
    def GetMainGunWeapon(self): ...
    def GetMainGunWeaponCase(self, is_fps_weapon=True): ...
    def GetMeleeWeaponCase(self, is_fps_weappon=True): ...
    def GetModelData(self): ...
    def GetMusicTypeLanding(self): ...
    def GetMusicTypeParachute(self): ...
    def GetMusicTypeSkydiving(self): ...
    def GetParanoiaPlacePosition(self, proto): ...
    def GetPlacePosition(self, cast_proto): ...
    def GetPrePlaceEntityPosition(self, spell_proto): ...
    def GetPrePlaceEntityPosition225(self, spell_proto): ...
    def GetPrePlaceEntityPosition234(self, spell_proto): ...
    def GetRealEntityOfCurThrowWeapon(self): ...
    def GetReplaceEffects(self, avatar_id): ...
    def GetReplaceModelID(self, model_id): ...
    def GetRotationFromAToB(self, v1, v2): ...
    def GetSubGunWeapon(self): ...
    def GetSubGunWeaponCase(self, is_fps_weapon=True): ...
    def GetSwitchValue_character_action(self): ...
    def GetSwitchValue_gun_fire_state(self): ...
    def GetSwitchValue_gun_type(self): ...
    def GetSwitchValue_hit_feedback(self): ...
    def GetSwitchValue_identity(self): ...
    def GetSwitchValue_material_surface(self): ...
    def GetSwitchValue_visual(self): ...
    def GetTeammateColorIndex(self, teammate_id): ...
    def GetTeammateIndex(self, teammate_id): ...
    def GetTeammateInfo(self, teammate_id): ...
    def GetWeaponAttrValueWithCache(self, name, defalut, timeout): ...
    def GetWeaponByGuid(self, guid): ...
    def GetWeaponCase(self, weapon_guid, is_fps_weapon=True): ...
    def GetWeaponCaseByGunId(self, gun_id, is_fps_weapon=True): ...
    def GetWeaponCaseById(self, weapon_id, is_fps_weapon=True): ...
    def GetWeaponList(self): ...
    def GetWeaponPartSlots(self, weapon_guid): ...
    def HasAttr(self, attr_type): ...
    def HasBuff(self, guid): ...
    def HasBuffByKind(self, kind): ...
    def HasBuffByKinds(self, kinds): ...
    def HasClientBuff(self, guid): ...
    def HasClientBuffByKind(self, kind): ...
    def HasSoundByTag(self, tag): ...
    def HasTalent(self, talent_id): ...
    def HasTalentCode(self, talent_code): ...
    def HelicopterDrive(self, x, z): ...
    def HideAttachModelForDead(self): ...
    def HideHeroAttachModel(self, hide, hide_scabbard): ...
    def HideNinjaBeacon(self, beacon_id): ...
    def HideWeaponForExecute(self, is_hide): ...
    def HouseDetectOnCombatState(self, avatar): ...
    def HouseRangeTriggerEnter(self, entity_name, is_enter): ...
    def IndoorTriggerEnter(self, entity_name, is_enter): ...
    def InitAvatarModel(self): ...
    def InitPropForTrace(self): ...
    def InitUpdateSoundCacheVar(self): ...
    def IsCurTakeCompoundBowWeapon(self): ...
    def IsCurTakeDualGunWeapon(self): ...
    def IsCurTakeGunMeleeWeapon(self): ...
    def IsCurTakeGunWeapon(self): ...
    def IsCurTakeLeftHandThrowableWeapon(self): ...
    def IsCurTakeLeftHandWeapon(self): ...
    def IsCurTakeMainWeapon(self): ...
    def IsCurTakeMeleeWeapon(self): ...
    def IsCurTakeMissileWeapon(self): ...
    def IsCurTakeRightHandThrowableWeapon(self): ...
    def IsCurTakeSpWeapon(self): ...
    def IsCurTakeSubWeapon(self): ...
    def IsInExecute(self): ...
    def IsInStropState(self): ...
    @property
    def IsVisible(self): ...    def JumpOutBeExecuteState(self): ...
    def JumpOutExecuteState(self): ...
    def JumpToBeExecuteState(self): ...
    def JumpToExecuteState(self): ...
    def JumpToSkillEnd(self): ...
    def JumpToSkillHold(self): ...
    def JumpToSkillToss(self): ...
    def JumpToSkillTossSecondary(self): ...
    def JumpToSwitchToss(self): ...
    def LeaveHouseOnDead(self): ...
    def LeaveKickUp(self): ...
    def MissileAttackIndicateTick(self, spell_id, spell_level, dt): ...
    def OnAddBuff(self, buff): ...
    def OnAddBuffCategory(self, kind, level, buff_guid): ...
    def OnAddBuffCatergoryInvincible(self, buff_proto, buff_guid): ...
    def OnAddBuff_1(self, buff_proto): ...
    def OnAddBuff_10(self, buff_proto): ...
    def OnAddBuff_1010(self, buff_proto): ...
    def OnAddBuff_1023(self, buff_proto): ...
    def OnAddBuff_1024(self, buff_proto): ...
    def OnAddBuff_1028(self, buff_proto): ...
    def OnAddBuff_1033(self, buff_proto): ...
    def OnAddBuff_17(self, buff_proto): ...
    def OnAddBuff_20(self, buff_proto): ...
    def OnAddBuff_21(self, buff_proto): ...
    def OnAddBuff_25(self, buff_proto): ...
    def OnAddBuff_6(self, buff_proto): ...
    def OnAddClientBuff(self, buff): ...
    def OnAddClientBuffCategory(self, kind, level, buff_guid): ...
    def OnAddClientBuffCategoryFlash(self, buff_proto, buff_guid): ...
    def OnAddRageEffect(self, buff_proto=None, buff_guid=None): ...
    def OnAddRecoverHpBuff(self, buff_proto): ...
    def OnAddSelfMarkBuff(self, buff_proto): ...
    def OnAddStealthEffect(self, buff_proto=None, buff_guid=None): ...
    def OnAddTeamMarkBuff(self, buff_proto): ...
    def OnAddWeaponPart(self, weapon_guid, part_id): ...
    def OnAvatarDyingMove(self, x, z): ...
    def OnBeInjured(self, caster): ...
    def OnClientBuffTick(self, dt): ...
    def OnCombatStateChangeForCameraEffect(self, avatar): ...
    def OnDead(self): ...
    def OnDealDamageResult(self, result, damage_result): ...
    def OnDropWeapon(self, guid): ...
    def OnDyeWeapon(self, guid): ...
    def OnDying(self, is_dying): ...
    def OnEnterHouseTrigger(self, entity_name, is_enter): ...
    def OnEnterInvincible(self): ...
    def OnGhost(self): ...
    def OnHeartbeatStop(self): ...
    def OnHoldItem202(self, item): ...
    def OnHoldItem208(self, item): ...
    def OnHoldItem209(self, item): ...
    def OnHoldItem214(self, item): ...
    def OnHoldItem225(self, item): ...
    def OnHoldItem24(self, item): ...
    def OnHoldItem250(self, item): ...
    def OnHoldItem309(self, item): ...
    def OnHoldItem310(self, item): ...
    def OnHoldItem317(self, item): ...
    def OnHoldItem432(self, item): ...
    def OnHoldItem435(self, item): ...
    def OnHoldItem437(self, item): ...
    def OnHoldItem438(self, item): ...
    def OnHoldItem439(self, item): ...
    def OnHoldItem440(self, item): ...
    def OnHoldItem467(self, item): ...
    def OnHoldItem482(self, item): ...
    def OnHoldItem485(self, item): ...
    def OnHoldItem486(self, item): ...
    def OnHoldItem487(self, item): ...
    def OnHoldItem489(self, item): ...
    def OnHoldItem5(self, item): ...
    def OnHoldItem52(self, item): ...
    def OnHoldItem58(self, item): ...
    def OnHoldItem96(self, item): ...
    def OnHoldItem97(self, item): ...
    def OnHoldItem98(self, item): ...
    def OnHoldItemMissile(self, item): ...
    def OnHoldSamuraiSprint(self, item): ...
    def OnInGameAchieveCompleted(self, kind, data): ...
    def OnInGameFeedbackCompleted(self, kind, data): ...
    def OnLeanoutStateChange(self): ...
    def OnLeaveInvincible(self): ...
    def OnLoadModel(self): ...
    def OnMovingPlatformChanged(self, old): ...
    def OnPickupItem(self, item_id): ...
    def OnPreusingItem(self, item): ...
    def OnProne(self): ...
    def OnReborn(self): ...
    def OnReceiveLike(self, info): ...
    def OnRefreshWeaponParts(self, weapon_guid): ...
    def OnReloadHandModel(self): ...
    def OnReloadModel(self): ...
    def OnRemoveBuff(self, buff): ...
    def OnRemoveBuffCategory(self, kind, level, buff_guid): ...
    def OnRemoveBuffCatergoryInvincible(self, buff_proto, buff_guid): ...
    def OnRemoveBuff_1(self, buff_proto, buff_guid=''): ...
    def OnRemoveBuff_10(self, buff_proto, buff_guid=''): ...
    def OnRemoveBuff_1010(self, buff_proto, buff_guid=''): ...
    def OnRemoveBuff_1023(self, buff_proto, buff_guid=''): ...
    def OnRemoveBuff_1024(self, buff_proto, buff_guid=''): ...
    def OnRemoveBuff_1028(self, buff_proto, buff_guid=''): ...
    def OnRemoveBuff_17(self, buff_proto, buff_guid=''): ...
    def OnRemoveBuff_20(self, buff_proto, buff_guid=''): ...
    def OnRemoveBuff_21(self, buff_proto, buff_guid=''): ...
    def OnRemoveBuff_25(self, buff_proto, buff_guid=''): ...
    def OnRemoveBuff_6(self, buff_proto, buff_guid=''): ...
    def OnRemoveClientBuff(self, buff): ...
    def OnRemoveClientBuffCategory(self, kind, level, buff_guid): ...
    def OnRemoveClientBuffCategoryFlash(self, buff_proto, buff_guid): ...
    def OnRemoveRageEffect(self, buff_proto=None, buff_guid=None): ...
    def OnRemoveRecoverHpBuff(self, buff_guid): ...
    def OnRemoveSelfMarkBuff(self, buff_proto): ...
    def OnRemoveStealthEffect(self, buff_proto=None, buff_guid=None): ...
    def OnRemoveTeamMarkBuff(self, buff_proto): ...
    def OnReplayHandModelLoaded(self): ...
    def OnReplayHandModelReloaded(self): ...
    def OnRotatePlaceEntity(self): ...
    def OnSlideWithParkour(self): ...
    def OnSpeedLevelChange(self): ...
    def OnSpellCureGun(self, item, to_use): ...
    def OnSpellItem102(self, item): ...
    def OnSpellItem103(self, item): ...
    def OnSpellItem104(self, item): ...
    def OnSpellItem202(self, item): ...
    def OnSpellItem208(self, item): ...
    def OnSpellItem209(self, item): ...
    def OnSpellItem213(self, item): ...
    def OnSpellItem214(self, item): ...
    def OnSpellItem225(self, item): ...
    def OnSpellItem24(self, item): ...
    def OnSpellItem250(self, item): ...
    def OnSpellItem309(self, item): ...
    def OnSpellItem310(self, item): ...
    def OnSpellItem317(self, item): ...
    def OnSpellItem353(self, item): ...
    def OnSpellItem354(self, item): ...
    def OnSpellItem400(self, item): ...
    def OnSpellItem401(self, item): ...
    def OnSpellItem424(self, item): ...
    def OnSpellItem425(self, item): ...
    def OnSpellItem427(self, item): ...
    def OnSpellItem428(self, item): ...
    def OnSpellItem432(self, item): ...
    def OnSpellItem435(self, item): ...
    def OnSpellItem437(self, item): ...
    def OnSpellItem438(self, item): ...
    def OnSpellItem439(self, item): ...
    def OnSpellItem440(self, item): ...
    def OnSpellItem467(self, item): ...
    def OnSpellItem471(self, item): ...
    def OnSpellItem482(self, item): ...
    def OnSpellItem483(self, item): ...
    def OnSpellItem485(self, item): ...
    def OnSpellItem486(self, item): ...
    def OnSpellItem487(self, item): ...
    def OnSpellItem489(self, item): ...
    def OnSpellItem5(self, item): ...
    def OnSpellItem52(self, item): ...
    def OnSpellItem58(self, item): ...
    def OnSpellItem60(self, item): ...
    def OnSpellItem96(self, item): ...
    def OnSpellItem97(self, item): ...
    def OnSpellItem98(self, item): ...
    def OnSpellItemCureUav(self, item): ...
    def OnSpellItemLightAttack(self, item): ...
    def OnSpellItemMissile(self, item): ...
    def OnSpellResult(self, cur_result): ...
    def OnSpellResultFull(self, cur_result): ...
    def OnSpellResultImpl(self, result): ...
    def OnSyncGame3DSound(self, sound_id, extra_info={}): ...
    def OnSyncUnloadGame3DSound(self, sound_id): ...
    def OnSyncUnloadGame3DSounds(self, sound_ids): ...
    def OnUavToss(self, cure_self): ...
    def OnUpdateBuff_1(self, buff_proto): ...
    def OnUpdateBuff_10(self, buff_proto): ...
    def OnUpdateBuff_25(self, buff_proto): ...
    def OnWeaponListChanged(self): ...
    def OnXdroidBuy(self): ...
    def PlaceElecticalFieldTick(self, dtime): ...
    def PlaceExplodeEntityTick(self, dtime): ...
    def PlaceFireWallEntityTick(self, dtime): ...
    def PlaceParanoiaEntityTick(self, dtime): ...
    def PlayArmorCameraEffect(self, old_armor): ...
    def PlayEffectPathInWorld(self, effect_id, pos, direction): ...
    def PlayExecuteSoundEvent(self, execute_info): ...
    def PlayExtraArmorCameraEffect(self): ...
    def PlayGeneralSoundEventById(self, event_id, pos=None, param_dict=None, is_3d=True, vol=1.0, gameObjectID=None, **kwargs): ...
    def PlayGunSoundEventById(self, event_id, direction=None, force_switch_dict=None): ...
    def PlayHitSoundEvent(self, caster_id, sound_result, vol=1.0): ...
    def PrePlaceEntityTick(self, dtime): ...
    def ProcessSpellResult(self, result, spell_result): ...
    def RecordStartHeartbeatScan(self): ...
    def RecycleCannon(self, spell_id): ...
    def RefreshAutoFrameLimit(self): ...
    def RefreshCombatAttrImmediately(self, attr_name, old, new): ...
    def RefreshCureGunLineEffect(self): ...
    def RefreshCureUavEffect(self, is_add): ...
    def RefreshCureUavEffectType(self): ...
    def RefreshHideWeaponOnVehicle(self): ...
    def RefreshTeammateTechState(self): ...
    def RefreshUavResidualBloodTip(self): ...
    def RemoveAllCameraEffect(self): ...
    def RemoveCameraEffect(self, effect_id): ...
    def RemoveCameraEffectByBuff(self, buff_proto, buff): ...
    def RemoveClientBuff(self, guid): ...
    def RemoveClientBuffsByKind(self, kind): ...
    def RemoveModelFollow(self, buff_proto, buff_guid): ...
    def RemoveSkeletonEffectByBuff(self, buff_proto, buff): ...
    def RemoveSnareFromSnareDict(self, proto_id, guid): ...
    def RemoveStoryTick(self, func): ...
    def RemoveTpsShowEntity(self, entity): ...
    def RemoveUavResidualBloodTip(self): ...
    def RemoveWorldField(self, world_field_id, magic_field_id, delay_disable_time=0): ...
    def RemoveWorldFieldFollow(self, buff_proto, buff_guid): ...
    def ReplayForAreaEntity(self, func_name, args, kwargs): ...
    def ReplayForCombatAvatar(self, func_name, args, kwargs): ...
    def ReplayForFpsWeaponCase(self, func_name, args, kwargs): ...
    def ReplayForHandModel(self, func_name, args, kwargs): ...
    def ReplayForHudFrontSight(self, func_name, args, kwargs): ...
    def ReplayForSpellWorker(self, func_name, args, kwargs): ...
    def ReplayGlobalConfig(self, flag): ...
    def ReplayNoticeWatcherLeave(self, watchable_dict): ...
    def ReplayOnReceiveRpcs(self, data): ...
    def ReplayOnRecvAssistData(self, frame_data): ...
    def ReplayOnRecvCameraStream(self, referenced_stamp, data): ...
    def ReplayOnRecvRpcStream(self, referenced_stamp, data): ...
    def ReplayOnUploadRpcs(self): ...
    def ReplayOnUploadRpcsThenStatus(self, states): ...
    def ReplaySyncClientStamp(self, client_stamp, server_stamp): ...
    def ResetCustomMaterial(self, buff_proto): ...
    def ResetExecuteTargetFilter(self, old): ...
    def ResetExecutorFilter(self, old): ...
    def ResetExecutorGraphState(self, executor): ...
    def ResetHeartbeatScan(self): ...
    def ResetPosResult(self, reason='client_create'): ...
    def ResetShaderGraphMaterial(self, buff_proto, buff_guid): ...
    def RestoreBuffCameraEffect(self, buff): ...
    def RestoreBuffState(self): ...
    def SamuraiSprintTick(self, spell_id, spell_level, dt): ...
    def SetAdsLoadPoint(self, pos_list): ...
    def SetCameraCtrlTargetExecute(self, is_control): ...
    def SetControlledTargetId(self, drone_id): ...
    def SetControllingDroneId(self, drone_id): ...
    def SetDroneConnectLoadingState(self, is_finished, connecting_or_disconnecting): ...
    def SetEnableWorldFieldFadeTime(self, value): ...
    def SetFocusDistanceForParachute(self, para_stage): ...
    def SetMeleeWeaponCaseVisibility(self, visible, hide_reason, is_fps_weapon=True): ...
    def SetSoundParameterByTag(self, tag, name, value): ...
    def ShowAttachModelForDead(self): ...
    def ShowHighSkyParaBtn(self): ...
    def ShowModel(self): ...
    def SortAndActiveWorldField(self): ...
    def SpectatorHandModelStatus(self, states): ...
    def StartEmoteDetect(self): ...
    def StartHeartbeatScan(self): ...
    def StartParkour(self, spell_id, spell_level, item_guid): ...
    def StopHeartbeatScan(self): ...
    def StopParachuteSkySound(self): ...
    def StopSoundByTag(self, tag): ...
    def SwitchCameraForDrone(self, follow_player): ...
    def SwitchCameraOnDroneControllingStateChanged(self, follow_player): ...
    def TestBackpack(self): ...
    def ThrowBomb(self, spell_id): ...
    def ThrowBombReal(self, current_spell): ...
    def TickCanShootPlayerForSound(self): ...
    def TickControlGraphCue(self): ...
    def TickInHouseRangeDetector(self): ...
    def TickUpdateSoundCache(self): ...
    def TryEnableAutoFrameLimit(self): ...
    def TryEnableInvisibleFrameLimit(self, frames): ...
    def TryEnableReplayRoomEffect(self, is_enable): ...
    def UnLoadEventByEventKey(self, eventKey): ...
    def UpdateCombatStatusTimestamp(self, combat_status): ...
    def UpdateHeartbeatSound(self, hp, old_hp): ...
    def UseItemAutoEnd214(self, item): ...
    def UseItemAutoEnd317(self, item): ...
    def _CancelExecuteSoundEvent(self): ...
    def _CancelRangeHouseTimer(self): ...
    def _CheckHeroSkinEffect(self): ...
    def _CreateElecticalFieldEffect(self, spell_id, level=1): ...
    def _CreateExplodeEntity(self, pos, spell_id, spell_level): ...
    def _CreateFireWallPlaceEntity(self, info_list, spell_id, spell_level): ...
    def _CreateParanoiaEntity(self, info_list, spell_id, spell_level): ...
    def _CreatePrePlaceEntity(self, spell_id, level): ...
    def _DamageGameLogicEffect(self, result, caster, target, damage_data, is_system_damage, is_friend): ...
    def _DamageModelEffect(self, result, caster, target, damage_data, is_system_damage, is_friend): ...
    def _DamageSoundEffect(self, result, caster, target, damage_data, is_system_damage, is_friend): ...
    def _DamageUIEffect(self, result, caster, target, damage_data, is_system_damage, is_friend): ...
    def _DelayDisableSpecifyWorldField(self, delay_time, world_field_id): ...
    def _DoAddShootTechEffect(self): ...
    def _GetCureGunEffectAttachWeapon(self): ...
    def _GetFireWallPlacePosition(self, max_distance, interval, cur_dir, start_pos, yaw): ...
    def _GetOpenParachuteSoundId(self): ...
    def _OnChangeToCloseParachute(self, old): ...
    def _OnChangeToFinish(self, old): ...
    def _OnChangeToFreeFall(self, old): ...
    def _OnChangeToLandGround(self, old): ...
    def _OnChangeToOpenParachute(self, old): ...
    def _OnChangeToParachute(self, old): ...
    def _OnHoldItemMissile(self, spell_id, spell_level=1): ...
    def _OnHoldSamuraiSprint(self, spell_id, spell_level=1): ...
    def _ResetInHouseParam(self): ...
    def _ResetRangeHouseParam(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_refresh_SkillMaxCount(self, old, new): ...
    def _on_refresh_StrafeMainFovScale(self, old, new): ...
    def _on_set_arm_clothes(self, old): ...
    def _on_set_bomb_mode(self, new): ...
    def _on_set_coins(self, old): ...
    def _on_set_combat_state(self, old): ...
    def _on_set_cur_lefthand_weapon_guid_server(self, old): ...
    def _on_set_cur_spec_weapon_guid_server(self, old): ...
    def _on_set_cur_weapon_guid_server(self, old): ...
    def _on_set_cure_drone_id(self, old): ...
    def _on_set_cure_gun_target(self, old): ...
    def _on_set_drone_curing_type(self, old): ...
    def _on_set_execute_target(self, old): ...
    def _on_set_execute_time(self, old): ...
    def _on_set_executor(self, old): ...
    def _on_set_fps_mode(self, old): ...
    def _on_set_getting_help_state(self, old): ...
    def _on_set_has_client(self, old): ...
    def _on_set_have_beard(self, old): ...
    def _on_set_help_other_speed(self, old): ...
    def _on_set_helper_id(self, old): ...
    def _on_set_hero_id(self, old): ...
    def _on_set_is_ads_status(self, old): ...
    def _on_set_is_drone_curing(self, old): ...
    def _on_set_is_high_frequency(self, old): ...
    def _on_set_is_in_house(self, old): ...
    def _on_set_is_in_swim(self, old): ...
    def _on_set_is_lean_out(self, old): ...
    def _on_set_kr_eid(self, old): ...
    def _on_set_motion_state(self, old): ...
    def _on_set_motion_state_info(self, old): ...
    def _on_set_moving_platform_guid(self, old): ...
    def _on_set_para_lose_client(self, old): ...
    def _on_set_para_stage(self, old): ...
    def _on_set_parkour(self, old): ...
    def _on_set_pose_type_server(self, old): ...
    def _on_set_repel_bomb_explode_time(self, old): ...
    def _on_set_server_armor(self, old): ...
    def _on_set_server_hp(self, old): ...
    def _on_set_suppression(self, old): ...
    def _on_set_uav_data(self, old): ...
    def _on_set_uav_data_full(self, old): ...
    def _on_set_vehicle_id(self, old): ...
    def _on_set_vehicle_seat(self, old): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    @property
    def armor(self): ...    @property
    def base_armor(self): ...    @property
    def base_maxarmor(self): ...    def cancel_timer(self, timerid): ...
    @property
    def combat_team(self): ...    @property
    def controlling_drone(self): ...    @property
    def controlling_target(self): ...    @property
    def cur_maxhp(self): ...    def deactive(self): ...
    @property
    def design_combat_properties(self): ...    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    @property
    def extra_armor(self): ...    @property
    def game_logic(self): ...    def get_gtick(self): ...
    @property
    def hand_model_id(self): ...    @property
    def handmodel_status(self): ...    @property
    def hp(self): ...    @property
    def in_same_house_with_player(self): ...    def init_from_dict(self, *args, **kwargs): ...
    @property
    def is_ads(self): ...    @property
    def is_alive(self): ...    @property
    def is_alive_state(self): ...    @property
    def is_ban_sprint(self): ...    def is_deactived(self): ...
    @property
    def is_dead_state(self): ...    def is_destroyed(self): ...
    @property
    def is_dying_state(self): ...    @property
    def is_fps_mode(self): ...    @property
    def is_invincible(self): ...    @property
    def is_on_sky(self): ...    @property
    def is_real_ads(self): ...    @property
    def is_replaying(self): ...    @property
    def is_shooting(self): ...    @property
    def is_vehicle_driver(self): ...    @property
    def is_vehicle_passenger(self): ...    @property
    def master(self): ...    @property
    def missile_entity(self): ...    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_ent_out_sight(self, guid): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def place_entity(self): ...    @property
    def pos(self): ...    @property
    def pose_type(self): ...    @property
    def position(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def show_game_sound(self): ...    @property
    def space(self): ...    @property
    def speed(self): ...    @property
    def speed_level_prop(self): ...    @property
    def standup_mat_id(self): ...    @property
    def teammate_info(self): ...    @property
    def throw_item(self): ...    def tick(self, dtime): ...
    @property
    def unit_model_id(self): ...    @property
    def vehicle(self): ...    @property
    def yaw(self): ...
class Dict(object):
    convert: method_descriptor = <method 'convert' of 'dict' objects>
    get_type: method_descriptor = <method 'get_type' of 'dict' objects>
    getname: method_descriptor = <method 'getname' of 'dict' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'dict' objects>
    name: getset_descriptor = <attribute 'name' of 'dict' objects>

class EntityID(object):
    convert: method_descriptor = <method 'convert' of 'entityid' objects>
    get_type: method_descriptor = <method 'get_type' of 'entityid' objects>
    getname: method_descriptor = <method 'getname' of 'entityid' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'entityid' objects>
    name: getset_descriptor = <attribute 'name' of 'entityid' objects>

class FreeviewDummyEntity(ClientAreaEntity):
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = False
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    logger: Logger = <Logger FreeviewDummyEntity (DEBUG)>

    def BatchForwardSpellResult(self, results): ...
    def ForwardSpellResult(self, cur_result): ...
    def FreeViewEntityLeave(self): ...
    def OnFreeviewCallSpectators(self, entity_id, method, args, kwargs): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    def is_deactived(self): ...
    def is_destroyed(self): ...
    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def pos(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    @property
    def yaw(self): ...
class List(object):
    convert: method_descriptor = <method 'convert' of 'list' objects>
    get_type: method_descriptor = <method 'get_type' of 'list' objects>
    getname: method_descriptor = <method 'getname' of 'list' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'list' objects>
    name: getset_descriptor = <attribute 'name' of 'list' objects>

class Str(object):
    convert: method_descriptor = <method 'convert' of 'str' objects>
    get_type: method_descriptor = <method 'get_type' of 'str' objects>
    getname: method_descriptor = <method 'getname' of 'str' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'str' objects>
    name: getset_descriptor = <attribute 'name' of 'str' objects>

class Tuple(object):
    convert: method_descriptor = <method 'convert' of 'tuple' objects>
    get_type: method_descriptor = <method 'get_type' of 'tuple' objects>
    getname: method_descriptor = <method 'getname' of 'tuple' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'tuple' objects>
    name: getset_descriptor = <attribute 'name' of 'tuple' objects>


def f(self, cur_result): ...
def rpc_method(rpctype, *types): ...
def with_tag(*args): ...

