# module: gclient.gameplay.logic_base.entities.move_fire_wall

import MObject
import MType
import cconst
import consts
import random
import six2

class GameSound(enum):
    Bomb: int = 2
    CompoundBow: int = 5
    FootStep: int = 1
    Gun: int = 0
    Parachute: int = 3
    Vehicle: int = 4
    name_to_values: dict = {'Gun': 0, 'FootStep': 1, 'Bomb': 2, 'Parachute': 3, 'Vehicle': 4, 'CompoundBow': 5}
    value_to_names: dict = {0: 'Gun', 1: 'FootStep', 2: 'Bomb', 3: 'Parachute', 4: 'Vehicle', 5: 'CompoundBow'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class MagicField(ClientAreaEntity):
    CHECK_INSIDE_SNARE_ID: list = [59]
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = True
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = True
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    ai_sensor_type: cached_property = <gshare.decorators.cached_property object at 0x6f78093390>
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    block_proto: cached_property = <gshare.decorators.cached_property object at 0x6f78092f10>
    can_through_wall: cached_property = <gshare.decorators.cached_property object at 0x6f78093090>
    collision_filter: cached_property = <gshare.decorators.cached_property object at 0x6f78093010>
    destruction: cached_property = <gshare.decorators.cached_property object at 0x6f78093350>
    equip_id: cached_property = <gshare.decorators.cached_property object at 0x6f78092f50>
    field_size: cached_property = <gshare.decorators.cached_property object at 0x6f78093150>
    is_fps_avatar: bool = False
    is_movable: cached_property = <gshare.decorators.cached_property object at 0x6f78093290>
    is_onewaypenetrate: cached_property = <gshare.decorators.cached_property object at 0x6f78093050>
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    is_shield: cached_property = <gshare.decorators.cached_property object at 0x6f78093250>
    live_time: cached_property = <gshare.decorators.cached_property object at 0x6f78092fd0>
    logger: Logger = <Logger MagicField (DEBUG)>
    particle_shield_proto: cached_property = <gshare.decorators.cached_property object at 0x6f78092f90>
    phy_material_type_id: cached_property = <gshare.decorators.cached_property object at 0x6f78093210>
    skill_attack_method_client: cached_property = <gshare.decorators.cached_property object at 0x6f78093310>
    skill_delay: cached_property = <gshare.decorators.cached_property object at 0x6f780932d0>
    snare_enter_code: cached_property = <gshare.decorators.cached_property object at 0x6f78093190>
    snare_leave_code: cached_property = <gshare.decorators.cached_property object at 0x6f780931d0>
    snare_proto: cached_property = <gshare.decorators.cached_property object at 0x6f78093110>
    spell_proto: cached_property = <gshare.decorators.cached_property object at 0x6f78092ed0>

    def AddStoryTick(self, func, frames=0): ...
    def ApplyEnemyEffectColorParam(self, effect_entity_id, enemy_effect_color_args): ...
    def BreakAnimAndDissolvingDestroy(self): ...
    def CacheModel(self): ...
    def CancelAllTimers(self): ...
    def CancelDissolvingTimer(self): ...
    def CheckAndCreateTrigger(self): ...
    def CheckPlayerCombatAvatarInSide(self): ...
    def ClearAllStoryTick(self): ...
    def CommonDelayDestroy(self): ...
    def CreateStoryTick(self): ...
    def CreateTrigger(self): ...
    def CylinderTickDuration(self, radius, height, low, duration, start_time, dt): ...
    def CylinderTickNormal(self, radius, height, low, dt): ...
    def DealWithExtraModelEffect(self): ...
    def DestroyExtra(self): ...
    def DestroyPrePlaceEntity(self): ...
    def DissolvingTick(self): ...
    def GetBornSoundId(self): ...
    def GetCreateType(self): ...
    def GetDestroySoundId(self): ...
    def GetDestroyType(self): ...
    def GetEffects(self): ...
    def GetPoseSenderClass(self): ...
    def GetReplaceModelID(self, model_id): ...
    def GetRotationFromAToB(self, v1, v2): ...
    def GetScaleByAttr(self, base_scale): ...
    def GetScaleByAttrX(self, base_scale): ...
    def GetScaleByAttrY(self, base_scale): ...
    def GetScaleByAttrZ(self, base_scale): ...
    def GetTriggerFilterInfo(self): ...
    def HideAndDelayDestroy(self): ...
    @property
    def IsVisible(self): ...    def MagicFieldTriggerCb(self, triggerinfo): ...
    def NeedCreateStoryTick(self): ...
    def NeedCreateTrigger(self): ...
    def NeedPlayEffectAndSound(self): ...
    def NewSpellResult(self): ...
    def OnAcceleratedChange(self): ...
    def OnBornTick(self, dt): ...
    def OnEnterSnare(self, ownerid): ...
    def OnExitSnare(self, ownerid): ...
    def OnMagicFieldModelLoad(self): ...
    def OnPlaceModelLoad(self): ...
    def PlayBornSound(self): ...
    def PlayDestroyEffect(self): ...
    def PlayEffectAndSound(self): ...
    def PlayLifeDestroySoundAndEffect(self): ...
    def PlayLifeStartSoundAndEffect(self): ...
    def PlayTickEffect(self): ...
    def ProcessShockwave(self): ...
    def ProcessShockwaveImp(self, target, pos, wave_radius): ...
    def RefreshEffectVisible(self): ...
    def RefreshEntityVisibilityOnLightAttack(self, _): ...
    def RefreshModelVisible(self): ...
    def RemoveStoryTick(self, func): ...
    def ReplaceEffects(self, effects): ...
    def SetCollisionFilterInfo(self): ...
    def SetDissolvingDestroy(self): ...
    def ShowModel(self): ...
    def ShowModelExtra(self): ...
    def SimulateDamage(self): ...
    def UnloadEffects(self, force_immediately=False): ...
    def UnloadExtra(self): ...
    def UnloadFog(self, player): ...
    def UnloadSound(self): ...
    def _CheckAndCreateTrigger(self): ...
    def _CreateStoryTickCylinder(self): ...
    def _CreateTriggerCylinder(self): ...
    def _CreateTriggerRectangle(self): ...
    def _CreateTriggerSphere(self): ...
    def _DealWithExtraModelEffect(self): ...
    def _PlayEffectAndSound(self): ...
    def _ShowModelExtra(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_set_dissolving(self, old): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    @property
    def fog_radius(self): ...    @property
    def fog_total_time(self): ...    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    @property
    def is_alive(self): ...    @property
    def is_controller(self): ...    def is_deactived(self): ...
    def is_destroyed(self): ...
    @property
    def is_enemy_field(self): ...    @property
    def is_invincible(self): ...    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def owner(self): ...    @property
    def pos(self): ...    @property
    def position(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    @property
    def unit_model_id(self): ...    @property
    def yaw(self): ...
class MoveFireWall(MagicField):
    CHECK_INSIDE_SNARE_ID: list = [59]
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = True
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = True
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    ai_sensor_type: cached_property = <gshare.decorators.cached_property object at 0x6f78093390>
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    block_proto: cached_property = <gshare.decorators.cached_property object at 0x6f78092f10>
    can_through_wall: cached_property = <gshare.decorators.cached_property object at 0x6f78093090>
    collision_filter: cached_property = <gshare.decorators.cached_property object at 0x6f78093010>
    destruction: cached_property = <gshare.decorators.cached_property object at 0x6f78093350>
    equip_id: cached_property = <gshare.decorators.cached_property object at 0x6f78092f50>
    field_size: cached_property = <gshare.decorators.cached_property object at 0x6f78093150>
    is_fps_avatar: bool = False
    is_movable: cached_property = <gshare.decorators.cached_property object at 0x6f78093290>
    is_onewaypenetrate: cached_property = <gshare.decorators.cached_property object at 0x6f78093050>
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    is_shield: cached_property = <gshare.decorators.cached_property object at 0x6f78093250>
    live_time: cached_property = <gshare.decorators.cached_property object at 0x6f78092fd0>
    logger: Logger = <Logger MoveFireWall (DEBUG)>
    particle_shield_proto: cached_property = <gshare.decorators.cached_property object at 0x6f78092f90>
    phy_material_type_id: cached_property = <gshare.decorators.cached_property object at 0x6f78093210>
    skill_attack_method_client: cached_property = <gshare.decorators.cached_property object at 0x6f78093310>
    skill_delay: cached_property = <gshare.decorators.cached_property object at 0x6f780932d0>
    snare_enter_code: cached_property = <gshare.decorators.cached_property object at 0x6f78093190>
    snare_leave_code: cached_property = <gshare.decorators.cached_property object at 0x6f780931d0>
    snare_proto: cached_property = <gshare.decorators.cached_property object at 0x6f78093110>
    spell_proto: cached_property = <gshare.decorators.cached_property object at 0x6f78092ed0>

    def AddStoryTick(self, func, frames=0): ...
    def ApplyEnemyEffectColorParam(self, effect_entity_id, enemy_effect_color_args): ...
    def BreakAnimAndDissolvingDestroy(self): ...
    def CacheModel(self): ...
    def CancelAllTimers(self): ...
    def CancelDissolvingTimer(self): ...
    def CheckAndCreateTrigger(self): ...
    def CheckPlayerCombatAvatarInSide(self): ...
    def ClearAllStoryTick(self): ...
    def CommonDelayDestroy(self): ...
    def CreateStoryTick(self): ...
    def CreateTrigger(self): ...
    def CylinderTickDuration(self, radius, height, low, duration, start_time, dt): ...
    def CylinderTickNormal(self, radius, height, low, dt): ...
    def DealWithExtraModelEffect(self): ...
    def DestroyExtra(self): ...
    def DestroyPrePlaceEntity(self): ...
    def DissolvingTick(self): ...
    def GetBornSoundId(self): ...
    def GetCreateType(self): ...
    def GetDestroySoundId(self): ...
    def GetDestroyType(self): ...
    def GetEffects(self): ...
    def GetPoseSenderClass(self): ...
    def GetReplaceModelID(self, model_id): ...
    def GetRotationFromAToB(self, v1, v2): ...
    def GetScaleByAttr(self, base_scale): ...
    def GetScaleByAttrX(self, base_scale): ...
    def GetScaleByAttrY(self, base_scale): ...
    def GetScaleByAttrZ(self, base_scale): ...
    def GetTriggerFilterInfo(self): ...
    def HideAndDelayDestroy(self): ...
    @property
    def IsVisible(self): ...    def MagicFieldTriggerCb(self, triggerinfo): ...
    def NeedCreateStoryTick(self): ...
    def NeedCreateTrigger(self): ...
    def NeedPlayEffectAndSound(self): ...
    def NewSpellResult(self): ...
    def OnAcceleratedChange(self): ...
    def OnBornTick(self, dt): ...
    def OnEnterSnare(self, ownerid): ...
    def OnExitSnare(self, ownerid): ...
    def OnMagicFieldModelLoad(self): ...
    def OnPlaceModelLoad(self): ...
    def PlayBornSound(self): ...
    def PlayDestroyEffect(self): ...
    def PlayEffectAndSound(self): ...
    def PlayLifeDestroySoundAndEffect(self): ...
    def PlayLifeStartSoundAndEffect(self): ...
    def PlayTickEffect(self): ...
    def ProcessShockwave(self): ...
    def ProcessShockwaveImp(self, target, pos, wave_radius): ...
    def RefreshEffectVisible(self): ...
    def RefreshEntityVisibilityOnLightAttack(self, _): ...
    def RefreshModelVisible(self): ...
    def RemoveStoryTick(self, func): ...
    def ReplaceEffects(self, effects): ...
    def SetCollisionFilterInfo(self): ...
    def SetDissolvingDestroy(self): ...
    def ShowModel(self): ...
    def ShowModelExtra(self): ...
    def SimulateDamage(self): ...
    def UnloadEffects(self, force_immediately=False): ...
    def UnloadExtra(self): ...
    def UnloadFog(self, player): ...
    def UnloadSound(self): ...
    def _CheckAndCreateTrigger(self): ...
    def _CreateStoryTickCylinder(self): ...
    def _CreateTriggerCylinder(self): ...
    def _CreateTriggerRectangle(self): ...
    def _CreateTriggerSphere(self): ...
    def _DealWithExtraModelEffect(self): ...
    def _PlayEffectAndSound(self): ...
    def _ShowModelExtra(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_set_dissolving(self, old): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    @property
    def fog_radius(self): ...    @property
    def fog_total_time(self): ...    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    @property
    def is_alive(self): ...    @property
    def is_controller(self): ...    def is_deactived(self): ...
    def is_destroyed(self): ...
    @property
    def is_enemy_field(self): ...    @property
    def is_invincible(self): ...    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def owner(self): ...    @property
    def pos(self): ...    @property
    def position(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    @property
    def unit_model_id(self): ...    @property
    def yaw(self): ...
class MoveFireWallModel(PoseSenderModel):
    logger: Logger = <Logger Model (DEBUG)>

    def AddHiddenReason(self, reason): ...
    def AddLoadTask(self, name): ...
    def AddTargetSlot(self, slot_name, actor): ...
    def AddTechState(self, id, custom_param=None): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def ApplyCustomStencil(self, custom_stencil, is_check=False): ...
    def ApplyFilterMotion(self, apply): ...
    def ApplyMotion(self, flag=True): ...
    def AttachToParent(self, entity, basepoint, hardpoint): ...
    def BatchResetShaderGraphParameter(self, params, layer=-1): ...
    def BatchSetShaderGraphParameter(self, params, values, layer=-1): ...
    def BindBoneColliderCallFunc(self, result): ...
    def BindEventSignalNotify(self): ...
    def CallOwner(self, method, *args, **kwargs): ...
    def ChangeCustomMaterial(self, material_path, **kwargs): ...
    def ChangeShaderGraphMaterial(self, shader_graph_path, layer=-1, inherit=False): ...
    def CheckRecreateSkeletonOnReloaded(self, data): ...
    def ClearALLCueCameraEffect(self): ...
    def ClearAllCueEffectCache(self): ...
    def ClearAllCueSoundCache(self): ...
    def ClearAllSkeletonEffect(self): ...
    def ClearCueEffectCache(self, graph_id, path): ...
    def ClearCueEffectCacheByGraphID(self, graph_id): ...
    def ClearHiddenReason(self): ...
    def ClearMotionBlur(self, elapsedTime, centerU, centerV): ...
    def ClearRigidBodies(self): ...
    def ClearSkeletonEffect(self, effect_id): ...
    def ClearSkeletonEffectByEffectId(self, effect_id): ...
    def ClearSkeletonEffectByEffectIdImmediately(self, effect_id): ...
    def ClearSkeletonEffectImmediately(self, effect_id): ...
    def ClearTechParam(self): ...
    def ClearTechState(self): ...
    def ClearWarmingUpHiddenReason(self): ...
    def CreateFilter(self, debug=False): ...
    def CreatePoseSender(self): ...
    def CreateSpecifyBone(self, bone_name): ...
    def CustomStencilCheck(self, target_stencil, *args): ...
    def DeleteFilter(self): ...
    def DeletePoseSender(self): ...
    def Destroy(self): ...
    def DestroyCppModel(self): ...
    def DisableMixMapAsFarAsPossible(self): ...
    def DisableNormalMap(self): ...
    def DisableOutlined(self): ...
    def DisablePrincipleRole(self): ...
    def EnableFilterWithReason(self, reason): ...
    def EnableOutlined(self, color, thickness): ...
    def EnablePoseSender(self, is_enable): ...
    def EnablePoseSenderWithReason(self, reason): ...
    def FilterMotionNotifyCallback(self, motion): ...
    def FireEvent(self, event, gid=-1): ...
    def GetAllPrim(self, need_sorted=False): ...
    def GetBoneLocalPosition(self, bone): ...
    def GetBoneLocalTransform(self, bone): ...
    def GetBoneModelPosition(self, bone): ...
    def GetBoneTransform(self, bone): ...
    def GetBoneWorldPosition(self, bone): ...
    def GetBoneWorldTransform(self, bone): ...
    def GetGraphHandleInGraphStack(self, graph_name): ...
    def GetMotionSkeletonFile(skeleton): ...
    def GetPrimWorldBound(self): ...
    def GetPrimWorldBoundCentre(self): ...
    def GetPrimWorldBoundCentreWithAttachments(self): ...
    def GetPrimWorldBoundLength(self): ...
    def GetPrimWorldBoundWithAttachments(self): ...
    def GetShaderGraphOriginParameter(self, param, layer=-1): ...
    def GetShaderGraphParameter(self, param, layer): ...
    def GetShaderParameter(self, param): ...
    def GetSkeleton(self): ...
    def GetSkeletonDynamicWorldBound(self): ...
    def GetSkeletonDynamicWorldBoundCentre(self): ...
    def GetSkeletonEffectEntities(self, eff_id): ...
    def GetSkeletonEffectEntitiesByEffectId(self, effect_id): ...
    def GetVariableF(self, varname, gid=-1): ...
    def GetVariableI(self, varname, gid=-1): ...
    def GetVariableS(self, varname, gid=-1): ...
    def GetVariableV3(self, varname, gid=-1): ...
    def GetVariableZ(self, varname, gid=-1): ...
    def HasActorComponent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HaveWarmingUpHiddenReason(self, reason): ...
    def IsEnableOutlined(self): ...
    def IsPrincipleRole(self): ...
    @property
    def IsVisible(self): ...    def JumpToState(self, state, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def Load(self, data, done=None, **create_kwargs): ...
    def MakeSureBones(self): ...
    def MarkPrincipleRole(self): ...
    def ModelExpireCallback(self, ientity): ...
    def OnCineDisplayPerformer(self, trigger, cueinput): ...
    def OnCineHidePerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformers(self, trigger, cueinput): ...
    def OnCineRenamePerformer(self, trigger, cueinput): ...
    def OnVisibleChanged(self, visible): ...
    def PauseGraph(self, pause, gid=-1): ...
    def PlayAnimation(self, anim_name, single_play=True, remove_motion=True, play_speed=1.0): ...
    def PlayEffectById(self, effect_id, max_life=-1, scale=1, bone='root', offset=(0, 0, 0), insure_play=False): ...
    def PlaySkeletonEffect(self, effect_str, max_life=-1, insure_play=False, effect_id=None): ...
    def PopEffectDictByEngineEid(self, engine_eid): ...
    def PopGraph(self, graph_id, blendTime=0): ...
    def PushGraph(self, graph, transtime=0, ratio=0): ...
    def ReceiveDynamicShadow(self): ...
    def Refresh(self): ...
    def RefreshTeammateTechState(self): ...
    def Reload(self, data, done=None, use_ready_to_appear=True): ...
    def ReloadPrimitives(self, data, use_ready_to_appear=True): ...
    def ReloadSkeleton(self, data): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveLoadTask(self, name): ...
    def RemoveTechState(self, proto_id): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def RemoveXRayBlock(self): ...
    def ReplaceGraph(self, graph_id, graph): ...
    def ResetCustomMaterial(self): ...
    def ResetPosResult(self): ...
    def ResetShaderGraphMaterial(self, layer=-1): ...
    def ResetShaderGraphParameter(self, param, layer=-1): ...
    def ResetShaderGraphParameters(self, layer=-1): ...
    def ResetShaderParameter(self, param): ...
    def SetAsCSMRole(self, is_role): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetEnableVisibilityOptimize(self, enable): ...
    def SetFilterInputInterval(self, value): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetLodDistance(self, layer, distance): ...
    def SetLodDistanceAllLayers(self, distances): ...
    def SetNoNearPlaneClip(self, enable): ...
    def SetOutlinedParam(self, color, thickness): ...
    def SetPoseSenderInterval(self, value): ...
    def SetShaderGraphParameter(self, param, value, layer=-1): ...
    def SetShaderGraphParameterRecursively(self, param, value, layer=-1): ...
    def SetShaderParameter(self, param, value, **kwargs): ...
    def SetShaderParameterRecursively(self, param, value): ...
    def SetSkeletonEffectVisible(self, visible): ...
    def SetSkeletonEffectVisibleForEffectId(self, effect_id, visible): ...
    def SetTechState(self): ...
    def SetTechStateParam(self, tech_id, custom_param): ...
    def SetTransformWithAttachmentsImmediately(self, transform): ...
    def SetVariableF(self, varname, varvalue, gid=-1): ...
    def SetVariableI(self, varname, varvalue, gid=-1): ...
    def SetVariableS(self, varname, varvalue, gid=-1): ...
    def SetVariableV3(self, varname, varvalue, gid=-1): ...
    def SetVariableZ(self, varname, varvalue, gid=-1): ...
    def SetWarmingUp(self, value): ...
    def SetWarmingUpAppearImmediately(self, value): ...
    def ShiftGraph(self, gid, offset): ...
    def SignalNotifyCallback(self, trigger, stype, signalStr): ...
    def SkeletonExpireCallback(self, skeleton): ...
    def StopAnimation(self, anim_name): ...
    def UnableFilterWithReason(self, reason): ...
    def UnablePoseSenderWithReason(self, reason): ...
    def UseDistancedEnemyTechState(self, param, param2): ...
    def UseTechEdgeLine(self, color, thickness): ...
    def UseTechFrozen(self): ...
    def UseTechHighLightXray(self, param, param2, color2): ...
    def UseTechHighlight(self, color, frequency=0.0): ...
    def UseTechXray(self, color2=None, param2=None): ...
    def _CheckSameTachStatus(self, parent, basepoint, hardpoint): ...
    def _GetAvailableModelInfo(self, model_data): ...
    def _ProcessCueEnd(self, prev, trigger): ...
    def _SetVisible(self, visible): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, interval, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def cue_signal_effect_attach_detach(self, trigger, signal_str): ...
    def cue_signal_event(self, trigger, signal_str): ...
    def cue_signal_execute_third_model(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate_enable(self, trigger, signal_str): ...
    def cue_signal_motion_blur_to_percent(self, trigger, signal_str): ...
    def cue_signal_player_event(self, trigger, signal_str): ...
    def cue_signal_sound_event(self, trigger, signal_str): ...
    def cue_signal_sound_far_event(self, trigger, signal_str): ...
    def cue_signal_variable_event_sync_stack(self, trigger, signal_str): ...
    def cue_type_node_transition_excute(self, trigger, curinput): ...
    def isModelOnlyValid(self): ...
    def isValid(self): ...
    @property
    def is_destroyed(self): ...    @property
    def is_loaded(self): ...    def onCineDismissPerformer(self, trigger, cueinput): ...
    def onCineDismissPerformers(self, trigger, cueinput): ...
    def onCineDisplayCaption(self, trigger, cueinput): ...
    def onLoaded(self): ...
    @property
    def poseSender(self): ...    @property
    def position(self): ...    @property
    def scale(self): ...    @property
    def skeleton(self): ...    @property
    def space(self): ...    @property
    def yaw(self): ...
class PoseSenderModel(SimpleModel):
    logger: Logger = <Logger Model (DEBUG)>

    def AddHiddenReason(self, reason): ...
    def AddLoadTask(self, name): ...
    def AddTargetSlot(self, slot_name, actor): ...
    def AddTechState(self, id, custom_param=None): ...
    def AddWarmingUpHiddenReason(self, reason): ...
    def ApplyCustomStencil(self, custom_stencil, is_check=False): ...
    def ApplyFilterMotion(self, apply): ...
    def ApplyMotion(self, flag=True): ...
    def AttachToParent(self, entity, basepoint, hardpoint): ...
    def BatchResetShaderGraphParameter(self, params, layer=-1): ...
    def BatchSetShaderGraphParameter(self, params, values, layer=-1): ...
    def BindBoneColliderCallFunc(self, result): ...
    def BindEventSignalNotify(self): ...
    def CallOwner(self, method, *args, **kwargs): ...
    def ChangeCustomMaterial(self, material_path, **kwargs): ...
    def ChangeShaderGraphMaterial(self, shader_graph_path, layer=-1, inherit=False): ...
    def CheckRecreateSkeletonOnReloaded(self, data): ...
    def ClearALLCueCameraEffect(self): ...
    def ClearAllCueEffectCache(self): ...
    def ClearAllCueSoundCache(self): ...
    def ClearAllSkeletonEffect(self): ...
    def ClearCueEffectCache(self, graph_id, path): ...
    def ClearCueEffectCacheByGraphID(self, graph_id): ...
    def ClearHiddenReason(self): ...
    def ClearMotionBlur(self, elapsedTime, centerU, centerV): ...
    def ClearRigidBodies(self): ...
    def ClearSkeletonEffect(self, effect_id): ...
    def ClearSkeletonEffectByEffectId(self, effect_id): ...
    def ClearSkeletonEffectByEffectIdImmediately(self, effect_id): ...
    def ClearSkeletonEffectImmediately(self, effect_id): ...
    def ClearTechParam(self): ...
    def ClearTechState(self): ...
    def ClearWarmingUpHiddenReason(self): ...
    def CreateFilter(self, debug=False): ...
    def CreatePoseSender(self): ...
    def CreateSpecifyBone(self, bone_name): ...
    def CustomStencilCheck(self, target_stencil, *args): ...
    def DeleteFilter(self): ...
    def DeletePoseSender(self): ...
    def Destroy(self): ...
    def DestroyCppModel(self): ...
    def DisableMixMapAsFarAsPossible(self): ...
    def DisableNormalMap(self): ...
    def DisableOutlined(self): ...
    def DisablePrincipleRole(self): ...
    def EnableFilterWithReason(self, reason): ...
    def EnableOutlined(self, color, thickness): ...
    def EnablePoseSender(self, is_enable): ...
    def EnablePoseSenderWithReason(self, reason): ...
    def FilterMotionNotifyCallback(self, motion): ...
    def FireEvent(self, event, gid=-1): ...
    def GetAllPrim(self, need_sorted=False): ...
    def GetBoneLocalPosition(self, bone): ...
    def GetBoneLocalTransform(self, bone): ...
    def GetBoneModelPosition(self, bone): ...
    def GetBoneTransform(self, bone): ...
    def GetBoneWorldPosition(self, bone): ...
    def GetBoneWorldTransform(self, bone): ...
    def GetGraphHandleInGraphStack(self, graph_name): ...
    def GetMotionSkeletonFile(skeleton): ...
    def GetPrimWorldBound(self): ...
    def GetPrimWorldBoundCentre(self): ...
    def GetPrimWorldBoundCentreWithAttachments(self): ...
    def GetPrimWorldBoundLength(self): ...
    def GetPrimWorldBoundWithAttachments(self): ...
    def GetShaderGraphOriginParameter(self, param, layer=-1): ...
    def GetShaderGraphParameter(self, param, layer): ...
    def GetShaderParameter(self, param): ...
    def GetSkeleton(self): ...
    def GetSkeletonDynamicWorldBound(self): ...
    def GetSkeletonDynamicWorldBoundCentre(self): ...
    def GetSkeletonEffectEntities(self, eff_id): ...
    def GetSkeletonEffectEntitiesByEffectId(self, effect_id): ...
    def GetVariableF(self, varname, gid=-1): ...
    def GetVariableI(self, varname, gid=-1): ...
    def GetVariableS(self, varname, gid=-1): ...
    def GetVariableV3(self, varname, gid=-1): ...
    def GetVariableZ(self, varname, gid=-1): ...
    def HasActorComponent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HaveWarmingUpHiddenReason(self, reason): ...
    def IsEnableOutlined(self): ...
    def IsPrincipleRole(self): ...
    @property
    def IsVisible(self): ...    def JumpToState(self, state, info=None, transtime=0.1, reset=False, spell_id=0): ...
    def Load(self, data, done=None, **create_kwargs): ...
    def MakeSureBones(self): ...
    def MarkPrincipleRole(self): ...
    def ModelExpireCallback(self, ientity): ...
    def OnCineDisplayPerformer(self, trigger, cueinput): ...
    def OnCineHidePerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformer(self, trigger, cueinput): ...
    def OnCineRecruitPerformers(self, trigger, cueinput): ...
    def OnCineRenamePerformer(self, trigger, cueinput): ...
    def OnVisibleChanged(self, visible): ...
    def PauseGraph(self, pause, gid=-1): ...
    def PlayAnimation(self, anim_name, single_play=True, remove_motion=True, play_speed=1.0): ...
    def PlayEffectById(self, effect_id, max_life=-1, scale=1, bone='root', offset=(0, 0, 0), insure_play=False): ...
    def PlaySkeletonEffect(self, effect_str, max_life=-1, insure_play=False, effect_id=None): ...
    def PopEffectDictByEngineEid(self, engine_eid): ...
    def PopGraph(self, graph_id, blendTime=0): ...
    def PushGraph(self, graph, transtime=0, ratio=0): ...
    def ReceiveDynamicShadow(self): ...
    def Refresh(self): ...
    def RefreshTeammateTechState(self): ...
    def Reload(self, data, done=None, use_ready_to_appear=True): ...
    def ReloadPrimitives(self, data, use_ready_to_appear=True): ...
    def ReloadSkeleton(self, data): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveLoadTask(self, name): ...
    def RemoveTechState(self, proto_id): ...
    def RemoveWarmingUpHiddenReason(self, reason): ...
    def RemoveXRayBlock(self): ...
    def ReplaceGraph(self, graph_id, graph): ...
    def ResetCustomMaterial(self): ...
    def ResetPosResult(self): ...
    def ResetShaderGraphMaterial(self, layer=-1): ...
    def ResetShaderGraphParameter(self, param, layer=-1): ...
    def ResetShaderGraphParameters(self, layer=-1): ...
    def ResetShaderParameter(self, param): ...
    def SetAsCSMRole(self, is_role): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetEnableVisibilityOptimize(self, enable): ...
    def SetFilterInputInterval(self, value): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetLodDistance(self, layer, distance): ...
    def SetLodDistanceAllLayers(self, distances): ...
    def SetNoNearPlaneClip(self, enable): ...
    def SetOutlinedParam(self, color, thickness): ...
    def SetPoseSenderInterval(self, value): ...
    def SetShaderGraphParameter(self, param, value, layer=-1): ...
    def SetShaderGraphParameterRecursively(self, param, value, layer=-1): ...
    def SetShaderParameter(self, param, value, **kwargs): ...
    def SetShaderParameterRecursively(self, param, value): ...
    def SetSkeletonEffectVisible(self, visible): ...
    def SetSkeletonEffectVisibleForEffectId(self, effect_id, visible): ...
    def SetTechState(self): ...
    def SetTechStateParam(self, tech_id, custom_param): ...
    def SetTransformWithAttachmentsImmediately(self, transform): ...
    def SetVariableF(self, varname, varvalue, gid=-1): ...
    def SetVariableI(self, varname, varvalue, gid=-1): ...
    def SetVariableS(self, varname, varvalue, gid=-1): ...
    def SetVariableV3(self, varname, varvalue, gid=-1): ...
    def SetVariableZ(self, varname, varvalue, gid=-1): ...
    def SetWarmingUp(self, value): ...
    def SetWarmingUpAppearImmediately(self, value): ...
    def ShiftGraph(self, gid, offset): ...
    def SignalNotifyCallback(self, trigger, stype, signalStr): ...
    def SkeletonExpireCallback(self, skeleton): ...
    def StopAnimation(self, anim_name): ...
    def UnableFilterWithReason(self, reason): ...
    def UnablePoseSenderWithReason(self, reason): ...
    def UseDistancedEnemyTechState(self, param, param2): ...
    def UseTechEdgeLine(self, color, thickness): ...
    def UseTechFrozen(self): ...
    def UseTechHighLightXray(self, param, param2, color2): ...
    def UseTechHighlight(self, color, frequency=0.0): ...
    def UseTechXray(self, color2=None, param2=None): ...
    def _CheckSameTachStatus(self, parent, basepoint, hardpoint): ...
    def _GetAvailableModelInfo(self, model_data): ...
    def _ProcessCueEnd(self, prev, trigger): ...
    def _SetVisible(self, visible): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, interval, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def cue_signal_effect_attach_detach(self, trigger, signal_str): ...
    def cue_signal_event(self, trigger, signal_str): ...
    def cue_signal_execute_third_model(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate(self, trigger, signal_str): ...
    def cue_signal_fps_camera_rotate_enable(self, trigger, signal_str): ...
    def cue_signal_motion_blur_to_percent(self, trigger, signal_str): ...
    def cue_signal_player_event(self, trigger, signal_str): ...
    def cue_signal_sound_event(self, trigger, signal_str): ...
    def cue_signal_sound_far_event(self, trigger, signal_str): ...
    def cue_signal_variable_event_sync_stack(self, trigger, signal_str): ...
    def cue_type_node_transition_excute(self, trigger, curinput): ...
    def isModelOnlyValid(self): ...
    def isValid(self): ...
    @property
    def is_destroyed(self): ...    @property
    def is_loaded(self): ...    def onCineDismissPerformer(self, trigger, cueinput): ...
    def onCineDismissPerformers(self, trigger, cueinput): ...
    def onCineDisplayCaption(self, trigger, cueinput): ...
    def onLoaded(self): ...
    @property
    def poseSender(self): ...    @property
    def position(self): ...    @property
    def scale(self): ...    @property
    def skeleton(self): ...    @property
    def space(self): ...    @property
    def yaw(self): ...

def with_tag(*args): ...

