# module: gclient.gameplay.logic_base.entities.oilbox

import effect_util

class CommonItem(ClientAreaEntity):
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = False
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    logger: Logger = <Logger CommonItem (DEBUG)>

    def BeforeDestroy(self): ...
    def CacheModel(self): ...
    def CreateCapsuleTrigger(self, radius, height, callback, filter_info, move_type=1, pos_height=None): ...
    def CreateTriggerRectangle(self, x, y, z, callback, is_trigger, move_type=1, offset=None): ...
    def CreateTriggerSphere(self, radius, callback, is_trigger=True, local_trans=None): ...
    def DestroyExtra(self): ...
    def GetCollisionFilter(self): ...
    def GetMaterialTypeID(self): ...
    def GetReplaceModelID(self, model_id): ...
    def GetRotationFromAToB(self, v1, v2): ...
    def GetTriggerFilterInfo(self): ...
    def GetUnitModelProto(self, model_id): ...
    def InitModel(self): ...
    @property
    def IsVisible(self): ...    def OnModelLoad(self): ...
    def ShowModel(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    def is_deactived(self): ...
    def is_destroyed(self): ...
    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def pos(self): ...    @property
    def position(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    @property
    def yaw(self): ...
class EntityDestroyType(enum):
    BreakAndDissolving: int = 2
    Delay: int = 1
    Dissolving: int = 3
    HideAndDelay: int = 0
    name_to_values: dict = {'HideAndDelay': 0, 'Delay': 1, 'BreakAndDissolving': 2, 'Dissolving': 3}
    value_to_names: dict = {0: 'HideAndDelay', 1: 'Delay', 2: 'BreakAndDissolving', 3: 'Dissolving'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class EntityDissolvingComponent(object):
    def BreakAnimAndDissolvingDestroy(self): ...
    def CancelDissolvingTimer(self): ...
    def CommonDelayDestroy(self): ...
    def DissolvingTick(self): ...
    def HideAndDelayDestroy(self): ...
    def OnBornTick(self, dt): ...
    def SetDissolvingDestroy(self): ...
    def _on_set_dissolving(self, old): ...

class ISimpleCombatUnit(ISimpleCombatUnitBase):
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = False
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = True
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False

    @property
    def is_alive(self): ...    @property
    def is_invincible(self): ...
class Oilbox(CommonItem):
    BURN_FACTOR: float = 0.8
    IsATM: bool = False
    IsATMGuardAI: bool = False
    IsAirDrop: bool = False
    IsAmmoBox: bool = False
    IsArrow: bool = False
    IsAttackDrone: bool = False
    IsAvatar: bool = False
    IsBarrieCannon: bool = False
    IsBomb: bool = False
    IsBuilding: bool = False
    IsChaosUav: bool = False
    IsCombatAvatar: bool = False
    IsCombatAvatarSniper: bool = False
    IsCombatAvatarZombieXray: bool = False
    IsCombatTeam: bool = False
    IsCombatUnit: bool = False
    IsContrabandPlane: bool = False
    IsCrack: bool = False
    IsCrow: bool = False
    IsCureUav: bool = False
    IsCureUavFix: bool = False
    IsDestructible: bool = False
    IsDummyCombatAvatar: bool = False
    IsEmoteTree: bool = False
    IsEnergyStronghold: bool = False
    IsEntityAttach: bool = False
    IsEntityMaster: bool = False
    IsGameLogic: bool = False
    IsGlass: bool = False
    IsHelenAI: bool = False
    IsHolographicRobot: bool = False
    IsIceWall: bool = False
    IsIgnoreCue: bool = False
    IsItem: bool = False
    IsItemSpaceSnare: bool = False
    IsMagicField: bool = False
    IsMonitorMissile: bool = False
    IsMonster: bool = False
    IsMovingPlatform: bool = False
    IsObserveAvatar: bool = False
    IsOccupyContractTarget: bool = False
    IsOccupyContractTargetNew: bool = False
    IsOilbox: bool = True
    IsPhyBall: bool = False
    IsPlayerCombatAvatar: bool = False
    IsPlayerObserveAvatar: bool = False
    IsPortableShop: bool = False
    IsRPGMissile: bool = False
    IsReplayPuppet: bool = False
    IsReplayRecorder: bool = False
    IsRobotCombatAvatar: bool = False
    IsRobotCombatAvatarZombie: bool = False
    IsSafeBox: bool = False
    IsSaveDrone: bool = False
    IsSaveMachine: bool = False
    IsScoutArrow: bool = False
    IsSearchContractBox: bool = False
    IsShield: bool = False
    IsShop: bool = False
    IsSimpleCombatUnit: bool = True
    IsSpellDrone: bool = False
    IsStickyMaster: bool = False
    IsStronghold: bool = False
    IsStropUav: bool = False
    IsSupply: bool = False
    IsSwordSpirit: bool = False
    IsSyncTransEntity: bool = False
    IsSystemKiller: bool = False
    IsVehicle: bool = False
    IsVirtualInteractionEntity: bool = False
    NinjaBeacon: bool = False
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    is_fps_avatar: bool = False
    is_replay_avatar: bool = False
    is_replay_room: bool = False
    logger: Logger = <Logger Oilbox (DEBUG)>

    def BeforeDestroy(self): ...
    def CacheModel(self): ...
    def CreateCapsuleTrigger(self, radius, height, callback, filter_info, move_type=1, pos_height=None): ...
    def CreateTriggerRectangle(self, x, y, z, callback, is_trigger, move_type=1, offset=None): ...
    def CreateTriggerSphere(self, radius, callback, is_trigger=True, local_trans=None): ...
    def DestroyExtra(self): ...
    def GetCollisionFilter(self): ...
    def GetMaterialTypeID(self): ...
    def GetReplaceModelID(self, model_id): ...
    def GetRotationFromAToB(self, v1, v2): ...
    def GetTriggerFilterInfo(self): ...
    def GetUnitModelProto(self, model_id): ...
    def InitModel(self): ...
    @property
    def IsVisible(self): ...    def OnModelLoad(self): ...
    def PlayLifeDestroySoundAndEffect(self): ...
    def ShowModel(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_set_hp(self, old): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    @property
    def is_alive(self): ...    @property
    def is_broken(self): ...    def is_deactived(self): ...
    def is_destroyed(self): ...
    @property
    def is_invincible(self): ...    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def pos(self): ...    @property
    def position(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    @property
    def yaw(self): ...

def Components(*components, **kwargs): ...
def Property(name, default, flag=2): ...
def with_tag(*args): ...

