# module: gclient.gameplay.logic_base.bot.goal_spec

import consts

class GoalBase(object):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalRecoverArmor(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalUseMedicine(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def PreCheckCanRun(owner): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...

