# module: gclient.gameplay.logic_base.bot.goal_attack

import cconst
import formula
import math
import random
import six2
import time

class BlackboardKey(enum):
    AGILITY_LEVEL: str = 'agility_level'
    ATTACK_PLAYER_OVERTIME: str = 'attack_player_overtime'
    ATTACK_ROBOT_OVERTIME: str = 'attack_robot_overtime'
    ATTACK_TARGET: str = 'attack_target'
    AVOID_GAS: str = 'avoid_gas'
    BEAT_BACK_IN_GAS: str = 'beat_back_in_gas'
    BEAT_BACK_TIME: str = 'beat_back_time'
    BOT_BEHAVIOR_TYPE: str = 'bot_behavior_type'
    IS_ESCAPING: str = 'escape'
    IS_SPRINT: str = 'is_sprint'
    NAVI_FLAG: str = 'navi_flag'
    STRONGHOLD: str = 'stronghold'
    name_to_values: dict = {'IS_ESCAPING': 'escape', 'IS_SPRINT': 'is_sprint', 'AGILITY_LEVEL': 'agility_level', 'NAVI_FLAG': 'navi_flag', 'ATTACK_TARGET': 'attack_target', 'ATTACK_ROBOT_OVERTIME': 'attack_robot_overtime', 'ATTACK_PLAYER_OVERTIME': 'attack_player_overtime', 'BEAT_BACK_TIME': 'beat_back_time', 'BEAT_BACK_IN_GAS': 'beat_back_in_gas', 'AVOID_GAS': 'avoid_gas', 'BOT_BEHAVIOR_TYPE': 'bot_behavior_type', 'STRONGHOLD': 'stronghold'}
    value_to_names: dict = {'escape': 'IS_ESCAPING', 'is_sprint': 'IS_SPRINT', 'agility_level': 'AGILITY_LEVEL', 'navi_flag': 'NAVI_FLAG', 'attack_target': 'ATTACK_TARGET', 'attack_robot_overtime': 'ATTACK_ROBOT_OVERTIME', 'attack_player_overtime': 'ATTACK_PLAYER_OVERTIME', 'beat_back_time': 'BEAT_BACK_TIME', 'beat_back_in_gas': 'BEAT_BACK_IN_GAS', 'avoid_gas': 'AVOID_GAS', 'bot_behavior_type': 'BOT_BEHAVIOR_TYPE', 'stronghold': 'STRONGHOLD'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class CombatState(enum):
    ALIVE: int = 0
    DEAD: int = 2
    DYING: int = 1
    GHOST: int = 3
    NONE: int = 4
    name_to_values: dict = {'ALIVE': 0, 'DYING': 1, 'DEAD': 2, 'GHOST': 3, 'NONE': 4}
    value_to_names: dict = {0: 'ALIVE', 1: 'DYING', 2: 'DEAD', 3: 'GHOST', 4: 'NONE'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class GoalActionMove(GoalBase):
    MOVE_DIRECTION_LIST_FAR: list = [1, 2, 3, 4, 5, 6]
    MOVE_DIRECTION_LIST_NEAR: list = [2, 3, 4, 5]
    MOVE_DIR_XY_MAP: dict = {1: (0.5, 0.5), 2: (1, 0), 3: (0.5, -0.5), 4: (-0.5, -0.5), 5: (-1, 0), 6: (-0.5, 0.5)}
    MOVE_YAW_MAP: dict = {1: -0.7853981633974483, 2: -1.5707963267948966, 3: -2.356194490192345, 4: 2.356194490192345, 5: 1.5707963267948966, 6: 0.7853981633974483}

    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def TryMove(self): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalAimThenFire(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalAimThenFireInSitu(GoalSequence):
    def Activate(self, brain): ...
    def AddChild(self, child): ...
    def Deactive(self, result=None): ...
    def GetEntity(self, guid): ...
    def OnChildActivate(self, child): ...
    def OnChildDeactive(self, child): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalAttackAndFollow(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalAttackBindTarget(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalAttackInSitu(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalAttackInSituWithFollow(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalAttackMove(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def NextMove(self): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalBase(object):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalCameraAimTarget(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalCameraFollowTarget(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalCountdown(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalFireAndMove(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def InterruptMoveGoal(self): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def RunMoveGoal(self, goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalFireInSitu(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalFollowAndSearch(GoalSequence):
    def Activate(self, brain): ...
    def AddChild(self, child): ...
    def Deactive(self, result=None): ...
    def GetEntity(self, guid): ...
    def OnChildActivate(self, child): ...
    def OnChildDeactive(self, child): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalGunAutoFire(GoalBase):
    def Activate(self, brain): ...
    def CheckCanEnterFireInterval(self): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RefreshFireCount(self): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalGunFireMove(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def NextMove(self): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalGunReload(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalGunReloadMove(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalGunReloadMoveMelee(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def NextMove(self): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalGunReloadMoveMiddle(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalJump(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalLookAround(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalMoveByPath(GoalMoveByPathBase):
    def Activate(self, brain): ...
    def CanControlYaw(self): ...
    def CheckAndMoveToNextWaypoint(self, dt): ...
    def CheckArrivedCurrentWaypoint(self, current_pos): ...
    def CheckBlocking(self): ...
    def Deactive(self, result=0): ...
    def DoOnBlocking(self): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def TickCustomMoveAction(self, dt): ...
    def TurnToNextWaypoint(self, target_pos, current_pos): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def current_waypoint(self): ...    @property
    def is_finished(self): ...    @property
    def space(self): ...    @property
    def target_waypoint(self): ...
class GoalMoveDirection(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalMoveHorizontally(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalNavigateTo(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnFindPath(self, points): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalParallel(GoalBase):
    def Activate(self, brain): ...
    def AddChild(self, child): ...
    def Deactive(self, result=None): ...
    def GetEntity(self, guid): ...
    def OnChildActivate(self, child): ...
    def OnChildDeactive(self, child): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChild(self, child): ...
    def RunChildGoal(self, child): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildByType(self, typ): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalPeek(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnFindPath(self, path): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalReloadWhenIdle(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalRescue(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalResult(enum):
    DESTROY: int = 3
    FAILED: int = 1
    INTERRUPTED: int = 2
    SUCCESS: int = 0
    name_to_values: dict = {'SUCCESS': 0, 'FAILED': 1, 'INTERRUPTED': 2, 'DESTROY': 3}
    value_to_names: dict = {0: 'SUCCESS', 1: 'FAILED', 2: 'INTERRUPTED', 3: 'DESTROY'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class GoalSequence(GoalBase):
    def Activate(self, brain): ...
    def AddChild(self, child): ...
    def Deactive(self, result=None): ...
    def GetEntity(self, guid): ...
    def OnChildActivate(self, child): ...
    def OnChildDeactive(self, child): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalState(enum):
    FINISHED: int = 2
    READY: int = 0
    RUNNING: int = 1
    name_to_values: dict = {'READY': 0, 'RUNNING': 1, 'FINISHED': 2}
    value_to_names: dict = {0: 'READY', 1: 'RUNNING', 2: 'FINISHED'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class GunType(enum):
    AR: int = 1
    LMG: int = 4
    MR: int = 5
    NG: int = 9
    NONE: int = 0
    PT: int = 7
    RL: int = 8
    SG: int = 3
    SMG: int = 2
    SR: int = 6
    name_to_values: dict = {'NONE': 0, 'AR': 1, 'SMG': 2, 'SG': 3, 'LMG': 4, 'MR': 5, 'SR': 6, 'PT': 7, 'RL': 8, 'NG': 9}
    value_to_names: dict = {0: 'NONE', 1: 'AR', 2: 'SMG', 3: 'SG', 4: 'LMG', 5: 'MR', 6: 'SR', 7: 'PT', 8: 'RL', 9: 'NG'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class WayPoint(object):
    flag: member_descriptor = <member 'flag' of 'WayPoint' objects>
    position: member_descriptor = <member 'position' of 'WayPoint' objects>

    @property
    def is_offmesh_connection(self): ...

def NormailzeTargetYaw(current, target): ...

