# module: gclient.gameplay.logic_base.bot.goal_move

import MObject
import MType
import cconst
import debug_util
import formula
import math
import random
import six2
import time
import weapon_util

class BlackboardKey(enum):
    AGILITY_LEVEL: str = 'agility_level'
    ATTACK_PLAYER_OVERTIME: str = 'attack_player_overtime'
    ATTACK_ROBOT_OVERTIME: str = 'attack_robot_overtime'
    ATTACK_TARGET: str = 'attack_target'
    AVOID_GAS: str = 'avoid_gas'
    BEAT_BACK_IN_GAS: str = 'beat_back_in_gas'
    BEAT_BACK_TIME: str = 'beat_back_time'
    BOT_BEHAVIOR_TYPE: str = 'bot_behavior_type'
    IS_ESCAPING: str = 'escape'
    IS_SPRINT: str = 'is_sprint'
    NAVI_FLAG: str = 'navi_flag'
    STRONGHOLD: str = 'stronghold'
    name_to_values: dict = {'IS_ESCAPING': 'escape', 'IS_SPRINT': 'is_sprint', 'AGILITY_LEVEL': 'agility_level', 'NAVI_FLAG': 'navi_flag', 'ATTACK_TARGET': 'attack_target', 'ATTACK_ROBOT_OVERTIME': 'attack_robot_overtime', 'ATTACK_PLAYER_OVERTIME': 'attack_player_overtime', 'BEAT_BACK_TIME': 'beat_back_time', 'BEAT_BACK_IN_GAS': 'beat_back_in_gas', 'AVOID_GAS': 'avoid_gas', 'BOT_BEHAVIOR_TYPE': 'bot_behavior_type', 'STRONGHOLD': 'stronghold'}
    value_to_names: dict = {'escape': 'IS_ESCAPING', 'is_sprint': 'IS_SPRINT', 'agility_level': 'AGILITY_LEVEL', 'navi_flag': 'NAVI_FLAG', 'attack_target': 'ATTACK_TARGET', 'attack_robot_overtime': 'ATTACK_ROBOT_OVERTIME', 'attack_player_overtime': 'ATTACK_PLAYER_OVERTIME', 'beat_back_time': 'BEAT_BACK_TIME', 'beat_back_in_gas': 'BEAT_BACK_IN_GAS', 'avoid_gas': 'AVOID_GAS', 'bot_behavior_type': 'BOT_BEHAVIOR_TYPE', 'stronghold': 'STRONGHOLD'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class BotPubProperty(enum):
    ActiveAttackDist: int = 1
    PassiveAttackDist: int = 2
    name_to_values: dict = {'ActiveAttackDist': 1, 'PassiveAttackDist': 2}
    value_to_names: dict = {1: 'ActiveAttackDist', 2: 'PassiveAttackDist'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class GoalAimTargetPos(GoalBase):
    JUMP_AIM: int = 3
    MOVE_AIM: int = 2
    MOVE_AND_JUMP_AIM: int = 4
    STAY_AIM: int = 1

    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalAvoidGas(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalAvoidGasWithTargetPos(GoalBase):
    def Activate(self, brain): ...
    def CalculateTangentPoint(center, radius, point): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalBase(object):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalBreakAway(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalCameraAimTarget(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalCameraFollowTarget(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalCameraFollowTargetPos(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalCountdown(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalCrouch(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalDetectFromShelter(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnFindLocations(self, locations): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalDetectTargetSector(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalDisturbFromShelter(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalDyingStruggling(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalDyingStrugglingNew(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def IsMoving(self): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalEscapeByPath(GoalMoveByPathBase):
    def Activate(self, brain): ...
    def CanControlYaw(self): ...
    def CheckAndMoveToNextWaypoint(self, dt): ...
    def CheckArrivedCurrentWaypoint(self, current_pos): ...
    def CheckBlocking(self): ...
    def Deactive(self, result=0): ...
    def DoOnBlocking(self): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def TickCustomMoveAction(self, dt): ...
    def TurnToNextWaypoint(self, target_pos, current_pos): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def current_waypoint(self): ...    @property
    def is_finished(self): ...    @property
    def space(self): ...    @property
    def target_waypoint(self): ...
class GoalFlyToGround(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalFollowAndSearch(GoalSequence):
    def Activate(self, brain): ...
    def AddChild(self, child): ...
    def Deactive(self, result=None): ...
    def GetEntity(self, guid): ...
    def OnChildActivate(self, child): ...
    def OnChildDeactive(self, child): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalHideToShelter(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnQueryTacticalLocations(self, locations): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalIdle(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalJump(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalLeaveAircraft(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalLookAround(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalMoveAndDetect(GoalBase):
    STATE_EXPAND: int = 1
    STATE_SHRINK: int = 3
    STATE_STAY: int = 2

    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalMoveBack(GoalMoveByPathBase):
    def Activate(self, brain): ...
    def CanControlYaw(self): ...
    def CheckAndMoveToNextWaypoint(self, dt): ...
    def CheckArrivedCurrentWaypoint(self, current_pos): ...
    def CheckBlocking(self): ...
    def Deactive(self, result=0): ...
    def DoOnBlocking(self): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def TickCustomMoveAction(self, dt): ...
    def TurnToNextWaypoint(self, target_pos, current_pos): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def current_waypoint(self): ...    @property
    def is_finished(self): ...    @property
    def space(self): ...    @property
    def target_waypoint(self): ...
class GoalMoveByPath(GoalMoveByPathBase):
    def Activate(self, brain): ...
    def CanControlYaw(self): ...
    def CheckAndMoveToNextWaypoint(self, dt): ...
    def CheckArrivedCurrentWaypoint(self, current_pos): ...
    def CheckBlocking(self): ...
    def Deactive(self, result=0): ...
    def DoOnBlocking(self): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def TickCustomMoveAction(self, dt): ...
    def TurnToNextWaypoint(self, target_pos, current_pos): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def current_waypoint(self): ...    @property
    def is_finished(self): ...    @property
    def space(self): ...    @property
    def target_waypoint(self): ...
class GoalMoveByPathBase(GoalBase):
    def Activate(self, brain): ...
    def CanControlYaw(self): ...
    def CheckAndMoveToNextWaypoint(self, dt): ...
    def CheckArrivedCurrentWaypoint(self, current_pos): ...
    def CheckBlocking(self): ...
    def Deactive(self, result=0): ...
    def DoOnBlocking(self): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def TickCustomMoveAction(self, dt): ...
    def TurnToNextWaypoint(self, target_pos, current_pos): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def current_waypoint(self): ...    @property
    def is_finished(self): ...    @property
    def space(self): ...    @property
    def target_waypoint(self): ...
class GoalMoveForward(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalMoveToRandomPos(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnFindPath(self, target_pos, points): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalMoveToRandomSnare(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnFindPath(self, target_pos, points): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalMoveWithFocus(GoalMoveByPathBase):
    def Activate(self, brain): ...
    def CanControlYaw(self): ...
    def CheckAndMoveToNextWaypoint(self, dt): ...
    def CheckArrivedCurrentWaypoint(self, current_pos): ...
    def CheckBlocking(self): ...
    def Deactive(self, result=0): ...
    def DoOnBlocking(self): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def TickCustomMoveAction(self, dt): ...
    def TurnToNextWaypoint(self, target_pos, current_pos): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def current_waypoint(self): ...    @property
    def is_finished(self): ...    @property
    def space(self): ...    @property
    def target_waypoint(self): ...
class GoalNavToTargetPosWithFocus(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnFindPath(self, points): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalNavToTargetWithMoveBack(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnFindPath(self, points): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalNavigateTo(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnFindPath(self, points): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalOnHit(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalParachute(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalReloadWhenIdle(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalResult(enum):
    DESTROY: int = 3
    FAILED: int = 1
    INTERRUPTED: int = 2
    SUCCESS: int = 0
    name_to_values: dict = {'SUCCESS': 0, 'FAILED': 1, 'INTERRUPTED': 2, 'DESTROY': 3}
    value_to_names: dict = {0: 'SUCCESS', 1: 'FAILED', 2: 'INTERRUPTED', 3: 'DESTROY'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class GoalSearchForGun(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnFindPath(self, guid, points): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def TryDetectGunOnGround(self): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalSequence(GoalBase):
    def Activate(self, brain): ...
    def AddChild(self, child): ...
    def Deactive(self, result=None): ...
    def GetEntity(self, guid): ...
    def OnChildActivate(self, child): ...
    def OnChildDeactive(self, child): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalSlide(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalSnakeLikeMove(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalSprint(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalState(enum):
    FINISHED: int = 2
    READY: int = 0
    RUNNING: int = 1
    name_to_values: dict = {'READY': 0, 'RUNNING': 1, 'FINISHED': 2}
    value_to_names: dict = {0: 'READY', 1: 'RUNNING', 2: 'FINISHED'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class GoalStrop(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalSuperSprint(GoalBase):
    def Activate(self, brain): ...
    def Deactive(self, result=0): ...
    def GetEntity(self, guid): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class GoalSuperSprintSlide(GoalSequence):
    def Activate(self, brain): ...
    def AddChild(self, child): ...
    def Deactive(self, result=None): ...
    def GetEntity(self, guid): ...
    def OnChildActivate(self, child): ...
    def OnChildDeactive(self, child): ...
    def OnChildGoalCompleted(self, child_goal): ...
    def OnEnter(self): ...
    def OnExit(self): ...
    def OnTick(self, dt): ...
    def PopBlackboard(self, key): ...
    def ReadBlackboard(self, key, default=None): ...
    def RunChildGoal(self, child_goal): ...
    def RunCustomChildGoal(self, child_goal): ...
    def StopChildGoal(self): ...
    def StopCustomChildGoal(self, child_goal): ...
    def TickChildGoal(self, dt): ...
    def TickCustomChildGoal(self, child_goal, dt): ...
    def WriteBlackboard(self, key, value): ...
    @property
    def is_finished(self): ...    @property
    def space(self): ...
class HelpState(enum):
    NONE: int = 0
    OTHER: int = 2
    SELF: int = 1
    name_to_values: dict = {'NONE': 0, 'SELF': 1, 'OTHER': 2}
    value_to_names: dict = {0: 'NONE', 1: 'SELF', 2: 'OTHER'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class ModelPoseType(enum):
    Crouch: int = 1
    Jump: int = 2
    Ladder: int = 6
    Prone: int = 4
    Slide: int = 3
    Stand: int = 0
    Swim: int = 5
    name_to_values: dict = {'Stand': 0, 'Crouch': 1, 'Jump': 2, 'Slide': 3, 'Prone': 4, 'Swim': 5, 'Ladder': 6}
    value_to_names: dict = {0: 'Stand', 1: 'Crouch', 2: 'Jump', 3: 'Slide', 4: 'Prone', 5: 'Swim', 6: 'Ladder'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class ParaAvatarStage(enum):
    Cinematics: int = 1
    CloseParachute: int = 6
    Default: int = 0
    Finish: int = 9
    FreeFall: int = 3
    FreeFallWithWeapon: int = 4
    LandGround: int = 8
    OnAircraft: int = 2
    OpenParachute: int = 5
    Parachute: int = 7
    name_to_values: dict = {'Default': 0, 'Cinematics': 1, 'OnAircraft': 2, 'FreeFall': 3, 'FreeFallWithWeapon': 4, 'OpenParachute': 5, 'CloseParachute': 6, 'Parachute': 7, 'LandGround': 8, 'Finish': 9}
    value_to_names: dict = {0: 'Default', 1: 'Cinematics', 2: 'OnAircraft', 3: 'FreeFall', 4: 'FreeFallWithWeapon', 5: 'OpenParachute', 6: 'CloseParachute', 7: 'Parachute', 8: 'LandGround', 9: 'Finish'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class WayPoint(object):
    flag: member_descriptor = <member 'flag' of 'WayPoint' objects>
    position: member_descriptor = <member 'position' of 'WayPoint' objects>

    @property
    def is_offmesh_connection(self): ...
class WayPointFlags(enum):
    END: int = 2
    OFFMESH_CONNECTION: int = 4
    START: int = 1
    name_to_values: dict = {'START': 1, 'END': 2, 'OFFMESH_CONNECTION': 4}
    value_to_names: dict = {1: 'START', 2: 'END', 4: 'OFFMESH_CONNECTION'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class deque(object):
    append: method_descriptor = <method 'append' of 'collections.deque' objects>
    appendleft: method_descriptor = <method 'appendleft' of 'collections.deque' objects>
    clear: method_descriptor = <method 'clear' of 'collections.deque' objects>
    copy: method_descriptor = <method 'copy' of 'collections.deque' objects>
    count: method_descriptor = <method 'count' of 'collections.deque' objects>
    extend: method_descriptor = <method 'extend' of 'collections.deque' objects>
    extendleft: method_descriptor = <method 'extendleft' of 'collections.deque' objects>
    index: method_descriptor = <method 'index' of 'collections.deque' objects>
    insert: method_descriptor = <method 'insert' of 'collections.deque' objects>
    maxlen: getset_descriptor = <attribute 'maxlen' of 'collections.deque' objects>
    pop: method_descriptor = <method 'pop' of 'collections.deque' objects>
    popleft: method_descriptor = <method 'popleft' of 'collections.deque' objects>
    remove: method_descriptor = <method 'remove' of 'collections.deque' objects>
    reverse: method_descriptor = <method 'reverse' of 'collections.deque' objects>
    rotate: method_descriptor = <method 'rotate' of 'collections.deque' objects>


