# module: gclient.gameplay.logic_placement.ui.main_uistage

class BaseMainStage(UIStage):
    def CacheNodeUseFrequently(self): ...
    def ChangeHudPickUpComp(self): ...
    def CheckBeScoutTipsUI(self): ...
    def Destroy(self): ...
    def EndLoading(self): ...
    def GetCacheCloneNode(self, filename): ...
    def GetCacheNodePath(self): ...
    def GetFunctionCls(self): ...
    def GetHelicopterHudCls(self): ...
    def GetInteractiveCls(self): ...
    def GetOutStandingWindowClass(self): ...
    def GetTimeLinePath(self): ...
    def GetVehicleHudCls(self): ...
    def OnAddBombPathEffect(self): ...
    def OnBeScoutTipsChange(self, owner_id, be_scouted): ...
    def OnDelBombPathEffect(self): ...
    def OnDestroy(self): ...
    def OnEnter(self, pre_uitype, previous): ...
    def OnExit(self, next_uitype, next_stage): ...
    def OnParaStageChangeForHud(self, para_stage=None): ...
    def OnParachuteBtnState(self, state): ...
    def OnPlayerDroneConnectLoadingStart(self, connecting_or_disconnecting): ...
    def OnPlayerDroneStateChanged(self, created_or_destroyed): ...
    def OnPlayerEnterDroneControlling(self, connected_or_disconnected): ...
    def OnPlayerHighJump(self, is_high_jump): ...
    def OnShowKillRecord(self, info): ...
    def OnSwitchScene(self, from_scene, to_scene): ...
    def PlayerVehicleChanged(self): ...
    def RefreshIgPcWindow(self): ...
    def ReleaseNodeUseFrequently(self): ...
    def StartLoading(self): ...
    def _GetAllCacheNodePath(self): ...
    def _GetAllTimeLinePath(self): ...
    def _GetParachuteButtonComp(self): ...
    def _on_timer(self, timerid): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...
    @property
    def main_ui_style(self): ...
class GameNoticeComp(UIWindow):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def AnimShowInCallback(self, duration): ...
    def AnimShowOutCallback(self): ...
    def CheckDLcExist(): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseCommonTips(self): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def Destroy(): ...
    def DoCommonPrompt(self, message, duration): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetRecoveryFunc(): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnCommonPrompt(self, proto_id, extra_data=None): ...
    def OnDestroy(self): ...
    def OnFocus(self, value): ...
    def OnKeyDownEsc(self): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def RefreshPcKey(self): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowCommonTipsPanel(self, value): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def StayCallback(self): ...
    def StopAnim(self): ...
    def _CancelCommonPromptStayTimer(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _SetHallLevel(self, visible): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _TryCommonPrompt(self): ...
    def _cancelLongTouch(self): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class HudTopRightPlacement(HudTopRightComp):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = (3, 16, 11, 15)
    GAME_LOGIC_FAR_DIS_RATIO: float = 1.0
    HALL_LEVEL: NoneType = None
    MAX_SOUND_COUNT: int = 4
    PANEL_LISTENER_NODE: type = <class 'gclient.gameplay.uicomponents.ig_cc_node.ListenerPanel'>
    PANEL_MIKE_NODE: type = <class 'gclient.gameplay.uicomponents.ig_cc_node.MikePanel'>
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddGameSound(self, sound_type, owner, pos, extra=None): ...
    def AddGamepadKeyPanel(self, func_id, panel, with_txt=False, force_long=False): ...
    def AddHiddenReason(self, reason): ...
    def AddPcKeyNode(self, func_id, panel, have_text=False): ...
    def AddStoryTick(self, func, frames=0): ...
    def CacheSomeBtnOpacity(self): ...
    def CancelSafeTip(self): ...
    def CancelSrMainTimer(self): ...
    def ChangePanelPcKeyFuncId(self, old_func_id, new_func_id, target_panel=None): ...
    def CheckAndStartSrMainTimer(self): ...
    def CheckDLcExist(): ...
    def CheckDroneConnecting(self): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def CheckReservationReddot(self): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def ClearWhenClose(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def DeactiveMap(self): ...
    def DelPcKeyNode(self, func_id): ...
    def DelPcKeyNodeByPanel(self, panel): ...
    def Destroy(): ...
    def EnableChatBtnTouch(self, enable): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FetchSoundNodeByOwnerId(self, owner_id): ...
    def FetchSoundNodeDisappear(self, now): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetBipMapUICls(self): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetPanelMapOpacityPercent(self): ...
    def GetRecoveryFunc(): ...
    def GetSceneIds(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HandleButtonA(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HandleButtonB(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HandleRightJoystick(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HandleSelectBtn(self, offset_x=0.0, offset_y=0.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideAllSel(self): ...
    def HideAllSoundNode(self): ...
    def HideBeforeReshow(self): ...
    def HideForReasonEvent(self, reason, is_hide): ...
    def HideListChat(self): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitGamepad(self): ...
    def InitListviewChatRecord(self): ...
    def InitMapBase(self): ...
    def InitNode(self): ...
    def InitOpacityWidgets(self, widgets_list, widget_info_list, widget_pc_list=[]): ...
    def InitPanelQuickBuy(self): ...
    def InitSafeRegion(self): ...
    def InitSoundNode(self): ...
    def InitSrMiniMapScale(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def IsUIVersion_1(self): ...
    def ListviewChatCallback(self, irange): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def ON_GM_SHOW_SUPPLY(self, info): ...
    def OnAvatarModelDestroy(self, avatar_id): ...
    def OnBorderTickTagEntityEnterAOI(self, tag_type, guid): ...
    def OnBorderTickTagEntityLeaveAOI(self, tag_type, guid): ...
    def OnChatBtnClick(self, btn): ...
    def OnChatBtnClickExtra(self, btn): ...
    def OnChatInfo(self, channel, msg=None): ...
    def OnClickEmoteBtn(self, btn): ...
    def OnCloseChatPanel(self): ...
    def OnCreateCommonMark(self, mark_id, mark_info): ...
    def OnDestroy(self): ...
    def OnDestroyCommonMark(self, mark_id): ...
    def OnEmoteWheelVisible(self, value): ...
    def OnEnterChat(self, enter): ...
    def OnFocus(self, value): ...
    def OnGameSound(self, sound_type, owner=None, pos=None, extra=None): ...
    def OnGameStateChanged(self, state): ...
    def OnGamepadChange(self, has_gamepad): ...
    def OnGamepadChangePcKeyNodes(self, has_gamepad): ...
    def OnGamepadChangeQuickBuy(self, has_gamepad): ...
    def OnGamepadInChange(self, gamepad): ...
    def OnGamepadKeySettingChange(self): ...
    def OnHideCommonMark(self, mark_id, hidden_reason): ...
    def OnHideEnemyMark(self): ...
    def OnHideEnemyMarkByAvatarId(self, avatar_id): ...
    def OnInfoChaos(self, info_chaos): ...
    def OnInitPanelQuickBuy(self): ...
    def OnInitSafeRegion(self): ...
    def OnInsideGameGigMapPositionChange(self, pos): ...
    def OnInsideGameGigMapScaleChange(self, scale): ...
    def OnKeyDownEsc(self): ...
    def OnLongMenuDown(self, show): ...
    def OnMapMissionMarkScaleDown(self, mark_id): ...
    def OnMapMissionMarkScaleUp(self, mark_id): ...
    def OnMapSkillRangeShow(self, spell_id, is_show): ...
    def OnMarkChange(self, pos, slot, mark_type, guid, extra_info=None, member_id=''): ...
    def OnMemberAskHelpTime(self, avatar_id): ...
    def OnMiniMapRotateModeChanged(self, mode): ...
    def OnOccupyItemEnemyCome(self, occupy_id): ...
    def OnOccupyItemEnemyLeave(self, occupy_id): ...
    def OnOpenBigMap(self, _=None): ...
    def OnOpenSettings(self, _): ...
    def OnParachuteStateChange(self, parachute_stage): ...
    def OnPcMinimapClick(self): ...
    def OnPlayerDroneConnectStateChanged(self, connected_or_disconnected): ...
    def OnPlayerDroneStateChanged(self, created_or_destroyed): ...
    def OnPlayerParaStageChanged(self, para_stage): ...
    def OnQuickBuyRequest(self): ...
    def OnQuickBuyTeammate(self): ...
    def OnQuickbuyUIShow(self, is_show): ...
    def OnRecommendBuySupport(self): ...
    def OnRecvReserveChanged(self, key, new): ...
    def OnRefreshRobotInfo(self, robot_info): ...
    def OnReplayFinish(self): ...
    def OnReplayStart(self, avatar): ...
    def OnReportBug(self, btn): ...
    def OnSafeRegionForeseeChange(self, info): ...
    def OnSafeRegionIndexChange(self, old_index, sr_index): ...
    def OnSafeRegionShrink(self): ...
    def OnSafeRegionShrinkTime(self, sr_shrink_time): ...
    def OnSafeRegionStable(self): ...
    def OnSafeRegionStateChange(self, sr_state): ...
    def OnSelectHeroIdChange(self, hero_id): ...
    def OnSetMiniMapScale(self, scale): ...
    def OnSettingMiniMapScale(self, new): ...
    def OnShowCommonMark(self, mark_id, hidden_reason): ...
    def OnShowEnemyMark(self, avatar_infos, extra=None): ...
    def OnShowShutterEnergyMapGuide(self): ...
    def OnShutterEnergyTeamPosChanged(self, *args, **kwargs): ...
    def OnTeamMemberSpeakingListChange(self): ...
    def OnTeammateAskSupport(self, teammate_id, item_id): ...
    def OnTeammateBuySupport(self, player_id, item_list): ...
    def OnTeammateChanged(self): ...
    def OnUIOpacityChange(self, reason, is_hide): ...
    def OnUavHideFull(self): ...
    def OnUavShow(self, caster_info, avatar_infos, level, spell_id, fix_pos, uav_range): ...
    def OnUavShowFull(self, caster_info, avatar_infos, level, spell_id, fix_pos, refresh_ui): ...
    def OnUpdateCoinCount(self, old=None, _=None): ...
    def OnUpdateSafe(self): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def OpenMikeOrListenerPanel(self, panel): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def RefreshBtnChatVisible(self): ...
    def RefreshCCChannels(self): ...
    def RefreshGamepadWhenShow(self): ...
    def RefreshPcKey(self): ...
    def RefreshPcKeyNodes(self): ...
    def RefreshPcNode(self): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetHudVisibleOnPlayerDroneControlling(self, visible): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetUserDefineWidgetPos(self, from_init=False): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowChatComp(self): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def SrMainTimer(self, dt): ...
    def StartBtnChatCD(self): ...
    def StartSrMainTimer(self): ...
    def StopAnim(self): ...
    def _AddOpacityHideReason(self, reason): ...
    def _AddSoundNode(self, gnode, itype, opacity, dist, color=None): ...
    def _CancelListChatTimer(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _GetCSBPath(self): ...
    def _GetOpacityInfoWidgets(self): ...
    def _GetPanelQuickBuyCls(self): ...
    def _HaveOpacityHideReason(self, reason): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _RemoveOpacityHideReason(self, reason): ...
    def _SetHallLevel(self, visible): ...
    def _SetOpacityForCacheWidgets(self, is_hide, opacity_factor, is_info=False, need_fade=False): ...
    def _SetOpacityForCacheWidgetsPC(self, is_hide, opacity_factor): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _ShowSoundNode(self, owner_id, sound_type, opacity, angle, dist): ...
    def _ValidSound(self, owner, sound_type): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _cancelLongTouch(self): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _postComponents(self, bdict): ...
    def _show_node_hover(self, node, visible): ...
    def _tickComponents(self, dtime): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class PlacementMainStage(BaseMainStage):
    def CacheNodeUseFrequently(self): ...
    def ChangeHudPickUpComp(self): ...
    def CheckBeScoutTipsUI(self): ...
    def Destroy(self): ...
    def EndLoading(self): ...
    def GetCacheCloneNode(self, filename): ...
    def GetCacheNodePath(self): ...
    def GetFunctionCls(self): ...
    def GetHelicopterHudCls(self): ...
    def GetInteractiveCls(self): ...
    def GetOutStandingWindowClass(self): ...
    def GetTimeLinePath(self): ...
    def GetVehicleHudCls(self): ...
    def OnAddBombPathEffect(self): ...
    def OnBeScoutTipsChange(self, owner_id, be_scouted): ...
    def OnDelBombPathEffect(self): ...
    def OnDestroy(self): ...
    def OnEnter(self, pre_uitype, previous): ...
    def OnExit(self, next_uitype, next_stage): ...
    def OnParaStageChangeForHud(self, para_stage=None): ...
    def OnParachuteBtnState(self, state): ...
    def OnPlayerDroneConnectLoadingStart(self, connecting_or_disconnecting): ...
    def OnPlayerDroneStateChanged(self, created_or_destroyed): ...
    def OnPlayerEnterDroneControlling(self, connected_or_disconnected): ...
    def OnPlayerHighJump(self, is_high_jump): ...
    def OnShowKillRecord(self, info): ...
    def OnSwitchScene(self, from_scene, to_scene): ...
    def PlayerVehicleChanged(self): ...
    def RefreshIgPcWindow(self): ...
    def ReleaseNodeUseFrequently(self): ...
    def StartLoading(self): ...
    def _GetAllCacheNodePath(self): ...
    def _GetAllTimeLinePath(self): ...
    def _GetParachuteButtonComp(self): ...
    def _on_timer(self, timerid): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...
    @property
    def main_ui_style(self): ...

