# module: gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_log

import events

class GameState(enum):
    FINISHED: int = 2
    GAMING: int = 1
    WAITING: int = 0
    name_to_values: dict = {'WAITING': 0, 'GAMING': 1, 'FINISHED': 2}
    value_to_names: dict = {0: 'WAITING', 1: 'GAMING', 2: 'FINISHED'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class PlayerCombatAvatarMember(object):
    def RecordGunFireAmmo(self, equip_id, ammo=1, hit_part=None): ...
    def RecordGunFireDamage(self, equip_id, damage, part_slots=None): ...
    def RecordGunLogToServer(self): ...


