# module: gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_snare

class CombatAvatarMember(object):
    def AddSnareToSnareDict(self, proto_id, guid): ...
    def RemoveSnareFromSnareDict(self, proto_id, guid): ...

class HumanoidMonsterSnare(CombatAvatarMember):
    def AddSnareToSnareDict(self, proto_id, guid): ...
    def RemoveSnareFromSnareDict(self, proto_id, guid): ...

class PlayerCombatAvatarMember(CombatAvatarMember):
    def AddSnareToSnareDict(self, proto_id, guid): ...
    def RemoveSnareFromSnareDict(self, proto_id, guid): ...


