# module: gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_auto_fire

import autofire_data
import cconst
import config
import events
import formula
import functools
import math
import time
import weapon_util

class AimEnemyResult(enum):
    HitAndInDistance: int = 1
    HitAndNotInDistance: int = 2
    NotHit: int = 3
    name_to_values: dict = {'HitAndInDistance': 1, 'HitAndNotInDistance': 2, 'NotHit': 3}
    value_to_names: dict = {1: 'HitAndInDistance', 2: 'HitAndNotInDistance', 3: 'NotHit'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class CombatAvatarMember(object):
class DualMeleeCase(WeaponCaseBase):
    EnableLazyLoadModel: bool = False
    IsCommonSkillCase: bool = False
    IsDualMelee: bool = True
    IsMelee: bool = True
    IsWeapon: bool = False
    ammunition_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f810>
    equip_proto: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520ca10>
    guise_template_data: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f610>
    is_dual_weapon: bool = False
    is_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e310>
    is_melee: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f590>
    is_own_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520eb90>
    show_guise_bullet_trace: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231a50>
    show_guise_hit_effect: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231b10>
    skin_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f5d0>
    spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e250>
    vice_spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520d250>

    def ActiveBindBomb(self, extra=None): ...
    def AddHiddenReason(self, reason): ...
    def AddWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def AttachLeftHandWeaponToHandBack(self): ...
    def AttachLeftHandWeaponToLeftHand(self): ...
    def AttachWeaponToAvatarBack(self): ...
    def AttachWeaponToAvatarHand(self): ...
    def AttachWeaponToHandAnimWeapon(self): ...
    def AttachWeaponToHandBack(self): ...
    def AttachWeaponToHandEquip(self): ...
    def AttachWeaponToLeftHand(self): ...
    def AttachWeaponToRightHand(self): ...
    def BanSamuraiSmoothSwitchOnce(self): ...
    def ChangeWeaponGuise(self, guise_id): ...
    def ChangeWeaponSkin(self, skin_id): ...
    def CheckIfQuickRaise(self, old_weapon_guid): ...
    def CheckShowGunDlcExistsShaderEffect(self): ...
    def ClearGuiseItemCache(self): ...
    def ClearTrailEffectList(self, effect_list, fadeout=0, is_lefthand=False): ...
    def DeActiveBindBomb(self): ...
    def Destroy(self): ...
    def DisablePrincipleRole(self): ...
    def DropLeftHandWeapon(self): ...
    def DropRightHandWeapon(self): ...
    def DropWeapon(self): ...
    def DropWeaponForAvatar(self): ...
    def ExecAllModelFunc(self, func_name, *args): ...
    def ForceAttachWeaponToHandAnimWeapon(self): ...
    def ForceAttachWeaponToLeftHand(self): ...
    def ForceAttachWeaponToRightHand(self): ...
    def ForceDropCurWeapon(self): ...
    def ForceDropWeaponForAvatar(self): ...
    def GetDefaultMeleeEquipId(self): ...
    def GetFallDirSpeed(self): ...
    def GetGunSkinPartModelList(self, default_value=None): ...
    def GetGunType(self): ...
    def GetMeleeAttackEffectId(self, hit_pose_id): ...
    def GetMeleeCaseDlcId(self): ...
    def GetMeleeCaseDlcids(self): ...
    def GetMeleeWeaponModelId(self): ...
    def GetWeaponAttrValue(self, name, default=None): ...
    def GetWorldBound(self): ...
    def GetWorldBoundCentre(self): ...
    def InitWeapon(self, part_slots=None, part_loaded_callback=None, all_loaded_callback=None, need_refresh_prop=True, is_reload=False, extra=None): ...
    def IsAllPartsModelLoaded(self): ...
    def IsOwnerValid(self): ...
    def IsSamuraiWithSamuraiSword(self): ...
    def LoadSubModel(self): ...
    def MarkPrincipleRole(self): ...
    def ModelAnimArmWeapon(self, model): ...
    def OnCastSpell(self): ...
    def OnCastSpellStart(self): ...
    def OnCastSpellStop(self): ...
    def OnSpellImmune(self): ...
    def OnWeaponModelLoad(self): ...
    def PlayTrailEffectList(self, effect_list, is_lefthand=False): ...
    def RaiseLeftHandWeapon(self): ...
    def RaiseRightHandWeapon(self): ...
    def RaiseWeapon(self): ...
    def RaiseWeaponForAvatar(self): ...
    def RefreshFpsPlacerProp(self): ...
    def RefreshGuise3PEffectInCombat(self): ...
    def RefreshGuiseEffect(self): ...
    def RefreshGuiseOverlayIdlePose(self): ...
    def RefreshGuiseSkinAnimPose(self, model, graph_id): ...
    def RefreshGuiseSkinAnimPoseForHand(self): ...
    def RefreshGuiseSkinAnimPoseForWeapon(self): ...
    def RefreshHasGuiseDlcId(self): ...
    def RefreshTpsEffectEntityVisible(self): ...
    def RefreshWeaponAttrFromCombatAttr(self, attr_name): ...
    def RefreshWeaponDecorate(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetIsAds(self, is_ads): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsInShowRoom(self, in_showroom): ...
    def SetIsLoadForWarmingUp(self, is_warmingup): ...
    def SetIsMeleeFirstRaise(self, value): ...
    def SetIsRealAds(self, is_real_ads): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetNoNearPlaneClip(self, enable): ...
    def ShowModel(self): ...
    def UseAllPartWarmingUp(self, is_warmingup): ...
    def _GetGuiseModelId(self, origin_model_id): ...
    @property
    def body_equip_proto(self): ...    @property
    def is_cur_taking(self): ...    @property
    def is_destroyed(self): ...    @property
    def is_match_server(self): ...    @property
    def weapon_model(self): ...
class FSMAutoFire(object):
    NAME: str = 'AFFire'

    def CountDownCallback(self): ...
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...
    def OnAFAimInEnter(self): ...
    def OnAFAimInExit(self): ...
    def OnAFAimInTick(self): ...
    def OnAFAimOutEnter(self): ...
    def OnAFAimOutExit(self): ...
    def OnAFAimOutTick(self): ...
    def OnAFEmptyEnter(self): ...
    def OnAFEmptyExit(self): ...
    def OnAFEmptyTick(self): ...
    def OnAFFireEnter(self): ...
    def OnAFFireTick(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...

class FiniteStateMachine(object):
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...

class GunMeleeCase(WeaponCase):
    EnableLazyLoadModel: bool = True
    IsCommonSkillCase: bool = False
    IsDualMelee: bool = False
    IsMelee: bool = False
    IsWeapon: bool = True
    ammunition_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd1fe7750>
    equip_proto: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520ca10>
    guise_template_data: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f610>
    is_dual_weapon: bool = False
    is_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e310>
    is_melee: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f590>
    is_own_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520eb90>
    show_guise_bullet_trace: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231a50>
    show_guise_hit_effect: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231b10>
    skin_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f5d0>
    spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e250>
    vice_spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520d250>

    def ActiveBindBomb(self, extra=None): ...
    def AddHiddenReason(self, reason): ...
    def AddInspectExtraModel(self): ...
    def AddWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def AddWeaponPart(self, part_id, part_loaded_callback=None, refresh_model=False): ...
    def AttachBackupChargerToWeapon(self, is_dual=False): ...
    def AttachLeftHandWeaponToHandBack(self): ...
    def AttachLeftHandWeaponToLeftHand(self): ...
    def AttachWeaponChargerToLeftHandNew(self): ...
    def AttachWeaponChargerToLeftHandOld(self, is_dual=False): ...
    def AttachWeaponToAvatarBack(self): ...
    def AttachWeaponToAvatarHand(self): ...
    def AttachWeaponToHandAnimWeapon(self): ...
    def AttachWeaponToHandBack(self): ...
    def AttachWeaponToHandEquip(self): ...
    def AttachWeaponToLeftHand(self): ...
    def AttachWeaponToRightHand(self): ...
    def BanSamuraiSmoothSwitchOnce(self): ...
    def BatchAddDecals(self, data, realtime=False): ...
    def BuildDecalBakeCameraInfo(self, slot, decal_path, rotation, offset, scale, viewMatrix): ...
    def BuildDecalBakeModelInfo(self, part_types, slot, realtime): ...
    def ChangeWeaponDecorate(self, skin_id, guise_id, hangings_id, sticker_info): ...
    def ChangeWeaponGuise(self, guise_id, data_changed=True, need_callback=True): ...
    def ChangeWeaponHangings(self, hangings_id, data_changed=True): ...
    def ChangeWeaponPartGuise(self, part_guise_info, data_changed=True, change_part=True, part_loaded_callback=None): ...
    def ChangeWeaponSkin(self, skin_id, data_changed=True, force_refresh=False): ...
    def ChangeWeaponSticker(self, sticker_info, realtime=False, data_changed=True): ...
    def CheckCreateMaterialFeature(self): ...
    def CheckIfQuickRaise(self, old_weapon_guid): ...
    def CheckInspectExtraModel(self): ...
    def CheckKillCounterPrim(self): ...
    def CheckSamePartGuiseInfo(self, info): ...
    def CheckSamePartSlots(self, part_slots_old, part_slots_new): ...
    def CheckSameStickerInfo(self, info): ...
    def CheckShowGunDlcExistsShaderEffect(self): ...
    def CheckSimulateHallFire(self): ...
    def CheckSupportedKillCounter(self): ...
    def CheckSupportedKillCounterInHall(self, item_id, check_satisfy_upgrade=False): ...
    def ClearDecal(self): ...
    def ClearGuiseItemCache(self): ...
    def ClearModAttrByName(self, name): ...
    def ClearParam(self): ...
    def ClearTrailEffectList(self, effect_list, fadeout=0, is_lefthand=False): ...
    def ClearWeaponPartTypeMod(self, part_type): ...
    def ClearWeaponPartTypeModAttr(self, part_type): ...
    def CombineDecalBakeModelInfo(self): ...
    def CopyDecalModelData(self, decalModel): ...
    def CreateKillCounterTexture(self, kill_number=0): ...
    def DeActiveBindBomb(self): ...
    def DebugChangeSkinWithRepositoryName(self, repository_name, change_optic=False): ...
    def DebugRecoverSkin(self): ...
    def DecalBakingEnter(self, data, realtime): ...
    def DecalBakingExit(self): ...
    def DecalChangeState(self, state, *args, **kwargs): ...
    def DecalEmptyEnter(self): ...
    def DecalEmptyExit(self): ...
    def DecalLoadingEnter(self, data, realtime=False): ...
    def DecalLoadingExit(self): ...
    def DecreaseFireHeat(self, dtime): ...
    def DecreaseHeatTick(self, dtime): ...
    def DecreaseScatterTick(self, dtime): ...
    def DelayUpdateCustomComposition(self): ...
    def DesideShowSimplePartModel(self): ...
    def Destroy(self): ...
    def DestroyDualWeapon(self): ...
    def DestroyModel(self): ...
    def DisablePrincipleRole(self): ...
    def DoBatchAddDecals(self, data, realtime=False): ...
    def DoRefreshOpticMaterial(self, is_ads, token): ...
    def DropLeftHandWeapon(self): ...
    def DropRightHandWeapon(self): ...
    def DropWeapon(self): ...
    def DropWeaponForAvatar(self): ...
    def ExecAllModelFunc(self, func_name, *args): ...
    def ExecPartModelFunc(self, part_types, func_name, *args): ...
    def FinishKillCounterTexture(self, guid): ...
    def ForceAttachWeaponToHandAnimWeapon(self): ...
    def ForceAttachWeaponToLeftHand(self): ...
    def ForceAttachWeaponToRightHand(self): ...
    def ForceDropCurWeapon(self): ...
    def ForceDropWeaponForAvatar(self): ...
    def GetAttrDiffPercent(self, name, default=None): ...
    def GetAttrValue(self, name, default=None): ...
    def GetDefaultMeleeEquipId(self): ...
    def GetFallDirSpeed(self): ...
    def GetGunMuzzleTrans(self): ...
    def GetGunSkinPartModelList(self, default_value=None): ...
    def GetGunType(self): ...
    def GetMaxDamageHitPart(self, hit_parts): ...
    def GetMeleeAttackEffectId(self, hit_pose_id): ...
    def GetMeleeCaseDlcId(self): ...
    def GetMeleeCaseDlcids(self): ...
    def GetMeleeWeaponModelId(self): ...
    def GetOpticCrosshairPrim(self): ...
    def GetRealAimPointScatterDistOffset(self, shoot_idx): ...
    def GetRealAimPointScatterRecoverSpeed(self, shoot_idx): ...
    def GetRealPenerateDamageDropoffData(self): ...
    def GetRealPersistRecoilDownTimeMax(self, shoot_idx): ...
    def GetRealRecoilData(self, is_real_ads, shoot_idx): ...
    def GetRealRecoilRandomData(self, is_real_ads, shoot_idx): ...
    def GetRealRollShakeInfo(self, is_real_ads, shoot_idx): ...
    def GetRealShootScatterRadian(self, shoot_idx): ...
    def GetRealShootScatterRadianByDecrease(self, shoot_idx): ...
    def GetRealShootScatterRadianForAds(self, shoot_idx): ...
    def GetScatterRadianByHeat(self): ...
    def GetTrailLightBarEffectId(self, simple_version, caster_id_ads, is_fps_avatar): ...
    def GetV6GemAnimPrim(self): ...
    def GetWeaponAttrValue(self, name, default=None): ...
    def GetWeaponAttrValueImmediately(self, name, default=None): ...
    def GetWeaponFeature(self, func_name): ...
    def GetWeaponModAttr(self, name): ...
    def GetWeaponPart(self, part_type): ...
    def GetWeaponPartModel(self, part_type): ...
    def GetWeaponPartModels(self, part_types): ...
    def GetWeaponPartPrims(self, part_types): ...
    def GetWorldBound(self): ...
    def GetWorldBoundCentre(self): ...
    def HideBackupCharger(self): ...
    def HideOpticReflectEffect(self, dtime): ...
    def IncreaseFireHeat(self): ...
    def InitFpsProperty(self): ...
    def InitHandGraphValue(self): ...
    def InitOpticShaderValue(self): ...
    def InitWeapon(self, part_slots=None, part_loaded_callback=None, all_loaded_callback=None, need_refresh_prop=True, is_reload=False, extra=None): ...
    def IsAllPartsModelLoaded(self): ...
    def IsOwnerValid(self): ...
    def IsSamuraiWithSamuraiSword(self): ...
    def JumpToAds(self, is_ads): ...
    def LoadWeaponModAttrOrgValue(self): ...
    def MarkPrincipleRole(self): ...
    def ModelAnimArmWeapon(self, model): ...
    def OnAddWeaponPart(self, part_type, part_id): ...
    def OnBakeSingleDecalCallback(self, holding_models, idx, task_id, result): ...
    def OnBatchBakeDecalCallback(self, ticket, taskid, result): ...
    def OnCastSpell(self): ...
    def OnCastSpellStart(self): ...
    def OnCastSpellStop(self): ...
    def OnRefreshWeaponMaterial(self): ...
    def OnSpellImmune(self): ...
    def OnWeaponModelLoad(self): ...
    def PlayTrailEffectList(self, effect_list, is_lefthand=False): ...
    def ProcessSeparateMeshDecal(self): ...
    def RaiseLeftHandWeapon(self): ...
    def RaiseRightHandWeapon(self): ...
    def RaiseWeapon(self): ...
    def RaiseWeaponForAvatar(self): ...
    def RefreshAmmoAmmunition(self): ...
    def RefreshAmmoAmmunitionEffect(self, ammo, max_ammo): ...
    def RefreshAmmoModelValue(self): ...
    def RefreshAmmoShaderEffect(self, ammo, max_ammo): ...
    def RefreshAmmoShaderEffectForRecevier(self, ammo, max_ammo): ...
    def RefreshAmmoShaderValue(self): ...
    def RefreshBackupChargerModel(self): ...
    def RefreshEffectCameraAttaching(self): ...
    def RefreshFireSfxId(self, guise_template_data, guise_item_id): ...
    def RefreshFireSfxIdForGunPart(self): ...
    def RefreshFpsPlacerProp(self, is_init=False): ...
    def RefreshGuise3PEffectInCombat(self): ...
    def RefreshGuiseEffect(self): ...
    def RefreshGuiseOverlayIdlePose(self): ...
    def RefreshGuiseSkinAnimPose(self, model, graph_id): ...
    def RefreshGuiseSkinAnimPoseForHand(self): ...
    def RefreshGuiseSkinAnimPoseForWeapon(self): ...
    def RefreshGunDlcExists(self): ...
    def RefreshHandGraphValue(self, val_name): ...
    def RefreshHasGuiseDlcId(self): ...
    def RefreshInspectExtraModel(self): ...
    def RefreshKillCounterForChangeGuise(self): ...
    def RefreshOpticEffect(self, is_ads): ...
    def RefreshOpticMaterial(self, is_ads): ...
    def RefreshOpticModelForAds(self, is_ads): ...
    def RefreshOpticPose(self): ...
    def RefreshOpticScopeEnable(self, is_ads): ...
    def RefreshOpticShaderSightStabilize(self): ...
    def RefreshOpticShaderValue(self, val_name): ...
    def RefreshShaderGraphParamterByData(self): ...
    def RefreshTpsEffectEntityVisible(self): ...
    def RefreshWeaponAttrFromCombatAttr(self, attr_name): ...
    def RefreshWeaponBody(self, body): ...
    def RefreshWeaponDecorate(self): ...
    def RefreshWeaponPartModAttr(self): ...
    def RefreshWeaponProp(self): ...
    def RefreshWeaponSticker(self, realtime=False): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveInspectExtraModel(self): ...
    def RemoveOpticStoryTick(self): ...
    def RemoveWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def ResetBackupCharger(self): ...
    def ResetFireHeat(self): ...
    def ResetOpticModelForAds(self, is_ads): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetDefaultShaderGraphMaterialForHall(self): ...
    def SetDualIsEmptyReload(self, is_empty): ...
    def SetIsAds(self, is_ads): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsEmptyReload(self, is_empty): ...
    def SetIsFirstRaise(self, value): ...
    def SetIsInShowRoom(self, in_showroom): ...
    def SetIsLoadForWarmingUp(self, is_warmingup): ...
    def SetIsMeleeFirstRaise(self, value): ...
    def SetIsNeedRechamber(self, is_need): ...
    def SetIsRealAds(self, is_real_ads): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetMpFpsActionForMachineSight(self, action, blendTime): ...
    def SetNoNearPlaneClip(self, enable): ...
    def ShowModel(self): ...
    def ShowOpticReflectEffect(self, dtime): ...
    def SimulatedHallAutoFireTimer(self): ...
    def StartDecreaseHeat(self): ...
    def StartDecreaseScatter(self): ...
    def StopDecreaseHeat(self): ...
    def StopDecreaseScatter(self): ...
    def TryFixOpticEffectBug(self): ...
    def UpdateExtraModelVisible(self, is_visible): ...
    def UpdateModAttr(self, part_type, attr_key, value): ...
    def UpdateModAttrOrgValue(self, name, org_value=None): ...
    def UpdateMutexPart(self): ...
    def UpdatePartSlots(self, part_type, part_id): ...
    def UpdateWeaponFeature(self): ...
    def UpdateWeaponPartModAttr(self, part_id): ...
    def UseAllPartWarmingUp(self, is_warmingup): ...
    def _CheckDecalBakeModelValid(self): ...
    def _ClearShootAttr(self): ...
    def _GetGuiseModelId(self, origin_model_id): ...
    def _GetOpticShaderValue_EnableScope(self, origin_value): ...
    def _GetOpticShaderValue_SightStabilize(self, origin_value): ...
    def _GetShootAttr(self, name, *keys): ...
    def _GetWeaponBodyPartSlots(self): ...
    def _InitDualWeaponBody(self): ...
    def _InitDualWeaponHangings(self): ...
    def _IsGunDlcExists(self): ...
    def _OnCastSpell(self): ...
    def _OnCastSpellStart(self): ...
    def _OnCastSpellStop(self): ...
    def _RealBackingDecalTimer(self): ...
    def _RefreshFeatureCache(self): ...
    def _TryOnBakeBackupChargerModelDecal(self): ...
    def _TryOnBakeDualWeaponDecal(self): ...
    def _UpdateShootAttr(self, name, value, *keys): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def ads_fire_heat(self): ...    @property
    def body_equip_proto(self): ...    @property
    def dual_weapon_model(self): ...    @property
    def hand_graph(self): ...    @property
    def is_cur_taking(self): ...    @property
    def is_decal_baking(self): ...    @property
    def is_destroyed(self): ...    @property
    def is_match_server(self): ...    @property
    def weapon_model(self): ...
class MeleeCase(WeaponCaseBase):
    EnableLazyLoadModel: bool = True
    IsCommonSkillCase: bool = False
    IsDualMelee: bool = False
    IsMelee: bool = True
    IsWeapon: bool = False
    ammunition_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f810>
    equip_proto: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520ca10>
    guise_template_data: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f610>
    is_dual_weapon: bool = False
    is_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e310>
    is_melee: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f590>
    is_own_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520eb90>
    show_guise_bullet_trace: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231a50>
    show_guise_hit_effect: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231b10>
    skin_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f5d0>
    spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e250>
    vice_spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520d250>

    def ActiveBindBomb(self, extra=None): ...
    def AddHiddenReason(self, reason): ...
    def AddWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def AttachWeaponToAvatarBack(self): ...
    def AttachWeaponToAvatarHand(self): ...
    def AttachWeaponToHandAnimWeapon(self): ...
    def AttachWeaponToHandBack(self): ...
    def AttachWeaponToHandEquip(self): ...
    def AttachWeaponToLeftHand(self): ...
    def AttachWeaponToRightHand(self): ...
    def BanSamuraiSmoothSwitchOnce(self): ...
    def ChangeWeaponGuise(self, guise_id): ...
    def ChangeWeaponSkin(self, skin_id): ...
    def CheckIfQuickRaise(self, old_weapon_guid): ...
    def CheckShowGunDlcExistsShaderEffect(self): ...
    def ClearGuiseItemCache(self): ...
    def ClearTrailEffectList(self, effect_list, fadeout=0, is_lefthand=False): ...
    def DeActiveBindBomb(self): ...
    def Destroy(self): ...
    def DisablePrincipleRole(self): ...
    def DropWeapon(self): ...
    def DropWeaponForAvatar(self): ...
    def ExecAllModelFunc(self, func_name, *args): ...
    def ForceAttachWeaponToHandAnimWeapon(self): ...
    def ForceAttachWeaponToLeftHand(self): ...
    def ForceAttachWeaponToRightHand(self): ...
    def ForceDropCurWeapon(self): ...
    def ForceDropWeaponForAvatar(self): ...
    def GetDefaultMeleeEquipId(self): ...
    def GetFallDirSpeed(self): ...
    def GetGunSkinPartModelList(self, default_value=None): ...
    def GetGunType(self): ...
    def GetMeleeAttackEffectId(self, hit_pose_id): ...
    def GetMeleeCaseDlcId(self): ...
    def GetMeleeCaseDlcids(self): ...
    def GetMeleeWeaponModelId(self): ...
    def GetWeaponAttrValue(self, name, default=None): ...
    def GetWorldBound(self): ...
    def GetWorldBoundCentre(self): ...
    def InitWeapon(self, part_slots=None, part_loaded_callback=None, all_loaded_callback=None, need_refresh_prop=True, is_reload=False, extra=None): ...
    def IsAllPartsModelLoaded(self): ...
    def IsOwnerValid(self): ...
    def IsSamuraiWithSamuraiSword(self): ...
    def LoadScabbardModel(self): ...
    def MarkPrincipleRole(self): ...
    def ModelAnimArmWeapon(self, model): ...
    def OnCastSpell(self): ...
    def OnCastSpellStart(self): ...
    def OnCastSpellStop(self): ...
    def OnSpellImmune(self): ...
    def OnWeaponModelLoad(self): ...
    def PlayTrailEffectList(self, effect_list, is_lefthand=False): ...
    def PushSamuraiSwordActionGraph(self): ...
    def RaiseWeapon(self): ...
    def RaiseWeaponForAvatar(self): ...
    def RefreshFpsPlacerProp(self): ...
    def RefreshGuise3PEffectInCombat(self): ...
    def RefreshGuiseEffect(self): ...
    def RefreshGuiseOverlayIdlePose(self): ...
    def RefreshGuiseSkinAnimPose(self, model, graph_id): ...
    def RefreshGuiseSkinAnimPoseForHand(self): ...
    def RefreshGuiseSkinAnimPoseForWeapon(self): ...
    def RefreshHasGuiseDlcId(self): ...
    def RefreshTpsEffectEntityVisible(self): ...
    def RefreshWeaponAttrFromCombatAttr(self, attr_name): ...
    def RefreshWeaponDecorate(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetIsAds(self, is_ads): ...
    def SetIsCastDynamicShadow(self, value): ...
    def SetIsInShowRoom(self, in_showroom): ...
    def SetIsLoadForWarmingUp(self, is_warmingup): ...
    def SetIsMeleeFirstRaise(self, value): ...
    def SetIsRealAds(self, is_real_ads): ...
    def SetIsReceiveDynamicShadow(self, value): ...
    def SetNoNearPlaneClip(self, enable): ...
    def ShowModel(self): ...
    def UseAllPartWarmingUp(self, is_warmingup): ...
    def _GetGuiseModelId(self, origin_model_id): ...
    def _GetGuiseScabbardModelId(self, origin_model_id): ...
    @property
    def body_equip_proto(self): ...    @property
    def is_cur_taking(self): ...    @property
    def is_destroyed(self): ...    @property
    def is_match_server(self): ...    @property
    def weapon_model(self): ...
class PlayerCombatAvatarMember(CombatAvatarMember):
    def CancelAutoFireTimer(self): ...
    def IsCurGunHasBolt(self): ...
    def OnChangeWeaponForAutoFire(self, guid, old=''): ...
    def OnEnterStateAFFire(self): ...
    def OnFireManuallyBegin(self): ...
    def OnFireManuallyEnd(self): ...
    def OnListenReloadWeaponForAutoFire(self, state): ...
    def OnRealAdsForAutoFire(self, enter): ...
    def SaveAutoFireSetting(self, enable): ...
    def SetupAutoFireAimDistance(self): ...
    def StopAutoFire(self): ...

class StateAFAimIn(object):
    NAME: str = 'AFAimIn'

    def CountDownCallback(self): ...
    def OnAFAimInEnter(self): ...
    def OnAFAimInExit(self): ...
    def OnAFAimInTick(self): ...

class StateAFAimOut(object):
    NAME: str = 'AFAimOut'

    def OnAFAimOutEnter(self): ...
    def OnAFAimOutExit(self): ...
    def OnAFAimOutTick(self): ...

class StateAFEmpty(object):
    NAME: str = 'AFEmpty'

    def OnAFEmptyEnter(self): ...
    def OnAFEmptyExit(self): ...
    def OnAFEmptyTick(self): ...

class StateAFFire(object):
    NAME: str = 'AFFire'

    def OnAFFireEnter(self): ...
    def OnAFFireTick(self): ...

class StateRelationship(enum):
    BeExecuted: int = 50
    ChargeJump: int = 63
    ChargeJumpAir: int = 66
    Climb: int = 10
    ClimbLadder: int = 32
    CommonTpsSkill: int = 67
    Cross: int = 23
    Crouch: int = 6
    DriveVehicle: int = 33
    DropWeapon: int = 21
    DualFire: int = 57
    DualGun: int = 52
    DualReload: int = 54
    DualReloadEnd: int = 56
    DualReloading: int = 55
    Emote: int = 51
    EnterAds: int = 19
    EnterProne: int = 27
    Execution: int = 49
    ExitProne: int = 28
    Fire: int = 12
    GunInspection: int = 44
    GunRefit: int = 30
    HighFall: int = 45
    Idle: int = 1
    Inspirator: int = 46
    Item: int = 16
    Jog: int = 3
    Jump: int = 8
    KickUp: int = 65
    KnockDown: int = 11
    LeanOutVehicle: int = 34
    LeftShield: int = 64
    LeftXDroid: int = 62
    Medicine: int = 60
    Melee: int = 29
    MeleeAttack: int = 39
    MovingShield: int = 31
    OnVehicle: int = 7
    PickUp: int = 18
    PortableEquipment: int = 53
    Prone: int = 26
    RaiseLeftHandWeapon: int = 25
    RaiseWeapon: int = 20
    Rechamber: int = 22
    Reload: int = 13
    ReloadEnd: int = 43
    Reloading: int = 42
    RescueOther: int = 35
    SamuraiBlock: int = 58
    SamuraiSprint: int = 59
    ScanCore: int = 36
    Skill: int = 24
    SkillCantAir: int = 48
    SkillCantProne: int = 41
    SkillWeaponDrop: int = 38
    SkillWeaponRaise: int = 37
    Slide: int = 9
    Sprint: int = 4
    Strop: int = 17
    SuperSprint: int = 5
    Swim: int = 47
    ThrowableWeaponLeft: int = 15
    ThrowableWeaponRight: int = 14
    TripleShot: int = 61
    Walk: int = 2
    Xdroid: int = 40
    name_to_values: dict = {'Idle': 1, 'Walk': 2, 'Jog': 3, 'Sprint': 4, 'SuperSprint': 5, 'Crouch': 6, 'OnVehicle': 7, 'Jump': 8, 'Slide': 9, 'Climb': 10, 'KnockDown': 11, 'Fire': 12, 'Reload': 13, 'ThrowableWeaponRight': 14, 'ThrowableWeaponLeft': 15, 'Item': 16, 'Strop': 17, 'PickUp': 18, 'EnterAds': 19, 'RaiseWeapon': 20, 'DropWeapon': 21, 'Rechamber': 22, 'Cross': 23, 'Skill': 24, 'RaiseLeftHandWeapon': 25, 'Prone': 26, 'EnterProne': 27, 'ExitProne': 28, 'Melee': 29, 'GunRefit': 30, 'MovingShield': 31, 'ClimbLadder': 32, 'DriveVehicle': 33, 'LeanOutVehicle': 34, 'RescueOther': 35, 'ScanCore': 36, 'SkillWeaponRaise': 37, 'SkillWeaponDrop': 38, 'MeleeAttack': 39, 'Xdroid': 40, 'SkillCantProne': 41, 'Reloading': 42, 'ReloadEnd': 43, 'GunInspection': 44, 'HighFall': 45, 'Inspirator': 46, 'Swim': 47, 'SkillCantAir': 48, 'Execution': 49, 'BeExecuted': 50, 'Emote': 51, 'DualGun': 52, 'PortableEquipment': 53, 'DualReload': 54, 'DualReloading': 55, 'DualReloadEnd': 56, 'DualFire': 57, 'SamuraiBlock': 58, 'SamuraiSprint': 59, 'Medicine': 60, 'TripleShot': 61, 'LeftXDroid': 62, 'ChargeJump': 63, 'LeftShield': 64, 'KickUp': 65, 'ChargeJumpAir': 66, 'CommonTpsSkill': 67}
    value_to_names: dict = {1: 'Idle', 2: 'Walk', 3: 'Jog', 4: 'Sprint', 5: 'SuperSprint', 6: 'Crouch', 7: 'OnVehicle', 8: 'Jump', 9: 'Slide', 10: 'Climb', 11: 'KnockDown', 12: 'Fire', 13: 'Reload', 14: 'ThrowableWeaponRight', 15: 'ThrowableWeaponLeft', 16: 'Item', 17: 'Strop', 18: 'PickUp', 19: 'EnterAds', 20: 'RaiseWeapon', 21: 'DropWeapon', 22: 'Rechamber', 23: 'Cross', 24: 'Skill', 25: 'RaiseLeftHandWeapon', 26: 'Prone', 27: 'EnterProne', 28: 'ExitProne', 29: 'Melee', 30: 'GunRefit', 31: 'MovingShield', 32: 'ClimbLadder', 33: 'DriveVehicle', 34: 'LeanOutVehicle', 35: 'RescueOther', 36: 'ScanCore', 37: 'SkillWeaponRaise', 38: 'SkillWeaponDrop', 39: 'MeleeAttack', 40: 'Xdroid', 41: 'SkillCantProne', 42: 'Reloading', 43: 'ReloadEnd', 44: 'GunInspection', 45: 'HighFall', 46: 'Inspirator', 47: 'Swim', 48: 'SkillCantAir', 49: 'Execution', 50: 'BeExecuted', 51: 'Emote', 52: 'DualGun', 53: 'PortableEquipment', 54: 'DualReload', 55: 'DualReloading', 56: 'DualReloadEnd', 57: 'DualFire', 58: 'SamuraiBlock', 59: 'SamuraiSprint', 60: 'Medicine', 61: 'TripleShot', 62: 'LeftXDroid', 63: 'ChargeJump', 64: 'LeftShield', 65: 'KickUp', 66: 'ChargeJumpAir', 67: 'CommonTpsSkill'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class WeaponCase(WeaponCaseBase):
    EnableLazyLoadModel: bool = True
    IsCommonSkillCase: bool = False
    IsDualMelee: bool = False
    IsMelee: bool = False
    IsWeapon: bool = True
    ammunition_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd1fe7750>
    equip_proto: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520ca10>
    guise_template_data: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f610>
    is_dual_weapon: bool = False
    is_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e310>
    is_melee: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f590>
    is_own_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520eb90>
    show_guise_bullet_trace: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231a50>
    show_guise_hit_effect: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231b10>
    skin_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f5d0>
    spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e250>
    vice_spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520d250>

    def ActiveBindBomb(self, extra=None): ...
    def AddHiddenReason(self, reason): ...
    def AddInspectExtraModel(self): ...
    def AddWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def AddWeaponPart(self, part_id, part_loaded_callback=None, refresh_model=False): ...
    def AttachBackupChargerToWeapon(self, is_dual=False): ...
    def AttachWeaponChargerToLeftHandNew(self): ...
    def AttachWeaponChargerToLeftHandOld(self, is_dual=False): ...
    def AttachWeaponToAvatarBack(self): ...
    def AttachWeaponToAvatarHand(self): ...
    def AttachWeaponToHandAnimWeapon(self): ...
    def AttachWeaponToHandBack(self): ...
    def AttachWeaponToHandEquip(self): ...
    def AttachWeaponToLeftHand(self): ...
    def AttachWeaponToRightHand(self): ...
    def BanSamuraiSmoothSwitchOnce(self): ...
    def BatchAddDecals(self, data, realtime=False): ...
    def BuildDecalBakeCameraInfo(self, slot, decal_path, rotation, offset, scale, viewMatrix): ...
    def BuildDecalBakeModelInfo(self, part_types, slot, realtime): ...
    def ChangeWeaponDecorate(self, skin_id, guise_id, hangings_id, sticker_info): ...
    def ChangeWeaponGuise(self, guise_id, data_changed=True, need_callback=True): ...
    def ChangeWeaponHangings(self, hangings_id, data_changed=True): ...
    def ChangeWeaponPartGuise(self, part_guise_info, data_changed=True, change_part=True, part_loaded_callback=None): ...
    def ChangeWeaponSkin(self, skin_id, data_changed=True, force_refresh=False): ...
    def ChangeWeaponSticker(self, sticker_info, realtime=False, data_changed=True): ...
    def CheckCreateMaterialFeature(self): ...
    def CheckIfQuickRaise(self, old_weapon_guid): ...
    def CheckInspectExtraModel(self): ...
    def CheckKillCounterPrim(self): ...
    def CheckSamePartGuiseInfo(self, info): ...
    def CheckSamePartSlots(self, part_slots_old, part_slots_new): ...
    def CheckSameStickerInfo(self, info): ...
    def CheckShowGunDlcExistsShaderEffect(self): ...
    def CheckSimulateHallFire(self): ...
    def CheckSupportedKillCounter(self): ...
    def CheckSupportedKillCounterInHall(self, item_id, check_satisfy_upgrade=False): ...
    def ClearDecal(self): ...
    def ClearGuiseItemCache(self): ...
    def ClearModAttrByName(self, name): ...
    def ClearParam(self): ...
    def ClearTrailEffectList(self, effect_list, fadeout=0, is_lefthand=False): ...
    def ClearWeaponPartTypeMod(self, part_type): ...
    def ClearWeaponPartTypeModAttr(self, part_type): ...
    def CombineDecalBakeModelInfo(self): ...
    def CopyDecalModelData(self, decalModel): ...
    def CreateKillCounterTexture(self, kill_number=0): ...
    def DeActiveBindBomb(self): ...
    def DebugChangeSkinWithRepositoryName(self, repository_name, change_optic=False): ...
    def DebugRecoverSkin(self): ...
    def DecalBakingEnter(self, data, realtime): ...
    def DecalBakingExit(self): ...
    def DecalChangeState(self, state, *args, **kwargs): ...
    def DecalEmptyEnter(self): ...
    def DecalEmptyExit(self): ...
    def DecalLoadingEnter(self, data, realtime=False): ...
    def DecalLoadingExit(self): ...
    def DecreaseFireHeat(self, dtime): ...
    def DecreaseHeatTick(self, dtime): ...
    def DecreaseScatterTick(self, dtime): ...
    def DelayUpdateCustomComposition(self): ...
    def DesideShowSimplePartModel(self): ...
    def Destroy(self): ...
    def DestroyDualWeapon(self): ...
    def DestroyModel(self): ...
    def DisablePrincipleRole(self): ...
    def DoBatchAddDecals(self, data, realtime=False): ...
    def DoRefreshOpticMaterial(self, is_ads, token): ...
    def DropWeapon(self): ...
    def DropWeaponForAvatar(self): ...
    def ExecAllModelFunc(self, func_name, *args): ...
    def ExecPartModelFunc(self, part_types, func_name, *args): ...
    def FinishKillCounterTexture(self, guid): ...
    def ForceAttachWeaponToHandAnimWeapon(self): ...
    def ForceAttachWeaponToLeftHand(self): ...
    def ForceAttachWeaponToRightHand(self): ...
    def ForceDropCurWeapon(self): ...
    def ForceDropWeaponForAvatar(self): ...
    def GetAttrDiffPercent(self, name, default=None): ...
    def GetAttrValue(self, name, default=None): ...
    def GetDefaultMeleeEquipId(self): ...
    def GetFallDirSpeed(self): ...
    def GetGunMuzzleTrans(self): ...
    def GetGunSkinPartModelList(self, default_value=None): ...
    def GetGunType(self): ...
    def GetMaxDamageHitPart(self, hit_parts): ...
    def GetMeleeAttackEffectId(self, hit_pose_id): ...
    def GetMeleeCaseDlcId(self): ...
    def GetMeleeCaseDlcids(self): ...
    def GetMeleeWeaponModelId(self): ...
    def GetOpticCrosshairPrim(self): ...
    def GetRealAimPointScatterDistOffset(self, shoot_idx): ...
    def GetRealAimPointScatterRecoverSpeed(self, shoot_idx): ...
    def GetRealPenerateDamageDropoffData(self): ...
    def GetRealPersistRecoilDownTimeMax(self, shoot_idx): ...
    def GetRealRecoilData(self, is_real_ads, shoot_idx): ...
    def GetRealRecoilRandomData(self, is_real_ads, shoot_idx): ...
    def GetRealRollShakeInfo(self, is_real_ads, shoot_idx): ...
    def GetRealShootScatterRadian(self, shoot_idx): ...
    def GetRealShootScatterRadianByDecrease(self, shoot_idx): ...
    def GetRealShootScatterRadianForAds(self, shoot_idx): ...
    def GetScatterRadianByHeat(self): ...
    def GetTrailLightBarEffectId(self, simple_version, caster_id_ads, is_fps_avatar): ...
    def GetV6GemAnimPrim(self): ...
    def GetWeaponAttrValue(self, name, default=None): ...
    def GetWeaponAttrValueImmediately(self, name, default=None): ...
    def GetWeaponFeature(self, func_name): ...
    def GetWeaponModAttr(self, name): ...
    def GetWeaponPart(self, part_type): ...
    def GetWeaponPartModel(self, part_type): ...
    def GetWeaponPartModels(self, part_types): ...
    def GetWeaponPartPrims(self, part_types): ...
    def GetWorldBound(self): ...
    def GetWorldBoundCentre(self): ...
    def HideBackupCharger(self): ...
    def HideOpticReflectEffect(self, dtime): ...
    def IncreaseFireHeat(self): ...
    def InitFpsProperty(self): ...
    def InitHandGraphValue(self): ...
    def InitOpticShaderValue(self): ...
    def InitWeapon(self, part_slots=None, part_loaded_callback=None, all_loaded_callback=None, need_refresh_prop=True, is_reload=False, extra=None): ...
    def IsAllPartsModelLoaded(self): ...
    def IsOwnerValid(self): ...
    def IsSamuraiWithSamuraiSword(self): ...
    def JumpToAds(self, is_ads): ...
    def LoadWeaponModAttrOrgValue(self): ...
    def MarkPrincipleRole(self): ...
    def ModelAnimArmWeapon(self, model): ...
    def OnAddWeaponPart(self, part_type, part_id): ...
    def OnBakeSingleDecalCallback(self, holding_models, idx, task_id, result): ...
    def OnBatchBakeDecalCallback(self, ticket, taskid, result): ...
    def OnCastSpell(self): ...
    def OnCastSpellStart(self): ...
    def OnCastSpellStop(self): ...
    def OnRefreshWeaponMaterial(self): ...
    def OnSpellImmune(self): ...
    def OnWeaponModelLoad(self): ...
    def PlayTrailEffectList(self, effect_list, is_lefthand=False): ...
    def ProcessSeparateMeshDecal(self): ...
    def RaiseWeapon(self): ...
    def RaiseWeaponForAvatar(self): ...
    def RefreshAmmoAmmunition(self): ...
    def RefreshAmmoAmmunitionEffect(self, ammo, max_ammo): ...
    def RefreshAmmoModelValue(self): ...
    def RefreshAmmoShaderEffect(self, ammo, max_ammo): ...
    def RefreshAmmoShaderEffectForRecevier(self, ammo, max_ammo): ...
    def RefreshAmmoShaderValue(self): ...
    def RefreshBackupChargerModel(self): ...
    def RefreshEffectCameraAttaching(self): ...
    def RefreshFireSfxId(self, guise_template_data, guise_item_id): ...
    def RefreshFireSfxIdForGunPart(self): ...
    def RefreshFpsPlacerProp(self, is_init=False): ...
    def RefreshGuise3PEffectInCombat(self): ...
    def RefreshGuiseEffect(self): ...
    def RefreshGuiseOverlayIdlePose(self): ...
    def RefreshGuiseSkinAnimPose(self, model, graph_id): ...
    def RefreshGuiseSkinAnimPoseForHand(self): ...
    def RefreshGuiseSkinAnimPoseForWeapon(self): ...
    def RefreshGunDlcExists(self): ...
    def RefreshHandGraphValue(self, val_name): ...
    def RefreshHasGuiseDlcId(self): ...
    def RefreshInspectExtraModel(self): ...
    def RefreshKillCounterForChangeGuise(self): ...
    def RefreshOpticEffect(self, is_ads): ...
    def RefreshOpticMaterial(self, is_ads): ...
    def RefreshOpticModelForAds(self, is_ads): ...
    def RefreshOpticPose(self): ...
    def RefreshOpticScopeEnable(self, is_ads): ...
    def RefreshOpticShaderSightStabilize(self): ...
    def RefreshOpticShaderValue(self, val_name): ...
    def RefreshShaderGraphParamterByData(self): ...
    def RefreshTpsEffectEntityVisible(self): ...
    def RefreshWeaponAttrFromCombatAttr(self, attr_name): ...
    def RefreshWeaponBody(self, body): ...
    def RefreshWeaponDecorate(self): ...
    def RefreshWeaponPartModAttr(self): ...
    def RefreshWeaponProp(self): ...
    def RefreshWeaponSticker(self, realtime=False): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveInspectExtraModel(self): ...
    def RemoveOpticStoryTick(self): ...
    def RemoveWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def ResetBackupCharger(self): ...
    def ResetFireHeat(self): ...
    def ResetOpticModelForAds(self, is_ads): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetDefaultShaderGraphMaterialForHall(self): ...
    def SetDualIsEmptyReload(self, is_empty): ...
    def SetIsAds(self, is_ads): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsEmptyReload(self, is_empty): ...
    def SetIsFirstRaise(self, value): ...
    def SetIsInShowRoom(self, in_showroom): ...
    def SetIsLoadForWarmingUp(self, is_warmingup): ...
    def SetIsMeleeFirstRaise(self, value): ...
    def SetIsNeedRechamber(self, is_need): ...
    def SetIsRealAds(self, is_real_ads): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetMpFpsActionForMachineSight(self, action, blendTime): ...
    def SetNoNearPlaneClip(self, enable): ...
    def ShowModel(self): ...
    def ShowOpticReflectEffect(self, dtime): ...
    def SimulatedHallAutoFireTimer(self): ...
    def StartDecreaseHeat(self): ...
    def StartDecreaseScatter(self): ...
    def StopDecreaseHeat(self): ...
    def StopDecreaseScatter(self): ...
    def TryFixOpticEffectBug(self): ...
    def UpdateExtraModelVisible(self, is_visible): ...
    def UpdateModAttr(self, part_type, attr_key, value): ...
    def UpdateModAttrOrgValue(self, name, org_value=None): ...
    def UpdateMutexPart(self): ...
    def UpdatePartSlots(self, part_type, part_id): ...
    def UpdateWeaponFeature(self): ...
    def UpdateWeaponPartModAttr(self, part_id): ...
    def UseAllPartWarmingUp(self, is_warmingup): ...
    def _CheckDecalBakeModelValid(self): ...
    def _ClearShootAttr(self): ...
    def _GetGuiseModelId(self, origin_model_id): ...
    def _GetOpticShaderValue_EnableScope(self, origin_value): ...
    def _GetOpticShaderValue_SightStabilize(self, origin_value): ...
    def _GetShootAttr(self, name, *keys): ...
    def _GetWeaponBodyPartSlots(self): ...
    def _InitDualWeaponBody(self): ...
    def _InitDualWeaponHangings(self): ...
    def _IsGunDlcExists(self): ...
    def _OnCastSpell(self): ...
    def _OnCastSpellStart(self): ...
    def _OnCastSpellStop(self): ...
    def _RealBackingDecalTimer(self): ...
    def _RefreshFeatureCache(self): ...
    def _TryOnBakeBackupChargerModelDecal(self): ...
    def _TryOnBakeDualWeaponDecal(self): ...
    def _UpdateShootAttr(self, name, value, *keys): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def ads_fire_heat(self): ...    @property
    def body_equip_proto(self): ...    @property
    def dual_weapon_model(self): ...    @property
    def hand_graph(self): ...    @property
    def is_cur_taking(self): ...    @property
    def is_decal_baking(self): ...    @property
    def is_destroyed(self): ...    @property
    def is_match_server(self): ...    @property
    def weapon_model(self): ...

def Components(*components, **kwargs): ...
def IsAimEnemy(player, max_dist): ...
def IsAimEnemy2D(player, max_dist, distance, filter_dist=True): ...
def IsAimEnemy2DV2(player, max_dist, distance): ...
def IsAimEnemyV2(player, max_dist): ...
def IsWeaponLauncher(equip_id): ...
def StateWrapper(cls): ...

