# module: gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_item

import MEngine
import MType
import cPickle
import cconst
import combat_item_data
import consts
import equip_data
import events
import formula
import functools
import game_logic_data
import lang
import math
import pickup_rank_data
import six2
import talent_data
import time
import time_util
import weapon_data
import weapon_util
import zlib

AUTO_PICKUP_SPECIAL_CHECK: set = {17, 11, 12}
CLIENT_STUB: int = 8
LocalConfig: _LocalConfig = <gclient.config._LocalConfig object at 0x7040bf6d50>
TAG_SPACE: int = 2
cmp_to_key: builtin_function_or_method = <built-in function cmp_to_key>

class ActiveItemSnares(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def on_setattr(self, key, old, new): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class AirdropKind(enum):
    COINS_SUPPLY: int = 9
    CRYSTAL_SWORD: int = 11
    HALL_PACKAGE: int = 6
    ITEM_SUPPLY: int = 7
    SQUAD_FIGHT: int = 8
    SYSTEM: int = 2
    name_to_values: dict = {'SYSTEM': 2, 'HALL_PACKAGE': 6, 'ITEM_SUPPLY': 7, 'SQUAD_FIGHT': 8, 'COINS_SUPPLY': 9, 'CRYSTAL_SWORD': 11}
    value_to_names: dict = {2: 'SYSTEM', 6: 'HALL_PACKAGE', 7: 'ITEM_SUPPLY', 8: 'SQUAD_FIGHT', 9: 'COINS_SUPPLY', 11: 'CRYSTAL_SWORD'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class BackpackSlot(enum):
    ARMOR_PIECE: int = 5002
    CRACK_SCANNER: int = 5004
    EMERGENCY_NEEDLE: int = 5003
    FAKE_SLOT_1: int = 8001
    FAKE_SLOT_2: int = 8002
    LAUNCHER_WEAPON: int = 1005
    MEDICINE_1: int = 7001
    MEDICINE_2: int = 7002
    NONE: int = 0
    SKILL_WEAPON: int = 4001
    SKILL_WEAPON2: int = 4002
    SKILL_WEAPON3: int = 4003
    SUPPORT_WEAPON: int = 5001
    TACTICAL_WEAPON_1: int = 3001
    TACTICAL_WEAPON_2: int = 3002
    TALENT_1: int = 6001
    TALENT_2: int = 6002
    VICE_WEAPON: int = 1003
    WEAPON_1: int = 1001
    WEAPON_2: int = 1002
    WEAPON_3: int = 1004
    name_to_values: dict = {'NONE': 0, 'WEAPON_1': 1001, 'WEAPON_2': 1002, 'WEAPON_3': 1004, 'VICE_WEAPON': 1003, 'LAUNCHER_WEAPON': 1005, 'TACTICAL_WEAPON_1': 3001, 'TACTICAL_WEAPON_2': 3002, 'SKILL_WEAPON': 4001, 'SKILL_WEAPON2': 4002, 'SKILL_WEAPON3': 4003, 'SUPPORT_WEAPON': 5001, 'ARMOR_PIECE': 5002, 'EMERGENCY_NEEDLE': 5003, 'CRACK_SCANNER': 5004, 'MEDICINE_1': 7001, 'MEDICINE_2': 7002, 'TALENT_1': 6001, 'TALENT_2': 6002, 'FAKE_SLOT_1': 8001, 'FAKE_SLOT_2': 8002}
    value_to_names: dict = {0: 'NONE', 1001: 'WEAPON_1', 1002: 'WEAPON_2', 1004: 'WEAPON_3', 1003: 'VICE_WEAPON', 1005: 'LAUNCHER_WEAPON', 3001: 'TACTICAL_WEAPON_1', 3002: 'TACTICAL_WEAPON_2', 4001: 'SKILL_WEAPON', 4002: 'SKILL_WEAPON2', 4003: 'SKILL_WEAPON3', 5001: 'SUPPORT_WEAPON', 5002: 'ARMOR_PIECE', 5003: 'EMERGENCY_NEEDLE', 5004: 'CRACK_SCANNER', 7001: 'MEDICINE_1', 7002: 'MEDICINE_2', 6001: 'TALENT_1', 6002: 'TALENT_2', 8001: 'FAKE_SLOT_1', 8002: 'FAKE_SLOT_2'}

    def IsSkill(slot): ...
    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class ClientAreaEntity(ClientEntity):
    area: getset_descriptor = <attribute 'area' of 'entity' objects>
    logger: Logger = <Logger ClientAreaEntity (DEBUG)>

    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_timer(self, timerid): ...
    def _orded_dispatch_rpc(self, method, *args): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    def add_repeat_timer(self, delay, func): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def deactive(self): ...
    def destroy(self, *args, **kwargs): ...
    def destroyObject(self): ...
    @property
    def dir(self): ...    def entity_method(self, md5, index, args): ...
    def get_gtick(self): ...
    def init_from_dict(self, *args, **kwargs): ...
    def is_deactived(self): ...
    def is_destroyed(self): ...
    def onEntityClassRegistered(): ...
    def on_del_space_data(self, key): ...
    def on_enter_space(self): ...
    def on_leave_space(self): ...
    def on_lose_server(self): ...
    def on_out_sight(self): ...
    def on_play_spectator_finished(self, msg): ...
    def on_set_space_center(self, cent): ...
    def on_set_space_data(self, key, value): ...
    def on_setattr(self, key, old, new): ...
    def on_speed(self, speed): ...
    def on_update_direction(self, stamp, yaw): ...
    def on_update_position(self, stamp, x, y, z): ...
    def on_update_position_and_direction(self, stamp, x, y, z, yaw): ...
    def on_update_space_data(self, data): ...
    @property
    def pos(self): ...    def pre_reload_script(self): ...
    def set_server(self, server): ...
    def set_tick(self, period): ...
    def setdefault(self, key, dft): ...
    @property
    def space(self): ...    @property
    def speed(self): ...    def tick(self, dtime): ...
    @property
    def yaw(self): ...
class CombatAvatarMember(object):
    def OnPickupItem(self, item_id): ...
    def _on_set_uav_data(self, old): ...
    def _on_set_uav_data_full(self, old): ...

class CombatItemType(enum):
    AIRDROP: int = 104
    AMMO: int = 102
    AMMOBAG: int = 115
    AMMO_SUPPLEMENT: int = 113
    ARMOR_UPGRADE: int = 118
    BLOOD_CRYSTAL: int = 117
    BOX: int = 103
    BROKEN_TALENT_CORE: int = 112
    COIN: int = 105
    CONTRACT: int = 107
    EQUIP: int = 101
    GENECODE: int = 109
    NONE: int = 0
    RANDOM_TALENT: int = 110
    REBORN_CHANCE: int = 108
    SHUTTER_CLUE: int = 120
    SKILL_UPGRADE: int = 119
    TACTICAL_CORE: int = 111
    TACTICAL_ENERGY: int = 116
    TALENT: int = 106
    TROPHIES: int = 114
    name_to_values: dict = {'NONE': 0, 'EQUIP': 101, 'AMMO': 102, 'BOX': 103, 'AIRDROP': 104, 'COIN': 105, 'TALENT': 106, 'CONTRACT': 107, 'REBORN_CHANCE': 108, 'GENECODE': 109, 'RANDOM_TALENT': 110, 'TACTICAL_CORE': 111, 'BROKEN_TALENT_CORE': 112, 'AMMO_SUPPLEMENT': 113, 'TROPHIES': 114, 'AMMOBAG': 115, 'TACTICAL_ENERGY': 116, 'BLOOD_CRYSTAL': 117, 'ARMOR_UPGRADE': 118, 'SKILL_UPGRADE': 119, 'SHUTTER_CLUE': 120}
    value_to_names: dict = {0: 'NONE', 101: 'EQUIP', 102: 'AMMO', 103: 'BOX', 104: 'AIRDROP', 105: 'COIN', 106: 'TALENT', 107: 'CONTRACT', 108: 'REBORN_CHANCE', 109: 'GENECODE', 110: 'RANDOM_TALENT', 111: 'TACTICAL_CORE', 112: 'BROKEN_TALENT_CORE', 113: 'AMMO_SUPPLEMENT', 114: 'TROPHIES', 115: 'AMMOBAG', 116: 'TACTICAL_ENERGY', 117: 'BLOOD_CRYSTAL', 118: 'ARMOR_UPGRADE', 119: 'SKILL_UPGRADE', 120: 'SHUTTER_CLUE'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class CombatState(enum):
    ALIVE: int = 0
    DEAD: int = 2
    DYING: int = 1
    GHOST: int = 3
    NONE: int = 4
    name_to_values: dict = {'ALIVE': 0, 'DYING': 1, 'DEAD': 2, 'GHOST': 3, 'NONE': 4}
    value_to_names: dict = {0: 'ALIVE', 1: 'DYING', 2: 'DEAD', 3: 'GHOST', 4: 'NONE'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class CustomMapType(area_map):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class EquipmentType(enum):
    ARMOR: int = 15
    COIN_TOOLS: int = 21
    CRACK_SCANNER: int = 20
    EMERGENCY_NEEDLE: int = 16
    GRENADE_LAUNCHER: int = 5
    GUN: int = 1
    GUN_MELEE: int = 3
    INVISIBLE: int = 19
    INVISIBLE2: int = 22
    MEDICINE: int = 17
    MELEE: int = 2
    NONE: int = 0
    NORMAL_TACTICAL: int = 18
    SKILL: int = 13
    SP_GUN: int = 4
    SP_SKILL: int = 23
    SUPPORT: int = 14
    THROWABLE_WEAPON_LEFT: int = 12
    THROWABLE_WEAPON_RIGHT: int = 11
    name_to_values: dict = {'NONE': 0, 'GUN': 1, 'MELEE': 2, 'GUN_MELEE': 3, 'SP_GUN': 4, 'GRENADE_LAUNCHER': 5, 'THROWABLE_WEAPON_RIGHT': 11, 'THROWABLE_WEAPON_LEFT': 12, 'SKILL': 13, 'SUPPORT': 14, 'ARMOR': 15, 'EMERGENCY_NEEDLE': 16, 'MEDICINE': 17, 'NORMAL_TACTICAL': 18, 'INVISIBLE': 19, 'CRACK_SCANNER': 20, 'COIN_TOOLS': 21, 'INVISIBLE2': 22, 'SP_SKILL': 23}
    value_to_names: dict = {0: 'NONE', 1: 'GUN', 2: 'MELEE', 3: 'GUN_MELEE', 4: 'SP_GUN', 5: 'GRENADE_LAUNCHER', 11: 'THROWABLE_WEAPON_RIGHT', 12: 'THROWABLE_WEAPON_LEFT', 13: 'SKILL', 14: 'SUPPORT', 15: 'ARMOR', 16: 'EMERGENCY_NEEDLE', 17: 'MEDICINE', 18: 'NORMAL_TACTICAL', 19: 'INVISIBLE', 20: 'CRACK_SCANNER', 21: 'COIN_TOOLS', 22: 'INVISIBLE2', 23: 'SP_SKILL'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class HudPickItemTipsPcComp(UIWindow):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def CheckDLcExist(): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCsbPathFile(self): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetRecoveryFunc(): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnDestroy(self): ...
    def OnFocus(self, value): ...
    def OnKeyDownEsc(self): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def PushItemInfo(self, info): ...
    def RefreshPcKey(self): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _SetHallLevel(self, visible): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _cancelLongTouch(self): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class IAirdrop(object):
    MAP_TAG_ID_MAP: dict = {2: 42, 6: 42, 7: 59, 8: 66, 9: 204, 11: 10004}
    SCENE_NODE_ID_MAP: dict = {2: 3, 6: 3, 7: 6, 8: 14, 9: 25, 11: 28}

    def GetMapTagId(self, marker=None): ...
    def GetMarkPosition(self): ...
    def GetSceneNodeId(self, marker=None): ...

class ICombatItem(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: NoneType = None
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    @property
    def ammo(self): ...    @property
    def contract_id(self): ...    @property
    def drop_timestamp(self): ...    @property
    def dye_owner_id(self): ...    @property
    def ecotope_name(self): ...    @property
    def equip_id(self): ...    @property
    def equip_proto(self): ...    @property
    def equip_type(self): ...    @property
    def from_id(self): ...    @property
    def guise_item_id(self): ...    @property
    def guise_name(self): ...    @property
    def guise_template_id(self): ...    @property
    def gun_id(self): ...    @property
    def id(self): ...    @property
    def inner_count(self): ...    @property
    def is_box(self): ...    @property
    def is_custom_gun(self): ...    @property
    def is_die_drop(self): ...    @property
    def is_gun(self): ...    @property
    def is_gun_melee(self): ...    @property
    def is_melee(self): ...    @property
    def is_sp_gun(self): ...    @property
    def is_throwable_weapon(self): ...    @property
    def item_proto(self): ...    @property
    def item_source(self): ...    @property
    def item_sub_type(self): ...    @property
    def item_type(self): ...    def items(self): ...
    def keys(self): ...
    @property
    def left_hand_ammo(self): ...    @property
    def max_stack(self): ...    @property
    def open_avatar_id(self): ...    @property
    def ornament_item_id(self): ...    @property
    def owner_id(self): ...    @property
    def owner_name(self): ...    @property
    def quality(self): ...    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    @property
    def skin_ground_item_id(self): ...    @property
    def skin_item_id(self): ...    @property
    def skin_template_id(self): ...    def update2(self, data): ...
    def values(self): ...

class Int(object):
    convert: method_descriptor = <method 'convert' of 'int' objects>
    get_type: method_descriptor = <method 'get_type' of 'int' objects>
    getname: method_descriptor = <method 'getname' of 'int' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'int' objects>
    name: getset_descriptor = <attribute 'name' of 'int' objects>

class MergeCall(object):
class MobaHudPickupCompPC(MobaHudPickupComp):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = (2, 4, 3, 14, 16, 15)
    HALL_LEVEL: NoneType = None
    PICKUP_ITEM_NODE: type = <class 'gclient.gameplay.logic_moba.ui.moba_hud_pickup_comp.PickupItem'>
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddGamepadKeyPanel(self, func_id, panel, with_txt=False, force_long=False): ...
    def AddHiddenReason(self, reason): ...
    def AddPcKeyNode(self, func_id, panel, have_text=False): ...
    def AddStoryTick(self, func, frames=0): ...
    def CacheSomeBtnOpacity(self): ...
    def CanScollUp(self): ...
    def CanScrollDown(self): ...
    def CancelPanelTouchTimer(self): ...
    def ChangePanelPcKeyFuncId(self, old_func_id, new_func_id, target_panel=None): ...
    def CheckDLcExist(): ...
    def CheckHiddenAction(self): ...
    def CheckNearItemEffective(self): ...
    def CheckNodeItemPanelChangeVisible(self, combat_item, show): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ChooseExchangeNodeForCurPicked(self): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def CreatePickupNode(self, key): ...
    def DelPcKeyNode(self, func_id): ...
    def DelPcKeyNodeByPanel(self, panel): ...
    def Destroy(): ...
    def DropPickupNode(self, key, node): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMarkMove(self, node, delta=0): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FetchPickupNode(self, key): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetDataSort(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetRecoveryFunc(): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HandleButtonB(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HandleButtonDPADDOWN(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HandleButtonDPADLEFT(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HandleButtonDPADRIGHT(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HandleButtonDPADUP(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HandleButtonThumbR(self, is_down=True, offset_x=0.0, offset_y=0.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def HideForReasonEvent(self, reason, is_hide): ...
    def InitCapacityNotices(self): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitNode(self): ...
    def InitOpacityWidgets(self, widgets_list, widget_info_list, widget_pc_list=[]): ...
    def InitPanelExchange(self, panel): ...
    def InitPanelExchangeTalent(self, panel): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsInClickedForExchange(self, combat_item): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def ListviewGroupSingle(self, irange): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def LoadPanelExchangeSlot(self, slot, combat_item): ...
    def LoadPanelExchangeTalent(self, combat_item): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def MovePositionWithBackpackInteraction(self): ...
    def OnAutoPickUpItemEvent(self, combat_item): ...
    def OnAvatarLoginRelay(self, is_relay): ...
    def OnBackpackSlotFull(self, combat_item): ...
    def OnClickCancelToMark(self, node): ...
    def OnClickMoveToMark(self, node): ...
    def OnClickStartToMark(self, node): ...
    def OnClosePanelClick(self, _): ...
    def OnCursorVisibleChangedForSpell(self, visible): ...
    def OnDestroy(self): ...
    def OnExchangeSlot(self, node): ...
    def OnFinishAutoPickAnim(self): ...
    def OnFocus(self, value): ...
    def OnGamepadChange(self, has_gamepad): ...
    def OnGamepadChangePcKeyNodes(self, has_gamepad): ...
    def OnGamepadChangePickUp(self, has_gamepad): ...
    def OnGamepadKeySettingChange(self): ...
    def OnKeyDownEsc(self): ...
    def OnMarkChange(self, pos, slot, mark_type, guid, extra_info=None, member_id=''): ...
    def OnNearbyCombatItemChange(self, combat_item): ...
    def OnPcOpenPickUpBox(self, is_open): ...
    def OnPickupBgTouchBegin(self, touch, event): ...
    def OnPickupBgTouchEnd(self, touch, event): ...
    def OnPickupBgTouchMove(self, touch, event): ...
    def OnPlayerBecomeZombiePickup(self, *args): ...
    def OnPlayerStateLinkAdd(self, state): ...
    def OnPlayerStateLinkRemove(self, state): ...
    def OnRefreshPcPickUpBox(self): ...
    def OnRefreshPickupCombatitem(self, is_add, combatitem, need_refresh=True, refresh_check=True, need_sort=True): ...
    def OnRefreshPickupUI(self): ...
    def OnShowPanelClick(self, _): ...
    def OnTalentExchangeNodeClick(self, node): ...
    def OnTalentExchangeNodeConfirm(self, node): ...
    def OnTalentSlotsFull(self, combat_item): ...
    def OnUIOpacityChange(self, reason, is_hide): ...
    def OnWheelDown(self): ...
    def OnWheelUp(self): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PickupItemOneByOne(self): ...
    def PickupItemOneByOneByHandle(self, from_handle=False): ...
    def PickupItemOneByOneOnBox(self): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayAutoPickShowingAnim(self, item_id): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PostVisible(self, value): ...
    def PreCachePool(self): ...
    def PreVisible(self, value): ...
    def ReCheckNearItemEffective(self, res_item_id): ...
    def RefreshAllCacheData(self): ...
    def RefreshListview(self, key, listview, listview_data): ...
    def RefreshPanelGroupSingle(self, group_item, data): ...
    def RefreshPanelItem(self, item, data): ...
    def RefreshPanelPickupSingle(self): ...
    def RefreshPcKey(self): ...
    def RefreshPcKeyNodes(self): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetReplaceItem(self, idx): ...
    def SetUserDefineWidgetPos(self): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def ShowPanel(self): ...
    def ShowPanelExchangeSlot(self, visible, btn=None): ...
    def ShowPanelExchangeTalentSlot(self, visible, btn=None): ...
    def StopAnim(self): ...
    def _AddOpacityHideReason(self, reason): ...
    def _CheckPosInteractionWithMarkPanel(self, world_pos, size, anchor): ...
    def _CheckValidCurIndex(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _GetCsbPath(self): ...
    def _GetCurChoosenItem(self): ...
    def _GetItemNodeByItem(self, combat_item): ...
    def _GetNodeWorldBeyondLimit(self, node): ...
    def _HaveOpacityHideReason(self, reason): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _RemoveOpacityHideReason(self, reason): ...
    def _SetCurChooseIndex(self, index): ...
    def _SetHallLevel(self, visible): ...
    def _SetOpacityForCacheWidgets(self, is_hide, opacity_factor, is_info=False, need_fade=False): ...
    def _SetOpacityForCacheWidgetsPC(self, is_hide, opacity_factor): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _cancelLongTouch(self): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _postComponents(self, bdict): ...
    def _show_node_hover(self, node, visible): ...
    def _tickComponents(self, dtime): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class PlayerCombatAvatarMember(CombatAvatarMember):
    Pickup_Equip_Type_Map: dict = {1: 'Gun', 11: 'Throwable', 12: 'Throwable', 14: 'Support', 16: 'Emergency_Needle', 17: 'Medicine'}
    Pickup_Item_Type_Map: dict = {101: 'Equip', 102: 'Ammo', 105: 'Coin', 109: 'Genecode', 112: 'BrokenTalentCore', 116: 'TacticalEnergy', 117: 'Coin'}
    _DelayPickup: AsyncDescriptor = <gshare.async_util.AsyncDescriptor object at 0x6f9c2b7590>

    def AutoMarkItem(self, combatitem): ...
    def AutoPickupItemImpl(self, _): ...
    def AutoPickupItemPCImpl(self, _): ...
    def AutoPickupItemPCTimer(self, _): ...
    def CanDropItemByGuid(self, item_guid): ...
    def CanPickupItemForCapacity(self, combatitem): ...
    def CompareCombatItemsNew(self, item1, item2): ...
    def CreatePickupGroup(self, group_id, group_name, priority=0): ...
    def DelAutoMarkItem(self, combatitem): ...
    def DeletePickupGroup(self, group_id): ...
    def DoAutoMarkItem(self, combatitem): ...
    def DoPickupItemCheckShoot(self): ...
    def DropItemByGuid(self, item_guid, count=-1): ...
    def DropItemByItemid(self, item_id, count=-1): ...
    def DropItemCoins(self, count=-1): ...
    def GetCombatItemRuleKey(self, combatitem): ...
    def GetSortLevel(self, item, sort_proto): ...
    def IsItemRecommonend(self, combatitem, recommend_count_map): ...
    def IsTacticalEnergyFull(self): ...
    def MarkAutoPickupItemTime(self): ...
    def OnGainSkillTalents(self): ...
    def OnPickupItem(self, item_id): ...
    def OpenSupply(self, guid): ...
    def PickupItem(self, combatitem, need_delay=False, is_auto=False): ...
    def PickupItemBySnare(self, item_guid, extra=None): ...
    def PropertyChanged(self, name, value): ...
    def RefreshPickupData(self, is_add, combatitem, check_shoot=True, do_sort=True): ...
    def RefreshPickupDataAfterPickup(self): ...
    def RefreshPickupDataList(self, combat_item_list, check_shoot=True): ...
    def ResetPickupData(self): ...
    def SortCombatItems(self, items, use_recommend_rank=False): ...
    def SortCombatItemsWithRecommond(self, combatitems, check_has_recommend=False, need_sort=True): ...
    def StartAutoPickupItem(self): ...
    def StopAutoPickupItem(self): ...
    def SwapBackpackSlot(self, src_slot, dst_slot): ...
    def _CanAutoPickUpForMedicine(self, combatitem): ...
    def _CanAutoPickUpForThrowableWeapon(self, combatitem): ...
    def _CanAutoPickup(self): ...
    def _CanAutoPickupItem(self, combatitem): ...
    def _CanAutoPickupItemForEnergy(self): ...
    def _CanPickup(self): ...
    def _CanPickupItem(self, combatitem, is_auto=False): ...
    def _CanPickup_Gun(self, combatitem, is_auto=False): ...
    def _CanShootPickupItem(self, combat_item): ...
    def _CheckCanAutoMarkItem(self, combatitem): ...
    def _CreateVirtualCombatItemForPickUp(self, item_id, item_count, guid): ...
    def _DoPickup(self, combatitem, is_auto=False): ...
    def _GetPickupItemPriority(self, data): ...
    def _GetRecMedicinePriority(self, item_id): ...
    def _IsCurGunRecommend(self, combatitem): ...
    def _Pickup_Talent(self, combatitem): ...
    def _RecommendRuleFor_Ammo(self, combatitem, recommend_count_map): ...
    def _RecommendRuleFor_BrokenTalentCore(self, combatitem, recommend_count_map): ...
    def _RecommendRuleFor_Coin(self, entity, recommend_count_map): ...
    def _RecommendRuleFor_Emergency_Needle(self, combatitem, recommend_count_map): ...
    def _RecommendRuleFor_Genecode(self, combatitem, recommend_count_map): ...
    def _RecommendRuleFor_Gun(self, combatitem, recommend_count_map): ...
    def _RecommendRuleFor_Medicine(self, combatitem, recommend_count_map): ...
    def _RecommendRuleFor_Support(self, combatitem, recommend_count_map): ...
    def _RecommendRuleFor_TacticalEnergy(self, combatitem, recommend_count_map): ...
    def _RecommendRuleFor_Throwable(self, combatitem, recommend_count_map): ...
    def _ResignPickupData(self): ...
    def _on_set_uav_data(self, old): ...
    def _on_set_uav_data_full(self, old): ...

class StateRelationship(enum):
    BeExecuted: int = 50
    ChargeJump: int = 63
    ChargeJumpAir: int = 66
    Climb: int = 10
    ClimbLadder: int = 32
    CommonTpsSkill: int = 67
    Cross: int = 23
    Crouch: int = 6
    DriveVehicle: int = 33
    DropWeapon: int = 21
    DualFire: int = 57
    DualGun: int = 52
    DualReload: int = 54
    DualReloadEnd: int = 56
    DualReloading: int = 55
    Emote: int = 51
    EnterAds: int = 19
    EnterProne: int = 27
    Execution: int = 49
    ExitProne: int = 28
    Fire: int = 12
    GunInspection: int = 44
    GunRefit: int = 30
    HighFall: int = 45
    Idle: int = 1
    Inspirator: int = 46
    Item: int = 16
    Jog: int = 3
    Jump: int = 8
    KickUp: int = 65
    KnockDown: int = 11
    LeanOutVehicle: int = 34
    LeftShield: int = 64
    LeftXDroid: int = 62
    Medicine: int = 60
    Melee: int = 29
    MeleeAttack: int = 39
    MovingShield: int = 31
    OnVehicle: int = 7
    PickUp: int = 18
    PortableEquipment: int = 53
    Prone: int = 26
    RaiseLeftHandWeapon: int = 25
    RaiseWeapon: int = 20
    Rechamber: int = 22
    Reload: int = 13
    ReloadEnd: int = 43
    Reloading: int = 42
    RescueOther: int = 35
    SamuraiBlock: int = 58
    SamuraiSprint: int = 59
    ScanCore: int = 36
    Skill: int = 24
    SkillCantAir: int = 48
    SkillCantProne: int = 41
    SkillWeaponDrop: int = 38
    SkillWeaponRaise: int = 37
    Slide: int = 9
    Sprint: int = 4
    Strop: int = 17
    SuperSprint: int = 5
    Swim: int = 47
    ThrowableWeaponLeft: int = 15
    ThrowableWeaponRight: int = 14
    TripleShot: int = 61
    Walk: int = 2
    Xdroid: int = 40
    name_to_values: dict = {'Idle': 1, 'Walk': 2, 'Jog': 3, 'Sprint': 4, 'SuperSprint': 5, 'Crouch': 6, 'OnVehicle': 7, 'Jump': 8, 'Slide': 9, 'Climb': 10, 'KnockDown': 11, 'Fire': 12, 'Reload': 13, 'ThrowableWeaponRight': 14, 'ThrowableWeaponLeft': 15, 'Item': 16, 'Strop': 17, 'PickUp': 18, 'EnterAds': 19, 'RaiseWeapon': 20, 'DropWeapon': 21, 'Rechamber': 22, 'Cross': 23, 'Skill': 24, 'RaiseLeftHandWeapon': 25, 'Prone': 26, 'EnterProne': 27, 'ExitProne': 28, 'Melee': 29, 'GunRefit': 30, 'MovingShield': 31, 'ClimbLadder': 32, 'DriveVehicle': 33, 'LeanOutVehicle': 34, 'RescueOther': 35, 'ScanCore': 36, 'SkillWeaponRaise': 37, 'SkillWeaponDrop': 38, 'MeleeAttack': 39, 'Xdroid': 40, 'SkillCantProne': 41, 'Reloading': 42, 'ReloadEnd': 43, 'GunInspection': 44, 'HighFall': 45, 'Inspirator': 46, 'Swim': 47, 'SkillCantAir': 48, 'Execution': 49, 'BeExecuted': 50, 'Emote': 51, 'DualGun': 52, 'PortableEquipment': 53, 'DualReload': 54, 'DualReloading': 55, 'DualReloadEnd': 56, 'DualFire': 57, 'SamuraiBlock': 58, 'SamuraiSprint': 59, 'Medicine': 60, 'TripleShot': 61, 'LeftXDroid': 62, 'ChargeJump': 63, 'LeftShield': 64, 'KickUp': 65, 'ChargeJumpAir': 66, 'CommonTpsSkill': 67}
    value_to_names: dict = {1: 'Idle', 2: 'Walk', 3: 'Jog', 4: 'Sprint', 5: 'SuperSprint', 6: 'Crouch', 7: 'OnVehicle', 8: 'Jump', 9: 'Slide', 10: 'Climb', 11: 'KnockDown', 12: 'Fire', 13: 'Reload', 14: 'ThrowableWeaponRight', 15: 'ThrowableWeaponLeft', 16: 'Item', 17: 'Strop', 18: 'PickUp', 19: 'EnterAds', 20: 'RaiseWeapon', 21: 'DropWeapon', 22: 'Rechamber', 23: 'Cross', 24: 'Skill', 25: 'RaiseLeftHandWeapon', 26: 'Prone', 27: 'EnterProne', 28: 'ExitProne', 29: 'Melee', 30: 'GunRefit', 31: 'MovingShield', 32: 'ClimbLadder', 33: 'DriveVehicle', 34: 'LeanOutVehicle', 35: 'RescueOther', 36: 'ScanCore', 37: 'SkillWeaponRaise', 38: 'SkillWeaponDrop', 39: 'MeleeAttack', 40: 'Xdroid', 41: 'SkillCantProne', 42: 'Reloading', 43: 'ReloadEnd', 44: 'GunInspection', 45: 'HighFall', 46: 'Inspirator', 47: 'Swim', 48: 'SkillCantAir', 49: 'Execution', 50: 'BeExecuted', 51: 'Emote', 52: 'DualGun', 53: 'PortableEquipment', 54: 'DualReload', 55: 'DualReloading', 56: 'DualReloadEnd', 57: 'DualFire', 58: 'SamuraiBlock', 59: 'SamuraiSprint', 60: 'Medicine', 61: 'TripleShot', 62: 'LeftXDroid', 63: 'ChargeJump', 64: 'LeftShield', 65: 'KickUp', 66: 'ChargeJumpAir', 67: 'CommonTpsSkill'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...


def Async(tag=0): ...
def Property(name, default, flag=2): ...
def rpc_method(rpctype, *types): ...

