# module: gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_house_detector

import MType
import cconst
import consts
import events
import formula
import replay_util
import six2

class CombatAvatarMember(object):
    def CheckEmitterObstructValue(self): ...
    def CheckInHouseWhenStateChange(self): ...
    def GetInHouseName(self): ...
    def HouseDetectOnCombatState(self, avatar): ...
    def HouseRangeTriggerEnter(self, entity_name, is_enter): ...
    def IndoorTriggerEnter(self, entity_name, is_enter): ...
    def LeaveHouseOnDead(self): ...
    def OnEnterHouseTrigger(self, entity_name, is_enter): ...
    def TickCanShootPlayerForSound(self): ...
    def TickInHouseRangeDetector(self): ...
    def _CancelRangeHouseTimer(self): ...
    def _ResetInHouseParam(self): ...
    def _ResetRangeHouseParam(self): ...
    def _on_set_is_in_house(self, old): ...
    @property
    def in_same_house_with_player(self): ...
class EPerformanceLevel(enum):
    LEVEL_0: int = 0
    LEVEL_1: int = 1
    LEVEL_2: int = 2
    LEVEL_3: int = 3
    LEVEL_4: int = 4
    LEVEL_5: int = 5
    LEVEL_HIGHEST: int = 10
    name_to_values: dict = {'LEVEL_0': 0, 'LEVEL_1': 1, 'LEVEL_2': 2, 'LEVEL_3': 3, 'LEVEL_4': 4, 'LEVEL_5': 5, 'LEVEL_HIGHEST': 10}
    value_to_names: dict = {0: 'LEVEL_0', 1: 'LEVEL_1', 2: 'LEVEL_2', 3: 'LEVEL_3', 4: 'LEVEL_4', 5: 'LEVEL_5', 10: 'LEVEL_HIGHEST'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class PlayerCombatAvatarMember(CombatAvatarMember):
    def CheckEmitterObstructValue(self): ...
    def CheckInHouseWhenStateChange(self): ...
    def GetInHouseName(self): ...
    def HouseDetectOnCombatState(self, avatar): ...
    def HouseRangeTriggerEnter(self, entity_name, is_enter): ...
    def IndoorTriggerEnter(self, entity_name, is_enter): ...
    def LeaveHouseOnDead(self): ...
    def OnEnterHouseTrigger(self, entity_name, is_enter): ...
    def TickCanShootPlayerForSound(self): ...
    def TickInHouseRangeDetector(self): ...
    def _CancelRangeHouseTimer(self): ...
    def _ResetInHouseParam(self): ...
    def _ResetRangeHouseParam(self): ...
    def _on_set_is_in_house(self, old): ...
    @property
    def in_same_house_with_player(self): ...

def Property(name, default, flag=2): ...

