# module: gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_attr

import cconst
import events
import six2
import time

class CombatAvatarMember(object):
    def AddAssassinateEffect(self): ...
    def ClearAssassinateEffect(self): ...
    def GetCombatStatusLastInterval(self, combat_status): ...
    def GetWeaponAttrValueWithCache(self, name, defalut, timeout): ...
    def RefreshCombatAttrImmediately(self, attr_name, old, new): ...
    def UpdateCombatStatusTimestamp(self, combat_status): ...
    def _on_refresh_SkillMaxCount(self, old, new): ...
    def _on_refresh_StrafeMainFovScale(self, old, new): ...

class HumanoidMonsterCombatAttr(CombatAvatarMember):
    def AddAssassinateEffect(self): ...
    def ClearAssassinateEffect(self): ...
    def GetCombatStatusLastInterval(self, combat_status): ...
    def GetWeaponAttrValueWithCache(self, name, defalut, timeout): ...
    def RefreshCombatAttrImmediately(self, attr_name, old, new): ...
    def UpdateCombatStatusTimestamp(self, combat_status): ...
    def _on_refresh_SkillMaxCount(self, old, new): ...
    def _on_refresh_StrafeMainFovScale(self, old, new): ...

class MonsterCombatAttr(CombatAvatarMember):
    def AddAssassinateEffect(self): ...
    def ClearAssassinateEffect(self): ...
    def GetCombatStatusLastInterval(self, combat_status): ...
    def GetWeaponAttrValueWithCache(self, name, defalut, timeout): ...
    def RefreshCombatAttrImmediately(self, attr_name, old, new): ...
    def UpdateCombatStatusTimestamp(self, combat_status): ...
    def _on_refresh_SkillMaxCount(self, old, new): ...
    def _on_refresh_StrafeMainFovScale(self, old, new): ...

class PlayerCombatAvatarMember(CombatAvatarMember):
    def AddAssassinateEffect(self): ...
    def ClearAssassinateEffect(self): ...
    def GetCombatStatusLastInterval(self, combat_status): ...
    def GetWeaponAttrValueWithCache(self, name, defalut, timeout): ...
    def RefreshCombatAttrImmediately(self, attr_name, old, new): ...
    def UpdateCombatStatusTimestamp(self, combat_status): ...
    def _on_refresh_BanSprint(self, old, new): ...
    def _on_refresh_SkillMaxCount(self, old, new): ...
    def _on_refresh_StrafeMainFovScale(self, old, new): ...
    def _on_refresh_global_movement_speed(self, old, new): ...
    def _on_refresh_move_action_speed(self, old, new): ...
    def _on_refresh_movement_speed(self, old, new): ...


