# module: gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_sound

import GlobalData
import MType
import cconst
import consts
import events
import formula
import material_type_data
import replay_util
import six2
import sound_event_data
import space_data
import time
import weapon_util

CLIENT_STUB: int = 8
GUN_SFX_LIMITS: dict = {6: -1, 8: -1, 5: -1}
GUN_SFX_LIMIT_DEFAULT: dict = {0: 100, 1: 100, 2: 125, 3: 150}
GUN_SOUND_LIMITS: dict = {6: -1, 8: -1, 5: -1}
GUN_SOUND_LIMIT_DEFAULT: dict = {0: 100, 1: 100, 2: 125, 3: 150, 4: 200}
LocalConfig: _LocalConfig = <gclient.config._LocalConfig object at 0x7040bf6d50>
SoundCache: dict = {}

class CombatAvatarMember(object):
    def BroadcastSoundEvent(self, sound_type, sound_pos, extra=None): ...
    def CacheSoundID(self, event_id, sound_id, sound_tag): ...
    def CheckAndGetSwitchDict(self, event_id, pos, is_3d, max_dist, notify_ai): ...
    def GetGunSoundMedia(self): ...
    def GetSwitchValue_character_action(self): ...
    def GetSwitchValue_gun_fire_state(self): ...
    def GetSwitchValue_gun_type(self): ...
    def GetSwitchValue_hit_feedback(self): ...
    def GetSwitchValue_identity(self): ...
    def GetSwitchValue_material_surface(self): ...
    def GetSwitchValue_visual(self): ...
    def HasSoundByTag(self, tag): ...
    def InitUpdateSoundCacheVar(self): ...
    def OnSyncGame3DSound(self, sound_id, extra_info={}): ...
    def OnSyncUnloadGame3DSound(self, sound_id): ...
    def OnSyncUnloadGame3DSounds(self, sound_ids): ...
    def PlayGeneralSoundEventById(self, event_id, pos=None, param_dict=None, is_3d=True, vol=1.0, gameObjectID=None, **kwargs): ...
    def PlayGunSoundEventById(self, event_id, direction=None, force_switch_dict=None): ...
    def PlayHitSoundEvent(self, caster_id, sound_result, vol=1.0): ...
    def SetSoundParameterByTag(self, tag, name, value): ...
    def StopSoundByTag(self, tag): ...
    def TickUpdateSoundCache(self): ...
    def UnLoadEventByEventKey(self, eventKey): ...
    def UpdateHeartbeatSound(self, hp, old_hp): ...
    @property
    def show_game_sound(self): ...
class Dict(object):
    convert: method_descriptor = <method 'convert' of 'dict' objects>
    get_type: method_descriptor = <method 'get_type' of 'dict' objects>
    getname: method_descriptor = <method 'getname' of 'dict' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'dict' objects>
    name: getset_descriptor = <attribute 'name' of 'dict' objects>

class EPerformanceLevel(enum):
    LEVEL_0: int = 0
    LEVEL_1: int = 1
    LEVEL_2: int = 2
    LEVEL_3: int = 3
    LEVEL_4: int = 4
    LEVEL_5: int = 5
    LEVEL_HIGHEST: int = 10
    name_to_values: dict = {'LEVEL_0': 0, 'LEVEL_1': 1, 'LEVEL_2': 2, 'LEVEL_3': 3, 'LEVEL_4': 4, 'LEVEL_5': 5, 'LEVEL_HIGHEST': 10}
    value_to_names: dict = {0: 'LEVEL_0', 1: 'LEVEL_1', 2: 'LEVEL_2', 3: 'LEVEL_3', 4: 'LEVEL_4', 5: 'LEVEL_5', 10: 'LEVEL_HIGHEST'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class GameSound(enum):
    Bomb: int = 2
    CompoundBow: int = 5
    FootStep: int = 1
    Gun: int = 0
    Parachute: int = 3
    Vehicle: int = 4
    name_to_values: dict = {'Gun': 0, 'FootStep': 1, 'Bomb': 2, 'Parachute': 3, 'Vehicle': 4, 'CompoundBow': 5}
    value_to_names: dict = {0: 'Gun', 1: 'FootStep', 2: 'Bomb', 3: 'Parachute', 4: 'Vehicle', 5: 'CompoundBow'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class GunType(enum):
    AR: int = 1
    LMG: int = 4
    MR: int = 5
    NG: int = 9
    NONE: int = 0
    PT: int = 7
    RL: int = 8
    SG: int = 3
    SMG: int = 2
    SR: int = 6
    name_to_values: dict = {'NONE': 0, 'AR': 1, 'SMG': 2, 'SG': 3, 'LMG': 4, 'MR': 5, 'SR': 6, 'PT': 7, 'RL': 8, 'NG': 9}
    value_to_names: dict = {0: 'NONE', 1: 'AR', 2: 'SMG', 3: 'SG', 4: 'LMG', 5: 'MR', 6: 'SR', 7: 'PT', 8: 'RL', 9: 'NG'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class HumanoidMonsterSound(CombatAvatarMember):
    def BroadcastSoundEvent(self, sound_type, sound_pos, extra=None): ...
    def CacheSoundID(self, event_id, sound_id, sound_tag): ...
    def CheckAndGetSwitchDict(self, event_id, pos, is_3d, max_dist, notify_ai): ...
    def GetGunSoundMedia(self): ...
    def GetSwitchValue_character_action(self): ...
    def GetSwitchValue_gun_fire_state(self): ...
    def GetSwitchValue_gun_type(self): ...
    def GetSwitchValue_hit_feedback(self): ...
    def GetSwitchValue_identity(self): ...
    def GetSwitchValue_material_surface(self): ...
    def GetSwitchValue_visual(self): ...
    def HasSoundByTag(self, tag): ...
    def InitUpdateSoundCacheVar(self): ...
    def OnSyncGame3DSound(self, sound_id, extra_info={}): ...
    def OnSyncUnloadGame3DSound(self, sound_id): ...
    def OnSyncUnloadGame3DSounds(self, sound_ids): ...
    def PlayGeneralSoundEventById(self, event_id, pos=None, param_dict=None, is_3d=True, vol=1.0, gameObjectID=None, **kwargs): ...
    def PlayGunSoundEventById(self, event_id, direction=None, force_switch_dict=None): ...
    def PlayHitSoundEvent(self, caster_id, sound_result, vol=1.0): ...
    def SetSoundParameterByTag(self, tag, name, value): ...
    def StopSoundByTag(self, tag): ...
    def TickUpdateSoundCache(self): ...
    def UnLoadEventByEventKey(self, eventKey): ...
    def UpdateHeartbeatSound(self, hp, old_hp): ...
    @property
    def show_game_sound(self): ...
class Int(object):
    convert: method_descriptor = <method 'convert' of 'int' objects>
    get_type: method_descriptor = <method 'get_type' of 'int' objects>
    getname: method_descriptor = <method 'getname' of 'int' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'int' objects>
    name: getset_descriptor = <attribute 'name' of 'int' objects>

class List(object):
    convert: method_descriptor = <method 'convert' of 'list' objects>
    get_type: method_descriptor = <method 'get_type' of 'list' objects>
    getname: method_descriptor = <method 'getname' of 'list' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'list' objects>
    name: getset_descriptor = <attribute 'name' of 'list' objects>

class ParaAvatarStage(enum):
    Cinematics: int = 1
    CloseParachute: int = 6
    Default: int = 0
    Finish: int = 9
    FreeFall: int = 3
    FreeFallWithWeapon: int = 4
    LandGround: int = 8
    OnAircraft: int = 2
    OpenParachute: int = 5
    Parachute: int = 7
    name_to_values: dict = {'Default': 0, 'Cinematics': 1, 'OnAircraft': 2, 'FreeFall': 3, 'FreeFallWithWeapon': 4, 'OpenParachute': 5, 'CloseParachute': 6, 'Parachute': 7, 'LandGround': 8, 'Finish': 9}
    value_to_names: dict = {0: 'Default', 1: 'Cinematics', 2: 'OnAircraft', 3: 'FreeFall', 4: 'FreeFallWithWeapon', 5: 'OpenParachute', 6: 'CloseParachute', 7: 'Parachute', 8: 'LandGround', 9: 'Finish'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class PlayerCombatAvatarMember(CombatAvatarMember):
    def AddSoundTipsBanReason(self, reason): ...
    def BroadcastSoundEvent(self, sound_type, sound_pos, extra=None): ...
    def CacheSoundID(self, event_id, sound_id, sound_tag): ...
    def CheckAndGetSwitchDict(self, event_id, pos, is_3d, max_dist, notify_ai): ...
    def GetGunSoundMedia(self): ...
    def GetSwitchValue_character_action(self): ...
    def GetSwitchValue_gun_fire_state(self): ...
    def GetSwitchValue_gun_type(self): ...
    def GetSwitchValue_hit_feedback(self): ...
    def GetSwitchValue_identity(self): ...
    def GetSwitchValue_material_surface(self): ...
    def GetSwitchValue_visual(self): ...
    def HasSoundByTag(self, tag): ...
    def InitUpdateSoundCacheVar(self): ...
    def OnChangeSpecWeaponForUpdateSoundCache(self, guid, old=''): ...
    def OnChangeWeaponForUpdateSoundCache(self, guid, old=''): ...
    def OnSyncGame3DSound(self, sound_id, extra_info={}): ...
    def OnSyncUnloadGame3DSound(self, sound_id): ...
    def OnSyncUnloadGame3DSounds(self, sound_ids): ...
    def PlayGeneralSoundEventById(self, event_id, pos=None, param_dict=None, is_3d=True, vol=1.0, gameObjectID=None, **kwargs): ...
    def PlayGunSoundEventById(self, event_id, direction=None, force_switch_dict=None): ...
    def PlayHitSoundEvent(self, caster_id, sound_result, vol=1.0): ...
    def RemoveSoundTipsBanReason(self, reason): ...
    def SetSoundParameterByTag(self, tag, name, value): ...
    def StopSoundByTag(self, tag): ...
    def SyncGame3DSound(self, sound_id, extra_info={}): ...
    def SyncUnloadGame3DSound(self, sound_id): ...
    def SyncUnloadGame3DSounds(self, *sound_ids): ...
    def TickUpdateSoundCache(self): ...
    def UnLoadEventByEventKey(self, eventKey): ...
    def UpdateHeartbeatSound(self, hp, old_hp): ...
    @property
    def show_game_sound(self): ...
class SoundNoticeMode(enum):
    HUD: int = 2
    MINIMAP: int = 1
    name_to_values: dict = {'MINIMAP': 1, 'HUD': 2}
    value_to_names: dict = {1: 'MINIMAP', 2: 'HUD'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class defaultdict(dict):
    clear: method_descriptor = <method 'clear' of 'dict' objects>
    copy: method_descriptor = <method 'copy' of 'collections.defaultdict' objects>
    default_factory: member_descriptor = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys: builtin_function_or_method = <built-in method fromkeys of type object at 0x702850e7d8>
    get: method_descriptor = <method 'get' of 'dict' objects>
    items: method_descriptor = <method 'items' of 'dict' objects>
    keys: method_descriptor = <method 'keys' of 'dict' objects>
    pop: method_descriptor = <method 'pop' of 'dict' objects>
    popitem: method_descriptor = <method 'popitem' of 'dict' objects>
    setdefault: method_descriptor = <method 'setdefault' of 'dict' objects>
    update: method_descriptor = <method 'update' of 'dict' objects>
    values: method_descriptor = <method 'values' of 'dict' objects>


def rpc_method(rpctype, *types): ...

