# module: gclient.framework.models.model_cache

import MHelper
import Timer
import six2

class EntityCacheManager(Singleton):
    def Dequeue(self, key): ...
    def Destroy(): ...
    def Enqueue(self, key, entity): ...
    def OnDestroy(self): ...
    def Show(self): ...
    def Start(self, world): ...
    def Stop(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class LogManager(object):
    asyncwrite: bool = False
    created_modules: set = {'CombatAvatarSquadFight', 'GameLogicRookieGuide', 'ReplayGameLogicSniperMode', 'RobotCombatAvatarNowhere', 'BaitBombField', 'ClientAreaEntity', 'ReplayCombatAvatarSniperMode', 'CombatTeamEntity_SquadFight', 'AttachScoutArrowEntity', 'bhttp_client.BHttpClient', 'AdsShield', 'BaseSupply', 'CombatAvatarMobaZombie', 'IceWallField', 'ClientSpace', 'CombatTeamEntity_BigHead', 'PlayerCombatAvatarPlacement', 'ControlTargetBase', 'RepelBomb', 'Formula', 'GameLogicNowhere', 'ReplayRoomGameLogicSquadFight', 'VehicleCannon', 'HumanoidMonsterMonsterAI', 'ReconDrone', 'CombatAvatar', 'RobotCombatAvatarMoba', 'PlayerCombatAvatarSniperMode', 'CombatAvatarMobaFirst', 'PlayerCombatAvatarHotSpotBase', 'EnergyStronghold', 'Bomb', 'Preload', 'GameLogicBigHead', 'GrenadeLauncherBomb', 'LeadWayEntity', 'ReplayCombatAvatarShootingRange', 'GameLogicGrandTheft', 'ReplayGameLogicMobaZombie', 'PlayerCombatAvatarSquadFightBase', 'Shop', 'MovingPlatformTelpher', 'ClientEntity', 'HelenRobotCombatAvatarMoba', 'SuicideDrone', 'ThermiteBomb', 'PhyBall', 'ReplayCombatAvatarMoba', 'FireWallField', 'RobotCombatAvatarRookieGuideNew', 'PlayerCombatAvatarRookieGuideNew', 'ReplayCombatAvatarSquadFight', 'ReplayDummy', 'TrackBomb', 'AmmoBox', 'CombatAvatarPlacement', 'Supply', 'asynctimer', 'PlayerAvatar', 'ServerUtil', 'PlayerCombatAvatar', 'RobotCombatAvatarShootingRange', 'StropEntity', 'CombatAvatarBigHead', 'CureUav', 'HelenRobotCombatAvatarNoWhere', 'SearchContractBox', 'RobotCombatAvatarMobaZombieAi', 'InteractionEntity', 'NewCrystalMonster', 'CombatTeamEntity_Moba', 'SaveMachine', 'ReplayCombatAvatarMobaZombie', 'NavigateCannon', 'ATM', 'RobotCombatAvatarBigHead', 'SatellitePlaceItem', 'Arrow', 'RestrictWall', 'WaterSnare', 'CDrone', 'Vehicle', 'MonsterCommon', 'OccupyContractTarget', 'ScoutField', 'Helicopter', 'HolographicRobotMoba', 'ReplayGameLogicPlacement', 'TrackTrapBomb', 'HolographicRobot', 'CombatAvatarShootingRange', 'ReplayGameLogicGrandTheft', 'Pubsub', 'Space', 'ReplayGameLogicNowhere', 'CombatAvatarMobaFirstNew', 'GameLogicRookieGuideNew', 'CombatAvatarGrandTheft', 'PlayerCombatAvatarMobaZombie', 'Account', 'PlayerCombatAvatarNowhere', 'ValDrone', 'CombatAvatarHotSpot', 'DeathBoxDummyEntity', 'CombatAvatarGunFight', 'CrystalMonster', 'Airdrop', 'ReplayRoomGameLogicMoba', 'RobotCombatAvatarMobaFirstNew', 'GateClient', 'MoveFireWall', 'Oilbox', 'ScoutTotemField', 'NewMonsterCommon', 'RPGMissile', 'SafeBox', 'RobotCombatAvatarATMGuard', 'RobotCombatAvatarMobaZombie', 'PlayerCombatAvatarClientOffline', 'ReplayCombatAvatar', 'PlayerEntity', 'ChaosUAV', 'SyncTransEntity', 'ReplayCombatAvatarGunFight', 'BigHeadCalculationDoll', 'DestructibleCollections', 'ScoutArrow', 'GameLogicSquadFight', 'MovingShield', 'CombatAvatarHotSpotBase', 'FreeviewDummyEntity', 'RobotCombatAvatarSniperMode', 'GameLogicPlacement', 'RobotCombatAvatarGrandTheft', 'CombatAvatarSquadFightBase', 'ActivityItem', 'ReplayRoomGameLogicBase', 'Missile', 'MonsterAI', 'CalculationDoll', 'MonitorMissile', 'AsioServerProxy', 'PlayerCombatAvatarHotSpot', 'Stronghold', 'GameLogicShootingRange', 'PlayerCombatAvatarGrandTheft', 'CombatAvatarGunFightBase', 'KcpClient', 'RobotCombatAvatarSquadFight', 'ReplayRoomGameLogicBigHead', 'ClientEnv', 'CombatTeamEntity_GunFight', 'ReplayCombatAvatarMobaFirstNew', 'ThroughBomb', 'ReplayCombatAvatarHotSpot', 'GameLogicMobaZombie', 'GameLogicGunFight', 'Building', 'mobilerpc.SimpleAsyncBHTTPClient', 'DummyCombatAvatar', 'ReplayGameLogicGunFight', 'ReplayCombatAvatarNowhere', 'ExplodingArrowEntity', 'RobotCombatAvatarHotSpot', 'NinjaBeacon', 'ReplayCombatAvatarGrandTheft', 'BarrieCannon', 'ReplayRoomGameLogicMobaZombie', 'CombatTeamEntity_ShootingRange', 'ReplayGameLogicMobaFirst', 'TrackBomb2025', 'PlayerCombatAvatarGunFightBase', 'CombatItemEntity', 'GameLogicMoba', 'CombatAvatarMoba', 'PlayerCombatAvatarShootingRange', 'RobotCombatAvatarRookieGuide', 'GameLogicClientOffline', 'PlayerCombatAvatarRookieGuide', 'CombatAvatarRookieGuideNew', 'Crow', 'Entity', 'MagicField', 'PlayerCombatAvatarSquadFight', 'AircraftPlane', 'Model', 'RpcIndexer', 'SpaceSnare', 'PlayerCombatAvatarMoba', 'PlaceEntity', 'SaveDrone', 'ReplayGameLogicHotSpot', 'PlayerCombatAvatarBigHeadBase', 'AvatarEntity', 'PortableShop', 'ReplayGameLogicShootingRange', 'CommonMoveItem', 'ShockField', 'ClueBox', 'VehicleAirplane', 'CombatTeamEntity_GrandTheft', 'AsioGateClient', 'FollowShieldMagicField', 'BigHeadMostKillDummyEntity', 'ReplayGameLogicBase', 'SamuraiBlockField', 'ReplayGameLogicMoba', 'CombatTeamEntity_Nowhere', 'ModelCache', 'CombatAvatarBigHeadBase', 'CombatTeamEntity_SniperMode', 'ReplayCombatAvatarMobaFirst', 'PlayerCombatAvatarMobaFirst', 'CombatTeamEntity', 'GameLogicMobaFirstNew', 'ATMGuardMonster', 'RobotCombatAvatarMobaFirst', 'SaveDroneDummyEntity', 'CombatTeamEntity_HotSpot', 'Telnet', 'GameLogicSniperMode', 'OccupyContractTargetNew', 'CombatTeamEntity_MobaZombie', 'ItemSpaceSnare', 'GameLogicBase', 'EmoteTree', 'ReplayCombatAvatarBigHead', 'CombatAvatarRookieGuide', 'ReplayRoomGameLogicSniperMode', 'CombatAvatarSniperMode', 'AttackDrone', 'StickyObjectEntity', 'ReplayGameLogicBigHead', 'SwordSpirit', 'ReplayGameLogicSquadFight', 'PlayerCombatAvatarMobaFirstNew', 'TotemField', 'PlayerCombatAvatarGunFight', 'CureUavFix', 'Doll', 'Crack', 'BlastBomb', 'ClusterBomb', 'HolographicRobotNowhere', 'GameLogicHotSpot', 'RobotCombatAvatarGunFight', 'DollLike', 'CombatAvatarNowhere', 'ReplayRoomGameLogicGunFight', 'HolographicHitTargetDummyEntity', 'server.EntityManager', 'StropUAV', 'CombatAvatarClientOffline', 'PlayerCombatAvatarBigHead', 'FollowerInteractionEntity', 'CommonItem', 'server.EntityFactory', 'ReplayGameLogicMobaFirstNew', 'GameLogicMobaFirst', 'Avatar'}
    custom_handler: NoneType = None
    log_handle: str = 'stream'
    log_level: int = 10
    log_tag: str = ''
    run_tag: str = ''
    sa_log_tag: str = ''
    sys_logger: NoneType = None

    def _create_handler(logger): ...
    def get_logger(moduleName): ...
    def get_sa_logger(): ...
    def run_message(message): ...
    def set_asyncwrite(asyncwrite): ...
    def set_custom_handler(handler): ...
    def set_log_handle(handle): ...
    def set_log_level(lv): ...
    def set_log_tag(log_tag): ...
    def set_run_tag(run_tag): ...
    def set_sa_log_tag(tag): ...

class ModelCache(Singleton):
    MODE_CACHE: int = 2
    MODE_PLANE: int = 1
    logger: Logger = <Logger ModelCache (DEBUG)>

    def AddBlackGuid(self, guid): ...
    def AddBlackModel(self, model): ...
    def Clear(self): ...
    def Destroy(): ...
    def ExtendBlackModels(self, model): ...
    def Fetch(self, done, guid, kind, resources, *args, **kwargs): ...
    def OnDestroy(self): ...
    def Push(self, guid, kind, resources, model): ...
    def SwitchMode(self, mode): ...
    def checkGuid(self, guid): ...
    def checkModel(self, model): ...
    def clearModel(self, model): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class Singleton(object):
    def Destroy(): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class defaultdict(dict):
    clear: method_descriptor = <method 'clear' of 'dict' objects>
    copy: method_descriptor = <method 'copy' of 'collections.defaultdict' objects>
    default_factory: member_descriptor = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys: builtin_function_or_method = <built-in method fromkeys of type object at 0x702850e7d8>
    get: method_descriptor = <method 'get' of 'dict' objects>
    items: method_descriptor = <method 'items' of 'dict' objects>
    keys: method_descriptor = <method 'keys' of 'dict' objects>
    pop: method_descriptor = <method 'pop' of 'dict' objects>
    popitem: method_descriptor = <method 'popitem' of 'dict' objects>
    setdefault: method_descriptor = <method 'setdefault' of 'dict' objects>
    update: method_descriptor = <method 'update' of 'dict' objects>
    values: method_descriptor = <method 'values' of 'dict' objects>


