# module: gclient.framework.models.model_decal_component

import MEngine
import MObject
import MRender
import MStruct
import MType
import Timer
import cconst
import consts
import functools
import gun_attachments_data
import gun_decal_data
import gun_decal_slot_template_data
import lobby_item_data
import six2
import time

DecalModelNameKeyDict: dict = {0: {1: ('P4v',), 2: ('P4v',), 3: ('P3v',)}, 2: {1: ('P4v', 'P5v', 'P2v'), 2: ('P4v', 'P5v', 'P2v'), 3: ('P4v',)}, 4: {1: ('P4v', 'P11v'), 2: ('P4v', 'P11v'), 3: ('P4v', 'P11v')}, 15: {1: ('P4v', 'P2v'), 2: ('P4v', 'P2v'), 3: ('P4v', 'P2v')}, 21: {1: ('P4v', 'P11v'), 2: ('P4v', 'P11v'), 3: ('P4v', 'P11v')}}
DefaultDecalModelNameKey: dict = {1: ('P4v',), 2: ('P4v',), 3: ('P3v',)}
MODEL_DECAL_POS: tuple = (-1.0, 3.0, 370.0)

class DecalConsts(object):
    BakeDelay: float = 0.0
    DestroyDelay: float = 0.1
    TaskDelay: float = 0.5

class DecalState(object):
    Baking: str = 'Baking'
    Empty: str = 'Empty'
    Loading: str = 'Loading'

class EquipCaseFactory(object):
    def Create(weapon_id, *args, **kwargs): ...

class GlobalDecalManager(object):
    CheckExpireHoldingModelTimer: NoneType = None
    CurrentTasks: dict = {}
    HoldingModels: dict = {}

    def AddHoldingModels(model_list): ...
    def CheckAllTasksLoaded(): ...
    def CheckExpireHoldingModel(): ...
    def DelHoldingModels(model_list): ...
    def IsTaskFinished(task_id): ...
    def OnTaskFinished(task_id): ...
    def OnTaskStart(task_id): ...

class GunDecalComponent(object):
    def BatchAddDecals(self, data, realtime=False): ...
    def BuildDecalBakeCameraInfo(self, slot, decal_path, rotation, offset, scale, viewMatrix): ...
    def BuildDecalBakeModelInfo(self, part_types, slot, realtime): ...
    def ClearDecal(self): ...
    def ClearParam(self): ...
    def CombineDecalBakeModelInfo(self): ...
    def CopyDecalModelData(self, decalModel): ...
    def DecalBakingEnter(self, data, realtime): ...
    def DecalBakingExit(self): ...
    def DecalChangeState(self, state, *args, **kwargs): ...
    def DecalEmptyEnter(self): ...
    def DecalEmptyExit(self): ...
    def DecalLoadingEnter(self, data, realtime=False): ...
    def DecalLoadingExit(self): ...
    def DoBatchAddDecals(self, data, realtime=False): ...
    def OnBakeSingleDecalCallback(self, holding_models, idx, task_id, result): ...
    def OnBatchBakeDecalCallback(self, ticket, taskid, result): ...
    def ProcessSeparateMeshDecal(self): ...
    def _CheckDecalBakeModelValid(self): ...
    def _RealBackingDecalTimer(self): ...
    def _TryOnBakeBackupChargerModelDecal(self): ...
    @property
    def is_decal_baking(self): ...
class IdManager(object):
    def bytes2id(bytes): ...
    def genid(): ...
    def id2bytes(uid): ...
    def id2str(uid): ...
    def is_valid_id(entityid): ...
    def str2id(string): ...


