# module: gclient.logic.cteam

import cc_util
import cdata_util
import consts
import events
import icredit
import six2
import space_data

class CArmClothes(CustomIntMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: type = <class 'int'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def on_setattr(self, key, old, new): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class CHallGunEquipment(IHallGunEquipment):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: NoneType = None
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def _on_set_equip_id(self, old): ...
    @property
    def guise_template_id(self): ...    def items(self): ...
    def keys(self): ...
    def on_setattr(self, key, old, new): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    @property
    def skin_template_id(self): ...    def update2(self, data): ...
    def values(self): ...

class CTeam(ITeam):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def CanAgreeApply(self, avtid): ...
    def CanAgreeInvite(self, inviter): ...
    def CanApply(self, avtid): ...
    def CanChangeLeader(self): ...
    def CanChangeMatchInfo(self, info): ...
    def CanInvite(self, invitee): ...
    def CanInviteMember(self, member_id, level=0): ...
    def CanJoinMember(self, level=0): ...
    def CanKickOut(self): ...
    def CanLeave(self): ...
    def CanSetReady(self): ...
    def ConvertToMatchTeam(self): ...
    def HasMemberUnlockQualifying(self): ...
    def IsAllMemberSufficientCreditScore(self): ...
    def IsAllMembersHasMaps(self): ...
    def IsAllMembersHaveAnyMaps(self): ...
    def IsAllReady(self): ...
    def IsEmpty(self): ...
    def IsFull(self): ...
    def IsMemberHaveAnyMap(self, member_id): ...
    def IsMemberHaveMaps(self, member_id): ...
    def IsTeamLeader(self, avatar_id): ...
    def SetMatchSpacenos(self, spacenos): ...
    def _initProperty(self, data): ...
    def _on_set_client_select_id(self, old, new): ...
    def _on_set_is_auto_team(self, old, new): ...
    def _on_set_leader_guid(self, old, new): ...
    def _on_set_match_mode(self, old, new): ...
    def _on_set_match_spacenos(self, old, new): ...
    def _on_set_match_state(self, old, new): ...
    def _on_set_match_type(self, old, new): ...
    def _on_set_member_dict(self, old, new): ...
    @property
    def id(self): ...    @property
    def info(self): ...    @property
    def is_leader(self): ...    def items(self): ...
    def keys(self): ...
    def on_clear(self): ...
    def on_setattr(self, key, old, new): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class CTeamMember(ITeamMember):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    key: str = 'show_qualifying_type'
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def CombatCopyMasterField(): ...
    def DBMetaData(): ...
    def FriendRankField(): ...
    def GetArmedPhotoProfile(self): ...
    def GlobalRankField(): ...
    def HasDownloadedMap(self, space_id): ...
    def PlayerCardField(): ...
    def PlayerSimpleField(): ...
    def QualifyingLevelByMatchType(self, match_type): ...
    def SearchFriendField(): ...
    def ShowModelField(): ...
    def TeamMemberField(): ...
    def Update(self, info): ...
    def ZoneField(): ...
    def _initProperty(self, data): ...
    def _onSetCardInfo(self, old): ...
    def _on_set_arm_clothes(self, old): ...
    def _on_set_card_background(self, old): ...
    def _on_set_clan_icon(self, old): ...
    def _on_set_clan_name(self, old): ...
    def _on_set_h_eid(self, old): ...
    def _on_set_hall_gun(self, old): ...
    def _on_set_hall_status(self, old): ...
    def _on_set_has_dlc_maps(self, old): ...
    def _on_set_head_frame(self, old): ...
    def _on_set_head_url(self, old): ...
    def _on_set_hero_id(self, old): ...
    def _on_set_level(self, old): ...
    def _on_set_name(self, old): ...
    def _on_set_national_flag(self, old): ...
    def _on_set_official_head(self, old): ...
    def _on_set_ready(self, old): ...
    def _on_set_show_name(self, old): ...
    def _on_set_show_qualifying_type(self, old): ...
    def _on_set_show_weapon(self, old): ...
    def items(self): ...
    def keys(self): ...
    @property
    def legend_rank(self): ...    def on_setattr(self, key, old, new): ...
    @property
    def qualifying_level(self): ...    @property
    def qualifying_score(self): ...    @property
    def rank_class(self): ...    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    @property
    def show_qualifying_level(self): ...    @property
    def show_qualifying_score(self): ...    @property
    def show_rank_class(self): ...    def update2(self, data): ...
    def values(self): ...

class CTeamMembers(ITeamMembers):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gclient.logic.cteam.CTeamMember'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def on_setattr(self, key, old, new): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class CustomIntMapType(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: type = <class 'int'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class CustomMapType(area_map):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class HallTeamEventsType(enum):
    EventTypeAutoTeam: int = 6
    EventTypeLeader: int = 1
    EventTypeMatchMode: int = 4
    EventTypeMatchType: int = 3
    EventTypeMatching: int = 5
    EventTypeMember: int = 2
    EventTypeSpaceno: int = 7
    name_to_values: dict = {'EventTypeLeader': 1, 'EventTypeMember': 2, 'EventTypeMatchType': 3, 'EventTypeMatchMode': 4, 'EventTypeMatching': 5, 'EventTypeAutoTeam': 6, 'EventTypeSpaceno': 7}
    value_to_names: dict = {1: 'EventTypeLeader', 2: 'EventTypeMember', 3: 'EventTypeMatchType', 4: 'EventTypeMatchMode', 5: 'EventTypeMatching', 6: 'EventTypeAutoTeam', 7: 'EventTypeSpaceno'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class HallTeamMemberEventsType(enum):
    EventTypeArmClothes: int = 2
    EventTypeCard: int = 8
    EventTypeDlcMaps: int = 6
    EventTypeEquipId: int = 4
    EventTypeHallStatus: int = 7
    EventTypeHeroId: int = 5
    EventTypeLevel: int = 1
    EventTypeMatchReady: int = 3
    EventTypeName: int = 7
    name_to_values: dict = {'EventTypeLevel': 1, 'EventTypeArmClothes': 2, 'EventTypeMatchReady': 3, 'EventTypeEquipId': 4, 'EventTypeHeroId': 5, 'EventTypeDlcMaps': 6, 'EventTypeHallStatus': 7, 'EventTypeName': 7, 'EventTypeCard': 8}
    value_to_names: dict = {1: 'EventTypeLevel', 2: 'EventTypeArmClothes', 3: 'EventTypeMatchReady', 4: 'EventTypeEquipId', 5: 'EventTypeHeroId', 6: 'EventTypeDlcMaps', 7: 'EventTypeName', 8: 'EventTypeCard'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class IHallGunEquipment(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: NoneType = None
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    @property
    def guise_template_id(self): ...    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    @property
    def skin_template_id(self): ...    def update2(self, data): ...
    def values(self): ...

class ITeam(ITeamBase):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def CanAgreeApply(self, avtid): ...
    def CanAgreeInvite(self, inviter): ...
    def CanApply(self, avtid): ...
    def CanChangeLeader(self): ...
    def CanChangeMatchInfo(self, info): ...
    def CanInvite(self, invitee): ...
    def CanInviteMember(self, member_id, level=0): ...
    def CanJoinMember(self, level=0): ...
    def CanKickOut(self): ...
    def CanLeave(self): ...
    def CanSetReady(self): ...
    def ConvertToMatchTeam(self): ...
    def IsAllReady(self): ...
    def IsEmpty(self): ...
    def IsFull(self): ...
    def SetMatchSpacenos(self, spacenos): ...
    def _initProperty(self, data): ...
    @property
    def id(self): ...    @property
    def info(self): ...    @property
    def is_leader(self): ...    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class ITeamMember(IPlayer):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def CombatCopyMasterField(): ...
    def DBMetaData(): ...
    def FriendRankField(): ...
    def GetArmedPhotoProfile(self): ...
    def GlobalRankField(): ...
    def PlayerCardField(): ...
    def PlayerSimpleField(): ...
    def QualifyingLevelByMatchType(self, match_type): ...
    def SearchFriendField(): ...
    def ShowModelField(): ...
    def TeamMemberField(): ...
    def Update(self, info): ...
    def ZoneField(): ...
    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    @property
    def legend_rank(self): ...    @property
    def qualifying_level(self): ...    @property
    def qualifying_score(self): ...    @property
    def rank_class(self): ...    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    @property
    def show_qualifying_level(self): ...    @property
    def show_qualifying_score(self): ...    @property
    def show_rank_class(self): ...    def update2(self, data): ...
    def values(self): ...

class ITeamMembers(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gshare.iteam.ITeamMember'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class enum(object):
    name_to_values: dict = {}
    value_to_names: dict = {}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...


def IsAvatarHasAllMaps(spaceids): ...
def IsAvatarHasAnyMaps(spaceids): ...
def Property(name, default, flag=2): ...

