# module: gclient.gamesystem.uihall.activity.combat_guide.combat_guide_util

import act_combat_guide
import activity_const
import lang
import six2
import text_message_data
import time_util
import ui_define

TIP_TYPE_COMMON: int = 0

class CommonTipsManager(object):
    _instance: CommonTipsManager = <gclient.ui.common.common_tips_node.CommonTipsManager object at 0x6f61d327d0>

    def CheckCreateListenerLayer(self): ...
    def Destroy(self): ...
    def EnableListenerLayer(self, enable): ...
    def HideCommonTips(self): ...
    def ShowCommonItemTips(self, node, item_id, tips_data=None, alignment=5, swallow_touches=True): ...
    def ShowCommonTips(self, node, data, tip_type, alignment=5, swallow_touches=True): ...
    def _CheckCreateNode(self, tip_type): ...
    def _GetNodeByTipType(self, tip_type): ...


def get_combat_guide_act_id(): ...
def get_combat_guide_act_time_desc(): ...
def get_countdown_time_str(left_time, show_countdown=True): ...
def is_old_combat_guide(act_id): ...
def need_show_combat_guide_node(): ...
def show_guide_act_desc(base_node, alignment, btn=None): ...

