# module: gclient.gameplay.logic_base.comps.comp_toplogo

import cconst
import events
import replay_util
import six2

TOPLOGO_BORDER_CSB_FILE: str = 'UIScript/node_ig_escape_hud_edgemask_2.csb'
call_until_player_ready: partial = functools.partial(<class 'gshare.decorators.call_until'>, <function <lambda> at 0x7040f72ac0>)

class CombatAvatarToplogo(ToplogoComponent):
    HAS_TOPLOGO: bool = True
    SLOT_TO_MARGIN_ICON: dict = {1: 162, 2: 163, 3: 164, 4: 165}
    TEAM_COLOR_MAP: dict = {1: 167, 2: 168, 3: 169, 4: 170}

    def AddTopLogoHiddenReason(self, hidden_reason): ...
    def AddTopLogoWidgetHiddenReason(self, reason, fade_out_time=1): ...
    def AddToplogoVisibleTick(self): ...
    def CreateBorder(self, scene_node_name, cocos_node, bias=Vec4(0.000000, 0.000000, 0.000000, 0.000000), depthEnable=True, auto_distinct=True): ...
    def CreateToplogo(self, ientity, scene_node_name, cocos_widget, depthEnable=False, auto_distinct=True): ...
    def EnemyTopLogoTimer(self): ...
    def FriendDistanceTick(self): ...
    def IsCameraHitMe(self): ...
    def IsInShowToplogoByExposeTalentDuration(self): ...
    def OnCombatAvatarHitFpsAvatar(self): ...
    def OnEnterKillMoment(self): ...
    def OnExposeEnemyIdsPop(self): ...
    def OnInfoChaos(self, new): ...
    def OnPlayerAdsStateChangedForOpacity(self, is_ads): ...
    def OnPlayerAvatarRealAdsStateChange(self, is_ads): ...
    def OnSettingHideTeammateNameChanged(self, new): ...
    def OnShowEnemyBar(self): ...
    def RefreshEmmaFriendTips(self): ...
    def RefreshEnemyArmorBar(self, old): ...
    def RefreshEnemyHpBar(self, old): ...
    def RefreshToplogo(self): ...
    def RefreshToplogoArmorBarForReplayRoom(self): ...
    def RefreshToplogoCombatState(self): ...
    def RefreshToplogoEquipWeaponForReplayRoom(self): ...
    def RefreshToplogoForReplayRoom(self): ...
    def RefreshToplogoHpBarForReplayRoom(self): ...
    def RefreshToplogoTacticalLevelForReplayRoom(self): ...
    def RefreshToplogoTeamTagForReplayRoom(self): ...
    def RefreshToplogoTitles(self): ...
    def RefreshToplogoVisibleForAircraft(self): ...
    def RefreshToplogoVisibleForCalculation(self): ...
    def RefreshToplogoVisibleForReplayRoom(self): ...
    def RefreshToplogoVisibleForSelectHero(self): ...
    def RemoveTopLogoHiddenReason(self, hidden_reason): ...
    def RemoveTopLogoWidgetHiddenReason(self, reason, fade_in_time=0.05): ...
    def RemoveToplogo(self): ...
    def RemoveToplogoVisibleTick(self): ...
    def SetEnemyTopLogoWidgetVisibleImm(self, visible): ...
    def SetOpacity(self, opacity): ...
    def SetToplogoVisible(self, fade_cb=None, fade_in=0.05, fade_out=1): ...
    def ShowBorderHelpAnim(self): ...
    def ShowEnemyBar(self): ...
    def ShowEnemyToplogo(self, value): ...
    def ShowToplogoByExposeTalent(self, duration): ...
    def TickTopologoVisible(self, dtime): ...
    def ToplogoTickForReplayRoom(self): ...
    def TransferToStateHide(self): ...
    def TryInitToplogo(self): ...
    def UpdateIsFriend(self): ...
    def _GetMyTeammateIndex(self): ...
    @property
    def toplogo_border_widget(self): ...
class NonexistentSwallower(Swallower):
class PlayerCombatAvatarToplogo(object):
    def OnInfoChaos(self, new): ...
    def OnSettingHideTeammateMarkChange(self, new): ...
    def OnSettingHideTeammateNameChanged(self, new): ...
    def RefreshTeammateToplogoTitles(self, state): ...
    def ShowTeammateBorderHelpAnim(self, teammate_id): ...

class Singleton(object):
    def Destroy(): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class TopLogoUINode(UINode):
    TIMER_COUNTER: int = 1
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddHiddenReason(self, reason): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def Destroy(self): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def InitClickSoundForUI(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _cancelLongTouch(self): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, interval, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, interval, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class ToplogoCacheManager(Singleton):
    def Dequeue(self, csb): ...
    def Destroy(): ...
    def Enqueue(self, csb, node): ...
    def OnDestroy(self): ...
    def Show(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class ToplogoComponent(object):
    def CreateBorder(self, scene_node_name, cocos_node, bias=Vec4(0.000000, 0.000000, 0.000000, 0.000000), depthEnable=True, auto_distinct=True): ...
    def CreateToplogo(self, ientity, scene_node_name, cocos_widget, depthEnable=False, auto_distinct=True): ...
    def RemoveToplogo(self): ...

class defaultdict(dict):
    clear: method_descriptor = <method 'clear' of 'dict' objects>
    copy: method_descriptor = <method 'copy' of 'collections.defaultdict' objects>
    default_factory: member_descriptor = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys: builtin_function_or_method = <built-in method fromkeys of type object at 0x702850e7d8>
    get: method_descriptor = <method 'get' of 'dict' objects>
    items: method_descriptor = <method 'items' of 'dict' objects>
    keys: method_descriptor = <method 'keys' of 'dict' objects>
    pop: method_descriptor = <method 'pop' of 'dict' objects>
    popitem: method_descriptor = <method 'popitem' of 'dict' objects>
    setdefault: method_descriptor = <method 'setdefault' of 'dict' objects>
    update: method_descriptor = <method 'update' of 'dict' objects>
    values: method_descriptor = <method 'values' of 'dict' objects>


