# module: gclient.gameplay.logic_base.comps.comp_dissolving_destroy

import MType
import cconst
import consts
import formula
import six2
import time

class EntityCreateType(enum):
    DissolveScale: int = 1
    Show: int = 2
    name_to_values: dict = {'DissolveScale': 1, 'Show': 2}
    value_to_names: dict = {1: 'DissolveScale', 2: 'Show'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class EntityDestroyType(enum):
    BreakAndDissolving: int = 2
    Delay: int = 1
    Dissolving: int = 3
    HideAndDelay: int = 0
    name_to_values: dict = {'HideAndDelay': 0, 'Delay': 1, 'BreakAndDissolving': 2, 'Dissolving': 3}
    value_to_names: dict = {0: 'HideAndDelay', 1: 'Delay', 2: 'BreakAndDissolving', 3: 'Dissolving'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class EntityDissolvingComponent(object):
    def BreakAnimAndDissolvingDestroy(self): ...
    def CancelDissolvingTimer(self): ...
    def CommonDelayDestroy(self): ...
    def DissolvingTick(self): ...
    def HideAndDelayDestroy(self): ...
    def OnBornTick(self, dt): ...
    def SetDissolvingDestroy(self): ...
    def _on_set_dissolving(self, old): ...

class PropertyMetaClass(type):
    mro: method_descriptor = <method 'mro' of 'type' objects>


def Property(name, default, flag=2): ...

