# module: gclient.gameplay.logic_base.comps.fsm_avatar_toplogo

import cconst
import functools
import random
import replay_util
import time

class EnterReason(enum):
    AttrTimesUp: int = 0
    BarsTimesUp: int = 1
    HitMeTimesUp: int = 3
    TalentShowEnemy: int = 2
    name_to_values: dict = {'AttrTimesUp': 0, 'BarsTimesUp': 1, 'TalentShowEnemy': 2, 'HitMeTimesUp': 3}
    value_to_names: dict = {0: 'AttrTimesUp', 1: 'BarsTimesUp', 2: 'TalentShowEnemy', 3: 'HitMeTimesUp'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class FSMEnemyTopLogoWidget(object):
    NAME: str = 'HitMeShowIcon'

    def CancelTick(self): ...
    def Destroy(self): ...
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...
    def GetHit(self): ...
    def OnBarsOnlyEnter(self): ...
    def OnBarsOnlyExit(self): ...
    def OnBarsOnlyTick(self): ...
    def OnHideEnter(self): ...
    def OnHideExit(self): ...
    def OnHideTick(self): ...
    def OnHitMeShowIconEnter(self): ...
    def OnHitMeShowIconExit(self): ...
    def OnHitMeShowIconTick(self): ...
    def OnIconOnlyEnter(self, reason=None): ...
    def OnIconOnlyExit(self): ...
    def OnIconOnlyPreEnter(self, attr_time=None): ...
    def OnIconOnlyPreExit(self): ...
    def OnIconOnlyPreTick(self): ...
    def OnIconOnlyTick(self): ...
    def SetEnemyTopLogoWidgetVisibleImm(self, visible): ...
    def StartTick(self): ...
    def VisibleCheckHide(self): ...
    def VisibleCheckShow(self, attr_time): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...

class FSMEnemyTopLogoWidgetKillMoment(object):
    NAME: str = 'ShowKillMoment'

    def Destroy(self): ...
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...
    def GetHit(self): ...
    def OnShowKillMomentEnter(self): ...
    def VisibleCheckHide(self): ...
    def VisibleCheckShow(self, attr_time): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...

class FiniteStateMachine(object):
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...

class StateBarsOnly(object):
    NAME: str = 'BarsOnly'

    def OnBarsOnlyEnter(self): ...
    def OnBarsOnlyExit(self): ...
    def OnBarsOnlyTick(self): ...

class StateHide(object):
    NAME: str = 'Hide'

    def OnHideEnter(self): ...
    def OnHideExit(self): ...
    def OnHideTick(self): ...

class StateHitMeShowIcon(object):
    NAME: str = 'HitMeShowIcon'

    def OnHitMeShowIconEnter(self): ...
    def OnHitMeShowIconExit(self): ...
    def OnHitMeShowIconTick(self): ...

class StateIconOnly(object):
    NAME: str = 'IconOnly'

    def OnIconOnlyEnter(self, reason=None): ...
    def OnIconOnlyExit(self): ...
    def OnIconOnlyTick(self): ...

class StateIconOnlyPre(object):
    NAME: str = 'IconOnlyPre'

    def OnIconOnlyPreEnter(self, attr_time=None): ...
    def OnIconOnlyPreExit(self): ...
    def OnIconOnlyPreTick(self): ...

class StateShowKillMoment(object):
    NAME: str = 'ShowKillMoment'

    def OnShowKillMomentEnter(self): ...

class enum(object):
    name_to_values: dict = {}
    value_to_names: dict = {}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...


def Components(*components, **kwargs): ...
def StateWrapper(cls): ...

