# module: gclient.gamesystem.entities.avatarmembers.cimp_backpack

import consts
import events
import gun_attachments_data
import gun_mod_data
import gun_type_data
import ihall_backpack
import six2
import weapon_util

CLIENT_STUB: int = 8
GunSmithBackpackGunType: dict = {1001: (1, 2, 3, 4, 5, 6), 1002: (7, 8)}

class AirdropSlotUsage(enum):
    Drop: int = 2
    Replace: int = 1
    name_to_values: dict = {'Replace': 1, 'Drop': 2}
    value_to_names: dict = {1: 'Replace', 2: 'Drop'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class AvatarMember(object):
class BackpackSlot(enum):
    ARMOR_PIECE: int = 5002
    CRACK_SCANNER: int = 5004
    EMERGENCY_NEEDLE: int = 5003
    FAKE_SLOT_1: int = 8001
    FAKE_SLOT_2: int = 8002
    LAUNCHER_WEAPON: int = 1005
    MEDICINE_1: int = 7001
    MEDICINE_2: int = 7002
    NONE: int = 0
    SKILL_WEAPON: int = 4001
    SKILL_WEAPON2: int = 4002
    SKILL_WEAPON3: int = 4003
    SUPPORT_WEAPON: int = 5001
    TACTICAL_WEAPON_1: int = 3001
    TACTICAL_WEAPON_2: int = 3002
    TALENT_1: int = 6001
    TALENT_2: int = 6002
    VICE_WEAPON: int = 1003
    WEAPON_1: int = 1001
    WEAPON_2: int = 1002
    WEAPON_3: int = 1004
    name_to_values: dict = {'NONE': 0, 'WEAPON_1': 1001, 'WEAPON_2': 1002, 'WEAPON_3': 1004, 'VICE_WEAPON': 1003, 'LAUNCHER_WEAPON': 1005, 'TACTICAL_WEAPON_1': 3001, 'TACTICAL_WEAPON_2': 3002, 'SKILL_WEAPON': 4001, 'SKILL_WEAPON2': 4002, 'SKILL_WEAPON3': 4003, 'SUPPORT_WEAPON': 5001, 'ARMOR_PIECE': 5002, 'EMERGENCY_NEEDLE': 5003, 'CRACK_SCANNER': 5004, 'MEDICINE_1': 7001, 'MEDICINE_2': 7002, 'TALENT_1': 6001, 'TALENT_2': 6002, 'FAKE_SLOT_1': 8001, 'FAKE_SLOT_2': 8002}
    value_to_names: dict = {0: 'NONE', 1001: 'WEAPON_1', 1002: 'WEAPON_2', 1004: 'WEAPON_3', 1003: 'VICE_WEAPON', 1005: 'LAUNCHER_WEAPON', 3001: 'TACTICAL_WEAPON_1', 3002: 'TACTICAL_WEAPON_2', 4001: 'SKILL_WEAPON', 4002: 'SKILL_WEAPON2', 4003: 'SKILL_WEAPON3', 5001: 'SUPPORT_WEAPON', 5002: 'ARMOR_PIECE', 5003: 'EMERGENCY_NEEDLE', 5004: 'CRACK_SCANNER', 7001: 'MEDICINE_1', 7002: 'MEDICINE_2', 6001: 'TALENT_1', 6002: 'TALENT_2', 8001: 'FAKE_SLOT_1', 8002: 'FAKE_SLOT_2'}

    def IsSkill(slot): ...
    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class CGunInfo(IGunInfo):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def GetExpByLevel(self, level): ...
    def GetExpProgressFromCurLevel(self, to_level, cur_level=0): ...
    def GetLevelAndExpLeftByExp(self, exp): ...
    def GetLevelByExp(self, exp): ...
    def GetTotalLevelUpExpByLevel(self, level): ...
    def PackSkinInfo(self): ...
    def _initProperty(self, data): ...
    def _on_set_exp_(self, old, new): ...
    def _on_set_fine_tuning_index_(self, old, new): ...
    def _on_set_fine_tuning_pre_affix_(self, old, new): ...
    def _on_set_guise_df_(self, old, new): ...
    def _on_set_guise_item_id_(self, old, new): ...
    def _on_set_guise_random_(self, old, new): ...
    def _on_set_ornament_info_(self, old, new): ...
    def _on_set_part_guise_info_(self, old, new): ...
    def _on_set_skin_df_(self, old, new): ...
    def _on_set_skin_item_id_(self, old, new): ...
    def _on_set_skin_random_(self, old, new): ...
    @property
    def equip_id(self): ...    @property
    def exp_progress(self): ...    @property
    def fine_tuning_affix(self): ...    @property
    def guise_df(self): ...    @property
    def guise_global_count(self): ...    @property
    def guise_random(self): ...    @property
    def guise_template_id(self): ...    @property
    def gun_proto(self): ...    @property
    def is_full_level(self): ...    def items(self): ...
    def keys(self): ...
    @property
    def level(self): ...    @property
    def lock(self): ...    @property
    def max_level(self): ...    def on_setattr(self, key, old, new): ...
    @property
    def ornament_item_id(self): ...    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    @property
    def skin_df(self): ...    @property
    def skin_random(self): ...    @property
    def skin_sticker(self): ...    @property
    def skin_template_id(self): ...    def update2(self, data): ...
    def values(self): ...

class CGunInfos(IGunInfos):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gclient.gamesystem.entities.avatarmembers.cimp_backpack.CGunInfo'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class CHallBackpack(IHallBackpack):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gshare.ihall_backpack.IHallEquipment'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def Add(self, equipment): ...
    def Get(self, guid): ...
    def GetByEquipId(self, equip_id): ...
    def GetByEquipId2(self, equip_id): ...
    def GetByEquipType(self, equip_type): ...
    def GetByGunId(self, gun_id): ...
    def GetByGunId2(self, gun_id): ...
    def GetBySlot(self, slot): ...
    def IsGunEquipped(self, gun_id): ...
    def IterEquippedWeapons(self, need_sort=True): yield ...
    def PackSlotInfo(self): ...
    def QueryEquipSlot(self, equip_guid): ...
    def _initProperty(self, data): ...
    def _on_set_name_(self, old, new): ...
    def items(self): ...
    def keys(self): ...
    def on_setattr(self, key, old, new): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class CHallBackpacks(IHallBackpacks):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gclient.gamesystem.entities.avatarmembers.cimp_backpack.CHallBackpack'>
    append: method_descriptor = <method 'append' of 'area_list' objects>
    assign: method_descriptor = <method 'assign' of 'area_list' objects>
    clear: method_descriptor = <method 'clear' of 'area_list' objects>
    copy: method_descriptor = <method 'copy' of 'area_list' objects>
    delete: method_descriptor = <method 'delete' of 'area_list' objects>
    extend: method_descriptor = <method 'extend' of 'area_list' objects>
    get: method_descriptor = <method 'get' of 'area_list' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_list' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_list' objects>
    insert: method_descriptor = <method 'insert' of 'area_list' objects>
    list: method_descriptor = <method 'list' of 'area_list' objects>
    pop: method_descriptor = <method 'pop' of 'area_list' objects>
    size: method_descriptor = <method 'size' of 'area_list' objects>
    slice: method_descriptor = <method 'slice' of 'area_list' objects>
    sorted: method_descriptor = <method 'sorted' of 'area_list' objects>
    update: method_descriptor = <method 'update' of 'area_list' objects>

    def IterEquippedWeapons(self, need_sort=True): yield ...

class CPartGuiseInfo(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def on_setattr(self, key, old, new): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class CShowWeapon(ShowWeapon):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def GetEquipId(skin_item_id, guise_item_id): ...
    def _initProperty(self, data): ...
    @property
    def equip_proto(self): ...    @property
    def from_warehouse(self): ...    @property
    def guise_template_id(self): ...    @property
    def gun_id(self): ...    @property
    def is_gun(self): ...    @property
    def is_melee(self): ...    def items(self): ...
    def keys(self): ...
    def on_setattr(self, key, old, new): ...
    @property
    def ornament_item_id(self): ...    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    @property
    def skin_template_id(self): ...    def update2(self, data): ...
    def values(self): ...

class CTrialEquipDict(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def on_setattr(self, key, old, new): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class CUnlockInfo(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: NoneType = None
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def on_clear(*args, **kwargs): ...
    def on_setattr(*args, **kwargs): ...
    def on_update(*args, **kwargs): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class CUnlockInfoDict(INewUnlockDict):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gclient.gamesystem.entities.avatarmembers.cimp_backpack.CUnlockInfo'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def on_clear(*args, **kwargs): ...
    def on_setattr(*args, **kwargs): ...
    def on_update(*args, **kwargs): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class CustomListType(area_list):
    IS_CUSTOM_TYPE: bool = True
    append: method_descriptor = <method 'append' of 'area_list' objects>
    assign: method_descriptor = <method 'assign' of 'area_list' objects>
    clear: method_descriptor = <method 'clear' of 'area_list' objects>
    copy: method_descriptor = <method 'copy' of 'area_list' objects>
    delete: method_descriptor = <method 'delete' of 'area_list' objects>
    extend: method_descriptor = <method 'extend' of 'area_list' objects>
    get: method_descriptor = <method 'get' of 'area_list' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_list' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_list' objects>
    insert: method_descriptor = <method 'insert' of 'area_list' objects>
    list: method_descriptor = <method 'list' of 'area_list' objects>
    pop: method_descriptor = <method 'pop' of 'area_list' objects>
    size: method_descriptor = <method 'size' of 'area_list' objects>
    slice: method_descriptor = <method 'slice' of 'area_list' objects>
    sorted: method_descriptor = <method 'sorted' of 'area_list' objects>
    update: method_descriptor = <method 'update' of 'area_list' objects>

class CustomMapType(area_map):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class Dict(object):
    convert: method_descriptor = <method 'convert' of 'dict' objects>
    get_type: method_descriptor = <method 'get_type' of 'dict' objects>
    getname: method_descriptor = <method 'getname' of 'dict' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'dict' objects>
    name: getset_descriptor = <attribute 'name' of 'dict' objects>

class FadeMergeIHallItem(IHallItem):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def AddUseDay(self, use_day): ...
    def AddUseTime(self, use_time): ...
    def DecUseTime(self, use_time): ...
    def InExpireTimeWarningPeriod(self): ...
    def IsExpireTimeWarningItem(self): ...
    def Pack(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    @property
    def _fixed_expired(self): ...    def _initComponents(self, bdict): ...
    def _initProperty(self, data): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def begin_time(self): ...    @property
    def bind_qualifying_expire_time(self): ...    @property
    def bind_qualifying_expired(self): ...    @property
    def can_disassemble(self): ...    @property
    def can_pileup(self): ...    @property
    def can_reuse(self): ...    @property
    def equip_id(self): ...    @property
    def expired(self): ...    @property
    def get_time(self): ...    @property
    def guise_id(self): ...    @property
    def gun_id(self): ...    @property
    def hangings_id(self): ...    @property
    def is_begin(self): ...    @property
    def is_bind_qualifying(self): ...    @property
    def is_experience_item(self): ...    @property
    def is_permanent(self): ...    @property
    def item_proto(self): ...    def items(self): ...
    def keys(self): ...
    @property
    def mall_id(self): ...    @property
    def mall_proto(self): ...    @property
    def melee_id(self): ...    def on_setattr(self, key, old, new): ...
    @property
    def quality(self): ...    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    @property
    def skin_id(self): ...    @property
    def skin_optic_id(self): ...    @property
    def skin_optic_part_id(self): ...    @property
    def sub_type(self): ...    def update2(self, data): ...
    def values(self): ...

class FadeMergeSubItems(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'common.classutils.CustomMapType'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class IBluePrints(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gshare.ihall_backpack.IBluePrintDict'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class IGunInfo(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def GetExpByLevel(self, level): ...
    def GetExpProgressFromCurLevel(self, to_level, cur_level=0): ...
    def GetLevelAndExpLeftByExp(self, exp): ...
    def GetLevelByExp(self, exp): ...
    def GetTotalLevelUpExpByLevel(self, level): ...
    def PackSkinInfo(self): ...
    def _initProperty(self, data): ...
    @property
    def equip_id(self): ...    @property
    def exp_progress(self): ...    @property
    def fine_tuning_affix(self): ...    @property
    def guise_df(self): ...    @property
    def guise_global_count(self): ...    @property
    def guise_random(self): ...    @property
    def guise_template_id(self): ...    @property
    def gun_proto(self): ...    @property
    def is_full_level(self): ...    def items(self): ...
    def keys(self): ...
    @property
    def level(self): ...    @property
    def lock(self): ...    @property
    def max_level(self): ...    @property
    def ornament_item_id(self): ...    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    @property
    def skin_df(self): ...    @property
    def skin_random(self): ...    @property
    def skin_sticker(self): ...    @property
    def skin_template_id(self): ...    def update2(self, data): ...
    def values(self): ...

class IGunInfos(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gshare.ihall_backpack.IGunInfo'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class IHallBackpack(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gshare.ihall_backpack.IHallEquipment'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def Add(self, equipment): ...
    def Get(self, guid): ...
    def GetByEquipId(self, equip_id): ...
    def GetByEquipId2(self, equip_id): ...
    def GetByEquipType(self, equip_type): ...
    def GetByGunId(self, gun_id): ...
    def GetByGunId2(self, gun_id): ...
    def GetBySlot(self, slot): ...
    def IsGunEquipped(self, gun_id): ...
    def IterEquippedWeapons(self, need_sort=True): yield ...
    def PackSlotInfo(self): ...
    def QueryEquipSlot(self, equip_guid): ...
    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class IHallBackpacks(CustomListType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gshare.ihall_backpack.IHallBackpack'>
    append: method_descriptor = <method 'append' of 'area_list' objects>
    assign: method_descriptor = <method 'assign' of 'area_list' objects>
    clear: method_descriptor = <method 'clear' of 'area_list' objects>
    copy: method_descriptor = <method 'copy' of 'area_list' objects>
    delete: method_descriptor = <method 'delete' of 'area_list' objects>
    extend: method_descriptor = <method 'extend' of 'area_list' objects>
    get: method_descriptor = <method 'get' of 'area_list' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_list' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_list' objects>
    insert: method_descriptor = <method 'insert' of 'area_list' objects>
    list: method_descriptor = <method 'list' of 'area_list' objects>
    pop: method_descriptor = <method 'pop' of 'area_list' objects>
    size: method_descriptor = <method 'size' of 'area_list' objects>
    slice: method_descriptor = <method 'slice' of 'area_list' objects>
    sorted: method_descriptor = <method 'sorted' of 'area_list' objects>
    update: method_descriptor = <method 'update' of 'area_list' objects>

    def IterEquippedWeapons(self, need_sort=True): yield ...

class IHallItem(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def AddUseDay(self, use_day): ...
    def AddUseTime(self, use_time): ...
    def DecUseTime(self, use_time): ...
    def InExpireTimeWarningPeriod(self): ...
    def IsExpireTimeWarningItem(self): ...
    def Pack(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    @property
    def _fixed_expired(self): ...    def _initComponents(self, bdict): ...
    def _initProperty(self, data): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def begin_time(self): ...    @property
    def bind_qualifying_expire_time(self): ...    @property
    def bind_qualifying_expired(self): ...    @property
    def can_disassemble(self): ...    @property
    def can_pileup(self): ...    @property
    def can_reuse(self): ...    @property
    def equip_id(self): ...    @property
    def expired(self): ...    @property
    def get_time(self): ...    @property
    def guise_id(self): ...    @property
    def gun_id(self): ...    @property
    def hangings_id(self): ...    @property
    def is_begin(self): ...    @property
    def is_bind_qualifying(self): ...    @property
    def is_experience_item(self): ...    @property
    def is_permanent(self): ...    @property
    def item_proto(self): ...    def items(self): ...
    def keys(self): ...
    @property
    def mall_id(self): ...    @property
    def mall_proto(self): ...    @property
    def melee_id(self): ...    def on_setattr(self, key, old, new): ...
    @property
    def quality(self): ...    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    @property
    def skin_id(self): ...    @property
    def skin_optic_id(self): ...    @property
    def skin_optic_part_id(self): ...    @property
    def sub_type(self): ...    def update2(self, data): ...
    def values(self): ...

class INewUnlockDict(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'common.classutils.CustomMapType'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class IOrnamentUseRecord(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'common.classutils.CustomMapType'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class IStickerUseRecord(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gshare.ihall_backpack.IStickerLocates'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class IUniversalGunReddot(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'common.classutils.CustomMapType'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class Int(object):
    convert: method_descriptor = <method 'convert' of 'int' objects>
    get_type: method_descriptor = <method 'get_type' of 'int' objects>
    getname: method_descriptor = <method 'getname' of 'int' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'int' objects>
    name: getset_descriptor = <attribute 'name' of 'int' objects>

class List(object):
    convert: method_descriptor = <method 'convert' of 'list' objects>
    get_type: method_descriptor = <method 'get_type' of 'list' objects>
    getname: method_descriptor = <method 'getname' of 'list' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'list' objects>
    name: getset_descriptor = <attribute 'name' of 'list' objects>

class PlayerAvatarMember(object):
    def ApplyDeathBoxSkin(self, guid): ...
    def ApplyMelee(self, item_guid, melee_random=0): ...
    def ApplyShowGunTimes(self, avatar_id, gun_id): ...
    def ArmBombSkin(self, item_id, equip_id=0): ...
    def ArmGunDiyBlueprint(self, gun_id, guise_guid, skin_guid, hangings_info, sticker, part_guise_dict, guise_random=0, skin_random=0): ...
    def ArmGunGuise(self, gun_id, guise_guid, need_publish=False, guise_random=0): ...
    def ArmGunSkin(self, gun_id, skin_guid, need_publish=False, skin_random=0): ...
    def ArmHeroSkin(self, hero_id, skin_item_id): ...
    def ArmPartGuise(self, gun_id, part_guise_dict): ...
    def BackpackAddWeaponPart(self, backpack_no, gun_id, part_id): ...
    def BackpackApplyEquip(self, backpack_no, eslot, equip_id): ...
    def BackpackApplyGun(self, backpack_no, eslot, gun_id): ...
    def BackpackApplyGunGuise(self, backpack_no, gun_id, guise_guid): ...
    def BackpackApplyGunSkin(self, backpack_no, gun_id, skin_guid): ...
    def BackpackApplyTalent(self, backpack_no, eslot, talent_id): ...
    def BackpackModifyBlueprintName(self, gun_id, index, name): ...
    def BackpackModifyName(self, backpack_no, name): ...
    def BackpackResetWeaponPart(self, backpack_no, gun_id): ...
    def BackpackSaveBluePrint(self, gun_id, part_slots, index, name, is_trial=False): ...
    def BackpackSetFavorite(self, backpack_no): ...
    def BackpackSetWeaponParts(self, backpack_no, gun_id, part_dict, ignore_unlock=False, scheme_type=0): ...
    def CanUseExpCardToUpgradeGun(self, gun_id, gun_lv_reward_list=None): ...
    def ClearGunExpChangeRecord(self): ...
    def GetAirdropSlotUsage(self, backpack_no, slot): ...
    def GetBackpackWeaponPartSlots(self, backpack_no, gun_id): ...
    def GetDisplayGunEquipment(self, gun_id): ...
    def GetGunDecalUseIndex(self, gun_id, decal_data, decal_item_id, decal_slot): ...
    def GetGunOrnamentUseIndex(self, gun_id, ornament_item_id): ...
    def GetGunSelectLastBackpack(self, gun_id, default_backpack=10): ...
    def GetOrnamentCanUseIndex(self, ornament_item_id): ...
    def GetRealGunSlotsDecalData(self, gun_id, decal_data, decal_slot, decal_item_id, decal_item_index): ...
    def GetShowBackpackByGunId(self, gun_id, default_backpack=10): ...
    def GetWeaponPartSlots(self, weapon_guid, backpack_no=0): ...
    def HasNewUnlockGun(self, gun_id): ...
    def HasNewUnlockGunPart(self, gun_id, part_id): ...
    def HasNewUnlockGunPartType(self, gun_id, part_type): ...
    def HasNewUnlockGunParts(self, gun_id): ...
    def HasNewUnlockGunSlot(self, slot): ...
    def HasNewUnlockGunSmith(self): ...
    def HasNewUnlockGunType(self, *gun_types): ...
    def HasNewUnlockSwitchButton(self, slot, gun_id): ...
    def HasUniversalGunReddot(self, gun_id, dot_type): ...
    def HasUnlockGunBlueprint(self, blueprint_id): ...
    def IsTrialWeapon(self, backpack_no, equip_id): ...
    def IsWeaponTrialEquipping(self, gun_id): ...
    def IterDisplayGunEquipments(self, need_sort=True): yield ...
    def OnGetShowGunApplyTimes(self, avatar_id, data): ...
    def OnGunExpChange(self, gun_id, exp_old, exp_new): ...
    def OnQueryGunBlueprintData(self, gun_id, gun_list): ...
    def PackBackpackGun(self, backpack_no): ...
    def PackFavoriteGun(self): ...
    def QueryGunBlueprintData(self, gun_id): ...
    def RecordGunSelectLastBackpack(self, gun_id, backpack_no): ...
    def RemoveNewUnlockGun(self, gun_id): ...
    def RemoveNewUnlockGunType(self, gun_type): ...
    def RemoveNewUnlockHall(self): ...
    def RemoveNewUnlockPart(self, gun_id, part_id): ...
    def RemoveNewUnlockPartAll(self, gun_id): ...
    def RemoveNewUnlockPartType(self, gun_id, part_type): ...
    def RemoveNewUnlockSlot(self, slot): ...
    def RemoveNewUnlockSwitch(self, slot): ...
    def RemoveUniversalGunReddot(self, gun_id, dot_type): ...
    def RemoveUnlockGunBlueprint(self, blueprint_id): ...
    def _on_set_avatar_double_exp_time(self, old): ...
    def _on_set_favorite_backpack_no(self, old): ...
    def _on_set_gun_double_exp_time(self, old): ...
    def _on_set_new_unlock_guns(self, old): ...
    def _on_set_new_unlock_hall(self, old): ...
    def _on_set_new_unlock_parts(self, old): ...
    def _on_set_show_weapon(self, old): ...

class ShowWeapon(HallShowWeapon):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def GetEquipId(skin_item_id, guise_item_id): ...
    def _initProperty(self, data): ...
    @property
    def equip_proto(self): ...    @property
    def from_warehouse(self): ...    @property
    def guise_template_id(self): ...    @property
    def gun_id(self): ...    @property
    def is_gun(self): ...    @property
    def is_melee(self): ...    def items(self): ...
    def keys(self): ...
    @property
    def ornament_item_id(self): ...    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    @property
    def skin_template_id(self): ...    def update2(self, data): ...
    def values(self): ...

class Str(object):
    convert: method_descriptor = <method 'convert' of 'str' objects>
    get_type: method_descriptor = <method 'get_type' of 'str' objects>
    getname: method_descriptor = <method 'getname' of 'str' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'str' objects>
    name: getset_descriptor = <attribute 'name' of 'str' objects>


def GetCurPlayerLocalConfig(config_name, default=None, trans_to_dict=True): ...
def IsTrialBackpack(backpack_no): ...
def OnChangeCustomBackpackName(old, new): ...
def OnGunExpUpdate(gun_id, old, new): ...
def OnUnlockPartsUpdate(*args, **kwargs): ...
def Property(name, default, flag=2): ...
def SetCurPlayerLocalConfig(config_name, value): ...
def rpc_method(rpctype, *types): ...

