# module: gclient.gamesystem.entities.avatarmembers.cimp_log

import time

class PlayerAvatarMember(object):
    def RecordGunSmithClickLogToServer(self, click_id, info=None): ...
    def RecordNewMobaFirstLogToServer(self, state, **kwargs): ...
    def RecordRookieGuideLogToServer(self, log_name, state, op): ...
    def StopGunSmithClickLogTimer(self): ...
    def TryStartGunSmithClickLogTimer(self): ...
    def UploadGunSmithClickLogToServer(self, *args): ...


