# module: gclient.gamesystem.entities.avatarmembers.cimp_gacha

import consts
import events
import functools
import gacha_data
import gacha_setting_data
import hall_ui_util
import six2
import taggeddict
import time_util
import zlib

CLIENT_STUB: int = 8
EMoneyType_ITEM: int = 5
HALLOWEEN_GACHA_ID: int = 10000
LocalConfig: _LocalConfig = <gclient.config._LocalConfig object at 0x7040bf6d50>

class BinData(object):
    convert: method_descriptor = <method 'convert' of 'bin' objects>
    get_type: method_descriptor = <method 'get_type' of 'bin' objects>
    getname: method_descriptor = <method 'getname' of 'bin' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'bin' objects>
    name: getset_descriptor = <attribute 'name' of 'bin' objects>

class CGacha(Gacha):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def GetCollectionCount(self): ...
    def IsProtoCanRoll(self, proto_id, proto): ...
    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def on_setattr(self, key, old, new): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class CGachaMgr(GachaMgr):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gclient.gamesystem.entities.avatarmembers.cimp_gacha.CGacha'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def New(self, act_id): ...
    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class ChargePopupWindow(UIWindow):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def CheckDLcExist(): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetRecoveryFunc(): ...
    def GetSceneId(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoCharge(self, btn): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnCloseBattlePassWindow(self): ...
    def OnDestroy(self): ...
    def OnFocus(self, value): ...
    def OnKeyDownEsc(self): ...
    def OnMoneyYuanbaoChange(self, yuanbao): ...
    def OnPay(self, btn): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def RefreshPcKey(self): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _GotoCharge(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _SetHallLevel(self, visible): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _cancelLongTouch(self): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class CustomMapType(area_map):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class Dict(object):
    convert: method_descriptor = <method 'convert' of 'dict' objects>
    get_type: method_descriptor = <method 'get_type' of 'dict' objects>
    getname: method_descriptor = <method 'getname' of 'dict' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'dict' objects>
    name: getset_descriptor = <attribute 'name' of 'dict' objects>

class ExchangeIdCountMap(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def on_setattr(self, key, old, new): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class Gacha(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def IsProtoCanRoll(self, proto_id, proto): ...
    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class GachaFingerWindow(UIWindow):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    LONG_TOUCH_TIME: float = 0.8
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def BuildInfo(act_id, item_add, times): ...
    def CancelLongTouchTipsTimer(self): ...
    def CheckAndStartPlay(self): ...
    def CheckDLcExist(): ...
    def CheckFignerWindowShow(self): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableFingerTouch(self, enable): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetOpenBoxEffectId(self): ...
    def GetPreOpenBoxEffectId(self): ...
    def GetRecoveryFunc(): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def GotoGachaReward(self): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def HideFinger(self): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSuperReward(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def LoopAndEnableTouch(self): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def OnBoxLandGround(self): ...
    def OnDestroy(self): ...
    def OnFingerCancel(self, btn): ...
    def OnFingerClick(self, btn): ...
    def OnFingerClickBegin(self, btn): ...
    def OnFingerLongTouch(self, btn): ...
    def OnFocus(self, value): ...
    def OnKeyDownEsc(self): ...
    def OnLevelLoaded(self, level_id): ...
    def OnModelLoad(self): ...
    def OnPass(self, btn): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def OpenBoxFinally(self): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayBoxEffect(self, effect_id): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def RefreshPcKey(self): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowFinger(self): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowLongTouchTips(self): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def StopPressingSound(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _HideFinger(self): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _LoopFinger(self): ...
    def _MakeSureAction(self): ...
    def _OnFingerKeyUp(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _SetHallLevel(self, visible): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _UnLockFinger(self): ...
    def _cancelLongTouch(self): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class GachaFreeState(enum):
    Free: int = 2
    No: int = 1
    Wait: int = 3
    name_to_values: dict = {'No': 1, 'Free': 2, 'Wait': 3}
    value_to_names: dict = {1: 'No', 2: 'Free', 3: 'Wait'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class GachaMgr(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    VALUE_TYPE: CustomMapTypeMetaClass = <class 'gshare.igacha.Gacha'>
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def New(self, act_id): ...
    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class GachaRewardComp(HallCommonRewardComp):
    AUTO_OUT_ANIM: NoneType = None
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    ITEM_MARGIN_HORIZON: int = 10
    ITEM_MARGIN_VERTICAL: int = 10
    NUM_PER_LINE: int = 5
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def BuildInfo(reward_mode, reward_data, act_id, open_func, show_tips=False, times=1, free_times=0, close_func=None): ...
    def CheckDLcExist(): ...
    def CheckHiddenAction(self): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseCallback(self): ...
    def CloseHallBestReward(self, _): ...
    def CloseInst(): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def CreateListviewH(self, children): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetRecoveryFunc(): ...
    def GetSceneIds(self): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GetZOrder(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GoToGacha(self, _): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideBeforeReshow(self): ...
    def InitClickSoundForUI(self): ...
    def InitData(self): ...
    def InitNode(self): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def MergeReward(self): ...
    def OnCaptureSharePicture(self, res): ...
    def OnChangeHarvest(self, _): ...
    def OnCheckBox(self, name, is_selected): ...
    def OnClickPanelTouch(self, _): ...
    def OnClickShowContinue(self, btn): ...
    def OnCloseWindow(self, btn=None): ...
    def OnDestroy(self): ...
    def OnFinishOneByOneAnim(self): ...
    def OnFocus(self, value): ...
    def OnGotoCharge(self): ...
    def OnGotoOpenWindow(self, btn): ...
    def OnHeroShowClose(self): ...
    def OnKeyDownEsc(self): ...
    def OnOpen(self, btn=None): ...
    def OnOpenBox(self, btn): ...
    def OnPass(self, btn): ...
    def OnTaskInfoChanged(self, act_id, task_id): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PlayOneByOneAnim(self): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def ReadjustBtnPosition(self): ...
    def ReadjustListItemPositionX(self): ...
    def RefreshData(self): ...
    def RefreshGachaBtn(self): ...
    def RefreshListviewV(self, irange): ...
    def RefreshNormalBtn(self): ...
    def RefreshPcKey(self): ...
    def RefreshRollNocycleBtn(self): ...
    def RefreshSPData(self): ...
    def RefreshTitle(self): ...
    def RefreshUI(self): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemoveStoryTick(self, func): ...
    def ResetData(self): ...
    def RetainWidget(self, widget): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowBestRewardCtrl(self): ...
    def ShowHeroGetRewardCtrl(self): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowNext(self): ...
    def ShowNodeHoverImage(self, visible): ...
    def StopAnim(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _SetHallLevel(self, visible): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _ShowNextRewardOneByOne(self): ...
    def _ShowRewardOneByOne(self, idx): ...
    def _cancelLongTouch(self): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _show_node_hover(self, node, visible): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class Int(object):
    convert: method_descriptor = <method 'convert' of 'int' objects>
    get_type: method_descriptor = <method 'get_type' of 'int' objects>
    getname: method_descriptor = <method 'getname' of 'int' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'int' objects>
    name: getset_descriptor = <attribute 'name' of 'int' objects>

class LimitCall(object):
class List(object):
    convert: method_descriptor = <method 'convert' of 'list' objects>
    get_type: method_descriptor = <method 'get_type' of 'list' objects>
    getname: method_descriptor = <method 'getname' of 'list' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'list' objects>
    name: getset_descriptor = <attribute 'name' of 'list' objects>

class PlayerAvatarMember(object):
    def BuyGacha(self, gacha_setting_id, times, callback): ...
    def CheckGachaFreeState(self, gacha_id): ...
    def GachaSpecEndTimeHotfix(self, encode_str): ...
    def GetGachaExchangeCount(self, gacha_id, index): ...
    def GetGachaFreeState(self, gacha_id): ...
    def GetGachaRollCount(self, gacha_id): ...
    def IsGachaCollectionUnlock(self, gacha_id): ...
    def OnGachaRoll(self, act_id, item_add, extra): ...
    def OnGachaRollSkipAnim(self, act_id, item_add, extra): ...
    def OnGachaRollToken(self, act_id, item_add, extra): ...
    def OnGachaV6Roll(self, act_id, item_add, extra): ...
    def PopGachaTokenReward(self): ...
    def PreCheckEnoughMoney(self, money_info): ...
    def ReceiveMileReward(self, gacha_id): ...
    def StartCheckFreeState(self): ...

class ProtoIdCountMap(CustomMapType):
    IS_CUSTOM_TYPE: bool = True
    clear: method_descriptor = <method 'clear' of 'area_map' objects>
    copy: method_descriptor = <method 'copy' of 'area_map' objects>
    dict: method_descriptor = <method 'dict' of 'area_map' objects>
    dsize: method_descriptor = <method 'dsize' of 'area_map' objects>
    get: method_descriptor = <method 'get' of 'area_map' objects>
    get_owner: method_descriptor = <method 'get_owner' of 'area_map' objects>
    get_parent: method_descriptor = <method 'get_parent' of 'area_map' objects>
    iteritems: method_descriptor = <method 'iteritems' of 'area_map' objects>
    iterkeys: method_descriptor = <method 'iterkeys' of 'area_map' objects>
    itervalues: method_descriptor = <method 'itervalues' of 'area_map' objects>
    normal_iteritems: method_descriptor = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys: method_descriptor = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues: method_descriptor = <method 'normal_itervalues' of 'area_map' objects>
    pop: method_descriptor = <method 'pop' of 'area_map' objects>
    props_all: method_descriptor = <method 'props_all' of 'area_map' objects>
    size: method_descriptor = <method 'size' of 'area_map' objects>
    total_size: method_descriptor = <method 'total_size' of 'area_map' objects>
    update: method_descriptor = <method 'update' of 'area_map' objects>
    weak_dict: method_descriptor = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...
    def items(self): ...
    def keys(self): ...
    def on_setattr(self, key, old, new): ...
    def setdefault(self, key, default): ...
    def show_memory_status(self): ...
    def update2(self, data): ...
    def values(self): ...

class RewardMode(enum):
    Common: int = 1
    Gacha: int = 2
    RollNocycleCommon: int = 4
    name_to_values: dict = {'Common': 1, 'Gacha': 2, 'RollNocycleCommon': 4}
    value_to_names: dict = {1: 'Common', 2: 'Gacha', 4: 'RollNocycleCommon'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...


def BuyGachaFadeInCb(act_id, item_add, times): ...
def GetMoneyDictByGachaSettingData(gacha_setting_proto, times, use_special_icon=True): ...
def Property(name, default, flag=2): ...
def rpc_method(rpctype, *types): ...

