# module: gclient.gameplay.logic_base.equips.lefthand_case

import bomb_skin_data
import cconst
import equip_data
import events
import lobby_item_data
import unit_model_data
import weapon_data
import weapon_util

class EquipmentType(enum):
    ARMOR: int = 15
    COIN_TOOLS: int = 21
    CRACK_SCANNER: int = 20
    EMERGENCY_NEEDLE: int = 16
    GRENADE_LAUNCHER: int = 5
    GUN: int = 1
    GUN_MELEE: int = 3
    INVISIBLE: int = 19
    INVISIBLE2: int = 22
    MEDICINE: int = 17
    MELEE: int = 2
    NONE: int = 0
    NORMAL_TACTICAL: int = 18
    SKILL: int = 13
    SP_GUN: int = 4
    SP_SKILL: int = 23
    SUPPORT: int = 14
    THROWABLE_WEAPON_LEFT: int = 12
    THROWABLE_WEAPON_RIGHT: int = 11
    name_to_values: dict = {'NONE': 0, 'GUN': 1, 'MELEE': 2, 'GUN_MELEE': 3, 'SP_GUN': 4, 'GRENADE_LAUNCHER': 5, 'THROWABLE_WEAPON_RIGHT': 11, 'THROWABLE_WEAPON_LEFT': 12, 'SKILL': 13, 'SUPPORT': 14, 'ARMOR': 15, 'EMERGENCY_NEEDLE': 16, 'MEDICINE': 17, 'NORMAL_TACTICAL': 18, 'INVISIBLE': 19, 'CRACK_SCANNER': 20, 'COIN_TOOLS': 21, 'INVISIBLE2': 22, 'SP_SKILL': 23}
    value_to_names: dict = {0: 'NONE', 1: 'GUN', 2: 'MELEE', 3: 'GUN_MELEE', 4: 'SP_GUN', 5: 'GRENADE_LAUNCHER', 11: 'THROWABLE_WEAPON_RIGHT', 12: 'THROWABLE_WEAPON_LEFT', 13: 'SKILL', 14: 'SUPPORT', 15: 'ARMOR', 16: 'EMERGENCY_NEEDLE', 17: 'MEDICINE', 18: 'NORMAL_TACTICAL', 19: 'INVISIBLE', 20: 'CRACK_SCANNER', 21: 'COIN_TOOLS', 22: 'INVISIBLE2', 23: 'SP_SKILL'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class LeftHandCase(WeaponCaseBase):
    EnableLazyLoadModel: bool = False
    IsCommonSkillCase: bool = False
    IsDualMelee: bool = False
    IsMelee: bool = False
    IsWeapon: bool = False
    ammunition_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f810>
    body_equip_proto: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520c310>
    equip_proto: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520ca10>
    guise_template_data: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f610>
    is_dual_weapon: bool = False
    is_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e310>
    is_melee: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f590>
    is_own_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520eb90>
    show_guise_bullet_trace: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231a50>
    show_guise_hit_effect: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231b10>
    skin_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f5d0>
    spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e250>
    vice_spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520d250>

    def ActiveBindBomb(self, extra=None): ...
    def AddHiddenReason(self, reason): ...
    def AddWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def AttachWeaponToAvatarBack(self): ...
    def AttachWeaponToAvatarHand(self): ...
    def AttachWeaponToHandAnimWeapon(self): ...
    def AttachWeaponToHandBack(self): ...
    def AttachWeaponToHandEquip(self): ...
    def AttachWeaponToLeftHand(self): ...
    def AttachWeaponToRightHand(self): ...
    def BanSamuraiSmoothSwitchOnce(self): ...
    def ChangeWeaponGuise(self, guise_id): ...
    def ChangeWeaponSkin(self, skin_id): ...
    def CheckIfQuickRaise(self, old_weapon_guid): ...
    def ClearGuiseItemCache(self): ...
    def ClearTrailEffectList(self, effect_list, fadeout=0, is_lefthand=False): ...
    def DeActiveBindBomb(self): ...
    def Destroy(self): ...
    def DisablePrincipleRole(self): ...
    def DropWeapon(self): ...
    def DropWeaponForAvatar(self): ...
    def ForceAttachWeaponToHandAnimWeapon(self): ...
    def ForceAttachWeaponToLeftHand(self): ...
    def ForceAttachWeaponToRightHand(self): ...
    def ForceDropCurWeapon(self): ...
    def ForceDropWeaponForAvatar(self): ...
    def GetDefaultMeleeEquipId(self): ...
    def GetFallDirSpeed(self): ...
    def GetGunSkinPartModelList(self, default_value=None): ...
    def GetGunType(self): ...
    def GetMeleeAttackEffectId(self, hit_pose_id): ...
    def GetMeleeCaseDlcId(self): ...
    def GetMeleeCaseDlcids(self): ...
    def GetMeleeWeaponModelId(self): ...
    def GetModelIdBySkinId(self, skin_id): ...
    def GetWeaponAttrValue(self, name, default=None): ...
    def GetWorldBound(self): ...
    def GetWorldBoundCentre(self): ...
    def InitWeapon(self, part_slots=None, part_loaded_callback=None, all_loaded_callback=None, need_refresh_prop=True, is_reload=False, extra=None): ...
    def IsAllPartsModelLoaded(self): ...
    def IsOwnerValid(self): ...
    def IsSamuraiWithSamuraiSword(self): ...
    def MarkPrincipleRole(self): ...
    def ModelAnimArmWeapon(self, model): ...
    def OnCastSpell(self): ...
    def OnCastSpellStart(self): ...
    def OnCastSpellStop(self): ...
    def OnSpellImmune(self): ...
    def OnWeaponModelLoad(self): ...
    def PlayTrailEffectList(self, effect_list, is_lefthand=False): ...
    def RaiseWeapon(self): ...
    def RaiseWeaponForAvatar(self): ...
    def RefreshGuise3PEffectInCombat(self): ...
    def RefreshGuiseEffect(self): ...
    def RefreshGuiseOverlayIdlePose(self): ...
    def RefreshGuiseSkinAnimPose(self, model, graph_id): ...
    def RefreshGuiseSkinAnimPoseForHand(self): ...
    def RefreshGuiseSkinAnimPoseForWeapon(self): ...
    def RefreshHasGuiseDlcId(self): ...
    def RefreshTpsEffectEntityVisible(self): ...
    def RefreshWeaponAttrFromCombatAttr(self, attr_name): ...
    def RefreshWeaponDecorate(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetIsAds(self, is_ads): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsInShowRoom(self, in_showroom): ...
    def SetIsLoadForWarmingUp(self, is_warmingup): ...
    def SetIsMeleeFirstRaise(self, value): ...
    def SetIsRealAds(self, is_real_ads): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetNoNearPlaneClip(self, enable): ...
    def ShowModel(self): ...
    def UseAllPartWarmingUp(self, is_warmingup): ...
    def _GetGuiseModelId(self, origin_model_id): ...
    def _SetStateRelationship(self, link=True): ...
    @property
    def is_cur_taking(self): ...    @property
    def is_destroyed(self): ...    @property
    def is_match_server(self): ...    @property
    def weapon_model(self): ...
class WeaponCaseBase(object):
    EnableLazyLoadModel: bool = False
    IsCommonSkillCase: bool = False
    IsDualMelee: bool = False
    IsMelee: bool = False
    IsWeapon: bool = False
    ammunition_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f810>
    body_equip_proto: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520c310>
    equip_proto: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520ca10>
    guise_template_data: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f610>
    is_dual_weapon: bool = False
    is_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e310>
    is_melee: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f590>
    is_own_gun: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520eb90>
    show_guise_bullet_trace: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231a50>
    show_guise_hit_effect: cached_property = <gclient.util.decorators.cached_property object at 0x6fd5231b10>
    skin_hit_object_effect_dict: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520f5d0>
    spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520e250>
    vice_spell_id: cached_property = <gclient.util.decorators.cached_property object at 0x6fd520d250>

    def ActiveBindBomb(self, extra=None): ...
    def AddHiddenReason(self, reason): ...
    def AddWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def AttachWeaponToAvatarBack(self): ...
    def AttachWeaponToAvatarHand(self): ...
    def AttachWeaponToHandAnimWeapon(self): ...
    def AttachWeaponToHandBack(self): ...
    def AttachWeaponToHandEquip(self): ...
    def AttachWeaponToLeftHand(self): ...
    def AttachWeaponToRightHand(self): ...
    def BanSamuraiSmoothSwitchOnce(self): ...
    def ChangeWeaponGuise(self, guise_id): ...
    def ChangeWeaponSkin(self, skin_id): ...
    def CheckIfQuickRaise(self, old_weapon_guid): ...
    def ClearGuiseItemCache(self): ...
    def ClearTrailEffectList(self, effect_list, fadeout=0, is_lefthand=False): ...
    def DeActiveBindBomb(self): ...
    def Destroy(self): ...
    def DisablePrincipleRole(self): ...
    def DropWeapon(self): ...
    def DropWeaponForAvatar(self): ...
    def ForceAttachWeaponToHandAnimWeapon(self): ...
    def ForceAttachWeaponToLeftHand(self): ...
    def ForceAttachWeaponToRightHand(self): ...
    def ForceDropCurWeapon(self): ...
    def ForceDropWeaponForAvatar(self): ...
    def GetDefaultMeleeEquipId(self): ...
    def GetFallDirSpeed(self): ...
    def GetGunSkinPartModelList(self, default_value=None): ...
    def GetGunType(self): ...
    def GetMeleeAttackEffectId(self, hit_pose_id): ...
    def GetMeleeCaseDlcId(self): ...
    def GetMeleeCaseDlcids(self): ...
    def GetMeleeWeaponModelId(self): ...
    def GetWeaponAttrValue(self, name, default=None): ...
    def GetWorldBound(self): ...
    def GetWorldBoundCentre(self): ...
    def InitWeapon(self, part_slots=None, part_loaded_callback=None, all_loaded_callback=None, need_refresh_prop=True, is_reload=False, extra=None): ...
    def IsAllPartsModelLoaded(self): ...
    def IsOwnerValid(self): ...
    def IsSamuraiWithSamuraiSword(self): ...
    def MarkPrincipleRole(self): ...
    def ModelAnimArmWeapon(self, model): ...
    def OnCastSpell(self): ...
    def OnCastSpellStart(self): ...
    def OnCastSpellStop(self): ...
    def OnSpellImmune(self): ...
    def OnWeaponModelLoad(self): ...
    def PlayTrailEffectList(self, effect_list, is_lefthand=False): ...
    def RaiseWeapon(self): ...
    def RaiseWeaponForAvatar(self): ...
    def RefreshGuise3PEffectInCombat(self): ...
    def RefreshGuiseEffect(self): ...
    def RefreshGuiseOverlayIdlePose(self): ...
    def RefreshGuiseSkinAnimPose(self, model, graph_id): ...
    def RefreshGuiseSkinAnimPoseForHand(self): ...
    def RefreshGuiseSkinAnimPoseForWeapon(self): ...
    def RefreshHasGuiseDlcId(self): ...
    def RefreshTpsEffectEntityVisible(self): ...
    def RefreshWeaponAttrFromCombatAttr(self, attr_name): ...
    def RefreshWeaponDecorate(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemoveWarmingUpHiddenReason(self, weapon_part_model, part_type): ...
    def SetCustomRenderSet(self, renderSet): ...
    def SetIsAds(self, is_ads): ...
    def SetIsCastDynamicShadow(self, enable): ...
    def SetIsInShowRoom(self, in_showroom): ...
    def SetIsLoadForWarmingUp(self, is_warmingup): ...
    def SetIsMeleeFirstRaise(self, value): ...
    def SetIsRealAds(self, is_real_ads): ...
    def SetIsReceiveDynamicShadow(self, enable): ...
    def SetNoNearPlaneClip(self, enable): ...
    def ShowModel(self): ...
    def UseAllPartWarmingUp(self, is_warmingup): ...
    def _GetGuiseModelId(self, origin_model_id): ...
    @property
    def is_cur_taking(self): ...    @property
    def is_destroyed(self): ...    @property
    def is_match_server(self): ...    @property
    def weapon_model(self): ...
class partial(object):
    args: member_descriptor = <member 'args' of 'functools.partial' objects>
    func: member_descriptor = <member 'func' of 'functools.partial' objects>
    keywords: member_descriptor = <member 'keywords' of 'functools.partial' objects>


def RegisterEquipCaseClass(cls): ...

