# module: gclient.gameplay.logic_base.equips.weapon_sunshine

import Timer
import equip_data
import gun_attachments_data
import gun_attachments_id_data
import gun_mod_attr_data
import gun_mod_data
import json
import os
import shoot_scatter_default_data
import six2
import weapon_attachment
import weapon_data
import weapon_util

_reload_all: bool = True

class AimPointScatterRecoverSpeed(object):
class HudFrontsightComp(UIWindow):
    AUTO_OUT_ANIM: NoneType = None
    BELONG_SCENEID: int = 4
    FOCUS_HIDDEN_REASON: tuple = ()
    HALL_LEVEL: NoneType = None
    RES_PATH: str = ''
    TIMER_COUNTER: int = 1
    WINDOW_DLC_ID: int = 0
    WINDOW_ID: int = 0
    _beginClickTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f710>
    _cd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f810>
    _cd_prompt: cached_property = <gshare.decorators.cached_property object at 0x7040f4f850>
    _cur_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f9d0>
    _enable_muti_touch_ori: cached_property = <gshare.decorators.cached_property object at 0x7040f4f8d0>
    _hidden_reason: cached_property = <gshare.decorators.cached_property object at 0x7040f4f750>
    _last_click_time: cached_property = <gshare.decorators.cached_property object at 0x7040f4f890>
    _longClickEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f6d0>
    _longTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f610>
    _longTouchTime: cached_property = <gshare.decorators.cached_property object at 0x7040f4f650>
    _multiTouchEnabled: cached_property = <gshare.decorators.cached_property object at 0x7040f4f4d0>
    _pos_began: cached_property = <gshare.decorators.cached_property object at 0x7040f4f690>
    _res_path: cached_property = <gshare.decorators.cached_property object at 0x7040f4f990>
    _zoom_action: cached_property = <gshare.decorators.cached_property object at 0x7040f4f7d0>
    click_sound_id: cached_property = <gshare.decorators.cached_property object at 0x7040f6e290>
    click_sound_id_for_ui: cached_property = <gshare.decorators.cached_property object at 0x7040f4f950>
    click_sound_init: cached_property = <gshare.decorators.cached_property object at 0x7040f4f910>
    last_touch_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa50>
    onClick: cached_property = <gshare.decorators.cached_property object at 0x7040f4f2d0>
    onClickBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f310>
    onClickCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f390>
    onClickMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f350>
    onLongTouch: cached_property = <gshare.decorators.cached_property object at 0x7040f4f3d0>
    onMouseEnter: cached_property = <gshare.decorators.cached_property object at 0x7040f4f410>
    onMouseHover: cached_property = <gshare.decorators.cached_property object at 0x7040f4f490>
    onMouseLeave: cached_property = <gshare.decorators.cached_property object at 0x7040f4f450>
    onMultiTouchBegin: cached_property = <gshare.decorators.cached_property object at 0x7040f4f510>
    onMultiTouchCancel: cached_property = <gshare.decorators.cached_property object at 0x7040f4f5d0>
    onMultiTouchEnd: cached_property = <gshare.decorators.cached_property object at 0x7040f4f590>
    onMultiTouchMove: cached_property = <gshare.decorators.cached_property object at 0x7040f4f550>
    onReddotNotify: cached_property = <gshare.decorators.cached_property object at 0x7040f4fa10>
    touch_begin_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f1d0>
    touch_cancel_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f290>
    touch_end_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f250>
    touch_move_id: cached_property = <gshare.decorators.cached_property object at 0x7040f4f210>

    def AddChild(self, child, zorder=None): ...
    def AddChildWindow(self, child_window_inst): ...
    def AddDestroyingCtrl(self, is_add): ...
    def AddHiddenReason(self, reason): ...
    def AddPointerHiddenReason(self, reason): ...
    def AddStoryTick(self, func, frames=0): ...
    def AimPointFadeIn(self, duration=0.5, need_move=True): ...
    def AimPointFadeOut(self, duration=0.5, need_move=True): ...
    def AimPointMotionMove(self, offset_x, offset_y): ...
    def AimPointScatter(self, player, shoot_idx=0): ...
    def AimPointScatterForBow(self, player, recover=False): ...
    def CacheSomeBtnOpacity(self): ...
    def CanShowCureUavHelpAlert(): ...
    def CheckAndShowSpellDroneHpAlert(self, *args): ...
    def CheckDLcExist(): ...
    def CheckDroneConnecting(self): ...
    def CheckHiddenAction(self): ...
    def CheckHideCureUavHelpAlert(self, *args): ...
    def CheckPosInView(self, pos, is_out_bounds, widget_size, visible_size, anchor=None): ...
    def CheckShowAmmoAlert(self): ...
    def ClearAutoFireAim(self): ...
    def ClearLastFrameCallFunc(self): ...
    def ClearStoryTick(self): ...
    def Close(self, _=None): ...
    def CloseDebuffPanel(self): ...
    def CloseInst(): ...
    def CloseWarnPanelMessage(self, prompt_id): ...
    def CloseWithFadeOut(self, widget=None, anim_name='out', swallow_touch=True): ...
    def Create(self, file_path, zorder=2, sceneids=(4,), parent=None): ...
    def Destroy(): ...
    def EnableClickSound(self, sound_event_id): ...
    def EnableLongClick(self, enable): ...
    def EnableLongTouch(self, enable=True, zoom_children=False): ...
    def EnableMultiTouch(self, enable=True): ...
    def EnablePressScale(self, enable, scale=0.0, origin_scale=1.0): ...
    def EnableTouch(self, enable=True, zoom_children=True): ...
    def ForceDoLayout(self): ...
    def FrameEventCallbackForSound(self, data): ...
    def GetCurrentFrame(self): ...
    def GetDlcId(): ...
    def GetEndFrame(self, anim_name): ...
    def GetHeight(self): ...
    def GetRecoveryFunc(): ...
    def GetStartFrame(self, anim_name): ...
    def GetTextureType(resource_name): ...
    def GetTotalFrame(self, anim_name): ...
    def GetWidth(self): ...
    def GetWorldPosition(self): ...
    def GetWorldPositionLeftBottom(self, offset=Vec2(0.000000, 0.000000)): ...
    def GetWorldPositionPercent(self): ...
    def GoAndKeepAnimLastFrame(self): ...
    def GotoFrameAndPlay(self, start_index, end_index=None, loop=False, callback=None, speed=1.0): ...
    def HasAnim(self, anim_name, load_action=True): ...
    def HasTouchEvent(self): ...
    def HaveHiddenReason(self, reason): ...
    def HideAutoFireAiming(self): ...
    def HideBeforeReshow(self): ...
    def HideForReasonEvent(self, reason, is_hide): ...
    def HideHitPoint(self): ...
    def HidePanelAutoFireAiming(self): ...
    def InitClickSoundForUI(self): ...
    def InitOpacityWidgets(self, widgets_list, widget_info_list, widget_pc_list=[]): ...
    def IsAncestorsVisible(self): ...
    def IsInButtonCD(self, last_click_time, now=0): ...
    def IsLongTouchTriggered(self): ...
    def IsPlayingAnim(self): ...
    def IsSwallower(self): ...
    def IsTouchValid(self, touch_id): ...
    def LoadAnimFromFile(self, filename, lazy=True): ...
    def MakeSureActionByLoadFile(self, filename=None): ...
    def NeedShowDroneHpAlert(): ...
    def OnAdsStateChange(self, is_ads): ...
    def OnArmorEnergyChange(self, key=None, old=None, new=None): ...
    def OnAutoFireAimOutOfDistance(self, out): ...
    def OnAutoFireFiring(self, enter): ...
    def OnBeFullUalScan(self, is_show): ...
    def OnChangeWeapon(self, guid, old=''): ...
    def OnDestroy(self): ...
    def OnFocus(self, value): ...
    def OnFrontsightTick(self): ...
    def OnKeyDownEsc(self): ...
    def OnMissileSpellOutOfRange(self, out, tips_enum=4): ...
    def OnMotionStateChange(self, player, pose_change=False): ...
    def OnPlayerDroneConnectStateChanged(self, connected_or_disconnected): ...
    def OnPlayerDroneStateChanged(self, created_or_destroyed): ...
    def OnPlayerLeanOutChanged(self): ...
    def OnPlayerMoveStateChange(self, speed_level): ...
    def OnPlayerParaStageChanged(self, para_stage=None): ...
    def OnPlayerPoseTypeChange(self, pose_type): ...
    def OnPlayerVehicleChanged(self): ...
    def OnSamuraiBlockChange(self, skill_start, duration): ...
    def OnShieldHealthChanged(self, shield_ent): ...
    def OnShowKillHudAnim(self, hit_part): ...
    def OnShowSpellForbid(self, value): ...
    def OnStoryTick(self, dt): ...
    def OnUIOpacityChange(self, reason, is_hide): ...
    def OnUpdateWeaponAmmo(self, guid, ammo): ...
    def OnUpdateWeaponRestAmmo(self, key, old, new): ...
    def OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def PauseAnim(self, start_frame=None, make_sure_action=True): ...
    def PauseAutoFireAim(self): ...
    def PlayAnim(self, anim_name, is_loop=False, callback=None, speed=1.0, frame_internal=0.03333333333333333): ...
    def PlayClickSoundForUI(self): ...
    def PlayFadeOutAnim(self, anim_name='out', callback=None, swallow_touch=True): ...
    def PlayHitAnim(self, hit_part): ...
    def PlayKillAnim(self, hit_part): ...
    def PointerMoveToDist(self, move_dist, pose_dist, speed, min_dist=0): ...
    def PointerSetPosAndMoveToOrigin(self, delay_time, dist, recover_speed): ...
    def PostVisible(self, value): ...
    def PreVisible(self, value): ...
    def RefreshFrontSightMode(self): ...
    def RefreshPcKey(self): ...
    def RefreshPointerBasePos(self, base_dist): ...
    def RefreshPointerVisible(self, state): ...
    def RefreshPointerVisible2(self, state): ...
    def ReleaseWidget(self, widget): ...
    def RemoveAnim(self): ...
    def RemoveHiddenReason(self, reason): ...
    def RemovePCWidget(self): ...
    def RemovePointerHiddenReason(self, reason): ...
    def RemoveStoryTick(self, func): ...
    def RetainWidget(self, widget): ...
    def SetAimVisible(self, visible): ...
    def SetCD(self, cd, cd_prompt=False): ...
    def SetChildrenClippingEnabled(self, enabled): ...
    def SetChildrenClippingType(self, clipping_type): ...
    def SetEnabled(self, is_enable): ...
    def SetFrameEventCallback(self, callback): ...
    def SetFrontsightColor(self, color): ...
    def SetHeight(self, height): ...
    def SetHiddenReason(self, value, reaseon): ...
    def SetHitPointColor(self, color): ...
    def SetLongTouchTime(self, val): ...
    def SetMouseMoveEventEnable(self, enable): ...
    def SetNodeHoverImage(self, image_id, is_scale9=False, scale9_params=None, anchor_point=None, pos=None, contentsize=None, size_offset=None): ...
    def SetPosition(self, *args): ...
    def SetPositionX(self, arg0): ...
    def SetPositionY(self, arg0): ...
    def SetVisibleForMutex(self, value): ...
    def SetVisibleForMutexImp(self, value): ...
    def SetWidth(self, width): ...
    def SetWidthHeight(self, width, height): ...
    def SetWorldPosition(self, pos): ...
    def SetWorldPositionPercent(self, percent): ...
    def Show(self, info=None): ...
    def ShowAutoFireAim(self, duration, callback): ...
    def ShowCureUavHelpAlert(self, visible): ...
    def ShowInst(show_info=None, *inst_args, **inst_kwargs): ...
    def ShowLeaveHighAreaMessage(self, prompt_id, extra_info): ...
    def ShowNodeHoverImage(self, visible): ...
    def ShowReloadLeftProgressAdd(self, state): ...
    def ShowReloadLeftProgressRemove(self, state): ...
    def ShowReloadProgressAdd(self, state): ...
    def ShowReloadProgressRemove(self, state): ...
    def StartAmmoLoading(self, duration): ...
    def StartLeftAmmoLoading(self, duration): ...
    def StopAmmoLoading(self): ...
    def StopAnim(self): ...
    def StopLeftAmmoLoading(self): ...
    def SwitchFrontSightMode(self, mode): ...
    def _AddOpacityHideReason(self, reason): ...
    def _CheckPointerHideAhead(self): ...
    def _CloseImpl(self, _=None): ...
    def _DoLayout(self, size): ...
    def _DoLayoutForCutout(self): ...
    def _DoWindowLayout(self): ...
    def _FadeOutAnimCallback(self, callback=None, cancel_swallow_touch=True): ...
    def _HaveOpacityHideReason(self, reason): ...
    def _LoadAnimFromFile(self, filename=None): ...
    def _MakeSureAction(self): ...
    def _OnWindowVisible(self, value, for_mutex=False, for_switch_scene=False): ...
    def _RemoveOpacityHideReason(self, reason): ...
    def _SetHallLevel(self, visible): ...
    def _SetOpacityForCacheWidgets(self, is_hide, opacity_factor, is_info=False, need_fade=False): ...
    def _SetOpacityForCacheWidgetsPC(self, is_hide, opacity_factor): ...
    def _SetVisible(self, value): ...
    def _ShouldAdaptCutout(self): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _cancelLongTouch(self): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_story_tick(self, dtime): ...
    def _on_timer(self, timerid): ...
    def _postComponents(self, bdict): ...
    def _show_node_hover(self, node, visible): ...
    def _tickComponents(self, dtime): ...
    def addChild(self, child, zorder=None): ...
    def add_repeat_timer(self, delay, func): ...
    def add_repeat_timer_range(self, interval, func, count, delay): ...
    def add_timer(self, delay, func): ...
    def cancel_timer(self, timerid): ...
    def child(self, name, wrapper=None): ...
    def childex(self, path, wrapper=None): ...
    @property
    def color(self): ...    def eventDispatcher(self, widget, eventtype, touchid): ...
    def getContentSize(self): ...
    @property
    def hidden_reason(self): ...    def instance(*args, **kwargs): ...
    def isInited(): ...
    def isVisible(): ...
    @property
    def is_created(self): ...    @property
    def is_destroyed(self): ...    def onLongTouched(self): ...
    def onMouseEntered(self, widget, touchid): ...
    def onMouseleft(self, widget, touchid): ...
    def onMultiTouchBegan(self, touch, event): ...
    def onMultiTouchCancelled(self, touch, event): ...
    def onMultiTouchEnded(self, touch, event): ...
    def onMultiTouchMoved(self, touch, event): ...
    def onTouchBegan(self, widget, touchid): ...
    def onTouchCancelled(self, widget, touchid): ...
    def onTouchEnded(self, widget, touchid): ...
    def onTouchMoved(self, widget, touchid): ...
    @property
    def opacity(self): ...    def rchild(self, name): ...
    def rchildex(self, path): ...
    @property
    def real_visible(self): ...    @property
    def root_widget(self): ...    def rseek(self, name): ...
    def runAction(self, action): ...
    def runZoomAction(self, scale, duration=0.05): ...
    @property
    def scale(self): ...    def seek(self, name, wrapper=None): ...
    def setContentSize(self, size): ...
    def setGrayRecursively(self, gray): ...
    def setLocalZOrder(self, localZOrder): ...
    def setVisible(self, value): ...
    def setZoomChildren(self, children): ...
    @property
    def visible(self): ...    def zoomChildren(self, bzoom): ...

class ModelPoseType(enum):
    Crouch: int = 1
    Jump: int = 2
    Ladder: int = 6
    Prone: int = 4
    Slide: int = 3
    Stand: int = 0
    Swim: int = 5
    name_to_values: dict = {'Stand': 0, 'Crouch': 1, 'Jump': 2, 'Slide': 3, 'Prone': 4, 'Swim': 5, 'Ladder': 6}
    value_to_names: dict = {0: 'Stand', 1: 'Crouch', 2: 'Jump', 3: 'Slide', 4: 'Prone', 5: 'Swim', 6: 'Ladder'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class MoveSpeedLevel(enum):
    Idle: int = 0
    Jog: int = 2
    KnockDown: int = 5
    Sprint: int = 3
    SuperSprint: int = 4
    Walk: int = 1
    name_to_values: dict = {'Idle': 0, 'Walk': 1, 'Jog': 2, 'Sprint': 3, 'SuperSprint': 4, 'KnockDown': 5}
    value_to_names: dict = {0: 'Idle', 1: 'Walk', 2: 'Jog', 3: 'Sprint', 4: 'SuperSprint', 5: 'KnockDown'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class RollShakeInfo(object):
class SunshineComponent(object):
    def OnCreateInSunshine(self, meta, data): ...
    def OnRemoveInSunshine(self): ...
    def OnSelectedInSunshine(self): ...
    def OnSunshinePropertyAdded(self, name, vals): ...
    def OnSunshinePropertyChanged(self, name, value): ...
    def OnSunshinePropertyDeleted(self, name): ...
    def OnUnselectedInSunshine(self): ...
    @property
    def rainbowPlugin(self): ...    @property
    def sunshine(self): ...
class WeaponAdsData(object):
class WeaponAimPointScatterData(object):
    def GetRealAimPointScatterRecoverSpeed(self, shoot_idx): ...

class WeaponAmmoData(object):
class WeaponAssistAimData(object):
    def OnSunshinePropertyChanged(self, name, value): ...

class WeaponCameraData(object):
class WeaponCaseSunshineComponent(SunshineComponent):
    def ChangeWeapon(self, gun_id): ...
    def LoadWeaponDataFromSunshine(self): ...
    def OnCreateInSunshine(self, meta, data): ...
    def OnRemoveInSunshine(self): ...
    def OnSelectedInSunshine(self): ...
    def OnSunshinePropertyAdded(self, name, vals): ...
    def OnSunshinePropertyChanged(self, name, value): ...
    def OnSunshinePropertyDeleted(self, name): ...
    def OnUnselectedInSunshine(self): ...
    def RefreshRecoilPlotGraphData(self): ...
    def RefreshWeapon(self): ...
    def UpdateObjectFromMetaData(self): ...
    def _on_sunshine_set_gun_id(self, new): ...
    @property
    def rainbowPlugin(self): ...    @property
    def sunshine(self): ...
class WeaponCompoundBowData(object):
class WeaponJitterData(object):
class WeaponPartProperty(object):
class WeaponPartSunshineComponent(SunshineComponent):
    def CheckPartAttrRepeated(self, idx, key): ...
    def ClearPartAttrTemplate(self): ...
    def OnCreateInSunshine(self, meta, data): ...
    def OnRemoveInSunshine(self): ...
    def OnSelectedInSunshine(self): ...
    def OnSunshineEditPropertyChanged(self, name, value): ...
    def OnSunshinePropertyAdded(self, name, vals): ...
    def OnSunshinePropertyChanged(self, name, value): ...
    def OnSunshinePropertyDeleted(self, name): ...
    def OnUnselectedInSunshine(self): ...
    def RefreshAllPartAttr(self): ...
    def RefreshPartAttr(self, attr_key, attr_value): ...
    def UpdateSunshineDataToPy(self): ...
    def _GenTemplateId(self, name, salt='0'): ...
    def _on_sunshine_set_equipped(self, new): ...
    def _on_sunshine_set_is_template(self, new): ...
    def _on_sunshine_set_part_attr_refer_id_list(self, new): ...
    def _on_sunshine_set_part_id(self, new): ...
    def _on_sunshine_set_search_field(self, new): ...
    @property
    def all_part_attr_template(self): ...    @property
    def all_part_id_dict(self): ...    @property
    def part_attr_dict(self): ...    @property
    def part_attr_id(self): ...    @property
    def rainbowPlugin(self): ...    @property
    def sunshine(self): ...
class WeaponPoseAimScatterRatioData(object):
class WeaponRecoilStateData(object):
class WeaponRollShakeData(object):
class WeaponShootData(object):
class WeaponShootScatterData(object):
class WeaponSuppressionData(object):

def GetWeaponPartIdListByType(gun_id, part_type, need_sorted=True): ...
def UpdateObject(obj, meta, data, partialUpdate=False): ...
def md5(s=None): ...
def unicode_to_utf8(d): ...

