# module: gclient.framework.camera.base_placer

class BasePlacer(object):
    Placers: dict = {}

    def DisableStoryTick(self): ...
    def EnableStoryTick(self): ...
    def GetAllPlacerTypes(): ...
    def GetPlacerType(name): ...
    def IsValid(self): ...
    def OnActive(self, info=None): ...
    def OnDeactive(self): ...
    def OnStoryTick(self, dtime): ...
    def RefreshConfig(self, config=None): ...
    def SetFocusTarget(self, target): ...
    @property
    def debug_enabled(self): ...    @property
    def target(self): ...
class StoryTick(object):
    _instance: StoryTick = <gclient.framework.util.story_tick.StoryTick object at 0x7005e37fd0>

    def Add(self, func, frames=0): ...
    def Remove(self, func): ...
    def doAdd(self, func, frames): ...
    def doRemove(self, func): ...
    def onTick(self, _, dtime): ...


