# module: gclient.framework.camera.fps_placer

import MConfig
import MEngine
import MObject
import MType
import cconst
import events
import formula
import fps_state_fsm
import grenade_burstCameraShake
import math
import six2
import switches
import sys

EPSILON: float = 2.220446049250313e-16

class CameraShakePlacerMeta(ClassMeta):
    CLASS_NAME: str = 'CameraShakePlacerObject'
    COMPONENTIZED: bool = False
    COMPONENT_META_TYPE: NoneType = None
    EDITOR_ATTRIBUTES: dict = {}
    META_TYPE: str = 'Class'
    OBJECT_VISITOR: NoneType = None
    PROPERTIES: OrderedProperties = OrderedProperties([('BurstShakeStartForSunshine', <SunshineSDK.Meta.TypeMeta.PButton object at 0x6fa4f9a2d0>), ('BurstShakeYawData', <SunshineSDK.Meta.TypeMeta.PObject object at 0x6fa4f9ad10>), ('BurstShakePitchData', <SunshineSDK.Meta.TypeMeta.PObject object at 0x6fa4f9bad0>), ('BurstShakeRollData', <SunshineSDK.Meta.TypeMeta.PObject object at 0x6fa4f9b990>)])
    VALID_EDIT_TYPES: list = ['Object', 'Unknown']

    def CreateChildObject(self, obj, key, extValue=None, partialUpdate=False): ...
    def DelChildObject(self, obj, key): ...
    def DeserializeData(self, value): ...
    def FromDict(data): ...
    def GetAllProperties(self): ...
    def GetChildMeta(self, obj, key): ...
    def GetChildObject(self, obj, key): ...
    def GetChildrenCount(self, obj): ...
    def GetComponentMeta(self, obj): ...
    def GetDefault(self): ...
    def GetDynamicEditorMeta(self, obj, bindObject=None): ...
    def GetEditType(self): ...
    def GetEditorMeta(self): ...
    def GetKeys(self, obj): ...
    def InsertRawChildObject(self, obj, key, childObj): ...
    def SerializeData(self, obj): ...
    def SetChildObject(self, obj, key, value): ...
    def SetRawChildObject(self, obj, key, childObj): ...
    def SetValue(self, parent, parentMeta, key, value): ...
    def UpdateExtraMeta(self, extraMeta): ...
    def _CreateEditorMeta(self, **kwargs): ...
    def _GetValidChildObject(self, obj, key): ...
    def _IsValidObject(self, obj): ...
    def _WarnOnNoneCollectionData(obj, childMeta, key): ...

class EnginePlacer(BasePlacer):
    Placers: dict = {}

    def BlenderInFinished(self): ...
    def CreateBlender(self, blendTime=None, blend_type=0, direct_transit=True): ...
    def DelayRestoreUseBonePosition(self): ...
    def DisableStoryTick(self): ...
    def EnableStoryTick(self): ...
    def FinishExposeProperties(self): ...
    def GetAllPlacerTypes(): ...
    def GetPlacerType(name): ...
    def IsValid(self): ...
    def OnActive(self, info=None): ...
    def OnDeactive(self): ...
    def OnStoryTick(self, dtime): ...
    def RefreshConfig(self, config=None): ...
    def SetFocusTarget(self, target): ...
    def StartExposeProperties(self): ...
    def TurnView(self, diffx, diffy, shoot_adsorb=False): ...
    def TurnViewBegin(self): ...
    def TurnViewEnd(self): ...
    def UseBonePosition(self, is_use, bone_name='Scene Root'): ...
    @property
    def debug_enabled(self): ...    @property
    def target(self): ...
class FpsPlacer(EnginePlacer):
    NAME: str = 'GraphRotate'
    Placers: dict = {}

    def ApplyCameraEasing(self): ...
    def ApplyMover(self, beginTargetPosOffset, endTargetPosOffset, beginDirection, endDirection, movetime=0.5, callback=None): ...
    def BlenderInFinished(self): ...
    def CheckCanJitter(self): ...
    def ClearReloadFovOffset(self): ...
    def CreateBlender(self, blendTime=None, blend_type=0, direct_transit=True): ...
    def DelayRestoreUseBonePosition(self): ...
    def DisableStoryTick(self): ...
    def DisableStoryTickForReplay(self): ...
    def EnableAdditiveFovOffset(self, enable): ...
    def EnableAnimationBoneOffset(self, enable): ...
    def EnableBoneFollow(self, enable, bone_name='HP_Camera'): ...
    def EnableBreatheJitter(self, enable=True): ...
    def EnablePersistRecoilRecover(self, enable=True): ...
    def EnableStoryTick(self): ...
    def EnableStoryTickForReplay(self): ...
    def FSMAppend(self, state, replace, *args, **kwargs): ...
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMClear(self): ...
    def FSMEvent(self, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMRemove(self, state): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...
    def FetchPrePlacerInfo(self): ...
    def FinishExposeProperties(self): ...
    def FixTickTime(self, last_time, cur_time, target_time): ...
    def GetAllPlacerTypes(): ...
    def GetPlacerType(name): ...
    def GraphRotate(self): ...
    def InitDebugDraw(self): ...
    def InitParameter(self): ...
    def IsValid(self): ...
    def LookAtTargetDirection(self, target_direction, pos_offset, use_time=0, callback=None): ...
    @property
    def MainFov(self): ...    @property
    def MainFovTarget(self): ...    def OnActive(self, info=None): ...
    def OnAdditiveAffiliatedFovOffsetEasingFinished(self, easeTime, easeType): ...
    def OnAdditiveFovOffsetEasingFinished(self, easeTime, easeType): ...
    def OnAffiliatedFovEasingFinished(self, easeTime, easeType): ...
    def OnAimEnter(self, is_aim=True, zoom_affiliated=True): ...
    def OnAimEvent(self, event): ...
    def OnBurstShakeEnter(self, initAmplitude_list=None, duration_list=None): ...
    def OnBurstShakeExit(self): ...
    def OnBurstShakePitchTick(self): ...
    def OnBurstShakeRollTick(self): ...
    def OnBurstShakeTick(self): ...
    def OnBurstShakeYawTick(self): ...
    def OnDeactive(self): ...
    def OnFovEasingFinished(self, easeTime, easeType): ...
    def OnGraphRotateCallback(self, easeTime, easeType): ...
    def OnGraphRotateEnter(self, target_pitch=None, target_yaw=None, graphRotateEasingType='linear', duration=0.0): ...
    def OnGraphRotateExit(self): ...
    def OnJitterEnter(self): ...
    def OnJitterExit(self): ...
    def OnJitterTick(self): ...
    def OnPlacerExpired(self, ientity): ...
    def OnRecoilDownCallback(self, easeTime, easeType): ...
    def OnRecoilEnter(self, shoot_idx=0): ...
    def OnRecoilExit(self): ...
    def OnRecoilFallCallback(self, easeTime, easeType): ...
    def OnRecoilRecoverCallback(self, easeTime, easeType): ...
    def OnRecoilRecoverEnter(self, shoot_idx=0): ...
    def OnRecoilRecoverExit(self): ...
    def OnRecoilStaticCallback(self, easeTime, easeType): ...
    def OnRecoilUpCallback(self, easeTime, easeType): ...
    def OnRefreshPitchMaxMinCallback(self, easeTime, easeType): ...
    def OnReloadAimEnter(self, is_reload_aim=False): ...
    def OnRollShakeEnter(self, shoot_idx=0): ...
    def OnRollShakeExit(self): ...
    def OnRollShakeTick(self): ...
    def OnStaticEnter(self): ...
    def OnStaticExit(self): ...
    def OnStaticTick(self): ...
    def OnStoryTick(self, dtime): ...
    def OnStoryTickForReplay(self, dtime): ...
    def OnUpdateBoneOffset(self): ...
    def OnZoomAdditiveAffiliatedFov(self): ...
    def OnZoomAdditiveFov(self): ...
    def OnZoomAffiliatedFov(self): ...
    def OnZoomFov(self): ...
    def PlotFrameTick(self): ...
    def RecoilDown(self): ...
    def RecoilFall(self): ...
    def RecoilStatic(self): ...
    def RecoilUp(self): ...
    def RefreshConfig(self, config=None): ...
    def RefreshDirectionByMaster(self): ...
    def RefreshFocusWeaponCase(self, weapon_case): ...
    def RefreshMainFovTarget(self): ...
    def RefreshPitchMaxMin(self): ...
    def RefreshRealRollShakeInfo(self, shoot_idx): ...
    def Rotate(self, yaw, pitch): ...
    def RotateTo(self, yaw, pitch, rotate_target=True): ...
    def SetAffiliatedFov(self, value): ...
    def SetBoneFollowTarget(self, animTarget): ...
    def SetFocusTarget(self, target): ...
    def SetFocusWeaponCase(self, weapon_case): ...
    def ShowRecoilDebug(self, cur_shoot_idx, cur_shoot_recoil_pitch, cur_shoot_recoil_yaw, cur_shoot_recoil_base_pitch, cur_shoot_recoil_base_yaw, cur_shoot_recoil_random_pitch, cur_shoot_recoil_random_yaw): ...
    def StartAssistAimShoot(self): ...
    def StartExposeProperties(self): ...
    def StorePrePlacerInfo(self): ...
    def TurnView(self, diffx, diffy, shoot_adsorb=False): ...
    def TurnViewBegin(self): ...
    def TurnViewEnd(self): ...
    def UseBonePosition(self, is_use, bone_name='Scene Root'): ...
    def _addComponent(component): ...
    def _callComponents(self, name, *args, **kwargs): ...
    def _delComponent(component): ...
    def _finiComponents(self): ...
    def _initComponents(self, bdict): ...
    def _on_set_RecoilDownCycleIdx(self, value): ...
    def _postComponents(self, bdict): ...
    def _tickComponents(self, dtime): ...
    @property
    def debug_enabled(self): ...    @property
    def target(self): ...
class StoryTick(object):
    _instance: StoryTick = <gclient.framework.util.story_tick.StoryTick object at 0x7005e37fd0>

    def Add(self, func, frames=0): ...
    def Remove(self, func): ...
    def doAdd(self, func, frames): ...
    def doRemove(self, func): ...
    def onTick(self, _, dtime): ...


def Components(*components, **kwargs): ...
def UpdateObject(obj, meta, data, partialUpdate=False): ...

