# module: gclient.framework.camera.fps_state_fsm

import MType
import cconst
import consts
import formula
import math
import random
import six2
import switches

LocalConfig: _LocalConfig = <gclient.config._LocalConfig object at 0x7040bf6d50>
_reload_all: bool = True

class BurstShakeData(object):
class BurstUnderdampedOscillator(object):
    def Tick(self, damp_time): ...

class DampingCurveSimulator(object):
    def ReBuild(self, easing, duration=1, amplitude=1, period=1, phase=0.0, endValue=0.0): ...
    def Reset(self): ...
    def Tick(self, damp_time): ...

class FiniteStateMachine(object):
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...

class FpsRequisite(object):
    def FixTickTime(self, last_time, cur_time, target_time): ...
    @property
    def MainFov(self): ...    @property
    def MainFovTarget(self): ...    def RefreshFocusWeaponCase(self, weapon_case): ...
    def RefreshMainFovTarget(self): ...
    def SetAffiliatedFov(self, value): ...
    def SetFocusWeaponCase(self, weapon_case): ...
    def _on_set_RecoilDownCycleIdx(self, value): ...

class FpsStateFSM(FiniteStateMachine):
    def FSMAppend(self, state, replace, *args, **kwargs): ...
    def FSMBootstrap(self, state=None, *args, **kwargs): ...
    def FSMClear(self): ...
    def FSMEvent(self, *args, **kwargs): ...
    def FSMForceTransfer(self, state, *args, **kwargs): ...
    def FSMGetHandler(self, state, stage): ...
    def FSMRemove(self, state): ...
    def FSMShutdown(self): ...
    def FSMTick(self, delta): ...
    def FSMTransfer(self, state, *args, **kwargs): ...

class JitterSimulator(object):
    def Reset(self): ...
    def Tick(self, dtime): ...

class RecoilStatus(enum):
    DOWN: int = 4
    FALL: int = 3
    NONE: int = 0
    STATIC: int = 2
    UP: int = 1
    name_to_values: dict = {'NONE': 0, 'UP': 1, 'STATIC': 2, 'FALL': 3, 'DOWN': 4}
    value_to_names: dict = {0: 'NONE', 1: 'UP', 2: 'STATIC', 3: 'FALL', 4: 'DOWN'}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class StateAim(object):
    NAME: str = 'Aim'

    def OnAffiliatedFovEasingFinished(self, easeTime, easeType): ...
    def OnAimEnter(self, is_aim=True, zoom_affiliated=True): ...
    def OnAimEvent(self, event): ...
    def OnFovEasingFinished(self, easeTime, easeType): ...
    def OnZoomAffiliatedFov(self): ...
    def OnZoomFov(self): ...

class StateBurstShake(object):
    NAME: str = 'BurstShake'

    def OnBurstShakeEnter(self, initAmplitude_list=None, duration_list=None): ...
    def OnBurstShakeExit(self): ...
    def OnBurstShakePitchTick(self): ...
    def OnBurstShakeRollTick(self): ...
    def OnBurstShakeTick(self): ...
    def OnBurstShakeYawTick(self): ...

class StateGraphRotate(object):
    NAME: str = 'GraphRotate'

    def GraphRotate(self): ...
    def OnGraphRotateCallback(self, easeTime, easeType): ...
    def OnGraphRotateEnter(self, target_pitch=None, target_yaw=None, graphRotateEasingType='linear', duration=0.0): ...
    def OnGraphRotateExit(self): ...

class StateJitter(object):
    NAME: str = 'Jitter'

    def CheckCanJitter(self): ...
    def EnableBreatheJitter(self, enable=True): ...
    def OnJitterEnter(self): ...
    def OnJitterExit(self): ...
    def OnJitterTick(self): ...

class StateRecoil(object):
    NAME: str = 'Recoil'

    def OnRecoilDownCallback(self, easeTime, easeType): ...
    def OnRecoilEnter(self, shoot_idx=0): ...
    def OnRecoilExit(self): ...
    def OnRecoilFallCallback(self, easeTime, easeType): ...
    def OnRecoilStaticCallback(self, easeTime, easeType): ...
    def OnRecoilUpCallback(self, easeTime, easeType): ...
    def RecoilDown(self): ...
    def RecoilFall(self): ...
    def RecoilStatic(self): ...
    def RecoilUp(self): ...
    def ShowRecoilDebug(self, cur_shoot_idx, cur_shoot_recoil_pitch, cur_shoot_recoil_yaw, cur_shoot_recoil_base_pitch, cur_shoot_recoil_base_yaw, cur_shoot_recoil_random_pitch, cur_shoot_recoil_random_yaw): ...
    def StartAssistAimShoot(self): ...

class StateRecoilRecover(object):
    NAME: str = 'RecoilRecover'

    def EnablePersistRecoilRecover(self, enable=True): ...
    def OnRecoilRecoverCallback(self, easeTime, easeType): ...
    def OnRecoilRecoverEnter(self, shoot_idx=0): ...
    def OnRecoilRecoverExit(self): ...

class StateReloadAim(object):
    NAME: str = 'ReloadAim'

    def ClearReloadFovOffset(self): ...
    def EnableAdditiveFovOffset(self, enable): ...
    def OnAdditiveAffiliatedFovOffsetEasingFinished(self, easeTime, easeType): ...
    def OnAdditiveFovOffsetEasingFinished(self, easeTime, easeType): ...
    def OnReloadAimEnter(self, is_reload_aim=False): ...
    def OnZoomAdditiveAffiliatedFov(self): ...
    def OnZoomAdditiveFov(self): ...

class StateRollShake(object):
    NAME: str = 'RollShake'

    def OnRollShakeEnter(self, shoot_idx=0): ...
    def OnRollShakeExit(self): ...
    def OnRollShakeTick(self): ...
    def RefreshRealRollShakeInfo(self, shoot_idx): ...

class StateStatic(object):
    NAME: str = 'Static'

    def OnStaticEnter(self): ...
    def OnStaticExit(self): ...
    def OnStaticTick(self): ...

class enum(object):
    name_to_values: dict = {}
    value_to_names: dict = {}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...

class partial(object):
    args: member_descriptor = <member 'args' of 'functools.partial' objects>
    func: member_descriptor = <member 'func' of 'functools.partial' objects>
    keywords: member_descriptor = <member 'keywords' of 'functools.partial' objects>


def Lerp(frm, to, ratio, func='linear'): ...
def StateWrapper(cls): ...

