# module: gclient.framework.camera.simple_tps_placer

import MObject
import MType
import cconst
import math
import six2

class EnginePlacer(BasePlacer):
    Placers: dict = {}

    def BlenderInFinished(self): ...
    def CreateBlender(self, blendTime=None, blend_type=0, direct_transit=True): ...
    def DelayRestoreUseBonePosition(self): ...
    def DisableStoryTick(self): ...
    def EnableStoryTick(self): ...
    def FinishExposeProperties(self): ...
    def GetAllPlacerTypes(): ...
    def GetPlacerType(name): ...
    def IsValid(self): ...
    def OnActive(self, info=None): ...
    def OnDeactive(self): ...
    def OnStoryTick(self, dtime): ...
    def RefreshConfig(self, config=None): ...
    def SetFocusTarget(self, target): ...
    def StartExposeProperties(self): ...
    def TurnView(self, diffx, diffy, shoot_adsorb=False): ...
    def TurnViewBegin(self): ...
    def TurnViewEnd(self): ...
    def UseBonePosition(self, is_use, bone_name='Scene Root'): ...
    @property
    def debug_enabled(self): ...    @property
    def target(self): ...
class SimpleTpsPlacer(EnginePlacer):
    Placers: dict = {}

    def ApplyMover(self, beginTargetPosOffset, endTargetPosOffset, beginDirection, endDirection, movetime=0.5, callback=None): ...
    def BlenderInFinished(self): ...
    def CreateBlender(self, blendTime=None, blend_type=0, direct_transit=True): ...
    def DelayRestoreUseBonePosition(self): ...
    def DisableStoryTick(self): ...
    def EnableStoryTick(self): ...
    def FinishExposeProperties(self): ...
    def GetAllPlacerTypes(): ...
    def GetPlacerType(name): ...
    def IsValid(self): ...
    def LookAtTargetDirection(self, target_direction, target_pos_offset, use_time=0, callback=None): ...
    def OnActive(self, info=None): ...
    def OnDeactive(self): ...
    def OnStoryTick(self, dtime): ...
    def RefreshConfig(self, config=None): ...
    def SetFocusTarget(self, target): ...
    def SetToDirection(self, direction): ...
    def StartExposeProperties(self): ...
    def TurnView(self, diffx, diffy, shoot_adsorb=False): ...
    def TurnViewBegin(self): ...
    def TurnViewEnd(self): ...
    def UseBonePosition(self, is_use, bone_name='Scene Root'): ...
    def _moverCallback(self): ...
    @property
    def debug_enabled(self): ...    @property
    def target(self): ...

