# module: gclient.framework.ui.widgets.ui_texture_download

import Timer
import events
import functools
import time
import ui_icon_data

class Singleton(object):
    def Destroy(): ...
    def OnDestroy(self): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class UITextureDownload(Singleton):
    def Destroy(): ...
    def OnDestroy(self): ...
    def OnDlcDownloadStatus(self, dlc_id, status): ...
    def RequestDlcTexture(self, ui_texture, tex_id): ...
    def _OnDlcDownloadLoaded(self, dlc_id): ...
    def init(self): ...
    def instance(*args, **kwargs): ...
    def isInited(): ...
    def is_destroyed(): ...

class defaultdict(dict):
    clear: method_descriptor = <method 'clear' of 'dict' objects>
    copy: method_descriptor = <method 'copy' of 'collections.defaultdict' objects>
    default_factory: member_descriptor = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys: builtin_function_or_method = <built-in method fromkeys of type object at 0x702850e7d8>
    get: method_descriptor = <method 'get' of 'dict' objects>
    items: method_descriptor = <method 'items' of 'dict' objects>
    keys: method_descriptor = <method 'keys' of 'dict' objects>
    pop: method_descriptor = <method 'pop' of 'dict' objects>
    popitem: method_descriptor = <method 'popitem' of 'dict' objects>
    setdefault: method_descriptor = <method 'setdefault' of 'dict' objects>
    update: method_descriptor = <method 'update' of 'dict' objects>
    values: method_descriptor = <method 'values' of 'dict' objects>


