# module: gclient.framework.entities.avatarmembers.cimp_gm

import MEngine
import cPickle
import consts
import json
import os
import six2
import zlib

CLIENT_STUB: int = 8

class AvatarMember(object):
class BinData(object):
    convert: method_descriptor = <method 'convert' of 'bin' objects>
    get_type: method_descriptor = <method 'get_type' of 'bin' objects>
    getname: method_descriptor = <method 'getname' of 'bin' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'bin' objects>
    name: getset_descriptor = <attribute 'name' of 'bin' objects>

class EntityID(object):
    convert: method_descriptor = <method 'convert' of 'entityid' objects>
    get_type: method_descriptor = <method 'get_type' of 'entityid' objects>
    getname: method_descriptor = <method 'getname' of 'entityid' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'entityid' objects>
    name: getset_descriptor = <attribute 'name' of 'entityid' objects>

class HttpClient(SimpleAsyncBHTTPClient):
    _callback: AsyncDescriptor = <gshare.async_util.AsyncDescriptor object at 0x7005c5fb10>
    clients: set = set()

    def http_request(self, request, timeout, callback, protocols=3): ...

class HttpRequest(BHttpRequest):
    def set_info(self, callback, timeout, ipv, expired_time, left_retry): ...

class IdManager(object):
    def bytes2id(bytes): ...
    def genid(): ...
    def id2bytes(uid): ...
    def id2str(uid): ...
    def is_valid_id(entityid): ...
    def str2id(string): ...

class PlayerAvatarMember(AvatarMember):
    def CheckAndLoopReplay(self): ...
    def GMEvalServer(self, expression, callback): ...
    def GMOnEvalServer(self, identity, result): ...
    def GMOnGetRecord(self, md5, data): ...
    def GMQueryGroundPos(self, position, callback): ...
    def GMQueryNaviValidPosition(self, position, radius, valid_pos, callback): ...
    def GmPlaybackByFilename(self, fns, on_new_file=None): ...
    def GmStartLoopPlayback(self): ...
    def GmStopLoopPlayback(self): ...
    def OnReplaySkipPlayback(self): ...
    def _LoadDataAndReplay(self, data): ...
    def _LoopReplayByFilename(self): ...
    def _Reset(self): ...

class Str(object):
    convert: method_descriptor = <method 'convert' of 'str' objects>
    get_type: method_descriptor = <method 'get_type' of 'str' objects>
    getname: method_descriptor = <method 'getname' of 'str' objects>
    getnametype: method_descriptor = <method 'getnametype' of 'str' objects>
    name: getset_descriptor = <attribute 'name' of 'str' objects>


def rpc_method(rpctype, *types): ...

