# module: gclient.gameplay.logic_base.spell.spell_util

import consts
import functools
import snare_data
import spell_data
import sys

AvatarCollisionBoneToNormalBone: dict = {'head': 'biped Head', 'uppertop': 'biped Spine', 'upperbottom': 'biped Spine', 'lower': 'biped Spine1', 'limbs_r_upperarm': 'biped R UpperArm', 'limbs_r_forearm': 'biped R Forearm', 'limbs_r_hand': 'biped R Hand', 'limbs_l_upperarm': 'biped L UpperArm', 'limbs_l_forearm': 'biped L Forearm', 'limbs_l_hand': 'biped L Hand', 'limbs_r_thigh': 'biped R Thigh', 'limbs_r_calf': 'biped R Calf', 'limbs_l_thigh': 'biped L Thigh', 'limbs_l_calf': 'biped L Calf'}
COMPONENT: str = 'Client'
GUN_SPELL_CODES: set = {'launcher_spell', 'gun_spell', 'shotgun_spell', 'dual_gun_spell'}
IdempotentCaches: dict = {'IsGunSpell': {}, 'IsShowBarSpell': {}}

class enum(object):
    name_to_values: dict = {}
    value_to_names: dict = {}

    def add_string(name, value): ...
    def from_string(name): ...
    def to_string(value): ...
    def to_values(): ...
    def values(): ...


def CanCastSpell(caster, spell_id, spell_level): ...
def CastSpell(caster, spell_id, spell_level, item_guid='', extra=None): ...
def CreateSpellInstance(caster, spell_proto, spell_level, item_guid, extra=None): ...
def GetCollisionBoneOffset(skeleton, hit_name, hit_pos): ...
def GetCollisionVerify(combat_avatar_skeleton, hit_name): ...
def GetMagicFieldProto(magic_field_id, level=1): ...
def GetSpellCode(spell_id): ...
def GetSpellProto(spell_id, level=1): ...
def GetSpellWorker(spell_id, spell_level=1): ...
def IsGunSpell(spell_id): ...
def IsShowBarSpell(spell_id): ...
def OnSpellReady(caster, spell_id): ...
def OnSpellStrike(caster, spell_id): ...
def StopSpell(caster, spell_id): ...
def idempotent(func): ...

